// Archetypal Memory Types · 原型记忆类型
export interface ArchetypalMemoryType {
  id: string;
  name: string;
  userFriendlyName: string;
  description: string;
  strengths: string[];
  risks: string[];
  creativeUses: string[];
  lifePatternEchoes: string[];
  relatedEvents: string[];
  relatedWorldArchetypes: string[];
}

export const ARCHETYPAL_MEMORY_TYPES: ArchetypalMemoryType[] = [
  { id: "KING_RULER", name: "King / Ruler", userFriendlyName: "王者/统御者",
    description: "对秩序、统御与决断的深层熟悉。",
    strengths: ["决断力", "格局感"], risks: ["权力膨胀"],
    creativeUses: ["君主角色", "宫廷叙事"], lifePatternEchoes: ["反复处于决策位"],
    relatedEvents: ["治理", "权力转移"], relatedWorldArchetypes: ["FOUNDER_CITADEL_WORLD"] },
  { id: "WARRIOR", name: "General / Warrior", userFriendlyName: "将军/战士",
    description: "对战场、誓约与忠诚的强反应。",
    strengths: ["执行力", "纪律"], risks: ["对抗倾向"],
    creativeUses: ["战争小说", "纪律性角色"], lifePatternEchoes: ["危机中冷静"],
    relatedEvents: ["冲突", "守护"], relatedWorldArchetypes: ["ORDER_FORGE_WORLD"] },
  { id: "PRIEST_ORACLE", name: "Priest / Oracle", userFriendlyName: "祭司/预言者",
    description: "对仪式、象征与高位叙事的亲近。",
    strengths: ["象征感", "敏锐"], risks: ["神秘化"],
    creativeUses: ["祭仪世界", "神谕角色"], lifePatternEchoes: ["他人寻你解释意义"],
    relatedEvents: ["仪式", "启示"], relatedWorldArchetypes: ["MYTHIC_MAINLINE_WORLD"] },
  { id: "SCHOLAR_SCRIBE", name: "Scholar / Scribe", userFriendlyName: "学者/记录者",
    description: "对档案、文字与系统知识的本能依赖。",
    strengths: ["归档力"], risks: ["分析瘫痪"],
    creativeUses: ["图书馆世界"], lifePatternEchoes: ["反复整理"],
    relatedEvents: ["归档", "传承"], relatedWorldArchetypes: ["RECOVERY_SANCTUARY_WORLD"] },
  { id: "EXILE_WANDERER", name: "Exile / Wanderer", userFriendlyName: "流亡者/游历者",
    description: "对边界、迁徙与陌生地域的吸引。",
    strengths: ["适应力"], risks: ["难收尾"],
    creativeUses: ["游历叙事"], lifePatternEchoes: ["反复迁居"],
    relatedEvents: ["迁移"], relatedWorldArchetypes: ["CHAOS_NAVIGATION_WORLD"] },
  { id: "BUILDER_ARCHITECT", name: "Builder / Architect", userFriendlyName: "建造者/架构师",
    description: "对结构、地基、长期工程的偏爱。",
    strengths: ["系统感"], risks: ["过度规划"],
    creativeUses: ["城市/建筑设定"], lifePatternEchoes: ["反复搭建"],
    relatedEvents: ["创建", "扩展"], relatedWorldArchetypes: ["ORDER_FORGE_WORLD"] },
  { id: "ALCHEMIST", name: "Alchemist / Transformer", userFriendlyName: "炼金者/转化者",
    description: "对转化、配方、跨域整合的兴趣。",
    strengths: ["整合力"], risks: ["实验失控"],
    creativeUses: ["奇术体系"], lifePatternEchoes: ["反复重组"],
    relatedEvents: ["突变"], relatedWorldArchetypes: ["CREATION_STARFIELD_WORLD"] },
  { id: "HEALER", name: "Healer", userFriendlyName: "疗愈者",
    description: "对受伤、恢复与照护的天然敏感。",
    strengths: ["共情"], risks: ["自耗"],
    creativeUses: ["疗愈线"], lifePatternEchoes: ["他人向你求助"],
    relatedEvents: ["恢复"], relatedWorldArchetypes: ["RECOVERY_SANCTUARY_WORLD"] },
  { id: "TRICKSTER", name: "Trickster", userFriendlyName: "扰动者",
    description: "对规则缝隙、反讽与转向的偏好。",
    strengths: ["创意"], risks: ["失信"],
    creativeUses: ["反派/转折角色"], lifePatternEchoes: ["打破僵局"],
    relatedEvents: ["颠覆"], relatedWorldArchetypes: ["WIND_CONVERGENCE_WORLD"] },
  { id: "JUDGE", name: "Judge", userFriendlyName: "审判者",
    description: "对公正、衡量、裁决的强烈关注。",
    strengths: ["衡平"], risks: ["僵硬"],
    creativeUses: ["律法世界"], lifePatternEchoes: ["调解者"],
    relatedEvents: ["裁决"], relatedWorldArchetypes: ["ORDER_FORGE_WORLD"] },
  { id: "MESSENGER", name: "Messenger", userFriendlyName: "信使",
    description: "对传递、连接、跨界沟通的本能。",
    strengths: ["传播"], risks: ["失真"],
    creativeUses: ["使者角色"], lifePatternEchoes: ["天然中介"],
    relatedEvents: ["通讯"], relatedWorldArchetypes: ["WIND_CONVERGENCE_WORLD"] },
  { id: "FOUNDER", name: "Founder", userFriendlyName: "开创者",
    description: "对从零起手、奠基、开宗立派的牵引。",
    strengths: ["开拓"], risks: ["孤狼"],
    creativeUses: ["创世神话"], lifePatternEchoes: ["反复创业"],
    relatedEvents: ["奠基"], relatedWorldArchetypes: ["FOUNDER_CITADEL_WORLD"] },
  { id: "GUARDIAN", name: "Guardian", userFriendlyName: "守护者",
    description: "对边界、守护、长守一物的认同。",
    strengths: ["可靠"], risks: ["僵守"],
    creativeUses: ["守关角色"], lifePatternEchoes: ["守护他人"],
    relatedEvents: ["守护"], relatedWorldArchetypes: ["RECOVERY_SANCTUARY_WORLD"] },
  { id: "DESTROYER", name: "Destroyer", userFriendlyName: "破坏者",
    description: "对终结、清场、收束的内在拉力。",
    strengths: ["决断收束"], risks: ["破坏过度"],
    creativeUses: ["终末叙事"], lifePatternEchoes: ["清理者"],
    relatedEvents: ["终结"], relatedWorldArchetypes: ["CHAOS_NAVIGATION_WORLD"] },
  { id: "WIND_BEARER", name: "Wind-Bearer", userFriendlyName: "风之承载者",
    description: "对变化、流动、不可控的亲近。",
    strengths: ["顺势"], risks: ["飘忽"],
    creativeUses: ["风之神话"], lifePatternEchoes: ["反复转向"],
    relatedEvents: ["变化"], relatedWorldArchetypes: ["WIND_CONVERGENCE_WORLD"] },
  { id: "CIVILIZATION_SEED", name: "Civilization Seed", userFriendlyName: "文明种子",
    description: "对承载/重启文明的远景使命感。",
    strengths: ["长期愿景"], risks: ["过度神话化"],
    creativeUses: ["创世文明"], lifePatternEchoes: ["反复构建体系"],
    relatedEvents: ["奠基", "传承"], relatedWorldArchetypes: ["MYTHIC_MAINLINE_WORLD"] },
];
