export interface BreakthroughResistance {
  id: string;
  name: string;
  userFriendlyName: string;
  description: string;
  detectionSignals: string[];
  reductionActions: string[];
  validationMethod: string;
}

export const BREAKTHROUGH_RESISTANCES: BreakthroughResistance[] = [
  { id: "INFORMATION_MISSING", name: "Information Missing", userFriendlyName: "信息不足",
    description: "关键事实/数据缺失，无法判断方向。",
    detectionSignals: ["反复猜测","结论摇摆","无法举例"],
    reductionActions: ["补材料","问知情者","拉数据"],
    validationMethod: "能否一句话说清现状" },
  { id: "USER_UNCLEAR", name: "User Unclear", userFriendlyName: "用户不清",
    description: "不知道为谁做、谁会用。",
    detectionSignals: ["说不出3位真实用户","受众过宽"],
    reductionActions: ["写用户画像","找3位面谈"],
    validationMethod: "有真实姓名与场景" },
  { id: "VALUE_UNCLEAR", name: "Value Unclear", userFriendlyName: "价值不清",
    description: "讲不出独特价值。",
    detectionSignals: ["要素堆砌","对方无反应"],
    reductionActions: ["一句价值主张","对比替代方案"],
    validationMethod: "用户能复述价值" },
  { id: "RESOURCE_LACK", name: "Resource Lack", userFriendlyName: "资源不足",
    description: "时间/金钱/人手不够。",
    detectionSignals: ["持续疲劳","项目拖延"],
    reductionActions: ["缩范围","止损","拉合作"],
    validationMethod: "单元经济为正" },
  { id: "STRUCTURE_MISSING", name: "Structure Missing", userFriendlyName: "结构缺失",
    description: "没有流程/制度/标准。",
    detectionSignals: ["重复返工","责任模糊"],
    reductionActions: ["写步骤","定模板","加 SOP"],
    validationMethod: "新人能照做" },
  { id: "TIMING_NOT_READY", name: "Timing Not Ready", userFriendlyName: "时机不到",
    description: "外部窗口没开。",
    detectionSignals: ["反复试无反馈","环境不接"],
    reductionActions: ["等待","观察","小步测试"],
    validationMethod: "出现真实信号" },
  { id: "FIELD_NOT_SUPPORTIVE", name: "Field Not Supportive", userFriendlyName: "场域不支持",
    description: "平台/制度/地理不支持。",
    detectionSignals: ["合规阻断","曝光被压"],
    reductionActions: ["换场","调形式","等政策"],
    validationMethod: "在新场域获正反馈" },
  { id: "LANGUAGE_TOO_COMPLEX", name: "Language Too Complex", userFriendlyName: "语言过难",
    description: "术语过多，用户看不懂。",
    detectionSignals: ["新手卡退","解释要好几遍"],
    reductionActions: ["降术语","写示例","加图"],
    validationMethod: "1分钟理解第一步" },
  { id: "TRUST_GAP", name: "Trust Gap", userFriendlyName: "信任缺口",
    description: "对方不相信你/产品。",
    detectionSignals: ["不回复","只观望"],
    reductionActions: ["公开证据","加担保","小步合作"],
    validationMethod: "出现首笔承诺" },
  { id: "FEEDBACK_MISSING", name: "Feedback Missing", userFriendlyName: "反馈缺失",
    description: "没有回路。",
    detectionSignals: ["黑箱推进","自我说服"],
    reductionActions: ["建反馈入口","主动回访"],
    validationMethod: "稳定得到真实反馈" },
  { id: "ACTION_OVERLOAD", name: "Action Overload", userFriendlyName: "行动过载",
    description: "同时做太多事。",
    detectionSignals: ["每件半成品","切换疲劳"],
    reductionActions: ["砍清单","锁今日3件事"],
    validationMethod: "完成率显著上升" },
  { id: "NOISE_HIGH", name: "Noise High", userFriendlyName: "噪声过高",
    description: "信号被干扰。",
    detectionSignals: ["情绪起伏大","结论频繁推翻"],
    reductionActions: ["降信源","隔离设备"],
    validationMethod: "结论可稳定复述" },
  { id: "FALSE_SIGNAL", name: "False Signal", userFriendlyName: "伪信号",
    description: "把噪声当结论。",
    detectionSignals: ["孤立证据","选择性记忆"],
    reductionActions: ["回验","找反例"],
    validationMethod: "经独立来源印证" },
  { id: "EMOTIONAL_DISTORTION", name: "Emotional Distortion", userFriendlyName: "情绪扭曲",
    description: "情绪覆盖判断。",
    detectionSignals: ["极端措辞","身体紧绷"],
    reductionActions: ["延迟决策","写情绪日志"],
    validationMethod: "冷静后仍同结论" },
  { id: "SCOPE_DRIFT", name: "Scope Drift", userFriendlyName: "范围漂移",
    description: "目标越变越大。",
    detectionSignals: ["新功能不断加","截止日期推后"],
    reductionActions: ["回到MVP","冻结需求"],
    validationMethod: "范围文档不再变" },
  { id: "OVER_MYTHIFICATION", name: "Over Mythification", userFriendlyName: "过度神话化",
    description: "把结果讲成命运/神谕。",
    detectionSignals: ["绝对化用词","拒绝回验"],
    reductionActions: ["改回普通语言","加安全说明"],
    validationMethod: "经QA无绝对承诺" },
  { id: "SYSTEM_OVERGROWTH", name: "System Overgrowth", userFriendlyName: "系统膨胀",
    description: "系统过度复杂自缠。",
    detectionSignals: ["模块互相依赖","新功能困难"],
    reductionActions: ["归档","拆分","降耦合"],
    validationMethod: "新模块独立可上" },
  { id: "LEGAL_ADMIN_BLOCK", name: "Legal/Admin Block", userFriendlyName: "制度阻断",
    description: "法律/合规/制度阻断。",
    detectionSignals: ["合规警告","账号风险"],
    reductionActions: ["改合规形式","咨询专业"],
    validationMethod: "无合规风险通过" },
  { id: "BODY_LIMITATION", name: "Body Limitation", userFriendlyName: "身体限流",
    description: "身体能量不够。",
    detectionSignals: ["持续低能","睡眠差"],
    reductionActions: ["恢复","降负载"],
    validationMethod: "能量回到工作线" },
  { id: "SOCIAL_MISALIGNMENT", name: "Social Misalignment", userFriendlyName: "人群错位",
    description: "目标群体不对。",
    detectionSignals: ["叫好不叫座","错频沟通"],
    reductionActions: ["换人群","换渠道"],
    validationMethod: "新人群有真实转化" },
];

export const getResistance = (id: string) => BREAKTHROUGH_RESISTANCES.find((r) => r.id === id);
