export interface BreakthroughObjectType {
  id: string;
  name: string;
  userFriendlyName: string;
  defaultDomains: string[];
  commonGaps: string[];
  commonResistances: string[];
  commonActions: string[];
  commonValidationMethods: string[];
}

export const BREAKTHROUGH_OBJECT_TYPES: BreakthroughObjectType[] = [
  { id: "PERSON", name: "Person", userFriendlyName: "人",
    defaultDomains: ["human","spirit","heaven"],
    commonGaps: ["主权不清","承载不足","表达不足"],
    commonResistances: ["EMOTIONAL_DISTORTION","BODY_LIMITATION","INFORMATION_MISSING"],
    commonActions: ["守","等待","补材料"],
    commonValidationMethods: ["情绪稳定度","睡眠质量","行动落地率"] },
  { id: "PRODUCT", name: "Product", userFriendlyName: "产品",
    defaultDomains: ["earth","wind","human","spirit"],
    commonGaps: ["缺2","缺3","缺4"],
    commonResistances: ["USER_UNCLEAR","LANGUAGE_TOO_COMPLEX","FEEDBACK_MISSING"],
    commonActions: ["补流程","降术语","找用户"],
    commonValidationMethods: ["新手完成率","核心动作转化","留存"] },
  { id: "RELATIONSHIP", name: "Relationship", userFriendlyName: "关系",
    defaultDomains: ["human","spirit","wind"],
    commonGaps: ["缺2","缺3","缺6"],
    commonResistances: ["TRUST_GAP","EMOTIONAL_DISTORTION","FEEDBACK_MISSING"],
    commonActions: ["沟通","等待","守"],
    commonValidationMethods: ["回复率","主动接触","真实反馈"] },
  { id: "COMPANY", name: "Company", userFriendlyName: "公司",
    defaultDomains: ["earth","human","spirit","wind"],
    commonGaps: ["缺4","缺6","缺8"],
    commonResistances: ["RESOURCE_LACK","STRUCTURE_MISSING","SYSTEM_OVERGROWTH"],
    commonActions: ["补流程","止损","小步测试"],
    commonValidationMethods: ["现金流","留存","NPS"] },
  { id: "PROJECT", name: "Project", userFriendlyName: "项目",
    defaultDomains: ["heaven","earth","wind"],
    commonGaps: ["缺5","缺6","缺9"],
    commonResistances: ["SCOPE_DRIFT","RESOURCE_LACK","TIMING_NOT_READY"],
    commonActions: ["进","转","封存"],
    commonValidationMethods: ["里程碑达成","资源消耗比","用户反馈"] },
  { id: "CONTENT", name: "Content", userFriendlyName: "内容",
    defaultDomains: ["wind","spirit","human"],
    commonGaps: ["缺3","缺2","缺5"],
    commonResistances: ["LANGUAGE_TOO_COMPLEX","NOISE_HIGH","FALSE_SIGNAL"],
    commonActions: ["降噪","小步测试","发布"],
    commonValidationMethods: ["阅读量","收藏率","真实评论"] },
  { id: "PLATFORM", name: "Platform", userFriendlyName: "平台",
    defaultDomains: ["earth","wind","human"],
    commonGaps: ["缺4","缺2","缺6"],
    commonResistances: ["FIELD_NOT_SUPPORTIVE","SYSTEM_OVERGROWTH","LEGAL_ADMIN_BLOCK"],
    commonActions: ["守","观察","补材料"],
    commonValidationMethods: ["留存","承载稳定性","违规率"] },
  { id: "MARKET", name: "Market", userFriendlyName: "市场",
    defaultDomains: ["earth","wind","spirit"],
    commonGaps: ["缺5","缺8","缺9"],
    commonResistances: ["TIMING_NOT_READY","NOISE_HIGH","SOCIAL_MISALIGNMENT"],
    commonActions: ["观察","小步测试","等待"],
    commonValidationMethods: ["增长曲线","定价接受度","转化率"] },
  { id: "CITY", name: "City", userFriendlyName: "城市",
    defaultDomains: ["earth","human","wind"],
    commonGaps: ["缺6","缺2","缺4"],
    commonResistances: ["FIELD_NOT_SUPPORTIVE","RESOURCE_LACK","SOCIAL_MISALIGNMENT"],
    commonActions: ["观察","守","转"],
    commonValidationMethods: ["落地体感","社群质量","机会密度"] },
  { id: "SCHOOL_APPLICATION", name: "School Application", userFriendlyName: "升学申请",
    defaultDomains: ["heaven","earth","spirit"],
    commonGaps: ["缺4","缺3","缺7"],
    commonResistances: ["INFORMATION_MISSING","STRUCTURE_MISSING","TIMING_NOT_READY"],
    commonActions: ["补材料","沟通","小步测试"],
    commonValidationMethods: ["材料完成度","推荐人反馈","面试结果"] },
  { id: "CAREER_PATH", name: "Career Path", userFriendlyName: "职业路径",
    defaultDomains: ["heaven","human","spirit","wind"],
    commonGaps: ["缺1","缺9","缺8"],
    commonResistances: ["VALUE_UNCLEAR","SCOPE_DRIFT","EMOTIONAL_DISTORTION"],
    commonActions: ["守","转","等待"],
    commonValidationMethods: ["内驱稳定度","成果可见度","收入趋势"] },
  { id: "HEALTH_STATE", name: "Health", userFriendlyName: "身体状态",
    defaultDomains: ["human","earth","heaven"],
    commonGaps: ["缺6","缺0","缺7"],
    commonResistances: ["BODY_LIMITATION","INFORMATION_MISSING","ACTION_OVERLOAD"],
    commonActions: ["恢复","止损","观察"],
    commonValidationMethods: ["精力","睡眠","专业检查"] },
  { id: "COGNITIVE_STATE", name: "Cognition", userFriendlyName: "认知状态",
    defaultDomains: ["human","spirit","heaven"],
    commonGaps: ["缺7","缺0","缺3"],
    commonResistances: ["NOISE_HIGH","ACTION_OVERLOAD","EMOTIONAL_DISTORTION"],
    commonActions: ["降噪","等待","归档"],
    commonValidationMethods: ["专注时长","决策清晰度","睡眠"] },
  { id: "CREATIVE_WORK", name: "Creative Work", userFriendlyName: "创作作品",
    defaultDomains: ["spirit","wind","human"],
    commonGaps: ["缺3","缺5","缺2"],
    commonResistances: ["SCOPE_DRIFT","VALUE_UNCLEAR","FEEDBACK_MISSING"],
    commonActions: ["发布","小步测试","降噪"],
    commonValidationMethods: ["真实反馈","完成度","回看价值"] },
  { id: "VIRTUAL_WORLD", name: "Virtual World", userFriendlyName: "虚拟世界",
    defaultDomains: ["spirit","earth","wind"],
    commonGaps: ["缺4","缺9","缺2"],
    commonResistances: ["STRUCTURE_MISSING","OVER_MYTHIFICATION","SCOPE_DRIFT"],
    commonActions: ["补流程","归档","小步测试"],
    commonValidationMethods: ["世界一致性","用户沉浸","可叙述性"] },
  { id: "DEITY_OBJECT", name: "Deity Object", userFriendlyName: "神明对象",
    defaultDomains: ["spirit","heaven","human"],
    commonGaps: ["缺7","缺9","缺0"],
    commonResistances: ["OVER_MYTHIFICATION","FALSE_SIGNAL","EMOTIONAL_DISTORTION"],
    commonActions: ["观察","归档","等待"],
    commonValidationMethods: ["跨场景一致性","降噪后留存","行动启示"] },
  { id: "ORGANIZATION", name: "Organization", userFriendlyName: "组织",
    defaultDomains: ["human","earth","spirit"],
    commonGaps: ["缺4","缺2","缺1"],
    commonResistances: ["STRUCTURE_MISSING","SOCIAL_MISALIGNMENT","TRUST_GAP"],
    commonActions: ["补流程","沟通","守"],
    commonValidationMethods: ["成员留存","决策速度","落地率"] },
  { id: "CIVILIZATION", name: "Civilization", userFriendlyName: "文明",
    defaultDomains: ["heaven","earth","spirit","wind"],
    commonGaps: ["缺9","缺6","缺4"],
    commonResistances: ["SYSTEM_OVERGROWTH","OVER_MYTHIFICATION","LEGAL_ADMIN_BLOCK"],
    commonActions: ["观察","归档","守"],
    commonValidationMethods: ["长期一致性","传承度","容错度"] },
  { id: "SYSTEM", name: "System", userFriendlyName: "系统",
    defaultDomains: ["earth","wind","spirit"],
    commonGaps: ["缺4","缺7","缺6"],
    commonResistances: ["STRUCTURE_MISSING","SYSTEM_OVERGROWTH","NOISE_HIGH"],
    commonActions: ["重算","归档","补流程"],
    commonValidationMethods: ["回归通过率","SLA","用户反馈"] },
  { id: "UNKNOWN_OBJECT", name: "Unknown", userFriendlyName: "未知对象",
    defaultDomains: ["heaven","earth","human","spirit","wind"],
    commonGaps: ["缺0","缺7"],
    commonResistances: ["INFORMATION_MISSING","FALSE_SIGNAL"],
    commonActions: ["观察","补材料","等待"],
    commonValidationMethods: ["重复出现度","可命名性","可拆解性"] },
];

export const getBreakthroughObjectType = (id: string) =>
  BREAKTHROUGH_OBJECT_TYPES.find((t) => t.id === id) ?? BREAKTHROUGH_OBJECT_TYPES[BREAKTHROUGH_OBJECT_TYPES.length - 1];
