import type { EncyclopediaEntryType } from "./encyclopediaEntryTypes";
import type { EncyclopediaStatus } from "./encyclopediaStatusTypes";

export interface EncyclopediaEntry {
  id: string;
  title: string;
  aliases: string[];
  category: string;
  entryType: EncyclopediaEntryType;
  status: EncyclopediaStatus;
  shortDefinition: string;
  userFriendlyExplanation: string;
  professionalExplanation: string;
  founderExplanation?: string;
  whyItMatters: string;
  whereItAppears: string[];
  relatedModules: string[];
  relatedEntries: string[];
  safetyNotes: string[];
  exampleUsage: string[];
  userLanguageTerms: string[];
  technicalTerms: string[];
  versionIntroduced: string;
  founderOnly?: boolean;
}

const V1 = "v1.0";

// 工具：快速构造条目（减少重复样板）
const e = (
  id: string, title: string, category: string, entryType: EncyclopediaEntryType,
  status: EncyclopediaStatus,
  short: string, user: string, pro: string,
  opts: Partial<EncyclopediaEntry> = {},
): EncyclopediaEntry => ({
  id, title, category, entryType, status,
  aliases: opts.aliases ?? [],
  shortDefinition: short,
  userFriendlyExplanation: user,
  professionalExplanation: pro,
  founderExplanation: opts.founderExplanation,
  whyItMatters: opts.whyItMatters ?? "影响判断稳定性与下一步行动选择。",
  whereItAppears: opts.whereItAppears ?? [],
  relatedModules: opts.relatedModules ?? [],
  relatedEntries: opts.relatedEntries ?? [],
  safetyNotes: opts.safetyNotes ?? ["本产品为结构性预测辅助，不构成医疗/法律/金融/心理诊断建议。"],
  exampleUsage: opts.exampleUsage ?? [],
  userLanguageTerms: opts.userLanguageTerms ?? [],
  technicalTerms: opts.technicalTerms ?? [],
  versionIntroduced: opts.versionIntroduced ?? V1,
  founderOnly: opts.founderOnly,
});

export const ENCYCLOPEDIA_SEED_ENTRIES: EncyclopediaEntry[] = [
  // ===== 核心概念 =====
  e("aether-fate-engine", "以太命运引擎", "getting_started", "MODULE", "BETA",
    "结构化预测与决策辅助系统。",
    "它帮你判断当前的事到底「定没定」，给出可以观察 / 小步推进 / 暂停的行动建议。",
    "由主体模型、定数计算法、回验权重、事件宇宙、常数宇宙、Prompt Forge 等子系统组成的决策辅助操作系统。",
    { aliases: ["Aether", "Aether Fate Engine", "本产品"], whereItAppears: ["/", "/docs", "/onboarding"],
      relatedEntries: ["personal-decision-os", "demo-persona", "determination", "feedback-loop"],
      founderExplanation: "复杂预测操作系统，所有计算法都汇入此结构。" }),

  e("personal-decision-os", "个人决策辅助系统", "getting_started", "CONCEPT", "ACTIVE",
    "面向个人决策的辅助操作系统。", "它不替你做决定，只帮你看清当前的结构。",
    "以主体模型驱动的个人化决策辅助层，输出定数态与行动许可。",
    { aliases: ["Decision OS"], relatedEntries: ["aether-fate-engine", "action-permission"] }),

  e("time-window", "时间窗口", "core_concepts", "CONCEPT", "ACTIVE",
    "事件发生的较高概率时段。",
    "系统会标出这件事更可能发生的时间段，不是精确到某一刻。",
    "由触发因子、回验权重和事件阶段共同框定的概率高位窗口。",
    { aliases: ["Window", "时间段"], whereItAppears: ["/calendar", "/timeline"],
      relatedEntries: ["trigger-calendar", "event-stage"] }),

  e("trigger-calendar", "触发日历", "prediction_system", "PAGE", "ACTIVE",
    "按日呈现触发因子与高概率窗口。", "每天打开看一眼，哪几天事更容易发生。",
    "汇总触发因子、事件阶段、信号强度的日历视图。",
    { whereItAppears: ["/calendar"], relatedEntries: ["time-window", "prediction-detail"] }),

  e("prediction-detail", "预测详情", "prediction_system", "PAGE", "ACTIVE",
    "单个预测的完整结构。", "点开一条预测，看它为什么是这样、怎么用。",
    "展示信号、定数、行动许可、回验入口与相关事件的预测详情页。",
    { whereItAppears: ["/prediction/$date"], relatedEntries: ["determination", "action-permission"] }),

  e("determination", "定数", "core_concepts", "CONCEPT", "ACTIVE",
    "判断「这件事到底定没定」。",
    "系统会综合信号、时间、回验和事件类型，告诉你这件事是还没定、半定、还是已经基本定了。",
    "由信号质量、事件阶段、回验权重、时间窗口与行动许可综合输出的状态判断。",
    { aliases: ["定没定", "定数状态", "Determination"],
      relatedEntries: ["undetermined", "semi-determined", "near-determined", "determined", "reverse-determined", "false-determined", "action-permission", "determination-calculus"],
      whereItAppears: ["/prediction/$date", "/advanced-core"],
      founderExplanation: "多计算法收束层，避免预测结果碎片化。" }),

  e("undetermined", "未定", "core_concepts", "CONCEPT", "ACTIVE",
    "事情还没定，先观察。", "现在还没到结果，建议先观察、收集信息。",
    "信号未净化、时间窗口尚未对齐的状态。",
    { relatedEntries: ["determination", "signal-purification"] }),
  e("semi-determined", "半定", "core_concepts", "CONCEPT", "ACTIVE",
    "可以小步推进，保留撤回余地。", "可以试试看，但别一次梭哈。",
    "结构性趋势出现，但关键变量未确认。", { relatedEntries: ["determination"] }),
  e("near-determined", "接近已定", "core_concepts", "CONCEPT", "ACTIVE",
    "差最后一两个变量。", "基本能定了，再确认一下关键人物或时点。",
    "主要变量已收束，仅余 1-2 个未确认。", { relatedEntries: ["determination"] }),
  e("determined", "已定", "core_concepts", "CONCEPT", "ACTIVE",
    "结构基本确定，可以执行。", "结构稳定，可以按当前判断推进。",
    "信号、阶段、回验、时间窗口均收束。", { relatedEntries: ["determination"] }),
  e("reverse-determined", "反定", "core_concepts", "CONCEPT", "ACTIVE",
    "已经在向反方向收束。", "原来的方向不太行了，建议转向或止损。",
    "原假设被回验否定，结构反向收束。", { relatedEntries: ["determination"] }),
  e("false-determined", "假定", "core_concepts", "CONCEPT", "ACTIVE",
    "看起来定了，但其实是情绪/愿望。", "先停一停，把情绪净化掉再做判断。",
    "由情绪、愿望或恐惧驱动的伪收束态。",
    { relatedEntries: ["determination", "false-signal", "signal-purification"] }),

  e("action-permission", "行动许可", "core_concepts", "CONCEPT", "ACTIVE",
    "当前是否建议行动。", "系统会告诉你：可以做 / 谨慎 / 暂时别做。",
    "由定数态、信号许可、风险阈值组成的三态许可。",
    { aliases: ["YES/CAUTION/NO"], relatedEntries: ["determination", "signal-purification"] }),

  e("feedback-loop", "回验", "core_concepts", "CONCEPT", "ACTIVE",
    "事后告诉系统结果，让它更准。", "事情发生后，回来标一下结果，下次会更准。",
    "用真实结果回填模型，更新事件权重、定数权重与命中率。",
    { aliases: ["Feedback", "记录结果", "回填"], whereItAppears: ["/feedback"],
      relatedEntries: ["feedback-weight-calculus", "accuracy-goal"] }),

  e("signal", "信号", "core_concepts", "CONCEPT", "ACTIVE",
    "支持判断的有效输入。", "和这件事真正相关的可信线索。",
    "经过净化、未被噪声污染的输入向量。",
    { relatedEntries: ["noise", "false-signal", "signal-purification"] }),
  e("noise", "噪声", "core_concepts", "CONCEPT", "ACTIVE",
    "干扰判断的杂音。", "和这件事没关系，却让你以为有关系的东西。",
    "未达到显著性的随机扰动。", { relatedEntries: ["signal", "false-signal"] }),
  e("false-signal", "伪信号", "core_concepts", "CONCEPT", "ACTIVE",
    "看起来像信号，实际是噪声。", "情绪、愿望、巧合伪装成的信号。",
    "通过情绪/动机偏差产生的伪显著输入。", { relatedEntries: ["false-determined", "signal"] }),

  e("branch-collapse", "分支收束", "core_concepts", "CONCEPT", "ACTIVE",
    "可能性逐渐收敛到一两条主线。", "前面有很多可能，越往后剩的就越少。",
    "事件树的概率质量沿时间向少数分支收束。",
    { whereItAppears: ["/branch-collapse"], relatedEntries: ["determination", "resonance-lock"] }),

  e("event-stage", "事件阶段", "event_universe", "CONCEPT", "ACTIVE",
    "事件处于哪一段。", "刚萌芽 / 在发酵 / 在发生 / 已结束。",
    "事件的生命周期阶段：潜伏 / 起势 / 爆发 / 衰退。",
    { relatedEntries: ["event-universe", "event-manifestation"] }),
  e("event-manifestation", "事件表现形式", "event_universe", "CONCEPT", "ACTIVE",
    "事件可能长什么样。", "比如「资源流失」可能表现为意外支出、合作终止等。",
    "事件的可观察显现：subtle / typical / strong / falseManifestations。",
    { relatedEntries: ["event-universe"] }),

  // ===== 主体模型 =====
  e("demo-persona", "Demo Persona", "subject_models", "USER_MODE", "ACTIVE",
    "演示用的虚拟主体，无真实数据。", "默认进来用的「样板模型」，方便你先看看产品长什么样。",
    "完全脱敏的演示主体，与真实主体严格隔离。",
    { aliases: ["演示模型", "Demo"], relatedEntries: ["light-20", "full-60", "imported-subject", "demo-real-isolation"] }),
  e("light-20", "Light 20", "subject_models", "USER_MODE", "ACTIVE",
    "20 字段轻量真实模型。", "用最少的信息建一个属于你的轻量模型。",
    "20 字段主体，覆盖核心维度，不涉及高敏感字段。",
    { relatedEntries: ["demo-persona", "full-60"] }),
  e("full-60", "Full 60", "subject_models", "USER_MODE", "EXPERIMENTAL",
    "60 字段完整真实模型。", "更完整的个人模型，仅在你授权后使用，本地保存。",
    "60 字段主体，仅本地存储，受 Full 60 隐私规则约束。",
    { aliases: ["完整模型"], relatedEntries: ["full-60-privacy", "imported-subject"],
      safetyNotes: ["Full 60 仅本地存储，不上传服务器。", "你可以随时清除全部数据。"] }),
  e("imported-subject", "Imported Subject", "subject_models", "USER_MODE", "BETA",
    "从外部导入的主体。", "从 JSON 文件导入已有的模型。",
    "通过 JSON 导入并校验后注入运行时的主体。",
    { relatedEntries: ["full-60"] }),
  e("real-subject", "真实主体", "subject_models", "CONCEPT", "ACTIVE",
    "和 Demo 相对的真实你。", "和样板不一样，这是真正属于你的模型。",
    "Light 20 / Full 60 / Imported 统称的真实主体类。",
    { whereItAppears: ["/real-subject"], relatedEntries: ["demo-persona", "demo-real-isolation"] }),
  e("three-cycles", "三循环", "subject_models", "WORKFLOW", "BETA",
    "三轮闭环训练流程。", "通过三轮「输入-预测-回验」让模型逐步贴近你。",
    "Cycle 1 / 2 / 3 的三轮回验闭环。",
    { relatedEntries: ["cycle-1", "cycle-2", "cycle-3"] }),
  e("cycle-1", "Cycle 1", "subject_models", "WORKFLOW", "BETA",
    "第一轮：建立基线。", "先让系统认识你。", "采样、字段补全、初始定数。", { relatedEntries: ["three-cycles"] }),
  e("cycle-2", "Cycle 2", "subject_models", "WORKFLOW", "BETA",
    "第二轮：回验校准。", "用真实结果反馈，模型开始变准。", "权重更新、事件优先级修正。", { relatedEntries: ["three-cycles"] }),
  e("cycle-3", "Cycle 3", "subject_models", "WORKFLOW", "BETA",
    "第三轮：收束与定型。", "模型趋于稳定，预测开始可信。", "定数收束、命中率门槛达成。", { relatedEntries: ["three-cycles"] }),
  e("terminal-mode", "终端模式", "subject_models", "USER_MODE", "EXPERIMENTAL",
    "三循环结束后的稳定态。", "模型已经基本「认识」你，可以更稳定地预测。",
    "Cycle 3 完成后的稳态运行模式。", { relatedEntries: ["three-cycles"] }),
  e("wind-singularity", "风域奇点", "subject_models", "CONCEPT", "EXPERIMENTAL",
    "主体进入高速变化期的标记。", "你的人生节奏忽然加快的那个时点。",
    "风域常数突增、事件密度跨越阈值的奇点。",
    { relatedEntries: ["wind-domain", "five-domains"], founderOnly: false }),

  // ===== 常数宇宙 =====
  e("number-constants-09", "0–9 数字常数", "constant_universe", "CONSTANT", "ACTIVE",
    "0-9 每个数字的固定含义。", "每个数字在系统里都有固定意义，例如 5=变化/触发。",
    "NUMBER_CONSTANTS 表，10 个数字的核心含义与正/反向表现。",
    { whereItAppears: ["/constants", "/constants-universe"], relatedEntries: ["constant-universe-calculus"] }),
  e("five-domains", "五域", "constant_universe", "CONSTANT", "ACTIVE",
    "天 / 地 / 人 / 神 / 风 五大域。", "把事情划分成五个领域，方便比较。",
    "FIVE_DOMAIN_CONSTANTS，主导域分配维度权重。",
    { relatedEntries: ["heaven-domain", "earth-domain", "human-domain", "spirit-domain", "wind-domain"] }),
  e("heaven-domain", "天域", "constant_universe", "CONSTANT", "ACTIVE",
    "时机与势能。", "和「时机到没到」相关的那一类事。",
    "Heaven domain：时机、势能、外部宏观因子。", { relatedEntries: ["five-domains"] }),
  e("earth-domain", "地域", "constant_universe", "CONSTANT", "ACTIVE",
    "资源与基础。", "和「资源够不够」相关的事。",
    "Earth domain：资源、基础、物理环境。", { relatedEntries: ["five-domains"] }),
  e("human-domain", "人域", "constant_universe", "CONSTANT", "ACTIVE",
    "关系与协作。", "和「人和人之间」相关的事。",
    "Human domain：关系、协作、社会网络。", { relatedEntries: ["five-domains"] }),
  e("spirit-domain", "神域", "constant_universe", "CONSTANT", "ACTIVE",
    "象征与长期价值。", "和「意义/精神/长期价值」相关的事。",
    "Spirit domain：象征、长期价值、信念结构。", { relatedEntries: ["five-domains"] }),
  e("wind-domain", "风域", "constant_universe", "CONSTANT", "ACTIVE",
    "变化与流动。", "和「忽然变化、风口」相关的事。",
    "Wind domain：变化、流动、突变因子。", { relatedEntries: ["five-domains", "wind-singularity"] }),
  e("multiply-divide-operators", "乘除算子", "constant_universe", "CONSTANT", "ACTIVE",
    "×N 放大 / ÷N 削弱。", "系统用 × 和 ÷ 来表示某个维度被加强或削弱。",
    "MULTIPLY_OPERATORS / DIVIDE_OPERATORS：1-10 倍率算子。",
    { relatedEntries: ["constant-universe-calculus"] }),
  e("twelve-life-phases", "十二长生", "constant_universe", "CONSTANT", "ACTIVE",
    "时间相位 12 阶段。", "把时间分成 12 个阶段，看事情处在哪一段。",
    "TIME_PHASE_CONSTANTS：十二长生相位映射事件阶段。",
    { relatedEntries: ["event-stage"] }),
  e("feedback-constants", "回验常数", "constant_universe", "CONSTANT", "ACTIVE",
    "回验权重的统一基准。", "系统计算「事后准不准」用的统一参数。",
    "FEEDBACK_OUTCOME_WEIGHTS / TIMING_WEIGHTS / BIAS_FLAGS。",
    { relatedEntries: ["feedback-weight-calculus"] }),
  e("platform-constants", "平台常数", "constant_universe", "CONSTANT", "BETA",
    "各平台的流量与权重参数。", "比如小红书、微信等平台的流量池系数。",
    "PLATFORM_CONSTANTS：平台流量池/算法权重表。",
    { relatedEntries: ["xiaohongshu-heat-calculus"] }),
  e("physical-reality-phase-c", "物理现实常数 Phase C", "constant_universe", "CONSTANT", "PLACEHOLDER",
    "天文/生物/环境等物理因子接口。", "未来会接入真实世界的物理数据，目前是占位。",
    "PHYSICAL_REALITY_CONSTANTS：天文、生物、地磁等占位接口。",
    { relatedEntries: ["constant-universe-calculus"], safetyNotes: ["当前为 Phase C 占位接口，不参与预测计算。"] }),

  // ===== 计算法 =====
  e("determination-calculus", "定数计算法", "calculus_engines", "CALCULUS", "ACTIVE",
    "输出定数态的核心算法。", "决定「定没定」的那个算法。",
    "综合信号、阶段、回验、时间窗口，输出 DeterminationStatus。",
    { relatedEntries: ["determination"] }),
  e("feedback-weight-calculus", "回验权重计算法", "calculus_engines", "CALCULUS", "ACTIVE",
    "根据回验结果调整权重。", "每次回验都会让系统更聪明。",
    "feedbackWeightEngine：基于结果/时序/偏差更新权重。",
    { relatedEntries: ["feedback-loop", "feedback-constants"] }),
  e("real-subject-calculus", "真实用户主体计算法", "calculus_engines", "CALCULUS", "ACTIVE",
    "真实主体的运行算法。", "把你的真实模型跑起来的那个引擎。",
    "realSubjectCalculus：Light 20 / Full 60 / Imported 主体推理。",
    { relatedEntries: ["real-subject"] }),
  e("regional-ux-calculus", "地区用户体验计算法", "calculus_engines", "CALCULUS", "BETA",
    "不同地区的体验偏好。", "在不同地区，文案、风险提示会自动调整。",
    "regionalUserCalculus：region preset → copywriting/risk tone。",
    { relatedEntries: ["regional-ux"] }),
  e("ui-fit-calculus", "多用户端 UI 适评算法", "calculus_engines", "CALCULUS", "BETA",
    "不同设备的 UI 适配评估。", "看在手机/平板/桌面上是不是都好用。",
    "multiClientUIFitEngine：device × role × density 评分。",
    { whereItAppears: ["/ui-fit"] }),
  e("language-fit-calculus", "产品与用户语言计算法", "calculus_engines", "CALCULUS", "BETA",
    "把高阶术语翻译成用户语言。", "看哪些字普通用户读起来太难。",
    "productUserLanguageEngine：jargon detection + rewrite。",
    { whereItAppears: ["/language-fit"], relatedEntries: ["user-language"] }),
  e("onboarding-simplification-calculus", "入门使用流程简化计算法", "calculus_engines", "CALCULUS", "BETA",
    "评估新手流程是否够顺。", "看新人能不能 1 分钟入门。",
    "onboardingSimplificationEngine：friction × steps × clarity。",
    { whereItAppears: ["/onboarding"], relatedEntries: ["beginner-mode"] }),
  e("software-qa-calculus", "软件测试反馈计算法", "calculus_engines", "CALCULUS", "ACTIVE",
    "扫描产品健康度。", "自动巡检：哪个模块不健康、哪条路由坏了。",
    "softwareQAFeedbackCalculus：路由/模块/数据/隔离/安全/回验/文档扫描。",
    { whereItAppears: ["/software-qa"] }),
  e("global-recalc-calculus", "总重新计算算法", "calculus_engines", "CALCULUS", "ACTIVE",
    "一键重算所有关联模块。", "改了重要的东西后，让系统全面重新计算一次。",
    "globalRecalculationEngine：scope × trigger × dependency。",
    { whereItAppears: ["/recalculation"] }),
  e("prediction-dimension-engine", "预测维度与事件算法", "calculus_engines", "CALCULUS", "ACTIVE",
    "15 维度 × 事件库的预测引擎。", "把 15 类事和事件库连起来生成预测。",
    "predictionDimensionEngine + eventAlgorithmEngine。",
    { whereItAppears: ["/prediction-dimensions", "/event-algorithms"] }),
  e("abstract-transfer-prompt-calculus", "抽象迁移化提示词计算法", "calculus_engines", "CALCULUS", "BETA",
    "把一类问题的提示词迁移到另一类。", "把「预测」的提示词，自动改成「文档」「营销」的提示词。",
    "abstractTransferPromptCalculus：domain → domain mapping。",
    { whereItAppears: ["/abstract-prompt-forge"] }),
  e("event-dedup-completion-calculus", "事件库查重补全计算法", "calculus_engines", "CALCULUS", "ACTIVE",
    "查重 + 字段补全。", "防止事件重复，补齐缺字段。",
    "eventDeduplicationEngine + eventCompletionEngine。", { whereItAppears: ["/event-library-audit"] }),
  e("event-bulk-completion-calculus", "事件库批量施工计算法", "calculus_engines", "CALCULUS", "ACTIVE",
    "一次性批量补全事件库。", "一次搬一面墙，不是一次搬一块砖。",
    "eventLibraryBulkCompletion：dimension floor + manifestation tiers。",
    { founderOnly: false }),
  e("founder-calculus", "创始人计算法", "calculus_engines", "CALCULUS", "LOCKED",
    "创始人模式的判定与切换。", "决定谁能进入创始人控制台。",
    "founderCalculus：role/permission/session 收束。", { founderOnly: true, relatedEntries: ["founder-mode"] }),
  e("founder-password-calculus", "创始人密码计算法", "calculus_engines", "CALCULUS", "LOCKED",
    "本地密码哈希校验。", "在你的设备上保护创始人入口的密码算法。",
    "PBKDF2-SHA256 120k 本地哈希。", { founderOnly: true, relatedEntries: ["founder-mode"] }),
  e("founder-permission-calculus", "创始人权限计算法", "calculus_engines", "CALCULUS", "LOCKED",
    "按模块风险分配权限。", "决定不同等级的创始人能动哪些模块。",
    "founderPermissionCalculus：role × module riskLevel。", { founderOnly: true }),
  e("constant-universe-calculus", "常数宇宙计算法", "calculus_engines", "CALCULUS", "ACTIVE",
    "统一常数中心。", "所有计算法都从同一个常数中心读参数。",
    "constantUniverseEngine：9 大常数组的统一来源。",
    { whereItAppears: ["/constants-universe"], relatedEntries: ["number-constants-09", "five-domains"] }),
  e("xiaohongshu-heat-calculus", "小红书热度计算法", "marketing", "CALCULUS", "EXPERIMENTAL",
    "评估小红书内容热度潜力。", "看一条笔记在小红书上会不会火。",
    "通过曝光池/互动率/标签匹配预估热度。",
    { relatedEntries: ["platform-constants", "product-fame-calculus"] }),
  e("product-fame-calculus", "产品知名度计算法", "marketing", "CALCULUS", "EXPERIMENTAL",
    "评估产品知名度成长。", "看产品在外面有多少人知道。",
    "Brand mention × platform weight × time decay。",
    { relatedEntries: ["xiaohongshu-heat-calculus"] }),
  e("platform-weight-calculus", "平台权重计算法", "marketing", "CALCULUS", "EXPERIMENTAL",
    "不同平台的权重分配。", "每个平台占的份量不同。",
    "Per-platform weight in fame & distribution。", { relatedEntries: ["platform-constants"] }),

  // ===== 事件与预测 =====
  e("prediction-dimensions-15", "15预测维度", "event_universe", "CONCEPT", "ACTIVE",
    "15 类预测范围。", "事业、关系、财务等 15 个大类。",
    "PREDICTION_DIMENSIONS：15 个 dimension × 多事件。",
    { whereItAppears: ["/prediction-dimensions"] }),
  e("event-universe", "事件宇宙", "event_universe", "MODULE", "ACTIVE",
    "事件库整体。", "系统所知的所有事件类型。",
    "全部事件算法的集合，含主/副/风险事件。",
    { whereItAppears: ["/event-algorithms"], relatedEntries: ["main-event", "sub-event", "risk-event"] }),
  e("main-event", "主事件", "event_universe", "EVENT", "ACTIVE",
    "维度内的核心事件。", "这一类里最有代表性的事。", "Dimension 内 primary event。", { relatedEntries: ["event-universe"] }),
  e("sub-event", "副事件", "event_universe", "EVENT", "ACTIVE",
    "主事件下的子事件。", "围绕主事件出现的小事。", "parentEventId 指向 main 的子事件。", { relatedEntries: ["main-event"] }),
  e("risk-event", "风险事件", "event_universe", "EVENT", "ACTIVE",
    "可能带来风险的事件。", "需要提前警惕的那一类事。", "标记 riskSignals 的事件类型。", { relatedEntries: ["false-signal"] }),
  e("event-feedback", "事件回验", "feedback_accuracy", "WORKFLOW", "ACTIVE",
    "对某事件的事后标注。", "标一下这个事件最后到底有没有发生。",
    "事件粒度的 outcome 标注。", { whereItAppears: ["/feedback"], relatedEntries: ["feedback-loop"] }),
  e("event-priority", "事件优先级", "event_universe", "CONCEPT", "ACTIVE",
    "事件的重要度排序。", "哪个事先看、哪个事可以忽略。",
    "由权重 × 信号 × 风险计算的优先级。", { relatedEntries: ["event-universe"] }),

  // ===== 产品运行 =====
  e("prompt-forge", "Prompt Forge", "prompt_forge", "MODULE", "ACTIVE",
    "AI 提示词生成器。", "帮你生成给 Lovable / AI 的指令。",
    "promptCalculus：power × type × stance。", { whereItAppears: ["/prompt-forge"] }),
  e("abstract-prompt-forge", "Abstract Prompt Forge", "prompt_forge", "MODULE", "BETA",
    "抽象迁移版提示词。", "把一类提示词模板迁移到别的领域。",
    "abstractTransferPromptCalculus 入口。", { whereItAppears: ["/abstract-prompt-forge"] }),
  e("product-docs", "Product Docs", "product_ops", "MODULE", "ACTIVE",
    "产品文档中心。", "可以连续阅读的产品手册。", "章节树 + 术语表 + 回链。", { whereItAppears: ["/docs"], relatedEntries: ["aether-fate-engine-encyclopedia"] }),
  e("software-qa", "Software QA", "product_ops", "MODULE", "ACTIVE",
    "软件测试反馈中心。", "自动检查产品健康度。", "softwareQAFeedbackCalculus 控制台。",
    { whereItAppears: ["/software-qa"] }),
  e("recalculation-center", "Recalculation Center", "product_ops", "MODULE", "ACTIVE",
    "总重算控制台。", "改了底层后一键全面重算。", "globalRecalculationEngine 入口。",
    { whereItAppears: ["/recalculation"] }),
  e("version-iteration", "Version Iteration", "product_ops", "MODULE", "ACTIVE",
    "版本迭代评估。", "看现在的版本能不能内测。",
    "versionIterationCalculus：readiness × risk。", { whereItAppears: ["/version-iteration"] }),
  e("beta-launch", "Beta Launch", "product_ops", "MODULE", "ACTIVE",
    "内测发布计算器。", "看现在能不能开内测。",
    "betaLaunchCalculus：access × segment × risk。", { whereItAppears: ["/beta-launch"] }),
  e("founder-console", "Founder Console", "founder_mode", "MODULE", "LOCKED",
    "创始人控制台。", "只有创始人模式下能看到的高阶面板。",
    "FounderConsolePanel：系统总览 + 高风险操作。",
    { whereItAppears: ["/founder-console"], founderOnly: true, relatedEntries: ["founder-mode"] }),

  // ===== 用户体验 =====
  e("beginner-mode", "Beginner Mode", "ux_language", "USER_MODE", "ACTIVE",
    "新手模式。", "默认开启，只显示必要的入口和最简单的语言。",
    "isBeginnerMode：UI 折叠 + 术语降密。", { relatedEntries: ["onboarding-simplification-calculus"] }),
  e("demo-first", "Demo First", "ux_language", "WORKFLOW", "ACTIVE",
    "默认先用 Demo。", "第一次进来用 Demo 模型，避免上来就要填资料。",
    "Demo persona 默认激活。", { relatedEntries: ["demo-persona"] }),
  e("user-language", "用户语言", "ux_language", "CONCEPT", "ACTIVE",
    "普通用户能懂的说法。", "把术语翻译成你听得懂的话。",
    "low-jargon copywriting layer。", { relatedEntries: ["language-fit-calculus"] }),
  e("enterprise-safety-language", "企业安全语言", "ux_language", "CONCEPT", "BETA",
    "面向企业/B端的稳健文案。", "更保守、更稳健的说法，适合给团队/客户看。",
    "Enterprise tone preset for risk-sensitive copy.", { relatedEntries: ["user-language"] }),
  e("mobile-simplification", "移动端简化", "ux_language", "CONCEPT", "BETA",
    "手机上的精简界面。", "在手机上自动隐藏复杂模块。",
    "Mobile breakpoint UI fold rules。", { relatedEntries: ["ui-fit-calculus"] }),

  // ===== 安全与边界 =====
  e("safety-boundary", "Safety Boundary", "safety_boundary", "SAFETY_RULE", "ACTIVE",
    "安全边界。", "本产品不构成医疗/法律/金融/投资/心理诊断建议。",
    "SAFETY_BOUNDARY_RULES：分页 × 严重度的免责文案。",
    { whereItAppears: ["所有预测/决策类页面"],
      safetyNotes: ["不构成医疗建议。", "不构成法律建议。", "不构成金融/投资建议。", "不构成心理诊断。"] }),
  e("demo-real-isolation", "Demo/Real 隔离", "safety_boundary", "SAFETY_RULE", "ACTIVE",
    "演示与真实严格隔离。", "Demo 数据永远不会污染你的真实模型，反之亦然。",
    "DEMO_REAL_ISOLATION_RULES：双向不可写。",
    { relatedEntries: ["demo-persona", "real-subject"] }),
  e("full-60-privacy", "Full 60 隐私", "safety_boundary", "SAFETY_RULE", "EXPERIMENTAL",
    "Full 60 仅本地存储。", "你的完整模型只在你的设备上，可以随时清除。",
    "Full 60 受 local-only 保护，不上传服务器。",
    { relatedEntries: ["full-60"] }),
  e("accuracy-goal", "准确率目标", "feedback_accuracy", "CONCEPT", "BETA",
    "理论命中率目标，需要回验。", "目前的命中率目标还需要更多回验来证实。",
    "Accuracy goal subject to sample limits & calibration.",
    { whereItAppears: ["/accuracy"], safetyNotes: ["命中率受样本限制；不是单次预测的保证。"] }),

  // ===== 入门 / 流程 =====
  e("one-minute-onboarding", "新手 1 分钟流程", "getting_started", "WORKFLOW", "ACTIVE",
    "1 分钟跑通主流程。", "用 Demo 看一次预测、回验一次、读一条文档。",
    "Demo → Prediction Detail → Feedback → Doc。",
    { whereItAppears: ["/onboarding"], relatedEntries: ["beginner-mode", "demo-first"] }),

  // ===== 高阶 / 研究 =====
  e("calculus-universe-encyclopedia", "计算法宇宙百科", "advanced_research", "MODULE", "EXPERIMENTAL",
    "Aetherworld 所有计算法、引擎计算逻辑、对象生成逻辑、世界生成逻辑与系统治理逻辑的总索引。",
    "计算法宇宙不是单个算法，而是把 Aetherworld 里所有「如何判断、如何生成、如何解释、如何运行、如何回验」的方法统一登记成一个宇宙级方法库。下方按 A 数列基础 / B 主体与创始人 / C 对象与万物 / D 生成 / E 世界与虚拟生活 / F 系统治理 / G 质量回验 / H 价值资源 / I 数字科学 / J 神话象征 十大分类索引所有条目。",
    "计算法宇宙是 Aetherworld 的元计算法注册系统，用于统一管理数列计算法、主体计算法、世界计算法、模型计算法、文本计算法、声乐计算法、翻译计算法、UI 计算法、常数计算法、宪法计算法、回验计算法与版本跃迁计算法。它通过 Calculus Registry 对每个计算法登记 id / 中英文名 / 分类 / 输入输出 / 关联引擎 / 示例 / 安全边界 / 成熟度，并对外暴露分类筛选、搜索、Founder 锁定与缺失检测能力。",
    { aliases: ["Calculus Universe Encyclopedia", "计算法总百科", "Calculus Registry"],
      whereItAppears: ["/encyclopedia-entry?id=calculus-universe-encyclopedia"],
      whyItMatters: "它是 Aetherworld 所有“怎么算”的总目录，决定模型生成、世界推演、文案更新、版本跃迁、回验权重的统一来源，是治理一致性的根。",
      safetyNotes: [
        "计算法宇宙是结构化推演与产品内部生成系统，不等于现实宇宙定律。",
        "不构成医疗、法律、金融、心理诊断或工程安全建议。",
        "数列货币与虚拟资产估值仅在产品内部生效，不构成现实金融工具或投资建议。",
        "Founder-only 计算法不暴露给普通用户。",
      ],
      exampleUsage: [
        "在 Free Input 中先调用「万物本身计算法」识别对象本体。",
        "在 /text-dynamic-update 中由「文本动态更新计算法」扫描 stale 文案。",
        "在 /version-leap 中由「版本跃迁计算法」给出 leap 等级与发布就绪检查。",
      ],
      technicalTerms: ["Calculus Registry", "Maturity", "Engine Binding", "Stale Detection", "Founder Gating"],
      relatedEntries: [
        "mother-sequence-language", "constant-universe", "system-constitution",
        "sequence-ai", "sequence-terminal", "world-engine", "world-simulation",
        "world-growth", "world-society", "civilization-evolution", "world-presentation",
        "sequence-currency", "hybrid-compression", "ui-update-engine",
        "text-dynamic-update-engine", "learning-docs-engine", "version-leap-engine",
        "software-qa", "recalculation", "nine-core-persona",
        "determination-calculus", "feedback-weight-calculus", "zb-cognitive-unit",
        "brain-recovery-calculus", "brain-plasticity-calculus",
      ],
      founderExplanation: "Calculus Universe 是治理总线：所有引擎都应在此登记 calculus，未登记的隐式逻辑视为债务。" }),
  e("zb-cognitive-unit", "zb认知结构单位", "advanced_research", "CONCEPT", "EXPERIMENTAL",
    "认知结构的最小单元。", "把人的认知拆成可比较的最小颗粒。",
    "zb-unit：认知结构的最小可比较单元。", { safetyNotes: ["研究态概念，不用于临床判断。"] }),
  e("brain-recovery-calculus", "大脑恢复计算法", "advanced_research", "CALCULUS", "EXPERIMENTAL",
    "评估大脑恢复程度。", "看大脑现在恢复到什么阶段。",
    "Brain recovery scoring model (research)。",
    { safetyNotes: ["不构成医疗诊断；研究态。"] }),
  e("brain-plasticity-calculus", "大脑可塑性计算法", "advanced_research", "CALCULUS", "EXPERIMENTAL",
    "评估大脑可塑性窗口。", "看大脑现在还能不能重塑。",
    "Plasticity window estimator (research)。",
    { safetyNotes: ["不构成医疗诊断；研究态。"] }),

  // ===== 创始人模式 =====
  e("founder-mode", "Founder Mode", "founder_mode", "USER_MODE", "LOCKED",
    "创始人模式。", "本地高阶模式，普通用户不可见。",
    "Founder session + role + permission 三件套。",
    { founderOnly: false, relatedEntries: ["founder-password", "founder-permission"],
      safetyNotes: ["这是本地保护，不是服务器级安全；只能阻挡日常误操作。"] }),
  e("founder-password", "Founder Password", "founder_mode", "CONCEPT", "LOCKED",
    "本地创始人密码。", "在你的设备上保护创始人入口。",
    "PBKDF2-SHA256 本地哈希；不上传。", { relatedEntries: ["founder-mode"] }),
  e("founder-permission", "Founder Permission", "founder_mode", "CONCEPT", "LOCKED",
    "创始人权限等级。", "不同等级能动的模块不一样。",
    "5 级 role × 模块 riskLevel 矩阵。", { relatedEntries: ["founder-mode"] }),

  // ===== 百科自身 =====
  e("aether-fate-engine-encyclopedia", "产品百科全书", "getting_started", "MODULE", "BETA",
    "可搜索、分类、分层阅读的知识库。", "想查一个词、一个模块、一个计算法，先来这里。",
    "Aether Fate Engine Encyclopedia：concept × module × calculus × constant × event × safety 的统一知识库。",
    { aliases: ["Encyclopedia", "百科全书", "产品百科"], whereItAppears: ["/encyclopedia"],
      relatedEntries: ["product-docs", "aether-fate-engine"] }),
];

export const SEED_ENTRY_COUNT = ENCYCLOPEDIA_SEED_ENTRIES.length;
