// 事件现实表现形式
export interface EventManifestation {
  eventId: string;
  subtle: string[];      // 轻微信号
  typical: string[];     // 中等信号
  strong: string[];      // 强信号
  falseSignals: string[]; // 假信号
}

export const EVENT_MANIFESTATIONS: EventManifestation[] = [
  { eventId: "CAREER_OPENING",
    subtle: ["旧同事偶然点赞", "招聘信息推送增多"],
    typical: ["有人询问项目", "面试/申请推进", "外部评价变正"],
    strong: ["收到合作消息", "出现正式回复", "旧项目重新有机会"],
    falseSignals: ["猎头泛泛而问", "无具体岗位描述"] },
  { eventId: "PRODUCT_RELEASE_WINDOW",
    subtle: ["内测用户主动询问进度"],
    typical: ["Demo 可解释", "功能形成闭环", "Prompt 可复用"],
    strong: ["回验数据开始积累", "内测用户提出有效反馈"],
    falseSignals: ["短期点击高但无回验", "Demo/Real 数据混淆"] },
  { eventId: "RELATIONSHIP_WARMING",
    subtle: ["语气变柔和", "出现试探"],
    typical: ["主动联系", "聊天频率增加", "发送私人内容"],
    strong: ["线下见面机会", "语音/视频"],
    falseSignals: ["群发式问候", "酒后/情绪化主动"] },
  { eventId: "HEALTH_RECOVERY_UP",
    subtle: ["疲劳恢复变快"],
    typical: ["睡眠质量提升", "运动欲增强", "情绪噪声下降"],
    strong: ["认知清晰度上升", "性欲/行动欲恢复"],
    falseSignals: ["咖啡因/兴奋剂带来的假性恢复"] },
  { eventId: "COGNITIVE_BOOST",
    subtle: ["旧结构重新连通"],
    typical: ["新计算法生成", "外化速度加快"],
    strong: ["判断压缩能力增强", "多线程承载提高"],
    falseSignals: ["短期亢奋后多巴胺崩"] },
  { eventId: "PRODUCT_ACTIVATION",
    subtle: ["朋友愿意点开 Demo"],
    typical: ["用户主动停留", "复访"],
    strong: ["收到主动反馈", "用户复用提示词"],
    falseSignals: ["一次性流量", "无回验点击"] },
  { eventId: "RESOURCE_INFLOW",
    subtle: ["小额订单", "推荐线索"],
    typical: ["合同推进", "进账信号"],
    strong: ["资金到账", "长期客户"],
    falseSignals: ["口头承诺", "无书面"] },
  { eventId: "RELATIONSHIP_COOLING",
    subtle: ["回复变慢"],
    typical: ["主动减少", "话题变浅"],
    strong: ["明确疏远", "拒绝邀约"],
    falseSignals: ["对方在忙的短期沉默"] },
  { eventId: "HUMAN_VARIABLE_APPEARS",
    subtle: ["弱连接评论"],
    typical: ["旧友联系", "新人物加入会话"],
    strong: ["关键人推动具体事"],
    falseSignals: ["无后续的客套寒暄"] },
  { eventId: "CHAOS_RISK",
    subtle: ["小冲突", "信息混乱"],
    typical: ["意外延迟", "误解"],
    strong: ["突发危机", "复合冲突"],
    falseSignals: ["焦虑投射", "灾难化想象"] },
  { eventId: "FALSE_SIGNAL_EVENT",
    subtle: ["梦境/直觉投射"],
    typical: ["巧合堆叠", "无来源消息"],
    strong: ["看似显著但无人确认"],
    falseSignals: ["全部均为伪信号"] },

  // —— 以下为字段补全（不新增事件，仅补 falseSignals/manifestations）——
  { eventId: "CAREER_BLOCKED",
    subtle: ["邮件回复变慢"],
    typical: ["项目反复延期", "对方推诿"],
    strong: ["明确取消", "长期无回应"],
    falseSignals: ["对方节假日导致的短期沉默", "自我焦虑放大的延迟感"] },
  { eventId: "PRODUCT_ITERATION",
    subtle: ["内部讨论增多"],
    typical: ["新版本草稿", "QA 列表收敛"],
    strong: ["发布候选版本", "回验闭环建立"],
    falseSignals: ["改了很多但目标飘移", "重构假象掩盖核心问题"] },
  { eventId: "RESOURCE_DRAIN",
    subtle: ["小额支出增多"],
    typical: ["现金流持续紧张", "应付增多"],
    strong: ["核心资源被抽走", "断流"],
    falseSignals: ["一次性大额非经常支出", "记账口径变化造成的错觉"] },
  { eventId: "MONEY_PRESSURE",
    subtle: ["对消费犹豫"],
    typical: ["账单集中到期", "需挪用储备"],
    strong: ["现金缺口出现", "需借入"],
    falseSignals: ["心理紧张但账面其实有余", "对比他人造成的相对剥夺感"] },
  { eventId: "RELATIONSHIP_CONFIRMATION",
    subtle: ["双方话题更具体"],
    typical: ["共同计划", "公开关系信号"],
    strong: ["明确表达", "对外宣布"],
    falseSignals: ["酒后承诺", "为安抚对方说出的口头确认"] },
  { eventId: "RELATIONSHIP_DISTORTION",
    subtle: ["你反复揣测对方意图"],
    typical: ["把模糊行为解释成强信号"],
    strong: ["基于想象采取行动"],
    falseSignals: ["对方一句普通问候被读成示好", "夜间情绪化解读"] },
  { eventId: "HUMAN_VARIABLE_MISSING",
    subtle: ["关键人物长时间不出现"],
    typical: ["无人推进", "找不到对接人"],
    strong: ["项目因缺人停摆"],
    falseSignals: ["对方只是暂时不在线", "你联系的不是真正的关键人"] },
  { eventId: "STUDY_SIGNAL",
    subtle: ["官网/系统状态变化"],
    typical: ["教授/校方回复", "材料推进"],
    strong: ["面试邀请", "正式更新"],
    falseSignals: ["自动群发邮件", "系统状态刷新但内容未变"] },
  { eventId: "APPLICATION_RESPONSE",
    subtle: ["状态字段变更"],
    typical: ["收到正式邮件"],
    strong: ["录取/拒信/Waitlist"],
    falseSignals: ["钓鱼/诈骗邮件", "未署名的非正式回复"] },
  { eventId: "HEALTH_OVERLOAD",
    subtle: ["入睡变难"],
    typical: ["持续疲劳", "情绪起伏大"],
    strong: ["生理症状出现", "需要强制休息"],
    falseSignals: ["短期熬夜造成的疲劳", "天气/气压引起的不适"] },
  { eventId: "COGNITIVE_LIMITING",
    subtle: ["读长文耐心下降"],
    typical: ["判断变慢", "输出阻滞"],
    strong: ["决策回避", "拒绝复杂任务"],
    falseSignals: ["单纯没睡好", "对当前任务缺乏兴趣而非能力下降"] },
  { eventId: "PLASTICITY_GENERATION",
    subtle: ["开始记录新想法"],
    typical: ["旧概念产生新连接", "新模型雏形"],
    strong: ["稳定输出新结构/新计算法"],
    falseSignals: ["一次性灵感无法复现", "对他人成果的二次包装"] },
  { eventId: "CREATIVE_BURST",
    subtle: ["想表达的冲动增强"],
    typical: ["短时间内多个作品/草稿"],
    strong: ["稳定高产", "形成系列"],
    falseSignals: ["亢奋后空转", "数量高但质量低的水货输出"] },
  { eventId: "CREATIVE_BLOCK",
    subtle: ["回避创作工具"],
    typical: ["反复推翻草稿"],
    strong: ["长时间无产出"],
    falseSignals: ["其实在酝酿期被误判为阻滞", "外界打扰造成的暂时停顿"] },
  { eventId: "IDENTITY_SHIFT",
    subtle: ["自我介绍开始改写"],
    typical: ["他人称呼/标签变化"],
    strong: ["公开身份变更", "对外宣布"],
    falseSignals: ["一时兴起的头衔变更", "尚未落地的自我设定"] },
  { eventId: "MAINLINE_ALIGNMENT",
    subtle: ["决策不再纠结"],
    typical: ["多个事项指向同一方向"],
    strong: ["主线事件连续推进"],
    falseSignals: ["短期顺利但偏离长期主线", "外界鼓励造成的方向幻觉"] },
  { eventId: "MAINLINE_DEVIATION",
    subtle: ["开始接短期机会"],
    typical: ["与主线无关的事消耗大量时间"],
    strong: ["主线长时间停滞"],
    falseSignals: ["必要的休整期被误判为偏离", "短期分支其实在反哺主线"] },
  { eventId: "LOCATION_SUPPORT",
    subtle: ["在当前地点行动更顺畅"],
    typical: ["环境/人脉/资源推进事项"],
    strong: ["出现迁移/驻留契机"],
    falseSignals: ["蜜月期错觉", "天气好带来的临时愉悦"] },
  { eventId: "LOCATION_BLOCK",
    subtle: ["在当地反复受阻"],
    typical: ["环境消耗精力多于产出"],
    strong: ["需要离开/重选地点"],
    falseSignals: ["短期不适应被误判为长期不合", "个人状态差被归因于地点"] },
  { eventId: "ADMIN_APPROVAL",
    subtle: ["材料齐全无补件要求"],
    typical: ["进入审核中"],
    strong: ["收到批准/回执"],
    falseSignals: ["未署名的非官方口头肯定", "中介转述的'差不多了'"] },
  { eventId: "ADMIN_DELAY",
    subtle: ["审核状态长期不变"],
    typical: ["反复要求补材料"],
    strong: ["明确延期/搁置"],
    falseSignals: ["节假日造成的正常延后", "系统未刷新而非真的延迟"] },
];

export function getManifestation(eventId: string): EventManifestation {
  return EVENT_MANIFESTATIONS.find((m) => m.eventId === eventId) ?? {
    eventId,
    subtle: ["微弱信号尚未稳定"],
    typical: ["中等可观察事件"],
    strong: ["强烈现实反馈"],
    falseSignals: ["注意区分噪声与诱饵"],
  };
}
