// 事件库批量扩展 — Event Library Bulk Extension
// 一次性补足 15 维度下限（每维度至少 8 个有效事件），新增事件总量 ~90
// 所有新增事件遵循 EventAlgorithm 接口，不覆盖任何已有 eventId
// 字段补齐策略：在此文件直接写明显式字段；其余标准字段（manifestations / microcopy / actionLanguage 等）
// 由 eventBulkFieldFiller 在运行时按维度模板回填，保持单事件代码紧凑。
import type { EventAlgorithm } from "./eventAlgorithmTypes";

const NEW_EVENTS: EventAlgorithm[] = [
  // ============= CAREER 补齐至 8+ =============
  { id: "CAREER_PROMOTION_WINDOW", name: "晋升窗口", en: "Promotion Window", dimensionId: "CAREER",
    positiveOrNegative: "POSITIVE", baseFormula: "DomainAlign(shen,di) × Determination × Trigger",
    requiredSignals: ["上级正向反馈", "项目成果可量化"], blockingSignals: ["关键人物缺位"],
    actionPermissions: ["进", "对齐", "记录"], validationSignals: ["晋升讨论", "薪资调整提案"], feedbackMetrics: ["晋升达成"],
    userFriendlyName: "可能会被提拔" },
  { id: "CAREER_OFFER_INCOMING", name: "Offer 入场", en: "Offer Incoming", dimensionId: "CAREER",
    positiveOrNegative: "POSITIVE", baseFormula: "ExternalReply × Resonance × DomainAlign(di)",
    requiredSignals: ["终面通过", "薪资谈判启动"], blockingSignals: ["背调未过"],
    actionPermissions: ["回应", "谈判", "确认"], validationSignals: ["书面 Offer", "入职日期"], feedbackMetrics: ["Offer 命中"],
    userFriendlyName: "会有 Offer 出现" },
  { id: "CAREER_PIVOT_SIGNAL", name: "职业转向信号", en: "Career Pivot Signal", dimensionId: "CAREER",
    positiveOrNegative: "MIXED", baseFormula: "MainlineShift × Resonance ÷ Noise",
    requiredSignals: ["新方向反复浮现", "旧赛道兴趣下降"], blockingSignals: [],
    actionPermissions: ["转", "小步试错", "记录"], validationSignals: ["新方向接触次数"], feedbackMetrics: ["转向确定度"],
    userFriendlyName: "可能要换赛道了" },
  { id: "CAREER_NETWORKING_OPENING", name: "职业社交窗口", en: "Career Networking Opening", dimensionId: "CAREER",
    positiveOrNegative: "POSITIVE", baseFormula: "DomainAlign(ren) × Trigger",
    requiredSignals: ["关键活动邀请", "强连接引荐"], blockingSignals: [],
    actionPermissions: ["主动连接", "参加"], validationSignals: ["产生具体合作线索"], feedbackMetrics: ["连接转化率"],
    userFriendlyName: "适合主动认识人" },
  { id: "CAREER_BURNOUT_RISK", name: "职业倦怠风险", en: "Burnout Risk", dimensionId: "CAREER",
    positiveOrNegative: "NEGATIVE", baseFormula: "Overload × Noise ÷ Carry",
    requiredSignals: ["持续低能量", "工作意义感下降"], blockingSignals: [],
    actionPermissions: ["降载", "休息", "重排优先级"], validationSignals: ["请假/请休"], feedbackMetrics: ["倦怠等级"],
    userFriendlyName: "工作要烧干了" },
  { id: "CAREER_RECOGNITION", name: "行业被看见", en: "Career Recognition", dimensionId: "CAREER",
    positiveOrNegative: "POSITIVE", baseFormula: "Resonance × OutputQuality × Trigger",
    requiredSignals: ["公开提及", "媒体/行业转发"], blockingSignals: [],
    actionPermissions: ["回应", "记录", "顺势发布"], validationSignals: ["影响力指标上升"], feedbackMetrics: ["认可度"],
    userFriendlyName: "你会被行业注意到" },
  { id: "CAREER_REJECTION_LOOP", name: "应聘连环失败", en: "Rejection Loop", dimensionId: "CAREER",
    positiveOrNegative: "NEGATIVE", baseFormula: "MissingHumanVariable × FieldBlock × Pressure",
    requiredSignals: ["多次面试拒信", "回复率低"], blockingSignals: [],
    actionPermissions: ["调整简历", "转赛道", "降载"], validationSignals: ["面试比", "回复率"], feedbackMetrics: ["失败连数"],
    userFriendlyName: "面试一直被拒" },

  // ============= PRODUCT 补齐 =============
  { id: "PRODUCT_RETENTION_DIP", name: "留存下滑", en: "Retention Dip", dimensionId: "PRODUCT",
    positiveOrNegative: "NEGATIVE", baseFormula: "Noise × ChurnSignal ÷ ProductVitality",
    requiredSignals: ["DAU 下降", "回访下降"], blockingSignals: [],
    actionPermissions: ["修复", "调研", "降噪"], validationSignals: ["留存曲线", "用户访谈"], feedbackMetrics: ["留存差额"],
    userFriendlyName: "用户在悄悄流失" },
  { id: "PRODUCT_FEEDBACK_SURGE", name: "用户反馈激增", en: "Feedback Surge", dimensionId: "PRODUCT",
    positiveOrNegative: "MIXED", baseFormula: "FeedbackWeight × Trigger",
    requiredSignals: ["反馈条数激增"], blockingSignals: [],
    actionPermissions: ["分类", "回复", "迭代"], validationSignals: ["反馈处理率"], feedbackMetrics: ["有效反馈占比"],
    userFriendlyName: "用户开始大量给反馈" },
  { id: "PRODUCT_SCOPE_DRIFT", name: "范围漂移", en: "Scope Drift", dimensionId: "PRODUCT",
    positiveOrNegative: "NEGATIVE", baseFormula: "Noise × Ambiguity ÷ Determination",
    requiredSignals: ["需求频繁变更", "目标模糊"], blockingSignals: [],
    actionPermissions: ["收敛", "冻结范围", "降噪"], validationSignals: ["v1 是否冻结"], feedbackMetrics: ["漂移次数"],
    userFriendlyName: "做着做着跑偏了" },
  { id: "PRODUCT_MONETIZATION_OPENING", name: "商业化窗口", en: "Monetization Opening", dimensionId: "PRODUCT",
    positiveOrNegative: "POSITIVE", baseFormula: "ProductVitality × DomainAlign(di) × Determination",
    requiredSignals: ["付费意愿浮现", "商业询单"], blockingSignals: ["定数=假定"],
    actionPermissions: ["试定价", "小流量发布", "记录"], validationSignals: ["试付率"], feedbackMetrics: ["首单达成"],
    userFriendlyName: "可以开始收钱了" },
  { id: "PRODUCT_BUG_OUTBREAK", name: "Bug 爆发", en: "Bug Outbreak", dimensionId: "PRODUCT",
    positiveOrNegative: "NEGATIVE", baseFormula: "Pressure × Complexity ÷ QACoverage",
    requiredSignals: ["错误率上升", "用户投诉"], blockingSignals: [],
    actionPermissions: ["修复", "回滚", "降噪"], validationSignals: ["错误率回落"], feedbackMetrics: ["修复 SLA"],
    userFriendlyName: "Bug 集中爆出来" },
  { id: "PRODUCT_PIVOT_FORCE", name: "被迫转型", en: "Forced Pivot", dimensionId: "PRODUCT",
    positiveOrNegative: "MIXED", baseFormula: "MarketShift × MissingResource",
    requiredSignals: ["核心假设被证伪"], blockingSignals: [],
    actionPermissions: ["转", "归档", "重构"], validationSignals: ["新方向 PMF 信号"], feedbackMetrics: ["转型完成度"],
    userFriendlyName: "可能必须换方向" },

  // ============= RELATIONSHIP 补齐 =============
  { id: "RELATIONSHIP_BREAKUP_SIGNAL", name: "分手信号", en: "Breakup Signal", dimensionId: "RELATIONSHIP",
    positiveOrNegative: "NEGATIVE", baseFormula: "Cooling × Determination ÷ Resonance",
    requiredSignals: ["回避", "重要话题被关闭"], blockingSignals: [],
    actionPermissions: ["守", "确认", "降载"], validationSignals: ["明确分手表达"], feedbackMetrics: ["关系结束"],
    userFriendlyName: "可能会分开" },
  { id: "RELATIONSHIP_RECONCILE", name: "复合/和解", en: "Reconcile", dimensionId: "RELATIONSHIP",
    positiveOrNegative: "POSITIVE", baseFormula: "Rebound × Resonance × Determination",
    requiredSignals: ["对方主动靠近", "旧议题被重提"], blockingSignals: [],
    actionPermissions: ["沟通", "确认", "小步靠近"], validationSignals: ["双方意愿一致"], feedbackMetrics: ["和解达成"],
    userFriendlyName: "可能会重归于好" },
  { id: "RELATIONSHIP_BOUNDARY_TEST", name: "边界试探", en: "Boundary Test", dimensionId: "RELATIONSHIP",
    positiveOrNegative: "NEUTRAL", baseFormula: "Resonance × Ambiguity",
    requiredSignals: ["越界小动作", "暧昧暗示"], blockingSignals: [],
    actionPermissions: ["明确边界", "观察"], validationSignals: ["对方是否止步"], feedbackMetrics: ["边界稳定度"],
    userFriendlyName: "对方在试探你的底线" },
  { id: "RELATIONSHIP_NEW_INTEREST", name: "新桃花出现", en: "New Romantic Interest", dimensionId: "RELATIONSHIP",
    positiveOrNegative: "POSITIVE", baseFormula: "Resonance × DomainAlign(ren,feng) × Trigger",
    requiredSignals: ["新对象进入视野", "高频互动"], blockingSignals: [],
    actionPermissions: ["小步靠近", "观察", "等待"], validationSignals: ["私聊频率上升"], feedbackMetrics: ["关系起步"],
    userFriendlyName: "有新的可能对象" },

  // ============= SOCIAL_NETWORK 补齐 =============
  { id: "MENTOR_APPEARS", name: "导师/贵人到位", en: "Mentor Appears", dimensionId: "SOCIAL_NETWORK",
    positiveOrNegative: "POSITIVE", baseFormula: "DomainAlign(ren,shen) × Resonance",
    requiredSignals: ["年长/资深者主动指点"], blockingSignals: [],
    actionPermissions: ["回应", "请教", "保持联络"], validationSignals: ["持续指导关系"], feedbackMetrics: ["指导次数"],
    userFriendlyName: "重要的引路人会出现" },
  { id: "BETRAYAL_RISK", name: "背叛/翻脸风险", en: "Betrayal Risk", dimensionId: "SOCIAL_NETWORK",
    positiveOrNegative: "NEGATIVE", baseFormula: "Noise × HiddenConflict ÷ Trust",
    requiredSignals: ["背后议论", "信息泄露"], blockingSignals: [],
    actionPermissions: ["守", "断", "记录"], validationSignals: ["关系破裂事件"], feedbackMetrics: ["背叛确认"],
    userFriendlyName: "可能会被人背刺" },
  { id: "WEAK_TIE_ACTIVATION", name: "弱连接激活", en: "Weak Tie Activation", dimensionId: "SOCIAL_NETWORK",
    positiveOrNegative: "POSITIVE", baseFormula: "Resonance × WeakTieDensity",
    requiredSignals: ["旧群组重新热", "朋友的朋友推进"], blockingSignals: [],
    actionPermissions: ["主动连接", "回应"], validationSignals: ["新机会经过弱连接到达"], feedbackMetrics: ["弱连接转化"],
    userFriendlyName: "老朋友的圈子会带来机会" },
  { id: "SOCIAL_DRAIN", name: "社交消耗过载", en: "Social Drain", dimensionId: "SOCIAL_NETWORK",
    positiveOrNegative: "NEGATIVE", baseFormula: "Pressure × LowQualityContact",
    requiredSignals: ["无效会议密集", "情绪劳务"], blockingSignals: [],
    actionPermissions: ["断", "降载", "拒绝"], validationSignals: ["精力回复"], feedbackMetrics: ["社交疲劳度"],
    userFriendlyName: "社交在消耗你" },
  { id: "PUBLIC_REPUTATION_SHIFT", name: "公众口碑变化", en: "Reputation Shift", dimensionId: "SOCIAL_NETWORK",
    positiveOrNegative: "MIXED", baseFormula: "ResonancePublic × Noise",
    requiredSignals: ["群体评价变化"], blockingSignals: [],
    actionPermissions: ["发声", "守", "回应"], validationSignals: ["评论倾向"], feedbackMetrics: ["口碑指数"],
    userFriendlyName: "外界对你的评价在变" },
  { id: "REFERRAL_INFLOW", name: "推荐流入", en: "Referral Inflow", dimensionId: "SOCIAL_NETWORK",
    positiveOrNegative: "POSITIVE", baseFormula: "Resonance × DomainAlign(ren,di)",
    requiredSignals: ["多人独立推荐同一机会"], blockingSignals: [],
    actionPermissions: ["回应", "接洽"], validationSignals: ["新合作启动"], feedbackMetrics: ["推荐转化"],
    userFriendlyName: "会有人帮你介绍机会" },

  // ============= FINANCE 补齐 =============
  { id: "UNEXPECTED_WINDFALL", name: "意外收益", en: "Unexpected Windfall", dimensionId: "FINANCE",
    positiveOrNegative: "POSITIVE", baseFormula: "Trigger × Resonance × DomainAlign(di)",
    requiredSignals: ["意外回款", "奖金/红包"], blockingSignals: [],
    actionPermissions: ["接收", "存起来"], validationSignals: ["账户进账"], feedbackMetrics: ["意外金额"],
    userFriendlyName: "会有一笔意外的钱" },
  { id: "DEBT_PRESSURE", name: "债务压力", en: "Debt Pressure", dimensionId: "FINANCE",
    positiveOrNegative: "NEGATIVE", baseFormula: "Pressure × Outflow ÷ Inflow",
    requiredSignals: ["到期账单密集"], blockingSignals: [],
    actionPermissions: ["守", "重排", "沟通"], validationSignals: ["逾期/重组协议"], feedbackMetrics: ["债务等级"],
    userFriendlyName: "欠的钱要还了" },
  { id: "INVESTMENT_OPPORTUNITY", name: "投资机会出现", en: "Investment Opportunity", dimensionId: "FINANCE",
    positiveOrNegative: "MIXED", baseFormula: "DomainAlign(di) × Trigger × Determination",
    requiredSignals: ["项目方主动接触"], blockingSignals: ["定数=假定"],
    actionPermissions: ["小步", "回验", "记录"], validationSignals: ["DD 推进"], feedbackMetrics: ["投资决策"],
    userFriendlyName: "有可以投钱的机会" },
  { id: "RECURRING_REVENUE", name: "重复性收入建立", en: "Recurring Revenue", dimensionId: "FINANCE",
    positiveOrNegative: "POSITIVE", baseFormula: "ProductVitality × Retention × Determination",
    requiredSignals: ["订阅/续费转化"], blockingSignals: [],
    actionPermissions: ["维护", "优化"], validationSignals: ["MRR 上升"], feedbackMetrics: ["MRR 变化"],
    userFriendlyName: "会有稳定的钱进来" },
  { id: "BUDGET_OVERRUN", name: "预算超支", en: "Budget Overrun", dimensionId: "FINANCE",
    positiveOrNegative: "NEGATIVE", baseFormula: "Outflow × Complexity ÷ Plan",
    requiredSignals: ["实际成本 > 预算"], blockingSignals: [],
    actionPermissions: ["复核", "重排", "断"], validationSignals: ["差额"], feedbackMetrics: ["超支幅度"],
    userFriendlyName: "花的钱超预算了" },

  // ============= STUDY_APPLICATION 补齐 =============
  { id: "ADMISSION_OFFER", name: "录取出现", en: "Admission Offer", dimensionId: "STUDY_APPLICATION",
    positiveOrNegative: "POSITIVE", baseFormula: "ExternalReply × Determination",
    requiredSignals: ["正式录取信"], blockingSignals: [],
    actionPermissions: ["接受", "回应", "记录"], validationSignals: ["入学手续"], feedbackMetrics: ["录取命中"],
    userFriendlyName: "会被录取" },
  { id: "REJECTION_LETTER", name: "拒信到达", en: "Rejection Letter", dimensionId: "STUDY_APPLICATION",
    positiveOrNegative: "NEGATIVE", baseFormula: "ExternalReply × MissingResource",
    requiredSignals: ["拒信邮件"], blockingSignals: [],
    actionPermissions: ["接受", "申诉", "转向"], validationSignals: ["申诉结果"], feedbackMetrics: ["拒信数量"],
    userFriendlyName: "会收到拒信" },
  { id: "INTERVIEW_INVITE", name: "面试邀约", en: "Interview Invite", dimensionId: "STUDY_APPLICATION",
    positiveOrNegative: "POSITIVE", baseFormula: "DomainAlign(di,shen) × Trigger",
    requiredSignals: ["面试官联系"], blockingSignals: [],
    actionPermissions: ["准备", "回应", "确认"], validationSignals: ["面试完成"], feedbackMetrics: ["面试推进"],
    userFriendlyName: "会被叫去面试" },
  { id: "MATERIAL_GAP", name: "材料缺口", en: "Material Gap", dimensionId: "STUDY_APPLICATION",
    positiveOrNegative: "NEGATIVE", baseFormula: "MissingResource × Pressure",
    requiredSignals: ["关键材料未齐"], blockingSignals: [],
    actionPermissions: ["补材料", "找推荐人"], validationSignals: ["材料齐全度"], feedbackMetrics: ["材料补齐时间"],
    userFriendlyName: "材料还没准备好" },
  { id: "DEADLINE_PRESSURE", name: "DDL 临近", en: "Deadline Pressure", dimensionId: "STUDY_APPLICATION",
    positiveOrNegative: "MIXED", baseFormula: "Pressure × TimeLeftInverse",
    requiredSignals: ["剩余时间 < 7 天"], blockingSignals: [],
    actionPermissions: ["进", "降范围", "聚焦"], validationSignals: ["按时提交"], feedbackMetrics: ["DDL 命中"],
    userFriendlyName: "截止日快到了" },
  { id: "RECOMMENDER_DELAY", name: "推荐人延迟", en: "Recommender Delay", dimensionId: "STUDY_APPLICATION",
    positiveOrNegative: "NEGATIVE", baseFormula: "MissingHumanVariable × FieldBlock",
    requiredSignals: ["推荐信未提交"], blockingSignals: [],
    actionPermissions: ["催促", "备选人"], validationSignals: ["推荐信到位"], feedbackMetrics: ["延迟天数"],
    userFriendlyName: "推荐人拖着没交" },

  // ============= HEALTH 补齐 =============
  { id: "SLEEP_DEGRADATION", name: "睡眠恶化", en: "Sleep Degradation", dimensionId: "HEALTH_RECOVERY",
    positiveOrNegative: "NEGATIVE", baseFormula: "Noise × NeuralExcitation ÷ Recovery",
    requiredSignals: ["入睡延迟", "夜醒多"], blockingSignals: [],
    actionPermissions: ["降载", "调节作息"], validationSignals: ["睡眠时长/质量"], feedbackMetrics: ["睡眠分"],
    userFriendlyName: "睡眠会变差" },
  { id: "EXERCISE_REBOUND", name: "运动反弹", en: "Exercise Rebound", dimensionId: "HEALTH_RECOVERY",
    positiveOrNegative: "POSITIVE", baseFormula: "Rebound × Carry",
    requiredSignals: ["运动欲恢复"], blockingSignals: [],
    actionPermissions: ["轻度训练", "恢复"], validationSignals: ["运动频次"], feedbackMetrics: ["运动量"],
    userFriendlyName: "想运动的劲会回来" },
  { id: "DIET_DRIFT", name: "饮食紊乱", en: "Diet Drift", dimensionId: "HEALTH_RECOVERY",
    positiveOrNegative: "NEGATIVE", baseFormula: "Noise × Pressure ÷ Discipline",
    requiredSignals: ["暴食/不规律"], blockingSignals: [],
    actionPermissions: ["调整饮食", "降噪"], validationSignals: ["饮食结构"], feedbackMetrics: ["饮食稳定度"],
    userFriendlyName: "吃饭会乱掉" },
  { id: "ILLNESS_ONSET", name: "疾病起势", en: "Illness Onset", dimensionId: "HEALTH_RECOVERY",
    positiveOrNegative: "NEGATIVE", baseFormula: "Overload × LowImmunity",
    requiredSignals: ["持续不适", "免疫力下降"], blockingSignals: [],
    actionPermissions: ["就医", "休息"], validationSignals: ["医生诊断"], feedbackMetrics: ["健康指标"],
    userFriendlyName: "可能要生病" },
  { id: "NERVOUS_OVEREXCITATION", name: "神经过度兴奋", en: "Nervous Overexcitation", dimensionId: "HEALTH_RECOVERY",
    positiveOrNegative: "NEGATIVE", baseFormula: "NeuralExcitation × StimulantLoad",
    requiredSignals: ["难以放松", "心率高"], blockingSignals: [],
    actionPermissions: ["降载", "减少咖啡因"], validationSignals: ["HRV / 心率"], feedbackMetrics: ["兴奋等级"],
    userFriendlyName: "神经停不下来" },
  { id: "RECOVERY_PLATEAU", name: "恢复平台期", en: "Recovery Plateau", dimensionId: "HEALTH_RECOVERY",
    positiveOrNegative: "NEUTRAL", baseFormula: "Carry × StableRoutine",
    requiredSignals: ["指标不再上升也不下降"], blockingSignals: [],
    actionPermissions: ["保持", "微调"], validationSignals: ["体感稳定"], feedbackMetrics: ["平台时长"],
    userFriendlyName: "身体进入瓶颈期" },

  // ============= COGNITION 补齐 =============
  { id: "COGNITIVE_OVERLOAD", name: "认知过载", en: "Cognitive Overload", dimensionId: "COGNITION",
    positiveOrNegative: "NEGATIVE", baseFormula: "TaskComplexity × Concurrency ÷ Carry",
    requiredSignals: ["多任务崩塌", "判断混乱"], blockingSignals: [],
    actionPermissions: ["降载", "外化", "断舍"], validationSignals: ["产出质量回落"], feedbackMetrics: ["过载次数"],
    userFriendlyName: "脑子转不动了" },
  { id: "INSIGHT_DROP", name: "顿悟落点", en: "Insight Drop", dimensionId: "COGNITION",
    positiveOrNegative: "POSITIVE", baseFormula: "Plasticity × Trigger × Resonance",
    requiredSignals: ["旧问题忽然通了"], blockingSignals: [],
    actionPermissions: ["记录", "外化"], validationSignals: ["新结构形成"], feedbackMetrics: ["顿悟数"],
    userFriendlyName: "会突然想通一件事" },
  { id: "DEEP_WORK_WINDOW", name: "深度工作窗口", en: "Deep Work Window", dimensionId: "COGNITION",
    positiveOrNegative: "POSITIVE", baseFormula: "FocusCapacity × LowNoise",
    requiredSignals: ["可连续 90 分钟无干扰"], blockingSignals: [],
    actionPermissions: ["深做", "拒打扰"], validationSignals: ["深度块次数"], feedbackMetrics: ["深做时长"],
    userFriendlyName: "可以专心做事的时间" },
  { id: "DECISION_FATIGUE", name: "决策疲劳", en: "Decision Fatigue", dimensionId: "COGNITION",
    positiveOrNegative: "NEGATIVE", baseFormula: "DecisionCount × Pressure ÷ Recovery",
    requiredSignals: ["拖延关键决策"], blockingSignals: [],
    actionPermissions: ["延后", "简化", "降载"], validationSignals: ["决策速度"], feedbackMetrics: ["疲劳等级"],
    userFriendlyName: "不想做选择了" },
  { id: "ALGORITHM_BIRTH", name: "新算法生成", en: "Algorithm Birth", dimensionId: "COGNITION",
    positiveOrNegative: "POSITIVE", baseFormula: "Plasticity × Synthesis × Determination",
    requiredSignals: ["跨域结构闭合"], blockingSignals: [],
    actionPermissions: ["记录", "命名", "外化"], validationSignals: ["新算法被复用"], feedbackMetrics: ["算法数"],
    userFriendlyName: "会长出新的判断方法" },

  // ============= CREATION 补齐 =============
  { id: "PUBLISH_RELEASE", name: "发布动作落地", en: "Publish Release", dimensionId: "CREATION",
    positiveOrNegative: "POSITIVE", baseFormula: "CreativeBurst × Determination × BranchCollapse",
    requiredSignals: ["可发布物完成"], blockingSignals: ["定数=假定"],
    actionPermissions: ["发布", "记录"], validationSignals: ["发布完成"], feedbackMetrics: ["发布次数"],
    userFriendlyName: "把作品发出去" },
  { id: "STYLE_SHIFT", name: "风格转折", en: "Style Shift", dimensionId: "CREATION",
    positiveOrNegative: "MIXED", baseFormula: "Plasticity × Synthesis",
    requiredSignals: ["旧风格无感", "新引用反复出现"], blockingSignals: [],
    actionPermissions: ["试新风格", "记录"], validationSignals: ["新风格作品产出"], feedbackMetrics: ["风格变更"],
    userFriendlyName: "创作风格会换" },
  { id: "AUDIENCE_RESONANCE", name: "受众共振", en: "Audience Resonance", dimensionId: "CREATION",
    positiveOrNegative: "POSITIVE", baseFormula: "OutputQuality × Resonance",
    requiredSignals: ["受众主动转发/评论"], blockingSignals: [],
    actionPermissions: ["延伸", "持续输出"], validationSignals: ["互动指标"], feedbackMetrics: ["共振强度"],
    userFriendlyName: "作品被人看见了" },
  { id: "CREATIVE_DOUBT", name: "自我怀疑", en: "Creative Doubt", dimensionId: "CREATION",
    positiveOrNegative: "NEGATIVE", baseFormula: "Noise × ComparisonPressure",
    requiredSignals: ["反复删稿"], blockingSignals: [],
    actionPermissions: ["休息", "外化", "降噪"], validationSignals: ["产出恢复"], feedbackMetrics: ["怀疑时长"],
    userFriendlyName: "开始怀疑自己" },
  { id: "WORLDBUILDING_LEAP", name: "世界观跃迁", en: "Worldbuilding Leap", dimensionId: "CREATION",
    positiveOrNegative: "POSITIVE", baseFormula: "Plasticity × Synthesis × LongHorizon",
    requiredSignals: ["跨作品贯通线浮现"], blockingSignals: [],
    actionPermissions: ["记录", "结构化"], validationSignals: ["体系闭合"], feedbackMetrics: ["体系扩展"],
    userFriendlyName: "故事/体系会扩大一圈" },
  { id: "OUTPUT_SPEED_UP", name: "输出加速", en: "Output Speed Up", dimensionId: "CREATION",
    positiveOrNegative: "POSITIVE", baseFormula: "Plasticity × LowFriction",
    requiredSignals: ["单位时间产出上升"], blockingSignals: [],
    actionPermissions: ["持续产出", "记录"], validationSignals: ["产出/小时"], feedbackMetrics: ["加速倍率"],
    userFriendlyName: "写得更快了" },

  // ============= IDENTITY 补齐 =============
  { id: "PUBLIC_IDENTITY_LAUNCH", name: "公开身份启动", en: "Public Identity Launch", dimensionId: "IDENTITY",
    positiveOrNegative: "POSITIVE", baseFormula: "BranchCollapse × Determination",
    requiredSignals: ["公开发布个人定位"], blockingSignals: [],
    actionPermissions: ["发布", "对齐"], validationSignals: ["他人称呼变化"], feedbackMetrics: ["身份扩散"],
    userFriendlyName: "你会有新的公开身份" },
  { id: "ROLE_OVERLOAD", name: "角色过载", en: "Role Overload", dimensionId: "IDENTITY",
    positiveOrNegative: "NEGATIVE", baseFormula: "RoleCount × Pressure",
    requiredSignals: ["多角色冲突"], blockingSignals: [],
    actionPermissions: ["收敛角色", "降载"], validationSignals: ["主角色清晰"], feedbackMetrics: ["角色数"],
    userFriendlyName: "扮演太多角色撑不住" },
  { id: "SELF_REDEFINITION", name: "自我重定义", en: "Self Redefinition", dimensionId: "IDENTITY",
    positiveOrNegative: "MIXED", baseFormula: "MainlineShift × Reflection",
    requiredSignals: ["反复重写自我介绍"], blockingSignals: [],
    actionPermissions: ["写定义", "外化"], validationSignals: ["新定义稳定"], feedbackMetrics: ["定义版本"],
    userFriendlyName: "你在重新定义自己" },

  // ============= SPIRIT_MAINLINE 补齐 =============
  { id: "MEANING_SURGE", name: "意义感涌现", en: "Meaning Surge", dimensionId: "SPIRIT_MAINLINE",
    positiveOrNegative: "POSITIVE", baseFormula: "Resonance × MainlineAlignment",
    requiredSignals: ["关键事件触动主线感"], blockingSignals: [],
    actionPermissions: ["记录", "对齐"], validationSignals: ["主线确认"], feedbackMetrics: ["意义强度"],
    userFriendlyName: "会觉得做的事更有意义" },
  { id: "VALUE_REORDER", name: "价值排序变动", en: "Value Reorder", dimensionId: "SPIRIT_MAINLINE",
    positiveOrNegative: "MIXED", baseFormula: "Reflection × MainlineShift",
    requiredSignals: ["对旧优先级反感"], blockingSignals: [],
    actionPermissions: ["重排", "记录"], validationSignals: ["新优先级落地"], feedbackMetrics: ["排序版本"],
    userFriendlyName: "你重视的东西会换" },
  { id: "SYMBOLIC_EVENT", name: "象征性事件", en: "Symbolic Event", dimensionId: "SPIRIT_MAINLINE",
    positiveOrNegative: "POSITIVE", baseFormula: "Resonance × LongHorizon",
    requiredSignals: ["重复象征再次出现"], blockingSignals: [],
    actionPermissions: ["记录", "反思"], validationSignals: ["事件复现"], feedbackMetrics: ["象征强度"],
    userFriendlyName: "会出现一个有意义的标志" },
  { id: "EXISTENTIAL_DOUBT", name: "存在性怀疑", en: "Existential Doubt", dimensionId: "SPIRIT_MAINLINE",
    positiveOrNegative: "NEGATIVE", baseFormula: "Noise × LowMeaning",
    requiredSignals: ["质疑长期方向"], blockingSignals: [],
    actionPermissions: ["暂停决策", "记录", "降噪"], validationSignals: ["主线再确认"], feedbackMetrics: ["怀疑时长"],
    userFriendlyName: "会怀疑活着的意义" },

  // ============= LOCATION 补齐 =============
  { id: "RELOCATION_OPPORTUNITY", name: "迁移机会出现", en: "Relocation Opportunity", dimensionId: "LOCATION",
    positiveOrNegative: "MIXED", baseFormula: "GeoFactor × Trigger × Determination",
    requiredSignals: ["跨城/跨国机会"], blockingSignals: [],
    actionPermissions: ["勘察", "决策", "等待"], validationSignals: ["搬迁动作"], feedbackMetrics: ["迁移决策"],
    userFriendlyName: "会有搬到别处的机会" },
  { id: "LOCAL_NETWORK_DENSIFY", name: "本地圈子密集化", en: "Local Network Densify", dimensionId: "LOCATION",
    positiveOrNegative: "POSITIVE", baseFormula: "GeoFactor × DomainAlign(ren)",
    requiredSignals: ["本地熟人增多"], blockingSignals: [],
    actionPermissions: ["参与", "深耕"], validationSignals: ["本地合作"], feedbackMetrics: ["本地连接数"],
    userFriendlyName: "本地圈子会变厚" },
  { id: "ENVIRONMENT_TOXICITY", name: "环境毒性", en: "Environment Toxicity", dimensionId: "LOCATION",
    positiveOrNegative: "NEGATIVE", baseFormula: "NegativeGeo × Noise",
    requiredSignals: ["环境持续消耗能量"], blockingSignals: [],
    actionPermissions: ["远离", "迁移"], validationSignals: ["状态恢复"], feedbackMetrics: ["毒性等级"],
    userFriendlyName: "现在的环境在伤你" },
  { id: "TRAVEL_INSIGHT", name: "旅行带来的洞见", en: "Travel Insight", dimensionId: "LOCATION",
    positiveOrNegative: "POSITIVE", baseFormula: "GeoFactor × Plasticity",
    requiredSignals: ["短期出行 + 视角转换"], blockingSignals: [],
    actionPermissions: ["记录", "外化"], validationSignals: ["新结构生成"], feedbackMetrics: ["洞见数"],
    userFriendlyName: "出门会带回新想法" },

  // ============= FAMILY_LIFE (映射到 LOCATION_ENVIRONMENT) =============
  { id: "FAMILY_TENSION", name: "家庭紧张", en: "Family Tension", dimensionId: "FAMILY_LIFE",
    positiveOrNegative: "NEGATIVE", baseFormula: "Noise × ResponsibilityPressure",
    requiredSignals: ["家庭冲突频次上升"], blockingSignals: [],
    actionPermissions: ["沟通", "守", "降载"], validationSignals: ["冲突减少"], feedbackMetrics: ["紧张等级"],
    userFriendlyName: "家里气氛会变紧" },
  { id: "FAMILY_SUPPORT_INFLOW", name: "家庭支持流入", en: "Family Support Inflow", dimensionId: "FAMILY_LIFE",
    positiveOrNegative: "POSITIVE", baseFormula: "DomainAlign(ren,di) × Resonance",
    requiredSignals: ["家人主动协助"], blockingSignals: [],
    actionPermissions: ["接受", "回应"], validationSignals: ["资源/情绪到位"], feedbackMetrics: ["支持等级"],
    userFriendlyName: "家人会帮你" },
  { id: "LIVING_ARRANGEMENT_CHANGE", name: "居住变动", en: "Living Arrangement Change", dimensionId: "FAMILY_LIFE",
    positiveOrNegative: "MIXED", baseFormula: "GeoFactor × Trigger",
    requiredSignals: ["搬家/合住/分住"], blockingSignals: [],
    actionPermissions: ["规划", "执行"], validationSignals: ["新住处落地"], feedbackMetrics: ["稳定度"],
    userFriendlyName: "住的地方会变" },

  // ============= LEGAL_ADMIN 补齐 =============
  { id: "CONTRACT_SIGNING", name: "合同签署", en: "Contract Signing", dimensionId: "LEGAL_ADMIN",
    positiveOrNegative: "POSITIVE", baseFormula: "Determination × BranchCollapse",
    requiredSignals: ["条款定稿", "双方意向一致"], blockingSignals: ["定数=假定"],
    actionPermissions: ["签署", "记录"], validationSignals: ["合同生效"], feedbackMetrics: ["签约达成"],
    userFriendlyName: "会签合同" },
  { id: "POLICY_CHANGE_IMPACT", name: "政策变更影响", en: "Policy Change Impact", dimensionId: "LEGAL_ADMIN",
    positiveOrNegative: "MIXED", baseFormula: "ExternalShift × Exposure",
    requiredSignals: ["相关政策更新"], blockingSignals: [],
    actionPermissions: ["调整", "合规"], validationSignals: ["合规状态"], feedbackMetrics: ["影响范围"],
    userFriendlyName: "外部政策会变" },
  { id: "VISA_IMMIGRATION_SIGNAL", name: "签证/身份信号", en: "Visa/Immigration Signal", dimensionId: "LEGAL_ADMIN",
    positiveOrNegative: "MIXED", baseFormula: "ExternalReply × Determination",
    requiredSignals: ["签证流程更新"], blockingSignals: ["材料缺失"],
    actionPermissions: ["补材料", "等待", "回应"], validationSignals: ["状态变化"], feedbackMetrics: ["流程进度"],
    userFriendlyName: "签证/身份手续会有动静" },
  { id: "LEGAL_DISPUTE", name: "法律争议", en: "Legal Dispute", dimensionId: "LEGAL_ADMIN",
    positiveOrNegative: "NEGATIVE", baseFormula: "ConflictDensity × Exposure",
    requiredSignals: ["对方发函", "争议升级"], blockingSignals: [],
    actionPermissions: ["守", "找律师", "记录"], validationSignals: ["流程进入"], feedbackMetrics: ["争议等级"],
    userFriendlyName: "可能会有纠纷" },
  { id: "COMPLIANCE_REVIEW", name: "合规审查", en: "Compliance Review", dimensionId: "LEGAL_ADMIN",
    positiveOrNegative: "MIXED", baseFormula: "ExternalAudit × Exposure",
    requiredSignals: ["审计通知"], blockingSignals: [],
    actionPermissions: ["配合", "补材料"], validationSignals: ["审查结果"], feedbackMetrics: ["合规度"],
    userFriendlyName: "要被检查/审计" },

  // ============= PROMPT_TOOLING 补齐（target TOOL_AI_PROMPT 当前为 0）=============
  { id: "PROMPT_HIT", name: "提示词命中", en: "Prompt Hit", dimensionId: "PROMPT_TOOLING",
    positiveOrNegative: "POSITIVE", baseFormula: "PromptQuality × ContextFit",
    requiredSignals: ["首轮输出可用"], blockingSignals: ["Scope drift"],
    actionPermissions: ["发布", "复用", "记录"], validationSignals: ["复用次数"], feedbackMetrics: ["命中率"],
    userFriendlyName: "提示词一次就成" },
  { id: "PROMPT_DRIFT", name: "提示词漂移", en: "Prompt Drift", dimensionId: "PROMPT_TOOLING",
    positiveOrNegative: "NEGATIVE", baseFormula: "Ambiguity × Concurrency",
    requiredSignals: ["越改越偏"], blockingSignals: [],
    actionPermissions: ["收敛", "重写", "降范围"], validationSignals: ["输出回到目标"], feedbackMetrics: ["漂移次数"],
    userFriendlyName: "提示词越改越乱" },
  { id: "TOOL_CONTEXT_LOSS", name: "工具上下文丢失", en: "Tool Context Loss", dimensionId: "PROMPT_TOOLING",
    positiveOrNegative: "NEGATIVE", baseFormula: "ContextChurn × LongChain",
    requiredSignals: ["工具忘了前文"], blockingSignals: [],
    actionPermissions: ["补上下文", "拆步"], validationSignals: ["输出重新对齐"], feedbackMetrics: ["丢失次数"],
    userFriendlyName: "工具忘了前面说过什么" },
  { id: "PROMPT_TEMPLATE_REUSE", name: "模板复用成功", en: "Template Reuse Success", dimensionId: "PROMPT_TOOLING",
    positiveOrNegative: "POSITIVE", baseFormula: "TemplateGeneralization × Resonance",
    requiredSignals: ["同模板跨场景产出可用"], blockingSignals: [],
    actionPermissions: ["归档", "标准化"], validationSignals: ["跨域复用率"], feedbackMetrics: ["复用次数"],
    userFriendlyName: "同一个模板能多次用" },
  { id: "AI_OUTPUT_FALSE_CONFIDENCE", name: "AI 输出虚假自信", en: "False Confidence Output", dimensionId: "PROMPT_TOOLING",
    positiveOrNegative: "NEGATIVE", baseFormula: "Fluency ÷ Grounding",
    requiredSignals: ["语气笃定但事实错"], blockingSignals: [],
    actionPermissions: ["回验", "信号净化"], validationSignals: ["事实核对"], feedbackMetrics: ["伪信号率"],
    userFriendlyName: "AI 一本正经地说错话" },
  { id: "BUILD_FAIL_LOOP", name: "构建失败循环", en: "Build Fail Loop", dimensionId: "PROMPT_TOOLING",
    positiveOrNegative: "NEGATIVE", baseFormula: "Complexity × ScopeDrift ÷ QACoverage",
    requiredSignals: ["连续构建失败"], blockingSignals: [],
    actionPermissions: ["缩小范围", "重算", "回滚"], validationSignals: ["构建成功"], feedbackMetrics: ["失败连数"],
    userFriendlyName: "一直构建失败" },
  { id: "PROMPT_FORGE_OUTPUT", name: "Prompt Forge 产出", en: "Prompt Forge Output", dimensionId: "PROMPT_TOOLING",
    positiveOrNegative: "POSITIVE", baseFormula: "PromptCalculus × Determination",
    requiredSignals: ["新提示词生成可用"], blockingSignals: [],
    actionPermissions: ["发布", "记录"], validationSignals: ["复用"], feedbackMetrics: ["产出数"],
    userFriendlyName: "做出一条可以用的提示词" },
  { id: "AGENT_CHAIN_BREAK", name: "Agent 链路断裂", en: "Agent Chain Break", dimensionId: "PROMPT_TOOLING",
    positiveOrNegative: "NEGATIVE", baseFormula: "ChainLength × Noise ÷ Determinism",
    requiredSignals: ["多步骤中途失败"], blockingSignals: [],
    actionPermissions: ["拆短链", "重启", "降范围"], validationSignals: ["链路完成"], feedbackMetrics: ["断点位置"],
    userFriendlyName: "多步操作走到一半断了" },

  // ============= RISK_CHAOS 补齐 =============
  { id: "EMOTIONAL_NOISE_SPIKE", name: "情绪噪声尖峰", en: "Emotional Noise Spike", dimensionId: "RISK_CHAOS",
    positiveOrNegative: "NEGATIVE", baseFormula: "Noise × LowRecovery",
    requiredSignals: ["短时情绪波动大"], blockingSignals: [],
    actionPermissions: ["不做决策", "降载"], validationSignals: ["48h 后是否成立"], feedbackMetrics: ["噪声等级"],
    userFriendlyName: "情绪暂时翻车了" },
  { id: "WISH_PROJECTION", name: "愿望投射", en: "Wish Projection", dimensionId: "RISK_CHAOS",
    positiveOrNegative: "NEGATIVE", baseFormula: "DesireWeight ÷ SignalQuality",
    requiredSignals: ["把希望当事实"], blockingSignals: [],
    actionPermissions: ["信号净化", "守"], validationSignals: ["事后回验"], feedbackMetrics: ["误判率"],
    userFriendlyName: "你只是太希望它发生" },
  { id: "FEAR_PROJECTION", name: "恐惧投射", en: "Fear Projection", dimensionId: "RISK_CHAOS",
    positiveOrNegative: "NEGATIVE", baseFormula: "FearWeight ÷ SignalQuality",
    requiredSignals: ["把恐惧当预言"], blockingSignals: [],
    actionPermissions: ["信号净化", "降载"], validationSignals: ["事后回验"], feedbackMetrics: ["误判率"],
    userFriendlyName: "你只是太害怕它发生" },
  { id: "DELAYED_AFTERSHOCK", name: "延迟残影", en: "Delayed Aftershock", dimensionId: "RISK_CHAOS",
    positiveOrNegative: "NEGATIVE", baseFormula: "PastEventWeight × LowResolution",
    requiredSignals: ["旧事件情绪复发"], blockingSignals: [],
    actionPermissions: ["守", "记录"], validationSignals: ["情绪退潮"], feedbackMetrics: ["残影强度"],
    userFriendlyName: "旧事情还在余震" },
  { id: "RUMOR_NOISE", name: "传闻噪声", en: "Rumor Noise", dimensionId: "RISK_CHAOS",
    positiveOrNegative: "NEGATIVE", baseFormula: "Noise × Reach",
    requiredSignals: ["未证实传闻扩散"], blockingSignals: [],
    actionPermissions: ["守", "不转发", "等证据"], validationSignals: ["事实证据"], feedbackMetrics: ["传闻命中"],
    userFriendlyName: "听到的可能只是谣言" },
  { id: "OVERREACTION_RISK", name: "过度反应风险", en: "Overreaction Risk", dimensionId: "RISK_CHAOS",
    positiveOrNegative: "NEGATIVE", baseFormula: "Reactivity × Pressure",
    requiredSignals: ["想立刻大动作"], blockingSignals: [],
    actionPermissions: ["延后 24h", "降载"], validationSignals: ["事后是否后悔"], feedbackMetrics: ["反应过度次数"],
    userFriendlyName: "想做的大动作可能太冲动" },
];

export default NEW_EVENTS;
