// 事件类型解码表
import type { Domain } from "./types";

export interface EventType {
  id: string;
  name: string;
  domain: Domain;
  explanation: string;
  appearance: string;
  shouldDo: string;
  shouldNotDo: string;
  verification: string;
}

export const EVENT_TYPES: EventType[] = [
  { id: "career_trigger", name: "事业触发", domain: "shen",
    explanation: "事业主线进入可操作窗口，结构出现推进口。",
    appearance: "项目推进、机会出现、关键节点确认。",
    shouldDo: "提交方案、约见关键人、明确节奏。",
    shouldNotDo: "因为热度过早承诺长期绑定。",
    verification: "7天内是否出现项目反馈或推进信号。" },
  { id: "partnership", name: "合作窗口", domain: "ren",
    explanation: "合作结构成型，配对位激活。",
    appearance: "邀约、共建提案、平台或机构联系。",
    shouldDo: "建立清晰边界与价值交换。",
    shouldNotDo: "情绪化承诺、模糊条款。",
    verification: "是否进入二次沟通或协议草案阶段。" },
  { id: "resource_appear", name: "资源出现", domain: "di",
    explanation: "资源位强化，财星 / 场域增强。",
    appearance: "资金、平台、客户、设备、机会信息浮现。",
    shouldDo: "整理报价、对齐资源使用路径。",
    shouldNotDo: "把短期资源当作长期身份。",
    verification: "是否在 5–10 日内落地到具体动作。" },
  { id: "finance_wave", name: "财务波动", domain: "di",
    explanation: "资金流向变化，进/出位同时被激活。",
    appearance: "回款、支出、计费、报销、结算波动。",
    shouldDo: "复核账目、保留缓冲。",
    shouldNotDo: "在高波动日做长期承诺。",
    verification: "账户流水与计划是否一致。" },
  { id: "relation_warm", name: "关系升温", domain: "ren",
    explanation: "二元关系结构温度上升。",
    appearance: "亲密、深聊、靠近、关心、和解。",
    shouldDo: "正视、回应、共建。",
    shouldNotDo: "把短期靠近误读为长期承诺。",
    verification: "互动频率是否保持稳定 7 天以上。" },
  { id: "relation_cool", name: "关系降温", domain: "ren",
    explanation: "关系结构进入降频或清理位。",
    appearance: "冷场、回避、距离感、合作减少。",
    shouldDo: "保持边界、观察主线。",
    shouldNotDo: "强行催热、自我归因。",
    verification: "对方主动重启是否在 14 日内发生。" },
  { id: "key_talk", name: "关键沟通", domain: "ren",
    explanation: "对话位激活，关键信息正在交换。",
    appearance: "一次决定性谈话、邮件、会议、对账。",
    shouldDo: "提前准备结构化表达。",
    shouldNotDo: "情绪化发言、模糊立场。",
    verification: "对方是否回应了核心议题。" },
  { id: "application_feedback", name: "申请反馈", domain: "di",
    explanation: "制度位被触发，外部系统正在响应。",
    appearance: "录取、审批、退稿、面试邀请、合规反馈。",
    shouldDo: "记录、补材料、按节奏推进。",
    shouldNotDo: "因结果情绪化撤回主线。",
    verification: "是否在 10 日内出现下一步说明。" },
  { id: "academic_signal", name: "学业 / 机构信号", domain: "di",
    explanation: "学术或机构身份位激活。",
    appearance: "录取、面谈、出版、立项、机构合作。",
    shouldDo: "对齐长期身份建设。",
    shouldNotDo: "为短期机会牺牲主线。",
    verification: "机构沟通是否进入正式流程。" },
  { id: "body_recover", name: "身体恢复", domain: "di",
    explanation: "承载位进入恢复相。",
    appearance: "睡眠改善、体感回升、思路清晰。",
    shouldDo: "运动、修复、调整饮食与节奏。",
    shouldNotDo: "在恢复期硬推产出。",
    verification: "连续 3 日是否保持稳定。" },
  { id: "body_overload", name: "身体过载", domain: "di",
    explanation: "承载位被透支，进入病位风险。",
    appearance: "疲劳、失眠、情绪起伏、注意力下降。",
    shouldDo: "降频、休整、删减议程。",
    shouldNotDo: "继续叠加新承诺。",
    verification: "是否在 3 日内主动降负。" },
  { id: "creation_burst", name: "创作爆发", domain: "feng",
    explanation: "表达位被激活，输出窗口打开。",
    appearance: "灵感涌现、写作高产、产品迭代加速。",
    shouldDo: "记录、产出、发布。",
    shouldNotDo: "完美主义自我拖延。",
    verification: "是否在 7 日内产出可发布物。" },
  { id: "project_form", name: "项目成型", domain: "di",
    explanation: "结构位完成由散到聚的关键转折。",
    appearance: "范围、节奏、关键里程碑清晰。",
    shouldDo: "锁定 v1、推进交付。",
    shouldNotDo: "再次扩大范围。",
    verification: "v1 是否在 14 日内冻结。" },
  { id: "old_ended", name: "旧项目终止", domain: "feng",
    explanation: "旧结构进入死墓相位。",
    appearance: "停止、归档、转交、关闭。",
    shouldDo: "结清、归档、复盘。",
    shouldNotDo: "拖延、反复回流。",
    verification: "是否完成正式关闭动作。" },
  { id: "identity_shift", name: "身份转折", domain: "shen",
    explanation: "主体身份位被重置或升级。",
    appearance: "新角色、新名片、新场域、新叙事。",
    shouldDo: "重写自我介绍、对齐主线。",
    shouldNotDo: "保留旧身份的承诺与义务。",
    verification: "新身份是否被关键人识别。" },
  { id: "life_change", name: "居住 / 生活变化", domain: "di",
    explanation: "承载场域发生位移。",
    appearance: "搬家、装修、节奏调整、关键消费决策。",
    shouldDo: "稳态优先、节奏先于风格。",
    shouldNotDo: "在过渡期同时启动多个变量。",
    verification: "新节奏是否在 21 日内稳定。" },
  { id: "benefactor", name: "贵人出现", domain: "ren",
    explanation: "正印 / 高位人物结构被激活。",
    appearance: "推荐、点拨、引荐、机会传递。",
    shouldDo: "正式回应、保持联络。",
    shouldNotDo: "把贵人当作主线本身。",
    verification: "是否带来具体的下一步动作。" },
  { id: "obstacle", name: "阻力显化", domain: "feng",
    explanation: "对立结构浮出表面。",
    appearance: "反对、阻拦、误解、否定信号。",
    shouldDo: "确认事实、绕道、降优先级。",
    shouldNotDo: "硬碰、自我攻击。",
    verification: "阻力是否在 7 日内具体化。" },
  { id: "turbulence", name: "乱流风险", domain: "feng",
    explanation: "变局位强烈被激活，信号高度噪声化。",
    appearance: "突发消息、临时变更、情绪剧烈起伏。",
    shouldDo: "降速、不做长期决定。",
    shouldNotDo: "对突发信号做永久判断。",
    verification: "48 小时后信号是否仍然成立。" },
  { id: "main_reset", name: "主线重置", domain: "shen",
    explanation: "主体核心叙事进入空位重启。",
    appearance: "目标质疑、价值排序变化、深层方向调整。",
    shouldDo: "暂缓承诺、记录新假设、保持微动作。",
    shouldNotDo: "在重置期对外宣告大决策。",
    verification: "新主线是否在 30 日内可以一句话说清。" },
];

export const getEventType = (id: string): EventType =>
  EVENT_TYPES.find((e) => e.id === id) ?? EVENT_TYPES[0];
