// 产品术语翻译表 · Product Terminology Map
import type { JargonRisk } from "./jargonRiskLevels";

export interface TerminologyEntry {
  rawTerm: string;
  professionalTerm: string;
  userFriendlyTerm: string;
  actionOrientedTerm: string;
  enterpriseSafeTerm: string;
  educationalExplanation: string;
  microcopy: string;
  difficultyScore: number; // 0-100
  jargonRisk: JargonRisk;
  shouldShowRawTermByDefault: boolean;
}

export const PRODUCT_TERMINOLOGY_MAP: TerminologyEntry[] = [
  {
    rawTerm: "定数计算法",
    professionalTerm: "最终状态判断",
    userFriendlyTerm: "判断这件事定没定",
    actionOrientedTerm: "现在是该行动，还是继续观察",
    enterpriseSafeTerm: "Decision State Evaluation",
    educationalExplanation: "定数计算法用于判断一件事当前是未定、半定、已定、反定还是假定。",
    microcopy: "定没定",
    difficultyScore: 80,
    jargonRisk: "HIGH",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "分支塌缩",
    professionalTerm: "未来分支收束",
    userFriendlyTerm: "可能性正在变成现实",
    actionOrientedTerm: "这条路正在变明确",
    enterpriseSafeTerm: "Scenario Convergence",
    educationalExplanation: "分支塌缩表示多个可能结果中，某一条正在越来越接近现实。",
    microcopy: "方向变明确",
    difficultyScore: 88,
    jargonRisk: "EXTREME",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "信号净化",
    professionalTerm: "信号质量分析",
    userFriendlyTerm: "判断哪些感觉是真的",
    actionOrientedTerm: "先分清真信号和噪声",
    enterpriseSafeTerm: "Signal Quality Check",
    educationalExplanation: "信号净化用于区分真实反馈、情绪噪声、愿望投射和误读。",
    microcopy: "信号可信度",
    difficultyScore: 65,
    jargonRisk: "MEDIUM",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "风域奇点",
    professionalTerm: "终端收束模式",
    userFriendlyTerm: "很多事情最后都指向同一种变化",
    actionOrientedTerm: "你当前容易进入转向期",
    enterpriseSafeTerm: "Trigger Convergence Pattern",
    educationalExplanation: "风域奇点表示多个变量最终集中到变化、转向、破局这一类输出。",
    microcopy: "变化核心",
    difficultyScore: 95,
    jargonRisk: "EXTREME",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "天地人神风",
    professionalTerm: "五域结构",
    userFriendlyTerm: "时间、环境、人、主线和变化",
    actionOrientedTerm: "看时间、环境、人、方向和变化",
    enterpriseSafeTerm: "Five-Factor Decision Map",
    educationalExplanation: "五域用于把一个事件拆成时间、环境、人物、主线与变化五个方面。",
    microcopy: "五方面",
    difficultyScore: 70,
    jargonRisk: "HIGH",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "回验",
    professionalTerm: "反馈校准",
    userFriendlyTerm: "记录后来发生了什么",
    actionOrientedTerm: "回来点一下是否命中",
    enterpriseSafeTerm: "Review Loop",
    educationalExplanation: "回验是记录预测后现实是否发生，以便系统学习和修正。",
    microcopy: "记录结果",
    difficultyScore: 45,
    jargonRisk: "LOW",
    shouldShowRawTermByDefault: true,
  },
  {
    rawTerm: "真实主体",
    professionalTerm: "私有用户模型",
    userFriendlyTerm: "你的个人模型",
    actionOrientedTerm: "创建你的私密模型",
    enterpriseSafeTerm: "Private User Model",
    educationalExplanation: "真实主体指用户自己创建的个人预测模型，与演示数据分开。",
    microcopy: "我的模型",
    difficultyScore: 55,
    jargonRisk: "MEDIUM",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "Full 60",
    professionalTerm: "完整 60 组私有模型",
    userFriendlyTerm: "深度个人模型",
    actionOrientedTerm: "输入完整数列前请确认隐私",
    enterpriseSafeTerm: "Full Private Signal Matrix",
    educationalExplanation: "Full 60 是完整主体模式，包含 60 组五位数字，仅建议深度自用或可信内测使用。",
    microcopy: "深度模型",
    difficultyScore: 75,
    jargonRisk: "HIGH",
    shouldShowRawTermByDefault: true,
  },
  {
    rawTerm: "多计算法内核",
    professionalTerm: "多模型判断核心",
    userFriendlyTerm: "系统会从多个角度一起判断",
    actionOrientedTerm: "综合多个判断后再行动",
    enterpriseSafeTerm: "Multi-Engine Decision Core",
    educationalExplanation: "多计算法内核表示系统不是只用一种方法，而是结合多个判断模块。",
    microcopy: "综合判断",
    difficultyScore: 85,
    jargonRisk: "HIGH",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "事件算法",
    professionalTerm: "事件类型判断",
    userFriendlyTerm: "系统判断可能发生什么事",
    actionOrientedTerm: "看主事件和下一步动作",
    enterpriseSafeTerm: "Event Classification Engine",
    educationalExplanation: "事件算法用于判断当前预测更像事业、关系、身体、产品等哪类事件。",
    microcopy: "可能事件",
    difficultyScore: 68,
    jargonRisk: "MEDIUM",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "提示词计算法",
    professionalTerm: "AI 指令生成策略",
    userFriendlyTerm: "帮你生成下一步给 AI 的指令",
    actionOrientedTerm: "复制这段提示词去继续做",
    enterpriseSafeTerm: "Prompt Strategy Engine",
    educationalExplanation: "提示词计算法用于根据产品状态和目标，生成适合给 AI 工具的提示词。",
    microcopy: "生成指令",
    difficultyScore: 72,
    jargonRisk: "MEDIUM",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "行动许可",
    professionalTerm: "行动建议状态",
    userFriendlyTerm: "现在能不能做",
    actionOrientedTerm: "建议动作",
    enterpriseSafeTerm: "Action Permission",
    educationalExplanation: "行动许可表示系统综合判断后，对当前行动给出的可执行性级别（YES / CAUTION / NO）。",
    microcopy: "可不可做",
    difficultyScore: 58,
    jargonRisk: "MEDIUM",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "主体数列",
    professionalTerm: "个人信号矩阵",
    userFriendlyTerm: "你的数字模型",
    actionOrientedTerm: "请输入你的数字模型",
    enterpriseSafeTerm: "Signal Matrix",
    educationalExplanation: "主体数列是描述用户结构的核心五位数字组合。",
    microcopy: "数字模型",
    difficultyScore: 60,
    jargonRisk: "MEDIUM",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "预测维度",
    professionalTerm: "事件领域分类",
    userFriendlyTerm: "事情类型",
    actionOrientedTerm: "看属于哪类事",
    enterpriseSafeTerm: "Prediction Dimension",
    educationalExplanation: "预测维度用于判断本次预测属于事业、关系、健康、产品等哪一类。",
    microcopy: "事情类型",
    difficultyScore: 62,
    jargonRisk: "MEDIUM",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "地区用户计算法",
    professionalTerm: "地区用户体验适配",
    userFriendlyTerm: "地区体验适配",
    actionOrientedTerm: "选择你所在的地区",
    enterpriseSafeTerm: "Regional UX Adaptation",
    educationalExplanation: "用于根据地区文化、监管与表达习惯，自动调整文案、术语与功能可见度。",
    microcopy: "地区适配",
    difficultyScore: 70,
    jargonRisk: "HIGH",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "软件测试反馈计算法",
    professionalTerm: "产品自检系统",
    userFriendlyTerm: "产品自检",
    actionOrientedTerm: "查看待修复问题",
    enterpriseSafeTerm: "QA Feedback Calculus",
    educationalExplanation: "用于扫描路由、模块、隔离、安全边界、文案与文档一致性，输出修复优先级。",
    microcopy: "产品自检",
    difficultyScore: 65,
    jargonRisk: "MEDIUM",
    shouldShowRawTermByDefault: false,
  },
  {
    rawTerm: "总重新计算算法",
    professionalTerm: "全局状态刷新",
    userFriendlyTerm: "重新计算全部结果",
    actionOrientedTerm: "重新计算",
    enterpriseSafeTerm: "Global Recalculation",
    educationalExplanation: "当核心数据变更后，按依赖关系刷新下游所有模块，保证结果一致。",
    microcopy: "重新计算",
    difficultyScore: 60,
    jargonRisk: "MEDIUM",
    shouldShowRawTermByDefault: true,
  },
  {
    rawTerm: "多用户端 UI 适评算法",
    professionalTerm: "多端 UI 适配评估",
    userFriendlyTerm: "不同用户界面适配",
    actionOrientedTerm: "检查不同设备体验",
    enterpriseSafeTerm: "Multi-Client UI Fit",
    educationalExplanation: "评估不同用户角色、设备与权限下，UI 是否过载、是否暴露高风险功能。",
    microcopy: "界面适配",
    difficultyScore: 65,
    jargonRisk: "MEDIUM",
    shouldShowRawTermByDefault: false,
  },
];

export function findTerm(rawTerm: string): TerminologyEntry | undefined {
  return PRODUCT_TERMINOLOGY_MAP.find((t) => t.rawTerm === rawTerm);
}
