import { VSRRuntimeSession } from '/dist/packages/core/src/index.js';
import { validateDocument, documentHash } from '/dist/packages/spec/src/index.js';
import { VSRHistory } from '/dist/packages/agent-protocol/src/index.js';
import { drawDisplayStateToCanvas } from '/dist/packages/backend-canvas/src/browser.js';
import { RealityOneVSRSession, createRealityOneObserverProfile } from '/dist/packages/adapter-reality-one/src/index.js';

const $=id=>document.getElementById(id);let doc=null,session=null,selectedId=null,time=0,playing=false,lastTick=0,idCounter=1,realitySession=null,realityEvents=[],realityIndex=0,realityTimer=null,currentObserverKind='owner',lastObserverProjection=null;const history=new VSRHistory();
const stage=$('stage'),diagnostics=[];
function blankDoc(){return{specVersion:'0.1',metadata:{id:'untitled-vsr',title:'未命名 VSR 文档',duration:5,defaultFps:30,seed:1},canvas:{width:960,height:540,layoutMode:'responsive',background:{type:'solid',color:'#0b1220'}},variables:{},nodes:[]}}
function setStatus(text,error=false){$('runtimeStatus').textContent=text;$('runtimeStatus').style.color=error?'#ff8f9a':'#7ee3ac'}
function addDiagnostic(text){diagnostics.push(text);$('diagnosticsOutput').textContent=diagnostics.join('\n')||'无诊断。'}
function stopRealityTimer(){if(realityTimer){clearInterval(realityTimer);realityTimer=null;$('autoRealityReplay').textContent='自动回放'}}
function leaveRealityMode(){stopRealityTimer();if(realitySession){realitySession.dispose();realitySession=null}realityEvents=[];realityIndex=0;lastObserverProjection=null;$('liveOutput').textContent='尚未载入实时会话。'}
function rebuildSession(){try{if(realitySession)leaveRealityMode();else session?.dispose();session=new VSRRuntimeSession(doc,{width:doc.canvas.width,height:doc.canvas.height,dpr:1});$('timeSlider').max=String(doc.metadata.duration);$('durationLabel').textContent=`/ ${doc.metadata.duration.toFixed(3)}s`;$('documentTitle').textContent=`${doc.metadata.title} · ${documentHash(doc)}`;setStatus('已求值');render()}catch(e){setStatus('运行时错误',true);addDiagnostic(e.message)}}
function renderLivePanel(result){if(!realitySession)return;const summary=realitySession.currentSummary();const manifest=lastObserverProjection?.manifest;$('documentTitle').textContent=`${doc.metadata.title} · ${summary.status} · ${currentObserverKind}`;$('liveOutput').textContent=JSON.stringify({observer:currentObserverKind,event:`${realityIndex}/${realityEvents.length}`,phase:summary.phase,status:summary.status,progress:summary.progress,authorityStatus:summary.authorityStatus,lastEventType:summary.lastEventType,eventChainRoot:realitySession.eventChainRoot(),stateHash:realitySession.stateHash(),sourceDisplayHash:manifest?.sourceDisplayHash??result?.semanticHash??null,projectedDisplayHash:manifest?.projectedDisplayHash??null,invariantHash:manifest?.invariantHash??null,disclosure:manifest?{shown:manifest.shownNodeIds.length,redacted:manifest.redactedNodeIds.length,hidden:manifest.hiddenNodeIds.length}:null},null,2)}
function render(){if(!doc||!session)return;try{session.clock.seek(time);let result,display;if(realitySession){const set=realitySession.evaluateForObservers([createRealityOneObserverProfile(currentObserverKind)],time);result=set.source;lastObserverProjection=set.projections[0];display=lastObserverProjection.displayState}else{result=session.evaluate(time);display=result.displayState;lastObserverProjection=null}drawDisplayStateToCanvas(display,stage);$('timeSlider').value=String(time);$('timeInput').value=time.toFixed(3);const observerStats=lastObserverProjection?` · 观察者 ${currentObserverKind}：显示 ${lastObserverProjection.manifest.shownNodeIds.length} / 脱敏 ${lastObserverProjection.manifest.redactedNodeIds.length} / 隐藏 ${lastObserverProjection.manifest.hiddenNodeIds.length}`:'';$('runtimeStatus').textContent=`帧 ${display.frame} · ${result.evaluationStats.durationMs.toFixed(2)}ms · 求值重算 ${result.evaluationStats.resolvedNodeCount} / 复用 ${result.evaluationStats.reusedResolvedNodeCount} · 投影重算 ${result.evaluationStats.projectedNodeCount} / 跳过 ${result.evaluationStats.skippedProjectionNodeCount}${observerStats}`;renderTree();renderInspector();renderTimeline();$('jsonEditor').value=JSON.stringify(realitySession?realitySession.snapshotDocument():doc,null,2);renderLivePanel(result);if(display.diagnostics.length)$('diagnosticsOutput').textContent=display.diagnostics.map(d=>`[${d.severity}] ${d.code}: ${d.message}`).join('\n');}catch(e){setStatus('求值失败',true);addDiagnostic(e.message)}}
function renderTree(){$('nodeCount').textContent=`${doc.nodes.length} 节点`;$('sceneTree').innerHTML='';for(const node of doc.nodes){const el=document.createElement('div');el.className=`scene-item ${node.id===selectedId?'selected':''}`;el.innerHTML=`<span>${node.name||node.id}</span><small>${node.type}</small>`;el.onclick=()=>{selectedId=node.id;render()};$('sceneTree').append(el)}}
function selected(){return doc?.nodes.find(n=>n.id===selectedId)}
function renderInspector(){const n=selected();$('selectionTitle').textContent=n?`${n.name||n.id} · ${n.type}`:'未选择节点';for(const id of['propName','propX','propY','propWidth','propHeight','propOpacity'])$(id).disabled=!n;$('propFill').disabled=!n;if(!n)return;$('propName').value=n.name||'';$('propX').value=n.layout?.x??0;$('propY').value=n.layout?.y??0;$('propWidth').value=n.layout?.width??100;$('propHeight').value=n.layout?.height??100;$('propOpacity').value=n.appearance?.opacity??1;$('propFill').value=n.appearance?.fill?.type==='solid'?n.appearance.fill.color:'#4488ff'}
function renderTimeline(){$('timelineTracks').innerHTML='';for(const n of doc.nodes){for(const t of n.tracks||[]){const row=document.createElement('div');row.className='track-row';row.innerHTML=`<span>${n.id} / ${t.property}</span><div class="track-bar"></div>`;const bar=row.querySelector('.track-bar');for(const k of t.keyframes||[]){const dot=document.createElement('i');dot.className='key-dot';dot.style.left=`calc(${Math.min(1,k.time/doc.metadata.duration)*100}% - 5px)`;dot.title=`${k.time}s = ${JSON.stringify(k.value)}`;bar.append(dot)}$('timelineTracks').append(row)}}}
function commit(tx){const result=history.apply(doc,{...tx,baseDocumentHash:documentHash(doc)});if(!result.ok){addDiagnostic(`事务失败：${result.error}`);setStatus('事务失败',true);return false}doc=result.document;$('diffOutput').textContent=JSON.stringify(result.diff,null,2);rebuildSession();return true}
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function parseLength(v){const s=String(v).trim();if(s==='auto'||/%$|vw$|vh$/.test(s))return s;const n=Number(s);return Number.isFinite(n)?n:s}
async function loadRealityOneDemo(){try{if(realitySession)leaveRealityMode();else session?.dispose();const stream=await fetch('/examples/reality-one-lifecycle.events.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()});realityEvents=stream.events||[];realitySession=new RealityOneVSRSession({profile:innerWidth<720?'mobile':'desktop'});doc=realitySession.document;session=realitySession.runtime;selectedId=null;time=0;history.clear();$('timeSlider').max=String(doc.metadata.duration);$('durationLabel').textContent=`/ ${doc.metadata.duration.toFixed(3)}s`;realityIndex=0;currentObserverKind=$('observerProfile').value||'owner';setStatus('实时会话已载入');render()}catch(e){addDiagnostic(`Reality One 演示加载失败：${e.message}`);setStatus('实时演示失败',true)}}
function nextRealityEvent(){if(!realitySession||!realityEvents.length){loadRealityOneDemo();return}if(realityIndex>=realityEvents.length){stopRealityTimer();setStatus('事件流已完成');return}try{realitySession.append(realityEvents[realityIndex++]);render();if(realityIndex>=realityEvents.length){stopRealityTimer();setStatus('事件流已完成')}else setStatus(`事件 ${realityIndex}/${realityEvents.length}`)}catch(e){stopRealityTimer();addDiagnostic(`事件应用失败：${e.message}`);setStatus('事件流错误',true)}}
function resetRealityReplay(){if(!realitySession)return;stopRealityTimer();realitySession.reset();realityIndex=0;render();setStatus('事件流已重置')}
function toggleRealityReplay(){if(!realitySession){loadRealityOneDemo();return}if(realityTimer){stopRealityTimer();setStatus('自动回放已暂停');return}$('autoRealityReplay').textContent='暂停回放';realityTimer=setInterval(nextRealityEvent,650);nextRealityEvent()}

$('newDoc').onclick=()=>{doc=blankDoc();selectedId=null;time=0;history.clear();rebuildSession()};
$('openDoc').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{doc=JSON.parse(await file.text());selectedId=null;time=0;history.clear();rebuildSession()}catch(err){addDiagnostic(`打开失败：${err.message}`)}};
$('saveDoc').onclick=()=>{const target=realitySession?realitySession.snapshotDocument():doc;download(`${target.metadata.id}.vsr.json`,new Blob([JSON.stringify(target,null,2)],{type:'application/json'}));};
$('loadExample').onclick=async()=>{try{doc=await fetch('/examples/hello-title.vsr.json',{cache:'no-store'}).then(r=>r.json());selectedId='title';time=0;history.clear();rebuildSession()}catch(e){addDiagnostic(`示例加载失败：${e.message}`)}};
$('validateDoc').onclick=()=>{const r=validateDocument(doc);$('diagnosticsOutput').textContent=r.diagnostics.length?r.diagnostics.map(d=>`[${d.severity}] ${d.code}: ${d.message}`).join('\n'):'校验通过：无诊断。';setStatus(r.ok?'校验通过':'校验失败',!r.ok)};
$('play').onclick=()=>{playing=true;lastTick=performance.now();setStatus('播放中')};$('pause').onclick=()=>{playing=false;setStatus('已暂停')};$('stop').onclick=()=>{playing=false;time=0;render();setStatus('已停止')};
$('prevFrame').onclick=()=>{time=Math.max(0,time-1/doc.metadata.defaultFps);render()};$('nextFrame').onclick=()=>{time=Math.min(doc.metadata.duration,time+1/doc.metadata.defaultFps);render()};
$('timeSlider').oninput=e=>{time=Number(e.target.value);render()};$('timeInput').onchange=e=>{time=Math.max(0,Math.min(doc.metadata.duration,Number(e.target.value)||0));render()};
$('addRect').onclick=()=>{const id=`rect-${idCounter++}`;commit({transactionId:`add-${id}`,operations:[{type:'addNode',node:{id,type:'rect',name:'新矩形',layout:{x:100+idCounter*8,y:100+idCounter*8,width:180,height:100},appearance:{fill:{type:'solid',color:'#318cff'},opacity:1},content:{cornerRadius:14}}}]});selectedId=id;render()};
$('duplicateNode').onclick=()=>{const n=selected();if(!n)return;const id=`${n.id}-copy-${idCounter++}`;if(commit({transactionId:`duplicate-${id}`,operations:[{type:'duplicateNode',nodeId:n.id,newNodeId:id}]})){selectedId=id;render()}};
$('deleteNode').onclick=()=>{const n=selected();if(!n)return;if(commit({transactionId:`delete-${n.id}`,operations:[{type:'removeNode',nodeId:n.id,cascade:true}]})){selectedId=null;render()}};
$('undo').onclick=()=>{const r=history.undo(doc);if(r?.ok){doc=r.document;rebuildSession()}};$('redo').onclick=()=>{const r=history.redo(doc);if(r?.ok){doc=r.document;rebuildSession()}};
$('applyProperties').onclick=()=>{const n=selected();if(!n)return;commit({transactionId:`props-${n.id}-${idCounter++}`,operations:[{type:'updateNode',nodeId:n.id,path:'name',value:$('propName').value},{type:'updateNode',nodeId:n.id,path:'layout.x',value:parseLength($('propX').value)},{type:'updateNode',nodeId:n.id,path:'layout.y',value:parseLength($('propY').value)},{type:'updateNode',nodeId:n.id,path:'layout.width',value:parseLength($('propWidth').value)},{type:'updateNode',nodeId:n.id,path:'layout.height',value:parseLength($('propHeight').value)},{type:'updateNode',nodeId:n.id,path:'appearance.opacity',value:Number($('propOpacity').value)},{type:'updateNode',nodeId:n.id,path:'appearance.fill',value:{type:'solid',color:$('propFill').value}}]})};
$('addKeyframe').onclick=()=>{const n=selected();if(!n)return;let t=n.tracks?.find(t=>t.property==='appearance.opacity');const operations=[];if(!t){t={id:`opacity-${n.id}`,property:'appearance.opacity',mode:'keyframes',keyframes:[]};operations.push({type:'addTrack',nodeId:n.id,track:t})}operations.push({type:'addKeyframe',nodeId:n.id,trackId:t.id,keyframe:{id:`kf-${idCounter++}`,time,value:n.appearance?.opacity??1,easing:'easeInOut'}});commit({transactionId:`keyframe-${n.id}-${idCounter}`,operations})};
$('removeKeyframe').onclick=()=>{const n=selected();const t=n?.tracks?.find(t=>t.property==='appearance.opacity'&&t.keyframes?.length);const k=t?.keyframes?.at(-1);if(n&&t&&k)commit({transactionId:`remove-kf-${k.id}`,operations:[{type:'removeKeyframe',nodeId:n.id,trackId:t.id,keyframeId:k.id}]})};
$('applyJson').onclick=()=>{try{const next=JSON.parse($('jsonEditor').value);commit({transactionId:`json-${idCounter++}`,operations:[{type:'replaceDocument',document:next}]})}catch(e){addDiagnostic(`JSON 失败：${e.message}`)}};
$('transactionEditor').value=JSON.stringify({transactionId:'agent-demo',operations:[{type:'setVariable',name:'headline',value:'AGENT UPDATED VSR'}]},null,2);
$('applyTransaction').onclick=()=>{try{commit(JSON.parse($('transactionEditor').value))}catch(e){addDiagnostic(`事务 JSON 失败：${e.message}`)}};
$('exportPng').onclick=()=>stage.toBlob(blob=>{if(blob){download(`${doc.metadata.id}-${time.toFixed(3)}.png`,blob);$('outputReport').textContent=`已导出当前帧：${time.toFixed(3)}s\n${stage.width} × ${stage.height}`}},'image/png');
$('renderRange').onclick=()=>{const fps=Math.min(doc.metadata.defaultFps,30),frames=[];for(let i=0;i<=Math.floor(doc.metadata.duration*fps);i++){const t=i/fps;frames.push({frame:i,time:t,semanticHash:session.evaluate(t).semanticHash})}download(`${doc.metadata.id}-range-manifest.json`,new Blob([JSON.stringify({documentHash:documentHash(doc),fps,frames},null,2)],{type:'application/json'}));$('outputReport').textContent=`浏览器已验证 ${frames.length} 个逻辑帧并导出语义清单。\n像素序列与视频请使用 CLI render-range / encode。`};
$('loadRealityDemo').onclick=loadRealityOneDemo;$('nextRealityEvent').onclick=nextRealityEvent;$('autoRealityReplay').onclick=toggleRealityReplay;$('resetRealityReplay').onclick=resetRealityReplay;$('observerProfile').onchange=e=>{currentObserverKind=e.target.value;render();setStatus(`已切换观察者：${currentObserverKind}`)};$('exportRealitySnapshot').onclick=()=>{if(!realitySession)return;const snapshot=realitySession.snapshotDocument();download(`${snapshot.metadata.id}.vsr.json`,new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}));};
$('clearDiagnostics').onclick=()=>{diagnostics.length=0;$('diagnosticsOutput').textContent='无诊断。'};
for(const tab of document.querySelectorAll('.tab'))tab.onclick=()=>{document.querySelectorAll('.tab,.tab-body').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(tab.dataset.tab+'Tab').classList.add('active')};
function tick(now){if(playing&&doc){const dt=(now-lastTick)/1000;lastTick=now;time+=dt;if(time>=doc.metadata.duration){time=doc.metadata.duration;playing=false}render()}requestAnimationFrame(tick)}requestAnimationFrame(tick);
window.addEventListener('pointermove',e=>{if(session){const r=stage.getBoundingClientRect();session.setInput({pointerX:(e.clientX-r.left)/r.width*doc.canvas.width,pointerY:(e.clientY-r.top)/r.height*doc.canvas.height});if(playing)render()}});
doc=blankDoc();rebuildSession();
