import test from 'node:test';
import assert from 'node:assert/strict';
import {createProductionSoundScene,createSoundScene,renderAudioScene,validateAudioScene} from '../src/index.mjs';
import {createAnimeProduction} from '../../anime-production-runtime/src/index.mjs';
import {generateVoicePerformance} from '../../voice-performance-runtime/src/index.mjs';

test('Audio Forge writes dialogue, ambience, foley, sfx, music and master stems',()=>{const voice=generateVoicePerformance({dialogue_event_id:'dialogue:one',character_id:'character:blue',voice_identity:'default',text:'何罪之有？'});const cut={cut_id:'S01',duration:5,voice_track:[{dialogue_event_id:'dialogue:one',active:true}],ambience_track:[{cue_id:'ambience:cold-wind',sound:'cold_wind'}],foley_track:[{cue_id:'foley:chain',sound:'distant_chain'}],sfx_track:[],music_track:[]};const scene=createSoundScene({productionId:'production:one',cut,voiceBundle:voice.bundle});const result=renderAudioScene(scene,{voiceWav:voice.wav});assert.equal(validateAudioScene(scene,result.report).valid,true);assert.deepEqual(Object.keys(result.buffers).sort(),['ambience','dialogue','foley','master','music','sfx']);assert.notEqual(result.report.stems.master.root,result.report.stems.dialogue.root)});
test('Audio Forge permits distinct dialogue events and rejects duplicate active takes for one event',()=>{assert.doesNotThrow(()=>createSoundScene({productionId:'production:one',cut:{cut_id:'S01',duration:1,voice_track:[{dialogue_event_id:'a',active:true},{dialogue_event_id:'b',active:true}]}}));assert.throws(()=>createSoundScene({productionId:'production:one',cut:{cut_id:'S01',duration:1,voice_track:[{dialogue_event_id:'a',active:true},{dialogue_event_id:'a',active:true}]}}),/MULTIPLE_DIALOGUE_AUTHORITY:a/)});

test('Audio Forge places two Cut-local voices on the authoritative editorial timeline',()=>{const cutBase={fps:10,resolution:{width:320,height:180},mode:'native-2d',background_layers:[],character_layers:[],animation:{exposure:'on_twos'}},production=createAnimeProduction({production_id:'production:editorial',cuts:[{...cutBase,episode_id:'EP01',scene_id:'court',cut_id:'S01',duration:1,voice_track:[{dialogue_event_id:'a',active:true}]},{...cutBase,episode_id:'EP01',scene_id:'court',cut_id:'S02',duration:1,voice_track:[{dialogue_event_id:'b',active:true}]}]}),a=generateVoicePerformance({dialogue_event_id:'a',character_id:'one',text:'甲',start_seconds:.25}),b=generateVoicePerformance({dialogue_event_id:'b',character_id:'one',text:'乙',start_seconds:.2}),scene=createProductionSoundScene({production,voiceBundles:[a.bundle,b.bundle]}),rendered=renderAudioScene(scene,{voiceWavs:new Map([['a',a.wav],['b',b.wav]])});assert.equal(scene.duration_seconds,2);assert.deepEqual(scene.dialogue_stems.map(stem=>stem.start_seconds),[.25,1.2]);assert.equal(rendered.report.dialogue_placements.every(item=>item.rendered),true);assert.equal(validateAudioScene(scene,rendered.report).valid,true);const firstSample=44+Math.floor(.25*scene.sample_rate)*2,secondSample=44+Math.floor(1.2*scene.sample_rate)*2;assert.ok(rendered.buffers.dialogue.subarray(firstSample,firstSample+4000).some(value=>value!==0));assert.ok(rendered.buffers.dialogue.subarray(secondSample,secondSample+4000).some(value=>value!==0))});
