import fs from 'node:fs';
import path from 'node:path';
import {compileAnimeSource,tryCompileAnimeSource,bindVoicePerformance} from './compiler.mjs';
import {buildAnimeEpisodeMedia} from './media-pipeline.mjs';
import {canonicalCutRef,listProductionCuts,resolveProductionCut,validateAnimeProduction,buildExposureSheet,buildProductionExposureSheets,validateExposureSheet,validateProductionExposureSheets,renderProduction,replayProduction,muxEpisodeWithFfmpeg} from '../../../world/anime-production-runtime/src/index.mjs';
import {generateVoicePerformance,validateVoicePerformance} from '../../../world/voice-performance-runtime/src/index.mjs';
import {createProductionSoundScene,renderAudioScene,validateAudioScene} from '../../../world/audio-scene-runtime/src/index.mjs';

const args=process.argv.slice(2),command=args[0];
function flag(name,fallback=null){const index=args.indexOf(`--${name}`);return index>=0?(args[index+1]??true):fallback}
function positional(index=1){return args.filter(item=>!item.startsWith('--')&&!args.includes(`--${item}`))[index]??args[index]}
function json(value){process.stdout.write(`${JSON.stringify(value,null,2)}\n`)}
function readJson(file){return JSON.parse(fs.readFileSync(file,'utf8'))}
function writeJson(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(value,null,2))}
function readProduction(file){const value=readJson(file);return value.production??value}
function errorResult(error){json({ok:false,error:{code:error.code??'RNCS_ANIME_CLI_ERROR',message:error.message,location:error.location??null,details:error.details??{}}});process.exitCode=1}
const safeSegment=value=>String(value).replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,80)||'anime';
function assetFamilyEntries(families={}){const entries=[],seen=new Set();const visit=(value,name)=>{if(value?.family?.family_root){if(!seen.has(value.family.family_root)){seen.add(value.family.family_root);entries.push([name,value])}return}if(value&&typeof value==='object')for(const[key,child]of Object.entries(value))visit(child,`${name}-${key}`)};for(const[name,value]of Object.entries(families))visit(value,name);return entries}
function findFiles(root,name){if(!fs.existsSync(root))return[];const found=[];for(const entry of fs.readdirSync(root,{withFileTypes:true})){const file=path.join(root,entry.name);if(entry.isDirectory())found.push(...findFiles(file,name));else if(entry.name===name)found.push(file)}return found}
function exportMp4(workspace){const manifest=readJson(path.join(workspace,'frames-manifest.json')),result=muxEpisodeWithFfmpeg({buildDir:workspace,framesDir:path.join(workspace,'frames'),audioFile:path.join(workspace,'audio','master.wav'),outFile:path.join(workspace,'episode.mp4'),frameManifest:manifest,ffmpegPath:String(flag('ffmpeg',process.env.FFMPEG_PATH??'ffmpeg')),ffprobePath:String(flag('ffprobe',process.env.FFPROBE_PATH??'ffprobe'))});writeJson(path.join(workspace,'export-report.json'),result.report);if(result.probe_report)writeJson(path.join(workspace,'ffprobe-report.json'),result.probe_report);return{...result.report,output:result.ok?path.join(workspace,'episode.mp4'):null}}

try{
  if(!command)throw Object.assign(new Error('Usage: rncs-anime <validate|compile|inspect|select-cut|xsheet|voice|render|mix|media|export|verify|replay|snapshot|rollback> ...'),{code:'USAGE'});
  if(command==='validate'){
    const sourceFile=args[1];if(!sourceFile)throw Object.assign(new Error('RCL anime source required'),{code:'SOURCE_REQUIRED'});const result=tryCompileAnimeSource(fs.readFileSync(sourceFile,'utf8'));json({ok:result.ok,diagnostics:result.diagnostics??[],production:result.ok?{production_id:result.production.production_id,production_root:result.production.production_root,cut_count:result.production.editorial_timeline.cut_count,total_frame_count:result.production.editorial_timeline.total_frame_count}:null});if(!result.ok)process.exitCode=1;
  }else if(command==='compile'){
    const sourceFile=args[1],out=path.resolve(String(flag('out','output/anime-forge')));const compiled=compileAnimeSource(fs.readFileSync(sourceFile,'utf8'));fs.mkdirSync(out,{recursive:true});fs.copyFileSync(sourceFile,path.join(out,'source.anime.rcl'));writeJson(path.join(out,'production.ir.json'),compiled.production);writeJson(path.join(out,'source-map.json'),compiled.source_map);fs.writeFileSync(path.join(out,'program.rbc'),compiled.bytecode);fs.writeFileSync(path.join(out,'shadow.rcl'),compiled.shadow_rcl);for(const [familyName,family] of assetFamilyEntries(compiled.asset_families)){const familyDir=path.join(out,'assets',safeSegment(familyName));fs.mkdirSync(familyDir,{recursive:true});for(const [fileName,file] of Object.entries(family.files??{}))fs.writeFileSync(path.join(familyDir,fileName),file.content);writeJson(path.join(familyDir,'family.json'),family.family)}const report={format:'rncs.anime-compile-report.v0.1',compiled_root:compiled.compiled_root,production_root:compiled.production.production_root,bytecode_root:compiled.bytecode_root,bytecode_length:compiled.bytecode_length,source_root:compiled.source_root,cut_count:compiled.production.editorial_timeline.cut_count,total_frame_count:compiled.production.editorial_timeline.total_frame_count,asset_family_roots:Object.fromEntries(assetFamilyEntries(compiled.asset_families).map(([name,value])=>[name,value.family.family_root])),output:out,phase:'phase-4-media-closure',status:'active',next_phase:'human-direction-and-external-provider-quality'};writeJson(path.join(out,'compile-report.json'),report);json({ok:true,...report});
  }else if(command==='inspect'){
    const production=readProduction(args[1]),validation=validateAnimeProduction(production);json({ok:validation.valid,format:production.format,series:production.series,episode:production.episode,active_cut_ref:production.active_cut_ref,cut_count:validation.cut_count,total_frame_count:validation.total_frame_count,cuts:listProductionCuts(production).map(cut=>({cut_ref:canonicalCutRef(cut),id:cut.cut_id,episode_id:cut.episode_id,scene_id:cut.scene_id,duration:cut.duration,fps:cut.fps,resolution:cut.resolution,mode:cut.mode,frame_count:Math.round(cut.duration*cut.fps),tracks:Object.fromEntries(Object.entries(cut).filter(([,value])=>Array.isArray(value)).map(([key,value])=>[key,value.length]))})),editorial_timeline:production.editorial_timeline,production_root:production.production_root,validation});
  }else if(command==='select-cut'){
    const ir=args[1],production=readProduction(ir),cut=resolveProductionCut(production,String(flag('cut',''))),selection={format:'rncs.anime-cut-inspection-selection.v0.1',production_root:production.production_root,episode_intent_root:production.episode_intent_root,active_cut_ref:canonicalCutRef(cut),cut_id:cut.cut_id,authority:'inspection-only',production_mutated:false},out=flag('out');if(out)writeJson(path.resolve(String(out)),selection);json({ok:true,out:out?path.resolve(String(out)):null,...selection});
  }else if(command==='xsheet'){
    const production=readProduction(args[1]),all=Boolean(flag('all',false)),cut=all?null:resolveProductionCut(production,flag('cut',production.active_cut_ref)),cutRef=cut?canonicalCutRef(cut):null,sheet=all?buildProductionExposureSheets(production):buildExposureSheet(cut,{motionProfile:production.motion_profiles?.[cutRef],renderProfile:production.rendering_profiles?.[cutRef],compositionContract:production.composition_contract}),out=flag('out');if(out)writeJson(path.resolve(out),sheet);json(sheet);
  }else if(command==='voice'){
    const ir=args[1],production=readProduction(ir),requested=flag('dialogue'),located=listProductionCuts(production).map(cut=>({cut,dialogue:cut.dialogue_track.find(item=>item.dialogue_event_id===requested)})).find(item=>item.dialogue),cut=located?.cut??resolveProductionCut(production,flag('cut',production.active_cut_ref)),dialogue=located?.dialogue??cut.dialogue_track[0];if(!dialogue)throw new Error('DIALOGUE_EVENT_REQUIRED');const out=path.resolve(String(flag('out',path.join(path.dirname(ir),'audio','voice',safeSegment(dialogue.dialogue_event_id))))),voice=generateVoicePerformance({dialogue_event_id:dialogue.dialogue_event_id,character_id:dialogue.actor_id,voice_identity:dialogue.voice_identity,text:dialogue.text,language:'zh-CN',emotion:dialogue.emotion,start_seconds:dialogue.start_frame/cut.fps},{outDir:out});const bound=bindVoicePerformance(production,voice.bundle),updated=path.join(path.dirname(ir),'production.voice-bound.ir.json');writeJson(updated,bound);json({ok:validateVoicePerformance(voice.bundle).valid,cut_ref:canonicalCutRef(cut),voice_root:voice.bundle.bundle_root,out,updated_ir:updated,duration_seconds:voice.bundle.duration_seconds});
  }else if(command==='render'){
    const ir=args[1],production=readProduction(ir),out=path.resolve(String(flag('out',path.join(path.dirname(ir),'render')))),quality=String(flag('quality','preview'));writeJson(path.join(out,'production.ir.json'),production);const result=renderProduction(production,{outDir:out,quality,maxFrames:flag('max-frames')?Number(flag('max-frames')):null});json({ok:true,out,quality,cut_count:result.manifest.cut_count,rendered_frames:result.manifest.rendered_frame_count,expected_frames:result.manifest.expected_frame_count,status:result.manifest.status,sequence_root:result.manifest.sequence_root});
  }else if(command==='mix'){
    const workspace=path.resolve(args[1]),production=readProduction(path.join(workspace,'production.ir.json')),voiceFiles=findFiles(path.join(workspace,'..','audio','voice'),'bundle.json'),voices=voiceFiles.map(readJson),voiceWavs=new Map(voiceFiles.map((file,index)=>[voices[index].dialogue_event_id,fs.readFileSync(path.join(path.dirname(file),'dialogue.wav'))])),scene=createProductionSoundScene({production,voiceBundles:voices}),out=path.join(workspace,'audio'),audio=renderAudioScene(scene,{voiceWavs,outDir:out});json({ok:validateAudioScene(scene,audio.report).valid,audio_root:audio.report.audio_root,dialogue_count:scene.dialogue_stems.length,out});
  }else if(command==='media'){
    const sourceFile=path.resolve(args[1]),out=path.resolve(String(flag('out','output/anime-forge-phase4'))),result=buildAnimeEpisodeMedia({sourceFile,outDir:out,quality:String(flag('quality','preview')),ffmpegPath:String(flag('ffmpeg',process.env.FFMPEG_PATH??'ffmpeg')),ffprobePath:String(flag('ffprobe',process.env.FFPROBE_PATH??'ffprobe'))});json({ok:result.ok,status:result.status,out,production_root:result.production.production_root,duration_seconds:result.summary.duration_seconds,frame_count:result.summary.frame_count,cut_count:result.summary.cut_count,mp4:result.summary.mp4,evidence_ledger_root:result.ledger.ledger_root,gates:result.ledger.gates});if(!result.ok)process.exitCode=1;
  }else if(command==='export'){
    const report=exportMp4(path.resolve(args[1]));json({ok:report.status==='complete',...report});if(report.status!=='complete')process.exitCode=1;
  }else if(command==='verify'){
    const workspace=path.resolve(args[1]),production=readProduction(path.join(workspace,'production.ir.json')),manifest=readJson(path.join(workspace,'frames-manifest.json')),xsheets=readJson(path.join(workspace,'xsheets.json')),pv=validateAnimeProduction(production),xv=validateProductionExposureSheets(xsheets),missing=manifest.frames.filter(frame=>!fs.existsSync(path.join(workspace,frame.filename))),audioReport=fs.existsSync(path.join(workspace,'audio','audio-report.json'))?readJson(path.join(workspace,'audio','audio-report.json')):null,exportReport=fs.existsSync(path.join(workspace,'export-report.json'))?readJson(path.join(workspace,'export-report.json')):null,ledgerFile=path.join(workspace,'evidence-ledger.json'),ledger=fs.existsSync(ledgerFile)?readJson(ledgerFile):null,errors=[...pv.errors,...xv.errors,...missing.map(frame=>`FRAME_MISSING:${frame.global_frame_number}`)];if(manifest.rendered_frame_count!==manifest.expected_frame_count)errors.push('FRAME_COUNT_INCOMPLETE');if(!ledger)errors.push('EVIDENCE_LEDGER_MISSING');else if(ledger.ledger_root!==manifest.evidence_ledger_root)errors.push('EVIDENCE_LEDGER_ROOT_MISMATCH');json({ok:errors.length===0,errors,warnings:[...(pv.warnings??[]),...(exportReport?.status==='blocked'?['MP4_ENCODER_UNAVAILABLE']:[])],production_root:production.production_root,timeline_root:production.editorial_timeline.timeline_root,sequence_root:manifest.sequence_root,evidence_ledger_root:ledger?.ledger_root??null,audio_root:audioReport?.audio_root??null,export:exportReport});if(errors.length)process.exitCode=1;
  }else if(command==='replay'){
    const workspace=path.resolve(args[1]),production=readProduction(path.join(workspace,'production.ir.json')),manifest=readJson(path.join(workspace,'frames-manifest.json')),result=replayProduction(production,manifest);writeJson(path.join(workspace,'replay-report.json'),result);json({ok:result.valid,...result});if(!result.valid)process.exitCode=1;
  }else if(command==='snapshot'){
    const workspace=path.resolve(args[1]),id=safeSegment(flag('id',`snapshot-${Date.now()}`)),source=path.join(workspace,'production.ir.json'),snapshotDir=path.join(workspace,'snapshots'),snapshot=path.join(snapshotDir,`${id}.json`);fs.mkdirSync(snapshotDir,{recursive:true});writeJson(snapshot,{format:'rncs.anime-snapshot.v0.1',snapshot_id:id,production:readProduction(source),frames_manifest:fs.existsSync(path.join(workspace,'frames-manifest.json'))?readJson(path.join(workspace,'frames-manifest.json')):null});json({ok:true,snapshot});
  }else if(command==='rollback'){
    const workspace=path.resolve(args[1]),requestedSnapshot=String(flag('snapshot',''));if(!requestedSnapshot)throw Object.assign(new Error('Snapshot not found'),{code:'SNAPSHOT_NOT_FOUND'});const snapshotId=safeSegment(requestedSnapshot),snapshot=path.join(workspace,'snapshots',`${snapshotId}.json`);if(!fs.existsSync(snapshot))throw Object.assign(new Error('Snapshot not found'),{code:'SNAPSHOT_NOT_FOUND'});const value=readJson(snapshot);writeJson(path.join(workspace,'production.ir.json'),value.production);const receipt={format:'rncs.anime-rollback-receipt.v0.1',snapshot_id:snapshotId,production_root:value.production.production_root,status:'restored-authoring-state',next_action:'re-render affected Cut',frames_preserved:false};writeJson(path.join(workspace,'rollback-receipt.json'),receipt);json({ok:true,...receipt});
  }else throw Object.assign(new Error(`Unknown command: ${command}`),{code:'COMMAND_UNKNOWN'});
}catch(error){errorResult(error)}
