import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {compileAnimeSource,tryCompileAnimeSource,bindVoicePerformance} from './compiler.mjs';
import {validateAnimeProduction,buildExposureSheet,validateExposureSheet,renderCut,replayCut} from '../../../world/anime-production-runtime/src/index.mjs';
import {generateVoicePerformance,validateVoicePerformance} from '../../../world/voice-performance-runtime/src/index.mjs';
import {createSoundScene,renderAudioScene,validateAudioScene} from '../../../world/audio-scene-runtime/src/index.mjs';

const args=process.argv.slice(2),command=args[0];
function flag(name,fallback=null){const index=args.indexOf(`--${name}`);return index>=0?(args[index+1]??true):fallback}
function positional(index=1){return args.filter(item=>!item.startsWith('--')&&!args.includes(`--${item}`))[index]??args[index]}
function json(value){process.stdout.write(`${JSON.stringify(value,null,2)}\n`)}
function readJson(file){return JSON.parse(fs.readFileSync(file,'utf8'))}
function writeJson(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(value,null,2))}
function readProduction(file){const value=readJson(file);return value.production??value}
function errorResult(error){json({ok:false,error:{code:error.code??'RNCS_ANIME_CLI_ERROR',message:error.message,location:error.location??null,details:error.details??{}}});process.exitCode=1}
function hasFfmpeg(){return spawnSync('ffmpeg',['-version'],{encoding:'utf8'}).status===0}
function exportMp4(workspace){const reportPath=path.join(workspace,'export-report.json'),manifest=readJson(path.join(workspace,'frames-manifest.json')),audio=path.join(workspace,'audio','master.wav'),output=path.join(workspace,'final.mp4');if(!hasFfmpeg()){const report={format:'rncs.anime-export-report.v0.1',status:'blocked',code:'MP4_ENCODER_UNAVAILABLE',requested_format:'mp4',frame_sequence:path.join(workspace,'frames'),audio:fs.existsSync(audio)?audio:null,encoder:'ffmpeg',boundary:'No static or fake MP4 is emitted.'};writeJson(reportPath,report);return report}const result=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-y','-framerate',String(manifest.fps),'-i',path.join(workspace,'frames','frame-%06d.png'),...(fs.existsSync(audio)?['-i',audio]:[]),'-c:v','libx264','-pix_fmt','yuv420p',...(fs.existsSync(audio)?['-c:a','aac','-b:a','128k','-shortest']:[]),output],{encoding:'utf8'});const report={format:'rncs.anime-export-report.v0.1',status:result.status===0&&fs.existsSync(output)?'complete':'failed',code:result.status===0?'OK':'MP4_ENCODING_FAILED',output:fs.existsSync(output)?output:null,stderr:String(result.stderr??'').slice(-4000),encoder:'ffmpeg'};writeJson(reportPath,report);return report}

try{
  if(!command)throw Object.assign(new Error('Usage: rncs-anime <validate|compile|inspect|xsheet|voice|render|mix|export|verify|replay|snapshot|rollback> ...'),{code:'USAGE'});
  if(command==='validate'){
    const sourceFile=args[1];if(!sourceFile)throw Object.assign(new Error('RCL anime source required'),{code:'SOURCE_REQUIRED'});const result=tryCompileAnimeSource(fs.readFileSync(sourceFile,'utf8'));json({ok:result.ok,diagnostics:result.diagnostics??[],production:result.ok?{production_id:result.production.production_id,production_root:result.production.production_root,cut_id:result.production.cut.cut_id,frame_count:Math.round(result.production.cut.duration*result.production.cut.fps)}:null});if(!result.ok)process.exitCode=1;
  }else if(command==='compile'){
    const sourceFile=args[1],out=path.resolve(String(flag('out','output/anime-forge')));const compiled=compileAnimeSource(fs.readFileSync(sourceFile,'utf8'));fs.mkdirSync(out,{recursive:true});fs.copyFileSync(sourceFile,path.join(out,'source.anime.rcl'));writeJson(path.join(out,'production.ir.json'),compiled.production);writeJson(path.join(out,'source-map.json'),compiled.source_map);fs.writeFileSync(path.join(out,'program.rbc'),compiled.bytecode);fs.writeFileSync(path.join(out,'shadow.rcl'),compiled.shadow_rcl);for(const [familyName,family] of Object.entries(compiled.asset_families??{})){const familyDir=path.join(out,'assets',familyName);fs.mkdirSync(familyDir,{recursive:true});for(const [fileName,file] of Object.entries(family.files??{}))fs.writeFileSync(path.join(familyDir,fileName),file.content);writeJson(path.join(familyDir,'family.json'),family.family)}const report={format:'rncs.anime-compile-report.v0.1',compiled_root:compiled.compiled_root,production_root:compiled.production.production_root,bytecode_root:compiled.bytecode_root,bytecode_length:compiled.bytecode_length,source_root:compiled.source_root,asset_family_roots:Object.fromEntries(Object.entries(compiled.asset_families??{}).map(([name,value])=>[name,value.family.family_root])),output:out,phase:'phase-1-foundation-plus-phase-2-runtime-contracts',status:'active',next_phase:'provider-parity-and-editorial-expansion'};writeJson(path.join(out,'compile-report.json'),report);json({ok:true,...report});
  }else if(command==='inspect'){
    const production=readProduction(args[1]);const validation=validateAnimeProduction(production);json({ok:validation.valid,format:production.format,series:production.series,episode:production.episode,scene:production.scene,cut:{id:production.cut.cut_id,duration:production.cut.duration,fps:production.cut.fps,resolution:production.cut.resolution,mode:production.cut.mode,frame_count:validation.frame_count,tracks:Object.fromEntries(Object.entries(production.cut).filter(([,value])=>Array.isArray(value)).map(([key,value])=>[key,value.length]))},production_root:production.production_root,validation});
  }else if(command==='xsheet'){
    const production=readProduction(args[1]),sheet=buildExposureSheet(production.cut),out=flag('out');if(out)writeJson(path.resolve(out),sheet);json(sheet);
  }else if(command==='voice'){
    const ir=args[1],production=readProduction(ir),dialogue=production.cut.dialogue_track.find(item=>item.dialogue_event_id===flag('dialogue'))??production.cut.dialogue_track[0];if(!dialogue)throw new Error('DIALOGUE_EVENT_REQUIRED');const out=path.resolve(String(flag('out',path.join(path.dirname(ir),'audio','voice')))),voice=generateVoicePerformance({dialogue_event_id:dialogue.dialogue_event_id,character_id:dialogue.actor_id,voice_identity:dialogue.voice_identity,text:dialogue.text,language:'zh-CN',emotion:dialogue.emotion,start_seconds:dialogue.start_frame/production.cut.fps},{outDir:out});const bound=bindVoicePerformance(production,voice.bundle);writeJson(path.join(path.dirname(ir),'production.voice-bound.ir.json'),bound);json({ok:validateVoicePerformance(voice.bundle).valid,voice_root:voice.bundle.bundle_root,out,updated_ir:path.join(path.dirname(ir),'production.voice-bound.ir.json'),duration_seconds:voice.bundle.duration_seconds});
  }else if(command==='render'){
    const ir=args[1],production=readProduction(ir),out=path.resolve(String(flag('out',path.join(path.dirname(ir),'render')))),quality=String(flag('quality','preview'));writeJson(path.join(out,'production.ir.json'),production);const result=renderCut(production,{outDir:out,quality,maxFrames:flag('max-frames')?Number(flag('max-frames')):null});json({ok:true,out,quality,rendered_frames:result.manifest.rendered_frame_count,sequence_root:result.manifest.sequence_root});
  }else if(command==='mix'){
    const workspace=path.resolve(args[1]),production=readProduction(path.join(workspace,'production.ir.json')),voiceFile=path.join(workspace,'..','audio','voice','bundle.json'),voice=fs.existsSync(voiceFile)?readJson(voiceFile):null,scene=createSoundScene({productionId:production.production_id,cut:production.cut,voiceBundle:voice}),out=path.join(workspace,'audio'),audio=renderAudioScene(scene,{voiceWav:voice?fs.readFileSync(path.join(path.dirname(voiceFile),'dialogue.wav')):null,outDir:out});json({ok:validateAudioScene(scene,audio.report).valid,audio_root:audio.report.audio_root,out});
  }else if(command==='export'){
    const report=exportMp4(path.resolve(args[1]));json({ok:report.status==='complete',...report});if(report.status!=='complete')process.exitCode=1;
  }else if(command==='verify'){
    const workspace=path.resolve(args[1]),production=readProduction(path.join(workspace,'production.ir.json')),manifest=readJson(path.join(workspace,'frames-manifest.json')),xsheet=readJson(path.join(workspace,'xsheet.json')),pv=validateAnimeProduction(production),xv=validateExposureSheet(xsheet),missing=manifest.frames.filter(frame=>!fs.existsSync(path.join(workspace,frame.filename))),audioReport=fs.existsSync(path.join(workspace,'audio','audio-report.json'))?readJson(path.join(workspace,'audio','audio-report.json')):null,exportReport=fs.existsSync(path.join(workspace,'export-report.json'))?readJson(path.join(workspace,'export-report.json')):null,ledgerFile=path.join(workspace,'evidence-ledger.json'),ledger=fs.existsSync(ledgerFile)?readJson(ledgerFile):null,errors=[...pv.errors,...xv.errors,...missing.map(frame=>`FRAME_MISSING:${frame.frame_number}`)];if(manifest.rendered_frame_count!==manifest.expected_frame_count)errors.push('FRAME_COUNT_INCOMPLETE');if(!ledger)errors.push('EVIDENCE_LEDGER_MISSING');else if(ledger.ledger_root!==manifest.evidence_ledger_root)errors.push('EVIDENCE_LEDGER_ROOT_MISMATCH');json({ok:errors.length===0,errors,warnings:[...(pv.warnings??[]),...(exportReport?.status==='blocked'?['MP4_ENCODER_UNAVAILABLE']:[])],production_root:production.production_root,sequence_root:manifest.sequence_root,evidence_ledger_root:ledger?.ledger_root??null,audio_root:audioReport?.audio_root??null,export:exportReport});if(errors.length)process.exitCode=1;
  }else if(command==='replay'){
    const workspace=path.resolve(args[1]),production=readProduction(path.join(workspace,'production.ir.json')),manifest=readJson(path.join(workspace,'frames-manifest.json')),result=replayCut(production,manifest);writeJson(path.join(workspace,'replay-report.json'),result);json({ok:result.valid,...result});if(!result.valid)process.exitCode=1;
  }else if(command==='snapshot'){
    const workspace=path.resolve(args[1]),id=String(flag('id',`snapshot-${Date.now()}`)),source=path.join(workspace,'production.ir.json'),snapshotDir=path.join(workspace,'snapshots'),snapshot=path.join(snapshotDir,`${id}.json`);fs.mkdirSync(snapshotDir,{recursive:true});writeJson(snapshot,{format:'rncs.anime-snapshot.v0.1',snapshot_id:id,production:readProduction(source),frames_manifest:fs.existsSync(path.join(workspace,'frames-manifest.json'))?readJson(path.join(workspace,'frames-manifest.json')):null});json({ok:true,snapshot});
  }else if(command==='rollback'){
    const workspace=path.resolve(args[1]),snapshotId=String(flag('snapshot','')),snapshot=path.join(workspace,'snapshots',`${snapshotId}.json`);if(!snapshotId||!fs.existsSync(snapshot))throw Object.assign(new Error('Snapshot not found'),{code:'SNAPSHOT_NOT_FOUND'});const value=readJson(snapshot);writeJson(path.join(workspace,'production.ir.json'),value.production);const receipt={format:'rncs.anime-rollback-receipt.v0.1',snapshot_id:snapshotId,production_root:value.production.production_root,status:'restored-authoring-state',next_action:'re-render affected Cut',frames_preserved:false};writeJson(path.join(workspace,'rollback-receipt.json'),receipt);json({ok:true,...receipt});
  }else throw Object.assign(new Error(`Unknown command: ${command}`),{code:'COMMAND_UNKNOWN'});
}catch(error){errorResult(error)}
