export const WEB_KNOWLEDGE_OBJECT_TYPES = [
  "WEBLKM_KNOWLEDGE_ITEM_OBJECT",
  "WEBLKM_EVIDENCE_CHAIN_OBJECT",
  "WEBCM_CALCULUS_ROUTE_OBJECT",
  "WEBCOM_CONSTANT_CONSTRAINT_OBJECT",
  "WEB_KNOWLEDGE_TRINITY_RUN_OBJECT",
  "WEB_KNOWLEDGE_QA_RESULT_OBJECT",
] as const;
export type WebKnowledgeObjectType = typeof WEB_KNOWLEDGE_OBJECT_TYPES[number];
