export const WEB_KNOWLEDGE_RISK_TYPES = [
  "KNOWLEDGE_DRIFT",
  "STALE_KNOWLEDGE",
  "KNOWLEDGE_CONFLICT",
  "WRONG_CALCULUS",
  "MISSING_CONSTANT",
  "CONSTANT_VIOLATION",
  "PRIVACY_LEAK",
  "FALSE_MEMORY",
  "CONTEXT_POLLUTION",
  "FAKE_EXECUTION",
  "VENDOR_LOCK",
] as const;
export type WebKnowledgeRiskType = typeof WEB_KNOWLEDGE_RISK_TYPES[number];
