import { semanticHash, type VSRDisplayItem, type VSRDisplayState } from '../../spec/src/index.js';
import { compileWebGPUPlan, renderDisplayStateWebGPU, subsetWebGPUPlan, type VSRWebGPUPlan, type VSRWebGPUResourceInput } from '../../backend-webgpu/src/index.js';
import { drawDisplayStateToCanvas } from '../../backend-canvas/src/browser.js';

export const VSR_HYBRID_BACKEND_VERSION='0.2.0-alpha.1';
export interface VSRHybridLayer { layerId:string; kind:'gpu'|'software'; itemIds:string[]; startOrder:number; endOrder:number; stateHash:string; layerHash:string; gpuPlan?:VSRWebGPUPlan }
export interface VSRHybridRenderPlan { format:'vsr.hybrid-render-plan.v0.1'; backendVersion:string; documentId:string; sourceDisplayHash:string; layers:VSRHybridLayer[]; stats:{layers:number;gpuLayers:number;softwareLayers:number;gpuItems:number;softwareItems:number;gpuCoverage:number}; planHash:string }

function subsetState(source:VSRDisplayState,items:VSRDisplayItem[],includeBackground:boolean):VSRDisplayState {const base={...source,background:includeBackground?source.background:undefined,items,diagnostics:[]};return{...base,semanticHash:semanticHash({source:source.semanticHash,background:includeBackground,itemIds:items.map(item=>item.id)})};}
export function compileHybridRenderPlan(state:VSRDisplayState,resources?:VSRWebGPUResourceInput):VSRHybridRenderPlan {
  const full=compileWebGPUPlan(state,resources),gpuIds=new Set(full.commands.map(command=>command.nodeId)),groups:Array<{kind:'gpu'|'software';items:VSRDisplayItem[];start:number;end:number}>=[];
  state.items.forEach((item,index)=>{const kind=gpuIds.has(item.nodeId)?'gpu':'software',last=groups.at(-1);if(last?.kind===kind){last.items.push(item);last.end=index;}else groups.push({kind,items:[item],start:index,end:index});});
  const layers=groups.map((group,index)=>{const layerState=subsetState(state,group.items,index===0),gpuPlan=group.kind==='gpu'?subsetWebGPUPlan(full,group.items.map(item=>item.nodeId),layerState.semanticHash,index===0?full.clearColor:[0,0,0,0]):undefined;const semantic={kind:group.kind,itemIds:group.items.map(item=>item.id),startOrder:group.start,endOrder:group.end,stateHash:layerState.semanticHash,gpuPlanHash:gpuPlan?.planHash};return{layerId:`layer:${index.toString().padStart(4,'0')}`,kind:group.kind,itemIds:semantic.itemIds,startOrder:group.start,endOrder:group.end,stateHash:layerState.semanticHash,layerHash:semanticHash(semantic),gpuPlan};});
  const gpuItems=layers.filter(layer=>layer.kind==='gpu').reduce((sum,layer)=>sum+layer.itemIds.length,0),softwareItems=state.items.length-gpuItems,stats={layers:layers.length,gpuLayers:layers.filter(layer=>layer.kind==='gpu').length,softwareLayers:layers.filter(layer=>layer.kind==='software').length,gpuItems,softwareItems,gpuCoverage:state.items.length?gpuItems/state.items.length:1};const base={format:'vsr.hybrid-render-plan.v0.1' as const,backendVersion:VSR_HYBRID_BACKEND_VERSION,documentId:state.documentId,sourceDisplayHash:state.semanticHash,layers:layers.map(({gpuPlan,...layer})=>({...layer,gpuPlanHash:gpuPlan?.planHash})),stats};return{format:base.format,backendVersion:base.backendVersion,documentId:base.documentId,sourceDisplayHash:base.sourceDisplayHash,layers,stats,planHash:semanticHash(base)};
}
export function verifyHybridRenderPlan(state:VSRDisplayState,plan:VSRHybridRenderPlan):{ok:boolean;diagnostics:string[]} {const diagnostics:string[]=[];if(plan.sourceDisplayHash!==state.semanticHash)diagnostics.push('source-display-hash-mismatch');const flattened=plan.layers.flatMap(layer=>layer.itemIds),expected=state.items.map(item=>item.id);if(flattened.length!==expected.length)diagnostics.push('item-count-mismatch');expected.forEach((id,index)=>{if(flattened[index]!==id)diagnostics.push(`item-order-mismatch:${index}:${id}:${flattened[index]??'missing'}`);});const duplicates=flattened.filter((id,index)=>flattened.indexOf(id)!==index);if(duplicates.length)diagnostics.push(`duplicate-items:${[...new Set(duplicates)].join(',')}`);for(let index=0;index<plan.layers.length;index++){const layer=plan.layers[index]!;if(layer.startOrder>layer.endOrder)diagnostics.push(`invalid-range:${layer.layerId}`);if(index>0&&plan.layers[index-1]!.endOrder+1!==layer.startOrder)diagnostics.push(`non-contiguous:${layer.layerId}`);if(layer.kind==='gpu'&&(!layer.gpuPlan||layer.gpuPlan.unsupported.length))diagnostics.push(`invalid-gpu-layer:${layer.layerId}`);}return{ok:diagnostics.length===0,diagnostics};}
export async function renderDisplayStateHybrid(state:VSRDisplayState,container:HTMLElement,resources?:VSRWebGPUResourceInput):Promise<VSRHybridRenderPlan>{
  const plan=compileHybridRenderPlan(state,resources),verification=verifyHybridRenderPlan(state,plan);if(!verification.ok)throw new Error(`混合渲染计划无效：${verification.diagnostics.join('；')}`);container.replaceChildren();container.style.position='relative';container.style.width=`${state.viewport.width}px`;container.style.height=`${state.viewport.height}px`;
  for(const layer of plan.layers){const canvas=document.createElement('canvas');canvas.dataset['vsrLayer']=layer.layerId;canvas.style.position='absolute';canvas.style.inset='0';canvas.style.pointerEvents='none';container.append(canvas);const items=state.items.slice(layer.startOrder,layer.endOrder+1),layerState=subsetState(state,items,layer.startOrder===0);if(layer.kind==='gpu')await renderDisplayStateWebGPU(layerState,canvas,resources);else drawDisplayStateToCanvas(layerState,canvas);}return plan;
}
