import fs from 'node:fs';import path from 'node:path';import {discoverRuntimeManifests} from './discovery.mjs';import {RuntimeLoader} from './loader.mjs';import {clone,hash,seal,now,id,GatewayError} from './canonical.mjs';
const atomic=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});const t=`${p}.tmp-${process.pid}`;fs.writeFileSync(t,JSON.stringify(v,null,2)+'\n');fs.renameSync(t,p);};
const withTimeout=(p,ms,label)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new GatewayError('RUNTIME_TIMEOUT',label)),ms);Promise.resolve(p).then(v=>{clearTimeout(timer);resolve(v)},e=>{clearTimeout(timer);reject(e)});});
export class RealityOneGateway{
 constructor({manifestDirs,dataDir,gatewayProtocol='0.3.0'}={}){this.manifestDirs=(manifestDirs??[path.resolve('runtimes')]).map(d=>path.resolve(d));this.dataDir=path.resolve(dataDir??'output/gateway-data');this.gatewayProtocol=gatewayProtocol;this.loader=new RuntimeLoader();this.registry=null;this.selected=null;}
 async discover(){const d=discoverRuntimeManifests(this.manifestDirs,{gatewayProtocol:this.gatewayProtocol});this.registry=d.registry;this.selected=d.selected;atomic(path.join(this.dataDir,'runtime-registry.json'),this.registry);return this.registry;}
 require(id){if(!this.selected)throw new GatewayError('GATEWAY_NOT_DISCOVERED');const m=this.selected.get(id);if(!m)throw new GatewayError('RUNTIME_NOT_FOUND',id);return m;}
 async health(){if(!this.selected)await this.discover();const reports=[];for(const id of this.registry.runtime_order){const m=this.require(id),started=performance.now();try{const r=await this.loader.load(m);const detail=await withTimeout(Promise.resolve(r.health?.()??{status:'ok'}),m.health_timeout_ms,id);reports.push({runtime_id:id,version:m.runtime_version,status:'healthy',duration_ms:+(performance.now()-started).toFixed(3),detail});}catch(e){reports.push({runtime_id:id,version:m.runtime_version,status:'unhealthy',duration_ms:+(performance.now()-started).toFixed(3),error:{code:e.code??'ERROR',message:e.message}});}}
  const report=seal({format:'reality-one.health-report.v0.3',gateway_protocol:this.gatewayProtocol,registry_root:this.registry.registry_root,generated_at:now(),status:reports.every(x=>x.status==='healthy')?'healthy':'degraded',runtimes:reports},'health_root');atomic(path.join(this.dataDir,'health-report.json'),report);return report;}
 async invoke(runtimeId,action,payload={},opts={}){if(!this.selected)await this.discover();const m=this.require(runtimeId);if(!m.actions.includes(action))throw new GatewayError('RUNTIME_ACTION_NOT_DECLARED',`${runtimeId}:${action}`);const key=opts.idempotencyKey?hash({runtimeId,action,key:String(opts.idempotencyKey)}):null;const cachePath=key?path.join(this.dataDir,'idempotency',`${key}.json`):null;if(cachePath&&fs.existsSync(cachePath))return JSON.parse(fs.readFileSync(cachePath,'utf8')).result;const runtime=await this.loader.load(m),started=performance.now(),requestId=opts.requestId??id('gateway-request');const result=await withTimeout(Promise.resolve(runtime.invoke(action,clone(payload),opts)),opts.timeoutMs??m.health_timeout_ms*5,`${runtimeId}:${action}`);const receipt=seal({format:'reality-one.invocation-receipt.v0.3',request_id:requestId,runtime_id:runtimeId,runtime_version:m.runtime_version,manifest_root:m.manifest_root,action,payload_root:hash(payload),result_root:hash(result),duration_ms:+(performance.now()-started).toFixed(3),created_at:now(),idempotency_key:key},'receipt_root');fs.mkdirSync(path.join(this.dataDir,'journal'),{recursive:true});fs.appendFileSync(path.join(this.dataDir,'journal','invocations.ndjson'),JSON.stringify(receipt)+'\n');if(cachePath)atomic(cachePath,{receipt,result});return result;}
}
