import fs from 'node:fs';import path from 'node:path';import {clone,hash,seal,now,GatewayError} from './canonical.mjs';
const write=(dir,name,v)=>{fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,name),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');};
export async function runIntentAuthorityPipeline(gateway,input,{outDir='output/pipeline'}={}){
 const started=performance.now();const providers=input.providers;const negotiation=await gateway.invoke('rncs.cnp','negotiate',{request:input.cnp_request,providers},{idempotencyKey:`cnp:${hash(input.cnp_request)}`});if(negotiation.plan?.status!=='satisfied')throw new GatewayError('PIPELINE_NEGOTIATION_UNSATISFIED');
 const preview=await gateway.invoke('rncs.icar','preview',{sourceArtifact:input.artifact,intentText:input.intent_text,actor:input.actor,hosts:input.hosts,capsule:input.capsule,rfeStorePath:input.rfe_store_path,realityId:input.reality_id??'reality:gateway-v0.3',providers:input.icar_providers??[],policy:input.icar_policy??{}},{idempotencyKey:`preview:${hash({artifact:input.artifact.evidence?.artifact_root,intent:input.intent_text,actor:input.actor.subject_id})}`});
 const policy=await gateway.invoke('rncs.aaf','sealPolicy',{raw:input.policy_bundle});let decision=await gateway.invoke('rncs.aaf','evaluate',{envelope:preview.envelope,negotiation,policy_bundle:policy,identity_scopes:input.actor.scopes??[],context:{request_id:`authority:${preview.envelope.transition_id}`,environment:input.environment??'local',now:input.now??now()} ,approvals:input.approvals??[]});
 let generatedApproval=null;if(decision.status==='pending_approval'&&input.auto_approve){generatedApproval=await gateway.invoke('rncs.aaf','sealApproval',{raw:{approval_id:`approval:gateway:${preview.envelope.transition_id}`,proposal_root:preview.envelope.proposal_root,approver_id:input.approver?.id??input.actor.subject_id,approver_roles:input.approver?.roles??['owner'],decision:'approved',scopes:['*'],conditions:[{type:'gateway-explicit-approval'}],issued_at:input.now??now(),expires_at:input.approval_expires_at??'2099-01-01T00:00:00Z'}});decision=await gateway.invoke('rncs.aaf','evaluate',{envelope:preview.envelope,negotiation,policy_bundle:policy,identity_scopes:input.actor.scopes??[],context:{request_id:`authority:${preview.envelope.transition_id}`,environment:input.environment??'local',now:input.now??now()},approvals:[...(input.approvals??[]),generatedApproval]});}
 if(decision.status!=='approved')return seal({format:'reality-one.pipeline-result.v0.3',status:decision.status,negotiation,preview,authority:decision,generated_approval:generatedApproval,commit:null,runtime_registry_root:gateway.registry.registry_root,duration_ms:+(performance.now()-started).toFixed(3)},'pipeline_root');
 const rebound=await gateway.invoke('rncs.icar','rebindAuthority',{preview,authorizedEnvelope:decision.authorized_envelope});const result=await gateway.invoke('rncs.icar','commit',{preview:rebound,rfeStorePath:input.rfe_store_path},{idempotencyKey:`commit:${decision.authorized_envelope.proposal_root}`});
 const output=seal({format:'reality-one.pipeline-result.v0.3',status:'committed',negotiation,preview_root:preview.preview_root,authority:decision,generated_approval:generatedApproval,application_result:result,runtime_registry_root:gateway.registry.registry_root,runtime_versions:Object.fromEntries(gateway.registry.runtimes.map(r=>[r.runtime_id,r.runtime_version])),duration_ms:+(performance.now()-started).toFixed(3)},'pipeline_root');
 const dir=path.resolve(outDir);write(dir,'negotiation.json',negotiation);write(dir,'preview.json',preview);write(dir,'authority-decision.json',decision);if(generatedApproval)write(dir,'approval.json',generatedApproval);write(dir,'application-result.json',result);write(dir,'pipeline-result.json',output);return output;
}
