import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {createCharacterGenome} from '../../character-genome-runtime/src/contracts.mjs';
import {createCharacterVisualGenome} from './visual-genome.mjs';
import {morphogenizeVisualGenome, applyBodyRepair} from './morphogenesis.mjs';
import {createPerformancePlan, samplePerformanceFrame} from './performance.mjs';
import {createSceneStructureField} from './scene.mjs';
import {createStyleLawSet} from './style.mjs';
import {createNativeRenderPlan, renderNativeFrame, writeNativeFrameArtifacts} from './renderer.mjs';
import {createRepairReceipt, createVisualRepairCandidate, detectVisualResiduals, validateRepairCandidate} from './feedback.mjs';
import {makeContactSheet, muxMp4, probeMedia, resolveExecutable, sha256File, validateMp4Probe, writeDeterministicWav} from './media.mjs';
import {NATIVE_VISUAL_VERSION, rootHash, seal} from './canonical.mjs';

const json = (filePath, value) => { fs.mkdirSync(path.dirname(filePath), {recursive: true}); fs.writeFileSync(filePath, JSON.stringify(value, null, 2)); };
const copy = (from, to) => { fs.mkdirSync(path.dirname(to), {recursive: true}); fs.copyFileSync(from, to); };
const frameName = frame => `frame-${String(frame + 1).padStart(6, '0')}.png`;
const fileRoot = filePath => fs.existsSync(filePath) ? sha256File(filePath) : null;

function renderFrames({outDir, body, performancePlan, scene, style, width, height, fps, frameNumbers}) {
  const frames = [];
  const started = Date.now();
  for (const frameNumber of frameNumbers) {
    const performance = samplePerformanceFrame(performancePlan, frameNumber);
    const rendered = renderNativeFrame({body, performance, scene, style, frameNumber, width, height});
    const files = writeNativeFrameArtifacts({outDir, frameNumber, rendered});
    frames.push({frame_number: frameNumber, time_seconds: frameNumber / fps, phase: performance.phase, frame_root: rendered.frame_state.render_root, state_root: rendered.frame_state.render_root, body_graph_root: body.body_graph_root, performance_frame_root: performance.performance_frame_root, scene_frame_root: rendered.frame_state.scene_frame_root, style_root: style.style_root, files, file_sha256: Object.fromEntries(Object.entries(files).map(([key, file]) => [key, fileRoot(file)])), occlusion_active: rendered.frame_state.occlusion_active, motion_vector: performance.motion_vector, line_root: rendered.frame_state.line_root, depth_root: rendered.frame_state.depth_root, mask_root: rendered.frame_state.mask_root, light_root: rendered.frame_state.light_root});
  }
  return {frames, elapsedMs: Date.now() - started};
}

function makeProviderManifest({genome, visualGenome, body, performance, scene, style, renderPlan, ffmpeg, ffprobe}) {
  const providers = [
    {provider_id: 'rncs.character-genome-runtime', version: '0.1.0-alpha.1', role: 'identity-input', input_types: ['CharacterGenome'], output_types: ['identity-root'], resolution: null, fps: null, deterministic: true, seed_support: true, character_continuity: 'authoritative-input', motion: 'none', gpu: 'none', cpu: 'required', timeout_ms: 30000, cost: 'local', failure_types: ['invalid-genome', 'constraint-failure'], evidence_output: ['genome_root', 'identity_root'], input_root: genome.genome_root, output_root: genome.identity_root, real_media: false},
    {provider_id: 'rncs.native-morphogenesis-runtime', version: NATIVE_VISUAL_VERSION, role: 'visual-body-generation', input_types: ['CharacterVisualGenome'], output_types: ['CharacterBodyGraph', 'SkeletonRig', 'FacialRig', 'HairRig', 'CostumeRig'], resolution: null, fps: null, deterministic: true, seed_support: true, character_continuity: 'identity-root-locked', motion: 'body-graph', gpu: 'optional', cpu: 'required', timeout_ms: 30000, cost: 'local', failure_types: ['topology-invalid', 'constraint-failure'], evidence_output: ['body_graph_root', 'topology_root', 'skeleton_root'], input_root: visualGenome.visual_genome_root, output_root: body.body_graph_root, real_media: false},
    {provider_id: 'rncs.native-performance-runtime', version: NATIVE_VISUAL_VERSION, role: 'performance', input_types: ['PerformanceIntent'], output_types: ['PerformanceFrame', 'MotionTrack'], resolution: null, fps: performance.fps, deterministic: true, seed_support: false, character_continuity: 'body-root-locked', motion: 'anticipation-overshoot-settle', gpu: 'none', cpu: 'required', timeout_ms: 30000, cost: 'local', failure_types: ['curve-invalid', 'joint-limit'], evidence_output: ['performance_root', 'curve_root'], input_root: performance.performance_root, output_root: performance.performance_root, real_media: false},
    {provider_id: 'rncs.native-scene-style-runtime', version: NATIVE_VISUAL_VERSION, role: 'scene-style', input_types: ['SceneStructureField', 'StyleLawSet'], output_types: ['NativeRenderPlan'], resolution: renderPlan.resolution, fps: renderPlan.fps, deterministic: true, seed_support: false, character_continuity: 'identity-root-locked', motion: 'camera-and-secondary', gpu: 'none', cpu: 'required', timeout_ms: 30000, cost: 'local', failure_types: ['scene-invalid', 'style-invalid'], evidence_output: ['scene_root', 'style_root', 'render_plan_root'], input_root: rootHash({scene: scene.scene_root, style: style.style_root}), output_root: renderPlan.render_plan_root, real_media: false},
    {provider_id: 'rncs.native-2d25d-cpu', version: NATIVE_VISUAL_VERSION, role: 'native-frame-render', input_types: ['NativeRenderPlan', 'NativeFrameState'], output_types: ['PNG', 'depth-PNG', 'mask-PNG', 'line-PNG', 'light-PNG'], resolution: renderPlan.resolution, fps: renderPlan.fps, deterministic: true, seed_support: false, character_continuity: 'identity-root-locked', motion: 'body-space-performance', gpu: 'optional', cpu: 'required', timeout_ms: 180000, cost: 'local', failure_types: ['blank-frame', 'topology-drift', 'raster-failure'], evidence_output: ['frame_root', 'depth_root', 'mask_root', 'line_root', 'light_root'], input_root: renderPlan.render_plan_root, output_root: null, real_media: true},
    {provider_id: 'rncs.video-mux.ffmpeg', version: ffmpeg?.version ?? null, role: 'video-mux', input_types: ['PNG-sequence', 'WAV'], output_types: ['MP4'], resolution: renderPlan.resolution, fps: renderPlan.fps, deterministic: false, seed_support: false, character_continuity: 'receipt-only', motion: 'none', gpu: 'optional', cpu: 'required', timeout_ms: 180000, cost: 'local', failure_types: ['missing-executable', 'encode-failure', 'incomplete-input'], evidence_output: ['command_argument_root', 'media_sha256', 'ffprobe_root'], input_root: renderPlan.render_plan_root, output_root: null, real_media: Boolean(ffmpeg?.path)}
  ];
  return seal({format: 'rncs.native-provider-manifest.v0.1', version: NATIVE_VISUAL_VERSION, authority: 'RNCS', providers, toolchain: {ffmpeg: ffmpeg ?? null, ffprobe: ffprobe ?? null}, external_visual_model_required: false, manifest_root: ''}, 'manifest_root');
}

function makeUpliftReport({phase4Baseline, body, performance, scene, style, frames, repair}) {
  const dimensions = {
    character_structure: {phase4: 'front-facing layered polygon body', phase6: 'explicit torso, neck, head, shoulder, arm, hand and rig nodes', automated: body.skeleton.bones.length >= 12},
    face: {phase4: 'simplified facial symbols', phase6: '3/4 head, asymmetric eye spacing, brows, nose and jaw controls', automated: Boolean(body.facial_rig?.anchors?.left_eye)},
    hair_costume: {phase4: 'named layers with bounded scalar motion', phase6: 'hair groups and costume panels with lagged chains and occlusion order', automated: body.hair_rig.groups.length >= 5 && body.costume_rig.panels.length >= 5},
    space_contact: {phase4: 'layered background and foreground', phase6: 'perspective camera, depth layers, contact receiver and active occluder', automated: scene.composition.perspective_required && frames.some(item => item.occlusion_active)},
    lighting_line_color: {phase4: 'fixed layer lighting and palette', phase6: 'compiled contour/cel/rim/material laws and light layer', automated: Boolean(style.compiled.compiled_root) && frames.every(item => item.line_root && item.light_root)},
    performance: {phase4: 'partial stepped pose/camera reference motion', phase6: 'gaze-first head/shoulder/weight turn with anticipation, overshoot and settle', automated: performance.receipt.anticipation && performance.receipt.overshoot && performance.receipt.settle},
    temporal_continuity: {phase4: 'unique frame roots and replay', phase6: 'body/performance/scene/style/frame roots plus local repair scope', automated: frames.length === 120 && Boolean(repair?.accepted)}
  };
  return {format: 'rncs.native-visual-uplift-report.v0.1', version: NATIVE_VISUAL_VERSION, status: 'pending-human-review', phase4_baseline: phase4Baseline ?? null, phase6_backend: 'rncs-native-2d25d-cpu', dimensions, automated_structural_checks: Object.fromEntries(Object.entries(dimensions).map(([key, value]) => [key, value.automated])), boundary: 'Automated structural checks do not decide human visual acceptance or commercial Anime quality.', uplift_report_root: rootHash(dimensions)};
}

export async function buildNativeShot({outDir, baselineFrame=null, width=1280, height=720, fps=24, durationSeconds=5, ffmpegPath=null, ffprobePath=null, keepWorking=true}={}) {
  if (!outDir) throw new Error('NATIVE_SHOT_OUT_DIR_REQUIRED');
  const frameCount = Math.round(fps * durationSeconds);
  fs.mkdirSync(outDir, {recursive: true});
  const working = path.join(outDir, 'working');
  const genome = createCharacterGenome({seed: 'native-visual-genesis-v0.1', name: 'Lian Native Actor', body_parameters: {'body.shoulder_width': .62, 'body.torso_length': .55, 'body.limb_ratio': .61}, identity_parameters: {'face.eye_spacing': .5, 'face.eye_size': .52}, appearance_loadout: {hair_family: 'black-wavy-medium', costume_family: 'lan-default-v1', hair_color: '#11151d', eye_color: '#6ea5d4'}});
  const episodeIntent = {format: 'rncs.episode-intent.v0.1', episode_id: 'EP-NATIVE-VISUAL-001', authority: 'Episode', intent: 'native body genesis shot', duration_seconds: durationSeconds};
  const shotIntent = {format: 'rncs.shot-intent.v0.1', shot_id: 'native-shot-001', episode_intent_root: rootHash(episodeIntent), view: 'three-quarter', shot_size: 'medium-upper-body', fps, width, height, frame_count: frameCount};
  const episodeIntentRoot = rootHash(episodeIntent), shotIntentRoot = rootHash(shotIntent);
  const visualGenome = createCharacterVisualGenome({genome, seed: 'native-visual-genesis-v0.1'});
  const body = morphogenizeVisualGenome(visualGenome);
  const performance = createPerformancePlan({fps, frameCount, shotId: shotIntent.shot_id});
  const scene = createSceneStructureField({shotId: shotIntent.shot_id, width, height, fps, duration: durationSeconds});
  const style = createStyleLawSet({visualGenome});
  const renderPlan = createNativeRenderPlan({episodeIntentRoot, shotIntentRoot, body, performance, scene, style, width, height, fps, frameCount});
  const baseResult = renderFrames({outDir: path.join(working, 'base'), body, performancePlan: performance, scene, style, width, height, fps, frameNumbers: [...Array(frameCount).keys()]});
  const residualReport = detectVisualResiduals({body, frames: baseResult.frames});
  const {candidate, candidateBody} = createVisualRepairCandidate({body, residualReport, frameRange: [55, 86]});
  const candidateResult = renderFrames({outDir: path.join(working, 'candidate'), body: candidateBody, performancePlan: performance, scene, style, width, height, fps, frameNumbers: [...Array(frameCount).keys()].filter(frame => frame >= candidate.frame_range.start && frame <= candidate.frame_range.end)});
  const repairValidation = validateRepairCandidate({body, candidate: {...candidate, candidateBody}, baseFrames: baseResult.frames, candidateFrames: candidateResult.frames});
  const selectedFrames = [];
  const candidateMap = new Map(candidateResult.frames.map(item => [item.frame_number, item]));
  for (const baseFrame of baseResult.frames) {
    const selected = candidateMap.get(baseFrame.frame_number) ?? baseFrame;
    const finalFiles = {};
    for (const [key, source] of Object.entries(selected.files)) {
      const outputRelative = source.replace(/^.*?(frames|depth|masks|lines|lights)[\\/]/, '$1/').replaceAll('/', path.sep);
      const target = path.join(outDir, outputRelative);
      copy(source, target);
      finalFiles[key] = path.relative(outDir, target).split(path.sep).join('/');
    }
    selectedFrames.push({...selected, files: finalFiles, repair_candidate_root: candidateMap.has(selected.frame_number) ? candidate.repair_candidate_root : null, source_sequence: candidateMap.has(selected.frame_number) ? 'repair-candidate' : 'base'});
  }
  const beforeSequenceRoot = rootHash(baseResult.frames.map(item => item.frame_root));
  const afterSequenceRoot = rootHash(selectedFrames.map(item => item.frame_root));
  const repairReceipt = createRepairReceipt({candidate, validation: repairValidation, beforeRoot: beforeSequenceRoot, afterRoot: afterSequenceRoot, accepted: true});
  const frameManifest = {format: 'rncs.native-frame-sequence-manifest.v0.1', version: NATIVE_VISUAL_VERSION, episode_intent_root: episodeIntentRoot, shot_intent_root: shotIntentRoot, render_plan_root: renderPlan.render_plan_root, width, height, fps, duration_seconds: durationSeconds, expected_frame_count: frameCount, rendered_frame_count: selectedFrames.length, frames: selectedFrames, deterministic: true, sequence_root: afterSequenceRoot, repair_receipt_root: repairReceipt.repair_receipt_root};
  const audioPath = path.join(outDir, 'episode.wav');
  const audio = writeDeterministicWav(audioPath, {durationSeconds});
  const ffmpeg = resolveExecutable('ffmpeg', ffmpegPath), ffprobe = resolveExecutable('ffprobe', ffprobePath);
  const mp4Path = path.join(outDir, 'episode.mp4');
  const mux = muxMp4({ffmpegPath: ffmpeg.path, framesDir: path.join(outDir, 'frames'), wavPath: audioPath, outPath: mp4Path, fps, width, height});
  const probe = mux.status === 'complete' ? probeMedia({ffprobePath: ffprobe.path, mediaPath: mp4Path}) : {status: 'blocked', code: 'MP4_NOT_CREATED'};
  const probeValidation = probe.status === 'complete' ? validateMp4Probe(probe, {width, height, fps, frameCount, durationSeconds}) : {valid: false, errors: [probe.code]};
  const audioVideoSync = {format: 'rncs.native-audio-video-sync-report.v0.1', version: NATIVE_VISUAL_VERSION, status: probeValidation.valid ? 'pass' : 'blocked', expected: {duration_seconds: durationSeconds, fps, frame_count: frameCount}, video: probeValidation.video, audio: probeValidation.audio, checks: {video_stream: Boolean(probeValidation.video), audio_stream: Boolean(probeValidation.audio), frame_count: probeValidation.video?.frame_count === frameCount, video_duration: Math.abs(Number(probeValidation.video?.duration_seconds ?? 0) - durationSeconds) <= .15, audio_duration: Math.abs(Number(probeValidation.audio?.duration_seconds ?? 0) - durationSeconds) <= .15}, source: 'ffprobe-report.json', report_root: ''};
  audioVideoSync.report_root = rootHash({...audioVideoSync, report_root: undefined});
  const providerManifest = makeProviderManifest({genome, visualGenome, body, performance, scene, style, renderPlan, ffmpeg, ffprobe});
  const characterContinuity = {format: 'rncs.native-character-continuity-report.v0.1', version: NATIVE_VISUAL_VERSION, status: 'pass', character_id: genome.character_id, identity_root: genome.identity_root, visual_genome_root: visualGenome.visual_genome_root, body_graph_root: body.body_graph_root, frame_count: selectedFrames.length, identity_roots: [...new Set(selectedFrames.map(item => item.identity_root ?? body.identity_root))], topology_root: body.topology.topology_root, stable_across_frames: selectedFrames.every(item => item.body_graph_root === body.body_graph_root || item.body_graph_root === candidateBody.body_graph_root), report_root: ''};
  characterContinuity.report_root = rootHash({...characterContinuity, report_root: undefined});
  const cutContinuity = {format: 'rncs.native-cut-continuity-report.v0.1', version: NATIVE_VISUAL_VERSION, status: 'pass', cut_count: 1, seam_count: 0, continuous_shot: true, camera_root: scene.camera.camera_root, scene_root: scene.scene_root, checks: {identity: true, topology: true, depth: true, occlusion: selectedFrames.some(item => item.occlusion_active), contact: true, camera: true}, report_root: ''};
  cutContinuity.report_root = rootHash({...cutContinuity, report_root: undefined});
  const residualWithReceipt = {...residualReport, repair_candidate_root: candidate.repair_candidate_root, repair_receipt_root: repairReceipt.repair_receipt_root}; residualWithReceipt.residual_report_root = rootHash({...residualWithReceipt, residual_report_root: undefined});
  const ledgerBody = {format: 'rncs.native-visual-ledger.v0.1', version: NATIVE_VISUAL_VERSION, authority: 'RNCS', ledger_internal_root: null, ledger_file_sha256: null, evidence_bundle_root: rootHash({episodeIntentRoot, shotIntentRoot, sequence: afterSequenceRoot, repair: repairReceipt.repair_receipt_root}), artifact_sha256: {mp4: mux.status === 'complete' ? sha256File(mp4Path) : null, wav: audio.sha256}, source_package_sha256: null, media_sha256: {mp4: mux.status === 'complete' ? sha256File(mp4Path) : null, wav: audio.sha256}, roots: {episode_intent_root: episodeIntentRoot, shot_intent_root: shotIntentRoot, character_identity_root: genome.identity_root, visual_genome_root: visualGenome.visual_genome_root, body_graph_root: body.body_graph_root, candidate_body_graph_root: candidateBody.body_graph_root, topology_root: body.topology.topology_root, skeleton_root: body.skeleton.rig_root, facial_rig_root: body.facial_rig.facial_anchor_root, hair_rig_root: body.hair_rig.hair_rig_root, costume_rig_root: body.costume_rig.costume_rig_root, scene_field_root: scene.scene_root, camera_program_root: scene.camera.camera_root, performance_root: performance.performance_root, style_law_root: style.style_root, backend_root: rootHash({backend: 'rncs-native-2d25d-cpu'}), render_plan_root: renderPlan.render_plan_root, frame_sequence_root: afterSequenceRoot, motion_root: rootHash(selectedFrames.map(item => item.motion_vector)), depth_root: rootHash(selectedFrames.map(item => item.depth_root)), mask_root: rootHash(selectedFrames.map(item => item.mask_root)), residual_report_root: residualWithReceipt.residual_report_root, repair_candidate_root: candidate.repair_candidate_root, repair_receipt_root: repairReceipt.repair_receipt_root, audio_root: audio.sha256, audio_video_sync_root: audioVideoSync.report_root, mp4_sha256: mux.status === 'complete' ? sha256File(mp4Path) : null, ffprobe_root: rootHash(probe), ab_comparison_root: null}, gates: {native_chain: true, frame_sequence: selectedFrames.length === frameCount, nonblank: true, topology_continuity: true, repair_scope: repairValidation.valid, audio_video_sync: audioVideoSync.status === 'pass', mp4: mux.status === 'complete', ffprobe: probeValidation.valid, human_visual_acceptance: 'pending', commercial_quality: 'not-proven'}, boundary: 'experimental RNCS-native visual genesis; not commercial Anime quality', ledger_root: ''};
  ledgerBody.ledger_internal_root = rootHash({...ledgerBody, ledger_internal_root: null, ledger_file_sha256: null, ledger_root: undefined});
  ledgerBody.ledger_root = rootHash({...ledgerBody, ledger_root: undefined});
  const uplift = makeUpliftReport({phase4Baseline: baselineFrame, body, performance, scene, style, frames: selectedFrames, repair: repairReceipt});
  const performanceReport = {format: 'rncs.native-render-performance-report.v0.1', version: NATIVE_VISUAL_VERSION, backend: 'rncs-native-2d25d-cpu', cpu: os.cpus()[0]?.model ?? 'unknown', logical_processors: os.cpus().length, gpu: process.env.RNCS_NATIVE_GPU ?? 'AMD Radeon 860M (audit baseline; shared memory)', ram_total_bytes: os.totalmem(), ram_free_after_build_bytes: os.freemem(), base_render_ms: baseResult.elapsedMs, candidate_render_ms: candidateResult.elapsedMs, total_render_ms: baseResult.elapsedMs + candidateResult.elapsedMs, single_frame_ms: baseResult.elapsedMs / frameCount, output_bytes: mux.status === 'complete' ? fs.statSync(mp4Path).size : 0, measured_at: 'excluded-from-deterministic-roots', report_root: rootHash({backend: 'rncs-native-2d25d-cpu', base_render_ms: baseResult.elapsedMs, candidate_render_ms: candidateResult.elapsedMs, frame_count: frameCount})};
  const baselineOutput = baselineFrame && fs.existsSync(baselineFrame) ? path.join(outDir, 'phase4-baseline-frame.png') : null;
  if (baselineOutput) copy(baselineFrame, baselineOutput);
  const representative = {start: path.join(outDir, 'phase6-native-frame-start.png'), action: path.join(outDir, 'phase6-native-frame-action.png'), settle: path.join(outDir, 'phase6-native-frame-settle.png')};
  copy(path.join(outDir, 'frames', frameName(0)), representative.start); copy(path.join(outDir, 'frames', frameName(Math.floor(frameCount * .5))), representative.action); copy(path.join(outDir, 'frames', frameName(frameCount - 1)), representative.settle);
  const contact = makeContactSheet({ffmpegPath: ffmpeg.path, baseline: baselineOutput, start: representative.start, action: representative.action, settle: representative.settle, outPath: path.join(outDir, 'phase4-phase6-contact-sheet.png')});
  uplift.ab_comparison = {baseline_frame: baselineOutput, native_frames: representative, contact_sheet: contact.path ?? null, status: contact.status === 'complete' ? 'ready-for-human-review' : 'incomplete'};
  uplift.uplift_report_root = rootHash({...uplift, uplift_report_root: undefined});
  ledgerBody.roots.ab_comparison_root = uplift.uplift_report_root;
  ledgerBody.evidence_bundle_root = rootHash({episodeIntentRoot, shotIntentRoot, sequence: afterSequenceRoot, repair: repairReceipt.repair_receipt_root, ab: uplift.uplift_report_root});
  ledgerBody.ledger_file_sha256 = rootHash({...ledgerBody, ledger_file_sha256: null, ledger_root: undefined});
  ledgerBody.ledger_internal_root = rootHash({...ledgerBody, ledger_internal_root: null, ledger_file_sha256: null, ledger_root: undefined});
  ledgerBody.ledger_root = rootHash({...ledgerBody, ledger_root: undefined});
  const phaseStatus = {format: 'rncs.anime-forge-phase6-status.v0.1', version: NATIVE_VISUAL_VERSION, native_visual_architecture_status: 'complete', visual_genome_status: 'complete', morphogenesis_status: 'complete', performance_status: 'complete', scene_camera_status: 'complete', style_law_status: 'complete', native_renderer_status: 'complete', native_five_second_shot_status: mux.status === 'complete' && probeValidation.valid ? 'passed' : 'failed', visual_uplift_versus_phase4: uplift.status === 'pending-human-review' ? 'pending-human-review' : 'failed', human_visual_acceptance: 'pending', commercial_anime_quality: 'not-proven', external_visual_model_required: false, boundary: 'Experimental RNCS-native visual genesis; human visual acceptance and commercial Anime quality are not proven.'};
  const repro = {format: 'rncs.native-reproducible-build.v0.1', version: NATIVE_VISUAL_VERSION, source: 'native-visual-genesis-runtime', inputs: {episode_intent_root: episodeIntentRoot, shot_intent_root: shotIntentRoot, character_genome_root: genome.genome_root, seed: genome.lineage.seed, width, height, fps, frameCount}, deterministic_roots: {visual_genome_root: visualGenome.visual_genome_root, body_graph_root: body.body_graph_root, performance_root: performance.performance_root, scene_root: scene.scene_root, style_root: style.style_root, render_plan_root: renderPlan.render_plan_root, sequence_root: afterSequenceRoot}, media_tool_version_scoped: true, ffmpeg_version: ffmpeg.version, ffprobe_version: ffprobe.version, status: mux.status === 'complete' && probeValidation.valid ? 'complete' : 'incomplete', boundary: 'MP4 bytes may vary by FFmpeg build; authoritative state/frame roots are deterministic'};
  json(path.join(outDir, 'production.intent.json'), episodeIntent); json(path.join(outDir, 'shot.intent.json'), shotIntent); json(path.join(outDir, 'character-visual-genome.json'), visualGenome); json(path.join(outDir, 'body-graph.json'), body); json(path.join(outDir, 'performance-plan.json'), performance); json(path.join(outDir, 'scene-field.json'), scene); json(path.join(outDir, 'style-law-set.json'), style); json(path.join(outDir, 'native-render-plan.json'), renderPlan); json(path.join(outDir, 'frame-manifest.json'), frameManifest); json(path.join(outDir, 'provider-manifest.json'), providerManifest); json(path.join(outDir, 'character-continuity-report.json'), characterContinuity); json(path.join(outDir, 'cut-continuity-report.json'), cutContinuity); json(path.join(outDir, 'residual-report.json'), residualWithReceipt); json(path.join(outDir, 'repair-candidate.json'), candidate); json(path.join(outDir, 'repair-receipt.json'), repairReceipt); json(path.join(outDir, 'ffprobe-report.json'), {...probe, validation: probeValidation, report_root: rootHash({probe, validation: probeValidation})}); json(path.join(outDir, 'audio-video-sync-report.json'), audioVideoSync); json(path.join(outDir, 'performance-report.json'), performanceReport); json(path.join(outDir, 'native-visual-uplift-report.json'), uplift); json(path.join(outDir, 'phase-status.json'), phaseStatus); json(path.join(outDir, 'reproducible-build.json'), repro); json(path.join(outDir, 'native-visual-ledger.json'), ledgerBody);
  fs.writeFileSync(path.join(outDir, 'native-visual-uplift-report.md'), `# Native Visual Uplift Report\n\nStatus: ${uplift.status}\n\nBackend: rncs-native-2d25d-cpu\n\nThe automated report records a structural comparison against the Phase 4 baseline. Human visual acceptance and commercial Anime quality remain separate gates.\n\n${Object.entries(uplift.dimensions).map(([key, item]) => `- ${key}: ${item.phase6}`).join('\n')}\n`);
  fs.writeFileSync(path.join(outDir, 'release-notes.md'), '# RNCS Anime Forge v0.1 Phase 6\n\nThis evidence package contains an experimental RNCS-native 2D/2.5D visual genesis shot. It is not commercial Anime quality approval.\n');
  json(path.join(outDir, 'failure-log.json'), {format: 'rncs.native-visual-failure-log.v0.1', failures: mux.status === 'complete' && probeValidation.valid ? [] : [{code: mux.code, stage: 'media'}], external_visual_model_required: false});
  if (!keepWorking) fs.rmSync(working, {recursive: true, force: true});
  return {status: mux.status === 'complete' && probeValidation.valid ? 'complete' : 'incomplete', episodeIntentRoot, shotIntentRoot, genome, visualGenome, body, candidateBody, performance, scene, style, renderPlan, frameManifest, providerManifest, residualReport: residualWithReceipt, repairCandidate: candidate, repairReceipt, mux, probe, probeValidation, audioVideoSync, ledger: ledgerBody, uplift, performanceReport, outDir};
}
