import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {sealPolicyBundle,sealDelegation,sealApproval,sealRevocationRegistry,evaluateAuthority,hash,generateEd25519Keypair,signObject,verifySignedObject} from '../src/index.mjs';
const env=JSON.parse(fs.readFileSync(new URL('../examples/proposed-envelope.json',import.meta.url),'utf8'));
const neg=JSON.parse(fs.readFileSync(new URL('../examples/cnp-negotiation.json',import.meta.url),'utf8'));
const now='2026-06-30T12:00:00Z';
const policy=()=>sealPolicyBundle({bundle_id:'policy:rncs-default',default_effect:'deny',policies:[
 {policy_id:'allow-owner-artifact',effect:'allow',priority:10,match:{roles_any:['owner'],scopes_any:['artifact.*'],risk_at_most:'medium'},obligations:[{type:'evidence-required'}]},
 {policy_id:'approve-irreversible',effect:'require_approval',priority:50,match:{irreversible:true},approval:{roles:['owner','security'],quorum:1}},
 {policy_id:'approve-high-risk',effect:'require_approval',priority:60,match:{risk_at_least:'high'},approval:{roles:['owner','security'],quorum:2}},
 {policy_id:'deny-critical',effect:'deny',priority:100,match:{risk_at_least:'critical'}},
 {policy_id:'approve-money',effect:'require_approval',priority:70,match:{monetary_above:1000000},approval:{roles:['finance','owner'],quorum:2}}
]});
const evalBase=(x={})=>evaluateAuthority({envelope:env,negotiation:neg,policy_bundle:policy(),identity_scopes:['artifact.read','artifact.write','host.notify'],context:{now,environment:'local',request_id:'req:1'},...x});
test('canonical unicode deterministic',()=>assert.equal(hash({界:'道',a:1}),hash({a:1,界:'道'})));
test('irreversible requires approval',()=>assert.equal(evalBase().status,'pending_approval'));
test('valid approval approves',()=>{const a=sealApproval({approval_id:'ap:1',proposal_root:env.proposal_root,approver_id:'human:owner',approver_roles:['owner'],decision:'approved',issued_at:'2026-06-30T11:00:00Z',expires_at:'2026-06-30T13:00:00Z'});assert.equal(evalBase({approvals:[a]}).status,'approved')});
test('stale approval rejected',()=>{const a=sealApproval({approval_id:'ap:stale',proposal_root:'0'.repeat(64),approver_id:'human:owner',approver_roles:['owner'],issued_at:'2026-06-30T11:00:00Z',expires_at:'2026-06-30T13:00:00Z'});assert.equal(evalBase({approvals:[a]}).status,'pending_approval')});
test('approver denial wins',()=>{const a=sealApproval({approval_id:'ap:no',proposal_root:env.proposal_root,approver_id:'human:owner',approver_roles:['owner'],decision:'denied',issued_at:'2026-06-30T11:00:00Z',expires_at:'2026-06-30T13:00:00Z'});assert.equal(evalBase({approvals:[a]}).status,'denied')});
test('delegation grants scope',()=>{const d=sealDelegation({delegation_id:'del:1',issuer_id:'human:owner',delegate_id:env.subject.subject_id,scopes:['artifact.*','host.notify'],capability_patterns:['*'],not_before:'2026-06-30T00:00:00Z',expires_at:'2026-07-01T00:00:00Z'});const a=sealApproval({approval_id:'ap:d',proposal_root:env.proposal_root,approver_id:'human:owner',approver_roles:['owner'],issued_at:'2026-06-30T11:00:00Z',expires_at:'2026-06-30T13:00:00Z'});assert.equal(evaluateAuthority({envelope:env,negotiation:neg,policy_bundle:policy(),delegations:[d],approvals:[a],identity_scopes:[],context:{now}}).status,'approved')});
test('expired delegation denied',()=>{const d=sealDelegation({delegation_id:'del:old',issuer_id:'x',delegate_id:env.subject.subject_id,scopes:['*'],not_before:'2020-01-01T00:00:00Z',expires_at:'2020-01-02T00:00:00Z'});assert.equal(evaluateAuthority({envelope:env,negotiation:neg,policy_bundle:policy(),delegations:[d],identity_scopes:[],context:{now}}).status,'denied')});
test('revoked delegation denied',()=>{const d=sealDelegation({delegation_id:'del:r',issuer_id:'x',delegate_id:env.subject.subject_id,scopes:['*'],not_before:'2026-01-01T00:00:00Z',expires_at:'2027-01-01T00:00:00Z'});const r=sealRevocationRegistry({registry_id:'rev:1',revoked_delegations:['del:r'],updated_at:now});assert.equal(evaluateAuthority({envelope:env,negotiation:neg,policy_bundle:policy(),delegations:[d],revocations:r,identity_scopes:[],context:{now}}).status,'denied')});
test('deny critical overrides',()=>{const n=structuredClone(neg);n.plan.steps[0].risk.level='critical';assert.equal(evaluateAuthority({envelope:env,negotiation:n,policy_bundle:policy(),identity_scopes:['*'],context:{now}}).status,'denied')});
test('high risk requires quorum 2',()=>{const n=structuredClone(neg);n.plan.steps[0].risk.level='high';n.plan.steps=n.plan.steps.filter(s=>s.reversible!==false);const a=sealApproval({approval_id:'a1',proposal_root:env.proposal_root,approver_id:'one',approver_roles:['owner'],issued_at:'2026-06-30T11:00:00Z',expires_at:'2026-06-30T13:00:00Z'});assert.equal(evaluateAuthority({envelope:env,negotiation:n,policy_bundle:policy(),identity_scopes:['*'],approvals:[a],context:{now}}).status,'pending_approval')});
test('high risk quorum passes',()=>{const n=structuredClone(neg);n.plan.steps[0].risk.level='high';n.plan.steps=n.plan.steps.filter(s=>s.reversible!==false);const as=['one','two'].map((id,i)=>sealApproval({approval_id:'a'+i,proposal_root:env.proposal_root,approver_id:id,approver_roles:[i?'security':'owner'],issued_at:'2026-06-30T11:00:00Z',expires_at:'2026-06-30T13:00:00Z'}));assert.equal(evaluateAuthority({envelope:env,negotiation:n,policy_bundle:policy(),identity_scopes:['*'],approvals:as,context:{now}}).status,'approved')});
test('authorized envelope output',()=>{const a=sealApproval({approval_id:'ap:e',proposal_root:env.proposal_root,approver_id:'human:owner',approver_roles:['owner'],issued_at:'2026-06-30T11:00:00Z',expires_at:'2026-06-30T13:00:00Z'});const r=evalBase({approvals:[a]});assert.equal(r.authorized_envelope.phase,'authorized');assert.equal(r.authorized_envelope.authority.status,'approved')});
test('pending does not authorize',()=>assert.equal(evalBase().authorized_envelope.phase,'proposed'));
test('tampered envelope rejected',()=>{const e=structuredClone(env);e.subject.subject_id='evil';assert.throws(()=>evalBase({envelope:e}),/ENVELOPE_ROOT_MISMATCH|ENVELOPE_INVALID/)});
test('ed25519 object signature',()=>{const k=generateEd25519Keypair(),v=signObject({a:1},k.private_key_pem,'signer:1');assert.equal(verifySignedObject(v,k.public_key_pem),true);v.a=2;assert.equal(verifySignedObject(v,k.public_key_pem),false)});
test('revoked approval no longer satisfies quorum',()=>{const a=sealApproval({approval_id:'ap:revoked',proposal_root:env.proposal_root,approver_id:'human:owner',approver_roles:['owner'],issued_at:'2026-06-30T11:00:00Z',expires_at:'2026-06-30T13:00:00Z'});const rr=sealRevocationRegistry({registry_id:'rr:1',revoked_approvals:['ap:revoked'],updated_at:now});assert.equal(evalBase({approvals:[a],revocations:rr}).status,'pending_approval')});
test('signed approval verifies independently of approval root',()=>{const k=generateEd25519Keypair();let a=sealApproval({approval_id:'ap:signed',proposal_root:env.proposal_root,approver_id:'human:owner',approver_roles:['owner'],issued_at:'2026-06-30T11:00:00Z',expires_at:'2026-06-30T13:00:00Z'});a=signObject(a,k.private_key_pem,'human:owner');assert.equal(verifySignedObject(a,k.public_key_pem),true);assert.equal(evalBase({approvals:[a],keyring:{'human:owner':k.public_key_pem},require_signatures:true}).status,'approved')});
test('decision root stable',()=>{const a=sealApproval({approval_id:'ap:s',proposal_root:env.proposal_root,approver_id:'human:owner',approver_roles:['owner'],issued_at:'2026-06-30T11:00:00Z',expires_at:'2026-06-30T13:00:00Z'});assert.equal(evalBase({approvals:[a]}).decision_root,evalBase({approvals:[a]}).decision_root)});
