// UI Update Engine — Empty State Templates v0.3
// 覆盖率 ≥ 90%：每个核心模块都有空状态。
export interface EmptyStateDefinition {
  moduleId: string;
  title: string;
  description: string;
  primaryAction: string;
  /** 主要跳转路由 —— 与 targetRoute 同义 */
  primaryRoute?: string;
  /** 推荐字段：跳转目标路由 */
  targetRoute: string;
  secondaryActions: string[];
  exampleInput: string;
  safetyNote?: string;
}

const es = (
  moduleId: string,
  title: string,
  description: string,
  primaryAction: string,
  targetRoute: string,
  secondaryActions: string[],
  exampleInput: string,
  safetyNote?: string,
): EmptyStateDefinition => ({
  moduleId, title, description, primaryAction,
  targetRoute, primaryRoute: targetRoute,
  secondaryActions, exampleInput, safetyNote,
});

export const EMPTY_STATE_TEMPLATES: EmptyStateDefinition[] = [
  // ---- PUBLIC / CORE ----
  es("free-input", "随便输入一句话",
     "你不需要懂模块，只要写下你要做的事。",
     "看个例子", "/usage-examples", ["问数列 AI", "查快速开始"],
     "我现在该不该推进这个项目？"),
  es("sequence-ai", "还没有对话",
     "你可以直接输入一个问题、想法、数列、歌词、世界设定或开发需求，系统会自动选择引擎。",
     "试一个示例", "/usage-examples", ["使用我的数列", "查看快速开始"],
     "解释 55555",
     "输出不保证现实必然发生，需以回验为准。"),
  es("subject-mode", "尚未切换主体",
     "你现在使用 Demo 主体。切换到真实主体后，输出会基于你自己的数列。",
     "设置真实主体", "/real-subject-setup", ["了解主体模式", "继续使用 Demo"],
     "查看当前主体模式",
     "Full60 默认本地保存，导出前会再次确认。"),
  es("real-subject-setup", "还在 Demo 模式",
     "设置 Light20 或 Full60，让系统给出真实主体级别的输出。",
     "设置 Light20", "/real-subject-setup", ["了解 Full60"],
     "输入你的真实主体数列",
     "Full60 默认本地保存，不会自动上传。"),
  es("usage-examples", "还没有挑选示例",
     "示例库里有覆盖每个模块的可复制输入。",
     "查看世界示例", "/usage-examples", ["查看 MSL 示例", "查看数列 AI 示例"],
     "显示世界引擎示例"),

  // ---- PUBLIC / IMPORTANT ----
  es("model-generation", "还没有模型",
     "把一个想法变成可保存、可导出、可回验的结构化模型。",
     "生成模型", "/model-forge", ["看个例子"],
     '给"蓝天机"生成角色模型'),
  es("narrative", "还没有剧情草案",
     "输入角色 / 世界 / 设定，剧情引擎会写出场景、对白与节拍。",
     "写一段试试", "/narrative-engine", ["导入世界", "看个例子"],
     "给蓝天机写一段漫画脚本"),
  es("vocal", "还没有声乐 Prompt",
     "输入歌词或氛围词，系统生成 Suno / Udio 提示词。",
     "生成 Prompt", "/vocal-engine", ["导入角色声线"],
     "把这段歌词生成 Suno prompt",
     "声乐提示不是医学声带诊断。"),
  es("translation", "还没有翻译任务",
     "输入要转译的词、概念或段落，并选择目标语言。",
     "翻译一段", "/translation-engine", ["看个例子"],
     "把『数列元智能驱动器』翻译成英文和日文",
     "翻译可能存在语境漂移，重要文本请人工校对。"),
  es("sequence-world", "还没有世界",
     "从一组数列开始生成你的第一个世界。",
     "用 55555 生成", "/sequence-world", ["导入 MSL", "看个例子"],
     "world.generate --from 55555",
     "生成结果是创作世界，不等于现实事实。"),
  es("world-knowledge", "还没查询知识",
     "查看产品知识、世界观、术语和模块说明。",
     "查 MSL", "/world-knowledge", ["查产品百科", "查使用示例"],
     "MSL 是什么？"),
  es("encyclopedia", "百科还没浏览",
     "用普通语言理解 Aetherworld 的核心概念。",
     "看『数列终端』", "/encyclopedia", ["看『主体模式』", "看『常数宇宙』"],
     "数列终端是什么？"),
  es("sequence-currency", "还没有内部贡献记录",
     "Sequence Currency 记录你在 Aetherworld 内部的贡献与积分。",
     "查看本日记录", "/sequence-currency", ["了解贡献规则"],
     "我今天生成了什么资产？",
     "数列货币不是现实货币，不支持提现、交易或投资。"),
  es("learn", "还没开始学习",
     "查看新手教程、模块文档、FAQ 和技术手册。",
     "开始新手教程", "/learn", ["查 FAQ", "查术语表"],
     "我不会用，给我新手教程"),

  // ---- ADVANCED ----
  es("msl", "还没有 MSL 输出",
     "输入一段 5 位数列，或运行一个 PROGRAM。",
     "解释 55555", "/msl-console", ["看 BLOCK 49..60"],
     "explain 55555",
     "MSL 是结构语言，不是绝对现实定律。"),
  es("sequence-terminal", "终端还没有命令",
     "用命令行驱动整个 Aetherworld。",
     "运行 world.sim", "/sequence-terminal", ["运行 ui.audit", "查看命令列表"],
     "world.sim run 49..60",
     "Founder 命令需要权限，普通命令不会执行现实动作。"),
  es("world-simulation", "还没有运行世界模拟",
     "先选择世界或输入一组数列，再运行 tick。",
     "用 55555 试运行", "/sequence-world", ["运行 BLOCK 49..60", "查看世界引擎说明"],
     "tick x10",
     "虚拟世界模拟不等于现实预测。"),
  es("world-growth", "还没有生长记录",
     "让世界自生长 / 突变 / 分支，每一步都会落入正典。",
     "生长一次", "/world-growth", ["看上一次生长"],
     "让这个世界安全生长一次",
     "生长结果是创作世界，不等于现实事实。"),
  es("world-society", "还没有社会图谱",
     "推演 NPC、阵营、信仰、经济结构。",
     "推一步社会", "/world-society", ["查看阵营"],
     "让这个世界形成三个阵营",
     "社会模型不等于现实社会预测。"),
  es("civilization", "还没有文明阶段",
     "推演文明时代、技术树、战争与和平。",
     "推进一个时代", "/civilization-evolution", ["看技术树"],
     "让这个文明进入下一个时代",
     "文明演化是虚拟创作，不预测现实文明走向。"),
  es("world-presentation", "还没有表现层参数",
     "生成 Godot/Unity/Three 表现配置。",
     "生成一组参数", "/world-presentation", ["导出 Godot"],
     "把 55555 变成 Godot 表现层参数",
     "表现层是创作参数，不代表真实物理或现实事件。"),
  es("constant-universe", "还没有查询常数",
     "查看 0–9 数字常数、五域、引擎权重、阈值和风险常数。",
     "查看数字 5", "/digit-constants", ["运行常数审计"],
     "查看数字 5 的全引擎常数",
     "系统常数不是现实宇宙定律。"),
  es("system-constitution", "还没有运行宪法检查",
     "对一段输出做宪法合规检查。",
     "运行合规检查", "/system-constitution", ["查看主体主权", "查看 CRITICAL 违规"],
     'constitution.check "数列货币可以提现"',
     "系统宪法是治理规范，不是现实法律文件。"),
  es("hybrid-compression", "还没有压缩输出",
     "把复杂结果压缩成普通用户版黑白箱输出。",
     "压缩上一条", "/hybrid-compression", ["查看黑箱信号"],
     "把上一条结果压缩成普通用户版",
     "黑箱信号不是确定事实，需结合白箱核对。"),
  es("prompt-forge", "还没有提示词",
     "把世界、主体和目标变成 Prompt。",
     "锻造一条", "/abstract-prompt-forge", ["看历史 Prompt"],
     "为蓝天机锻造一条 Lovable 提示词",
     "提示词需要人工测试，避免直接上线。"),

  // ---- QUALITY ----
  es("software-qa", "还没有 QA 报告",
     "运行系统级软件质量检查。",
     "运行 QA", "/software-qa", ["按模块筛选", "导出报告"],
     "qa.run",
     "QA 用于系统质量审计，不代表现实必然正确。"),
  es("recalculation", "还没有重算任务",
     "对 stale 项重新计算并回写。",
     "重算 stale", "/recalculation", ["查看上次重算"],
     "recalc.stale",
     "重算结果仅作系统一致性使用。"),
  es("ui-update", "还没有 UI 审计",
     "检查 Quick Start、Sidebar、Empty State、Safety Note 缺口。",
     "运行 UI 审计", "/ui-update-engine", ["查看 Quick Start", "查看修复提示词"],
     "ui.audit"),
  es("interface-audit", "还没有界面审计",
     "完整界面审计，含权限与子路由。",
     "运行界面审计", "/interface-audit", ["导出审计 JSON"],
     "ui.audit --full"),

  // ---- FOUNDER ----
  es("docs-audit", "还没有文档审计",
     "检查文档完整性、版本与安全提示。",
     "运行 Docs Audit", "/docs-audit", ["导出审计"],
     "docs.audit"),
];

export function getEmptyState(moduleId: string): EmptyStateDefinition | undefined {
  return EMPTY_STATE_TEMPLATES.find((e) => e.moduleId === moduleId);
}
