// UI Update Engine — Quick Start Templates v0.3
// 覆盖所有 PUBLIC / ADVANCED / FOUNDER 核心模块，满足 UI Audit 90% 入口完整性。
import type { UIUserMode } from "./uiUserModes";

export interface QuickStartTemplate {
  id: string;
  title: string;
  description: string;
  userMode: "PUBLIC" | "ADVANCED" | "FOUNDER";
  subjectModeRequirement: "ANY" | "DEMO" | "LIGHT_20" | "FULL_60" | "FOUNDER";
  targetRoute: string;
  targetModuleId: string;
  /** moduleId 别名 —— 与 targetModuleId 同义，方便外部读取 */
  moduleId?: string;
  exampleInput: string;
  expectedOutput: string;
  priority: number;
  safetyNote?: string;
}

const qs = (
  id: string,
  moduleId: string,
  userMode: QuickStartTemplate["userMode"],
  title: string,
  description: string,
  targetRoute: string,
  exampleInput: string,
  expectedOutput: string,
  priority: number,
  safetyNote?: string,
  subjectModeRequirement: QuickStartTemplate["subjectModeRequirement"] = "ANY",
): QuickStartTemplate => ({
  id, title, description, userMode, subjectModeRequirement,
  targetRoute, targetModuleId: moduleId, moduleId,
  exampleInput, expectedOutput, priority, safetyNote,
});

/** PUBLIC · 普通用户 Quick Start（14 项） */
export const PUBLIC_QUICK_START: QuickStartTemplate[] = [
  qs("qs-pub-1",  "free-input",        "PUBLIC", "随便问",
     "不用懂模块，直接输入你想分析、生成、翻译、创作或开发的内容。",
     "/free-input",
     "我现在该不该推进这个项目？",
     "结构分析、下一步动作、验证点。", 1),
  qs("qs-pub-2",  "sequence-ai",       "PUBLIC", "问数列 AI",
     "让 Sequence AI 自动选择合适引擎并给出结构化结论。",
     "/sequence-ai",
     "帮我分析这个想法，并给下一步。",
     "引擎路由、结构化回答、行动建议。", 2,
     "输出不保证现实必然发生，需以回验为准。"),
  qs("qs-pub-3",  "subject-mode",      "PUBLIC", "查看当前主体模式",
     "确认当前是 Demo、Light20、Full60 还是 Founder。",
     "/subject-mode",
     "查看当前主体模式。",
     "当前主体、隐私状态、是否需要切换。", 3,
     "Full60 默认本地保存，导出前会再次确认。"),
  qs("qs-pub-4",  "real-subject-setup","PUBLIC", "设置真实主体",
     "输入 Light20 或 Full60，让系统从 Demo 进入真实主体模式。",
     "/real-subject-setup",
     "粘贴 20 组或 60 组数列。",
     "识别数量、主体模式、隐私提示。", 4,
     "Full60 默认本地保存，不会自动上传。"),
  qs("qs-pub-5",  "model-generation",  "PUBLIC", "生成模型",
     "把一个想法变成可保存、可导出、可回验的结构化模型。",
     "/model-forge",
     "把『个人世界生成器』抽象成数据模型。",
     "字段、结构、验证点、导出格式。", 5),
  qs("qs-pub-6",  "sequence-world",    "PUBLIC", "生成世界",
     "用数列生成世界、区域、NPC、任务和表现层。",
     "/sequence-world",
     "用 55555 生成一个世界。",
     "世界状态、区域、NPC、任务、导出选项。", 6,
     "虚拟世界不等于现实，仅用于创作与推演。"),
  qs("qs-pub-7",  "narrative",         "PUBLIC", "写剧情",
     "把世界、角色或事件转成剧情文本。",
     "/narrative-engine",
     "给蓝天机写一段漫画开场。",
     "剧情片段、角色动作、分镜建议。", 7),
  qs("qs-pub-8",  "vocal",             "PUBLIC", "生成声乐提示词",
     "把歌词、角色或世界氛围转成 Suno / AI 音乐提示词。",
     "/vocal-engine",
     "把这段歌词生成 Suno prompt。",
     "曲风、情绪、声音、结构提示词。", 8,
     "声乐提示不是医学声带诊断。"),
  qs("qs-pub-9",  "translation",       "PUBLIC", "翻译与概念转译",
     "支持简中、繁中、英文、日文、韩文、法文之间的概念转译。",
     "/translation-engine",
     "把『数列元智能驱动器』翻译成英文和日文。",
     "多语言译名、语气说明、使用场景。", 9,
     "翻译可能存在语境漂移，重要文本请人工校对。"),
  qs("qs-pub-10", "world-knowledge",   "PUBLIC", "查世界知识",
     "查看产品知识、世界观、术语和模块说明。",
     "/world-knowledge",
     "MSL 是什么？",
     "知识条目、来源、可信度、相关模块。", 10),
  qs("qs-pub-11", "encyclopedia",      "PUBLIC", "查产品百科",
     "用普通语言理解 Aetherworld 的核心概念。",
     "/encyclopedia",
     "数列终端是什么？",
     "简明解释、技术解释、使用例子。", 11),
  qs("qs-pub-12", "usage-examples",    "PUBLIC", "看使用示例",
     "不知道怎么输入时，先看现成示例。",
     "/usage-examples",
     "显示世界引擎示例。",
     "可复制输入、预期输出、目标模块。", 12),
  qs("qs-pub-13", "sequence-currency", "PUBLIC", "查看内部积分与贡献",
     "查看 Aetherworld 内部贡献、积分和虚拟资源。",
     "/sequence-currency",
     "我今天生成了什么资产？",
     "内部价值记录、贡献说明、安全边界。", 13,
     "数列货币不是现实货币，不支持提现、交易或投资。"),
  qs("qs-pub-14", "learn",             "PUBLIC", "学习中心",
     "查看新手教程、模块文档、FAQ 和技术手册。",
     "/learn",
     "我不会用，给我新手教程。",
     "学习路径、教程步骤、相关文档。", 14),
];

/** ADVANCED · 高阶用户 Quick Start（14 项） */
export const ADVANCED_QUICK_START: QuickStartTemplate[] = [
  qs("qs-adv-1",  "msl",                  "ADVANCED", "运行 MSL",
     "用母体数列语言运行一段程序。",
     "/msl-console",
     "解释 55555。",
     "五域解析、数字含义、模块路由。", 1,
     "MSL 是结构语言，不是绝对现实定律。"),
  qs("qs-adv-2",  "sequence-terminal",    "ADVANCED", "使用数列终端",
     "命令行驱动整个 Aetherworld。",
     "/sequence-terminal",
     "world.sim run 49..60",
     "终端执行结果、trace、导出选项。", 2,
     "终端命令不执行现实动作，Founder 命令需权限。"),
  qs("qs-adv-3",  "world-simulation",     "ADVANCED", "运行世界模拟",
     "对当前世界推进一次 tick。",
     "/world-simulation",
     "用 55555 推进世界一次。",
     "tick、事件、NPC、资源、因果链。", 3,
     "虚拟世界模拟不等于现实预测。"),
  qs("qs-adv-4",  "world-growth",         "ADVANCED", "让世界生长",
     "让世界自生长 / 突变 / 分支。",
     "/world-growth",
     "让这个世界安全生长一次。",
     "新增区域、NPC、规则、正典更新。", 4,
     "生长结果是创作世界，不等于现实事实。"),
  qs("qs-adv-5",  "world-society",        "ADVANCED", "生成世界社会",
     "推演 NPC、阵营、信仰、经济。",
     "/world-society",
     "让这个世界形成三个阵营。",
     "阵营、组织、社会关系、冲突。", 5,
     "社会模型不等于现实社会预测。"),
  qs("qs-adv-6",  "civilization",         "ADVANCED", "生成文明演化",
     "时代转换、技术树、战争与和平。",
     "/civilization-evolution",
     "让这个文明进入下一个时代。",
     "时代、历史事件、技术树、文明周期。", 6,
     "文明演化是虚拟创作，不预测现实文明走向。"),
  qs("qs-adv-7",  "world-presentation",   "ADVANCED", "生成世界表现层",
     "生成 Godot/Unity/Three 表现配置。",
     "/world-presentation",
     "把 55555 变成 Godot 表现层参数。",
     "渲染、语义物理、动画、镜头、声音参数。", 7,
     "表现层是创作参数，不代表真实物理或现实事件。"),
  qs("qs-adv-8",  "constant-universe",    "ADVANCED", "查看常数宇宙",
     "查看 0–9 数字常数、五域、引擎权重、阈值和风险常数。",
     "/constants-universe",
     "查看数字 5 的全引擎常数。",
     "数字含义、使用模块、风险边界。", 8,
     "系统常数不是现实宇宙定律。"),
  qs("qs-adv-9",  "system-constitution",  "ADVANCED", "查看系统宪法",
     "对一段输出做宪法合规检查。",
     "/system-constitution",
     "查看主体主权条款。",
     "宪法条款、权限边界、违规规则。", 9,
     "系统宪法是治理规范，不是现实法律文件。"),
  qs("qs-adv-10", "hybrid-compression",   "ADVANCED", "压缩复杂输出",
     "把上一条结果压缩成普通用户版黑白箱输出。",
     "/hybrid-compression",
     "把上一条结果压缩成普通用户版。",
     "结论、原因、下一步、验证点。", 10,
     "黑箱信号不是确定事实，需结合白箱核对。"),
  qs("qs-adv-11", "software-qa",          "ADVANCED", "运行软件 QA",
     "运行系统级软件质量检查。",
     "/software-qa",
     "检查当前系统缺口。",
     "PASS / WARN / FAIL、严重等级、修复建议。", 11,
     "QA 用于系统质量审计，不代表现实必然正确。"),
  qs("qs-adv-12", "recalculation",        "ADVANCED", "重新计算",
     "对 stale 项重新计算并回写。",
     "/recalculation",
     "重新计算 stale 结果。",
     "过期项、重算结果、失败原因。", 12,
     "重算结果仅作系统一致性使用。"),
  qs("qs-adv-13", "ui-update",            "ADVANCED", "更新 UI 入口",
     "检查 Quick Start、Sidebar、Empty State、Safety Note 缺口。",
     "/ui-update-engine",
     "检查 UI 缺什么。",
     "缺失入口、过期 UI、修复提示词。", 13),
  qs("qs-adv-14", "interface-audit",      "ADVANCED", "运行界面审计",
     "检查快速开始、侧边栏、权限暴露和死路由。",
     "/interface-audit",
     "检查快速开始和侧边栏。",
     "dead route、缺失入口、权限风险。", 14),
];

/** FOUNDER · 创始人 Quick Start（17 项） */
export const FOUNDER_QUICK_START: QuickStartTemplate[] = [
  qs("qs-fnd-1",  "founder-terminal",        "FOUNDER", "Founder Terminal",
     "Founder 专属终端，可执行受限指令。",
     "/founder-terminal",
     "founder.status",
     "Founder 状态、权限矩阵、可执行命令。", 1,
     "Founder Terminal 含特权命令，须谨慎使用。", "FOUNDER"),
  qs("qs-fnd-2",  "system-constitution",     "FOUNDER", "System Constitution",
     "查看系统宪法全文与修订历史。",
     "/system-constitution",
     "constitution.summary",
     "宪法摘要、版本、Founder Locked 条款。", 2,
     "系统宪法不是现实法律文件。", "FOUNDER"),
  qs("qs-fnd-3",  "constitutional-compliance","FOUNDER", "Constitutional Compliance",
     "对一段输出做宪法合规检查。",
     "/constitution-violations",
     'constitution.check "..."',
     "合规状态、触发条款、修复建议。", 3,
     "合规检查不是司法判定。", "FOUNDER"),
  qs("qs-fnd-4",  "constitutional-amendments","FOUNDER", "Constitutional Amendments",
     "提交、审阅与归档宪法修订案。",
     "/constitution",
     "amendment.list",
     "修订案列表、状态、Founder 锁定信息。", 4,
     "修订需走 Founder 流程，普通用户无权操作。", "FOUNDER"),
  qs("qs-fnd-5",  "constant-universe",       "FOUNDER", "Constant Universe",
     "查看常数宇宙与全引擎引用。",
     "/constants-universe",
     "constants list",
     "常数列表、引擎引用、风险标签。", 5,
     "系统常数不是现实宇宙定律。", "FOUNDER"),
  qs("qs-fnd-6",  "constant-audit",          "FOUNDER", "Constant Audit",
     "运行常数审计，发现冲突与漂移。",
     "/constant-audit",
     "constants audit",
     "冲突报告、漂移项、修复建议。", 6, undefined, "FOUNDER"),
  qs("qs-fnd-7",  "constant-versions",       "FOUNDER", "Constant Versions",
     "查看常数版本与回滚点。",
     "/constant-versions",
     "constants versions",
     "版本列表、差异、回滚选项。", 7, undefined, "FOUNDER"),
  qs("qs-fnd-8",  "ui-update",               "FOUNDER", "UI Update Engine",
     "治理界面入口、Quick Start、Sidebar。",
     "/ui-update-engine",
     "ui.audit",
     "UI 审计报告、缺失入口、修复提示词。", 8, undefined, "FOUNDER"),
  qs("qs-fnd-9",  "interface-audit",         "FOUNDER", "Interface Audit",
     "完整界面审计，含权限与子路由。",
     "/interface-audit",
     "ui.audit --full",
     "Dead route、Permission leak、stale 入口。", 9, undefined, "FOUNDER"),
  qs("qs-fnd-10", "software-qa",             "FOUNDER", "Full System QA",
     "运行全系统软件质量检查。",
     "/software-qa",
     "qa.run --all",
     "完整 QA 报告、严重等级、修复优先级。", 10,
     "QA 不代表现实必然正确。", "FOUNDER"),
  qs("qs-fnd-11", "recalculation",           "FOUNDER", "Recalculation",
     "重算所有 stale 依赖。",
     "/recalculation",
     "recalc.all",
     "stale → clean、失败原因。", 11, undefined, "FOUNDER"),
  qs("qs-fnd-12", "system-integration-audit","FOUNDER", "System Integration Audit",
     "检查跨引擎集成与宪法接入。",
     "/system-audit",
     "system.audit",
     "集成缺口、宪法接入、版本一致性。", 12, undefined, "FOUNDER"),
  qs("qs-fnd-13", "integration-audit",       "FOUNDER", "Integration Audit",
     "检查模块之间的接入关系。",
     "/integration-audit",
     "integration.audit",
     "未接入模块、孤岛、引用关系。", 13, undefined, "FOUNDER"),
  qs("qs-fnd-14", "sub-route-audit",         "FOUNDER", "Sub-Route Audit",
     "检查子路由权限、死路由与重复路径。",
     "/subroute-audit",
     "route.audit",
     "子路由问题、权限泄漏、重复路径。", 14, undefined, "FOUNDER"),
  qs("qs-fnd-15", "docs-audit",              "FOUNDER", "Docs Audit",
     "检查文档完整性、版本与安全提示。",
     "/docs-audit",
     "docs.audit",
     "文档缺口、过期项、安全提示。", 15, undefined, "FOUNDER"),
  qs("qs-fnd-16", "engine-registry",         "FOUNDER", "Engine Registry",
     "查看所有引擎注册表与依赖。",
     "/founder-console",
     "engine.list",
     "引擎清单、版本、依赖关系。", 16, undefined, "FOUNDER"),
  qs("qs-fnd-17", "full-system-export",      "FOUNDER", "Full System Export",
     "导出 Founder 系统级报告与快照。",
     "/engine-export",
     "system.export",
     "完整系统报告、快照、可回滚包。", 17,
     "导出包可能含 Founder 敏感数据，谨慎共享。", "FOUNDER"),
];

export const QUICK_START_TEMPLATES_V2 = {
  PUBLIC: PUBLIC_QUICK_START,
  ADVANCED: ADVANCED_QUICK_START,
  FOUNDER: FOUNDER_QUICK_START,
};

export const ALL_QUICK_START_TEMPLATES: QuickStartTemplate[] = [
  ...PUBLIC_QUICK_START, ...ADVANCED_QUICK_START, ...FOUNDER_QUICK_START,
];

export type { UIUserMode };
