import { createHash, randomUUID } from 'node:crypto';
export class ContractError extends Error {}
const keySort=(a,b)=>Buffer.compare(Buffer.from(a,'utf8'),Buffer.from(b,'utf8'));
export function canonicalJson(v){
 if(v===null)return'null'; if(v===true)return'true'; if(v===false)return'false';
 if(typeof v==='number'){ if(!Number.isSafeInteger(v)) throw new ContractError('RNCS_HASH_FLOAT_FORBIDDEN: use an integer or decimal string'); return String(v); }
 if(typeof v==='string')return JSON.stringify(v);
 if(Array.isArray(v))return`[${v.map(canonicalJson).join(',')}]`;
 if(typeof v==='object'){return`{${Object.keys(v).sort(keySort).map(k=>`${canonicalJson(k)}:${canonicalJson(v[k])}`).join(',')}}`;}
 throw new ContractError(`RNCS_HASH_TYPE_UNSUPPORTED:${typeof v}`);
}
export const rootHash=v=>createHash('sha256').update(canonicalJson(v)).digest('hex');
export const without=(o,...fs)=>Object.fromEntries(Object.entries(o).filter(([k])=>!fs.includes(k)));
const clone=v=>structuredClone(v), req=(c,e)=>{if(!c)throw new ContractError(e)}, hex64=v=>typeof v==='string'&&/^[0-9a-f]{64}$/.test(v);
const rooted=(v,f)=>{const o=clone(v);delete o[f];o[f]=rootHash(o);return o};
const subject=s=>{const o={subject_id:String(s.subject_id??s.id??''),kind:String(s.kind??'human'),roles:[...new Set((s.roles??[]).map(String))].sort(keySort),responsibility_boundary:String(s.responsibility_boundary??'declared-operation')};req(o.subject_id,'SUBJECT_ID_REQUIRED');if(s.identity_root)o.identity_root=String(s.identity_root);return o};
const generation=g=>{const o={reality_id:String(g.reality_id??''),generation:Number(g.generation??0),generation_root:String(g.generation_root??'0'.repeat(64))};req(o.reality_id,'REALITY_ID_REQUIRED');req(Number.isSafeInteger(o.generation)&&o.generation>=0,'GENERATION_INVALID');req(hex64(o.generation_root),'GENERATION_ROOT_INVALID');return o};
const intent=i=>rooted({intent_id:String(i.intent_id??`intent:${randomUUID()}`),source:String(i.source??''),goals:clone(i.goals??[]),constraints:clone(i.constraints??[])},'intent_root');
const plan=p=>rooted({plan_id:String(p.plan_id??`plan:${randomUUID()}`),capabilities:clone(p.capabilities??[]),host_bindings:clone(p.host_bindings??[]),required_scopes:[...new Set((p.required_scopes??[]).map(String))].sort(keySort)},'plan_root');
const delta=d=>rooted({operations:clone(d?.operations??[]),provisional:true},'delta_root');
const causal=c=>rooted({events:clone(c?.events??[]),rules:clone(c?.rules??[]),simulation_refs:clone(c?.simulation_refs??[])},'causal_root');const foundationGovernance=f=>{const d={explicitVariables:[],uncertainty:{status:'undeclared',variables:[]},providerCapabilities:{required:[],externalSideEffects:false},authorityRequirements:[],irreversibleEffects:[],invariants:[],adaptiveInvariantField:{version:'0.1.0',mode:'static-plus-runtime',active:[]},causalParents:[],evidenceRequirements:[]};const o={...d,...clone(f??{})};for(const k of ['explicitVariables','authorityRequirements','irreversibleEffects','invariants','causalParents','evidenceRequirements'])o[k]=clone(o[k]??[]);o.uncertainty=clone(o.uncertainty??d.uncertainty);o.providerCapabilities=clone(o.providerCapabilities??d.providerCapabilities);o.adaptiveInvariantField=clone(o.adaptiveInvariantField??d.adaptiveInvariantField);return o};
const evidence=e=>{const nodes=(e?.nodes??[]).map(raw=>{const n=clone(raw);n.evidence_id??=`evidence:${randomUUID()}`;n.kind??='declaration';n.source??='unknown';delete n.node_root;n.node_root=rootHash(n);return n}).sort((a,b)=>keySort(a.evidence_id,b.evidence_id));const edges=clone(e?.edges??[]).sort((a,b)=>keySort(rootHash(a),rootHash(b)));return rooted({nodes,edges},'evidence_root')};
export const proposalPayload=e=>({format:e.format,contract_version:e.contract_version,transition_id:e.transition_id,base_generation:e.base_generation,subject:e.subject,intent_root:e.intent.intent_root,plan_root:e.capability_plan.plan_root,inputs:e.inputs,delta_root:e.provisional_delta.delta_root,causal_root:e.causal_basis.causal_root,evidence_root:e.evidence.evidence_root,host_state_refs:e.host_state_refs,foundation_governance:e.foundation_governance,extensions:e.extensions??{}});
export const reseal=e=>{const o=clone(e);delete o.envelope_root;o.envelope_root=rootHash(o);return o};
export function newProposal(x){let e={format:'rncs.reality-transition-envelope.v0.1',contract_version:'0.1.0',transition_id:x.transition_id??`transition:${randomUUID()}`,phase:'proposed',base_generation:generation({reality_id:x.reality_id,generation:x.base_generation,generation_root:x.base_generation_root}),subject:subject(x.subject),intent:intent(x.intent),capability_plan:plan(x.capability_plan),inputs:clone(x.inputs??[]),provisional_delta:delta(x.provisional_delta),causal_basis:causal(x.causal_basis),authority:{status:'pending',claims:[],constraints:[]},evidence:evidence(x.evidence),commit:{status:'not_committed'},projections:[],host_state_refs:clone(x.host_state_refs??[]),foundation_governance:foundationGovernance(x.foundation_governance??x.extensions?.rcl?.foundation_governance),extensions:clone(x.extensions??{})};e.proposal_root=rootHash(proposalPayload(e));return reseal(e)}
export function authorize(e,{status,resolver,claims=[],constraints=[],reason=''}){const v=verify(e);req(v.valid,'ENVELOPE_INVALID:'+v.errors.join(','));req(e.phase==='proposed','AUTHORITY_PHASE_INVALID');req(['approved','denied'].includes(status),'AUTHORITY_STATUS_INVALID');const o=clone(e),d={status,resolver:String(resolver),proposal_root:o.proposal_root,claims:clone(claims),constraints:clone(constraints),reason:String(reason)};d.decision_root=rootHash(d);o.authority=d;if(status==='approved')o.phase='authorized';else{o.phase='rejected';o.commit={status:'rejected',reason:String(reason),decision_root:d.decision_root}}return reseal(o)}
export function commit(e,{generation:g,generation_root,receipt_refs=[]}){const v=verify(e);req(v.valid,'ENVELOPE_INVALID:'+v.errors.join(','));req(e.phase==='authorized','COMMIT_PHASE_INVALID');req(e.authority.status==='approved','COMMIT_AUTHORITY_NOT_APPROVED');req(g>e.base_generation.generation,'COMMIT_GENERATION_NOT_ADVANCED');req(hex64(generation_root),'COMMIT_GENERATION_ROOT_INVALID');if(e.foundation_governance){const f=e.foundation_governance;req(Array.isArray(f.explicitVariables)&&f.uncertainty&&f.providerCapabilities&&Array.isArray(f.authorityRequirements)&&Array.isArray(f.irreversibleEffects)&&Array.isArray(f.invariants)&&f.adaptiveInvariantField&&Array.isArray(f.causalParents)&&Array.isArray(f.evidenceRequirements),'FOUNDATION_4R_GATE_FAILED')}const o=clone(e),result={reality_id:e.base_generation.reality_id,generation:g,generation_root};const p={proposal_root:o.proposal_root,decision_root:o.authority.decision_root,result_generation:result,receipt_refs:clone(receipt_refs)};p.commit_root=rootHash(p);o.commit={status:'committed',...p};o.phase='committed';return reseal(o)}
export function attachProjection(e,p){const v=verify(e);req(v.valid,'ENVELOPE_INVALID:'+v.errors.join(','));req(['committed','projected'].includes(e.phase),'PROJECTION_REQUIRES_COMMIT');const x=clone(p);for(const k of ['projection_id','observer_id','modality','target_host','semantic_root'])req(x[k],`PROJECTION_${k.toUpperCase()}_REQUIRED`);req(hex64(x.semantic_root),'PROJECTION_SEMANTIC_ROOT_INVALID');delete x.projection_root;x.projection_root=rootHash(x);const o=clone(e);o.projections.push(x);o.projections.sort((a,b)=>keySort(a.projection_id,b.projection_id));o.phase='projected';return reseal(o)}
export function verify(e){const errors=[],check=(c,x)=>{if(!c)errors.push(x)};if(!e||typeof e!=='object')return{valid:false,errors:['ENVELOPE_NOT_OBJECT']};try{check(e.format==='rncs.reality-transition-envelope.v0.1','FORMAT_INVALID');check(e.contract_version==='0.1.0','VERSION_INVALID');check(rootHash(without(e,'envelope_root'))===e.envelope_root,'ENVELOPE_ROOT_MISMATCH');check(rootHash(proposalPayload(e))===e.proposal_root,'PROPOSAL_ROOT_MISMATCH');check(rootHash(without(e.intent,'intent_root'))===e.intent.intent_root,'INTENT_ROOT_MISMATCH');check(rootHash(without(e.capability_plan,'plan_root'))===e.capability_plan.plan_root,'PLAN_ROOT_MISMATCH');check(rootHash(without(e.provisional_delta,'delta_root'))===e.provisional_delta.delta_root,'DELTA_ROOT_MISMATCH');check(rootHash(without(e.causal_basis,'causal_root'))===e.causal_basis.causal_root,'CAUSAL_ROOT_MISMATCH');check(rootHash(without(e.evidence,'evidence_root'))===e.evidence.evidence_root,'EVIDENCE_ROOT_MISMATCH');for(const n of e.evidence.nodes)check(rootHash(without(n,'node_root'))===n.node_root,'EVIDENCE_NODE_ROOT_MISMATCH');if(['approved','denied'].includes(e.authority?.status)){check(rootHash(without(e.authority,'decision_root'))===e.authority.decision_root,'DECISION_ROOT_MISMATCH');check(e.authority.proposal_root===e.proposal_root,'DECISION_PROPOSAL_MISMATCH')}if(e.commit?.status==='committed'){check(rootHash(without(e.commit,'status','commit_root'))===e.commit.commit_root,'COMMIT_ROOT_MISMATCH');check(e.commit.decision_root===e.authority.decision_root,'COMMIT_DECISION_MISMATCH');check(e.commit.result_generation.generation>e.base_generation.generation,'COMMIT_GENERATION_NOT_ADVANCED')}for(const p of e.projections??[])check(rootHash(without(p,'projection_root'))===p.projection_root,'PROJECTION_ROOT_MISMATCH');for(const r of e.host_state_refs??[]){check(!('generation'in r),'HOST_STATE_MUST_NOT_DECLARE_GENERATION');check('snapshot_sequence'in r,'HOST_STATE_SNAPSHOT_SEQUENCE_REQUIRED')}}catch(err){errors.push(`VERIFY_EXCEPTION:${err.name}:${err.message}`)}return{valid:!errors.length,errors,envelope_root:e.envelope_root,phase:e.phase}}
export function adaptHnacSnapshot(s,host_id='unknown-host'){const state=s.state??s;return{kind:'host-state',source_format:s.format??state.format??'hnaf.portable-state.v0.5',host_id,replica_id:String(s.replicaId??s.replica_id??'unknown-replica'),snapshot_sequence:Number(s.snapshot_sequence??s.generation??0),state_root:String(s.snapshotRoot??s.snapshot_root??state.state_root??rootHash(state)),schema_version:String(state.schema_version??'unknown'),partitions:Object.keys(state.partitions??{}).sort(keySort),continuity_class:'replica_snapshot'}}
export * from './entity-kernel.mjs';
export * from './representation-ref.mjs';
export * from './representation-transition.mjs';
