import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {RealityOneGateway,discoverRuntimeManifests,GatewayError} from '../src/index.mjs';
const root=path.resolve(import.meta.dirname,'..');const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'reality-one-v03-'));
test('discovers seventeen unified runtimes including the native Aetherworld and RCL bridges',async()=>{const g=new RealityOneGateway({manifestDirs:[path.join(root,'runtimes')],dataDir:tmp()});const r=await g.discover();assert.equal(r.runtimes.length,17);assert.ok(r.runtime_order.includes('rncs.aetherworld-native'));assert.ok(r.runtime_order.includes('rncs.rcl-control'));assert.ok(r.runtime_order.indexOf('rncs.network')<r.runtime_order.indexOf('rncs.aetherworld-native'));assert.ok(r.runtime_order.indexOf('rncs.vsr')<r.runtime_order.indexOf('rncs.aetherworld-native'));assert.match(r.registry_root,/^[0-9a-f]{64}$/);});
test('all packaged runtimes pass dynamic health checks',async()=>{const g=new RealityOneGateway({manifestDirs:[path.join(root,'runtimes')],dataDir:tmp()});await g.discover();const h=await g.health();assert.equal(h.status,'healthy');assert.equal(h.runtimes.filter(x=>x.status==='healthy').length,17);});
test('higher compatible runtime version wins without source copying',()=>{const d=tmp();const base=JSON.parse(fs.readFileSync(path.join(root,'runtimes','rfe.runtime.json'),'utf8'));for(const v of ['0.0.9','0.1.0']){const m=structuredClone(base);m.runtime_version=v;fs.writeFileSync(path.join(d,`rfe-${v}.runtime.json`),JSON.stringify(m));}const {registry}=discoverRuntimeManifests([d]);assert.equal(registry.runtimes[0].runtime_version,'0.1.0');});
test('undeclared actions are rejected before invocation',async()=>{const g=new RealityOneGateway({manifestDirs:[path.join(root,'runtimes')],dataDir:tmp()});await g.discover();await assert.rejects(()=>g.invoke('rncs.laf','deleteEverything',{}),e=>e.code==='RUNTIME_ACTION_NOT_DECLARED');});
test('RCL runtime compiles and executes a source program through the Gateway',async()=>{const g=new RealityOneGateway({manifestDirs:[path.join(root,'runtimes')],dataDir:tmp()});await g.discover();const h=await g.invoke('rncs.rcl-control','health',{});assert.equal(h.status,'ok');const result=await g.invoke('rncs.rcl-control','compileExecute',{source:'reality GatewayRcl { facet world.ready : Truth = true facet world.value : Number = 7 }'});assert.equal(result.parity.ok,true);assert.equal(result.native.state['world.ready'],true);assert.equal(result.native.state['world.value'],7);});
test('RCL native authority workflow commits through the RNCS RFE store',async()=>{const g=new RealityOneGateway({manifestDirs:[path.join(root,'runtimes')],dataDir:tmp()});await g.discover();const before=await g.invoke('rncs.aetherworld-native','worldStatus',{});const result=await g.invoke('rncs.rcl-control','authorityWorkflow',{source:'reality GatewayRclAuthority { facet rncs.world.world_id : Text = "world:aether-island" facet rncs.world.title : Text = "RCL owns the authoritative title" facet rncs.world.rcl_marker : Truth = true }',commit:true,approvalRoles:['owner','security'],expectedStateRoot:before.state_root,expectedRevision:before.revision},{timeoutMs:120000,idempotencyKey:`rcl-authority:${before.state_root}`});assert.equal(result.status,'committed');assert.equal(result.committed,true);assert.equal(result.authority.authorized,true);assert.equal(result.merge.evidence.rfe_commit_receipt.integrityHash.length,64);assert.equal(result.merge.evidence.rcl_native_evidence.parity_verified,true);assert.equal(result.merge.evidence.rcl_native_evidence.bytecode_hash,result.execution.bytecodeHash);assert.equal(result.after.revision>before.revision,true);assert.equal(result.after.state_root!==before.state_root,true);const after=await g.invoke('rncs.aetherworld-native','worldStatus',{});assert.equal(after.revision,result.after.revision);assert.equal(after.state_root,result.after.state_root);await assert.rejects(()=>g.invoke('rncs.rcl-control','authorityWorkflow',{source:'reality GatewayRclAuthority { facet rncs.world.title : Text = "stale" }',commit:true,approvalRoles:['owner','security'],expectedStateRoot:before.state_root,expectedRevision:before.revision},{timeoutMs:120000}),e=>e.code==='RCL_AUTHORITY_STATE_ROOT_MISMATCH'||e.code==='RCL_AUTHORITY_REVISION_MISMATCH');});
