import fs from 'node:fs';
import path from 'node:path';
import {compileReality,compileRealityToBytecode,RCL_LANGUAGE_VERSION} from '@taowind/reality-computation-language';
import {clone,rootHash,seal} from '../../../world/reality-asset-genesis-fabric/src/canonical.mjs';
import {BODY_PARAMETER_DEFINITIONS,FACE_PARAMETER_DEFINITIONS,createCharacterGenome,validateCharacterGenome} from '../../../world/character-genome-runtime/src/index.mjs';
import {compileCharacterPhenotype,verifyCharacterAssetDirectory} from '../../../world/character-phenotype-compiler/src/index.mjs';
import {parseCharacterGenomeSource} from './parser.mjs';

export const RCL_CHARACTER_GENOME_DIALECT_VERSION='0.1.0-alpha.1';
const faceNames=new Set(FACE_PARAMETER_DEFINITIONS.map(item=>item.semantic_name)),bodyNames=new Set(BODY_PARAMETER_DEFINITIONS.map(item=>item.parameter_id.split('.').at(-1)));
const eyeColors={'imperial-blue':'#4f86c6','cool-blue':'#5d91ce','graphite-red':'#985044','forest-green':'#66805b'};
const safe=value=>String(value).replace(/[^a-zA-Z0-9_]/g,'_').replace(/^\d/,'_')||'CharacterGenome';
const write=(file,value,binary=false)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,binary?value:typeof value==='string'?value:`${JSON.stringify(value,null,2)}\n`)};

export function buildCharacterGenomeFromAst(ast){
  const identityParameters={},bodyParameters={},descriptors={};
  for(const [key,value] of Object.entries(ast.identity)){if(typeof value==='number'&&faceNames.has(key))identityParameters[`face.${key}`]=value;else if(typeof value==='number'&&bodyNames.has(key))bodyParameters[`body.${key}`]=value;else if(!['age','resting_expression'].includes(key))descriptors[key]=value}
  const appearance={};for(const [key,value] of Object.entries(ast.appearance)){const mapped={hair:'hair_family',costume:'costume_family',palette:'palette_family',emblem:'emblem_slot'}[key]??key;appearance[mapped]=key==='eye_color'?(eyeColors[value]??value):value}
  const lockIdentity=ast.continuity.lock.includes('identity'),allow=[...new Set(ast.continuity.allow)],deny=[...new Set(ast.continuity.deny)];
  return createCharacterGenome({name:ast.name,seed:ast.seed??`rcl-character:${ast.name}`,topology_family:ast.topology_family??'young-male-slim',age_band:ast.identity.age??'young-adult',identity_parameters:identityParameters,body_parameters:bodyParameters,identity_genome:{resting_expression:ast.identity.resting_expression??'calm',descriptors},appearance,expression_profile:ast.profiles.expression_profile,voice_binding:{voice_identity:ast.profiles.voice,viseme_profile:ast.profiles.viseme_profile},motion_profile:ast.profiles.motion_profile,continuity_contract:{lock_identity:lockIdentity,allow,deny,max_identity_drift:.035,cross_cut:true,cross_episode:true}});
}

export function buildCharacterShadowRcl(genome){const name=safe(`CharacterGenome_${genome.identity_genome.name}`),fields=[`facet character.id : Text = ${JSON.stringify(genome.character_id)}`,`facet character.genome_id : Text = ${JSON.stringify(genome.genome_id)}`,`facet character.genome_root : Text = ${JSON.stringify(genome.genome_root)}`,`facet character.identity_root : Text = ${JSON.stringify(genome.identity_root)}`,`facet character.topology : Text = ${JSON.stringify(genome.topology_family)}`,`facet character.face_parameter_count : Number = ${Object.keys(genome.identity_genome.identity_parameters).length}`,`facet character.expression_count : Number = ${genome.expression_profile.morphs.length}`,`facet character.viseme_count : Number = ${genome.voice_binding.visemes.length}`];return{source:`reality ${name} {\n  ${fields.join('\n  ')}\n}`,name,fields:fields.length}}

export function compileCharacterGenomeSource(source){
  const ast=parseCharacterGenomeSource(source),genome=buildCharacterGenomeFromAst(ast),validation=validateCharacterGenome(genome);if(!validation.valid)throw Object.assign(new Error(`CHARACTER_GENOME_INVALID:${validation.errors.join(',')}`),{code:'CHARACTER_GENOME_INVALID',details:validation});const shadow=buildCharacterShadowRcl(genome),rclProgram=compileReality(shadow.source),bytecode=compileRealityToBytecode(shadow.source),request=seal({format:'ragf.character-phenotype-request.v0.1',provider_id:'ragf.character-genome-reference-provider',capability:'character-phenotype.compile',genome_root:genome.genome_root,identity_root:genome.identity_root,outputs:['character-glb','three-lods','identity-morphs','expressions','visemes','native-2d','2.5d','3d-assisted-2d'],commit:false,request_root:''},'request_root');
  const result={format:'rcl.character-genome-compiled-program.v0.1',version:RCL_CHARACTER_GENOME_DIALECT_VERSION,dialect:'rcl-character-genome-compatibility-bridge',rcl_language_version:RCL_LANGUAGE_VERSION,source_root:ast.sourceRoot,genome,ragf_request:request,source_map:clone(ast.sourceMap),shadow_rcl:shadow.source,shadow_program_root:rclProgram.programRoot,bytecode:Buffer.from(bytecode),bytecode_length:bytecode.length,bytecode_root:rootHash([...bytecode]),diagnostics:[],compiler:{kind:'rcl-character-genome-bridge',identity_authority:'RNCS Character Genome',provider_commit_authority:false}};const rootInput={...result,bytecode:result.bytecode.toString('base64')};return{...result,compiled_root:rootHash(rootInput)};
}

export function tryCompileCharacterGenomeSource(source){
  try{return{ok:true,...compileCharacterGenomeSource(source)}}
  catch(error){return{ok:false,diagnostics:[{code:error.code??'CHARACTER_COMPILE_FAILURE',message:error.message,location:error.location??null,details:error.details??{}}]}}
}

export function compileCharacterSourceToAssets(source,{outDir,provider='reference'}={}){
  if(!outDir)throw Object.assign(new Error('CHARACTER_OUTPUT_DIRECTORY_REQUIRED'),{code:'CHARACTER_OUTPUT_DIRECTORY_REQUIRED'});const compiled=compileCharacterGenomeSource(source);write(path.join(outDir,'source.character.rcl'),source);write(path.join(outDir,'genome.json'),compiled.genome);write(path.join(outDir,'ragf-request.json'),compiled.ragf_request);write(path.join(outDir,'source-map.json'),compiled.source_map);write(path.join(outDir,'shadow.rcl'),compiled.shadow_rcl);write(path.join(outDir,'program.rbc'),compiled.bytecode,true);const generated=compileCharacterPhenotype(compiled.genome,{outDir,provider});const report=seal({format:'rncs.character-compile-report.v0.1',source_root:compiled.source_root,compiled_root:compiled.compiled_root,genome_root:compiled.genome.genome_root,identity_root:compiled.genome.identity_root,asset_root:generated.family.asset_root,family_root:generated.family.family_root,provider_receipt_root:generated.family.provider_receipt.receipt_root,validation:generated.validation.valid,commit:false,output:path.resolve(outDir),report_root:''},'report_root');write(path.join(outDir,'compile-report.json'),report);return{compiled,generated,report};
}

export function commitCharacterAsset({workspaceDir,libraryDir,approved=false}={}){
  if(!approved)throw Object.assign(new Error('CHARACTER_COMMIT_APPROVAL_REQUIRED'),{code:'CHARACTER_COMMIT_APPROVAL_REQUIRED'});const verification=verifyCharacterAssetDirectory(workspaceDir);if(!verification.ok)throw Object.assign(new Error(`CHARACTER_COMMIT_VERIFICATION_FAILED:${verification.errors.join(',')}`),{code:'CHARACTER_COMMIT_VERIFICATION_FAILED',details:verification});const family=JSON.parse(fs.readFileSync(path.join(workspaceDir,'family.json'),'utf8')),quality=JSON.parse(fs.readFileSync(path.join(workspaceDir,'quality-report.json'),'utf8'));if(!quality.valid)throw Object.assign(new Error('CHARACTER_COMMIT_QUALITY_FAILED'),{code:'CHARACTER_COMMIT_QUALITY_FAILED'});const base=path.resolve(libraryDir),target=path.resolve(base,safe(family.character_id),family.asset_root);if(!target.startsWith(base))throw Object.assign(new Error('CHARACTER_COMMIT_PATH_INVALID'),{code:'CHARACTER_COMMIT_PATH_INVALID'});fs.mkdirSync(path.dirname(target),{recursive:true});fs.cpSync(workspaceDir,target,{recursive:true});const receipt=seal({format:'rncs.character-authority-commit.v0.1',status:'committed',authority:'RNCS Character Genome Authority',character_id:family.character_id,genome_root:family.genome_root,identity_root:family.identity_root,asset_root:family.asset_root,family_root:family.family_root,quality_report_root:quality.report_root,verification_report_root:verification.report_root,target,receipt_root:''},'receipt_root');write(path.join(target,'authority-commit-receipt.json'),receipt);return receipt;
}
