export const CIVILIZATION_PHASES_V2 = [
  "PRIMAL_SEED","TRIBAL_NETWORK","CITY_STATE","GUILD_SOCIETY","RULED_CIVILIZATION",
  "EXPANSION","FRACTURED_ERA","ARCHIVE_CIVILIZATION","STAR_RELIC","TERMINAL_CIVILIZATION","RESEED_CIVILIZATION",
] as const;
export type CivilizationPhaseV2 = typeof CIVILIZATION_PHASES_V2[number];

export const CIVILIZATION_PHASE_V2_LABELS: Record<CivilizationPhaseV2, string> = {
  PRIMAL_SEED: "原初种子", TRIBAL_NETWORK: "部落网络", CITY_STATE: "城邦",
  GUILD_SOCIETY: "公会社会", RULED_CIVILIZATION: "规则文明", EXPANSION: "扩张文明",
  FRACTURED_ERA: "裂变时代", ARCHIVE_CIVILIZATION: "归档文明", STAR_RELIC: "星海遗迹",
  TERMINAL_CIVILIZATION: "终局文明", RESEED_CIVILIZATION: "再种子文明",
};
