export const TECHNOLOGY_TYPES = [
  "AGRICULTURE","WRITING","ARCHIVE_SYSTEM","NAVIGATION","METALLURGY",
  "MARKET_SYSTEM","GOVERNANCE_SYSTEM","ENERGY_SYSTEM","COMMUNICATION_NETWORK",
  "WORLD_ENGINEERING","SEQUENCE_COMPILATION","TERMINAL_INFRASTRUCTURE",
  "STAR_ARCHIVE_TECH","RESEED_PROTOCOL",
] as const;
export type TechnologyType = typeof TECHNOLOGY_TYPES[number];

export const TECHNOLOGY_LABELS: Record<TechnologyType, string> = {
  AGRICULTURE: "农耕", WRITING: "文字", ARCHIVE_SYSTEM: "归档系统",
  NAVIGATION: "航行", METALLURGY: "冶金", MARKET_SYSTEM: "市场系统",
  GOVERNANCE_SYSTEM: "治理系统", ENERGY_SYSTEM: "能源系统",
  COMMUNICATION_NETWORK: "通讯网络", WORLD_ENGINEERING: "世界工程",
  SEQUENCE_COMPILATION: "数列编译", TERMINAL_INFRASTRUCTURE: "终端基建",
  STAR_ARCHIVE_TECH: "星海归档技术", RESEED_PROTOCOL: "再种子协议",
};
