import path from 'node:path';
import {
  assertArray, assertObject, assertText, atomicDirectory, artifactManifest,
  escapeHtml, identifier, receipt, slugify, stableJson, writeJson, writeText,
} from './common.mjs';
import { runAuthorizedProvider } from './rcl-driver.mjs';

export const APP_FORGE_VERSION = '0.1.0-alpha.1';

const FIELD_TYPES = new Set(['text', 'number', 'boolean', 'date', 'textarea']);

export function validateAppBlueprint(input) {
  const blueprint = structuredClone(assertObject(input, 'app blueprint'));
  blueprint.project = assertObject(blueprint.project, 'project');
  blueprint.project.name = assertText(blueprint.project.name, 'project.name', { max: 120 });
  blueprint.project.title = assertText(blueprint.project.title ?? blueprint.project.name, 'project.title', { max: 160 });
  blueprint.project.description = String(blueprint.project.description ?? 'Generated by RCL App Forge').slice(0, 800);
  blueprint.project.locale = String(blueprint.project.locale ?? 'zh-CN');
  blueprint.project.accent = String(blueprint.project.accent ?? '#6750A4');

  blueprint.entities = assertArray(blueprint.entities, 'entities', { min: 1 }).map((entity, entityIndex) => {
    const item = assertObject(entity, `entities[${entityIndex}]`);
    item.name = assertText(item.name, `entities[${entityIndex}].name`, { max: 80 });
    item.label = String(item.label ?? item.name).slice(0, 100);
    item.fields = assertArray(item.fields, `${item.name}.fields`, { min: 1 }).map((field, fieldIndex) => {
      const value = assertObject(field, `${item.name}.fields[${fieldIndex}]`);
      value.name = assertText(value.name, `${item.name}.fields[${fieldIndex}].name`, { max: 80 });
      value.label = String(value.label ?? value.name).slice(0, 100);
      value.type = FIELD_TYPES.has(value.type) ? value.type : 'text';
      value.required = Boolean(value.required);
      value.placeholder = String(value.placeholder ?? '').slice(0, 180);
      return value;
    });
    return item;
  });

  blueprint.seedData ??= {};
  for (const entity of blueprint.entities) {
    const rows = blueprint.seedData[entity.name];
    blueprint.seedData[entity.name] = Array.isArray(rows) ? rows.slice(0, 200) : [];
  }
  blueprint.features = {
    offline: blueprint.features?.offline !== false,
    localStorage: blueprint.features?.localStorage !== false,
    auditTrail: blueprint.features?.auditTrail !== false,
  };
  return blueprint;
}

function generatePolicyRcl(blueprint) {
  const reality = identifier(`${blueprint.project.name}_Policy`, 'GeneratedAppPolicy');
  return `# Generated policy projection. The running browser app remains a projection; RCL is the authority model.
reality ${reality} {
  facet app.records : Number = 0
  facet app.audit_events : Number = 0

  subject operator {
    warrant data.create on workspace
    warrant data.update on workspace
    warrant data.delete on workspace
  }

  emergence record_create {
    cause operator
    when true
    needs data.create on workspace
    alter app.records <- app.records + 1
    alter app.audit_events <- app.audit_events + 1
    preserve app.records >= 0
    witness "app:create"
  }

  emergence record_delete {
    cause operator
    when app.records > 0
    needs data.delete on workspace
    alter app.records <- app.records - 1
    alter app.audit_events <- app.audit_events + 1
    preserve app.records >= 0
    witness "app:delete"
  }
}`;
}

function generateHtml(blueprint) {
  const title = escapeHtml(blueprint.project.title);
  const description = escapeHtml(blueprint.project.description);
  return `<!doctype html>
<html lang="${escapeHtml(blueprint.project.locale)}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="${escapeHtml(blueprint.project.accent)}">
  <meta name="description" content="${description}">
  <link rel="manifest" href="manifest.webmanifest">
  <link rel="stylesheet" href="styles.css">
  <title>${title}</title>
</head>
<body>
  <div class="app-shell">
    <header class="topbar">
      <div>
        <p class="eyebrow">RCL APP FORGE</p>
        <h1>${title}</h1>
        <p class="subtitle">${description}</p>
      </div>
      <button id="exportButton" class="secondary">导出数据</button>
    </header>
    <nav id="entityNav" class="entity-nav" aria-label="数据对象"></nav>
    <main id="app" aria-live="polite"></main>
    <footer>Reality blueprint → authorized build → runnable projection</footer>
  </div>
  <script id="blueprint" type="application/json">${JSON.stringify(blueprint).replaceAll('<', '\\u003c')}</script>
  <script type="module" src="app.js"></script>
</body>
</html>`;
}

function generateCss(blueprint) {
  return `:root{--accent:${blueprint.project.accent};--bg:#f7f5fa;--surface:#fff;--text:#1d1b20;--muted:#625b71;--border:#ddd7e5;--danger:#b3261e;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--text);background:var(--bg)}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at top right,color-mix(in srgb,var(--accent) 12%,transparent),transparent 28rem),var(--bg)}button,input,textarea{font:inherit}.app-shell{width:min(1120px,100%);margin:auto;padding:clamp(16px,4vw,42px)}.topbar{display:flex;gap:24px;justify-content:space-between;align-items:flex-start;margin-bottom:22px}.eyebrow{font-size:.72rem;letter-spacing:.18em;font-weight:800;color:var(--accent);margin:0 0 8px}.topbar h1{font-size:clamp(1.8rem,5vw,3.7rem);line-height:1;margin:0}.subtitle{color:var(--muted);max-width:62ch}.entity-nav{display:flex;gap:10px;overflow:auto;padding:4px 0 18px}.entity-nav button,.secondary{border:1px solid var(--border);background:var(--surface);border-radius:999px;padding:10px 16px;cursor:pointer}.entity-nav button.active{background:var(--accent);color:white;border-color:var(--accent)}.workspace{display:grid;grid-template-columns:minmax(260px,360px) 1fr;gap:20px}.card{background:color-mix(in srgb,var(--surface) 96%,var(--accent));border:1px solid var(--border);border-radius:24px;padding:20px;box-shadow:0 18px 50px rgba(50,35,65,.08)}.card h2{margin-top:0}.field{display:grid;gap:7px;margin-bottom:14px}.field label{font-weight:700;font-size:.9rem}.field input,.field textarea{width:100%;padding:12px 14px;border:1px solid var(--border);border-radius:14px;background:white}.field textarea{min-height:100px;resize:vertical}.primary{border:0;background:var(--accent);color:white;border-radius:14px;padding:12px 16px;font-weight:800;cursor:pointer;width:100%}.record-list{display:grid;gap:12px}.record{display:grid;grid-template-columns:1fr auto;gap:16px;padding:16px;border:1px solid var(--border);border-radius:18px;background:white}.record dl{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:8px;margin:0}.record dt{font-size:.72rem;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.record dd{margin:3px 0 0;overflow-wrap:anywhere}.record-actions{display:flex;gap:8px;align-items:start}.record-actions button{border:0;border-radius:10px;padding:8px 10px;cursor:pointer}.danger{background:#ffdad6;color:var(--danger)}.empty{padding:40px;text-align:center;color:var(--muted);border:1px dashed var(--border);border-radius:18px}.audit{margin-top:18px;color:var(--muted);font-size:.8rem}footer{text-align:center;color:var(--muted);padding:26px 0 4px;font-size:.82rem}@media(max-width:760px){.topbar{display:block}.topbar .secondary{margin-top:10px}.workspace{grid-template-columns:1fr}.record{grid-template-columns:1fr}.record-actions{justify-content:flex-end}}`;
}

function generateClientJs() {
  return `const blueprint=JSON.parse(document.querySelector('#blueprint').textContent);const storageKey='rcl-app-forge:'+blueprint.project.name;const initial=structuredClone(blueprint.seedData||{});let db=load();let active=blueprint.entities[0].name;function load(){try{return JSON.parse(localStorage.getItem(storageKey))||initial}catch{return initial}}function save(){localStorage.setItem(storageKey,JSON.stringify(db))}function audit(action,entity,id){if(!blueprint.features.auditTrail)return;const key='__audit';db[key]??=[];db[key].push({at:new Date().toISOString(),action,entity,id});db[key]=db[key].slice(-100);save()}function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}function renderNav(){const nav=document.querySelector('#entityNav');nav.innerHTML='';for(const entity of blueprint.entities){const b=document.createElement('button');b.textContent=entity.label;b.className=entity.name===active?'active':'';b.onclick=()=>{active=entity.name;render()};nav.append(b)}}function fieldInput(field){if(field.type==='textarea')return '<textarea name="'+field.name+'" placeholder="'+escapeHtml(field.placeholder)+'" '+(field.required?'required':'')+'></textarea>';if(field.type==='boolean')return '<input name="'+field.name+'" type="checkbox">';return '<input name="'+field.name+'" type="'+(field.type==='number'?'number':field.type==='date'?'date':'text')+'" placeholder="'+escapeHtml(field.placeholder)+'" '+(field.required?'required':'')+'>'}function render(){renderNav();const entity=blueprint.entities.find(item=>item.name===active);db[entity.name]??=[];const rows=db[entity.name];const fields=entity.fields.map(field=>'<div class="field"><label>'+escapeHtml(field.label)+fieldInput(field)+'</label></div>').join('');const list=rows.length?rows.map(row=>'<article class="record"><dl>'+entity.fields.map(field=>'<div><dt>'+escapeHtml(field.label)+'</dt><dd>'+escapeHtml(field.type==='boolean'?(row[field.name]?'是':'否'):row[field.name])+'</dd></div>').join('')+'</dl><div class="record-actions"><button class="danger" data-delete="'+row.__id+'">删除</button></div></article>').join(''):'<div class="empty">还没有记录。左边的表单就是这套现实的第一个入口。</div>';document.querySelector('#app').innerHTML='<section class="workspace"><form id="createForm" class="card"><h2>新增 '+escapeHtml(entity.label)+'</h2>'+fields+'<button class="primary" type="submit">提交现实变化</button></form><section class="card"><h2>'+escapeHtml(entity.label)+' · '+rows.length+'</h2><div class="record-list">'+list+'</div><p class="audit">本地审计事件：'+((db.__audit||[]).length)+'</p></section></section>';document.querySelector('#createForm').onsubmit=event=>{event.preventDefault();const form=new FormData(event.currentTarget);const row={__id:crypto.randomUUID()};for(const field of entity.fields){const input=event.currentTarget.elements[field.name];row[field.name]=field.type==='boolean'?input.checked:field.type==='number'?Number(form.get(field.name)):form.get(field.name)}db[entity.name].unshift(row);audit('create',entity.name,row.__id);save();render()};document.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>{const id=button.dataset.delete;db[entity.name]=db[entity.name].filter(row=>row.__id!==id);audit('delete',entity.name,id);save();render()})}document.querySelector('#exportButton').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=blueprint.project.name+'-data.json';a.click();URL.revokeObjectURL(a.href)};if('serviceWorker'in navigator&&blueprint.features.offline)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();`;
}

function generateServiceWorker() {
  return `const CACHE='rcl-app-forge-v1';const ASSETS=['./','./index.html','./styles.css','./app.js','./manifest.webmanifest'];self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));self.addEventListener('fetch',event=>event.respondWith(caches.match(event.request).then(hit=>hit||fetch(event.request))));`;
}

async function writeAppArtifacts(blueprint, root) {
  writeText(root, 'index.html', generateHtml(blueprint));
  writeText(root, 'styles.css', generateCss(blueprint));
  writeText(root, 'app.js', generateClientJs());
  writeText(root, 'sw.js', generateServiceWorker());
  writeJson(root, 'manifest.webmanifest', {
    name: blueprint.project.title,
    short_name: blueprint.project.name.slice(0, 24),
    start_url: './',
    display: 'standalone',
    background_color: '#f7f5fa',
    theme_color: blueprint.project.accent,
  });
  writeJson(root, 'blueprint.json', blueprint);
  writeJson(root, 'schema.json', {
    format: 'rcl.app-forge.schema.v0.1',
    entities: blueprint.entities.map(entity => ({
      name: entity.name,
      fields: entity.fields.map(field => ({ name: field.name, type: field.type, required: field.required })),
    })),
  });
  writeText(root, 'policy.rcl', generatePolicyRcl(blueprint));
}

export async function forgeApp(input, outputDir) {
  const blueprint = validateAppBlueprint(input);
  let finalReceipt;
  await atomicDirectory(outputDir, async temp => {
    let providerManifest;
    const authorized = await runAuthorizedProvider({
      realityName: `${blueprint.project.name} App Forge`,
      subject: 'app_architect',
      host: 'app_forge',
      capability: 'generate',
      warrant: 'app.generate',
      target: 'forge',
      request: blueprint,
      witness: 'rcl:app-forge:authorized-build',
      purpose: 'generate_runnable_application',
      provider: async parsed => {
        const validated = validateAppBlueprint(parsed);
        await writeAppArtifacts(validated, temp);
        providerManifest = artifactManifest(temp, {
          framework: 'RCL App Forge', version: APP_FORGE_VERSION,
          metadata: { project: validated.project.name, blueprintRoot: stableJson(validated).length },
        });
        return receipt({ framework: 'RCL App Forge', capability: 'app.generate', outputDir, manifest: providerManifest });
      },
    });
    writeText(temp, 'authority.rcl', authorized.source);
    writeJson(temp, 'rcl-run.json', authorized.result);
    const manifest = artifactManifest(temp, {
      framework: 'RCL App Forge', version: APP_FORGE_VERSION,
      metadata: {
        project: blueprint.project.name,
        runnableEntry: 'index.html',
        entityCount: blueprint.entities.length,
        executionRoot: authorized.result.stateRoot,
      },
    });
    writeJson(temp, 'manifest.json', manifest);
    finalReceipt = receipt({
      framework: 'RCL App Forge', capability: 'app.generate', outputDir,
      manifest,
      details: { entry: path.join(outputDir, 'index.html'), entities: blueprint.entities.map(item => item.name) },
    });
  });
  return finalReceipt;
}
