import { validateArtifact, componentRoots, revisionPayload, artifactPayload, rootHash as lafRootHash } from '@taowind/living-artifact-format';
import { clone, now, ICARError, rootHash } from './canonical.mjs';
const ZERO='0'.repeat(64);
function requireValid(a){const v=validateArtifact(a);if(!v.valid)throw new ICARError('LAF_INVALID',v.errors.join(','));return v;}
function resolveParent(container,path,create=false){const parts=path.split('/').filter(Boolean);if(!parts.length)throw new ICARError('LAF_OPERATION_PATH_EMPTY');let cur=container;for(const p of parts.slice(0,-1)){if(Array.isArray(cur))cur=cur[Number(p)];else{if(!(p in cur)){if(!create)throw new ICARError('LAF_OPERATION_PATH_MISSING',path);cur[p]={};}cur=cur[p];}}return[cur,parts.at(-1)];}
export function sealArtifact(artifact,{actor_subject_id,message,advance=true,clock=now}={}){const out=clone(artifact),c=out.continuity.current;const previous=/^[0-9a-f]{64}$/.test(c.revision_root??'')&&c.revision_root!==ZERO?c.revision_root:null;if(advance){c.revision=Number(c.revision??0)+1;c.parent_revision_root=previous;c.binding_status='unbound';c.committed_transition_ref=null;}out.identity.updated_at=clock();const roots=componentRoots(out);c.revision_root=lafRootHash(revisionPayload(out,roots));out.continuity.branches[c.branch]=c.revision_root;const record={revision:c.revision,revision_root:c.revision_root,parent_revision_root:c.parent_revision_root??null,branch:c.branch,actor_subject_id:String(actor_subject_id??'system'),message:String(message??'edit'),created_at:out.identity.updated_at,binding_status:c.binding_status,authoritative_generation:clone(c.authoritative_generation),...roots};out.continuity.history=(out.continuity.history??[]).filter(h=>h.revision_root!==record.revision_root);out.continuity.history.push(record);out.evidence={algorithm:'sha256-rncs-canonical-v1',...roots,revision_root:c.revision_root};out.evidence.artifact_root=lafRootHash(artifactPayload(out));requireValid(out);return out;}
export function applyOperations(artifact,operations,{actor_subject_id,message='ICAR proposed edit',clock=now}={}){requireValid(artifact);const out=clone(artifact);for(const op of operations){if(!String(op.path).startsWith('/semantics/values/'))throw new ICARError('LAF_ONLY_SEMANTIC_VALUES_ALLOWED',op.path);const[parent,key]=resolveParent(out,op.path,op.op==='set');const get=()=>Array.isArray(parent)?parent[Number(key)]:parent[key];const put=v=>{if(Array.isArray(parent))parent[Number(key)]=v;else parent[key]=v};if(op.op==='set')put(clone(op.value));else if(op.op==='append'){const v=get();if(!Array.isArray(v))throw new ICARError('LAF_APPEND_TARGET_NOT_LIST',op.path);v.push(clone(op.value));}else if(op.op==='increment'){const v=get();if(!Number.isSafeInteger(v))throw new ICARError('LAF_INCREMENT_TARGET_NOT_INT',op.path);put(v+Number(op.value??1));}else if(op.op==='toggle'){const v=get();if(typeof v!=='boolean')throw new ICARError('LAF_TOGGLE_TARGET_NOT_BOOL',op.path);put(!v);}else throw new ICARError('LAF_OPERATION_UNSUPPORTED',op.op);}return sealArtifact(out,{actor_subject_id,message,advance:true,clock});}
export function renderReport(artifact){const v=artifact.semantics.values;return `# ${artifact.identity.title} 状态报告\n\n- 状态：${v.status??'未知'}\n- 进度：${v.progress??0}%\n- 所有者：${v.owner??artifact.identity.owner_subject_id}\n\n## 摘要\n\n${v.summary??''}\n\n## 里程碑\n\n${(v.milestones??[]).map(x=>`- ${x}`).join('\n')||'- 暂无'}\n`;}
export function bindGeneration(artifact,envelope,{actor_subject_id='system',clock=now}={}){const out=clone(artifact),commit=envelope.commit;if(!['committed','projected'].includes(envelope.phase)||commit?.status!=='committed')throw new ICARError('LAF_TRANSITION_NOT_COMMITTED');const blob=JSON.stringify(envelope);if(!blob.includes(out.identity.artifact_id)&&!blob.includes(out.evidence.artifact_root))throw new ICARError('LAF_TRANSITION_DOES_NOT_REFERENCE_ARTIFACT');out.continuity.current.binding_status='bound';out.continuity.current.authoritative_generation=clone(commit.result_generation);out.continuity.current.committed_transition_ref=envelope.transition_id;return sealArtifact(out,{actor_subject_id,message:'bind authoritative generation',advance:false,clock});}
export function makePreviewOperations(plan,artifact){const context={};const operations=[];for(const step of plan.steps){const t=step.operation_template;if(!t)continue;const op=clone(t);if(t.value_from_goal)op.value=step.goal[t.value_from_goal];if(t.value_from_context==='report'){context.report=renderReport(artifact);op.value=context.report;}operations.push(op);}return{operations,context};}
export function deltaFromOperations(artifact,operations){return operations.map((op,index)=>{const path=op.path;let cur=artifact;for(const p of path.split('/').filter(Boolean))cur=cur?.[p];return{operation_id:`operation:${index+1}`,op:op.op,target:artifact.identity.artifact_id,path,before_root:rootHash(cur),after:clone(op.value)};});}
