import { rootHash, seal } from './canonical.mjs';
function snapshot(artifact,fields){return Object.fromEntries(fields.filter(f=>f in artifact.semantics.values).map(f=>[f,artifact.semantics.values[f]]));}
export function buildProjections({artifact,plan,execution,hosts}){
 const all=['status','progress','owner','summary','milestones','approved','generated_report']; const mobile=['status','progress','milestones','approved'];
 const desktopSemantic=snapshot(artifact,all),mobileSemantic=snapshot(artifact,mobile); const common=Object.keys(mobileSemantic); const equivalent=common.every(k=>rootHash(desktopSemantic[k])===rootHash(mobileSemantic[k]));
 const desktop=seal({format:'icar.projection.v0.5',projection_id:'projection:icar:desktop',observer_id:'observer:desktop',modality:'visual',target_host:hosts[0]?.identity?.id??'desktop',semantic:desktopSemantic,plan_steps:plan.steps.map(s=>({step_id:s.step_id,capability_id:s.capability_id,status:execution.step_receipts.find(r=>r.step_id===s.step_id)?.status??'planned'}))},'projection_root');
 const mobileView=seal({format:'icar.projection.v0.5',projection_id:'projection:icar:mobile',observer_id:'observer:mobile',modality:'visual',target_host:hosts[1]?.identity?.id??'mobile',semantic:mobileSemantic,plan_steps:plan.steps.map(s=>({step_id:s.step_id,capability_id:s.capability_id,status:execution.step_receipts.find(r=>r.step_id===s.step_id)?.status??'planned'}))},'projection_root');
 return seal({format:'icar.projection-bundle.v0.5',semantic_equivalence:{equivalent,shared_fields:common},desktop,mobile:mobileView},'bundle_root');
}
export function renderHtml(result,target='desktop'){
 const view=result.projections[target];const s=view.semantic;const rows=Object.entries(s).map(([k,v])=>`<tr><th>${esc(k)}</th><td><pre>${esc(typeof v==='string'?v:JSON.stringify(v,null,2))}</pre></td></tr>`).join('');
 const steps=view.plan_steps.map(x=>`<li><code>${esc(x.capability_id)}</code><span>${esc(x.status)}</span></li>`).join('');
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ICAR v0.5 ${target}</title><style>body{margin:0;background:#07111f;color:#e9f3ff;font-family:system-ui,sans-serif}.wrap{max-width:1100px;margin:auto;padding:30px}.hero,.card{background:#0d1b2e;border:1px solid #24415f;border-radius:18px;padding:22px;margin-bottom:18px}h1{margin:0 0 8px}.badge{display:inline-block;padding:5px 10px;border-radius:999px;background:#17334e;color:#5ee7ff}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #203a56;padding:12px;text-align:left;vertical-align:top}th{width:180px;color:#8ab4d8}pre{white-space:pre-wrap;margin:0}li{display:flex;justify-content:space-between;padding:10px;border-bottom:1px solid #203a56}code{color:#73f0cf}.root{word-break:break-all;color:#8ab4d8;font-family:monospace}</style></head><body><div class="wrap"><section class="hero"><span class="badge">${esc(result.envelope.phase)}</span><h1>ICAR 原生 Envelope 运行结果</h1><p>${esc(result.intent.source)}</p><div class="root">Generation ${result.envelope.commit.result_generation.generation} · ${result.envelope.commit.result_generation.generation_root}</div></section><section class="card"><h2>现实对象</h2><table>${rows}</table></section><section class="card"><h2>能力执行</h2><ol>${steps}</ol></section></div></body></html>`;
}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
