import fs from 'node:fs';import path from 'node:path';
import {compileIntent} from './intent.mjs';import {buildRegistry} from './capabilities.mjs';import {negotiateHosts,hostStateReferences,emitNotification} from './hnac.mjs';import {planIntent} from './planner.mjs';import {resolveAuthority} from './authority.mjs';import {applyOperations,makePreviewOperations,deltaFromOperations,bindGeneration,renderReport} from './laf-runtime.mjs';import {buildProjections} from './projector.mjs';import {seal,rootHash,clone,ICARError,verifySeal} from './canonical.mjs';
import {newProposal,authorize,commit as commitEnvelope,attachProjection,verify as verifyEnvelope} from '@taowind/rncs-core-contract';import {RealityStore} from '@taowind/rfe-core-sdk';import {validateArtifact} from '@taowind/living-artifact-format';
function ensureStore(storePath,realityId){if(!fs.existsSync(storePath)||!fs.existsSync(path.join(storePath,'store.json')))return RealityStore.init(storePath,{worldId:realityId,branchId:'branch:main'});return new RealityStore(storePath)}
function requirePrepared(p){if(!verifySeal(p,'preview_root'))throw new ICARError('PREVIEW_ROOT_MISMATCH');const ev=verifyEnvelope(p.envelope);if(!ev.valid)throw new ICARError('PREVIEW_ENVELOPE_INVALID',ev.errors.join(','));if(p.envelope.phase!=='authorized')throw new ICARError('PREVIEW_NOT_AUTHORIZED');}
export function prepareApplication({sourceArtifact,intentText,actor,hosts,capsule,rfeStorePath,realityId='reality:icar',providers=[],policy={},clock}){
 const av=validateArtifact(sourceArtifact);if(!av.valid)throw new ICARError('SOURCE_ARTIFACT_INVALID',av.errors.join(','));const store=ensureStore(rfeStorePath,realityId),base=store.currentGeneration();
 const intent=compileIntent(intentText);const initialNegotiation=negotiateHosts({capsule,hosts,requiredHostCapabilities:[]});const registry=buildRegistry({artifact:sourceArtifact,providers});
 const plan=planIntent({intent,registry,hostGrants:initialNegotiation.available});const hostNegotiation=negotiateHosts({capsule,hosts,requiredHostCapabilities:plan.required_host_capabilities});if(hostNegotiation.status!=='ready')throw new ICARError('HOST_NEGOTIATION_BLOCKED',hostNegotiation.unresolved.join(','));
 const authority=resolveAuthority({plan,actor,hostNegotiation,policy});const {operations,context}=makePreviewOperations(plan,sourceArtifact);const proposedArtifact=operations.length?applyOperations(sourceArtifact,operations,{actor_subject_id:actor.subject_id??actor.id,message:`ICAR preview ${intent.intent_id}`,clock}):clone(sourceArtifact);
 const provisionalDelta={operations:deltaFromOperations(sourceArtifact,operations)};
 let envelope=newProposal({transition_id:`transition:${intent.intent_root.slice(0,24)}`,reality_id:base.worldId,base_generation:base.realityRevision,base_generation_root:base.integrityHash,subject:{subject_id:actor.subject_id??actor.id,kind:actor.kind??'human',roles:[actor.role??'operator'],responsibility_boundary:actor.responsibility_boundary??'declared-operation'},intent:{intent_id:intent.intent_id,source:intent.source,goals:intent.goals,constraints:[...intent.constraints,'must-preview-before-commit']},capability_plan:{plan_id:plan.plan_id,capabilities:plan.steps.map(s=>({capability_id:s.capability_id,provider:s.provider,risk:s.risk,reversible:s.reversible})),host_bindings:hosts.map(h=>({host_id:h.identity?.id??h.host_id})),required_scopes:plan.required_scopes},inputs:[{kind:'living-artifact',id:sourceArtifact.identity.artifact_id,root:sourceArtifact.evidence.artifact_root,version:`revision:${sourceArtifact.continuity.current.revision}`,continuity_class:'object_revision'}],provisional_delta:provisionalDelta,causal_basis:{events:[{event_id:`event:intent:${intent.intent_root.slice(0,16)}`,kind:'intent-received'}],rules:[{rule_id:'preview-before-commit',expression:'phase authorized before commit'},{rule_id:'rfe-generation-only',expression:'only RFE commit advances reality generation'}],simulation_refs:[]},evidence:{nodes:[{evidence_id:'evidence:intent',kind:'subject-declaration',source:'ICAR v0.5',content_root:intent.intent_root},{evidence_id:'evidence:plan',kind:'capability-plan',source:'ICAR v0.5',content_root:plan.plan_root},{evidence_id:'evidence:artifact-preview',kind:'artifact-revision',source:'LAF v1.0',content_root:proposedArtifact.evidence.artifact_root}],edges:[{from:'evidence:intent',to:'evidence:plan',relation:'compiled-to'},{from:'evidence:plan',to:'evidence:artifact-preview',relation:'proposes'}]},host_state_refs:hostStateReferences(hosts),extensions:{icar:{version:'0.5.0',registry_root:registry.registry_root,host_negotiation_root:hostNegotiation.negotiation_root,proposed_artifact_id:proposedArtifact.identity.artifact_id,proposed_artifact_root:proposedArtifact.evidence.artifact_root,proposed_revision_root:proposedArtifact.continuity.current.revision_root}}});
 envelope=authorize(envelope,{status:authority.status==='approved'?'approved':'denied',resolver:'icar.authority.v0.2',claims:authority.scope_decisions.filter(x=>x.granted).map(x=>({scope:x.scope})),constraints:[{type:'preview-root-required'},{type:'rfe-commit-required'}],reason:authority.denied.join(',')});
 const preview=seal({format:'icar.application-preview.v0.5',status:authority.status==='approved'?'ready-for-explicit-commit':'denied',intent,registry,plan,host_negotiation:hostNegotiation,authority,source_artifact_root:sourceArtifact.evidence.artifact_root,proposed_artifact:proposedArtifact,operation_context:context,envelope,rfe_base:{generation_id:base.generationId,generation:base.realityRevision,generation_root:base.integrityHash,store_path:path.resolve(rfeStorePath)}},'preview_root');return preview;
}
function rfeOperations(store,prepared){const a=prepared.proposed_artifact,actor=prepared.authority.actor,ops=[];if(!store.getIdentity(actor.subject_id))ops.push({op:'createIdentity',identity:{id:actor.subject_id,type:'subject',metadata:{role:actor.role}}});if(!store.getIdentity(a.identity.artifact_id))ops.push({op:'createIdentity',identity:{id:a.identity.artifact_id,type:'living-artifact',metadata:{kind:a.identity.kind,title:a.identity.title}}});const values=a.semantics.values;for(const[predicate,value]of [['rncs.artifact.root',a.evidence.artifact_root],['rncs.artifact.revision_root',a.continuity.current.revision_root],['rncs.artifact.semantic_root',a.evidence.semantic_root],['rncs.artifact.progress',values.progress??null],['rncs.artifact.status',values.status??null],['icar.intent.root',prepared.intent.intent_root],['icar.plan.root',prepared.plan.plan_root]])ops.push({op:'setFact',fact:{subject:a.identity.artifact_id,predicate,value,source:'source:icar-v0.5'}});const owns=store.relations({type:'owns',from:actor.subject_id,to:a.identity.artifact_id});if(!owns.length)ops.push({op:'addRelation',relation:{type:'owns',from:actor.subject_id,to:a.identity.artifact_id,qualifiers:{source:'icar'}}});return ops;}
export function commitPreparedApplication(prepared,{rfeStorePath=null,clock}={}){requirePrepared(prepared);const storePath=rfeStorePath??prepared.rfe_base.store_path,store=new RealityStore(storePath),current=store.currentGeneration();if(current.generationId!==prepared.rfe_base.generation_id)throw new ICARError('RFE_STALE_PREVIEW',`${prepared.rfe_base.generation_id} != ${current.generationId}`);
 const tx=store.commit({actor:prepared.authority.actor.subject_id,intent:{intent_id:prepared.intent.intent_id,intent_root:prepared.intent.intent_root,source:prepared.intent.source},authority:{resolver:'icar.authority.v0.2',decision_root:prepared.envelope.authority.decision_root},operations:rfeOperations(store,prepared),baseGenerationId:current.generationId,transactionId:`transaction:${prepared.envelope.transition_id}`,evidence:[{kind:'rncs-envelope-proposal',root:prepared.envelope.proposal_root},{kind:'icar-preview',root:prepared.preview_root},{kind:'laf-artifact',root:prepared.proposed_artifact.evidence.artifact_root}]});
 let envelope=commitEnvelope(prepared.envelope,{generation:tx.generation.realityRevision,generation_root:tx.generation.integrityHash,receipt_refs:[tx.receipt.integrityHash]});let artifact=bindGeneration(prepared.proposed_artifact,envelope,{actor_subject_id:prepared.authority.actor.subject_id,clock});
 const step_receipts=[];let notification_receipt=null;for(const step of prepared.plan.steps){if(step.capability_id==='hnac.notification.emit'){notification_receipt=emitNotification(prepared.host_negotiation,{title:'意图执行完成',body:`${artifact.identity.title} 已提交到 Generation ${tx.generation.realityRevision}`,transition_id:envelope.transition_id});step_receipts.push({step_id:step.step_id,capability_id:step.capability_id,status:'completed-post-commit',receipt_root:notification_receipt.receipt_root});}else step_receipts.push({step_id:step.step_id,capability_id:step.capability_id,status:'completed'});}
 const execution=seal({format:'icar.execution.v0.5',preview_root:prepared.preview_root,transition_id:envelope.transition_id,step_receipts,notification_receipt,artifact_revision_root:artifact.continuity.current.revision_root,rfe_receipt_root:tx.receipt.integrityHash},'execution_root');const projections=buildProjections({artifact,plan:prepared.plan,execution,hosts:prepared.host_negotiation.host_ids.map(id=>({identity:{id}}))});for(const p of [projections.desktop,projections.mobile])envelope=attachProjection(envelope,{projection_id:p.projection_id,observer_id:p.observer_id,modality:p.modality,target_host:p.target_host,semantic_root:rootHash(p.semantic),reference_root:p.projection_root});
 const result=seal({format:'icar.application-result.v0.5',status:'projected',intent:prepared.intent,plan:prepared.plan,authority:prepared.authority,host_negotiation:prepared.host_negotiation,execution,artifact,projections,envelope,rfe:{store_path:path.resolve(storePath),generation:tx.generation,receipt:tx.receipt,generation_reference:store.generationReference({generationId:tx.generation.generationId})},evidence:{rncs_contract:'0.1.0',rfe_core_sdk:'0.1.0',laf:'1.0.0',hnac:'0.5.x'}},'result_root');return result;}
export function runApplication(input){const preview=prepareApplication(input);if(preview.status!=='ready-for-explicit-commit')return{preview};return{preview,result:commitPreparedApplication(preview,{rfeStorePath:input.rfeStorePath,clock:input.clock})};}
