import { evaluateAt } from '../../packages/core/src/index.js';
import { compileRealtimeWebGPUFrame, probeRealtimeWebGPU, VSRRealtimeWebGPUExecutor } from '../../packages/realtime-webgpu/src/index.js';

const captureMode=location.search.includes('capture=1');
const canvas=document.querySelector('#canvas'),mode=document.querySelector('#mode'),log=document.querySelector('#log'),fpsEl=document.querySelector('#fps');
const documentSpec={specVersion:'0.1',metadata:{id:'frost-trial-gpu',title:'Frost Trial GPU',duration:999,defaultFps:60,seed:37},canvas:{width:960,height:540,background:{type:'solid',color:'#030712'}},nodes:[
{id:'sky',type:'rect',layout:{x:0,y:0,width:960,height:540},appearance:{fill:{type:'solid',color:'#071328'}}},
{id:'moon-glow',type:'ellipse',layout:{x:690,y:58,width:180,height:180},appearance:{fill:{type:'solid',color:'#38bdf8'},opacity:.12},tags:['decorative']},
{id:'moon',type:'ellipse',layout:{x:728,y:96,width:104,height:104},appearance:{fill:{type:'solid',color:'#dbeafe'},opacity:.95}},
{id:'ridge-a',type:'path',layout:{x:0,y:0,width:960,height:540},appearance:{fill:{type:'solid',color:'#102447'}},content:{d:'M0 350 L150 210 L260 330 L395 170 L530 340 L690 215 L840 340 L960 245 L960 540 L0 540 Z'}},
{id:'ridge-b',type:'path',layout:{x:0,y:0,width:960,height:540},appearance:{fill:{type:'solid',color:'#0a1832'}},content:{d:'M0 410 L190 285 L320 410 L500 250 L650 420 L820 290 L960 410 L960 540 L0 540 Z'}},
{id:'ground',type:'rect',layout:{x:0,y:418,width:960,height:122},appearance:{fill:{type:'solid',color:'#0b1730'}}},
{id:'portal-glow',type:'ellipse',layout:{x:756,y:319,width:108,height:142},appearance:{fill:{type:'solid',color:'#22d3ee'},opacity:.18},tags:['decorative']},
{id:'portal',type:'rect',layout:{x:786,y:344,width:48,height:106},appearance:{fill:{type:'solid',color:'#67e8f9'},opacity:.68},content:{cornerRadius:22}},
{id:'hero-shadow',type:'ellipse',layout:{x:280,y:435,width:90,height:18},appearance:{fill:{type:'solid',color:'#000000'},opacity:.55}},
{id:'hero-body',type:'rect',layout:{x:304,y:338,width:42,height:102},appearance:{fill:{type:'solid',color:'#2563eb'}},content:{cornerRadius:16},tags:['hero']},
{id:'hero-head',type:'ellipse',layout:{x:307,y:302,width:38,height:38},appearance:{fill:{type:'solid',color:'#dbeafe'}},tags:['hero']},
{id:'hero-blade',type:'line',layout:{x:0,y:0,width:960,height:540},appearance:{stroke:{type:'solid',color:'#e0f2fe'},strokeWidth:7},content:{x1:346,y1:350,x2:410,y2:292},tags:['hero']},
{id:'guard-shadow',type:'ellipse',layout:{x:548,y:435,width:96,height:18},appearance:{fill:{type:'solid',color:'#000000'},opacity:.55}},
{id:'guard-body',type:'rect',layout:{x:574,y:334,width:45,height:106},appearance:{fill:{type:'solid',color:'#7c3aed'}},content:{cornerRadius:10}},
{id:'guard-head',type:'ellipse',layout:{x:577,y:298,width:39,height:39},appearance:{fill:{type:'solid',color:'#f5d0fe'}}},
...Array.from({length:48},(_,i)=>({id:`particle-${i}`,type:'rect',layout:{x:90+(i*73)%790,y:70+(i*47)%350,width:2+(i%3),height:2+(i%3)},appearance:{fill:{type:'solid',color:i%3===0?'#ffffff':i%3===1?'#7dd3fc':'#c4b5fd'},opacity:.8},tags:['particle','decorative']}))
]};
const config={quality:'quality',observer:{id:'player:local',purpose:'player'},device:{class:'desktop',gpuTier:2},materials:[{id:'material:hero',baseColor:'#2563eb',emissive:'#38bdf8',emissiveStrength:.25,receivesLight:true,castsShadow:true,blend:'alpha'}],bindings:[{materialId:'material:hero',tags:['hero']}],lights:[{id:'ambient',kind:'ambient',color:'#bcd7ff',intensity:.16},{id:'moon',kind:'point',color:'#7dd3fc',intensity:2.1,x:780,y:150,radius:430,castsShadow:true},{id:'portal',kind:'point',color:'#22d3ee',intensity:2.5,x:810,y:390,radius:240},{id:'rim',kind:'point',color:'#c084fc',intensity:1.8,x:580,y:350,radius:260}],post:{bloom:.72,vignette:.18,exposure:.15}};
const state=evaluateAt({document:documentSpec,time:0}).displayState,plan=compileRealtimeWebGPUFrame(state,config);document.querySelector('#draws').textContent=String(plan.stats.estimatedDrawCalls);document.querySelector('#vertices').textContent=String(plan.stats.vertices);document.querySelector('#lights').textContent=String(plan.stats.lights);document.querySelector('#particles').textContent=String(plan.stats.particleSeeds);document.querySelector('#root').textContent=`FRAME ROOT ${plan.framePlanRoot.slice(0,14)}…`;document.querySelector('#passes').innerHTML=plan.passes.filter(p=>p.enabled).map(p=>`<span class="pass">${p.id}</span>`).join('');
let frames=0,lastFps=performance.now();function updateFps(){frames++;const t=performance.now();if(t-lastFps>600){fpsEl.textContent=`${Math.round(frames*1000/(t-lastFps))} FPS`;frames=0;lastFps=t;}}
function fallback(reason){mode.textContent='Canvas 2D 降级';mode.classList.add('warn');const ctx=canvas.getContext('2d'),snow=plan.particleSeeds.map((p,i)=>({x:p.x,y:p.y,vx:(i%5-2)*.08,vy:.25+(i%7)*.04,size:p.size,color:`rgba(${Math.round(p.color[0]*255)},${Math.round(p.color[1]*255)},${Math.round(p.color[2]*255)},.8)`}));function draw(){const g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,'#071328');g.addColorStop(1,'#020617');ctx.fillStyle=g;ctx.fillRect(0,0,960,540);ctx.fillStyle='#102447';ctx.beginPath();ctx.moveTo(0,350);ctx.lineTo(150,210);ctx.lineTo(260,330);ctx.lineTo(395,170);ctx.lineTo(530,340);ctx.lineTo(690,215);ctx.lineTo(840,340);ctx.lineTo(960,245);ctx.lineTo(960,540);ctx.lineTo(0,540);ctx.fill();ctx.fillStyle='#0b1730';ctx.fillRect(0,418,960,122);ctx.shadowBlur=42;ctx.shadowColor='#22d3ee';ctx.fillStyle='#67e8f9';ctx.fillRect(786,344,48,106);ctx.shadowBlur=0;ctx.fillStyle='#2563eb';ctx.roundRect(304,338,42,102,16);ctx.fill();ctx.fillStyle='#dbeafe';ctx.beginPath();ctx.arc(326,321,19,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#e0f2fe';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(346,350);ctx.lineTo(410,292);ctx.stroke();ctx.fillStyle='#7c3aed';ctx.roundRect(574,334,45,106,10);ctx.fill();ctx.fillStyle='#f5d0fe';ctx.beginPath();ctx.arc(596,318,20,0,Math.PI*2);ctx.fill();for(const p of snow){p.x+=p.vx;p.y+=p.vy;if(p.y>520){p.y=20;p.x=(p.x*1.37)%930;}ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);}updateFps();if(!captureMode)requestAnimationFrame(draw)}draw();log.innerHTML=`<span class="warn">WebGPU 未执行</span>\n${reason}\n\n已显式切换 Canvas 2D，\n没有把降级路径冒充 GPU 帧。`;}
(async()=>{const capability=probeRealtimeWebGPU();if(!capability.available){fallback(capability.reason??'navigator.gpu unavailable');return;}try{const executor=await VSRRealtimeWebGPUExecutor.create(canvas);mode.textContent='WebGPU 实时执行';mode.classList.add('ok');let start=performance.now(),lastReceipt;async function frame(){const time=(performance.now()-start)/1000;lastReceipt=await executor.render(plan,time);updateFps();log.innerHTML=`<span class="ok">GPU frame submitted</span>\nframe ${lastReceipt.frameIndex}\ncompute ${lastReceipt.computePasses}\ndraw ${lastReceipt.drawCalls}\ncache pipelines ${executor.cacheStats().pipelinesCreated}`;if(!captureMode)requestAnimationFrame(frame)}requestAnimationFrame(frame);}catch(error){fallback(error instanceof Error?error.message:String(error));}})();
