import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import {
  Q,
  ExperienceFabricWorld,
  experienceSnapshotToCausalDelta,
  replayExperience,
  validateExperienceConfig,
  type ExperienceFabricConfig,
  type ExperienceInputEvent
} from '../packages/experience-fabric/src/index.js';
import { renderExperienceAudio } from '../packages/experience-fabric-audio/src/index.js';
import { ExperienceFabricVSRBridge, createExperienceObserverProfile } from '../packages/experience-fabric-vsr/src/index.js';

let passed = 0;
function test(name: string, fn: () => void): void { try { fn(); passed++; console.log(`PASS ${name}`); } catch (error) { console.error(`FAIL ${name}`); throw error; } }
function config(extra: Partial<ExperienceFabricConfig> = {}): ExperienceFabricConfig {
  return {
    format: 'rsr.experience-fabric.v0.4', experienceId: 'test-experience', tickHz: 30, seed: 42,
    clips: [{ id: 'idle', durationTicks: 10, loop: true, tracks: [{ target: 'hero.x', keyframes: [{ tick: 0, value: 0 }, { tick: 10, value: 100 }] }], markers: [{ id: 'mid', tick: 5, eventType: 'marker.mid' }] }, { id: 'attack', durationTicks: 8, tracks: [{ target: 'hero.x', keyframes: [{ tick: 0, value: 0 }, { tick: 4, value: 200, interpolation: 'ease-out' }, { tick: 8, value: 0 }] }], markers: [{ id: 'hit', tick: 4, eventType: 'attack.hit' }] }],
    animators: [{ id: 'hero', parameters: { attack: false }, layers: [{ id: 'base', initialState: 'idle', states: [{ id: 'idle', clipId: 'idle' }, { id: 'attack', clipId: 'attack' }], transitions: [{ id: 'to-attack', from: 'idle', to: 'attack', durationTicks: 1, conditions: [{ parameter: 'attack', op: 'trigger' }] }, { id: 'to-idle', from: 'attack', to: 'idle', durationTicks: 1, exitTimeQ: 900_000 }] }] }],
    audioBuses: [{ id: 'master' }, { id: 'sfx', parentId: 'master', gainQ: Q }],
    audioCues: [{ id: 'hit', voices: [{ id: 'tone', source: { type: 'oscillator', waveform: 'sine', frequencyHz: 440 }, durationMs: 100, busId: 'sfx' }] }],
    effects: [{ id: 'sparks', durationTicks: 10, emitters: [{ id: 'e', bursts: [{ tick: 0, count: 4 }], maxParticles: 10, lifetimeTicks: { min: 4, max: 4 }, spawn: { type: 'point' }, speed: { min: 30, max: 30 }, angleTurnsQ: { min: 0, max: 0 }, gravity: { x: 0, y: 30 }, sizeCurve: [{ tQ: 0, value: Q }, { tQ: Q, value: 0 }], opacityCurve: [{ tQ: 0, value: Q }, { tQ: Q, value: 0 }], colorCurve: [{ tQ: 0, color: { r: 255, g: 100, b: 0, a: 255 } }, { tQ: Q, color: { r: 0, g: 0, b: 0, a: 0 } }] }], screenEffects: [{ type: 'shake', durationTicks: 4, intensityQ: Q }] }],
    bindings: [{ id: 'request', eventType: 'attack.request', actions: [{ type: 'animation-trigger', animatorId: 'hero', parameter: 'attack' }] }, { id: 'hit', eventType: 'attack.hit', actions: [{ type: 'audio-cue', cueId: 'hit' }, { type: 'effect', effectId: 'sparks' }] }],
    ...extra
  };
}

test('config validation accepts valid graph', () => assert.deepEqual(validateExperienceConfig(config()), []));
test('config validation rejects missing clip', () => { const c = config(); c.animators![0]!.layers[0]!.states[0]!.clipId = 'missing'; assert.ok(validateExperienceConfig(c).some(e => e.includes('Missing clip'))); });
test('linear keyframe sampling advances property', () => { const w = new ExperienceFabricWorld(config()); w.run(3); assert.ok(w.snapshot().properties['hero.x']! > 0); });
test('looping clip wraps local animation time', () => { const w = new ExperienceFabricWorld(config()); w.run(12); const x = w.snapshot().properties['hero.x']!; assert.ok(x >= 0 && x <= 40); });
test('animation trigger starts transition', () => { const w = new ExperienceFabricWorld(config()); w.step([{ id: 'a', tick: 0, type: 'attack.request' }]); assert.ok(w.snapshot().layerStates[0]!.transition || w.snapshot().layerStates[0]!.currentState === 'attack'); });
test('transition completes into target state', () => { const w = new ExperienceFabricWorld(config()); w.step([{ id: 'a', tick: 0, type: 'attack.request' }]); w.step(); assert.equal(w.snapshot().layerStates[0]!.currentState, 'attack'); });
test('attack returns to idle after exit time', () => { const w = new ExperienceFabricWorld(config()); w.step([{ id: 'a', tick: 0, type: 'attack.request' }]); w.run(12); assert.equal(w.snapshot().layerStates[0]!.currentState, 'idle'); });
test('animation marker emits semantic event', () => { const w = new ExperienceFabricWorld(config()); w.step([{ id: 'a', tick: 0, type: 'attack.request' }]); w.run(6); assert.ok(w.snapshot().events.some(e => e.type === 'attack.hit')); });
test('marker binding schedules audio cue', () => { const w = new ExperienceFabricWorld(config()); w.step([{ id: 'a', tick: 0, type: 'attack.request' }]); w.run(6); assert.ok(w.snapshot().audioEvents.some(e => e.cueId === 'hit')); });
test('marker binding starts particle effect', () => { const w = new ExperienceFabricWorld(config()); w.step([{ id: 'a', tick: 0, type: 'attack.request' }]); w.run(6); assert.ok(w.snapshot().effectInstances.length > 0); });
test('burst emitter creates exact initial particle count', () => { const c = config({ initialEvents: [{ id: 'hit', tick: 0, type: 'attack.hit', position: { x: 5, y: 6 } }] }); const s = new ExperienceFabricWorld(c).step(); assert.equal(s.particles.length, 4); });
test('particle origin follows semantic event position', () => { const c = config({ initialEvents: [{ id: 'hit', tick: 0, type: 'attack.hit', position: { x: 50, y: 60 } }] }); const s = new ExperienceFabricWorld(c).step(); assert.equal(s.particles[0]!.position.x, 51); assert.equal(s.particles[0]!.position.y, 60); });
test('particle gravity changes velocity', () => { const c = config({ initialEvents: [{ id: 'hit', tick: 0, type: 'attack.hit' }] }); const w = new ExperienceFabricWorld(c); w.step(); const before = w.snapshot().particles[0]!.velocity.y; w.step(); assert.ok(w.snapshot().particles[0]!.velocity.y > before); });
test('particle curves reduce size over life', () => { const c = config({ initialEvents: [{ id: 'hit', tick: 0, type: 'attack.hit' }] }); const w = new ExperienceFabricWorld(c); w.step(); const before = w.snapshot().particles[0]!.sizeQ; w.step(); assert.ok(w.snapshot().particles[0]!.sizeQ < before); });
test('particles expire deterministically', () => { const c = config({ initialEvents: [{ id: 'hit', tick: 0, type: 'attack.hit' }] }); const w = new ExperienceFabricWorld(c); w.run(6); assert.equal(w.snapshot().particles.length, 0); });
test('screen effect signal appears during effect', () => { const c = config({ initialEvents: [{ id: 'hit', tick: 0, type: 'attack.hit' }] }); const w = new ExperienceFabricWorld(c); w.step(); w.step(); assert.ok(w.snapshot().screenSignals.some(s => s.type === 'shake')); });
test('effect max instances retires oldest instance', () => { const c = config(); c.effects![0]!.maxInstances = 1; const w = new ExperienceFabricWorld(c); w.emit({ id: 'x', tick: 0, type: 'attack.hit' }); w.emit({ id: 'y', tick: 0, type: 'attack.hit' }); assert.equal(w.snapshot().effectInstances.filter(i => !i.completed).length, 1); });
test('audio cooldown suppresses repeated cue', () => { const c = config(); c.audioCues![0]!.cooldownTicks = 3; const w = new ExperienceFabricWorld(c); w.emit({ id: 'x', tick: 0, type: 'attack.hit' }); w.emit({ id: 'y', tick: 0, type: 'attack.hit' }); assert.equal(w.snapshot().audioEvents.length, 1); });
test('audio renderer writes RIFF WAVE', () => { const c = config({ initialEvents: [{ id: 'hit', tick: 0, type: 'attack.hit' }] }); const s = new ExperienceFabricWorld(c).run(2); const r = renderExperienceAudio(c, s, { durationSeconds: 0.25, sampleRate: 8000 }); assert.equal(Buffer.from(r.wav.subarray(0, 4)).toString('ascii'), 'RIFF'); assert.equal(Buffer.from(r.wav.subarray(8, 12)).toString('ascii'), 'WAVE'); });
test('audio renderer is deterministic', () => { const c = config({ initialEvents: [{ id: 'hit', tick: 0, type: 'attack.hit' }] }); const s = new ExperienceFabricWorld(c).run(2); assert.equal(renderExperienceAudio(c, s, { durationSeconds: 0.2, sampleRate: 8000 }).wavHash, renderExperienceAudio(c, s, { durationSeconds: 0.2, sampleRate: 8000 }).wavHash); });
test('audio voice cap records dropped voices', () => { const c = config({ initialEvents: [{ id: 'hit', tick: 0, type: 'attack.hit' }] }); c.audioCues![0]!.voices.push({ id: 'tone2', source: { type: 'oscillator', waveform: 'square', frequencyHz: 220 }, durationMs: 100 }); const s = new ExperienceFabricWorld(c).run(2); assert.equal(renderExperienceAudio(c, s, { durationSeconds: 0.2, sampleRate: 8000, maxVoices: 1 }).diagnostics.droppedVoices, 1); });
test('sample source is accepted by audio renderer', () => { const c = config({ initialEvents: [{ id: 'sample', tick: 0, type: 'sample.play' }], audioCues: [{ id: 'sample', voices: [{ id: 'pcm', source: { type: 'sample', samples: [0, 1, 0, -1], sampleRate: 4, loop: true }, durationMs: 100 }] }], bindings: [{ id: 's', eventType: 'sample.play', actions: [{ type: 'audio-cue', cueId: 'sample' }] }] }); const s = new ExperienceFabricWorld(c).run(2); assert.ok(renderExperienceAudio(c, s, { durationSeconds: 0.2, sampleRate: 8000 }).wav.length > 44); });
test('additive animation layer preserves base properties', () => { const c = config(); c.clips!.push({ id: 'add', durationTicks: 10, loop: true, tracks: [{ target: 'hero.glow', keyframes: [{ tick: 0, value: 100 }, { tick: 10, value: 100 }] }] }); c.animators![0]!.layers.push({ id: 'fx', initialState: 'add', mode: 'additive', states: [{ id: 'add', clipId: 'add' }] }); const s = new ExperienceFabricWorld(c).step(); assert.equal(s.properties['hero.glow'], 100); assert.ok('hero.x' in s.properties); });
test('skeleton pose follows animated bone rotation', () => { const c = config({ skeletons: [{ id: 'rig', bones: [{ id: 'root', length: 10, restRotation: 0 }] }] }); c.clips![0]!.tracks.push({ target: 'skeleton:rig/bone:root.rotation', keyframes: [{ tick: 0, value: 0 }, { tick: 10, value: 250000 }] }); const s = new ExperienceFabricWorld(c).run(5); assert.ok(s.skeletonPoses[0]!.bones[0]!.endpoint.y > 0); });
test('two-bone IK moves end effector toward target', () => { const c = config({ skeletons: [{ id: 'rig', bones: [{ id: 'a', length: 50 }, { id: 'b', parentId: 'a', length: 50 }, { id: 'c', parentId: 'b', length: 0 }], ik: [{ id: 'ik', rootBone: 'a', midBone: 'b', endBone: 'c', targetXParameter: 'hero:targetX', targetYParameter: 'hero:targetY', weightParameter: 'hero:weight' }] }] }); c.animators![0]!.parameters = { attack: false, targetX: 60, targetY: 60, weight: Q }; const end = new ExperienceFabricWorld(c).step().skeletonPoses[0]!.bones.find(b => b.id === 'c')!; assert.ok(Math.hypot(end.worldPosition.x - 60, end.worldPosition.y - 60) < 40); });
test('snapshot restore converges', () => { const c = config({ initialEvents: [{ id: 'a', tick: 2, type: 'attack.request' }] }); const w = new ExperienceFabricWorld(c); w.run(7); const checkpoint = w.snapshot(); w.run(9); const final = w.snapshot(); const restored = ExperienceFabricWorld.fromSnapshot(c, checkpoint); restored.run(9); assert.equal(restored.snapshot().stateRoot, final.stateRoot); });
test('deterministic replay preserves state root', () => { const c = config({ initialEvents: [{ id: 'a', tick: 2, type: 'attack.request' }] }); assert.equal(replayExperience(c, 20).stateRoot, replayExperience(c, 20).stateRoot); });
test('different seeds produce different particle roots', () => { const event = [{ id: 'hit', tick: 0, type: 'attack.hit' }]; const ca = config({ seed: 1, initialEvents: event }); const cb = config({ seed: 2, initialEvents: event }); ca.effects![0]!.emitters![0]!.speed = { min: 10, max: 90 }; cb.effects![0]!.emitters![0]!.speed = { min: 10, max: 90 }; ca.effects![0]!.emitters![0]!.angleTurnsQ = { min: -500000, max: 500000 }; cb.effects![0]!.emitters![0]!.angleTurnsQ = { min: -500000, max: 500000 }; const a = replayExperience(ca, 2); const b = replayExperience(cb, 2); assert.notEqual(a.effectRoot, b.effectRoot); });
test('causal delta is provisional and carries evidence roots', () => { const s = new ExperienceFabricWorld(config()).step(); const d = experienceSnapshotToCausalDelta(s, 'rfe:base'); assert.equal(d.provisional, true); assert.equal(d.evidenceRoots.animation, s.animationRoot); assert.ok(d.deltaRoot.startsWith('fnv1a64:')); });
test('player and debugger projections share invariant root', () => { const c = config(); const s = new ExperienceFabricWorld(c).step(); const r = new ExperienceFabricVSRBridge(c).render(s, [createExperienceObserverProfile('player'), createExperienceObserverProfile('debugger')]); assert.equal(r.verification.ok, true); assert.equal(r.views.length, 2); });
test('player projection hides debug state node', () => { const c = config(); const s = new ExperienceFabricWorld(c).step(); const r = new ExperienceFabricVSRBridge(c).render(s, [createExperienceObserverProfile('player'), createExperienceObserverProfile('debugger')]); const player = r.views[0]!.projection.manifest; const debug = r.views[1]!.projection.manifest; assert.ok(player.hiddenNodeIds.includes('debug:state')); assert.ok(debug.shownNodeIds.includes('debug:state')); });
test('accessibility projection exposes audio captions', () => { const c = config(); const s = new ExperienceFabricWorld(c).step(); const r = new ExperienceFabricVSRBridge(c).render(s, [createExperienceObserverProfile('accessibility')]); assert.ok(r.views[0]!.projection.manifest.shownNodeIds.includes('audio:caption')); });
test('VSR bridge emits real PNG bytes', () => { const c = config(); const s = new ExperienceFabricWorld(c).step(); const png = new ExperienceFabricVSRBridge(c, { width: 320, height: 180 }).render(s, [createExperienceObserverProfile('player')]).views[0]!.png; assert.deepEqual([...png.subarray(0, 8)], [137,80,78,71,13,10,26,10]); });
test('full showcase produces animation audio and effects', () => { const c = JSON.parse(readFileSync('examples/experience-fabric/cinematic-showcase.experience.json', 'utf8')) as ExperienceFabricConfig; const s = new ExperienceFabricWorld(c).run(120); assert.ok(s.events.some(e => e.type === 'attack.impact')); assert.ok(s.audioEvents.length >= 4); assert.ok(s.animationRoot && s.audioPlanRoot && s.effectRoot); });
test('event input order is canonical by id', () => { const c = config(); const events: ExperienceInputEvent[] = [{ id: 'z', tick: 0, type: 'attack.hit' }, { id: 'a', tick: 0, type: 'attack.hit' }]; const s = new ExperienceFabricWorld(c).step(events); const inputs = s.events.filter(e => e.source === 'input').map(e => e.id); assert.deepEqual(inputs, ['a', 'z']); });

console.log(`Experience Fabric tests: ${passed}/${passed} PASS`);
