import assert from 'node:assert/strict';
import {
  Q,
  SPATIAL_EMBODIMENT_FORMAT,
  SpatialEmbodimentWorld,
  degrees,
  replaySpatialEmbodiment,
  spatialEmbodimentSnapshotToCausalDelta,
  type SpatialBodySpec,
  type SpatialCommand,
  type SpatialEmbodimentWorldConfig
} from '../packages/spatial-embodiment/src/index.js';
import { projectSpatialEmbodiment, spatialEmbodimentSnapshotToVSRScene } from '../packages/spatial-embodiment-vsr/src/index.js';
import { verifySpatialFrame } from '../packages/spatial-embodiment-vsr/src/vsr-spatial-v04.js';

let passed = 0;
function test(name: string, fn: () => void): void { try { fn(); passed++; console.log(`PASS ${name}`); } catch (error) { console.error(`FAIL ${name}`); throw error; } }
const sphere = (id: string, x: number, y: number, z: number, kind: SpatialBodySpec['kind'] = 'dynamic', radius = 500): SpatialBodySpec => ({ id, kind, position: { x, y, z }, fixtures: [{ id: `${id}:shape`, shape: { type: 'sphere', radius }, bodyZone: `${id}:body` }] });
const box = (id: string, x: number, y: number, z: number, kind: SpatialBodySpec['kind'] = 'dynamic', hx = 500, hy = 500, hz = 500): SpatialBodySpec => ({ id, kind, position: { x, y, z }, fixtures: [{ id: `${id}:shape`, shape: { type: 'box', halfExtents: { x: hx, y: hy, z: hz } }, bodyZone: `${id}:body` }] });
const capsule = (id: string, x: number, y: number, z: number, kind: SpatialBodySpec['kind'] = 'dynamic', radius = 300, halfHeight = 700): SpatialBodySpec => ({ id, kind, position: { x, y, z }, fixtures: [{ id: `${id}:shape`, shape: { type: 'capsule', radius, halfHeight }, bodyZone: `${id}:torso` }] });
function config(bodies: SpatialBodySpec[], extra: Partial<SpatialEmbodimentWorldConfig> = {}): SpatialEmbodimentWorldConfig { return { format: SPATIAL_EMBODIMENT_FORMAT, worldId: 'spatial-test', stepHz: 60, gravity: { x: 0, y: -9_810, z: 0 }, floorY: 0, velocityIterations: 6, positionIterations: 4, maxSubsteps: 16, bodies, reality: { generation: 7, realityRoot: 'rfe:test:root' }, ...extra }; }

// 1
test('sphere settles on floor and becomes grounded', () => { const s = new SpatialEmbodimentWorld(config([sphere('a', 0, 2500, 0)])).run(120); const a = s.bodies[0]!; assert.equal(a.grounded, true); assert.ok(a.position.y >= 490 && a.position.y <= 520); });
// 2
test('box floor contact preserves half extent', () => { const s = new SpatialEmbodimentWorld(config([box('a', 0, 1500, 0)])).run(100); assert.ok(s.bodies[0]!.position.y >= 490); });
// 3
test('sphere-sphere collision separates bodies', () => { const a = sphere('a', -900, 1000, 0); a.velocity = { x: 2500, y: 0, z: 0 }; const b = sphere('b', 900, 1000, 0); b.velocity = { x: -2500, y: 0, z: 0 }; const s = new SpatialEmbodimentWorld(config([a, b], { gravity: { x: 0, y: 0, z: 0 } })).run(20); assert.ok(s.bodies[0]!.position.x < s.bodies[1]!.position.x); });
// 4
test('sphere collides with static box', () => { const a = sphere('a', -1600, 1000, 0); a.velocity = { x: 5000, y: 0, z: 0 }; const w = new SpatialEmbodimentWorld(config([a, box('wall', 0, 1000, 0, 'static', 300, 1000, 1000)], { gravity: { x: 0, y: 0, z: 0 } })); let touched = false; for (let i = 0; i < 30; i++) touched ||= w.step().events.some(e => e.kind === 'contact' && e.phase === 'begin'); assert.equal(touched, true); });
// 5
test('capsule-capsule contact is detected', () => { const a = capsule('a', -250, 1200, 0); const b = capsule('b', 250, 1200, 0); const s = new SpatialEmbodimentWorld(config([a, b], { gravity: { x: 0, y: 0, z: 0 } })).step().snapshot; assert.ok(s.contacts.length >= 1); });
// 6
test('box-box overlap resolves on minimum axis', () => { const s = new SpatialEmbodimentWorld(config([box('a', 0, 1000, 0), box('b', 700, 1000, 0)], { gravity: { x: 0, y: 0, z: 0 } })).step().snapshot; assert.ok(s.contacts.length >= 1); });
// 7
test('sensor emits contact without stopping body', () => { const a = sphere('a', -1200, 1000, 0); a.velocity = { x: 5000, y: 0, z: 0 }; const sensor = box('sensor', 0, 1000, 0, 'static', 300, 1000, 1000); sensor.fixtures[0]!.sensor = true; const w = new SpatialEmbodimentWorld(config([a, sensor], { gravity: { x: 0, y: 0, z: 0 } })); let sensed = false; for (let i = 0; i < 30; i++) { const step = w.step(); if (step.events.some(e => e.kind === 'contact' && e.sensor)) sensed = true; } const s = w.snapshot(); assert.ok(sensed); assert.ok(s.bodies.find(x => x.id === 'a')!.position.x > 0); });
// 8
test('collision masks reject pairs', () => { const a = sphere('a', 0, 1000, 0); const b = sphere('b', 100, 1000, 0); a.fixtures[0]!.categoryBits = 1; a.fixtures[0]!.maskBits = 1; b.fixtures[0]!.categoryBits = 2; b.fixtures[0]!.maskBits = 2; assert.equal(new SpatialEmbodimentWorld(config([a, b], { gravity: { x: 0, y: 0, z: 0 } })).step().snapshot.contacts.length, 0); });
// 9
test('impulse changes 3D velocity', () => { const w = new SpatialEmbodimentWorld(config([sphere('a', 0, 1000, 0)], { gravity: { x: 0, y: 0, z: 0 } })); w.step([{ id: 'kick', tick: 1, type: 'apply-impulse', bodyId: 'a', impulse: { x: 1000, y: 2000, z: 3000 } }]); const v = w.snapshot().bodies[0]!.velocity; assert.ok(v.x > 0 && v.y > 0 && v.z > 0); });
// 10
test('off-center impulse creates angular velocity', () => { const w = new SpatialEmbodimentWorld(config([box('a', 0, 1000, 0)], { gravity: { x: 0, y: 0, z: 0 } })); w.step([{ id: 'spin', tick: 1, type: 'apply-impulse', bodyId: 'a', impulse: { x: 0, y: 0, z: 5000 }, worldPoint: { x: 500, y: 1000, z: 0 } }]); assert.notEqual(w.snapshot().bodies[0]!.angularVelocityDeg.y, 0); });
// 11
test('gravity integrates on Y axis', () => { const s = new SpatialEmbodimentWorld(config([sphere('a', 0, 10_000, 0)])).run(10); assert.ok(s.bodies[0]!.velocity.y < 0); });
// 12
test('linear damping reduces free velocity', () => { const a = sphere('a', 0, 10_000, 0); a.velocity = { x: 10_000, y: 0, z: 0 }; a.linearDampingQ = 600_000; const s = new SpatialEmbodimentWorld(config([a], { gravity: { x: 0, y: 0, z: 0 } })).run(60); assert.ok(s.bodies[0]!.velocity.x < 10_000); });
// 13
test('character controller accelerates planar body', () => { const body = capsule('avatar', 0, 1000, 0); const cfg = config([body], { gravity: { x: 0, y: 0, z: 0 }, characters: [{ id: 'player', bodyId: 'avatar', walkSpeed: 3000, acceleration: 12_000, jumpSpeed: 5000 }] }); const commands: SpatialCommand[] = [{ id: 'move', tick: 1, type: 'move-character', characterId: 'player', direction: { x: Q, y: 0, z: 0 } }]; const s = new SpatialEmbodimentWorld(cfg).run(30, commands); assert.ok(s.bodies[0]!.velocity.x > 1000); });
// 14
test('grounded character can jump', () => { const body = capsule('avatar', 0, 1000, 0); const cfg = config([body], { characters: [{ id: 'player', bodyId: 'avatar', walkSpeed: 3000, acceleration: 12_000, jumpSpeed: 6000 }] }); const w = new SpatialEmbodimentWorld(cfg); w.run(10); const tick = w.tick + 1; const s = w.step([{ id: 'jump', tick, type: 'jump-character', characterId: 'player' }]).snapshot; assert.ok(s.bodies[0]!.velocity.y > 0); });
// 15
test('air control is lower than grounded control', () => { const groundBody = capsule('ground', 0, 1000, 0); const airBody = capsule('air', 0, 5000, 0); const cfg = config([groundBody, airBody], { characters: [{ id: 'g', bodyId: 'ground', walkSpeed: 3000, acceleration: 12_000, jumpSpeed: 5000, airControlQ: 100_000 }, { id: 'a', bodyId: 'air', walkSpeed: 3000, acceleration: 12_000, jumpSpeed: 5000, airControlQ: 100_000 }] }); const w = new SpatialEmbodimentWorld(cfg); w.run(5); const t = w.tick + 1; const s = w.step([{ id: 'mg', tick: t, type: 'move-character', characterId: 'g', direction: { x: Q, y: 0, z: 0 } }, { id: 'ma', tick: t, type: 'move-character', characterId: 'a', direction: { x: Q, y: 0, z: 0 } }]).snapshot; assert.ok(s.bodies.find(x => x.id === 'ground')!.velocity.x > s.bodies.find(x => x.id === 'air')!.velocity.x); });
// 16
test('walking emits alternating footstep events', () => { const body = capsule('avatar', 0, 1000, 0); const cfg = config([body], { characters: [{ id: 'player', bodyId: 'avatar', walkSpeed: 6000, acceleration: 30_000, jumpSpeed: 5000, footstepDistance: 80 }] }); const commands: SpatialCommand[] = [{ id: 'move', tick: 2, type: 'move-character', characterId: 'player', direction: { x: Q, y: 0, z: 0 } }]; const w = new SpatialEmbodimentWorld(cfg); w.run(2, commands); const feet = new Set<string>(); for (let i = 0; i < 30; i++) for (const e of w.step(commands).events) if (e.kind === 'footstep') feet.add(e.foot); assert.ok(feet.has('left') && feet.has('right')); });
// 17
test('impact generates spatial audio event', () => { const s = new SpatialEmbodimentWorld(config([{ ...sphere('a', 0, 520, 0), velocity: { x: 0, y: -5000, z: 0 } }])).step().snapshot; assert.ok(s.events.some(e => e.kind === 'spatial-audio')); });
// 18
test('impact generates body-zone haptic event', () => { const body = sphere('a', 0, 520, 0); body.fixtures[0]!.bodyZone = 'hand.right'; body.velocity = { x: 0, y: -5000, z: 0 }; const s = new SpatialEmbodimentWorld(config([body])).step().snapshot; const event = s.events.find(e => e.kind === 'haptic'); assert.equal(event?.kind === 'haptic' ? event.zone : '', 'hand.right'); });
// 19
test('contact lifecycle begins then persists', () => { const w = new SpatialEmbodimentWorld(config([sphere('a', 0, 500, 0)], { gravity: { x: 0, y: 0, z: 0 } })); const phases = new Set<string>(); for (let i = 0; i < 3; i++) for (const e of w.step().events) if (e.kind === 'contact') phases.add(e.phase); assert.ok(phases.has('begin') && phases.has('persist')); });
// 20
test('distance joint approximately preserves length', () => { const cfg = config([sphere('a', 0, 2000, 0, 'static'), sphere('b', 2000, 2000, 0)], { gravity: { x: 0, y: 0, z: 0 }, joints: [{ id: 'rope', type: 'distance', bodyA: 'a', bodyB: 'b', restLength: 2000, stiffnessQ: 900_000 }] }); const w = new SpatialEmbodimentWorld(cfg); w.run(30, [{ id: 'kick', tick: 1, type: 'apply-impulse', bodyId: 'b', impulse: { x: 0, y: 0, z: 5000 } }]); const s = w.snapshot(); const a = s.bodies.find(x => x.id === 'a')!, b = s.bodies.find(x => x.id === 'b')!; assert.ok(Math.abs(Math.hypot(a.position.x - b.position.x, a.position.y - b.position.y, a.position.z - b.position.z) - 2000) < 400); });
// 21
test('ball joint pulls anchors together', () => { const cfg = config([sphere('a', 0, 2000, 0, 'static'), sphere('b', 2500, 2000, 0)], { gravity: { x: 0, y: 0, z: 0 }, joints: [{ id: 'shoulder', type: 'ball', bodyA: 'a', bodyB: 'b', localAnchorA: { x: 500, y: 0, z: 0 }, localAnchorB: { x: -500, y: 0, z: 0 }, stiffnessQ: 900_000 }] }); const s = new SpatialEmbodimentWorld(cfg).step().snapshot; assert.ok(s.joints[0]!.lastForce > 0); assert.ok(s.bodies.find(x => x.id === 'b')!.position.x < 2500); });
// 22
test('hinge motor changes angular velocity', () => { const cfg = config([box('base', 0, 2000, 0, 'static'), box('arm', 1000, 2000, 0)], { gravity: { x: 0, y: 0, z: 0 }, joints: [{ id: 'elbow', type: 'hinge', bodyA: 'base', bodyB: 'arm', axis: { x: 0, y: Q, z: 0 }, motorSpeedDeg: degrees(90), maxMotorTorque: degrees(5) }] }); const s = new SpatialEmbodimentWorld(cfg).run(5); assert.notEqual(s.bodies.find(x => x.id === 'arm')!.angularVelocityDeg.y, 0); });
// 23
test('joint breaks above force limit', () => { const cfg = config([sphere('a', 0, 1000, 0, 'static'), sphere('b', 4000, 1000, 0)], { gravity: { x: 0, y: 0, z: 0 }, joints: [{ id: 'weak', type: 'distance', bodyA: 'a', bodyB: 'b', restLength: 1000, stiffnessQ: Q, breakForce: 10 }] }); const s = new SpatialEmbodimentWorld(cfg).step().snapshot; assert.equal(s.joints[0]!.broken, true); assert.ok(s.events.some(e => e.kind === 'joint')); });
// 24
test('point query finds fixture in 3D', () => { const w = new SpatialEmbodimentWorld(config([box('a', 1000, 1000, 1000, 'static')])); assert.equal(w.queryPoint({ x: 1000, y: 1000, z: 1000 })[0]!.bodyId, 'a'); });
// 25
test('AABB query excludes distant bodies', () => { const w = new SpatialEmbodimentWorld(config([sphere('a', 0, 1000, 0, 'static'), sphere('b', 10_000, 1000, 0, 'static')])); assert.deepEqual(w.queryAabb({ min: { x: -1000, y: 0, z: -1000 }, max: { x: 1000, y: 2000, z: 1000 } }).map(x => x.bodyId), ['a']); });
// 26
test('ray cast sorts nearest 3D hit first', () => { const w = new SpatialEmbodimentWorld(config([box('a', 2000, 1000, 0, 'static'), box('b', 5000, 1000, 0, 'static')])); const hits = w.rayCast({ x: 0, y: 1000, z: 0 }, { x: Q, y: 0, z: 0 }); assert.equal(hits[0]!.bodyId, 'a'); });
// 27
test('deterministic replay preserves state root', () => { const cfg = config([{ ...sphere('a', 0, 5000, 0), velocity: { x: 1000, y: 0, z: 500 } }]); const commands: SpatialCommand[] = [{ id: 'kick', tick: 7, type: 'apply-impulse', bodyId: 'a', impulse: { x: 100, y: 200, z: 300 } }]; assert.equal(replaySpatialEmbodiment(cfg, 80, commands).stateRoot, replaySpatialEmbodiment(cfg, 80, commands).stateRoot); });
// 28
test('snapshot recovery converges', () => { const cfg = config([{ ...box('a', 0, 4000, 0), velocity: { x: 500, y: 0, z: 700 }, angularVelocityDeg: { x: degrees(10), y: degrees(20), z: degrees(5) } }]); const w = new SpatialEmbodimentWorld(cfg); w.run(30); const checkpoint = w.snapshot(); w.run(30); const final = w.snapshot(); const restored = SpatialEmbodimentWorld.fromSnapshot(checkpoint); restored.run(30); assert.equal(restored.snapshot().stateRoot, final.stateRoot); });
// 29
test('bullet body requests microsteps', () => { const bullet = sphere('bullet', 0, 1000, 0, 'dynamic', 100); bullet.velocity = { x: 300_000, y: 0, z: 0 }; bullet.bullet = true; const s = new SpatialEmbodimentWorld(config([bullet, box('wall', 3000, 1000, 0, 'static', 50, 1000, 1000)], { gravity: { x: 0, y: 0, z: 0 }, maxSubsteps: 32 })).step().snapshot; assert.ok(s.diagnostics.microsteps > 1); assert.equal(s.diagnostics.ccdBodies, 1); });
// 30
test('stable grounded body can sleep', () => { const a = sphere('a', 0, 500, 0); a.sleepTicks = 3; a.sleepSpeedThreshold = 20; const s = new SpatialEmbodimentWorld(config([a], { gravity: { x: 0, y: 0, z: 0 } })).run(5); assert.equal(s.bodies[0]!.awake, false); });
// 31
test('RFE causal delta contains position and grounded facts', () => { const s = new SpatialEmbodimentWorld(config([sphere('a', 0, 500, 0)])).step().snapshot; const delta = spatialEmbodimentSnapshotToCausalDelta(s, 'rfe:base'); assert.equal(delta.format, 'rfe.spatial-embodiment-causal-delta.v0.6'); assert.ok(delta.facts.some(f => f.predicate === 'spatial.position')); assert.ok(delta.deltaRoot.length > 8); });
// 32
test('snapshot keeps RFE generation binding distinct from simulation tick', () => { const s = new SpatialEmbodimentWorld(config([sphere('a', 0, 500, 0)])).run(3); assert.equal(s.reality.generation, 7); assert.equal(s.tick, 3); });
// 33
test('VSR scene contains body hierarchy and 3D reality binding', () => { const s = new SpatialEmbodimentWorld(config([capsule('avatar', 0, 1000, 0)])).step().snapshot; const scene = spatialEmbodimentSnapshotToVSRScene(s); assert.ok(scene.nodes.some(n => n.id === 'body:avatar')); assert.equal(scene.reality?.worldId, s.worldId); assert.equal(scene.reality?.generation, 7); });
// 34
test('VSR projection compiles verified frame and deterministic pixels', () => { const s = new SpatialEmbodimentWorld(config([capsule('avatar', 0, 1000, 0), box('crate', 1800, 500, 0)])).run(2); const a = projectSpatialEmbodiment(s, { width: 240, height: 135, qualityTier: 'economy' }); const b = projectSpatialEmbodiment(s, { width: 240, height: 135, qualityTier: 'economy' }); assert.equal(a.frameVerified, true); assert.equal(a.pixelRoot, b.pixelRoot); assert.ok(a.png.byteLength > 100); });
// 34a
test('RSR projection uses the central VSR instance frame contract', () => { const s = new SpatialEmbodimentWorld(config([capsule('avatar', 0, 1000, 0), box('crate', 1800, 500, 0)])).run(2); const projected = projectSpatialEmbodiment(s, { width: 160, height: 90, qualityTier: 'economy' }); assert.ok((projected.framePlan.stats.visibleInstances ?? 0) >= projected.framePlan.drawPackets.length); assert.ok((projected.framePlan.stats.instancedDraws ?? 0) > 0); assert.ok(projected.framePlan.resources.some(resource => resource.kind === 'instance-buffer')); assert.ok(projected.framePlan.drawPackets.every(packet => Array.isArray(packet.instances))); });
// 35
test('tampered VSR draw packet is rejected', () => { const s = new SpatialEmbodimentWorld(config([sphere('a', 0, 500, 0)])).step().snapshot; const projected = projectSpatialEmbodiment(s, { width: 160, height: 90, qualityTier: 'economy' }); projected.framePlan.drawPackets[0]!.distanceToCamera += 1; assert.equal(verifySpatialFrame(projected.framePlan).ok, false); });
// 36
test('sensory root changes when impact events appear', () => { const quiet = new SpatialEmbodimentWorld(config([sphere('a', 0, 5000, 0)], { gravity: { x: 0, y: 0, z: 0 } })).step().snapshot; const hitBody = sphere('a', 0, 520, 0); hitBody.velocity = { x: 0, y: -5000, z: 0 }; const hit = new SpatialEmbodimentWorld(config([hitBody])).step().snapshot; assert.notEqual(quiet.sensoryRoot, hit.sensoryRoot); });

// 37
test('rotated fixture local position follows body orientation', () => { const carrier = box('carrier', 0, 1000, 0, 'static', 100, 100, 100); carrier.rotationDeg = { x: 0, y: degrees(90), z: 0 }; carrier.fixtures[0]!.localPosition = { x: 1000, y: 0, z: 0 }; const w = new SpatialEmbodimentWorld(config([carrier], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 })); assert.equal(w.queryAabb({ min: { x: -200, y: 800, z: -1200 }, max: { x: 200, y: 1200, z: -800 } }).length, 1); assert.equal(w.queryAabb({ min: { x: 800, y: 800, z: -200 }, max: { x: 1200, y: 1200, z: 200 } }).length, 0); });
// 38
test('sphere contacts rotated box through deterministic convex narrow phase', () => { const wall = box('wall', 0, 1000, 0, 'static', 1000, 100, 100); wall.rotationDeg = { x: 0, y: degrees(45), z: 0 }; const ball = sphere('ball', -800, 1000, 500, 'dynamic', 150); const s = new SpatialEmbodimentWorld(config([ball, wall], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 })).step().snapshot; const contact = s.contacts.find(entry => entry.bodyA === 'ball' || entry.bodyB === 'ball'); assert.ok(contact); assert.ok(Math.abs(contact!.normal.x) > 600_000); assert.ok(Math.abs(contact!.normal.z) > 600_000); assert.equal(s.diagnostics.convexContacts, 1); assert.equal(s.diagnostics.convexFallbacks, 0); });
// 39
test('OBB SAT rejects separated thin boxes whose world AABBs overlap', () => { const a = box('a', 0, 1000, 0, 'static', 1000, 100, 100); a.rotationDeg = { x: 0, y: degrees(45), z: 0 }; const b = box('b', 200, 1000, 200, 'dynamic', 1000, 100, 100); b.rotationDeg = { x: 0, y: degrees(45), z: 0 }; const s = new SpatialEmbodimentWorld(config([a, b], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 })).step().snapshot; assert.equal(s.contacts.length, 0); });
// 40
test('rotated OBB contact replay is deterministic', () => { const a = box('a', 0, 1000, 0, 'static', 1000, 200, 200); a.rotationDeg = { x: degrees(8), y: degrees(32), z: degrees(4) }; const b = box('b', 900, 1000, 100, 'dynamic', 600, 250, 300); b.rotationDeg = { x: degrees(-6), y: degrees(-18), z: degrees(2) }; const cfg = config([a, b], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 }); assert.equal(replaySpatialEmbodiment(cfg, 4).stateRoot, replaySpatialEmbodiment(cfg, 4).stateRoot); });

// 41
test('rotated OBB narrow phase emits deterministic GJK and EPA evidence', () => { const a = box('a', 0, 1000, 0, 'static', 1000, 200, 200); a.rotationDeg = { x: degrees(8), y: degrees(32), z: degrees(4) }; const b = box('b', 900, 1000, 100, 'dynamic', 600, 250, 300); b.rotationDeg = { x: degrees(-6), y: degrees(-18), z: degrees(2) }; const cfg = config([a, b], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 }); const snapshot = new SpatialEmbodimentWorld(cfg).step().snapshot; assert.ok(snapshot.contacts.length >= 1); assert.ok(snapshot.diagnostics.gjkCalls >= 1); assert.ok(snapshot.diagnostics.epaCalls >= 1); assert.ok(snapshot.diagnostics.convexContacts >= 1); assert.equal(snapshot.diagnostics.convexFallbacks, 0); assert.equal(replaySpatialEmbodiment(cfg, 1).stateRoot, snapshot.stateRoot); });

// 42
test('sphere-sphere contact uses the stable convex fast path without legacy fallback', () => { const a = sphere('a', -250, 1000, 0, 'static', 300); const b = sphere('b', 250, 1000, 0, 'dynamic', 300); const snapshot = new SpatialEmbodimentWorld(config([a, b], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 })).step().snapshot; assert.equal(snapshot.contacts.length, 1); assert.equal(snapshot.diagnostics.gjkCalls, 1); assert.equal(snapshot.diagnostics.epaCalls, 0); assert.equal(snapshot.diagnostics.convexContacts, 1); assert.equal(snapshot.diagnostics.convexFallbacks, 0); });

// 43
test('rotated capsule-box contact uses generalized convex support', () => { const wall = box('wall', 0, 1000, 0, 'static', 700, 400, 140); wall.rotationDeg = { x: degrees(8), y: degrees(42), z: degrees(-5) }; const avatar = capsule('avatar', -520, 1000, 220, 'dynamic', 180, 420); avatar.rotationDeg = { x: degrees(18), y: degrees(-12), z: degrees(26) }; const snapshot = new SpatialEmbodimentWorld(config([avatar, wall], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 })).step().snapshot; assert.ok(snapshot.contacts.length >= 1); assert.equal(snapshot.diagnostics.gjkCalls, 1); assert.ok(snapshot.diagnostics.epaCalls >= 1); assert.equal(snapshot.diagnostics.convexContacts, 1); assert.equal(snapshot.diagnostics.convexFallbacks, 0); assert.equal(snapshot.diagnostics.capsuleObbContacts, 1); });

// 44
test('rotated capsule-capsule contact is deterministic and generalized', () => { const a = capsule('a', -200, 1000, 0, 'static', 240, 500); a.rotationDeg = { x: degrees(10), y: degrees(18), z: degrees(28) }; const b = capsule('b', 200, 1000, 120, 'dynamic', 240, 500); b.rotationDeg = { x: degrees(-14), y: degrees(-24), z: degrees(-16) }; const cfg = config([a, b], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 }); const snapshot = new SpatialEmbodimentWorld(cfg).step().snapshot; assert.ok(snapshot.contacts.length >= 1); assert.equal(snapshot.diagnostics.gjkCalls, 1); assert.ok(snapshot.diagnostics.epaCalls >= 1); assert.equal(snapshot.diagnostics.convexContacts, 1); assert.equal(snapshot.diagnostics.convexFallbacks, 0); assert.equal(replaySpatialEmbodiment(cfg, 1).stateRoot, snapshot.stateRoot); });

// 45
test('rotated sphere-capsule contact uses generalized convex support', () => { const avatar = capsule('avatar', 0, 1000, 0, 'static', 220, 500); avatar.rotationDeg = { x: degrees(24), y: degrees(-18), z: degrees(31) }; const ball = sphere('ball', 420, 1020, 80, 'dynamic', 260); const snapshot = new SpatialEmbodimentWorld(config([avatar, ball], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 })).step().snapshot; assert.ok(snapshot.contacts.length >= 1); assert.equal(snapshot.diagnostics.gjkCalls, 1); assert.ok(snapshot.diagnostics.epaCalls >= 1); assert.equal(snapshot.diagnostics.convexContacts, 1); assert.equal(snapshot.diagnostics.convexFallbacks, 0); });

// 46
test('rotated capsule broad phase covers the oriented segment', () => { const spear = capsule('spear', -550, 1000, 0, 'static', 150, 600); spear.rotationDeg = { x: 0, y: 0, z: degrees(90) }; const avatar = capsule('avatar', 0, 1000, 0, 'dynamic', 150, 400); const snapshot = new SpatialEmbodimentWorld(config([spear, avatar], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 })).step().snapshot; assert.equal(snapshot.contacts.length, 1); assert.equal(snapshot.diagnostics.broadPhasePairs, 1); assert.equal(snapshot.diagnostics.gjkCalls, 1); assert.equal(snapshot.diagnostics.convexContacts, 1); assert.equal(snapshot.diagnostics.convexFallbacks, 0); });

// 47
test('persistent contact cache warm-starts resting contacts', () => { const w = new SpatialEmbodimentWorld(config([sphere('warm', 0, 500, 0)])); w.step(); const second = w.step().snapshot; assert.ok(second.contacts.some(contact => contact.warmStarted)); assert.ok(second.diagnostics.warmStartedContacts > 0); assert.ok(second.diagnostics.persistentManifolds > 0); });
// 48
test('deterministic spatial partition avoids all-pairs broad phase', () => { const bodies: SpatialBodySpec[] = []; for (let i = 0; i < 24; i++) bodies.push(sphere(`far:${i}`, i * 20_000, 1000, 0, i === 0 ? 'dynamic' : 'static')); const snapshot = new SpatialEmbodimentWorld(config(bodies, { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000, broadPhaseCellSize: 2000 })).step().snapshot; assert.ok(snapshot.diagnostics.broadPhaseCells >= 24); assert.ok(snapshot.diagnostics.broadPhasePairs < 10); });
// 49
test('character controller steps over a low obstacle', () => { const avatar = capsule('avatar', 0, 1000, 0); const stepBody = box('step', 950, 150, 0, 'static', 300, 150, 1000); const cfg = config([avatar, stepBody], { characters: [{ id: 'player', bodyId: 'avatar', walkSpeed: 4000, acceleration: 40_000, jumpSpeed: 6000, stepHeight: 400, groundSnapDistance: 120 }] }); const w = new SpatialEmbodimentWorld(cfg); const commands: SpatialCommand[] = [{ id: 'walk', tick: 2, type: 'move-character', characterId: 'player', direction: { x: Q, y: 0, z: 0 } }]; w.run(2, commands); let stepped = false; let steppedHeight = 0; for (let i = 0; i < 30; i++) { const snapshot = w.step(commands).snapshot; if (snapshot.diagnostics.steppedCharacters > 0) { stepped = true; steppedHeight = Math.max(steppedHeight, snapshot.bodies.find(body => body.id === 'avatar')!.position.y); } } const avatarState = w.snapshot().bodies.find(body => body.id === 'avatar')!; assert.equal(stepped, true); assert.ok(steppedHeight >= 1300); assert.ok(avatarState.position.x > 1250); });
// 50
test('ground snap keeps a character attached across a small drop', () => { const avatar = capsule('avatar', 0, 1520, 0); const platform = box('platform', 0, 250, 0, 'static', 1500, 250, 1500); const cfg = config([avatar, platform], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000, characters: [{ id: 'player', bodyId: 'avatar', walkSpeed: 3000, acceleration: 12_000, jumpSpeed: 6000, groundSnapDistance: 100 }] }); const snapshot = new SpatialEmbodimentWorld(cfg).step().snapshot; const state = snapshot.bodies.find(body => body.id === 'avatar')!; assert.equal(state.grounded, true); assert.equal(state.position.y, 1500); assert.equal(snapshot.diagnostics.snappedCharacters, 1); });
// 51
test('character inherits deterministic displacement from a moving platform', () => { const avatar = capsule('avatar', 0, 1500, 0); const platform = box('platform', 0, 250, 0, 'kinematic', 1500, 250, 1500); const cfg = config([avatar, platform], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000, characters: [{ id: 'player', bodyId: 'avatar', walkSpeed: 3000, acceleration: 12_000, jumpSpeed: 6000, groundSnapDistance: 50 }] }); const w = new SpatialEmbodimentWorld(cfg); w.step([{ id: 'platform-move', tick: 1, type: 'set-velocity', bodyId: 'platform', velocity: { x: 6000, y: 0, z: 0 } }]); const second = w.step().snapshot; assert.ok(second.bodies.find(body => body.id === 'avatar')!.position.x >= 90); assert.ok(second.diagnostics.movingPlatformTransfers > 0); });
// 52
test('one-way platform allows upward passage and catches falling bodies', () => { const platform = box('one-way', 0, 1000, 0, 'static', 1200, 100, 1200); platform.fixtures[0]!.oneWay = { normal: { x: 0, y: Q, z: 0 }, minApproachSpeed: 40, skin: 30 }; const rising = sphere('rising', 0, 600, 0, 'dynamic', 100); rising.velocity = { x: 0, y: 30_000, z: 0 }; const risingState = new SpatialEmbodimentWorld(config([rising, platform], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 })).run(3); assert.ok(risingState.bodies.find(body => body.id === 'rising')!.position.y > 1500); const falling = sphere('falling', 0, 1450, 0, 'dynamic', 100); falling.velocity = { x: 0, y: -12_000, z: 0 }; const fallingState = new SpatialEmbodimentWorld(config([falling, platform], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 })).run(6); const finalBody = fallingState.bodies.find(body => body.id === 'falling')!; assert.equal(finalBody.grounded, true); assert.ok(finalBody.position.y >= 1190); });
// 53
test('legacy spatial world format migrates to v0.6 snapshots', () => { const legacy = config([sphere('legacy', 0, 500, 0)]) as SpatialEmbodimentWorldConfig; legacy.format = 'rsr.spatial-embodiment-world.v0.5'; const snapshot = new SpatialEmbodimentWorld(legacy).step().snapshot; assert.equal(snapshot.format, 'rsr.spatial-embodiment-snapshot.v0.6'); assert.equal(snapshot.runtimeVersion, '0.9.0-alpha.1'); });

// 54
test('capsule contacts rotated OBB with oriented normal instead of AABB fallback', () => { const wall = box('wall', 0, 1200, 0, 'static', 1200, 500, 120); wall.rotationDeg = { x: 0, y: degrees(45), z: 0 }; const avatar = capsule('avatar', -850, 1200, 520, 'dynamic', 180, 450); const snapshot = new SpatialEmbodimentWorld(config([avatar, wall], { gravity: { x: 0, y: 0, z: 0 }, floorY: -100_000 })).step().snapshot; const contact = snapshot.contacts.find(entry => entry.bodyA === 'avatar' || entry.bodyB === 'avatar'); assert.ok(contact); assert.ok(Math.abs(contact!.normal.x) > 500_000); assert.ok(Math.abs(contact!.normal.z) > 500_000); assert.equal(snapshot.diagnostics.capsuleObbContacts, 1); });
// 55
test('persistent friction impulse warm-starts sliding floor contacts', () => { const slider = box('slider', 0, 500, 0); slider.velocity = { x: 3000, y: 0, z: 0 }; slider.frictionQ = 900_000; const world = new SpatialEmbodimentWorld(config([slider])); const first = world.step().snapshot; assert.ok(first.contacts.some(contact => contact.tangentImpulse > 0)); const second = world.step().snapshot; assert.ok(second.contacts.some(contact => contact.warmStarted && contact.tangentImpulse > 0)); assert.ok(second.diagnostics.warmStartedFrictionContacts > 0); });
// 56
test('deterministic constraint islands separate unrelated dynamic groups', () => { const bodies = [sphere('a', 0, 500, 0), sphere('b', 800, 500, 0), sphere('isolated', 10_000, 500, 0)]; const snapshot = new SpatialEmbodimentWorld(config(bodies, { gravity: { x: 0, y: 0, z: 0 } })).step().snapshot; assert.equal(snapshot.diagnostics.solverIslands, 2); assert.equal(snapshot.diagnostics.largestSolverIsland, 2); });
// 57
test('connected resting bodies sleep as one deterministic island', () => { const a = sphere('a', 0, 500, 0), b = sphere('b', 900, 500, 0); for (const body of [a, b]) { body.sleepTicks = 2; body.sleepSpeedThreshold = 20; } const snapshot = new SpatialEmbodimentWorld(config([a, b], { gravity: { x: 0, y: 0, z: 0 }, joints: [{ id: 'sleep-link', type: 'distance', bodyA: 'a', bodyB: 'b', restLength: 900, stiffnessQ: 900_000 }] })).run(3); assert.equal(snapshot.bodies.every(body => !body.awake), true); assert.equal(snapshot.diagnostics.solverIslands, 1); assert.equal(snapshot.diagnostics.sleepingIslands, 1); });
// 58
test('character coyote time accepts a jump shortly after leaving support', () => { const avatar = capsule('avatar', 0, 1000, 0); const cfg = config([avatar], { characters: [{ id: 'player', bodyId: 'avatar', walkSpeed: 3000, acceleration: 12_000, jumpSpeed: 6000, coyoteTicks: 3, jumpBufferTicks: 3 }] }); const world = new SpatialEmbodimentWorld(cfg); world.step(); world.step([{ id: 'leave', tick: 2, type: 'teleport', bodyId: 'avatar', position: { x: 0, y: 1800, z: 0 } }]); const snapshot = world.step([{ id: 'late-jump', tick: 3, type: 'jump-character', characterId: 'player' }]).snapshot; assert.ok(snapshot.bodies[0]!.velocity.y > 0); assert.equal(snapshot.diagnostics.coyoteJumps, 1); });
// 59
test('jump buffer fires on the tick after an airborne character lands', () => { const avatar = capsule('avatar', 0, 1600, 0); avatar.velocity = { x: 0, y: -30_000, z: 0 }; const cfg = config([avatar], { characters: [{ id: 'player', bodyId: 'avatar', walkSpeed: 3000, acceleration: 12_000, jumpSpeed: 7000, coyoteTicks: 0, jumpBufferTicks: 4 }] }); const world = new SpatialEmbodimentWorld(cfg); const landing = world.step([{ id: 'early-jump', tick: 1, type: 'jump-character', characterId: 'player' }]).snapshot; assert.equal(landing.bodies[0]!.grounded, true); const takeoff = world.step().snapshot; assert.ok(takeoff.bodies[0]!.velocity.y > 0); assert.equal(takeoff.diagnostics.bufferedJumps, 1); });

console.log(`Spatial Embodiment tests: ${passed}/${passed} PASS`);
