const $=id=>document.getElementById(id),state={unified:null,forge:null,inspection:null,preview:null,angle:0};
const post=async(route,body)=>{const response=await fetch(route,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok||data.error)throw new Error(data.error?.message||`HTTP ${response.status}`);return data};
const short=value=>value?String(value).slice(0,12)+'…':'—';
function setStatus(value){$('status').textContent=typeof value==='string'?value:JSON.stringify(value,null,2)}
function intent(){return{description:$('description').value,subject_id:'subject:studio-asset-forge',asset_kind:$('kind').value,functional_role:$('kind').value==='character-3d'?'player-character':'world-prop',target_platforms:$('platform').value.split(','),constraints:{palette:$('palette').value.split(',').map(x=>x.trim()),style:'stylized-readable-pbr',max_texture_size:512,max_sprite_frames:6,audio_seconds:.8,max_particles:96,max_triangles:2400,pbr_texture_size:256,max_bones:64,animation_fps:30,lod_ratios:[1,.55,.25],license_policy:'generated-or-cleared'}}}
async function boot(){try{const health=await fetch('/api/health').then(r=>r.json());$('connection').textContent=`原生服务在线 · ${health.studio_version}`;const project=await fetch('/api/unified/sample').then(r=>r.json());state.unified=await post('/api/unified/session/new',{project});setStatus(`统一制造会话已建立\n${state.unified.session_id}`)}catch(error){$('connection').textContent='离线参考模式';setStatus(`未连接原生服务：${error.message}\n请通过 node src/cli.mjs serve 启动。`)}}
async function ensureForge(){if(!state.unified)throw new Error('统一制造会话尚未建立');if(!state.forge){state.forge=await post('/api/asset-forge/session/new',{unified_session_id:state.unified.session_id,intent:intent()})}return state.forge}
function renderCandidates(){const list=state.inspection?.production?.candidates??[];$('generation').textContent=`Generation ${state.inspection?.production?.generation??'—'}`;$('cards').innerHTML=list.length?'':'<div class="empty">尚未生成</div>';for(const item of list){const card=document.createElement('article');card.className='candidate'+(item.candidate_id===state.inspection.production.selected_candidate_id?' selected':'');card.innerHTML=`<b>${item.variant}</b><small>${item.candidate_id}</small><span class="score">${Math.round((item.score?.total??0)*100)/100}</span><div class="gates">${Object.entries(item.gates).filter(([,ok])=>ok).map(([name])=>`<i>${name}</i>`).join('')}</div>`;card.onclick=async()=>{try{state.inspection=await post('/api/asset-forge/session/select',{forge_id:state.forge.forge_id,candidate_id:item.candidate_id,reason:'visual-selection'});await loadPreview();renderCandidates()}catch(error){setStatus(error.message)}};$('cards').append(card)}}
function drawMesh(){const ctx=$('canvas').getContext('2d'),w=ctx.canvas.width,h=ctx.canvas.height;ctx.clearRect(0,0,w,h);const mesh=state.preview?.runtime_payload?.mesh;if(!mesh?.positions?.length)return;const p=mesh.positions,idx=mesh.indices??[],c=Math.cos(state.angle),s=Math.sin(state.angle),points=[];for(let i=0;i<p.length;i+=3){const x=p[i],y=p[i+1],z=p[i+2],rx=x*c-z*s,rz=x*s+z*c,scale=145/(2.5+rz*.25);points.push([w/2+rx*scale,h*.58-y*scale,rz])}ctx.lineWidth=1;ctx.strokeStyle='#6dd3ff';ctx.fillStyle='#17466a88';for(let i=0;i<idx.length;i+=3){const a=points[idx[i]],b=points[idx[i+1]],d=points[idx[i+2]];if(!a||!b||!d)continue;ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.lineTo(d[0],d[1]);ctx.closePath();ctx.fill();ctx.stroke()}state.angle+=.008;requestAnimationFrame(drawMesh)}
function renderEvidence(){const p=state.preview,i=state.inspection,a=i?.accepted;$('previewRoot').textContent=`Preview Root ${short(p?.preview_root)}`;const values=[['候选',p?.variant],['三角形',p?.visual?.triangle_count],['PBR贴图',p?.visual?.pbr_files?.length],['骨架身体',p?.physical?.shape],['Workspace',i?.production?.workspace_root],['Candidate',p?.candidate_root],['Project',i?.project?.project_root],['Acceptance',a?.acceptance_root]];$('metrics').innerHTML=values.slice(0,4).map(([k,v])=>`<div class="metric"><span>${k}</span><b>${v??'—'}</b></div>`).join('');$('evidence').innerHTML=values.slice(4).map(([k,v])=>`<article><small>${k}</small><code>${v??'—'}</code></article>`).join('')}
async function loadPreview(){state.preview=await post('/api/asset-forge/session/preview',{forge_id:state.forge.forge_id,include_runtime:true});renderEvidence()}
$('generate').onclick=async()=>{try{await ensureForge();state.inspection=await post('/api/asset-forge/session/generate',{forge_id:state.forge.forge_id});renderCandidates();await loadPreview();setStatus('三个候选已经生成，可切换查看并接受。')}catch(error){setStatus(error.message)}};
$('regenerate').onclick=async()=>{try{await ensureForge();state.inspection=await post('/api/asset-forge/session/regenerate',{forge_id:state.forge.forge_id,patch:{constraints:{palette:$('palette').value.split(',').map(x=>x.trim())}},label:'visual-palette-regeneration'});renderCandidates();await loadPreview();setStatus('已按当前配色定点再生，资产身份保持不变。')}catch(error){setStatus(error.message)}};
$('accept').onclick=async()=>{try{await ensureForge();state.inspection=await post('/api/asset-forge/session/accept',{forge_id:state.forge.forge_id,x:220,y:144,z:0});renderCandidates();renderEvidence();setStatus({status:'accepted',asset_id:state.inspection.accepted.asset_id,node_id:state.inspection.accepted.node_id,spatial_body_id:state.inspection.accepted.spatial_body_id,project_root:state.inspection.project.project_root})}catch(error){setStatus(error.message)}};
boot();drawMesh();
