import {createWorkspace} from '@taowind/reality-branch-fabric';
import {clone,rootHash,now,seal,StudioError} from './canonical.mjs';
import {requireValid,ZERO_ROOT} from './model.mjs';
const riskRank={low:1,medium:2,high:3,critical:4};
function componentRoots(a){return{semantic_root:rootHash(a.semantics),authority_root:rootHash(a.authority),affordance_root:rootHash(a.affordances),capability_root:rootHash(a.capabilities),projection_root:rootHash(a.projections),host_state_root:rootHash(a.host_state_refs)}}
function revisionPayload(a,roots){const c=a.continuity.current;return{artifact_id:a.identity.artifact_id,revision:c.revision,parent_revision_root:c.parent_revision_root??null,branch:c.branch,binding_status:c.binding_status,authoritative_generation:c.authoritative_generation,committed_transition_ref:c.committed_transition_ref??null,...roots}}
function artifactPayload(a){const o=clone(a);delete o.evidence;return o}
export function compileLAF(project){
 requireValid(project);const t=project.identity.updated_at??now();
 const a={format:'laf.artifact.v1',laf_version:'1.0.0',identity:{artifact_id:project.artifact.artifact_id,kind:project.artifact.kind,title:project.artifact.title,owner_subject_id:project.artifact.owner_subject_id,created_at:project.identity.created_at,updated_at:t},semantics:{field_schema:clone(project.artifact.field_schema),values:clone(project.artifact.values),relations:clone(project.artifact.relations??[]),tags:clone(project.artifact.tags??[])},authority:{default_role:project.authority.default_role,mutations_require_transition:project.authority.mutations_require_transition,roles:clone(project.authority.roles),policy_refs:(project.authority.policies??[]).map(x=>x.policy_id)},affordances:(project.affordances??[]).map(x=>({affordance_id:x.affordance_id,label:x.label,intent_patterns:x.intent_patterns??[],parameters:x.parameters??[],preconditions:x.preconditions??[],proposed_operations:x.proposed_operations??[],required_scopes:x.required_scopes??[],capability_requirements:(x.capability_requirements??[]).map(id=>({id,version:'*'}))})),capabilities:{provides:(project.capabilities??[]).map(x=>({id:x.capability_id,version:x.version,provider:x.provider_id,fulfills:x.fulfills??[],risk:x.risk,reversible:x.reversible,execution_phase:x.execution_phase})),requires:[]},projections:(project.projections??[]).map(x=>({projection_id:x.projection_id,modality:x.modality,target_hosts:[x.target_host],definition:{title:x.title,mode:x.target_host,fields:x.visible_fields??[],actions:x.actions??[],priority:x.priority??10,requires:x.requires??[],prefers:x.prefers??[],cost:x.cost??{cpu_ms:'1',memory_mb:8,network_kb:0}}})),host_state_refs:[],continuity:{current:{revision:0,parent_revision_root:null,branch:'main',binding_status:'unbound',authoritative_generation:{reality_id:project.rncs.reality_id,generation:0,generation_root:ZERO_ROOT},committed_transition_ref:null,revision_root:ZERO_ROOT},branches:{main:ZERO_ROOT},history:[]},extensions:{'reality-studio':{studio_version:project.version,project_id:project.identity.project_id,project_root:project.evidence.project_root,subjects:project.subjects,intents:project.intents,reality:project.reality,branches:project.branches,evidence_requirements:project.evidence.requirements,experience:project.experience?.legacy_project?{kind:project.experience.kind,legacy_format:project.experience.legacy_format,source_root:project.experience.migration?.source_root}:null,behavior:{active_program_id:project.behavior?.active_program_id??null,programs:(project.behavior?.programs??[]).map(x=>({program_id:x.program_id,title:x.title,program_root:x.program_root,status:x.status??'ready'})),bindings:clone(project.behavior?.bindings??[])}}}};
 const roots=componentRoots(a);a.continuity.current.revision_root=rootHash(revisionPayload(a,roots));a.continuity.branches.main=a.continuity.current.revision_root;a.continuity.history=[{revision:0,revision_root:a.continuity.current.revision_root,parent_revision_root:null,branch:'main',binding_status:'unbound',authoritative_generation:a.continuity.current.authoritative_generation,actor_subject_id:project.artifact.owner_subject_id,message:'Reality Studio native compile',created_at:t,...roots}];a.evidence={algorithm:'sha256-rncs-canonical-v1',...roots,revision_root:a.continuity.current.revision_root};a.evidence.artifact_root=rootHash(artifactPayload(a));return a
}
export function compileProviders(project){
 const groups=new Map();for(const c of project.capabilities??[]){const id=c.provider_id??'provider:studio';if(!groups.has(id))groups.set(id,[]);groups.get(id).push({capability_id:c.capability_id,version:c.version,fulfills:c.fulfills??[],inputs:c.inputs??{},outputs:c.outputs??{},required_scopes:c.required_scopes??[],host_requirements:c.host_requirements??[],risk:{level:c.risk??'low',reasons:c.risk_reasons??[]},reversible:c.reversible!==false,execution_phase:c.execution_phase??'transaction',side_effects:c.side_effects??[],evidence:{produces:c.evidence_produces??[],requires:c.evidence_requires??[]},cost:c.cost??{cpu_millis:1,memory_mb:1,network_kb:0,monetary_microunits:0},transport:c.transport??{kind:'local',entrypoint:c.capability_id}})}
 return [...groups.entries()].map(([provider_id,capabilities])=>({provider_id,protocol_versions:['0.1.0'],status:'available',trust:{level:3,attestations:['reality-studio-native-project']},transports:[{kind:'local',runtime:'studio'}],capabilities}));
}
export function compileCNPRequest(project,{intentId=null,subjectId=null}={}){requireValid(project);const intent=project.intents.find(x=>x.intent_id===(intentId??project.intents[0]?.intent_id));if(!intent)throw new StudioError('INTENT_NOT_FOUND',intentId??'');const subject=project.subjects.find(x=>x.subject_id===(subjectId??project.artifact.owner_subject_id));if(!subject)throw new StudioError('SUBJECT_NOT_FOUND',subjectId??'');const effectiveScopes=(subject.scopes??[]).includes('*')?[...new Set((project.capabilities??[]).flatMap(c=>c.required_scopes??[]))]:subject.scopes??[];return{request_id:`request:${rootHash({project:project.evidence.project_root,intent:intent.intent_id}).slice(0,24)}`,protocol_versions:['0.1.0'],subject:{subject_id:subject.subject_id,scopes:effectiveScopes},host:{host_id:'host:studio-desktop',capabilities:['display.text','display.visual','input.activate','input.text','host.notification','storage.persistent']},goals:(intent.goals??[]).map((type,i)=>({goal_id:`goal:${i+1}:${type.replace(/[^a-z0-9.-]+/gi,'-')}`,type,version_range:'>=1.0.0 <2.0.0',inputs:{artifact_id:{type:'string'}}})),policy:{max_risk:'medium',require_reversible:false,required_evidence:[],minimum_trust:1,cost_budget:{cpu_millis:100,memory_mb:128,network_kb:64,monetary_microunits:0}},constraints:{prefer_local:true,base_generation:'generation:0'}}}
export function compilePolicyBundle(project){
 const ownerRoles=project.subjects.find(x=>x.subject_id===project.artifact.owner_subject_id)?.roles??['owner'];
 const policies=[];let priority=10;
 for(const p of project.authority.policies??[]){
  if((p.effect??'allow')==='allow')policies.push({policy_id:p.policy_id??`allow:${priority}`,effect:'allow',priority:priority++,match:{roles_any:p.roles?.length?p.roles:ownerRoles,scopes_any:(p.scopes??['artifact.*']).map(x=>x==='*'?'artifact.*':x),risk_at_most:p.max_risk??'medium'},obligations:[{type:'evidence-required'}]});
  if(p.effect==='deny')policies.push({policy_id:p.policy_id??`deny:${priority}`,effect:'deny',priority:100,match:{risk_at_least:p.risk_at_least??'critical'}})
 }
 policies.push({policy_id:'studio-approve-irreversible',effect:'require_approval',priority:50,match:{irreversible:true},approval:{roles:['owner','security'],quorum:1}});
 policies.push({policy_id:'studio-approve-high-risk',effect:'require_approval',priority:60,match:{risk_at_least:'high'},approval:{roles:['owner','security'],quorum:2}});
 policies.push({policy_id:'studio-deny-critical',effect:'deny',priority:100,match:{risk_at_least:'critical'}});
 return{bundle_id:`policy:studio:${rootHash(project.authority).slice(0,16)}`,default_effect:'deny',policies}
}
export function compilePipelineInput(project,{intentId=null,subjectId=null,rfeStorePath='output/studio-rfe-store',autoApprove=false}={}){
 const artifact=compileLAF(project),cnp_request=compileCNPRequest(project,{intentId,subjectId}),providers=compileProviders(project),subject=project.subjects.find(x=>x.subject_id===(subjectId??project.artifact.owner_subject_id)),intent=project.intents.find(x=>x.intent_id===(intentId??project.intents[0]?.intent_id));
 const cap=(id,required=true,scope='session')=>({id,version:'1',required,scope});
 const desktopCaps=['runtime.javascript','display.visual','display.text','display.table','input.activate','input.pointer','input.keyboard','input.text','storage.persistent','storage.download','crypto.ed25519','host.notification'];
 const mobileCaps=['runtime.javascript','display.visual','display.text','input.activate','input.touch','input.text','storage.persistent','host.notification'];
 return{artifact,intent_text:intent.source,actor:{subject_id:subject.subject_id,kind:subject.kind,role:subject.roles?.[0]??'operator',roles:subject.roles??[],scopes:subject.scopes??[],responsibility_boundary:subject.responsibility_boundary},hosts:[{host_profile_version:'0.1',identity:{id:'host:studio-desktop',runtime:'browser',platform:'web',form_factor:'desktop'},capabilities:desktopCaps.map(id=>({id,version:'1.0'})),adapters:[],budgets:{memory_mb:256,cpu_ms:8,network_kb:1024,storage_mb:256}},{host_profile_version:'0.1',identity:{id:'host:studio-mobile',runtime:'browser',platform:'android',form_factor:'mobile'},capabilities:mobileCaps.map(id=>({id,version:'1.0'})),adapters:[],budgets:{memory_mb:96,cpu_ms:6,network_kb:256,storage_mb:64}}],capsule:{format_version:'0.5',app:{id:'org.taowind.reality-studio.native',name:'Reality Studio Native Project Runtime',version:'0.8.0-alpha.1',description:'RNCS-native project manufacturing capsule'},execution:{primary:{profile:'node-js',entry:'src/cli.mjs'},limits:{operations:100}},capabilities:[cap('display.text'),cap('input.activate'),cap('input.text',false),cap('host.notification',false),cap('storage.state',false,'app')],state:{schema_version:'1',autosnapshot:true,partitions:{portable:{persistence:'durable',portability:'exportable',encrypted:false},device_private:{persistence:'durable',portability:'local-only',encrypted:false},secret:{persistence:'durable',portability:'encrypted-export',encrypted:true},cache:{persistence:'rebuildable',portability:'optional-export',encrypted:false},ephemeral:{persistence:'memory',portability:'never-export',encrypted:false}}},distribution:{projections:['desktop','mobile','headless']},security:{sandbox:'deny-by-default',signature:'optional'},compatibility:{min_runtime:'0.5.0'},extensions:{rncs_contract:'0.1.0'}},rfe_store_path:rfeStorePath,reality_id:project.rncs.reality_id,providers,cnp_request,policy_bundle:compilePolicyBundle(project),environment:'local',auto_approve:autoApprove,approver:{id:subject.subject_id,roles:subject.roles??['owner']}}
}

export function compileBranchWorkspace(project,{generationReference=null}={}){
 requireValid(project);const ref=generationReference??project.rncs?.generation_reference??{generation:0,generation_root:ZERO_ROOT,branch_id:project.rncs.branch_id};
 const candidates=(project.branches??[]).filter(b=>b.branch_id!==project.rncs.branch_id&&b.status!=='merged').map(b=>({branch_id:b.branch_id,label:b.label,parent_branch_id:b.parent_branch_id,hypothesis:b.hypothesis??'',operations:clone(b.operations??[]),constraints:clone(b.constraints??{}),predicted_metrics:clone(b.predicted_metrics??{}),assumptions:clone(b.assumptions??[])}));
 const input={reality_id:project.rncs.reality_id,base_generation:ref.generation??0,base_generation_root:ref.generation_root??ZERO_ROOT,base_branch_id:ref.branch_id??project.rncs.branch_id,project_root:project.evidence.project_root,base_state:project,branches:candidates};if(project.branch_weights)input.weights=project.branch_weights;return createWorkspace(input)
}

export function compileBehaviorDomain(project){
 requireValid(project);
 const programs=(project.behavior?.programs??[]).map(p=>({program_id:p.program_id,title:p.title??p.program_id,program_root:p.program_root,status:p.status??'ready',scene_id:p.scene_id??null,source:p.source??'project'}));
 const bindings=clone(project.behavior?.bindings??[]);
 return seal({format:'reality-studio.behavior-domain.v0.8',version:'0.8.0-alpha.1',active_program_id:project.behavior?.active_program_id??null,programs,bindings,editor:clone(project.behavior?.editor??{}),trace_refs:clone(project.behavior?.trace_refs??[])},'behavior_domain_root')
}

export function compileAll(project,options={}){
 const laf=compileLAF(project),branch_workspace=compileBranchWorkspace(project,options),providers=compileProviders(project),cnp_request=compileCNPRequest(project,options),policy_bundle=compilePolicyBundle(project),pipeline_input=compilePipelineInput(project,options),behavior_domain=compileBehaviorDomain(project);
 return seal({format:'reality-studio.compilation.v0.8',studio_version:'0.8.0-alpha.1',project_root:project.evidence.project_root,compiled_at:now(),laf,providers,cnp_request,policy_bundle,pipeline_input,branch_workspace,behavior_domain},'compilation_root')
}
