import path from 'node:path';import fs from 'node:fs';import {fileURLToPath} from 'node:url';
import {RealityOneGateway,runIntentAuthorityPipeline} from '@taowind/reality-one-gateway';
import {compilePipelineInput} from './compiler.mjs';import {evaluateProjectBranches,proposeProjectBranch,adoptProjectBranch} from './branches.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));const root=path.resolve(here,'..');
export class StudioRuntime{
 constructor({dataDir=path.join(root,'output/runtime'),manifestDirs=null}={}){this.dataDir=path.resolve(dataDir);const gatewayEntry=fileURLToPath(import.meta.resolve('@taowind/reality-one-gateway'));const packageRoot=path.resolve(path.dirname(gatewayEntry),'..');this.manifestDirs=manifestDirs??[path.join(packageRoot,'runtimes')];this.gateway=new RealityOneGateway({manifestDirs:this.manifestDirs,dataDir:path.join(this.dataDir,'gateway')})}
 async init(){await this.gateway.discover();return this}
 async health(){return this.gateway.health()}
 async preview(project,options={}){const input=compilePipelineInput(project,{...options,autoApprove:false,rfeStorePath:options.rfeStorePath??path.join(this.dataDir,'rfe-store')});return runIntentAuthorityPipeline(this.gateway,input,{outDir:path.join(this.dataDir,'preview')})}
 async evaluateBranches(project,options={}){const local=evaluateProjectBranches(project,options),simulations=[];for(const b of local.workspace.branches)simulations.push(await this.gateway.invoke('rncs.rbf','simulateBranch',{workspace:local.workspace,branch_id:b.branch_id},{idempotencyKey:`${local.workspace.workspace_root}:${b.branch_id}`}));const comparison=await this.gateway.invoke('rncs.rbf','compareBranches',{workspace:local.workspace,results:simulations},{idempotencyKey:`compare:${local.workspace.workspace_root}`});return{...local,simulations,comparison,recommended_branch_id:comparison.recommended_branch_id}}
 async proposeBranch(project,options={}){const evaluation=await this.evaluateBranches(project,options);const proposal=await this.gateway.invoke('rncs.rbf','createMergeProposal',{workspace:evaluation.workspace,comparison:evaluation.comparison,branch_id:options.branchId??evaluation.recommended_branch_id,options:{actor:project.artifact.owner_subject_id,require_authority:false}});const transition_draft=await this.gateway.invoke('rncs.rbf','createTransitionDraft',{workspace:evaluation.workspace,proposal});return{...evaluation,proposal,transition_draft}}
 async adoptBranch(project,options={}){const dynamic=await this.proposeBranch(project,options),local=adoptProjectBranch(project,{...options,branchId:dynamic.proposal.selected_branch_id});return{...local,dynamic_runtime:{workspace_root:dynamic.workspace.workspace_root,comparison_root:dynamic.comparison.comparison_root,proposal_root:dynamic.proposal.proposal_root}}}
 async commitBranch(project,options={}){const adopted=await this.adoptBranch(project,options);const pipeline=await this.commit(adopted.project,{...options,resetStore:options.resetStore??true});return{format:'reality-studio.branch-commit.v0.8',...adopted,pipeline}}
 async commit(project,options={}){const store=options.rfeStorePath??path.join(this.dataDir,'rfe-store');if(options.resetStore){fs.rmSync(store,{recursive:true,force:true});fs.rmSync(path.join(this.dataDir,'gateway','idempotency'),{recursive:true,force:true});}const input=compilePipelineInput(project,{...options,autoApprove:true,rfeStorePath:store});return runIntentAuthorityPipeline(this.gateway,input,{outDir:path.join(this.dataDir,'commit')})}
}
