import type { GeneratedModelSchema, GeneratedModelField } from "@/lib/model-generation/modelSchemaBuilder";
import { getExportTarget } from "@/constants/model-generation/modelExportTargets";

export interface ModelExportResult {
  target: string;
  content: string;
  filenameSuggestion: string;
  safetyNotes: string[];
}

const SAFETY_NOTES = ["此模型结构需要真实数据回验", "不要在高风险决策中直接使用"];

function pascal(s: string): string {
  return (s || "Model")
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join("") || "Model";
}

function tsTypeOf(f: GeneratedModelField): string {
  switch (f.fieldType) {
    case "string": return "string";
    case "number": return "number";
    case "boolean": return "boolean";
    case "array": return "string[]";
    case "object": return "Record<string, unknown>";
    case "enum": return (f.allowedValues ?? []).map(v => JSON.stringify(v)).join(" | ") || "string";
    default: return "unknown";
  }
}

function zodTypeOf(f: GeneratedModelField): string {
  let base = "z.unknown()";
  switch (f.fieldType) {
    case "string":  base = "z.string()"; break;
    case "number":  base = "z.number()"; break;
    case "boolean": base = "z.boolean()"; break;
    case "array":   base = "z.array(z.string())"; break;
    case "object":  base = "z.record(z.unknown())"; break;
    case "enum":    base = `z.enum([${(f.allowedValues ?? []).map(v => JSON.stringify(v)).join(",")}])`; break;
  }
  return f.required ? base : `${base}.optional()`;
}

function csTypeOf(f: GeneratedModelField): string {
  switch (f.fieldType) {
    case "string": return "string";
    case "number": return "float";
    case "boolean": return "bool";
    case "array": return "List<string>";
    case "object": return "Dictionary<string, object>";
    default: return "string";
  }
}

function gdTypeOf(f: GeneratedModelField): string {
  switch (f.fieldType) {
    case "string": return "String";
    case "number": return "float";
    case "boolean": return "bool";
    case "array": return "Array";
    case "object": return "Dictionary";
    default: return "String";
  }
}

export function exportModel(schema: GeneratedModelSchema, target: string): ModelExportResult {
  const tgt = getExportTarget(target);
  const ext = tgt?.extension ?? "txt";
  const className = pascal(schema.modelName);
  const filename = `${className}.${ext}`;
  let content = "";

  switch (target) {
    case "JSON":
      content = JSON.stringify(schema, null, 2);
      break;
    case "TS_INTERFACE":
      content =
        `// Generated by Aether Model Forge — ${schema.modelType}\n` +
        `export interface ${className} {\n` +
        schema.fields.map(f =>
          `  /** ${f.description} */\n  ${f.fieldName}${f.required ? "" : "?"}: ${tsTypeOf(f)};`
        ).join("\n") +
        `\n}\n`;
      break;
    case "ZOD":
      content =
        `import { z } from "zod";\n\n` +
        `export const ${className}Schema = z.object({\n` +
        schema.fields.map(f => `  ${f.fieldName}: ${zodTypeOf(f)},`).join("\n") +
        `\n});\n\nexport type ${className} = z.infer<typeof ${className}Schema>;\n`;
      break;
    case "UNITY_CS":
      content =
        `// Aether Model Forge metadata: ${schema.modelType} v${schema.version}\n` +
        `using System.Collections.Generic;\n\n` +
        `[System.Serializable]\npublic class ${className} {\n` +
        schema.fields.map(f => `    public ${csTypeOf(f)} ${f.fieldName}; // ${f.description}`).join("\n") +
        `\n}\n`;
      break;
    case "GODOT_GD":
      content =
        `# Aether Model Forge metadata: ${schema.modelType} v${schema.version}\n` +
        `class_name ${className}\nextends Resource\n\n` +
        schema.fields.map(f => `var ${f.fieldName}: ${gdTypeOf(f)} # ${f.description}`).join("\n") + "\n";
      break;
    case "MARKDOWN":
    case "ENCYCLOPEDIA":
      content =
        `# ${schema.modelName}\n\n` +
        `**Type**: ${schema.modelType}　**Version**: ${schema.version}\n\n` +
        `${schema.description}\n\n## 字段\n\n` +
        schema.fields.map(f => `- \`${f.fieldName}\` (${f.fieldType}${f.required ? ", required" : ""}) — ${f.description}`).join("\n") +
        `\n\n## 权重\n\n` +
        schema.weights.map(w => `- ${w.name}：${w.value}`).join("\n") +
        `\n\n## 回验计划\n\n- 目标：${schema.validationPlan.validationGoal}\n- 信号：${schema.validationPlan.measurableSignals.join("、")}\n- 成功：${schema.validationPlan.successCriteria.join("、")}\n- 失败：${schema.validationPlan.failureSignals.join("、")}\n\n## 安全\n\n${schema.safetyRules.map(r => `- ${r}`).join("\n")}\n`;
      break;
    case "PROMPT":
    case "LOVABLE_PROMPT":
    case "CODEX_PROMPT": {
      const head = target === "LOVABLE_PROMPT" ? "请基于以下模型生成 Lovable 实现："
                 : target === "CODEX_PROMPT"   ? "请基于以下模型生成 Codex / 工程实现："
                 : "请基于以下模型完成任务：";
      content =
        `${head}\n\n模型：${schema.modelName} (${schema.modelType})\n\n字段：\n` +
        schema.fields.map(f => `- ${f.fieldName} (${f.fieldType}${f.required ? ", required" : ""}): ${f.description}`).join("\n") +
        `\n\n验收：\n${schema.validationPlan.successCriteria.map(s => `- ${s}`).join("\n")}\n\n安全：\n${schema.safetyRules.map(s => `- ${s}`).join("\n")}\n`;
      break;
    }
    case "CODE":
      content =
        `// Skeleton for ${className}\nexport class ${className} {\n` +
        schema.fields.map(f => `  ${f.fieldName}${f.required ? "!" : "?"}: ${tsTypeOf(f)};`).join("\n") +
        `\n}\n`;
      break;
    default:
      content = JSON.stringify(schema, null, 2);
  }

  return { target, content, filenameSuggestion: filename, safetyNotes: SAFETY_NOTES };
}
