(() => {
  const climates = ['oceanic','temperate','arid','tundra'];
  const climateColors = {oceanic:'#17658c',temperate:'#2c8158',arid:'#9b7237',tundra:'#8da8b7'};
  let seed = 20260704 >>> 0;
  const rnd = () => { seed ^= seed << 13; seed ^= seed >>> 17; seed ^= seed << 5; return (seed >>> 0) / 4294967296; };
  const state = {day:0,timeScale:1,tiles:[],agents:[],knowledge:512,crystals:[],background:false};
  const native = window.AetherEarthNative || null;
  const canvas = document.getElementById('world'); const ctx = canvas.getContext('2d');
  for(let y=0;y<16;y++) for(let x=0;x<16;x++){const lat=Math.abs(y/15*2-1);let c=lat>.78?'tundra':rnd()<.24?'arid':rnd()>.75?'oceanic':'temperate';state.tiles.push({x,y,c,b:.2+rnd()*.7});}
  for(let i=0;i<100;i++)state.agents.push({id:`life:${String(i+1).padStart(3,'0')}`,x:(rnd()*16)|0,y:(rnd()*16)|0,e:55+rnd()*40,k:0,g:1,a:['Forager','Scholar','Cooperator','Explorer'][i%4],action:'rest'});
  function browserAdvance(days){for(let d=0;d<days;d++){state.day++;for(const t of state.tiles)t.b=Math.min(1,t.b+.004);for(const a of state.agents){const t=state.tiles[a.y*16+a.x];a.e-=.7;if(a.e<48&&t.b>.04){a.action='forage';const gain=Math.min(7,t.b*10);a.e=Math.min(100,a.e+gain);t.b=Math.max(0,t.b-gain/45);if(rnd()<.07){a.k++;state.knowledge++;}}else if(rnd()<.18){a.action='move';a.x=(a.x+((rnd()*3)|0)-1+16)%16;a.y=(a.y+((rnd()*3)|0)-1+16)%16;}else if(rnd()<.07){a.action='experiment';a.k++;state.knowledge++;}else a.action='rest';if(a.e<=0){a.g++;a.e=70+rnd()*20;a.k=Math.max(0,a.k-2);}}if(state.day%60===0){const c={id:`crystal-${state.crystals.length+1}`,strategy:'prefer_temperate_biomass',confidence:Math.min(.99,.68+state.day/10000),support:24+((rnd()*60)|0),promoted:true};state.crystals.push(c);}}render();}
  function nativeState(){try{return native?JSON.parse(native.getState()):null}catch(e){console.error(e);return null}}
  function syncFromNative(){const n=nativeState();if(!n)return;Object.assign(state,n);render();}
  function advance(days){if(native){native.advance(days);syncFromNative()}else browserAdvance(days);}
  function draw(){const s=canvas.width/16;ctx.clearRect(0,0,canvas.width,canvas.height);for(const t of state.tiles){ctx.fillStyle=climateColors[t.c||t.climate]||'#315';ctx.globalAlpha=.42+.58*(t.b??t.biomass??.5);ctx.fillRect(t.x*s,t.y*s,s+1,s+1)}ctx.globalAlpha=1;for(const a of state.agents){ctx.beginPath();ctx.fillStyle=a.action==='experiment'?'#ffd36b':a.action==='forage'?'#76e4c4':'#f1f6ff';ctx.arc((a.x+.5)*s,(a.y+.5)*s,Math.max(2,s*.13),0,Math.PI*2);ctx.fill();}}
  function render(){draw();document.getElementById('dayLabel').textContent=`Day ${state.day}`;document.getElementById('knowledgeCount').textContent=state.knowledge||512;document.getElementById('crystalCount').textContent=state.crystals.length;const avgE=state.agents.reduce((x,a)=>x+(a.e??a.energy),0)/state.agents.length;const avgK=state.agents.reduce((x,a)=>x+(a.k??(a.knowledge?.length||0)),0)/state.agents.length;document.getElementById('metrics').innerHTML=[['生物',state.agents.length],['平均能量',avgE.toFixed(1)],['知识密度',avgK.toFixed(1)],['时间倍率',`${state.timeScale}×`]].map(([k,v])=>`<div class="metric"><small>${k}</small><b>${v}</b></div>`).join('');document.getElementById('crystals').className=`list${state.crystals.length?'':' empty'}`;document.getElementById('crystals').innerHTML=state.crystals.length?state.crystals.slice(-8).reverse().map(c=>`<div class="item"><small>${c.id}</small><b>${c.strategy}</b><p>支持 ${c.support} · 置信度 ${(c.confidence*100).toFixed(1)}% · ${c.promoted?'已晋升':'候选'}</p></div>`).join(''):'等待群体形成稳定模式……';document.getElementById('agents').innerHTML=state.agents.slice(0,100).map(a=>{const e=a.e??a.energy;const k=a.k??(a.knowledge?.length||0);return `<div class="agent"><header><b>${a.id}</b></header><p>${a.a||a.archetype||a.genome?.archetype||'Life'} · G${a.g||a.generation}</p><p>${a.action||a.lastAction} · K${k}</p><div class="bar"><i style="width:${Math.max(0,Math.min(100,e))}%"></i></div></div>`}).join('');}
  function renderKnowledge(q=''){const terms=[['temperate.biomass','supports','body.energy'],['oceanic.water','supports','life.stability'],['arid.moisture','constrains','biomass.growth'],['tundra.thermal','constrains','body.energy'],['collective.experiment','supports','knowledge.discovery']];document.getElementById('knowledge').innerHTML=terms.filter(x=>x.join(' ').includes(q.toLowerCase())).map((x,i)=>`<div class="item"><small>rclpedia:${String(i+1).padStart(4,'0')}</small><b>${x[0]} ${x[1]} ${x[2]}</b><p>证据可追踪 · 置信度 ${(82+i*2)}%</p></div>`).join('');}
  document.querySelectorAll('[data-days]').forEach(b=>b.onclick=()=>advance(Number(b.dataset.days)));document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{state.timeScale=Number(b.dataset.speed);if(native)native.setTimeScale(state.timeScale);document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===b));render();});document.getElementById('search').oninput=e=>renderKnowledge(e.target.value);document.getElementById('backgroundButton').onclick=()=>{state.background=!state.background;if(native){state.background?native.startBackground():native.stopBackground();syncFromNative()}document.getElementById('backgroundButton').textContent=state.background?'停止后台世界':'后台持续世界'};document.getElementById('exportButton').onclick=()=>{if(native){native.exportSnapshot();return}const blob=new Blob([JSON.stringify(state)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`aether-earth-day-${state.day}.json`;a.click();};
  if(native){document.getElementById('runtimeMode').textContent='Android 原生宿主';syncFromNative();setInterval(syncFromNative,3000)}else{document.getElementById('runtimeMode').textContent='浏览器沙盒';render()}renderKnowledge();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
