import { semanticHash, type VSRDisplayItem, type VSRDisplayState, type VSRMatrix3, type VSRPaint, type VSRRect } from '../../spec/src/index.js';
import type { VSRBitmapFont, VSRFontResourceMap, VSRImageBitmap, VSRImageResourceMap, VSRRasterResources } from '../../backend-canvas/src/index.js';
import { tessellatePath } from '../../path-tessellation/src/index.js';

export const VSR_WEBGPU_BACKEND_VERSION = '0.3.0-alpha.1';
export interface VSRWebGPUCapabilityReport { format:'vsr.webgpu-capability-report.v0.1'; available:boolean; secureContext:boolean; reason?:string }
export interface VSRWebGPUUnsupportedItem { nodeId:string; type:string; reason:string }
export interface VSRWebGPUScissorRect { x:number; y:number; width:number; height:number }
export type VSRWebGPUBlendMode = 'normal'|'additive';
export interface VSRWebGPUPlanStats {
  items:number; primitives:number; vertices:number; unsupported:number; bytes:number;
  triangles?:number; textures?:number; glyphs?:number; pathTriangles?:number;
  clippedItems?:number; shadowPrimitives?:number; additiveCommands?:number;
}
export interface VSRWebGPUTexturePlan { id:string; kind:'white'|'font-atlas'|'image'; width:number; height:number; data:Uint8Array; textureHash:string; glyphs?:Record<string,{u0:number;v0:number;u1:number;v1:number}> }
export interface VSRWebGPUDrawCommand {
  nodeId:string; pipeline:'solid'|'textured'; textureId:string; sampling:'linear'|'nearest';
  blendMode:VSRWebGPUBlendMode; firstVertex:number; vertexCount:number; order:number; scissor?:VSRWebGPUScissorRect;
}
export interface VSRWebGPUPlan {
  format:'vsr.webgpu-plan.v0.1'; backendVersion:string; documentId:string; sourceDisplayHash:string;
  viewport:{width:number;height:number;dpr:number}; clearColor:[number,number,number,number]; vertexStrideFloats:number;
  vertexData:Float32Array; unsupported:VSRWebGPUUnsupportedItem[]; stats:VSRWebGPUPlanStats;
  commands:VSRWebGPUDrawCommand[]; textures:VSRWebGPUTexturePlan[]; vertexHash:string; planHash:string;
}
export type VSRWebGPUResourceInput = VSRRasterResources | {images?:VSRImageResourceMap;fonts?:VSRFontResourceMap};

const STRIDE=11;
type RGBA=[number,number,number,number];
function parseColor(value:string):RGBA {const h=value.trim().match(/^#([0-9a-f]{3,8})$/i);if(!h)return[1,0,1,1];const x=h[1]!;if(x.length===3||x.length===4)return[parseInt(x[0]!+x[0]!,16)/255,parseInt(x[1]!+x[1]!,16)/255,parseInt(x[2]!+x[2]!,16)/255,(x.length===4?parseInt(x[3]!+x[3]!,16):255)/255];if(x.length===6||x.length===8)return[parseInt(x.slice(0,2),16)/255,parseInt(x.slice(2,4),16)/255,parseInt(x.slice(4,6),16)/255,(x.length===8?parseInt(x.slice(6,8),16):255)/255];return[1,0,1,1];}
function solid(paint:VSRPaint|undefined):RGBA|undefined{return paint?.type==='solid'?parseColor(paint.color):undefined;}
function worldPoint(m:VSRMatrix3,x:number,y:number):[number,number]{return[m[0]*x+m[1]*y+m[2],m[3]*x+m[4]*y+m[5]];}
function clipPoint(x:number,y:number,width:number,height:number):[number,number]{return[x/width*2-1,1-y/height*2];}
function pushVertex(target:number[],position:[number,number],uv:[number,number],color:RGBA,shape:number,radiusX:number,radiusY:number):void{target.push(position[0],position[1],uv[0],uv[1],color[0],color[1],color[2],color[3],shape,radiusX,radiusY);}
function pushQuad(target:number[],corners:Array<[number,number]>,color:RGBA,shape:number,radiusX=0,radiusY=0,uvRect:[number,number,number,number]=[0,0,1,1]):void {const [u0,v0,u1,v1]=uvRect,uv:Array<[number,number]>=[[u0,v0],[u1,v0],[u1,v1],[u0,v0],[u1,v1],[u0,v1]],order=[0,1,2,0,2,3];for(let i=0;i<6;i++)pushVertex(target,corners[order[i]!]!,uv[i]!,color,shape,radiusX,radiusY);}
function applyOpacity(color:RGBA,item:VSRDisplayItem):RGBA{return[color[0],color[1],color[2],color[3]*Math.max(0,Math.min(1,item.opacity))];}
function fastBytesHash(data:Uint8Array,prefix='gpu32'):string{let a=0x811c9dc5,b=0x9e3779b9;for(const value of data){a=Math.imul(a^value,0x01000193)>>>0;b=Math.imul((b+value)>>>0,0x85ebca6b)>>>0;b=(b^(b>>>13))>>>0;}return`${prefix}:${(a>>>0).toString(16).padStart(8,'0')}${(b>>>0).toString(16).padStart(8,'0')}`;}
function fastVertexHash(data:Float32Array):string{return fastBytesHash(new Uint8Array(data.buffer,data.byteOffset,data.byteLength));}
function normalizedResources(input?:VSRWebGPUResourceInput):{images:VSRImageResourceMap;fonts:VSRFontResourceMap}{return{images:input?.images??new Map(),fonts:input?.fonts??new Map()};}
function nextPowerOfTwo(value:number):number{let result=1;while(result<value)result*=2;return result;}
const FONT_ATLAS_CACHE=new WeakMap<VSRBitmapFont,VSRWebGPUTexturePlan>();
const IMAGE_TEXTURE_CACHE=new WeakMap<VSRImageBitmap,VSRWebGPUTexturePlan>();
function buildFontAtlas(font:VSRBitmapFont):VSRWebGPUTexturePlan{
  const cached=FONT_ATLAS_CACHE.get(font);if(cached)return cached;const characters=Object.keys(font.glyphs).sort((a,b)=>(a.codePointAt(0)??0)-(b.codePointAt(0)??0));const count=Math.max(1,characters.length),columns=Math.ceil(Math.sqrt(count)),cellW=font.glyphWidth+2,cellH=font.glyphHeight+2,width=nextPowerOfTwo(columns*cellW),rows=Math.ceil(count/columns),height=nextPowerOfTwo(rows*cellH),data=new Uint8Array(width*height*4),glyphs:Record<string,{u0:number;v0:number;u1:number;v1:number}>={};
  characters.forEach((character,index)=>{const col=index%columns,row=Math.floor(index/columns),x=col*cellW+1,y=row*cellH+1,bitmap=font.glyphs[character]!;for(let gy=0;gy<font.glyphHeight;gy++)for(let gx=0;gx<font.glyphWidth;gx++){const dst=((y+gy)*width+x+gx)*4,alpha=bitmap[gy]?.[gx]==='1'?255:0;data[dst]=255;data[dst+1]=255;data[dst+2]=255;data[dst+3]=alpha;}glyphs[character]={u0:x/width,v0:y/height,u1:(x+font.glyphWidth)/width,v1:(y+font.glyphHeight)/height};});
  const result:VSRWebGPUTexturePlan={id:`font:${font.family}`,kind:'font-atlas',width,height,data,textureHash:fastBytesHash(data,'texture32'),glyphs};FONT_ATLAS_CACHE.set(font,result);return result;
}
function buildImageTexture(id:string,image:VSRImageBitmap):VSRWebGPUTexturePlan{const cached=IMAGE_TEXTURE_CACHE.get(image);if(cached)return cached.id===`image:${id}`?cached:{...cached,id:`image:${id}`};const result:VSRWebGPUTexturePlan={id:`image:${id}`,kind:'image',width:image.width,height:image.height,data:image.data,textureHash:fastBytesHash(image.data,'texture32')};IMAGE_TEXTURE_CACHE.set(image,result);return result;}
function resolvedBlendMode(item:VSRDisplayItem):VSRWebGPUBlendMode|undefined{const raw=String((item.appearance as unknown as Record<string,unknown>).blendMode??'normal');if(raw==='normal'||raw==='source-over')return'normal';if(raw==='add'||raw==='lighter'||raw==='plus-lighter')return'additive';return undefined;}
function genericAppearanceReason(item:VSRDisplayItem):string|undefined{const blend=resolvedBlendMode(item);if(!blend)return`blend-mode:${String((item.appearance as unknown as Record<string,unknown>).blendMode)}`;return undefined;}
function cornersForRect(item:VSRDisplayItem,state:VSRDisplayState,rect=item.localBounds,offsetX=0,offsetY=0):Array<[number,number]>{const m=item.worldTransform,w=state.viewport.width,h=state.viewport.height;return[worldPoint(m,rect.x,rect.y),worldPoint(m,rect.x+rect.width,rect.y),worldPoint(m,rect.x+rect.width,rect.y+rect.height),worldPoint(m,rect.x,rect.y+rect.height)].map(point=>clipPoint(point[0]+offsetX,point[1]+offsetY,w,h)) as Array<[number,number]>;}
function intersectRect(a:VSRRect,b:VSRRect):VSRRect{const x=Math.max(a.x,b.x),y=Math.max(a.y,b.y),right=Math.min(a.x+a.width,b.x+b.width),bottom=Math.min(a.y+a.height,b.y+b.height);return{x,y,width:Math.max(0,right-x),height:Math.max(0,bottom-y)};}
function commandScissor(item:VSRDisplayItem,state:VSRDisplayState):VSRWebGPUScissorRect|undefined{if(!item.clipStack?.length)return undefined;let result:VSRRect={x:0,y:0,width:state.viewport.width,height:state.viewport.height};for(const clip of item.clipStack)result=intersectRect(result,clip.worldBounds);return{x:result.x,y:result.y,width:result.width,height:result.height};}
function imageGeometry(rect:VSRRect,image:VSRImageBitmap,fit:string,crop?:VSRRect):{draw:VSRRect;uv:[number,number,number,number]}{
  let draw={...rect},source=crop?{...crop}:{x:0,y:0,width:image.width,height:image.height};const sourceAspect=source.width/source.height,targetAspect=rect.width/rect.height;
  if(fit==='contain'){if(sourceAspect>targetAspect){const height=rect.width/sourceAspect;draw={x:rect.x,y:rect.y+(rect.height-height)/2,width:rect.width,height};}else{const width=rect.height*sourceAspect;draw={x:rect.x+(rect.width-width)/2,y:rect.y,width,height:rect.height};}}
  else if(fit==='cover'){if(sourceAspect>targetAspect){const width=source.height*targetAspect;source={x:source.x+(source.width-width)/2,y:source.y,width,height:source.height};}else{const height=source.width/targetAspect;source={x:source.x,y:source.y+(source.height-height)/2,width:source.width,height};}}
  else if(fit==='none')draw={x:rect.x,y:rect.y,width:source.width,height:source.height};
  return{draw,uv:[source.x/image.width,source.y/image.height,(source.x+source.width)/image.width,(source.y+source.height)/image.height]};
}

export function compileWebGPUPlan(state:VSRDisplayState,resourceInput?:VSRWebGPUResourceInput):VSRWebGPUPlan {
  const resources=normalizedResources(resourceInput),vertices:number[]=[],unsupported:VSRWebGPUUnsupportedItem[]=[],commands:VSRWebGPUDrawCommand[]=[],textureMap=new Map<string,VSRWebGPUTexturePlan>();let supportedItems=0,glyphCount=0,pathTriangles=0,clippedItems=0,shadowPrimitives=0,additiveCommands=0;
  const addCommand=(item:VSRDisplayItem,pipeline:'solid'|'textured',textureId:string,start:number,sampling:'linear'|'nearest'='linear')=>{const blendMode=resolvedBlendMode(item)??'normal',scissor=commandScissor(item,state);commands.push({nodeId:item.nodeId,pipeline,textureId,sampling,blendMode,firstVertex:start,vertexCount:vertices.length/STRIDE-start,order:commands.length,scissor});supportedItems++;if(scissor)clippedItems++;if(blendMode==='additive')additiveCommands++;};
  for(const item of state.items){const generic=genericAppearanceReason(item);if(generic){unsupported.push({nodeId:item.nodeId,type:item.type,reason:generic});continue;}const appearance=item.appearance as unknown as Record<string,unknown>,r=item.localBounds,m=item.worldTransform,w=state.viewport.width,h=state.viewport.height,start=vertices.length/STRIDE,shadow=appearance.shadow as {color?:unknown;blur?:unknown;offsetX?:unknown;offsetY?:unknown}|undefined;
    if(shadow&&(item.type!=='rect'&&item.type!=='ellipse')){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'shadow-type-not-supported'});continue;}
    if(shadow&&Number(shadow.blur??0)>0){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'soft-shadow-not-supported'});continue;}
    if(item.type==='rect'||item.type==='ellipse'){
      if(appearance.stroke){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'stroke-not-supported'});continue;}const fill=solid(appearance.fill as VSRPaint|undefined);if(!fill){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'solid-fill-required'});continue;}const raw=(item.content as Record<string,unknown>).cornerRadius,radius=Array.isArray(raw)?Number(raw[0]??0):Number(raw??0),shape=item.type==='ellipse'?2:radius>0?1:0,rx=Math.max(0,radius/Math.max(1,Math.abs(r.width))),ry=Math.max(0,radius/Math.max(1,Math.abs(r.height)));
      if(shadow){const shadowColor=parseColor(String(shadow.color??'#00000080'));pushQuad(vertices,cornersForRect(item,state,r,Number(shadow.offsetX??0),Number(shadow.offsetY??0)),applyOpacity(shadowColor,item),shape,rx,ry);shadowPrimitives++;}
      pushQuad(vertices,cornersForRect(item,state),applyOpacity(fill,item),shape,rx,ry);addCommand(item,'solid','__white',start);continue;
    }
    if(item.type==='line'){
      if(Array.isArray(appearance.dash)&&appearance.dash.length){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'dashed-line'});continue;}const stroke=solid(appearance.stroke as VSRPaint|undefined)??solid(appearance.fill as VSRPaint|undefined);if(!stroke){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'solid-stroke-required'});continue;}const c=item.content as Record<string,unknown>,a=worldPoint(m,Number(c.x1??r.x),Number(c.y1??r.y)),b=worldPoint(m,Number(c.x2??r.x+r.width),Number(c.y2??r.y+r.height)),width=Math.max(1,Number(appearance.strokeWidth??1)),dx=b[0]-a[0],dy=b[1]-a[1],len=Math.max(1e-6,Math.hypot(dx,dy)),nx=-dy/len*width/2,ny=dx/len*width/2,corners=([[a[0]+nx,a[1]+ny],[b[0]+nx,b[1]+ny],[b[0]-nx,b[1]-ny],[a[0]-nx,a[1]-ny]] as Array<[number,number]>).map(point=>clipPoint(point[0],point[1],w,h));pushQuad(vertices,corners,applyOpacity(stroke,item),0);addCommand(item,'solid','__white',start);continue;
    }
    if(item.type==='path'){
      const pathContent=item.content as Record<string,unknown>;if(pathContent.fillRule==='evenodd'){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'path-evenodd-not-supported'});continue;}if(appearance.stroke){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'path-stroke-not-supported'});continue;}const fill=solid(appearance.fill as VSRPaint|undefined);if(!fill){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'solid-fill-required'});continue;}const result=tessellatePath(String(pathContent.d??''),m);if(!result.triangles.length||result.diagnostics.length){unsupported.push({nodeId:item.nodeId,type:item.type,reason:result.diagnostics[0]??'path-tessellation-empty'});continue;}const color=applyOpacity(fill,item);for(const point of result.triangles)pushVertex(vertices,clipPoint(point.x,point.y,w,h),[0,0],color,0,0,0);pathTriangles+=result.triangleCount;addCommand(item,'solid','__white',start);continue;
    }
    if(item.type==='text'){
      const content=item.content as Record<string,unknown>;if(content.wrap&&content.wrap!=='none'){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'text-wrap-not-supported'});continue;}if(content.overflow==='ellipsis'){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'text-ellipsis-not-supported'});continue;}if(content.fontWeight&&content.fontWeight!=='normal'&&content.fontWeight!==400){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'bitmap-font-weight-not-supported'});continue;}const family=String(content.fontFamily??''),font=resources.fonts.get(family);if(!font){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'bitmap-font-required'});continue;}const fill=solid(appearance.fill as VSRPaint|undefined)??[1,1,1,1],textureId=`font:${font.family}`;let texture=textureMap.get(textureId);if(!texture){texture=buildFontAtlas(font);textureMap.set(textureId,texture);}const text=String(content.text??''),fontSize=Number(content.fontSize??24),scale=Math.max(1,fontSize/font.glyphHeight),advance=(font.advance??font.glyphWidth+1)*scale+Number(content.letterSpacing??0),total=text.length*advance;let x=r.x;if(content.align==='center')x+=Math.max(0,(r.width-total)/2);else if(content.align==='right')x+=Math.max(0,r.width-total);let y=r.y;if(content.verticalAlign==='middle')y+=Math.max(0,(r.height-font.glyphHeight*scale)/2);else if(content.verticalAlign==='bottom')y+=Math.max(0,r.height-font.glyphHeight*scale);const fallback=texture.glyphs?.['?'];for(const character of text){const uv=texture.glyphs?.[character]??fallback;if(uv){const glyphRect={x,y,width:font.glyphWidth*scale,height:font.glyphHeight*scale};pushQuad(vertices,cornersForRect(item,state,glyphRect),applyOpacity(fill,item),3,0,0,[uv.u0,uv.v0,uv.u1,uv.v1]);glyphCount++;}x+=advance;if(x>r.x+r.width)break;}if(vertices.length/STRIDE===start){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'font-glyph-missing'});continue;}addCommand(item,'textured',textureId,start,'nearest');continue;
    }
    if(item.type==='image'){
      const content=item.content as Record<string,unknown>,assetId=String(content.assetId??''),image=resources.images.get(assetId);if(!image){unsupported.push({nodeId:item.nodeId,type:item.type,reason:'image-resource-required'});continue;}const textureId=`image:${assetId}`;if(!textureMap.has(textureId))textureMap.set(textureId,buildImageTexture(assetId,image));const geometry=imageGeometry(r,image,String(content.fit??'fill'),content.crop as unknown as VSRRect|undefined);pushQuad(vertices,cornersForRect(item,state,geometry.draw),[1,1,1,item.opacity],4,0,0,geometry.uv);addCommand(item,'textured',textureId,start,content.smoothing===false?'nearest':'linear');continue;
    }
    unsupported.push({nodeId:item.nodeId,type:item.type,reason:item.type});
  }
  const vertexData=Float32Array.from(vertices),vertexHash=fastVertexHash(vertexData),textures=[...textureMap.values()],clear=solid(state.background)??[0,0,0,0];const stats:VSRWebGPUPlanStats={items:state.items.length,primitives:supportedItems,vertices:vertexData.length/STRIDE,unsupported:unsupported.length,bytes:vertexData.byteLength,triangles:vertexData.length/(STRIDE*3),textures:textures.length,glyphs:glyphCount,pathTriangles,clippedItems,shadowPrimitives,additiveCommands};
  const base={format:'vsr.webgpu-plan.v0.1' as const,backendVersion:VSR_WEBGPU_BACKEND_VERSION,documentId:state.documentId,sourceDisplayHash:state.semanticHash,viewport:{...state.viewport},clearColor:clear,vertexStrideFloats:STRIDE,unsupported,stats,commands,textures:textures.map(({data,...texture})=>texture),vertexHash};
  return{...base,vertexData,textures,planHash:semanticHash(base)};
}

export function subsetWebGPUPlan(plan:VSRWebGPUPlan,nodeIds:Iterable<string>,sourceDisplayHash=plan.sourceDisplayHash,clearColor:RGBA=[0,0,0,0]):VSRWebGPUPlan {
  const selected=new Set(nodeIds),vertices:number[]=[],commands:VSRWebGPUDrawCommand[]=[],usedTextures=new Set<string>();for(const command of plan.commands){if(!selected.has(command.nodeId))continue;const start=vertices.length/STRIDE,from=command.firstVertex*STRIDE,to=(command.firstVertex+command.vertexCount)*STRIDE;for(let index=from;index<to;index++)vertices.push(plan.vertexData[index]!);commands.push({...command,firstVertex:start,order:commands.length});if(command.textureId!=='__white')usedTextures.add(command.textureId);}
  const vertexData=Float32Array.from(vertices),textures=plan.textures.filter(texture=>usedTextures.has(texture.id)),vertexHash=fastVertexHash(vertexData),stats:VSRWebGPUPlanStats={items:selected.size,primitives:commands.length,vertices:vertexData.length/STRIDE,unsupported:0,bytes:vertexData.byteLength,triangles:vertexData.length/(STRIDE*3),textures:textures.length,clippedItems:commands.filter(command=>command.scissor).length,additiveCommands:commands.filter(command=>command.blendMode==='additive').length};const base={format:'vsr.webgpu-plan.v0.1' as const,backendVersion:plan.backendVersion,documentId:plan.documentId,sourceDisplayHash,viewport:{...plan.viewport},clearColor,vertexStrideFloats:STRIDE,unsupported:[] as VSRWebGPUUnsupportedItem[],stats,commands,textures:textures.map(({data,...texture})=>texture),vertexHash};return{...base,vertexData,textures,planHash:semanticHash(base)};
}

export function probeWebGPU():VSRWebGPUCapabilityReport {const nav=(typeof navigator==='undefined'?{}:navigator) as Navigator&{gpu?:unknown};const secure=typeof window==='undefined'||window.isSecureContext;return nav.gpu?{format:'vsr.webgpu-capability-report.v0.1',available:true,secureContext:secure}:{format:'vsr.webgpu-capability-report.v0.1',available:false,secureContext:secure,reason:'navigator.gpu unavailable'};}
const SHADER=`
struct VertexOut { @builtin(position) position: vec4f, @location(0) uv: vec2f, @location(1) color: vec4f, @location(2) params: vec3f };
@group(0) @binding(0) var texSampler: sampler;
@group(0) @binding(1) var tex: texture_2d<f32>;
@vertex fn vs_main(@location(0) position: vec2f,@location(1) uv: vec2f,@location(2) color: vec4f,@location(3) params: vec3f)->VertexOut{var out:VertexOut;out.position=vec4f(position,0.0,1.0);out.uv=uv;out.color=color;out.params=params;return out;}
@fragment fn fs_main(in:VertexOut)->@location(0) vec4f{let shape=in.params.x;if(shape>3.5){return textureSample(tex,texSampler,in.uv)*in.color;}if(shape>2.5){let sample=textureSample(tex,texSampler,in.uv);return vec4f(in.color.rgb,in.color.a*sample.a);}if(shape>1.5){let p=in.uv*2.0-vec2f(1.0);if(dot(p,p)>1.0){discard;}}else if(shape>0.5){let r=max(in.params.y,in.params.z);let q=abs(in.uv*2.0-vec2f(1.0))-(vec2f(1.0)-vec2f(r*2.0));if(length(max(q,vec2f(0.0)))>r*2.0){discard;}}return in.color;}`;
function paddedTextureData(texture:VSRWebGPUTexturePlan):{data:Uint8Array;bytesPerRow:number}{const row=texture.width*4,padded=Math.ceil(row/256)*256;if(padded===row)return{data:texture.data,bytesPerRow:row};const data=new Uint8Array(padded*texture.height);for(let y=0;y<texture.height;y++)data.set(texture.data.subarray(y*row,(y+1)*row),y*padded);return{data,bytesPerRow:padded};}
function blendState(mode:VSRWebGPUBlendMode):Record<string,unknown>{return mode==='additive'?{color:{srcFactor:'src-alpha',dstFactor:'one',operation:'add'},alpha:{srcFactor:'one',dstFactor:'one',operation:'add'}}:{color:{srcFactor:'src-alpha',dstFactor:'one-minus-src-alpha',operation:'add'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha',operation:'add'}};}
export async function renderDisplayStateWebGPU(state:VSRDisplayState,canvas:HTMLCanvasElement,resources?:VSRWebGPUResourceInput):Promise<VSRWebGPUPlan>{
  const plan=compileWebGPUPlan(state,resources);if(plan.unsupported.length)throw new Error(`WebGPU 计划含 ${plan.unsupported.length} 个不支持节点，必须使用混合后端。`);const nav=navigator as Navigator&{gpu?:{requestAdapter:()=>Promise<any>;getPreferredCanvasFormat:()=>string}};if(!nav.gpu)throw new Error('当前环境不支持 WebGPU。');const adapter=await nav.gpu.requestAdapter();if(!adapter)throw new Error('无法取得 WebGPU adapter。');const device=await adapter.requestDevice(),context=canvas.getContext('webgpu') as any;if(!context)throw new Error('无法取得 webgpu canvas context。');const format=nav.gpu.getPreferredCanvasFormat();canvas.width=Math.round(state.viewport.width*state.viewport.dpr);canvas.height=Math.round(state.viewport.height*state.viewport.dpr);context.configure({device,format,alphaMode:'premultiplied'});const module=device.createShaderModule({code:SHADER}),pipelineDescriptor=(mode:VSRWebGPUBlendMode)=>({layout:'auto',vertex:{module,entryPoint:'vs_main',buffers:[{arrayStride:STRIDE*4,attributes:[{shaderLocation:0,offset:0,format:'float32x2'},{shaderLocation:1,offset:8,format:'float32x2'},{shaderLocation:2,offset:16,format:'float32x4'},{shaderLocation:3,offset:32,format:'float32x3'}]}]},fragment:{module,entryPoint:'fs_main',targets:[{format,blend:blendState(mode)}]},primitive:{topology:'triangle-list'}}),pipelines:{normal:any;additive:any}={normal:device.createRenderPipeline(pipelineDescriptor('normal')),additive:device.createRenderPipeline(pipelineDescriptor('additive'))},buffer=device.createBuffer({size:Math.max(4,plan.vertexData.byteLength),usage:0x20|0x08,mappedAtCreation:true});new Float32Array(buffer.getMappedRange()).set(plan.vertexData);buffer.unmap();
  const samplers={linear:device.createSampler({magFilter:'linear',minFilter:'linear'}),nearest:device.createSampler({magFilter:'nearest',minFilter:'nearest'})},texturePlans=[{id:'__white',kind:'white' as const,width:1,height:1,data:new Uint8Array([255,255,255,255]),textureHash:'white'},...plan.textures],bindGroups=new Map<string,any>();for(const texturePlan of texturePlans){const texture=device.createTexture({size:[texturePlan.width,texturePlan.height,1],format:'rgba8unorm',usage:0x04|0x02}),upload=paddedTextureData(texturePlan);device.queue.writeTexture({texture},{data:upload.data,bytesPerRow:upload.bytesPerRow,rowsPerImage:texturePlan.height},{width:texturePlan.width,height:texturePlan.height,depthOrArrayLayers:1});for(const sampling of ['linear','nearest'] as const)bindGroups.set(`${texturePlan.id}:${sampling}`,device.createBindGroup({layout:pipelines.normal.getBindGroupLayout(0),entries:[{binding:0,resource:samplers[sampling]},{binding:1,resource:texture.createView()}]}));}
  const encoder=device.createCommandEncoder(),pass=encoder.beginRenderPass({colorAttachments:[{view:context.getCurrentTexture().createView(),clearValue:{r:plan.clearColor[0],g:plan.clearColor[1],b:plan.clearColor[2],a:plan.clearColor[3]},loadOp:'clear',storeOp:'store'}]});pass.setVertexBuffer(0,buffer);let activeBlend:VSRWebGPUBlendMode|undefined;for(const command of plan.commands){if(activeBlend!==command.blendMode){activeBlend=command.blendMode;pass.setPipeline(pipelines[activeBlend]);}const scissor=command.scissor,dpr=state.viewport.dpr;if(scissor){const x=Math.max(0,Math.floor(scissor.x*dpr)),y=Math.max(0,Math.floor(scissor.y*dpr)),right=Math.min(canvas.width,Math.ceil((scissor.x+scissor.width)*dpr)),bottom=Math.min(canvas.height,Math.ceil((scissor.y+scissor.height)*dpr));pass.setScissorRect(x,y,Math.max(0,right-x),Math.max(0,bottom-y));}else pass.setScissorRect(0,0,canvas.width,canvas.height);pass.setBindGroup(0,bindGroups.get(`${command.textureId}:${command.sampling}`)??bindGroups.get(`__white:${command.sampling}`));pass.draw(command.vertexCount,1,command.firstVertex,0);}pass.end();device.queue.submit([encoder.finish()]);return plan;
}
