export const CHAT_MESSAGE_TYPES = [
  "USER_MESSAGE",
  "ASSISTANT_TEXT",
  "ANSWER_CARD",
  "ANALYSIS_CARD",
  "ASK_TO_DO_CARD",
  "ROUTE_RESULT",
  "CAPABILITY_REQUIRED",
  "CAPABILITY_INSTALL_REQUIRED",
  "CAPABILITY_DOWNLOAD_REQUIRED",
  "RUNTIME_RUN_RESULT",
  "OBJECT_CREATED",
  "PAGE_NAVIGATION",
  "QA_RESULT",
  "CONFIRMATION_REQUIRED",
  "ERROR_BLOCKED",
  "SYSTEM_NOTICE",
  "WEBCODEM_RESULT",
  "DISPLAY_RESULT",
] as const;

export type ChatMessageType = (typeof CHAT_MESSAGE_TYPES)[number];
