export type WebLcmConceptSource =
  | "USER_INPUT" | "SEQUENCE_AI_OUTPUT" | "APP_PROJECT_OBJECT" | "CODE_RUN_LOG"
  | "ERROR_SUMMARY_OBJECT" | "PATCH_DRAFT_OBJECT" | "WORLD_OBJECT" | "NPC_OBJECT"
  | "QUEST_EVENT_OBJECT" | "SONG_OBJECT" | "LYRIC_OBJECT" | "STORY_OBJECT"
  | "CALCULUS_ENTRY" | "CONSTANT_ENTRY" | "VOCABULARY_TERM" | "PRODUCT_ENTRY"
  | "AGENT_BINDING_PROFILE" | "DIGITAL_ROLE_OUTPUT" | "WORKSPACE_OBJECT"
  | "SYSTEM_CONSTITUTION_RULE" | "QA_REPORT";

export const WEB_LCM_CONCEPT_SOURCES: WebLcmConceptSource[] = [
  "USER_INPUT","SEQUENCE_AI_OUTPUT","APP_PROJECT_OBJECT","CODE_RUN_LOG",
  "ERROR_SUMMARY_OBJECT","PATCH_DRAFT_OBJECT","WORLD_OBJECT","NPC_OBJECT",
  "QUEST_EVENT_OBJECT","SONG_OBJECT","LYRIC_OBJECT","STORY_OBJECT",
  "CALCULUS_ENTRY","CONSTANT_ENTRY","VOCABULARY_TERM","PRODUCT_ENTRY",
  "AGENT_BINDING_PROFILE","DIGITAL_ROLE_OUTPUT","WORKSPACE_OBJECT",
  "SYSTEM_CONSTITUTION_RULE","QA_REPORT",
];
