export type WebLcmRelationType =
  | "CAUSES" | "SUPPORTS" | "CONTRADICTS" | "REFINES" | "EXPANDS" | "COMPRESSES"
  | "TRANSLATES_TO" | "MAPS_TO" | "DERIVES_FROM" | "BLOCKS" | "REQUIRES"
  | "PRODUCES" | "GOVERNED_BY" | "BELONGS_TO" | "SIMILAR_TO" | "OPPOSITE_OF";

export const WEB_LCM_RELATION_TYPES: WebLcmRelationType[] = [
  "CAUSES","SUPPORTS","CONTRADICTS","REFINES","EXPANDS","COMPRESSES",
  "TRANSLATES_TO","MAPS_TO","DERIVES_FROM","BLOCKS","REQUIRES",
  "PRODUCES","GOVERNED_BY","BELONGS_TO","SIMILAR_TO","OPPOSITE_OF",
];
