#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import {generateAssetWorkspace,regenerateAssetWorkspace,verifyWorkspace,inspectWorkspace} from './runtime.mjs';import {planIncrementalRegeneration} from './lineage.mjs';import {builtinProviders,providerSummary} from './providers.mjs';import {startServer} from './server.mjs';import {AssetProductionSession} from './production-session.mjs';import {generateSocietyGenesisWorkspace,verifySocietyGenesisWorkspace,inspectSocietyGenesisWorkspace} from './society-genesis.mjs';
const args=process.argv.slice(2),cmd=args.shift(),arg=n=>{const i=args.indexOf(n);return i>=0?args[i+1]:null};
try{
 if(cmd==='generate'){const p=arg('--intent'),out=arg('--out')??'outputs/generated';if(!p)throw new Error('--intent required');const ws=generateAssetWorkspace(JSON.parse(fs.readFileSync(p,'utf8')),{outDir:path.resolve(out)});console.log(JSON.stringify({ok:true,out:path.resolve(out),workspace_root:ws.workspace_root,recommended_candidate_id:ws.recommended_candidate_id,asset_id:ws.genome.identity.asset_id,kind:ws.genome.identity.kind},null,2));}
 else if(cmd==='verify'){const p=arg('--workspace');if(!p)throw new Error('--workspace required');const abs=path.resolve(p),r=verifyWorkspace(JSON.parse(fs.readFileSync(abs,'utf8')),{baseDir:path.dirname(abs),verifyFiles:args.includes('--files')});console.log(JSON.stringify(r,null,2));if(!r.valid)process.exitCode=1;}
 else if(cmd==='inspect'){const p=arg('--workspace');if(!p)throw new Error('--workspace required');console.log(JSON.stringify(inspectWorkspace(JSON.parse(fs.readFileSync(p,'utf8'))),null,2));}
 else if(cmd==='regenerate'){const w=arg('--workspace'),patchPath=arg('--patch'),out=arg('--out')??'outputs/regenerated';if(!w||!patchPath)throw new Error('--workspace and --patch required');const ws=regenerateAssetWorkspace(JSON.parse(fs.readFileSync(w,'utf8')),JSON.parse(fs.readFileSync(patchPath,'utf8')),{outDir:path.resolve(out)});console.log(JSON.stringify({ok:true,out:path.resolve(out),workspace_root:ws.workspace_root,asset_id:ws.genome.identity.asset_id,regeneration_receipt_root:ws.regeneration_receipt?.receipt_root},null,2));}
 else if(cmd==='plan-regeneration'){const w=arg('--workspace'),patchPath=arg('--patch');if(!w||!patchPath)throw new Error('--workspace and --patch required');console.log(JSON.stringify(planIncrementalRegeneration(JSON.parse(fs.readFileSync(w,'utf8')),JSON.parse(fs.readFileSync(patchPath,'utf8'))),null,2));}
 else if(cmd==='production-demo'){
  const intentPath=arg('--intent'),out=path.resolve(arg('--out')??'outputs/production-demo');if(!intentPath)throw new Error('--intent required');
  const session=new AssetProductionSession(JSON.parse(fs.readFileSync(intentPath,'utf8')),{rootDir:out});session.generate();
  const variant=arg('--variant');if(variant){const candidate=session.current().workspace.candidates.find(item=>item.variant===variant);if(!candidate)throw new Error(`variant not found: ${variant}`);session.select(candidate.candidate_id,{reason:'cli-variant-selection'});}
  const palette=arg('--palette');if(palette)session.regenerate({constraints:{palette:palette.split(',').map(value=>value.trim()).filter(Boolean)}},{label:'cli-palette-regeneration'});
  const artifacts=session.accept({reason:'cli-production-acceptance'});fs.mkdirSync(out,{recursive:true});
  for(const [name,value] of Object.entries(artifacts)){if(value!==null&&typeof value==='object')fs.writeFileSync(path.join(out,`${name.replaceAll('_','-')}.json`),JSON.stringify(value,null,2)+'\n');}
  fs.writeFileSync(path.join(out,'production-session.json'),JSON.stringify(session.inspect(),null,2)+'\n');
  console.log(JSON.stringify({ok:true,out,session_id:session.session_id,asset_id:artifacts.production_manifest.asset_id,candidate_id:artifacts.production_manifest.candidate_id,variant:artifacts.production_manifest.variant,manifest_root:artifacts.production_manifest.manifest_root,acceptance_root:artifacts.acceptance_receipt.receipt_root},null,2));
 }

 else if(cmd==='generate-society'){const p=arg('--intent'),out=arg('--out')??'outputs/society-genesis',interventionPath=arg('--interventions');if(!p)throw new Error('--intent required');const interventions=interventionPath?JSON.parse(fs.readFileSync(interventionPath,'utf8')):[];const ws=generateSocietyGenesisWorkspace(JSON.parse(fs.readFileSync(p,'utf8')),{outDir:path.resolve(out),interventions});console.log(JSON.stringify({ok:true,out:path.resolve(out),workspace_root:ws.workspace_root,world_id:ws.genome.identity.world_id,concepts:ws.technology_concept_space.concepts.length,adopted:ws.history.summary.technologies_adopted,llm_calls:ws.genome.simulation.llm_calls},null,2));}
 else if(cmd==='verify-society'){const p=arg('--workspace');if(!p)throw new Error('--workspace required');const abs=path.resolve(p),r=verifySocietyGenesisWorkspace(JSON.parse(fs.readFileSync(abs,'utf8')),{baseDir:path.dirname(abs),verifyFiles:args.includes('--files')});console.log(JSON.stringify(r,null,2));if(!r.valid)process.exitCode=1;}
 else if(cmd==='inspect-society'){const p=arg('--workspace');if(!p)throw new Error('--workspace required');console.log(JSON.stringify(inspectSocietyGenesisWorkspace(JSON.parse(fs.readFileSync(p,'utf8'))),null,2));}
 else if(cmd==='providers')console.log(JSON.stringify({format:'reality-asset.provider-catalog.v0.3',providers:builtinProviders().map(providerSummary)},null,2));
 else if(cmd==='serve')startServer({port:Number(arg('--port')??4188),host:arg('--host')??'127.0.0.1'});
 else{console.log('asset-genesis generate --intent <intent.json> --out <directory>\nasset-genesis verify --workspace <workspace.json> [--files]\nasset-genesis inspect --workspace <workspace.json>\nasset-genesis plan-regeneration --workspace <workspace.json> --patch <patch.json>\nasset-genesis regenerate --workspace <workspace.json> --patch <patch.json> --out <directory>\nasset-genesis generate-society --intent <intent.json> --out <directory> [--interventions <json>]\nasset-genesis verify-society --workspace <workspace.json> [--files]\nasset-genesis inspect-society --workspace <workspace.json>\nasset-genesis providers\nasset-genesis serve --port 4188');process.exitCode=2;}
}catch(e){console.error(e.stack||e.message);process.exitCode=1;}
