import {clone,rootHash,seal,stableId,GenesisError,clamp} from './canonical.mjs';

export const FORMATS={
 intent:'reality-asset.intent.v0.3',genome:'reality-asset.genome.v0.3',provider:'reality-asset.provider.v0.3',
 plan:'reality-asset.generation-plan.v0.3',candidate:'reality-asset.candidate.v0.3',
 validation:'reality-asset.validation.v0.3',workspace:'reality-asset.genesis-workspace.v0.3',
 continuity:'reality-asset.continuity-bundle.v0.3',delta:'rfe.asset-genesis-causal-delta.v0.3'
};
const OUTPUTS_2D=['concept-svg','sprite-sheet','sfx-wav','particle-preset','collision-shape'];
const OUTPUTS_3D=['concept-svg','sprite-sheet','mesh-glb','mesh-lod1-glb','mesh-lod2-glb','pbr-texture-pack','skeleton-rig','animation-clips','lod-manifest','sfx-wav','particle-preset','collision-shape','vsr-spatial-asset','rsr-embodiment-profile','retarget-profile','projection-manifest','dependency-graph','prefab-blueprint'];
export const defaultOutputs=kind=>String(kind).includes('3d')?[...OUTPUTS_3D]:[...OUTPUTS_2D];
const required=(obj,key,errors)=>{if(obj?.[key]===undefined||obj?.[key]===null||obj?.[key]==='')errors.push(`MISSING:${key}`);};
export function normalizeIntent(input={}){
 const description=String(input.description??input.goal??'').trim();if(!description)throw new GenesisError('INTENT_DESCRIPTION_REQUIRED');const assetKind=input.asset_kind??'character-2d';
 const intent={format:FORMATS.intent,version:'0.3.0',intent_id:input.intent_id??stableId('asset-intent',{description,subject:input.subject_id??'subject:owner',kind:assetKind}),subject_id:input.subject_id??'subject:owner',description,asset_kind:assetKind,world_context:input.world_context??{},functional_role:input.functional_role??'gameplay-entity',target_platforms:[...new Set(input.target_platforms??['desktop','mobile','web'])].sort(),required_outputs:[...new Set(input.required_outputs??defaultOutputs(assetKind))].sort(),constraints:{palette:input.constraints?.palette??['#1c4fa3','#f2f6ff','#9ddcff','#17305a'],style:input.constraints?.style??'stylized-readable',max_texture_size:input.constraints?.max_texture_size??512,max_sprite_frames:input.constraints?.max_sprite_frames??8,audio_seconds:input.constraints?.audio_seconds??1,max_particles:input.constraints?.max_particles??96,max_triangles:input.constraints?.max_triangles??(String(assetKind).includes('3d')?2400:0),pbr_texture_size:input.constraints?.pbr_texture_size??256,max_bones:input.constraints?.max_bones??64,animation_fps:input.constraints?.animation_fps??30,lod_ratios:clone(input.constraints?.lod_ratios??[1,.55,.25]),forbidden:[...(input.constraints?.forbidden??[])],semantic_requirements:[...(input.constraints?.semantic_requirements??[])],license_policy:input.constraints?.license_policy??'generated-or-cleared'},seed:String(input.seed??rootHash(description).slice(0,16)),extensions:clone(input.extensions??{})};return seal(intent,'intent_root');
}
export function validateIntent(intent){const errors=[];if(intent?.format!==FORMATS.intent)errors.push('FORMAT_INVALID');for(const k of ['intent_id','subject_id','description','asset_kind','seed','intent_root'])required(intent,k,errors);if(!Array.isArray(intent?.target_platforms)||!intent.target_platforms.length)errors.push('TARGET_PLATFORM_REQUIRED');if(!Array.isArray(intent?.required_outputs)||!intent.required_outputs.length)errors.push('OUTPUT_REQUIRED');const x=clone(intent),r=x.intent_root;delete x.intent_root;if(r!==rootHash(x))errors.push('INTENT_ROOT_MISMATCH');return{valid:!errors.length,errors};}
export function createGenome(intent,derived={}){const v=validateIntent(intent);if(!v.valid)throw new GenesisError('INTENT_INVALID',v.errors.join(','));const genome={format:FORMATS.genome,version:'0.3.0',genome_id:stableId('asset-genome',{intent:intent.intent_root,derived}),intent_root:intent.intent_root,identity:{asset_id:derived.asset_id??stableId('asset',{description:intent.description,kind:intent.asset_kind}),name:derived.name??'未命名资产',kind:intent.asset_kind,continuity_policy:'stable-identity'},semantics:{world_context:clone(intent.world_context),functional_role:intent.functional_role,tags:[...new Set(derived.tags??[])].sort(),element:derived.element??'neutral',faction:derived.faction??'unassigned'},visual:{style:intent.constraints.style,palette:clone(intent.constraints.palette),silhouette:derived.silhouette??'readable',motifs:derived.motifs??[],proportions:derived.proportions??{},material_language:derived.material_language??'pbr-stylized'},behavior:{animation_set:derived.animation_set??['idle','move','attack','hit','defeat'],affordances:derived.affordances??['selectable','collidable'],gameplay_signals:derived.gameplay_signals??[]},audio:{signature:derived.audio_signature??'semantic-impact',events:derived.audio_events??['spawn','move','attack','hit']},effects:{language:derived.effect_language??'event-readable',events:derived.effect_events??['spawn','attack','hit']},physical:{body_type:derived.body_type??'kinematic-character',collision_shape:derived.collision_shape??'capsule',mass_class:derived.mass_class??'light',embodiment_profile:derived.embodiment_profile??(String(intent.asset_kind).includes('3d')?'humanoid-lite':'planar')},budgets:{max_texture_size:intent.constraints.max_texture_size,max_sprite_frames:intent.constraints.max_sprite_frames,max_particles:intent.constraints.max_particles,audio_seconds:intent.constraints.audio_seconds,max_triangles:intent.constraints.max_triangles,pbr_texture_size:intent.constraints.pbr_texture_size,max_bones:intent.constraints.max_bones,animation_fps:intent.constraints.animation_fps,lod_ratios:clone(intent.constraints.lod_ratios),platforms:clone(intent.target_platforms)},provenance:{policy:intent.constraints.license_policy,source_kind:'generated',requires_provider_evidence:true},prohibitions:clone(intent.constraints.forbidden),required_outputs:clone(intent.required_outputs),seed:intent.seed};return seal(genome,'genome_root');}
export function validateGenome(g){const errors=[];if(g?.format!==FORMATS.genome)errors.push('FORMAT_INVALID');for(const k of ['genome_id','intent_root','identity','semantics','visual','behavior','budgets','genome_root'])required(g,k,errors);const x=clone(g),r=x.genome_root;delete x.genome_root;if(r!==rootHash(x))errors.push('GENOME_ROOT_MISMATCH');if(!Array.isArray(g?.visual?.palette)||g.visual.palette.length<2)errors.push('PALETTE_TOO_SMALL');if(clamp(g?.budgets?.max_texture_size,1,8192)!==g?.budgets?.max_texture_size)errors.push('TEXTURE_BUDGET_INVALID');if(String(g?.identity?.kind).includes('3d')&&g?.budgets?.max_triangles<12)errors.push('TRIANGLE_BUDGET_INVALID');if(g?.budgets?.max_bones>256)errors.push('BONE_BUDGET_INVALID');return{valid:!errors.length,errors};}
export function createProviderManifest(input){const manifest={format:FORMATS.provider,version:'0.3.0',provider_id:input.provider_id,name:input.name??input.provider_id,mode:input.mode??'builtin',capabilities:(input.capabilities??[]).map(x=>({capability_id:x.capability_id,outputs:[...new Set(x.outputs??[])].sort(),quality:clamp(x.quality??7000),cost:clamp(x.cost??1000),latency:clamp(x.latency??1000),platforms:[...new Set(x.platforms??['any'])].sort(),asset_kinds:[...new Set(x.asset_kinds??['any'])].sort(),deterministic:Boolean(x.deterministic??false)})).sort((a,b)=>a.capability_id.localeCompare(b.capability_id)),command:input.command??null,endpoint:input.endpoint??null,metadata:clone(input.metadata??{})};return seal(manifest,'provider_root');}
export function validateProvider(p){const errors=[];if(p?.format!==FORMATS.provider)errors.push('FORMAT_INVALID');if(!p?.provider_id)errors.push('PROVIDER_ID_REQUIRED');if(!Array.isArray(p?.capabilities)||!p.capabilities.length)errors.push('CAPABILITIES_REQUIRED');if(!['builtin','stdio','http'].includes(p?.mode))errors.push('PROVIDER_MODE_INVALID');const x=clone(p),r=x.provider_root;delete x.provider_root;if(r!==rootHash(x))errors.push('PROVIDER_ROOT_MISMATCH');return{valid:!errors.length,errors};}
