import {seal,rootHash,clamp} from './canonical.mjs';import {FORMATS} from './contracts.mjs';
function sealed(value,field){if(!value||typeof value!=='object'||typeof value[field]!=='string')return false;const copy=structuredClone(value),actual=copy[field];delete copy[field];return actual===rootHash(copy)}
export function validateRuntimeAdapters(artifacts,genome){
 const errors=[];if(!String(genome?.identity?.kind).includes('3d'))return{valid:true,errors:[]};
 const vsr=artifacts?.['vsr-spatial-asset']?.data,rsr=artifacts?.['rsr-embodiment-profile']?.data;
 if(vsr?.format!=='ragf.vsr-spatial-asset.v0.4')errors.push('VSR_ADAPTER_FORMAT_INVALID');
 if(vsr?.version!=='0.4.0')errors.push('VSR_ADAPTER_VERSION_INVALID');
 if(vsr?.asset_id!==genome.identity.asset_id)errors.push('VSR_ADAPTER_ASSET_ID_MISMATCH');
 if(vsr?.compatibility?.target_format!=='vsr.spatial-scene.v0.4')errors.push('VSR_ADAPTER_TARGET_INVALID');
 if(!sealed(vsr,'adapter_root'))errors.push('VSR_ADAPTER_ROOT_INVALID');
 if(!Array.isArray(vsr?.lods)||vsr.lods.length<1||vsr.lods.some(level=>!level.meshId||!level.mesh||!Number.isFinite(level.maxDistance)))errors.push('VSR_ADAPTER_LOD_BINDING_INVALID');
 if(vsr?.quality?.pbr_map_count!==4||vsr?.quality?.pbr_material_model!=='stylized-pbr-v0.4')errors.push('VSR_MATERIAL_QUALITY_INVALID');
 if((vsr?.quality?.morph_target_count??0)<1||(vsr?.quality?.triangle_counts?.[0]??0)<Math.min(900,Math.max(240,Math.floor((genome.budgets?.max_triangles??0)*.3))))errors.push('VSR_GEOMETRY_QUALITY_INVALID');
 if(rsr?.format!=='ragf.rsr-embodiment-profile.v0.4')errors.push('RSR_PROFILE_FORMAT_INVALID');
 if(rsr?.version!=='0.4.0')errors.push('RSR_PROFILE_VERSION_INVALID');
 if(rsr?.asset_id!==genome.identity.asset_id)errors.push('RSR_PROFILE_ASSET_ID_MISMATCH');
 if(rsr?.compatibility?.target_format!=='rsr.spatial-embodiment-world.v0.6')errors.push('RSR_PROFILE_TARGET_INVALID');
 if(!sealed(rsr,'profile_root'))errors.push('RSR_PROFILE_ROOT_INVALID');
 if(rsr?.body?.runtime_kind!=='dynamic'||rsr?.body?.shape_spec?.type!=='capsule')errors.push('RSR_PROFILE_PHYSICAL_BINDING_INVALID');
 if((rsr?.skeleton?.bones?.length??0)<8||(rsr?.collision?.fixtures?.length??0)<4)errors.push('RSR_EMBODIMENT_QUALITY_INVALID');
 return{valid:errors.length===0,errors};
}
function scoreTechnical(artifacts,genome){let score=10000;const issues=[];for(const output of new Set(genome.required_outputs))if(!artifacts[output]){score-=1800;issues.push({severity:'error',code:'OUTPUT_MISSING',output});}
 const sprite=artifacts['sprite-sheet']?.metadata;if(sprite?.frames?.length>genome.budgets.max_sprite_frames){score-=1000;issues.push({severity:'error',code:'SPRITE_FRAME_BUDGET_EXCEEDED'});}const particle=artifacts['particle-preset']?.data;if(particle?.budget?.max_particles>genome.budgets.max_particles){score-=900;issues.push({severity:'error',code:'PARTICLE_BUDGET_EXCEEDED'});}const audio=artifacts['sfx-wav']?.metadata;if(audio?.duration_seconds>genome.budgets.audio_seconds+.01){score-=900;issues.push({severity:'error',code:'AUDIO_BUDGET_EXCEEDED'});}const mesh=artifacts['mesh-glb']?.metadata;if(mesh){if(!mesh.glb_valid){score-=3000;issues.push({severity:'error',code:'GLB_INVALID'});}if(mesh.triangle_count>genome.budgets.max_triangles){score-=1600;issues.push({severity:'error',code:'TRIANGLE_BUDGET_EXCEEDED',actual:mesh.triangle_count,max:genome.budgets.max_triangles});}if(mesh.bone_count>genome.budgets.max_bones){score-=1200;issues.push({severity:'error',code:'BONE_BUDGET_EXCEEDED'});}}
 const lod0=mesh?.triangle_count,lod1=artifacts['mesh-lod1-glb']?.metadata?.triangle_count,lod2=artifacts['mesh-lod2-glb']?.metadata?.triangle_count;if(lod0&&!(lod0>lod1&&lod1>lod2)){score-=900;issues.push({severity:'error',code:'LOD_TRIANGLE_ORDER_INVALID'});}if(mesh&&String(genome.identity.kind).includes('3d')){const minimumTriangles=Math.min(900,Math.max(240,Math.floor(genome.budgets.max_triangles*.3)));if(mesh.triangle_count<minimumTriangles){score-=650;issues.push({severity:'warning',code:'GEOMETRY_DETAIL_LOW',actual:mesh.triangle_count,minimum:minimumTriangles});}if((mesh.morph_target_count??0)<1){score-=250;issues.push({severity:'warning',code:'MORPH_TARGET_MISSING'});}if((mesh.animation_count??0)<4){score-=300;issues.push({severity:'warning',code:'EMBEDDED_ANIMATION_SET_INCOMPLETE'});}}const pbr=artifacts['pbr-texture-pack']?.metadata;if(pbr?.size>genome.budgets.pbr_texture_size){score-=900;issues.push({severity:'error',code:'PBR_TEXTURE_BUDGET_EXCEEDED'});}if(pbr&&String(genome.identity.kind).includes('3d')&&(pbr.files?.length!==4||pbr.material_model!=='stylized-pbr-v0.4')){score-=500;issues.push({severity:'error',code:'PBR_QUALITY_BINDING_INCOMPLETE'});}return{score:clamp(score),issues};}
function scoreSemantic(artifacts,genome,variant){let score=7600;const issues=[];if(artifacts['concept-svg']?.text?.includes(genome.identity.name))score+=500;else issues.push({severity:'warning',code:'NAME_NOT_EMBEDDED'});if(artifacts['concept-svg']?.text?.includes(genome.semantics.element))score+=400;else issues.push({severity:'warning',code:'ELEMENT_NOT_EMBEDDED'});if(genome.visual.palette.every(c=>artifacts['concept-svg']?.text?.includes(c)))score+=450;else issues.push({severity:'warning',code:'PALETTE_PARTIAL'});if(artifacts['skeleton-rig']?.data?.profile===genome.physical.embodiment_profile||artifacts['skeleton-rig']?.data?.profile==='humanoid-rounded-v0.4')score+=350;if(artifacts['projection-manifest']?.data?.invariants?.identity===genome.identity.asset_id)score+=250;if(artifacts['prefab-blueprint']?.data?.identity?.stable)score+=200;if(artifacts['animation-clips']?.data?.clips?.some(c=>c.name==='attack'&&c.events?.some(e=>e.type==='telegraph')))score+=350;if(variant==='mobile'&&(artifacts['sprite-sheet']?.metadata?.frames?.length??0)<=4)score+=200;return{score:clamp(score),issues};}
function scorePlatform(artifacts,genome,variant){let score=8000;const issues=[];if(variant==='mobile'){if((artifacts['particle-preset']?.data?.budget?.max_particles??999)<=32)score+=500;else{score-=1800;issues.push({severity:'error',code:'MOBILE_PARTICLE_BUDGET'});}if((artifacts['sprite-sheet']?.metadata?.frames?.length??999)<=4)score+=350;else{score-=1000;issues.push({severity:'warning',code:'MOBILE_FRAME_BUDGET'});}if((artifacts['mesh-glb']?.metadata?.triangle_count??0)<=1200)score+=500;else{score-=900;issues.push({severity:'warning',code:'MOBILE_TRIANGLE_BUDGET'});}if((artifacts['pbr-texture-pack']?.metadata?.size??0)<=128)score+=350;}else if(variant==='cinematic')score+=450;if(artifacts['vsr-spatial-asset']&&artifacts['rsr-embodiment-profile'])score+=350;return{score:clamp(score),issues};}
function scoreProduction(artifacts,genome,runtime){let score=6800;const issues=[];const roots=Object.values(artifacts).every(a=>typeof a.root==='string'&&a.root.length===64);if(roots)score+=700;else issues.push({severity:'error',code:'CONTENT_ADDRESSING_INCOMPLETE'});const evidence=Object.values(artifacts).every(a=>a.provenance?.provider_root&&a.provenance?.license);if(evidence)score+=700;else issues.push({severity:'warning',code:'PROVIDER_EVIDENCE_INCOMPLETE'});if(String(genome.identity.kind).includes('3d')){for(const role of ['mesh-glb','pbr-texture-pack','skeleton-rig','animation-clips','lod-manifest','retarget-profile','projection-manifest','dependency-graph','prefab-blueprint'])if(artifacts[role])score+=180;else issues.push({severity:'error',code:'PRODUCTION_3D_ROLE_MISSING',role});if(runtime.valid)score+=350;else issues.push(...runtime.errors.map(code=>({severity:'error',code})));}return{score:clamp(score),issues};}
export function validateCandidate(candidate,genome){const technical=scoreTechnical(candidate.artifacts,genome),semantic=scoreSemantic(candidate.artifacts,genome,candidate.variant),platform=scorePlatform(candidate.artifacts,genome,candidate.variant),runtime=validateRuntimeAdapters(candidate.artifacts,genome),production=scoreProduction(candidate.artifacts,genome,runtime),total=Math.round(technical.score*.32+semantic.score*.25+platform.score*.2+production.score*.23);return seal({format:FORMATS.validation,version:'0.3.0',candidate_id:candidate.candidate_id,candidate_root:candidate.candidate_root,genome_root:genome.genome_root,variant:candidate.variant,scores:{technical:technical.score,semantic:semantic.score,platform:platform.score,production:production.score,total},runtime_validation:runtime,issues:[...technical.issues,...semantic.issues,...platform.issues,...production.issues],eligible:technical.score>=7000&&semantic.score>=7000&&platform.score>=6500&&production.score>=6500,artifact_roots:Object.fromEntries(Object.entries(candidate.artifacts).map(([k,v])=>[k,v.root??rootHash(v)]))},'validation_root');}
export function compareCandidateReports(reports){const pref={balanced:300,mobile:220,cinematic:120},rows=reports.map(r=>({...r,rank_score:r.eligible?r.scores.total+(pref[r.variant]??0):-1})).sort((a,b)=>b.rank_score-a.rank_score||a.candidate_id.localeCompare(b.candidate_id)),eligible=rows.filter(r=>r.eligible),top=eligible.length?Math.max(...eligible.map(x=>x.scores.total)):0;return seal({format:'reality-asset.candidate-comparison.v0.3',version:'0.3.0',rows,pareto_frontier:eligible.filter(r=>r.scores.total>=top-300).map(r=>r.candidate_id),recommended_candidate_id:eligible[0]?.candidate_id??null},'comparison_root');}
