import { VSRRuntimeSession } from '/dist/packages/core/src/index.js';
import { validateDocument, documentHash } from '/dist/packages/spec/src/index.js';
import { VSRHistory } from '/dist/packages/agent-protocol/src/index.js';
import { drawDisplayStateToCanvas } from '/dist/packages/backend-canvas/src/browser.js';
import { compileWebGPUPlan, probeWebGPU } from '/dist/packages/backend-webgpu/src/index.js';
import { compileHybridRenderPlan } from '/dist/packages/backend-hybrid/src/index.js';
import { compileRealityStudioVSRBridge, createRealityStudioPatchFromVSRDocument, RealityStudioLiveVSRSession } from '/dist/packages/adapter-reality-studio/src/index.js';
import { compileRealityOneUnifiedV02Projection, RealityOneHttpGatewayTransport, RealityOneVSRGatewayBridge, RealityOneVSRSession, createRealityOneObserverProfile } from '/dist/packages/adapter-reality-one/src/index.js';
import { createDeviceProfile } from '/dist/packages/device-projection/src/index.js';
import { VSRSharedRealityCoordinator, VSRSharedRealityReplica } from '/dist/packages/shared-coordination/src/index.js';
import { replaySimulation } from '/dist/packages/simulation-core/src/index.js';
import { simulateBranchSet, selectSimulationBranch as createSimulationBranchSelection } from '/dist/packages/simulation-branch/src/index.js';
import { createVSRHNACSnapshot, exportVSRHNACBundle } from '/dist/packages/adapter-hnac-state/src/index.js';

const $=id=>document.getElementById(id);let doc=null,session=null,selectedId=null,time=0,playing=false,lastTick=0,idCounter=1,realitySession=null,realityEvents=[],realityIndex=0,realityTimer=null,currentObserverKind='owner',currentDeviceKind='desktop',lastObserverProjection=null,lastDeviceProjection=null,lastInteractionReceipt=null,sharedCoordinator=null,sharedReplica=null,sharedUnsubscribe=null,lastSharedResult=null,lastDisplayState=null,simulationConfig=null,simulationBase=null,simulationSet=null,simulationSelection=null,simulationRun=0,currentRealityStudioProject=null,studioLiveSession=null,studioLiveEvents=[],studioLiveIndex=0;const history=new VSRHistory();
const stage=$('stage'),diagnostics=[];
function blankDoc(){return{specVersion:'0.1',metadata:{id:'untitled-vsr',title:'未命名 VSR 文档',duration:5,defaultFps:30,seed:1},canvas:{width:960,height:540,layoutMode:'responsive',background:{type:'solid',color:'#0b1220'}},variables:{},nodes:[]}}
function simulationBranchDocument(set){const width=960,height=540,margin=20,gap=14,branches=set.branches.slice(0,3),cardWidth=(width-margin*2-gap*(branches.length-1))/Math.max(1,branches.length),nodes=[{id:'sim-title',type:'text',layout:{x:24,y:18,width:900,height:34},appearance:{fill:{type:'solid',color:'#f8fafc'}},content:{text:'现实模拟分支比较',fontSize:26}},{id:'sim-root',type:'text',layout:{x:24,y:56,width:900,height:18},appearance:{fill:{type:'solid',color:'#94a3b8'}},content:{text:`set ${set.setRoot.slice(0,22)}… · base ${set.baseSimulationRoot.slice(0,22)}…`,fontSize:11}}];branches.forEach((branch,index)=>{const x=margin+index*(cardWidth+gap),color=['#2563eb','#7c3aed','#059669'][index]||'#ea580c';nodes.push({id:`sim-card-${branch.branchId}`,type:'rect',layout:{x,y:88,width:cardWidth,height:420},appearance:{fill:{type:'solid',color:'#111827'},stroke:{type:'solid',color},strokeWidth:2},content:{cornerRadius:12}},{id:`sim-label-${branch.branchId}`,type:'text',layout:{x:x+14,y:104,width:cardWidth-28,height:24},appearance:{fill:{type:'solid',color:'#f8fafc'}},content:{text:branch.label,fontSize:17}},{id:`sim-info-${branch.branchId}`,type:'text',layout:{x:x+14,y:134,width:cardWidth-28,height:46},appearance:{fill:{type:'solid',color:'#cbd5e1'}},content:{text:`tick ${branch.baseTick}→${branch.finalTick} · risk ${branch.metrics.riskScore}\nchanged ${branch.metrics.changedBodyCount} · contacts ${branch.metrics.finalContactCount}`,fontSize:11}});const bodies=branch.finalSnapshot.bodies;const minX=Math.min(...bodies.map(b=>b.position.x-b.halfSize.x)),maxX=Math.max(...bodies.map(b=>b.position.x+b.halfSize.x)),minY=Math.min(...bodies.map(b=>b.position.y-b.halfSize.y)),maxY=Math.max(...bodies.map(b=>b.position.y+b.halfSize.y)),scale=Math.min((cardWidth-32)/Math.max(1,maxX-minX),240/Math.max(1,maxY-minY))*.9;bodies.forEach(body=>nodes.push({id:`sim-${branch.branchId}-${body.id}`,type:'rect',layout:{x:x+16+(body.position.x-body.halfSize.x-minX)*scale,y:190+(body.position.y-body.halfSize.y-minY)*scale,width:Math.max(4,body.halfSize.x*2*scale),height:Math.max(4,body.halfSize.y*2*scale)},appearance:{fill:{type:'solid',color:body.kind==='static'?'#334155':color},stroke:{type:'solid',color:'#e2e8f0'},strokeWidth:1},content:{cornerRadius:body.kind==='static'?2:4}}));nodes.push({id:`sim-evidence-${branch.branchId}`,type:'text',layout:{x:x+14,y:458,width:cardWidth-28,height:34},appearance:{fill:{type:'solid',color:'#64748b'}},content:{text:`${branch.branchRoot.slice(0,18)}…\n${branch.causalDelta.deltaRoot.slice(0,18)}…`,fontSize:9}})});return{specVersion:'0.1',runtimeTarget:'vsr-simulation-branch-studio-v0.1',metadata:{id:`simulation-${set.setRoot.slice(0,12)}`,title:'现实模拟分支比较',duration:10,defaultFps:60,seed:8},canvas:{width,height,background:{type:'solid',color:'#020617'}},variables:{setRoot:set.setRoot,branchCount:set.branchCount},nodes,extensions:{'rsr:branch-set':{setRoot:set.setRoot,provisional:true}}}}
function renderSimulationStatus(extra={}){if(!$('simulationOutput'))return;if(!simulationSet){$('simulationOutput').textContent='尚未运行现实模拟分支。';return}$('simulationOutput').textContent=JSON.stringify({baseRoot:simulationSet.baseSimulationRoot,setRoot:simulationSet.setRoot,branches:simulationSet.branches.map(branch=>({id:branch.branchId,label:branch.label,risk:branch.metrics.riskScore,finalRoot:branch.finalSnapshot.stateRoot,deltaRoot:branch.causalDelta.deltaRoot})),selection:simulationSelection,...extra},null,2)}
async function loadSimulationDemo(){try{simulationConfig=await fetch('/examples/simulation-assets/falling-box.world.json',{cache:'no-store'}).then(r=>r.json());simulationBase=replaySimulation(simulationConfig,30);simulationRun=0;rerunSimulationBranches()}catch(e){addDiagnostic(`模拟演示失败：${e.message}`);setStatus('模拟演示失败',true)}}
function rerunSimulationBranches(){if(!simulationConfig||!simulationBase){loadSimulationDemo();return}try{simulationRun++;const tick=simulationBase.tick,boost=180000+simulationRun*20000,root='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';const plans=[{format:'vsr.simulation-branch-plan.v0.1',branchId:'baseline',label:'自然演化',createdBy:'studio:planner',logicalTime:simulationRun,baseRealityRoot:root,steps:90,commands:[]},{format:'vsr.simulation-branch-plan.v0.1',branchId:'impulse-right',label:'右向冲量',createdBy:'studio:planner',logicalTime:simulationRun,baseRealityRoot:root,steps:90,commands:[{id:`impulse-${simulationRun}`,tick:tick+10,type:'apply-impulse',bodyId:'falling-box',impulse:{x:boost,y:-120000}}]},{format:'vsr.simulation-branch-plan.v0.1',branchId:'brake',label:'提前制动',createdBy:'studio:planner',logicalTime:simulationRun,baseRealityRoot:root,steps:90,commands:[{id:`brake-${simulationRun}`,tick:tick+20,type:'set-velocity',bodyId:'falling-box',velocity:{x:0,y:0}}]}];simulationSet=simulateBranchSet(simulationBase,plans);simulationSelection=null;doc=simulationBranchDocument(simulationSet);selectedId=null;time=0;history.clear();rebuildSession();renderSimulationStatus({run:simulationRun});setStatus(`模拟分支已生成：${simulationSet.branchCount} 条`)}catch(e){addDiagnostic(`模拟分支失败：${e.message}`);setStatus('模拟分支失败',true)}}
function chooseSimulationBranch(){if(!simulationSet){loadSimulationDemo();return}const selected=[...simulationSet.branches].sort((a,b)=>a.metrics.riskScore-b.metrics.riskScore||a.branchId.localeCompare(b.branchId))[0];simulationSelection=createSimulationBranchSelection(simulationSet,selected.branchId,'studio:planner',simulationRun,'选择当前最低风险分支');renderSimulationStatus({selected:selected.branchId});setStatus(`已选择模拟分支：${selected.label}`)}
function setStatus(text,error=false){$('runtimeStatus').textContent=text;$('runtimeStatus').style.color=error?'#ff8f9a':'#7ee3ac'}
function addDiagnostic(text){diagnostics.push(text);$('diagnosticsOutput').textContent=diagnostics.join('\n')||'无诊断。'}
function resetSharedSession(){if(sharedUnsubscribe){sharedUnsubscribe();sharedUnsubscribe=null}sharedCoordinator=null;sharedReplica=null;lastSharedResult=null;if($('sharedOutput'))$('sharedOutput').textContent='尚未建立共享现实会话。'}
function renderSharedStatus(extra={}){if(!sharedCoordinator||!sharedReplica){$('sharedOutput').textContent='尚未建立共享现实会话。';return}const snapshot=sharedCoordinator.snapshot();$('sharedOutput').textContent=JSON.stringify({sessionId:snapshot.sessionId,coordinator:{sequence:snapshot.sequence,eventRoot:snapshot.eventRoot,stateHash:snapshot.stateHash,variables:snapshot.variables,revoked:snapshot.revoked},replica:{cursor:sharedReplica.cursor(),variables:sharedReplica.state(),revoked:sharedReplica.revocationState()},lastResult:lastSharedResult,...extra},null,2)}
function startSharedSession(){try{resetSharedSession();const sessionId=`studio:${doc.metadata.id}`;const initial=session?.getVariables?session.getVariables():(doc.variables||{});sharedCoordinator=new VSRSharedRealityCoordinator({sessionId,documentHash:documentHash(doc),initialVariables:initial});sharedReplica=new VSRSharedRealityReplica({replicaId:'studio:offline-replica',sessionId,documentHash:documentHash(doc),initialVariables:initial});sharedUnsubscribe=sharedCoordinator.subscribe(event=>renderSharedStatus({broadcast:{sequence:event.sequence,type:event.type,eventHash:event.eventHash}}));renderSharedStatus();setStatus('共享会话已建立')}catch(e){addDiagnostic(`共享会话失败：${e.message}`);setStatus('共享会话失败',true)}}
function syncSharedReplica(){if(!sharedCoordinator||!sharedReplica){startSharedSession();return}try{const batch=sharedCoordinator.eventsAfter(sharedReplica.cursor());sharedReplica.applyBatch(batch);renderSharedStatus({sync:{events:batch.events.length,toSequence:batch.toSequence}});setStatus(`副本已同步 ${batch.events.length} 个事件`)}catch(e){addDiagnostic(`副本同步失败：${e.message}`);setStatus('副本同步失败',true)}}
function revokeSharedAuthority(){if(!sharedCoordinator){startSharedSession();return}try{const event=sharedCoordinator.revoke({format:'vsr.shared-revocation-request.v0.1',revocationId:`studio-revoke-${Date.now()}`,sessionId:sharedCoordinator.sessionId,targetKind:'authority',targetId:'studio:subject-owner',revokedBy:'studio:root-authority',logicalTime:time,previousEventRoot:sharedCoordinator.cursor().eventRoot,reason:'Studio 主动撤权'});lastSharedResult={status:'revoked',eventHash:event.eventHash};renderSharedStatus();setStatus('撤权事件已广播')}catch(e){addDiagnostic(`共享撤权失败：${e.message}`);setStatus('共享撤权失败',true)}}
function stopRealityTimer(){if(realityTimer){clearInterval(realityTimer);realityTimer=null;$('autoRealityReplay').textContent='自动回放'}}
function leaveRealityMode(){stopRealityTimer();resetSharedSession();if(realitySession){realitySession.dispose();realitySession=null}realityEvents=[];realityIndex=0;lastObserverProjection=null;lastDeviceProjection=null;lastInteractionReceipt=null;$('liveOutput').textContent='尚未载入实时会话。'}
function rebuildSession(){try{if(realitySession)leaveRealityMode();else session?.dispose();session=new VSRRuntimeSession(doc,{width:doc.canvas.width,height:doc.canvas.height,dpr:1});$('timeSlider').max=String(doc.metadata.duration);$('durationLabel').textContent=`/ ${doc.metadata.duration.toFixed(3)}s`;$('documentTitle').textContent=`${doc.metadata.title} · ${documentHash(doc)}`;setStatus('已求值');render()}catch(e){setStatus('运行时错误',true);addDiagnostic(e.message)}}
function renderLivePanel(result){if(!realitySession)return;const summary=realitySession.currentSummary();const manifest=lastObserverProjection?.manifest;$('documentTitle').textContent=`${doc.metadata.title} · ${summary.status} · ${currentObserverKind}`;$('liveOutput').textContent=JSON.stringify({observer:currentObserverKind,device:currentDeviceKind,event:`${realityIndex}/${realityEvents.length}`,phase:summary.phase,status:summary.status,progress:summary.progress,authorityStatus:summary.authorityStatus,lastEventType:summary.lastEventType,eventChainRoot:realitySession.eventChainRoot(),stateHash:realitySession.stateHash(),sourceDisplayHash:manifest?.sourceDisplayHash??result?.semanticHash??null,projectedDisplayHash:manifest?.projectedDisplayHash??null,invariantHash:manifest?.invariantHash??null,deviceProjection:lastDeviceProjection?{deviceId:lastDeviceProjection.manifest.deviceId,projectedDisplayHash:lastDeviceProjection.manifest.projectedDisplayHash,equivalenceHash:lastDeviceProjection.manifest.equivalenceHash,scaleX:lastDeviceProjection.manifest.transform.scaleX,scaleY:lastDeviceProjection.manifest.transform.scaleY}:null,lastInteraction:lastInteractionReceipt?{status:lastInteractionReceipt.status,proposalHash:lastInteractionReceipt.proposalHash,commitHash:lastInteractionReceipt.commitHash}:null,disclosure:manifest?{shown:manifest.shownNodeIds.length,redacted:manifest.redactedNodeIds.length,hidden:manifest.hiddenNodeIds.length}:null},null,2)}
function render(){if(!doc||!session)return;try{session.clock.seek(time);let result,display;if(realitySession){const observer=createRealityOneObserverProfile(currentObserverKind);const devices=realitySession.evaluateForObserverAndDevices(observer,[createDeviceProfile(currentDeviceKind)],time);result=realitySession.evaluate(time);lastObserverProjection=devices.observerProjection;lastDeviceProjection=devices.devices[0];display=lastDeviceProjection.displayState}else{result=session.evaluate(time);display=result.displayState;lastObserverProjection=null;lastDeviceProjection=null}lastDisplayState=display;drawDisplayStateToCanvas(display,stage);$('timeSlider').value=String(time);$('timeInput').value=time.toFixed(3);const observerStats=lastObserverProjection?` · 观察者 ${currentObserverKind} / 设备 ${currentDeviceKind}：显示 ${lastObserverProjection.manifest.shownNodeIds.length} / 脱敏 ${lastObserverProjection.manifest.redactedNodeIds.length} / 隐藏 ${lastObserverProjection.manifest.hiddenNodeIds.length}`:'';$('runtimeStatus').textContent=`帧 ${display.frame} · ${result.evaluationStats.durationMs.toFixed(2)}ms · 求值重算 ${result.evaluationStats.resolvedNodeCount} / 复用 ${result.evaluationStats.reusedResolvedNodeCount} · 投影重算 ${result.evaluationStats.projectedNodeCount} / 跳过 ${result.evaluationStats.skippedProjectionNodeCount}${observerStats}`;renderTree();renderInspector();renderTimeline();$('jsonEditor').value=JSON.stringify(realitySession?realitySession.snapshotDocument():doc,null,2);renderLivePanel(result);if(display.diagnostics.length)$('diagnosticsOutput').textContent=display.diagnostics.map(d=>`[${d.severity}] ${d.code}: ${d.message}`).join('\n');}catch(e){setStatus('求值失败',true);addDiagnostic(e.message)}}
function renderTree(){$('nodeCount').textContent=`${doc.nodes.length} 节点`;$('sceneTree').innerHTML='';for(const node of doc.nodes){const el=document.createElement('div');el.className=`scene-item ${node.id===selectedId?'selected':''}`;el.innerHTML=`<span>${node.name||node.id}</span><small>${node.type}</small>`;el.onclick=()=>{selectedId=node.id;render()};$('sceneTree').append(el)}}
function selected(){return doc?.nodes.find(n=>n.id===selectedId)}
function renderInspector(){const n=selected();$('selectionTitle').textContent=n?`${n.name||n.id} · ${n.type}`:'未选择节点';for(const id of['propName','propX','propY','propWidth','propHeight','propOpacity'])$(id).disabled=!n;$('propFill').disabled=!n;if(!n)return;$('propName').value=n.name||'';$('propX').value=n.layout?.x??0;$('propY').value=n.layout?.y??0;$('propWidth').value=n.layout?.width??100;$('propHeight').value=n.layout?.height??100;$('propOpacity').value=n.appearance?.opacity??1;$('propFill').value=n.appearance?.fill?.type==='solid'?n.appearance.fill.color:'#4488ff'}
function renderTimeline(){$('timelineTracks').innerHTML='';for(const n of doc.nodes){for(const t of n.tracks||[]){const row=document.createElement('div');row.className='track-row';row.innerHTML=`<span>${n.id} / ${t.property}</span><div class="track-bar"></div>`;const bar=row.querySelector('.track-bar');for(const k of t.keyframes||[]){const dot=document.createElement('i');dot.className='key-dot';dot.style.left=`calc(${Math.min(1,k.time/doc.metadata.duration)*100}% - 5px)`;dot.title=`${k.time}s = ${JSON.stringify(k.value)}`;bar.append(dot)}$('timelineTracks').append(row)}}}
function commit(tx){const result=history.apply(doc,{...tx,baseDocumentHash:documentHash(doc)});if(!result.ok){addDiagnostic(`事务失败：${result.error}`);setStatus('事务失败',true);return false}doc=result.document;$('diffOutput').textContent=JSON.stringify(result.diff,null,2);rebuildSession();return true}
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function parseLength(v){const s=String(v).trim();if(s==='auto'||/%$|vw$|vh$/.test(s))return s;const n=Number(s);return Number.isFinite(n)?n:s}
async function loadRealityOneDemo(){try{if(realitySession)leaveRealityMode();else session?.dispose();const stream=await fetch('/examples/reality-one-lifecycle.events.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()});realityEvents=stream.events||[];realitySession=new RealityOneVSRSession({profile:innerWidth<720?'mobile':'desktop'});doc=realitySession.document;session=realitySession.runtime;selectedId=null;time=0;history.clear();$('timeSlider').max=String(doc.metadata.duration);$('durationLabel').textContent=`/ ${doc.metadata.duration.toFixed(3)}s`;realityIndex=0;currentObserverKind=$('observerProfile').value||'owner';currentDeviceKind=$('deviceProfile').value||'desktop';setStatus('实时会话已载入');render()}catch(e){addDiagnostic(`Reality One 演示加载失败：${e.message}`);setStatus('实时演示失败',true)}}
function nextRealityEvent(){if(!realitySession||!realityEvents.length){loadRealityOneDemo();return}if(realityIndex>=realityEvents.length){stopRealityTimer();setStatus('事件流已完成');return}try{const pending=realityEvents[realityIndex];if(pending?.type==='authority.resolved'&&realitySession.currentSummary().authorityStatus!=='pending'){realityIndex++;return nextRealityEvent()}realitySession.append(realityEvents[realityIndex++]);render();if(realityIndex>=realityEvents.length){stopRealityTimer();setStatus('事件流已完成')}else setStatus(`事件 ${realityIndex}/${realityEvents.length}`)}catch(e){stopRealityTimer();addDiagnostic(`事件应用失败：${e.message}`);setStatus('事件流错误',true)}}
function resetRealityReplay(){if(!realitySession)return;stopRealityTimer();realitySession.reset();realityIndex=0;render();setStatus('事件流已重置')}
function toggleRealityReplay(){if(!realitySession){loadRealityOneDemo();return}if(realityTimer){stopRealityTimer();setStatus('自动回放已暂停');return}$('autoRealityReplay').textContent='暂停回放';realityTimer=setInterval(nextRealityEvent,650);nextRealityEvent()}

function resolveRealityAuthority(approved){if(!realitySession){loadRealityOneDemo();return}try{const summary=realitySession.currentSummary();if(summary.authorityStatus!=='pending'||summary.phase!=='permission'){setStatus('当前不在权限确认阶段',true);return}const observer=createRealityOneObserverProfile(currentObserverKind);const device=createDeviceProfile(currentDeviceKind);const nodeId=approved?'authority-approve':'authority-deny';const proposal=realitySession.proposeInteraction({format:'vsr.input-event.v0.1',inputId:`studio-${nodeId}-${summary.sequence||0}`,trigger:'click',nodeId,logicalTime:0,observerId:observer.observerId,deviceId:device.deviceId},observer,device);const authorization={format:'vsr.interaction-authorization.v0.1',proposalHash:proposal.proposalHash,decision:'approved',authorityId:'studio:subject-owner',logicalTime:0,evidenceRoot:realitySession.eventChainRoot()};const committed=realitySession.commitInteraction(proposal,authorization);lastInteractionReceipt=committed.receipt;if(sharedCoordinator&&sharedReplica&&committed.receipt.status==='committed'){const cursor=sharedReplica.cursor();lastSharedResult=sharedCoordinator.submit({format:'vsr.shared-interaction-candidate.v0.1',candidateId:`studio:${proposal.proposalHash}`,sessionId:sharedCoordinator.sessionId,replicaId:'studio:primary',baseSequence:cursor.sequence,baseEventRoot:cursor.eventRoot,logicalTime:0,proposal,authorization,receipt:committed.receipt});renderSharedStatus()}render();setStatus(approved?'权限已通过交互提交':'拒绝已通过交互提交')}catch(e){addDiagnostic(`权限交互失败：${e.message}`);setStatus('交互提交失败',true)}}
$('newDoc').onclick=()=>{doc=blankDoc();selectedId=null;time=0;history.clear();rebuildSession()};
$('openDoc').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{doc=JSON.parse(await file.text());selectedId=null;time=0;history.clear();rebuildSession()}catch(err){addDiagnostic(`打开失败：${err.message}`)}};
$('saveDoc').onclick=()=>{const target=realitySession?realitySession.snapshotDocument():doc;download(`${target.metadata.id}.vsr.json`,new Blob([JSON.stringify(target,null,2)],{type:'application/json'}));};
$('loadExample').onclick=async()=>{try{doc=await fetch('/examples/hello-title.vsr.json',{cache:'no-store'}).then(r=>r.json());selectedId='title';time=0;history.clear();rebuildSession()}catch(e){addDiagnostic(`示例加载失败：${e.message}`)}};
$('validateDoc').onclick=()=>{const r=validateDocument(doc);$('diagnosticsOutput').textContent=r.diagnostics.length?r.diagnostics.map(d=>`[${d.severity}] ${d.code}: ${d.message}`).join('\n'):'校验通过：无诊断。';setStatus(r.ok?'校验通过':'校验失败',!r.ok)};
$('play').onclick=()=>{playing=true;lastTick=performance.now();setStatus('播放中')};$('pause').onclick=()=>{playing=false;setStatus('已暂停')};$('stop').onclick=()=>{playing=false;time=0;render();setStatus('已停止')};
$('prevFrame').onclick=()=>{time=Math.max(0,time-1/doc.metadata.defaultFps);render()};$('nextFrame').onclick=()=>{time=Math.min(doc.metadata.duration,time+1/doc.metadata.defaultFps);render()};
$('timeSlider').oninput=e=>{time=Number(e.target.value);render()};$('timeInput').onchange=e=>{time=Math.max(0,Math.min(doc.metadata.duration,Number(e.target.value)||0));render()};
$('addRect').onclick=()=>{const id=`rect-${idCounter++}`;commit({transactionId:`add-${id}`,operations:[{type:'addNode',node:{id,type:'rect',name:'新矩形',layout:{x:100+idCounter*8,y:100+idCounter*8,width:180,height:100},appearance:{fill:{type:'solid',color:'#318cff'},opacity:1},content:{cornerRadius:14}}}]});selectedId=id;render()};
$('duplicateNode').onclick=()=>{const n=selected();if(!n)return;const id=`${n.id}-copy-${idCounter++}`;if(commit({transactionId:`duplicate-${id}`,operations:[{type:'duplicateNode',nodeId:n.id,newNodeId:id}]})){selectedId=id;render()}};
$('deleteNode').onclick=()=>{const n=selected();if(!n)return;if(commit({transactionId:`delete-${n.id}`,operations:[{type:'removeNode',nodeId:n.id,cascade:true}]})){selectedId=null;render()}};
$('undo').onclick=()=>{const r=history.undo(doc);if(r?.ok){doc=r.document;rebuildSession()}};$('redo').onclick=()=>{const r=history.redo(doc);if(r?.ok){doc=r.document;rebuildSession()}};
$('applyProperties').onclick=()=>{const n=selected();if(!n)return;commit({transactionId:`props-${n.id}-${idCounter++}`,operations:[{type:'updateNode',nodeId:n.id,path:'name',value:$('propName').value},{type:'updateNode',nodeId:n.id,path:'layout.x',value:parseLength($('propX').value)},{type:'updateNode',nodeId:n.id,path:'layout.y',value:parseLength($('propY').value)},{type:'updateNode',nodeId:n.id,path:'layout.width',value:parseLength($('propWidth').value)},{type:'updateNode',nodeId:n.id,path:'layout.height',value:parseLength($('propHeight').value)},{type:'updateNode',nodeId:n.id,path:'appearance.opacity',value:Number($('propOpacity').value)},{type:'updateNode',nodeId:n.id,path:'appearance.fill',value:{type:'solid',color:$('propFill').value}}]})};
$('addKeyframe').onclick=()=>{const n=selected();if(!n)return;let t=n.tracks?.find(t=>t.property==='appearance.opacity');const operations=[];if(!t){t={id:`opacity-${n.id}`,property:'appearance.opacity',mode:'keyframes',keyframes:[]};operations.push({type:'addTrack',nodeId:n.id,track:t})}operations.push({type:'addKeyframe',nodeId:n.id,trackId:t.id,keyframe:{id:`kf-${idCounter++}`,time,value:n.appearance?.opacity??1,easing:'easeInOut'}});commit({transactionId:`keyframe-${n.id}-${idCounter}`,operations})};
$('removeKeyframe').onclick=()=>{const n=selected();const t=n?.tracks?.find(t=>t.property==='appearance.opacity'&&t.keyframes?.length);const k=t?.keyframes?.at(-1);if(n&&t&&k)commit({transactionId:`remove-kf-${k.id}`,operations:[{type:'removeKeyframe',nodeId:n.id,trackId:t.id,keyframeId:k.id}]})};
$('applyJson').onclick=()=>{try{const next=JSON.parse($('jsonEditor').value);commit({transactionId:`json-${idCounter++}`,operations:[{type:'replaceDocument',document:next}]})}catch(e){addDiagnostic(`JSON 失败：${e.message}`)}};
$('transactionEditor').value=JSON.stringify({transactionId:'agent-demo',operations:[{type:'setVariable',name:'headline',value:'AGENT UPDATED VSR'}]},null,2);
$('applyTransaction').onclick=()=>{try{commit(JSON.parse($('transactionEditor').value))}catch(e){addDiagnostic(`事务 JSON 失败：${e.message}`)}};
$('exportPng').onclick=()=>stage.toBlob(blob=>{if(blob){download(`${doc.metadata.id}-${time.toFixed(3)}.png`,blob);$('outputReport').textContent=`已导出当前帧：${time.toFixed(3)}s\n${stage.width} × ${stage.height}`}},'image/png');
$('analyzeGpuPlan').onclick=()=>{if(!lastDisplayState)return;const capability=probeWebGPU(),plan=compileWebGPUPlan(lastDisplayState);$('outputReport').textContent=JSON.stringify({capability,planHash:plan.planHash,stats:plan.stats,commands:plan.commands.slice(0,20),textures:plan.textures.map(({data,...texture})=>texture),unsupported:plan.unsupported.slice(0,20)},null,2);setStatus(plan.unsupported.length?`GPU 计划：${plan.stats.primitives} 图元，${plan.unsupported.length} 节点回退`:`GPU 计划可直接执行：${plan.stats.primitives} 图元`)};
$('analyzeHybridPlan').onclick=()=>{if(!lastDisplayState)return;const plan=compileHybridRenderPlan(lastDisplayState);$('outputReport').textContent=JSON.stringify({planHash:plan.planHash,stats:plan.stats,layers:plan.layers.map(layer=>({layerId:layer.layerId,kind:layer.kind,itemIds:layer.itemIds,layerHash:layer.layerHash,gpuPlanHash:layer.gpuPlan?.planHash}))},null,2);setStatus(`混合计划：${plan.stats.gpuLayers} GPU 层 + ${plan.stats.softwareLayers} 软件层，覆盖 ${(plan.stats.gpuCoverage*100).toFixed(1)}%`)};
$('renderRange').onclick=()=>{const fps=Math.min(doc.metadata.defaultFps,30),frames=[];for(let i=0;i<=Math.floor(doc.metadata.duration*fps);i++){const t=i/fps;frames.push({frame:i,time:t,semanticHash:session.evaluate(t).semanticHash})}download(`${doc.metadata.id}-range-manifest.json`,new Blob([JSON.stringify({documentHash:documentHash(doc),fps,frames},null,2)],{type:'application/json'}));$('outputReport').textContent=`浏览器已验证 ${frames.length} 个逻辑帧并导出语义清单。\n像素序列与视频请使用 CLI render-range / encode。`};

async function loadRealityStudioV04(){try{studioLiveSession?.dispose();currentRealityStudioProject=await fetch('/examples/reality-studio-reality-graph-v04.project.json',{cache:'no-store'}).then(response=>response.json());studioLiveSession=new RealityStudioLiveVSRSession(currentRealityStudioProject,'studio-live:browser');studioLiveEvents=[{format:'reality-studio.live-event.v0.4',sessionId:'studio-live:browser',projectId:currentRealityStudioProject.projectId,sequence:1,type:'blackboard.set',sceneId:'first-leap',payload:{key:'energy',value:3}},{format:'reality-studio.live-event.v0.4',sessionId:'studio-live:browser',projectId:currentRealityStudioProject.projectId,sequence:2,type:'signal.emitted',sceneId:'first-leap',payload:{signal:'core.collected',subject:'core-a',payload:{energy:3}}},{format:'reality-studio.live-event.v0.4',sessionId:'studio-live:browser',projectId:currentRealityStudioProject.projectId,sequence:3,type:'object.updated',sceneId:'first-leap',payload:{objectUid:'obj-0xnzhd9',set:{x:155,y:233}}}];studioLiveIndex=0;doc=studioLiveSession.currentDocument();selectedId='object:player';time=0;history.clear();rebuildSession();$('outputReport').textContent=JSON.stringify(studioLiveSession.manifest(),null,2);setStatus('Reality Studio v0.4 实时会话已载入')}catch(error){addDiagnostic(`Reality Studio v0.4 载入失败：${error.message}`);setStatus('Studio v0.4 实时会话失败',true)}}
function nextStudioLiveEvent(){if(!studioLiveSession){loadRealityStudioV04();return}if(studioLiveIndex>=studioLiveEvents.length){setStatus('Studio v0.4 编辑事件已完成');return}try{const manifest=studioLiveSession.append(studioLiveEvents[studioLiveIndex++]);currentRealityStudioProject=studioLiveSession.currentProject();doc=studioLiveSession.currentDocument();selectedId='object:player';rebuildSession();$('outputReport').textContent=JSON.stringify(manifest,null,2);setStatus(`Studio 实时事件 ${studioLiveIndex}/${studioLiveEvents.length}`)}catch(error){addDiagnostic(`Studio 实时事件失败：${error.message}`);setStatus('Studio 实时事件失败',true)}}
function exportCurrentHNACState(){try{if(!doc||!session)throw new Error('没有可导出的运行会话');const snapshot=createVSRHNACSnapshot(doc,session,{appId:`vsr:${doc.metadata.id}`,replicaId:'studio:browser',generation:0,devicePrivate:{viewport:{width:innerWidth,height:innerHeight}},ephemeral:{selectedId:selectedId??''}}),bundle=exportVSRHNACBundle(snapshot);download(`${doc.metadata.id}.hnac-state.json`,new Blob([JSON.stringify({snapshot,bundle},null,2)],{type:'application/json'}));$('outputReport').textContent=JSON.stringify({stateRoot:snapshot.state.state_root,snapshotRoot:snapshot.snapshotRoot,bundleRoot:bundle.bundle_root,omitted:bundle.omitted_partitions},null,2);setStatus('HNAC v0.5 可携带状态已导出')}catch(error){addDiagnostic(`HNAC 状态导出失败：${error.message}`);setStatus('HNAC 状态导出失败',true)}}
async function submitRealityGateway(){if(!realitySession){await loadRealityOneDemo();return}try{const summary=realitySession.currentSummary();if(summary.authorityStatus!=='pending'||summary.phase!=='permission'){setStatus('当前不在权限确认阶段',true);return}const observer=createRealityOneObserverProfile(currentObserverKind),device=createDeviceProfile(currentDeviceKind),proposal=realitySession.proposeInteraction({format:'vsr.input-event.v0.1',inputId:`gateway-approve-${summary.sequence||0}`,trigger:'click',nodeId:'authority-approve',logicalTime:0,observerId:observer.observerId,deviceId:device.deviceId},observer,device),authorization={format:'vsr.interaction-authorization.v0.1',proposalHash:proposal.proposalHash,decision:'approved',authorityId:'studio:subject-owner',grantedScopes:['*'],logicalTime:0,evidenceRoot:realitySession.eventChainRoot()},url=prompt('Reality One Gateway 地址','http://127.0.0.1:4173')||'http://127.0.0.1:4173',bridge=new RealityOneVSRGatewayBridge(realitySession,new RealityOneHttpGatewayTransport(url)),receipt=await bridge.submitAuthorityInteraction(proposal,authorization);lastInteractionReceipt={status:receipt.gatewayStatus,proposalHash:receipt.proposalHash,commitHash:receipt.interactionCommitHash};render();$('outputReport').textContent=JSON.stringify(receipt,null,2);setStatus(`Gateway 提交：${receipt.gatewayStatus}`,receipt.gatewayStatus==='failed'||receipt.gatewayStatus==='blocked')}catch(error){addDiagnostic(`Reality One Gateway 提交失败：${error.message}`);setStatus('Gateway 提交失败',true)}}
$('loadRealityStudioDemo').onclick=async()=>{try{currentRealityStudioProject=await fetch('/examples/reality-studio-first-leap.project.json',{cache:'no-store'}).then(response=>response.json());const bridge=compileRealityStudioVSRBridge(currentRealityStudioProject);doc=bridge.document;selectedId=doc.nodes.find(node=>node.tags?.includes('reality-studio-object'))?.id??null;time=0;history.clear();rebuildSession();$('outputReport').textContent=JSON.stringify({projectId:bridge.projectId,sourceFormat:bridge.sourceFormat,activeSceneId:bridge.activeSceneId,projectRoot:bridge.projectRoot,sceneRoot:bridge.sceneRoot,bridgeRoot:bridge.bridgeRoot,hybridStats:bridge.hybridPlan.stats,verification:bridge.verification},null,2);setStatus('Reality Studio v0.1 项目已编译为 VSR')}catch(error){addDiagnostic(`Reality Studio 项目载入失败：${error.message}`);setStatus('Reality Studio 编译失败',true)}};
$('loadRealityStudioV04').onclick=loadRealityStudioV04;$('nextStudioLiveEvent').onclick=nextStudioLiveEvent;$('exportHNACState').onclick=exportCurrentHNACState;$('submitRealityGateway').onclick=submitRealityGateway;$('loadRealityStudioV03').onclick=async()=>{try{currentRealityStudioProject=await fetch('/examples/reality-studio-component-v03.project.json',{cache:'no-store'}).then(response=>response.json());const bridge=compileRealityStudioVSRBridge(currentRealityStudioProject);doc=bridge.document;selectedId='object:core';time=.5;history.clear();rebuildSession();$('outputReport').textContent=JSON.stringify({projectId:bridge.projectId,sourceFormat:bridge.sourceFormat,activeSceneId:bridge.activeSceneId,componentContractHash:bridge.componentContractHash,sceneRoot:bridge.sceneRoot,bridgeRoot:bridge.bridgeRoot,hybridStats:bridge.hybridPlan.stats},null,2);setStatus('Reality Studio v0.3 组件项目已编译')}catch(error){addDiagnostic(`Reality Studio v0.3 载入失败：${error.message}`);setStatus('Studio v0.3 编译失败',true)}};
$('previewRealityStudioPatch').onclick=()=>{try{if(!currentRealityStudioProject)throw new Error('请先载入 Reality Studio 项目。');const patch=createRealityStudioPatchFromVSRDocument(currentRealityStudioProject,doc);$('outputReport').textContent=JSON.stringify(patch,null,2);setStatus(`已生成 ${patch.changes.length} 个对象回写变更`)}catch(error){addDiagnostic(`回写补丁失败：${error.message}`);setStatus('回写补丁失败',true)}};
$('loadRealityOneUnified').onclick=async()=>{try{const input=await fetch('/examples/reality-one-unified-result-v02.json',{cache:'no-store'}).then(response=>response.json()),projection=compileRealityOneUnifiedV02Projection(input,{profile:'desktop'});doc=projection.document;selectedId='domain:2:card';time=0;history.clear();rebuildSession();$('outputReport').textContent=JSON.stringify({sessionId:projection.sessionId,sourceRoot:projection.sourceRoot,domainRoots:projection.domainRoots,projectionRoot:projection.projectionRoot},null,2);setStatus('Reality One v0.2 六域结果已投影')}catch(error){addDiagnostic(`Reality One 六域投影失败：${error.message}`);setStatus('Reality One 六域投影失败',true)}};
$('loadSimulationDemo').onclick=loadSimulationDemo;$('rerunSimulationBranches').onclick=rerunSimulationBranches;$('selectSimulationBranch').onclick=chooseSimulationBranch;$('startSharedSession').onclick=startSharedSession;$('syncSharedReplica').onclick=syncSharedReplica;$('revokeSharedAuthority').onclick=revokeSharedAuthority;$('loadRealityDemo').onclick=loadRealityOneDemo;$('nextRealityEvent').onclick=nextRealityEvent;$('autoRealityReplay').onclick=toggleRealityReplay;$('resetRealityReplay').onclick=resetRealityReplay;$('observerProfile').onchange=e=>{currentObserverKind=e.target.value;render();setStatus(`已切换观察者：${currentObserverKind}`)};$('deviceProfile').onchange=e=>{currentDeviceKind=e.target.value;render();setStatus(`已切换设备：${currentDeviceKind}`)};$('approveRealityAuthority').onclick=()=>resolveRealityAuthority(true);$('denyRealityAuthority').onclick=()=>resolveRealityAuthority(false);$('exportRealitySnapshot').onclick=()=>{if(!realitySession)return;const snapshot=realitySession.snapshotDocument();download(`${snapshot.metadata.id}.vsr.json`,new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}));};
$('clearDiagnostics').onclick=()=>{diagnostics.length=0;$('diagnosticsOutput').textContent='无诊断。'};
for(const tab of document.querySelectorAll('.tab'))tab.onclick=()=>{document.querySelectorAll('.tab,.tab-body').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(tab.dataset.tab+'Tab').classList.add('active')};
function tick(now){if(playing&&doc){const dt=(now-lastTick)/1000;lastTick=now;time+=dt;if(time>=doc.metadata.duration){time=doc.metadata.duration;playing=false}render()}requestAnimationFrame(tick)}requestAnimationFrame(tick);
window.addEventListener('pointermove',e=>{if(session){const r=stage.getBoundingClientRect();session.setInput({pointerX:(e.clientX-r.left)/r.width*doc.canvas.width,pointerY:(e.clientY-r.top)/r.height*doc.canvas.height});if(playing)render()}});
doc=blankDoc();rebuildSession();
