export const WORLD_PERMISSIONS = [
  "VIEW_WORLD","RUN_TICK","CREATE_ZONE","CREATE_NPC","MUTATE_RULE","LOCK_CANON",
  "EXPORT_RUNTIME","DELETE_WORLD","FORK_TIMELINE","FOUNDER_DECREE",
] as const;
export type WorldPermission = typeof WORLD_PERMISSIONS[number];

export const ROLE_PERMISSIONS: Record<"BEGINNER"|"ADVANCED"|"FOUNDER", WorldPermission[]> = {
  BEGINNER: ["VIEW_WORLD","RUN_TICK"],
  ADVANCED: ["VIEW_WORLD","RUN_TICK","CREATE_ZONE","CREATE_NPC","MUTATE_RULE","EXPORT_RUNTIME","FORK_TIMELINE"],
  FOUNDER: [...["VIEW_WORLD","RUN_TICK","CREATE_ZONE","CREATE_NPC","MUTATE_RULE","LOCK_CANON","EXPORT_RUNTIME","DELETE_WORLD","FORK_TIMELINE","FOUNDER_DECREE"] as WorldPermission[]],
};
