export const WORLD_MUTATION_TYPES = [
  "QUEST_MUTATION","NPC_ROLE_MUTATION","ZONE_STATE_MUTATION","RESOURCE_MUTATION",
  "RULE_MUTATION","NARRATIVE_MUTATION","RELATION_MUTATION","TERMINAL_MUTATION",
] as const;
export type WorldMutationType = typeof WORLD_MUTATION_TYPES[number];
