// Text type taxonomy — see spec §2
export const TEXT_TYPES = [
  "PAGE_TITLE", "PAGE_SUBTITLE", "HERO_COPY", "MODULE_DESCRIPTION",
  "BUTTON_LABEL", "EMPTY_STATE", "QUICK_START_TEXT", "TOOLTIP",
  "SAFETY_NOTE", "PERMISSION_NOTE", "SUBJECT_MODE_NOTE", "DEMO_REAL_NOTE",
  "FOUNDER_NOTE", "FAQ_ANSWER", "TUTORIAL_SUMMARY", "GLOSSARY_DEFINITION",
  "AUDIT_EXPLANATION", "EXPORT_DESCRIPTION", "ERROR_MESSAGE", "SUCCESS_MESSAGE",
] as const;
export type TextType = (typeof TEXT_TYPES)[number];

export const TEXT_TYPE_LABELS: Record<TextType, string> = {
  PAGE_TITLE: "页面标题", PAGE_SUBTITLE: "页面副标题", HERO_COPY: "首屏文案",
  MODULE_DESCRIPTION: "模块说明", BUTTON_LABEL: "按钮文案", EMPTY_STATE: "空状态",
  QUICK_START_TEXT: "快速开始", TOOLTIP: "提示浮层", SAFETY_NOTE: "安全提示",
  PERMISSION_NOTE: "权限提示", SUBJECT_MODE_NOTE: "主体模式提示", DEMO_REAL_NOTE: "Demo/Real 提示",
  FOUNDER_NOTE: "Founder 提示", FAQ_ANSWER: "FAQ 回答", TUTORIAL_SUMMARY: "教程摘要",
  GLOSSARY_DEFINITION: "术语定义", AUDIT_EXPLANATION: "审计解释", EXPORT_DESCRIPTION: "导出说明",
  ERROR_MESSAGE: "错误提示", SUCCESS_MESSAGE: "成功提示",
};
