// Text trigger types — see spec §3
export const TEXT_TRIGGER_TYPES = [
  "ENGINE_ADDED", "ENGINE_UPDATED", "ROUTE_ADDED", "ROUTE_CHANGED",
  "UI_LAYOUT_CHANGED", "QUICK_START_CHANGED",
  "SUBJECT_MODE_CHANGED", "CONSTANT_UPDATED", "CONSTITUTION_UPDATED",
  "SAFETY_RULE_UPDATED", "PERMISSION_RULE_UPDATED",
  "WORLD_ENGINE_VERSION_UPDATED", "WEIGHT_CHANGED", "MODULE_PRIORITY_CHANGED",
  "USAGE_EXAMPLE_UPDATED", "DOCS_UPDATED", "AUDIT_RESULT_CHANGED",
  "LOCALIZATION_CHANGED",
] as const;
export type TextTriggerType = (typeof TEXT_TRIGGER_TYPES)[number];

export const TEXT_TRIGGER_LABELS: Record<TextTriggerType, string> = {
  ENGINE_ADDED: "新增引擎", ENGINE_UPDATED: "引擎升级",
  ROUTE_ADDED: "新增路由", ROUTE_CHANGED: "路由变化",
  UI_LAYOUT_CHANGED: "UI 布局变化", QUICK_START_CHANGED: "快速开始变化",
  SUBJECT_MODE_CHANGED: "主体模式变化", CONSTANT_UPDATED: "常数宇宙更新",
  CONSTITUTION_UPDATED: "系统宪法更新", SAFETY_RULE_UPDATED: "安全规则更新",
  PERMISSION_RULE_UPDATED: "权限规则更新", WORLD_ENGINE_VERSION_UPDATED: "世界引擎版本更新",
  WEIGHT_CHANGED: "权重变化", MODULE_PRIORITY_CHANGED: "模块优先级变化",
  USAGE_EXAMPLE_UPDATED: "使用示例更新", DOCS_UPDATED: "教程文档更新",
  AUDIT_RESULT_CHANGED: "审计结果变化", LOCALIZATION_CHANGED: "本地化语言更新",
};
