import {rootHash,seal} from '../canonical.mjs';

function meshPayload(mesh,id){return{id,positions:mesh.geometry.positions,normals:mesh.geometry.normals,uvs:mesh.geometry.uvs,indices:mesh.geometry.indices,jointIndices:mesh.geometry.joints,jointWeights:mesh.geometry.weights,morphTargets:(mesh.geometry.morphTargets??[]).map(target=>({id:target.id,positions:target.positions,defaultWeight:target.defaultWeight??0})),topology:'triangle-list'};}
function pbrRoot(pbr){return pbr?rootHash({metadata:pbr.metadata,files:pbr.files.map(file=>({name:file.name,root:file.root??rootHash(file.buffer.toString('base64'))}))}):null;}

export function generateVsrSpatialAsset({genome,variant,mesh,meshes=[mesh],lodManifest=null,pbr=null,rig=null,animations=null}){
  const assetId=genome.identity.asset_id,materialId=`material:${assetId}:${variant}`,meshEntries=meshes.filter(Boolean).map((entry,lod)=>({lod,meshId:`mesh:${assetId}:${variant}:lod${lod}`,maxDistance:lod===0?12:lod===1?36:72,mesh:meshPayload(entry,`mesh:${assetId}:${variant}:lod${lod}`),sourceRoot:entry.metadata?.glb_root??rootHash(entry.geometry)}));
  const fallback=meshEntries.at(-1)??{lod:0,meshId:`mesh:${assetId}:${variant}:lod0`,maxDistance:72,mesh:meshPayload(mesh,'mesh:'+assetId+':'+variant+':lod0'),sourceRoot:rootHash(mesh.geometry)};
  const nodeId=`node:${assetId}`,node={id:nodeId,meshId:fallback.meshId,materialId,castShadow:true,receiveShadow:true,tags:['ragf','asset:'+assetId,'variant:'+variant],lods:meshEntries.length>1?meshEntries.slice(0,-1).map(entry=>({maxDistance:entry.maxDistance,meshId:entry.meshId})):undefined};
  return seal({format:'ragf.vsr-spatial-asset.v0.4',version:'0.4.0',asset_id:assetId,variant,mesh:meshEntries[0]?.mesh??meshPayload(mesh,`mesh:${assetId}:${variant}:lod0`),lods:meshEntries,material:{id:materialId,baseColor:genome.visual.palette[0],metallic:variant==='cinematic'?.35:.15,roughness:variant==='mobile'?.7:.48,emissive:genome.visual.palette[2],emissiveStrength:variant==='cinematic'?.55:.25},node,quality:{profile:mesh.metadata?.quality_profile??'unknown',feature_level:mesh.metadata?.feature_level??0,triangle_counts:meshes.map(entry=>entry?.metadata?.triangle_count??0),pbr_map_count:pbr?.files?.length??0,pbr_material_model:pbr?.metadata?.material_model??null,embedded_texture_count:mesh.metadata?.embedded_texture_count??0,morph_target_count:mesh.metadata?.morph_target_count??0},runtime:{skin:{id:`skin:${assetId}:${variant}`,joints:(rig?.bones??[]).map(bone=>bone.name)},animation_clips:(animations?.clips??[]).map(clip=>({name:clip.name,duration:clip.duration,loop:clip.loop}))},source:{asset_id:assetId,mesh_roots:meshEntries.map(entry=>entry.sourceRoot),lod_manifest_root:lodManifest?.lod_root??null,pbr_root:pbrRoot(pbr)},compatibility:{target_format:'vsr.spatial-scene.v0.4',minimum_runtime:'0.8.0-alpha.1'},adapter_root:''},'adapter_root');
}

export function generateRsrEmbodimentProfile({genome,variant,rig,collision=null}){
  const assetId=genome.identity.asset_id,radius=variant==='mobile'?.276:.3,height=2.55,halfHeight=(height-radius*2)/2,mass=variant==='mobile'?48:55;
  return seal({format:'ragf.rsr-embodiment-profile.v0.4',version:'0.4.0',asset_id:assetId,variant,units:{distance:'meters',mass:'kilograms',fixed_point_scale:1000},body:{kind:'character',runtime_kind:'dynamic',shape:'capsule-3d',shape_spec:{type:'capsule',radius,height,halfHeight},radius,height,mass,center:[0,height/2,0],position:[0,height/2,0],material_id:`material:${assetId}:${variant}`},movement:{max_speed:6,acceleration:24,jump_speed:7.5,ground_probe:.08,max_slope_deg:50,step_height:.45,ground_snap_distance:.18,skin_width:.008},collision:{source_root:collision?.shape_root??null,layer:collision?.collision_layer??'character',mask:collision?.mask??['world','enemy','trigger'],fixtures:collision?.fixtures??[],authoring:collision?.authoring??null},skeleton:{profile:rig.profile,bones:rig.bones.map(b=>b.name),sockets:rig.sockets},audio_listener:{enabled:false},runtime:{tags:['ragf','asset:'+assetId,'variant:'+variant],body_id:`body:${assetId}`,character_id:`character:${assetId}`},compatibility:{target_format:'rsr.spatial-embodiment-world.v0.6',minimum_runtime:'0.9.0-alpha.1'},profile_root:''},'profile_root');
}
