import {rootHash,seal,stableId,verifySeal} from '../canonical.mjs';

const escape=value=>String(value).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[character]));
const paletteOf=value=>Array.isArray(value)&&value.length?value:['#17253d','#d8e3ef','#5f91c4','#0d1424'];
function sheetSvg({name,palette,view='front',seed='reference'}){
  const [deep,light,accent,ink]=palette;
  const flip=view==='side'?'translate(18 0) scale(.82 1)':view==='back'?'translate(4 0) scale(.94 1)':'';
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 320"><title>${escape(name)} ${escape(view)} model sheet</title><rect width="240" height="320" fill="#eef2f5"/><g transform="${flip}" stroke="${ink}" stroke-width="5" stroke-linejoin="round"><path fill="${deep}" d="M86 133L62 165 76 282 42 309 198 309 164 282 178 165 154 133Z"/><ellipse fill="${light}" cx="120" cy="82" rx="45" ry="54"/><path fill="${deep}" d="M75 76Q78 20 120 20T165 76Q145 50 120 58T75 76Z"/><path fill="${accent}" d="M80 143L120 164 160 143 151 194 120 210 89 194Z"/><circle fill="${accent}" cx="105" cy="86" r="6"/><circle fill="${accent}" cx="135" cy="86" r="6"/><path fill="none" d="M108 113Q120 120 132 113"/><path fill="none" d="M78 177L37 226M162 177L203 226"/><path fill="none" d="M94 281L78 309M146 281L162 309"/></g><text x="12" y="20" font-family="sans-serif" font-size="11" fill="#26323d">${escape(name)} · ${escape(view)} · ${escape(seed)}</text></svg>`;
}
function chartSvg({name,title,items,palette}){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 180"><title>${escape(title)}</title><rect width="480" height="180" fill="#f5f6f7"/><text x="18" y="24" font-family="sans-serif" font-size="16" fill="#19232d">${escape(name)} · ${escape(title)}</text>${items.map((item,index)=>`<g transform="translate(${18+index*90} 48)"><circle cx="36" cy="38" r="30" fill="${palette[index%palette.length]}" stroke="#1a2430" stroke-width="3"/><text x="36" y="82" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#26323d">${escape(item)}</text></g>`).join('')}</svg>`}

export function generateAnimeCharacterFamily({assetId='character:blue-tianlin',name='蓝天临',palette,seed='anime-reference-v0.1'}={}){
  const colors=paletteOf(palette),identity={asset_id:assetId,name,seed},files={
    'model-sheet.svg':sheetSvg({name,palette:colors,seed}),
    'front-view.svg':sheetSvg({name,palette:colors,view:'front',seed}),
    'side-view.svg':sheetSvg({name,palette:colors,view:'side',seed}),
    'back-view.svg':sheetSvg({name,palette:colors,view:'back',seed}),
    'expression-sheet.svg':chartSvg({name,title:'expression sheet',items:['neutral','restrained','question','resolve'],palette:colors}),
    'mouth-chart.svg':chartSvg({name,title:'mouth chart',items:['closed','a','i','o','u'],palette:colors}),
    'eye-chart.svg':chartSvg({name,title:'eye chart',items:['open','blink','gaze','soft'],palette:colors}),
    'hand-chart.svg':chartSvg({name,title:'hand chart',items:['rest','point','grip','open'],palette:colors}),
    'pose-library.svg':chartSvg({name,title:'pose library',items:['lowered','raise','locked','hold'],palette:colors}),
  };
  const family=seal({format:'ragf.anime-character-family.v0.1',version:'0.1.0-alpha.1',identity,character_bible:{silhouette:'slender-judge',line_style:'stable-ink-5px',palette:colors,proportions:{head_to_body:7.1,shoulder_width:1.35},costume:{primary:'deep-navy',secondary:'cold-silver',accent:'blue-sigil'}},model_sheet:{views:['front','side','back'],files:Object.keys(files).slice(0,4)},expression_sheet:{file:'expression-sheet.svg',expressions:['neutral','restrained','question','resolve']},mouth_chart:{file:'mouth-chart.svg',shapes:['closed','a','i','o','u']},eye_chart:{file:'eye-chart.svg',states:['open','blink','gaze','soft']},hand_chart:{file:'hand-chart.svg',states:['rest','point','grip','open']},pose_library:{file:'pose-library.svg',poses:['head_lowered','begin_raise_head','gaze_locked','hold']},palette:colors,line_style:{name:'stable-ink-5px',outline_px:5,internal_line_px:3,temporal_stability:'deterministic'},costume_variants:[{id:'default',palette:colors}],layered_2d_rig:{format:'ragf.layered-2d-rig.v0.1',layers:['back-hair','face','eyes','mouth','front-hair','coat','hands','effects'],anchors:{head:[0,0],mouth:[0,.12],gaze:[0,.03]}},optional_3d_proxy:{provider:'ragf.deterministic-procedural-3d',status:'available-as-proxy',quality_boundary:'not commercial anime source art'},facial_rig:{format:'ragf.facial-rig.v0.1',controls:['head_pitch','gaze_x','gaze_y','blink','mouth_open','mouth_shape','expression_weight']},viseme_map:{sil:'closed',a:'a',i:'i',u:'u',e:'i',o:'o'},retarget_profile:{profile:'rncs.anime-humanoid-v0.1',bones:['root','head','spine','arm_l','arm_r','leg_l','leg_r']},continuity_bundle:{asset_root:stableId('anime-character',identity),identity_root:rootHash(identity),stable_across_cuts:true},lineage_graph:{source:'reference-provider',parents:[],provider_root:rootHash({provider:'ragf.anime-reference-provider',seed})},provider:{id:'ragf.anime-reference-provider',version:'0.1.0',mode:'reference',quality:'reference-anime-tv-blocking',license:'Apache-2.0'}} ,'family_root');
  return{family,files:Object.fromEntries(Object.entries(files).map(([name,content])=>[name,{name,content,mime:'image/svg+xml',root:rootHash(content)}]))};
}

export function generateAnimeBackgroundFamily({assetId='background:unnamed-city',name='无名城审判台',seed='anime-background-reference-v0.1'}={}){
  const layers=[{layer_id:'sky',depth:1,color:'#cbd2d8'},{layer_id:'city',depth:.7,color:'#77828d'},{layer_id:'platform',depth:.4,color:'#3d4651'},{layer_id:'foreground',depth:.1,color:'#1e2630'}];
  const layoutSvg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 540"><title>${escape(name)}</title><rect width="960" height="540" fill="#cbd2d8"/><path fill="#77828d" d="M0 300L100 240 190 286 280 202 360 280 460 226 560 274 650 180 760 270 860 220 960 284V420H0Z"/><path fill="#3d4651" d="M0 420H960V540H0Z"/><path fill="#1e2630" d="M0 500L160 470 290 500 420 452 580 500 720 460 960 500V540H0Z"/></svg>`;
  return{family:seal({format:'ragf.anime-background-family.v0.1',version:'0.1.0-alpha.1',identity:{asset_id:assetId,name,seed},layout:{file:'layout.svg',projection:'2.5d',camera_projection:'orthographic'},perspective:{vanishing_point:[.5,.54],safe_area:[.05,.05,.9,.9]},depth_layers:layers,matte_layers:layers.map(item=>({layer_id:item.layer_id,alpha:true})),light_variants:['cold-overcast','judge-platform-key'],day_state:'overcast',weather_state:'cold-wind',camera_projection:{kind:'2.5d',parallax:true},continuity_bundle:{asset_root:stableId('anime-background',{assetId,seed}),stable_across_cuts:true},provider:{id:'ragf.anime-reference-provider',version:'0.1.0',mode:'reference',quality:'reference-anime-tv-blocking',license:'Apache-2.0'},lineage_graph:{source:'reference-provider',parents:[],provider_root:rootHash({assetId,seed})}},'family_root'),files:{'layout.svg':{name:'layout.svg',content:layoutSvg,mime:'image/svg+xml',root:rootHash(layoutSvg)}}};
}

export function validateAnimeCharacterFamily(family){
  const errors=[];if(family?.format!=='ragf.anime-character-family.v0.1')errors.push('RAGF_ANIME_CHARACTER_FORMAT_INVALID');if(!family?.identity?.asset_id)errors.push('RAGF_ANIME_CHARACTER_ID_REQUIRED');if(!verifySeal(family,'family_root'))errors.push('RAGF_ANIME_CHARACTER_ROOT_INVALID');if(!Array.isArray(family?.model_sheet?.files)||family.model_sheet.files.length<3)errors.push('RAGF_ANIME_CHARACTER_ROLE_MISSING:model_sheet');for(const role of ['expression_sheet','mouth_chart','eye_chart','hand_chart','pose_library'])if(!family?.[role]?.file)errors.push(`RAGF_ANIME_CHARACTER_ROLE_MISSING:${role}`);if(family?.provider?.id!=='ragf.anime-reference-provider')errors.push('RAGF_ANIME_CHARACTER_PROVIDER_INVALID');if(family?.provider?.mode!=='reference')errors.push('RAGF_ANIME_CHARACTER_PROVIDER_MODE_INVALID');return{valid:errors.length===0,errors,family_root:family?.family_root??null};
}

export function validateAnimeBackgroundFamily(family){
  const errors=[];if(family?.format!=='ragf.anime-background-family.v0.1')errors.push('RAGF_ANIME_BACKGROUND_FORMAT_INVALID');if(!family?.identity?.asset_id)errors.push('RAGF_ANIME_BACKGROUND_ID_REQUIRED');if(!verifySeal(family,'family_root'))errors.push('RAGF_ANIME_BACKGROUND_ROOT_INVALID');if(!family?.layout?.file)errors.push('RAGF_ANIME_BACKGROUND_LAYOUT_MISSING');if((family?.depth_layers??[]).length<2)errors.push('RAGF_ANIME_BACKGROUND_DEPTH_LAYERS_MISSING');if(family?.provider?.id!=='ragf.anime-reference-provider')errors.push('RAGF_ANIME_BACKGROUND_PROVIDER_INVALID');return{valid:errors.length===0,errors,family_root:family?.family_root??null};
}
