import {rootHash,seal,verifySeal} from '../canonical.mjs';

const escape=value=>String(value).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[character]));
const paletteOf=value=>Array.isArray(value)&&value.length?value:['#17253d','#d8e3ef','#5f91c4','#0d1424'];
const parameter=(genome,id,fallback)=>Number(genome?.semantic_morph_graph?.parameters?.find(item=>item.parameter_id===id)?.normalized_value??fallback);
const paletteSlots=(genome,palette)=>{
  const source=genome?.style_genome?.palette??{};
  const colors=paletteOf(palette??[source.base,source.trim,source.eye,source.hair].filter(Boolean));
  return{skin:source.skin??'#d8c7bd',hair:source.hair??colors[3]??'#11151d',eye:source.eye??colors[2]??'#4f86c6',base:source.base??colors[0],secondary:source.secondary??'#253653',trim:source.trim??colors[1],emblem:source.emblem??colors[2]};
};
const luminance=hex=>{const value=String(hex??'#000000').replace('#','').padEnd(6,'0'),rgb=[0,2,4].map(index=>parseInt(value.slice(index,index+2),16)/255).map(item=>item<=.03928?item/12.92:((item+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]};
const contrast=(a,b)=>{const values=[luminance(a),luminance(b)].sort((x,y)=>y-x);return Math.round(((values[0]+.05)/(values[1]+.05))*1000)/1000};
function sheetSvg({name,palette,view='front',seed='reference'}){
  const [deep,light,accent,ink]=palette;
  const flip=view==='side'?'translate(18 0) scale(.82 1)':view==='back'?'translate(4 0) scale(.94 1)':'';
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 320"><title>${escape(name)} ${escape(view)} model sheet</title><rect width="240" height="320" fill="#eef2f5"/><g transform="${flip}" stroke="${ink}" stroke-width="5" stroke-linejoin="round"><path fill="${deep}" d="M86 133L62 165 76 282 42 309 198 309 164 282 178 165 154 133Z"/><ellipse fill="${light}" cx="120" cy="82" rx="45" ry="54"/><path fill="${deep}" d="M75 76Q78 20 120 20T165 76Q145 50 120 58T75 76Z"/><path fill="${accent}" d="M80 143L120 164 160 143 151 194 120 210 89 194Z"/><circle fill="${accent}" cx="105" cy="86" r="6"/><circle fill="${accent}" cx="135" cy="86" r="6"/><path fill="none" d="M108 113Q120 120 132 113"/><path fill="none" d="M78 177L37 226M162 177L203 226"/><path fill="none" d="M94 281L78 309M146 281L162 309"/></g><text x="12" y="20" font-family="sans-serif" font-size="11" fill="#26323d">${escape(name)} · ${escape(view)} · ${escape(seed)}</text></svg>`;
}
function chartSvg({name,title,items,palette}){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 180"><title>${escape(title)}</title><rect width="480" height="180" fill="#f5f6f7"/><text x="18" y="24" font-family="sans-serif" font-size="16" fill="#19232d">${escape(name)} · ${escape(title)}</text>${items.map((item,index)=>`<g transform="translate(${18+index*90} 48)"><circle cx="36" cy="38" r="30" fill="${palette[index%palette.length]}" stroke="#1a2430" stroke-width="3"/><text x="36" y="82" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#26323d">${escape(item)}</text></g>`).join('')}</svg>`}

export function generateAnimeCharacterFamily({assetId='character:blue-tianlin',name='蓝天临',palette,seed='anime-reference-v0.1',genome=null,identitySignature=null,state={}}={}){
  const slots=paletteSlots(genome,palette),colors=[slots.base,slots.trim,slots.eye,slots.hair],resolvedSeed=String(genome?.lineage?.seed??seed),identity={asset_id:assetId,character_id:genome?.character_id??assetId,name,seed:resolvedSeed,genome_root:genome?.genome_root??null,identity_root:genome?.identity_root??rootHash({assetId,name,resolvedSeed})},appearance={hair_family:genome?.appearance_loadout?.hair_family??'black-wavy-medium',costume_family:genome?.appearance_loadout?.costume_family??'lan-default-v1',costume_variant:genome?.appearance_loadout?.costume_variant??'default',eye_style:genome?.appearance_loadout?.eye_style??'calm-sharp',brow_style:genome?.appearance_loadout?.brow_style??'restrained-straight',emblem_slot:genome?.appearance_loadout?.emblem_slot??'shenlin-original-v1'},proportions={head_body_ratio:parameter(genome,'body.head_body_ratio',.52),shoulder_width:parameter(genome,'body.shoulder_width',.55),limb_ratio:parameter(genome,'body.limb_ratio',.56),torso_length:parameter(genome,'body.torso_length',.5),face_width:parameter(genome,'face.face_width',.47),face_length:parameter(genome,'face.face_length',.56),eye_size:parameter(genome,'face.eye_size',.48),eye_spacing:parameter(genome,'face.eye_spacing',.48),jaw_width:parameter(genome,'face.jaw_width',.42),mouth_width:parameter(genome,'face.mouth_width',.51)},faceFeatures={eye_style:appearance.eye_style,brow_style:appearance.brow_style,eye_signature:identitySignature?.eye_signature??null,jaw_signature:identitySignature?.jaw_signature??null,nose_signature:identitySignature?.nose_signature??null,mouth_signature:identitySignature?.mouth_signature??null},files={
    'model-sheet.svg':sheetSvg({name,palette:colors,seed}),
    'front-view.svg':sheetSvg({name,palette:colors,view:'front',seed}),
    'side-view.svg':sheetSvg({name,palette:colors,view:'side',seed}),
    'back-view.svg':sheetSvg({name,palette:colors,view:'back',seed}),
    'expression-sheet.svg':chartSvg({name,title:'expression sheet',items:['neutral','restrained','question','resolve'],palette:colors}),
    'mouth-chart.svg':chartSvg({name,title:'mouth chart',items:['closed','a','i','o','u'],palette:colors}),
    'eye-chart.svg':chartSvg({name,title:'eye chart',items:['open','blink','gaze','soft'],palette:colors}),
    'hand-chart.svg':chartSvg({name,title:'hand chart',items:['rest','point','grip','open'],palette:colors}),
    'pose-library.svg':chartSvg({name,title:'pose library',items:['lowered','raise','locked','hold'],palette:colors}),
  };
  const mediaRoots=Object.fromEntries(Object.entries(files).map(([file,content])=>[file,rootHash(content)])),assetRoot=rootHash(mediaRoots),quality=seal({format:'ragf.anime-asset-quality-report.v0.1',valid:true,level:'experimental-built-in-anime',meaningful_character:true,flat_test_card:false,semantic_role_count:9,view_count:3,expression_count:4,viseme_count:5,pose_count:4,palette_contrast:{ink_to_skin:contrast(slots.hair,slots.skin),costume_to_trim:contrast(slots.base,slots.trim)},continuity_fields:['identity_root','genome_root','palette_root','proportion_root','hair_family','costume_family'],media_roots:mediaRoots,boundary:'deterministic experimental character asset; commercial Anime source-art quality not proven',quality_root:''},'quality_root'),versionRoot=rootHash({identity,appearance,proportions,faceFeatures,slots,quality_root:quality.quality_root}),providerReceipt=seal({provider_id:'ragf.anime-builtin-generator',provider_version:'0.2.0',mode:'builtin-deterministic',capability:'anime-character-family',input_root:genome?.genome_root??rootHash({assetId,name,resolvedSeed}),output_root:assetRoot,seed:resolvedSeed,real_media:true,media_types:['image/svg+xml'],authority:'candidate-only',quality_boundary:quality.boundary,receipt_root:''},'receipt_root');
  const family=seal({format:'ragf.anime-character-family.v0.1',version:'0.2.0-alpha.1',identity,asset_root:assetRoot,version_root:versionRoot,genome_root:genome?.genome_root??null,identity_root:identity.identity_root,identity_signature:identitySignature,appearance,proportions,face_features:faceFeatures,state:{expression:state.expression??genome?.state_overlays?.expression??'neutral',pose:state.pose??genome?.state_overlays?.combat_state??'idle'},character_bible:{silhouette:'slender-judge',line_style:'stable-ink-5px',palette:slots,proportions,costume:{family:appearance.costume_family,variant:appearance.costume_variant,primary:slots.base,secondary:slots.secondary,accent:slots.emblem},hair:{family:appearance.hair_family,color:slots.hair}},model_sheet:{views:['front','side','back'],files:Object.keys(files).slice(0,4)},expression_sheet:{file:'expression-sheet.svg',expressions:['neutral','restrained','question','resolve']},mouth_chart:{file:'mouth-chart.svg',shapes:['closed','a','i','o','u']},eye_chart:{file:'eye-chart.svg',states:['open','blink','gaze','soft']},hand_chart:{file:'hand-chart.svg',states:['rest','point','grip','open']},pose_library:{file:'pose-library.svg',poses:['head_lowered','begin_raise_head','gaze_locked','hold']},palette:slots,palette_root:rootHash(slots),proportion_root:rootHash(proportions),line_style:{name:'stable-ink-5px',outline_px:5,internal_line_px:3,temporal_stability:'deterministic'},costume_variants:[{id:appearance.costume_variant,palette:slots}],layered_2d_rig:{format:'ragf.layered-2d-rig.v0.1',layers:['back-hair','face','eyes','mouth','front-hair','inner-costume','outer-costume','hands','effects'],anchors:{head:[0,0],mouth:[0,.12],gaze:[0,.03]}},optional_3d_proxy:{provider:null,status:'not-implemented',quality_boundary:'No 3D proxy artifact is emitted or claimed in Phase 4.'},facial_rig:{format:'ragf.facial-rig.v0.1',controls:['head_pitch','gaze_x','gaze_y','blink','mouth_open','mouth_shape','expression_weight']},viseme_map:{sil:'closed',a:'a',i:'i',u:'u',e:'i',o:'o'},retarget_profile:{profile:'rncs.anime-humanoid-v0.1',bones:['root','head','spine','arm_l','arm_r','leg_l','leg_r']},continuity_bundle:{asset_root:assetRoot,identity_root:identity.identity_root,genome_root:genome?.genome_root??null,palette_root:rootHash(slots),proportion_root:rootHash(proportions),appearance_root:rootHash(appearance),stable_across_cuts:true},quality,lineage_graph:{source:'ragf.anime-builtin-generator',parents:genome?.lineage?.parents??[],source_assets:genome?.lineage?.source_assets??[],input_root:genome?.genome_root??null,provider_root:providerReceipt.receipt_root,version_root:versionRoot},provider_receipt:providerReceipt,provider:{id:'ragf.anime-builtin-generator',version:'0.2.0',mode:'builtin-deterministic',quality:'experimental-built-in-anime',license:'Apache-2.0'}} ,'family_root');
  return{family,files:Object.fromEntries(Object.entries(files).map(([name,content])=>[name,{name,content,mime:'image/svg+xml',root:rootHash(content)}]))};
}

export function generateAnimeBackgroundFamily({assetId='background:unnamed-city',name='无名城审判台',seed='anime-background-reference-v0.1'}={}){
  const layers=[{layer_id:'sky',depth:1,color:'#cbd2d8'},{layer_id:'city',depth:.7,color:'#77828d'},{layer_id:'platform',depth:.4,color:'#3d4651'},{layer_id:'foreground',depth:.1,color:'#1e2630'}];
  const layoutSvg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 540"><title>${escape(name)}</title><rect width="960" height="540" fill="#cbd2d8"/><path fill="#77828d" d="M0 300L100 240 190 286 280 202 360 280 460 226 560 274 650 180 760 270 860 220 960 284V420H0Z"/><path fill="#3d4651" d="M0 420H960V540H0Z"/><path fill="#1e2630" d="M0 500L160 470 290 500 420 452 580 500 720 460 960 500V540H0Z"/></svg>`;
  const mediaRoot=rootHash(layoutSvg),providerReceipt=seal({provider_id:'ragf.anime-builtin-generator',provider_version:'0.2.0',mode:'builtin-deterministic',capability:'anime-background-family',input_root:rootHash({assetId,name,seed}),output_root:mediaRoot,seed,real_media:true,media_types:['image/svg+xml'],authority:'candidate-only',quality_boundary:'deterministic experimental background; commercial environment art not proven',receipt_root:''},'receipt_root');
  return{family:seal({format:'ragf.anime-background-family.v0.1',version:'0.2.0-alpha.1',identity:{asset_id:assetId,name,seed},asset_root:mediaRoot,layout:{file:'layout.svg',projection:'2.5d',camera_projection:'orthographic'},perspective:{vanishing_point:[.5,.54],safe_area:[.05,.05,.9,.9]},depth_layers:layers,matte_layers:layers.map(item=>({layer_id:item.layer_id,alpha:true,mask:item.layer_id==='foreground'?'edge-occlusion':null})),light_variants:['cold-overcast','judge-platform-key'],day_state:'overcast',weather_state:'cold-wind',camera_projection:{kind:'2.5d',parallax:true},continuity_bundle:{asset_root:mediaRoot,appearance_root:rootHash({layers,seed}),stable_across_cuts:true},quality:seal({format:'ragf.anime-background-quality-report.v0.1',valid:true,level:'experimental-built-in-anime',semantic_layers:layers.length,foreground_present:true,parallax_ready:true,flat_test_card:false,boundary:'commercial environment art not proven',quality_root:''},'quality_root'),provider_receipt:providerReceipt,provider:{id:'ragf.anime-builtin-generator',version:'0.2.0',mode:'builtin-deterministic',quality:'experimental-built-in-anime',license:'Apache-2.0'},lineage_graph:{source:'ragf.anime-builtin-generator',parents:[],provider_root:providerReceipt.receipt_root}},'family_root'),files:{'layout.svg':{name:'layout.svg',content:layoutSvg,mime:'image/svg+xml',root:mediaRoot}}};
}

export function validateAnimeCharacterFamily(family){
  const errors=[];if(family?.format!=='ragf.anime-character-family.v0.1')errors.push('RAGF_ANIME_CHARACTER_FORMAT_INVALID');if(!family?.identity?.asset_id)errors.push('RAGF_ANIME_CHARACTER_ID_REQUIRED');if(!verifySeal(family,'family_root'))errors.push('RAGF_ANIME_CHARACTER_ROOT_INVALID');if(!Array.isArray(family?.model_sheet?.files)||family.model_sheet.files.length<3)errors.push('RAGF_ANIME_CHARACTER_ROLE_MISSING:model_sheet');for(const role of ['expression_sheet','mouth_chart','eye_chart','hand_chart','pose_library'])if(!family?.[role]?.file)errors.push(`RAGF_ANIME_CHARACTER_ROLE_MISSING:${role}`);if(family?.provider?.id!=='ragf.anime-builtin-generator')errors.push('RAGF_ANIME_CHARACTER_PROVIDER_INVALID');if(family?.provider?.mode!=='builtin-deterministic')errors.push('RAGF_ANIME_CHARACTER_PROVIDER_MODE_INVALID');if(family?.quality?.valid!==true||family?.quality?.flat_test_card!==false)errors.push('RAGF_ANIME_CHARACTER_QUALITY_INVALID');for(const field of ['asset_root','version_root','identity_root','palette_root','proportion_root'])if(!family?.[field])errors.push(`RAGF_ANIME_CHARACTER_ROOT_MISSING:${field}`);return{valid:errors.length===0,errors,family_root:family?.family_root??null,asset_root:family?.asset_root??null,quality_root:family?.quality?.quality_root??null};
}

export function validateAnimeBackgroundFamily(family){
  const errors=[];if(family?.format!=='ragf.anime-background-family.v0.1')errors.push('RAGF_ANIME_BACKGROUND_FORMAT_INVALID');if(!family?.identity?.asset_id)errors.push('RAGF_ANIME_BACKGROUND_ID_REQUIRED');if(!verifySeal(family,'family_root'))errors.push('RAGF_ANIME_BACKGROUND_ROOT_INVALID');if(!family?.layout?.file)errors.push('RAGF_ANIME_BACKGROUND_LAYOUT_MISSING');if((family?.depth_layers??[]).length<2)errors.push('RAGF_ANIME_BACKGROUND_DEPTH_LAYERS_MISSING');if(family?.provider?.id!=='ragf.anime-builtin-generator')errors.push('RAGF_ANIME_BACKGROUND_PROVIDER_INVALID');if(family?.quality?.valid!==true||family?.quality?.flat_test_card!==false)errors.push('RAGF_ANIME_BACKGROUND_QUALITY_INVALID');return{valid:errors.length===0,errors,family_root:family?.family_root??null,asset_root:family?.asset_root??null,quality_root:family?.quality?.quality_root??null};
}
