import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createAnimeProduction,validateAnimeProduction,buildExposureSheet,buildProductionExposureSheets,validateExposureSheet,validateProductionExposureSheets,renderCutFrame,renderProduction,replayProduction} from '../src/index.mjs';

function production(){return createAnimeProduction({series:'神临者言律',episode:'EP01',scene:'无名城审判',cut:{cut_id:'S01',duration:5,fps:24,resolution:{width:1920,height:1080},mode:'native-2d',background_layers:[{layer_id:'background:city'}],character_layers:[{layer_id:'character:blue'}],key_pose_track:[{frame:0,pose_id:'head_lowered'},{frame:15,pose_id:'begin_raise_head'},{frame:28,pose_id:'gaze_locked'}],dialogue_track:[{dialogue_event_id:'dialogue:one',text:'何罪之有？',start_frame:31,end_frame:57}],mouth_track:[{dialogue_event_id:'dialogue:one',start_frame:31,end_frame:40,shape:'o'}],blink_track:[{frame:34}],animation:{exposure:'on_twos'}}})}

test('Anime Production IR validates the first cut contract',()=>{const value=production(),result=validateAnimeProduction(value);assert.equal(result.valid,true);assert.equal(result.frame_count,120);assert.equal(value.cut.mode,'native-2d')});
test('X-Sheet preserves stepped on-twos and dialogue authority interval',()=>{const sheet=buildExposureSheet(production().cut);assert.equal(sheet.frame_count,120);assert.equal(validateExposureSheet(sheet).valid,true);assert.equal(sheet.frames[0].animation_policy.interpolation,'stepped');assert.equal(sheet.frames[0].dialogue_state,null);assert.equal(sheet.frames[31].dialogue_state.dialogue_event_id,'dialogue:one');assert.equal(sheet.frames[41].mouth_shape,'closed')});
test('same render input produces same PNG and frame evidence root',()=>{const value=production(),a=renderCutFrame(value,31,{width:320,height:180,quality:'preview'}),b=renderCutFrame(value,31,{width:320,height:180,quality:'preview'});assert.deepEqual(a.bytes,b.bytes);assert.equal(a.evidence.evidence_root,b.evidence.evidence_root);assert.ok(a.bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))});

function editorialProduction(overrides={}){const base={fps:10,resolution:{width:320,height:180},mode:'native-2d',background_layers:[{layer_id:'background:city',asset_id:'background:city'}],character_layers:[{layer_id:'character:blue',actor_id:'blue',asset_id:'character:blue'}],key_pose_track:[{frame:0,pose_id:'hold'}],animation:{exposure:'on_twos'}};return createAnimeProduction({series:'Editorial Test',cuts:[{...base,episode_id:'EP01',scene_id:'court',cut_id:'S01',duration:.2,dialogue_track:[{dialogue_event_id:'dialogue:one',start_frame:0,end_frame:1,text:'one'}]},{...base,...overrides,episode_id:'EP01',scene_id:'court',cut_id:overrides.cut_id??'S02',duration:.2,dialogue_track:[{dialogue_event_id:'dialogue:two',start_frame:0,end_frame:1,text:'two'}]}]})}

test('multi-Cut editorial timeline and X-Sheets cover the full production',()=>{const value=editorialProduction(),validation=validateAnimeProduction(value),sheets=buildProductionExposureSheets(value);assert.equal(validation.valid,true);assert.equal(validation.cut_count,2);assert.equal(validation.total_frame_count,4);assert.deepEqual(value.editorial_timeline.cut_order,['EP01/court/S01','EP01/court/S02']);assert.equal(validateProductionExposureSheets(sheets).valid,true);assert.equal(sheets.total_frame_count,4)});

test('production renderer writes globally numbered real PNGs, replays both Cuts, and removes stale frames',t=>{const outDir=fs.mkdtempSync(path.join(os.tmpdir(),'anime-editorial-render-'));t.after(()=>fs.rmSync(outDir,{recursive:true,force:true}));const value=editorialProduction(),result=renderProduction(value,{outDir,width:160,height:90,quality:'preview'});assert.equal(result.manifest.status,'complete');assert.equal(result.manifest.rendered_frame_count,4);assert.deepEqual(result.manifest.frames.map(frame=>frame.global_frame_number),[0,1,2,3]);assert.deepEqual(result.manifest.frames.map(frame=>frame.cut_ref),['EP01/court/S01','EP01/court/S01','EP01/court/S02','EP01/court/S02']);for(const frame of result.manifest.frames)assert.ok(fs.readFileSync(path.join(outDir,frame.filename)).subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])));assert.equal(replayProduction(value,result.manifest).valid,true);const partial=renderProduction(value,{outDir,width:160,height:90,quality:'preview',maxFrames:1});assert.equal(partial.manifest.rendered_frame_count,1);assert.equal(fs.readdirSync(path.join(outDir,'frames')).filter(name=>/^frame-\d{6}\.png$/u.test(name)).length,1)});

test('editorial validation rejects duplicate refs, mixed fps, unsupported transition, and identity drift',()=>{assert.ok(validateAnimeProduction(editorialProduction({cut_id:'S01'})).errors.some(error=>error.includes('EDITORIAL_CUT_REF_DUPLICATE')));assert.ok(validateAnimeProduction(editorialProduction({fps:12})).errors.includes('EDITORIAL_MASTER_FPS_MISMATCH'));assert.ok(validateAnimeProduction(editorialProduction({transition:{type:'dissolve',duration_frames:4}})).errors.some(error=>error.includes('EDITORIAL_TRANSITION_UNSUPPORTED')));assert.ok(validateAnimeProduction(editorialProduction({character_layers:[{layer_id:'character:blue',actor_id:'blue',asset_id:'character:other'}]})).errors.some(error=>error.includes('CHARACTER_ASSET_DRIFT')))});
