import test from 'node:test';
import assert from 'node:assert/strict';
import {createAnimeProduction,validateAnimeProduction,buildExposureSheet,validateExposureSheet,renderCutFrame} from '../src/index.mjs';

function production(){return createAnimeProduction({series:'神临者言律',episode:'EP01',scene:'无名城审判',cut:{cut_id:'S01',duration:5,fps:24,resolution:{width:1920,height:1080},mode:'native-2d',background_layers:[{layer_id:'background:city'}],character_layers:[{layer_id:'character:blue'}],key_pose_track:[{frame:0,pose_id:'head_lowered'},{frame:15,pose_id:'begin_raise_head'},{frame:28,pose_id:'gaze_locked'}],dialogue_track:[{dialogue_event_id:'dialogue:one',text:'何罪之有？',start_frame:31,end_frame:57}],mouth_track:[{dialogue_event_id:'dialogue:one',start_frame:31,end_frame:40,shape:'o'}],blink_track:[{frame:34}],animation:{exposure:'on_twos'}}})}

test('Anime Production IR validates the first cut contract',()=>{const value=production(),result=validateAnimeProduction(value);assert.equal(result.valid,true);assert.equal(result.frame_count,120);assert.equal(value.cut.mode,'native-2d')});
test('X-Sheet preserves stepped on-twos and dialogue authority interval',()=>{const sheet=buildExposureSheet(production().cut);assert.equal(sheet.frame_count,120);assert.equal(validateExposureSheet(sheet).valid,true);assert.equal(sheet.frames[0].animation_policy.interpolation,'stepped');assert.equal(sheet.frames[0].dialogue_state,null);assert.equal(sheet.frames[31].dialogue_state.dialogue_event_id,'dialogue:one');assert.equal(sheet.frames[41].mouth_shape,'closed')});
test('same render input produces same PNG and frame evidence root',()=>{const value=production(),a=renderCutFrame(value,31,{width:320,height:180,quality:'preview'}),b=renderCutFrame(value,31,{width:320,height:180,quality:'preview'});assert.deepEqual(a.bytes,b.bytes);assert.equal(a.evidence.evidence_root,b.evidence.evidence_root);assert.ok(a.bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))});
