import {createHash,randomUUID} from 'node:crypto';
import fs from 'node:fs'; import path from 'node:path';
export class RFEError extends Error{constructor(code,message){super(`${code}: ${message}`);this.code=code}}
const keySort=(a,b)=>a<b?-1:a>b?1:0; // JS string comparison is UTF-16 code-unit order.
function num(v){if(!Number.isFinite(v))throw new RFEError('RFE_CANONICAL_NON_FINITE','NaN and Infinity are forbidden');if(Object.is(v,-0))return'0';return JSON.stringify(v)}
export function canonicalJson(v){if(v===null)return'null';if(v===true)return'true';if(v===false)return'false';if(typeof v==='number')return num(v);if(typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canonicalJson).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort(keySort).map(k=>`${canonicalJson(k)}:${canonicalJson(v[k])}`).join(',')}}`;throw new RFEError('RFE_CANONICAL_UNSUPPORTED',typeof v)}
export const rootHash=v=>createHash('sha256').update(canonicalJson(v)).digest('hex');
export const withIntegrity=(v,field='integrityHash')=>{const b=structuredClone(v);delete b[field];return{...b,[field]:rootHash(b)}};
export const verifyIntegrity=(v,field='integrityHash')=>v?.[field]===rootHash(Object.fromEntries(Object.entries(v).filter(([k])=>k!==field)));
const clone=structuredClone, read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const generationDirName=id=>encodeURIComponent(id);
function writeAtomic(p,v){fs.mkdirSync(path.dirname(p),{recursive:true});const t=`${p}.tmp-${process.pid}-${randomUUID()}`;fs.writeFileSync(t,JSON.stringify(v,null,2)+'\n');fs.renameSync(t,p)}
const active=(r,t)=>Number(r.validFrom??0)<=t&&(r.validTo===null||r.validTo===undefined||t<Number(r.validTo));
const factKey=f=>`${f.subject}\0${f.predicate}`;
const semRel=r=>({type:r.type,from:r.from,to:r.to,qualifiers:r.qualifiers??{}});const relKey=r=>canonicalJson(semRel(r));
function normalizeOperations(operations,authority){return clone(operations).map(op=>{if(op.op==='createIdentity'){op.identity.continuityPolicy??='persistent';op.identity.createdAt??='$logicalTime';op.identity.retiredAt??=null;op.identity.lineage??=[];op.identity.metadata??={}}else if(op.op==='setFact'){op.fact.source??='source:runtime';op.fact.confidence??=1;op.fact.visibility??={type:'public'};op.fact.authority??=authority}else if(op.op==='addRelation'){op.relation.qualifiers??={};op.relation.authority??=authority}return op})}
export class RealityStore{
 constructor(root){this.root=path.resolve(root)}
 static init(root,{worldId='world:default',branchId='branch:main',overwrite=false}={}){root=path.resolve(root);if(fs.existsSync(root)&&fs.readdirSync(root).length){if(!overwrite)throw new RFEError('RFE_STORE_EXISTS',root);fs.rmSync(root,{recursive:true,force:true})}for(const d of ['objects','generations','branches'])fs.mkdirSync(path.join(root,d),{recursive:true});const s=new RealityStore(root);writeAtomic(path.join(root,'store.json'),withIntegrity({format:'rfe.local-core-store.v0.1',sdkVersion:'0.1.0',worldId,defaultBranch:branchId,canonical:'rfe-stable-json-v1',digest:'sha256'}));const refs={identity:s.putObject('identity-group',[]),'event-ledger':s.putObject('event-ledger',[])};const g=s.makeGeneration({branchId,revision:0,logicalTime:0,parent:null,parentEvidence:null,refs,authorityEventHead:null});s.persistGeneration(g);s.writePointer(branchId,g);return s}
 get metadata(){const m=read(path.join(this.root,'store.json'));if(!verifyIntegrity(m))throw new RFEError('RFE_STORE_METADATA_TAMPERED',this.root);return m}get worldId(){return this.metadata.worldId}get defaultBranch(){return this.metadata.defaultBranch}
 branchFile(id){return path.join(this.root,'branches',`${rootHash(id)}.CURRENT.json`)};objectPath(ref){return path.join(this.root,'objects',ref.slice(0,2),`${ref}.json`)};generationPath(id){const encoded=path.join(this.root,'generations',generationDirName(id),'generation.json'),legacy=path.join(this.root,'generations',id,'generation.json');return fs.existsSync(encoded)||encoded===legacy||!fs.existsSync(legacy)?encoded:legacy}
 putObject(kind,value){const body={format:'rfe.content-object.v1',kind,value:clone(value)};const ref=rootHash(body),obj={...body,integrityHash:ref};const p=this.objectPath(ref);if(fs.existsSync(p)){if(canonicalJson(read(p))!==canonicalJson(obj))throw new RFEError('RFE_CONTENT_ADDRESS_COLLISION',ref)}else writeAtomic(p,obj);return ref}
 loadObject(ref){const o=read(this.objectPath(ref));if(o.integrityHash!==ref||rootHash(Object.fromEntries(Object.entries(o).filter(([k])=>k!=='integrityHash')))!==ref)throw new RFEError('RFE_OBJECT_TAMPERED',ref);return o}
 writePointer(branchId,g){writeAtomic(this.branchFile(branchId),withIntegrity({format:'rfe.branch-pointer.v0.3',branchId,generationId:g.generationId,generationRoot:g.integrityHash,revision:g.realityRevision}))}
 currentPointer(branchId=this.defaultBranch){const p=read(this.branchFile(branchId));if(!verifyIntegrity(p)||p.branchId!==branchId)throw new RFEError('RFE_POINTER_TAMPERED',branchId);return p}
 loadGeneration(id){const g=read(this.generationPath(id));if(!verifyIntegrity(g))throw new RFEError('RFE_GENERATION_TAMPERED',id);const marker=path.join(path.dirname(this.generationPath(id)),'COMMITTED');if(!fs.existsSync(marker)||fs.readFileSync(marker,'utf8').trim()!==g.integrityHash)throw new RFEError('RFE_GENERATION_NOT_COMMITTED',id);return g}
 currentGeneration(branchId=this.defaultBranch){return this.loadGeneration(this.currentPointer(branchId).generationId)}
 semanticRoot(refs){const r=Object.fromEntries(Object.keys(refs).filter(k=>k!=='event-ledger').sort(keySort).map(k=>[k,refs[k]]));return rootHash({format:'rfe.semantic-root.v1',refs:r})}
 makeGeneration({branchId,revision,logicalTime,parent,parentEvidence,refs,authorityEventHead}){const semanticRoot=this.semanticRoot(refs),evidenceRoot=rootHash({format:'rfe.evidence-root.v1',semanticRoot,eventLedgerRef:refs['event-ledger']??'',parentEvidenceRoot:parentEvidence});const generationId=`generation:${revision}:${rootHash({branchId,revision,parent,refs,evidenceRoot}).slice(0,20)}`;return withIntegrity({format:'rfe.generation.v0.3',worldId:this.worldId,branchId,generationId,parentGenerationId:parent,realityRevision:revision,logicalTime,semanticRoot,evidenceRoot,authorityEventHead,refs:Object.fromEntries(Object.keys(refs).sort(keySort).map(k=>[k,refs[k]]))})}
 persistGeneration(g){const dir=path.dirname(this.generationPath(g.generationId));if(fs.existsSync(dir)){if(canonicalJson(this.loadGeneration(g.generationId))!==canonicalJson(g))throw new RFEError('RFE_GENERATION_ID_COLLISION',g.generationId);return}const tmp=path.join(this.root,'generations',`.tmp-${generationDirName(g.generationId)}-${randomUUID()}`);fs.mkdirSync(tmp);writeAtomic(path.join(tmp,'generation.json'),g);fs.writeFileSync(path.join(tmp,'COMMITTED'),g.integrityHash+'\n');fs.renameSync(tmp,dir)}
 loadState(g){const identities=clone(this.loadObject(g.refs.identity).value),facts=[],relations=[];let events=[];for(const[k,ref]of Object.entries(g.refs)){if(k.startsWith('fact:'))facts.push(...clone(this.loadObject(ref).value));else if(k.startsWith('relation:'))relations.push(...clone(this.loadObject(ref).value));else if(k==='event-ledger')events=clone(this.loadObject(ref).value)}return{identities,facts,relations,events}}
 materialize({generationId=null,branchId=null}={}){const g=generationId?this.loadGeneration(generationId):this.currentGeneration(branchId??this.defaultBranch);return{generation:clone(g),...this.loadState(g)}}
 getIdentity(id,opts={}){return this.materialize(opts).identities.find(i=>i.id===id)??null}getFact(subject,predicate,opts={}){const m=this.materialize(opts),t=m.generation.logicalTime;return m.facts.find(f=>f.subject===subject&&f.predicate===predicate&&active(f,t))??null}relations({type=null,from=null,to=null,current=true,...opts}={}){const m=this.materialize(opts),t=m.generation.logicalTime;return m.relations.filter(r=>(!type||r.type===type)&&(!from||r.from===from)&&(!to||r.to===to)&&(!current||active(r,t)))}
 generationReference({generationId=null,branchId=null}={}){const g=generationId?this.loadGeneration(generationId):this.currentGeneration(branchId??this.defaultBranch);return{format:'rncs.generation-reference.v0.1',reality_id:g.worldId,generation:g.realityRevision,generation_root:g.integrityHash,rfe_generation_id:g.generationId,branch_id:g.branchId,evidence_root:g.evidenceRoot}}
 commit({actor,intent,authority,operations,branchId=this.defaultBranch,baseGenerationId=null,transactionId=null,evidence=[]}){const current=this.currentGeneration(branchId);if(baseGenerationId&&baseGenerationId!==current.generationId)throw new RFEError('RFE_STALE_BASE',baseGenerationId);transactionId??=`transaction:${randomUUID()}`;const state=this.loadState(current),logicalTime=current.logicalTime+1,revision=current.realityRevision+1,idmap=new Map(state.identities.map(i=>[i.id,i]));operations=normalizeOperations(operations,authority);
  operations.forEach((op,index)=>{if(op.op==='createIdentity'){const i=clone(op.identity);i.createdAt=i.createdAt==='$logicalTime'||i.createdAt===undefined?logicalTime:Number(i.createdAt);i.retiredAt??=null;i.lineage??=[];i.metadata??={};if(idmap.has(i.id))throw new RFEError('RFE_IDENTITY_EXISTS',i.id);state.identities.push(i);idmap.set(i.id,i)}else if(op.op==='retireIdentity'){const i=idmap.get(op.identityId);if(!i)throw new RFEError('RFE_IDENTITY_NOT_FOUND',op.identityId);i.retiredAt=logicalTime}else if(op.op==='setFact'){const s=clone(op.fact);if(!idmap.has(s.subject))throw new RFEError('RFE_FACT_DANGLING_SUBJECT',s.subject);for(const f of state.facts)if(f.subject===s.subject&&f.predicate===s.predicate&&active(f,logicalTime))f.validTo=logicalTime;const payload={transactionId,operation:index,subject:s.subject,predicate:s.predicate,value:s.value,logicalTime};state.facts.push({id:`fact:${rootHash(payload).slice(0,24)}`,subject:s.subject,predicate:s.predicate,value:s.value,validFrom:logicalTime,validTo:null,source:s.source??'source:runtime',confidence:s.confidence??1,visibility:s.visibility??{type:'public'},authority:s.authority??authority})}else if(op.op==='retractFact'){let found=false;for(const f of state.facts)if(f.subject===op.subject&&f.predicate===op.predicate&&active(f,logicalTime)){f.validTo=logicalTime;found=true}if(!found)throw new RFEError('RFE_FACT_NOT_ACTIVE',`${op.subject}:${op.predicate}`)}else if(op.op==='addRelation'){const s=clone(op.relation);if(!idmap.has(s.from)||!idmap.has(s.to))throw new RFEError('RFE_RELATION_DANGLING_ENDPOINT',`${s.from}->${s.to}`);const sem=semRel(s);if(state.relations.some(r=>active(r,logicalTime)&&canonicalJson(semRel(r))===canonicalJson(sem)))throw new RFEError('RFE_RELATION_EXISTS',relKey(s));const payload={transactionId,operation:index,relation:sem,logicalTime};state.relations.push({id:`relation:${rootHash(payload).slice(0,24)}`,...sem,validFrom:logicalTime,validTo:null,authority:s.authority??authority})}else if(op.op==='removeRelation'){let found=false;for(const r of state.relations){const m=op.match,same=r.type===m.type&&r.from===m.from&&r.to===m.to&&(!('qualifiers'in m)||canonicalJson(r.qualifiers??{})===canonicalJson(m.qualifiers));if(same&&active(r,logicalTime)){r.validTo=logicalTime;found=true}}if(!found)throw new RFEError('RFE_RELATION_NOT_ACTIVE',canonicalJson(op.match))}else throw new RFEError('RFE_OPERATION_UNSUPPORTED',String(op.op))});
  const ids=new Set(state.identities.map(i=>i.id));if(ids.size!==state.identities.length)throw new RFEError('RFE_IDENTITY_DUPLICATE','duplicate IDs');for(const f of state.facts)if(!ids.has(f.subject))throw new RFEError('RFE_FACT_DANGLING_SUBJECT',f.subject);for(const r of state.relations)if(!ids.has(r.from)||!ids.has(r.to))throw new RFEError('RFE_RELATION_DANGLING_ENDPOINT',r.id);
  const operationsRoot=rootHash(operations),event=withIntegrity({format:'rfe.authority-event.v0.1',eventId:`event:${rootHash({tx:transactionId,base:current.generationId,operationsRoot}).slice(0,24)}`,transactionId,actor,intent:clone(intent),authority,baseGenerationId:current.generationId,logicalTime,operationsRoot,evidence:clone(evidence)});state.events.push(event);const refs={identity:this.putObject('identity-group',state.identities.sort((a,b)=>keySort(a.id,b.id))),'event-ledger':this.putObject('event-ledger',state.events)};for(const p of [...new Set(state.facts.map(f=>f.predicate))].sort(keySort))refs[`fact:${p}`]=this.putObject('fact-group',state.facts.filter(f=>f.predicate===p).sort((a,b)=>keySort(a.subject,b.subject)||a.validFrom-b.validFrom||keySort(a.id,b.id)));for(const t of [...new Set(state.relations.map(r=>r.type))].sort(keySort))refs[`relation:${t}`]=this.putObject('relation-group',state.relations.filter(r=>r.type===t).sort((a,b)=>keySort(a.from,b.from)||keySort(a.to,b.to)||a.validFrom-b.validFrom||keySort(a.id,b.id)));const g=this.makeGeneration({branchId,revision,logicalTime,parent:current.generationId,parentEvidence:current.evidenceRoot,refs,authorityEventHead:event.eventId});this.persistGeneration(g);if(this.currentGeneration(branchId).generationId!==current.generationId)throw new RFEError('RFE_POINTER_CHANGED_DURING_COMMIT',branchId);this.writePointer(branchId,g);const receipt=withIntegrity({format:'rfe.local-commit-receipt.v0.1',transactionId,branchId,baseGenerationId:current.generationId,resultGenerationId:g.generationId,resultGenerationRoot:g.integrityHash,eventId:event.eventId,operationsRoot,evidenceRoot:g.evidenceRoot});return{generation:g,event,receipt}}
 verify({deep=true}={}){const errors=[],objects=new Set(),generations=new Set();try{this.metadata}catch(e){errors.push(e.message)}for(const name of fs.readdirSync(path.join(this.root,'branches'))){if(!name.endsWith('.json'))continue;try{const p=read(path.join(this.root,'branches',name));if(!verifyIntegrity(p))throw new RFEError('RFE_POINTER_TAMPERED',name);const g=this.loadGeneration(p.generationId);generations.add(g.generationId);if(p.generationRoot!==g.integrityHash)throw new RFEError('RFE_POINTER_ROOT_MISMATCH',p.branchId);if(deep)for(const ref of Object.values(g.refs)){this.loadObject(ref);objects.add(ref)}}catch(e){errors.push(e.message)}}return{valid:!errors.length,errors,checked_generations:generations.size,checked_objects:objects.size}}
}
export function verifyExternalGeneration(generationPath,objectsRoot=null){const g=read(generationPath),errors=[];if(!verifyIntegrity(g))errors.push('GENERATION_INTEGRITY_MISMATCH');if(objectsRoot){for(const ref of Object.values(g.refs??{}).concat(g.objectRefs??[])){const candidates=[path.join(objectsRoot,ref.slice(0,2),`${ref}.json`),path.join(objectsRoot,`${ref}.json`)];const p=candidates.find(fs.existsSync);if(!p){errors.push(`OBJECT_MISSING:${ref}`);continue}const o=read(p);if(o.integrityHash!==ref||rootHash(Object.fromEntries(Object.entries(o).filter(([k])=>k!=='integrityHash')))!==ref)errors.push(`OBJECT_INTEGRITY_MISMATCH:${ref}`)}}return{valid:!errors.length,errors,generation_id:g.generationId,generation_root:g.integrityHash}}

export function federationCandidate(commitResult,{domainId,requestedPolicy='quorum'}={}){const g=commitResult.generation,r=commitResult.receipt;if(!domainId)throw new RFEError('RFE_FEDERATION_DOMAIN_REQUIRED','domainId');return withIntegrity({format:'rfe.federation-candidate.v0.1',domainId,worldId:g.worldId,branchId:g.branchId,generationId:g.generationId,generationRoot:g.integrityHash,semanticRoot:g.semanticRoot,evidenceRoot:g.evidenceRoot,localReceiptRoot:r.integrityHash,requestedPolicy,status:'candidate-not-federated'})}
