import {clone,rootHash,seal,stableId} from './canonical.mjs';

export function createRsrCommandBatch(runtime){
  const commands=(runtime.state.command_log??[]).map((c,i)=>({command_id:`behavior-command:${i+1}`,tick:c.tick,capability_id:c.capability_id,kind:c.capability_id.includes('audio')?'audio':c.capability_id.includes('effect')?'effect':'generic',payload:clone(c.inputs),result:clone(c.result)}));
  return seal({format:'rsr.behavior-command-batch.v0.1',version:'0.1.0',program_root:runtime.program.program_root,state_root:runtime.stateRoot(),commands},'batch_root');
}
export function createVsrDocument(runtime,{observer='player'}={}){
  const s=runtime.state,e=s.entities,showDebug=observer==='debugger';const nodes=[
    {id:'bg',type:'rect',zIndex:0,layout:{x:0,y:0,width:640,height:360},appearance:{fill:{type:'solid',color:'#071426'}}},
    {id:'floor',type:'rect',zIndex:1,layout:{x:0,y:300,width:640,height:60},appearance:{fill:{type:'solid',color:'#102c46'}}},
    {id:'player',type:'ellipse',zIndex:5,layout:{x:e.player.variables.x-14,y:e.player.variables.y-28,width:28,height:56},appearance:{fill:{type:'solid',color:e.player.variables.color}}},
    {id:'enemy',type:'rect',zIndex:5,visible:e.enemy.active,layout:{x:e.enemy.variables.x-14,y:e.enemy.variables.y-30,width:28,height:60},appearance:{fill:{type:'solid',color:e.enemy.variables.color}}},
    {id:'key',type:'ellipse',zIndex:4,visible:!e.key.variables.collected,layout:{x:e.key.variables.x-8,y:e.key.variables.y-8,width:16,height:16},appearance:{fill:{type:'solid',color:e.key.variables.color}}},
    {id:'door',type:'rect',zIndex:3,layout:{x:e.door.variables.x-18,y:e.door.variables.y-70,width:36,height:100},appearance:{fill:{type:'solid',color:e.door.variables.open?'#74f2ce':'#2c526b'}}},
    {id:'message',type:'text',zIndex:10,layout:{x:20,y:18,width:600,height:32},content:{text:s.globals.message,fontFamily:'sans-serif',fontSize:20,fontWeight:'bold'},appearance:{fill:{type:'solid',color:'#ffffff'}}},
    {id:'hud',type:'text',zIndex:10,layout:{x:20,y:52,width:600,height:26},content:{text:`生命 ${e.player.variables.health}/${e.player.variables.max_health}　分数 ${s.globals.score}　钥匙 ${e.player.variables.has_key?'有':'无'}`,fontFamily:'sans-serif',fontSize:15},appearance:{fill:{type:'solid',color:'#bfe8ff'}}}
  ];
  if(showDebug)nodes.push({id:'debug',type:'text',zIndex:20,layout:{x:20,y:92,width:600,height:160},content:{text:`Tick ${s.tick}\nPlayerSM ${s.machines['machine:player'].state}\nEnemySM ${s.machines['machine:enemy'].state}\nEnemyBT ${s.trees['tree:enemy-guard'].status}\nState ${runtime.stateRoot().slice(0,24)}\nProgram ${runtime.program.program_root.slice(0,24)}`,fontFamily:'monospace',fontSize:13},appearance:{fill:{type:'solid',color:'#74f2ce'}}});
  return{specVersion:'0.1',runtimeTarget:'vsr-v0.2',metadata:{id:`vsr:${runtime.program.identity.program_id}:${observer}`,title:runtime.program.identity.title,duration:0,defaultFps:runtime.program.tick_rate,seed:parseInt(runtime.program.program_root.slice(0,8),16)},canvas:{width:640,height:360,background:{type:'solid',color:'#071426'}},variables:{stateRoot:runtime.stateRoot(),observer},nodes,outputs:[{id:'interactive',type:'interactive',width:640,height:360,responsive:true}],extensions:{'rncs:behavior':{program_root:runtime.program.program_root,tick:s.tick,observer}}};
}
export function createStudioImport(runtime,files={}){
  return seal({format:'reality-studio.behavior-import.v0.1',version:'0.1.0',import_id:stableId('studio-behavior-import',{program:runtime.program.program_root,state:runtime.stateRoot()}),program_root:runtime.program.program_root,state_root:runtime.stateRoot(),project_operations:[{op:'register-behavior-program',program_id:runtime.program.identity.program_id,program_root:runtime.program.program_root},{op:'bind-scene-behavior',scene_id:'scene:frost-trial',program_id:runtime.program.identity.program_id},{op:'open-behavior-debugger',trace_path:files.trace??'trace.json'}],panels:['behavior-graph','state-machines','behavior-tree','event-trace','authority-proposals'],preserve_runtime_state:true,authority:{status:'proposal',resolver:'aaf:default'}},'import_root');
}
export function createGatewayManifest(){return{format:'reality-one.runtime-manifest.v0.3',runtime_id:'rncs.behavior',name:'Reality Behavior Fabric',version:'0.1.0-alpha.1',entry:'src/index.mjs',capabilities:[{capability_id:'behavior.program.validate',method:'validateProgram',risk:'low',reversible:true},{capability_id:'behavior.simulate',method:'simulate',risk:'low',reversible:true},{capability_id:'behavior.snapshot',method:'snapshot',risk:'low',reversible:true},{capability_id:'behavior.hot-reload',method:'hotReload',risk:'medium',reversible:true},{capability_id:'behavior.commit-delta',method:'causalDelta',risk:'medium',reversible:true}],host_requirements:['runtime.javascript','storage.state'],evidence:['behavior.trace','behavior.state-root','rfe.behavior-causal-delta']};}
export function createWorkspace({runtime,outputs}){
  const snapshot=runtime.snapshot(),trace=runtime.exportTrace(),delta=runtime.causalDelta(),rsr=createRsrCommandBatch(runtime),vsr_player=createVsrDocument(runtime,{observer:'player'}),vsr_debugger=createVsrDocument(runtime,{observer:'debugger'}),studio=createStudioImport(runtime,{trace:outputs.trace});
  return seal({format:'reality-behavior.workspace.v0.1',version:'0.1.0',workspace_id:stableId('behavior-workspace',{program:runtime.program.program_root,state:runtime.stateRoot()}),program:clone(runtime.program),final_snapshot:snapshot,trace,causal_delta:delta,rsr_command_batch:rsr,vsr:{player:vsr_player,debugger:vsr_debugger},studio_import:studio,gateway_manifest:createGatewayManifest(),outputs:clone(outputs),summary:{tick:runtime.state.tick,state_root:runtime.stateRoot(),score:runtime.state.globals.score,victory:runtime.state.globals.victory,defeat:runtime.state.globals.defeat,events_processed:runtime.state.events_processed,commands:runtime.state.command_log.length,proposals:runtime.state.proposals.length}},'workspace_root');
}
export function verifyWorkspace(w){
  const errors=[];if(w?.format!=='reality-behavior.workspace.v0.1')errors.push('FORMAT_INVALID');const x=clone(w),r=x.workspace_root;delete x.workspace_root;if(rootHash(x)!==r)errors.push('WORKSPACE_ROOT_MISMATCH');
  for(const [obj,field,label]of [[w.final_snapshot,'snapshot_root','SNAPSHOT'],[w.trace,'trace_root','TRACE'],[w.causal_delta,'delta_root','DELTA'],[w.rsr_command_batch,'batch_root','RSR_BATCH'],[w.studio_import,'import_root','STUDIO_IMPORT']]){if(!obj?.[field])errors.push(`${label}_ROOT_MISSING`);else{const y=clone(obj),rr=y[field];delete y[field];if(rootHash(y)!==rr)errors.push(`${label}_ROOT_MISMATCH`);}}
  return{valid:!errors.length,errors,summary:w?.summary??null};
}
