#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {fileURLToPath} from 'node:url';
import {BehaviorRuntime,replayProgram} from './runtime.mjs';import {validateProgram} from './contracts.mjs';import {createWorkspace,verifyWorkspace} from './adapters.mjs';import {createPlayableHtml,writeSvgAndPng} from './render.mjs';import {clone,rootHash} from './canonical.mjs';
const args=process.argv.slice(2),cmd=args[0]??'help';const val=(name,def=null)=>{const i=args.indexOf(name);return i>=0?args[i+1]:def;};
const readJson=f=>JSON.parse(fs.readFileSync(path.resolve(f),'utf8'));const writeJson=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n');};
const providers={
 'experience.audio.emit':({inputs})=>({accepted:true,domain:'audio',cue:inputs.cue??'unknown'}),
 'experience.effect.emit':({inputs})=>({accepted:true,domain:'effect',effect:inputs.effect??'unknown'})
};
function autoInput(runtime){const p=runtime.state.entities.player.variables,n=runtime.state.entities.enemy.variables;const input={};if(!p.has_key)input.move_right=true;else if(n.health>0){const dx=n.x-p.x;if(Math.abs(dx)>50){if(dx>0)input.move_right=true;else input.move_left=true;}else if(p.attack_cooldown<=0)input.attack=true;}else input.move_right=true;return input;}
async function demo(){
 const programPath=val('--program','examples/frost-trial.behavior.json'),out=path.resolve(val('--out','outputs/frost-trial')),program=readJson(programPath),report=validateProgram(program);if(!report.valid)throw new Error(`PROGRAM_INVALID ${JSON.stringify(report.errors)}`);fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
 const runtime=new BehaviorRuntime(program,{providers});let checkpoint=null;while(runtime.state.tick<500&&!runtime.state.globals.victory&&!runtime.state.globals.defeat){runtime.tick(autoInput(runtime));if(runtime.state.tick===100)checkpoint=runtime.snapshot();}
 if(!runtime.state.globals.victory)throw new Error('DEMO_DID_NOT_REACH_VICTORY');const finalRoot=runtime.stateRoot(),inputLog=clone(runtime.state.input_log),replayed=replayProgram(program,inputLog,{providers});if(replayed.stateRoot()!==finalRoot)throw new Error('REPLAY_ROOT_MISMATCH');
 const recovered=new BehaviorRuntime(program,{providers});recovered.run(100,(_,r)=>inputLog[r.state.tick]?.input??{});recovered.restore(checkpoint);for(const row of inputLog.slice(checkpoint.tick))recovered.tick(row.input);if(recovered.stateRoot()!==finalRoot)throw new Error('CHECKPOINT_ROOT_MISMATCH');
 const player=writeSvgAndPng(runtime,out,'final-player',{debug:false}),debuggerView=writeSvgAndPng(runtime,out,'final-debugger',{debug:true});if(!player.rasterized)console.warn('[rbf] ImageMagick unavailable; SVG outputs retained and PNG rasterization skipped.');fs.writeFileSync(path.join(out,'playable.html'),createPlayableHtml(program));
 const outputs={player_svg:path.basename(player.svg),debugger_svg:path.basename(debuggerView.svg),player_png:player.png?path.basename(player.png):null,debugger_png:debuggerView.png?path.basename(debuggerView.png):null,playable:'playable.html',trace:'trace.json',final_state:'final-state.json',rsr_commands:'rsr-command-batch.json',vsr_player:'vsr-player.json',vsr_debugger:'vsr-debugger.json',studio_import:'studio-import.json',causal_delta:'rfe-causal-delta.json'};
 const workspace=createWorkspace({runtime,outputs});writeJson(path.join(out,'program.json'),program);writeJson(path.join(out,'final-state.json'),{format:'reality-behavior.final-state.v0.1',program_root:program.program_root,state_root:finalRoot,state:runtime.state,replay_root:replayed.stateRoot(),recovered_root:recovered.stateRoot()});writeJson(path.join(out,'trace.json'),workspace.trace);writeJson(path.join(out,'rfe-causal-delta.json'),workspace.causal_delta);writeJson(path.join(out,'rsr-command-batch.json'),workspace.rsr_command_batch);writeJson(path.join(out,'vsr-player.json'),workspace.vsr.player);writeJson(path.join(out,'vsr-debugger.json'),workspace.vsr.debugger);writeJson(path.join(out,'studio-import.json'),workspace.studio_import);writeJson(path.join(out,'gateway-runtime-manifest.json'),workspace.gateway_manifest);writeJson(path.join(out,'workspace.json'),workspace);
 const hashes={};for(const f of fs.readdirSync(out).sort()){const full=path.join(out,f);if(fs.statSync(full).isFile())hashes[f]=rootHash(fs.readFileSync(full).toString('base64'));}writeJson(path.join(out,'output-hashes.json'),hashes);
 console.log(JSON.stringify({status:'PASS',out,tick:runtime.state.tick,state_root:finalRoot,score:runtime.state.globals.score,replay_root:replayed.stateRoot(),recovered_root:recovered.stateRoot(),tests:{program:report.valid,workspace:verifyWorkspace(workspace).valid}},null,2));
}
function verify(){const file=path.resolve(val('--workspace','outputs/frost-trial/workspace.json')),w=readJson(file),r=verifyWorkspace(w),dir=path.dirname(file),missing=[];for(const f of Object.values(w.outputs??{}))if(typeof f==='string'&&!fs.existsSync(path.join(dir,f)))missing.push(f);const ok=r.valid&&!missing.length&&w.summary?.victory===true;console.log(JSON.stringify({status:ok?'PASS':'FAIL',...r,missing},null,2));if(!ok)process.exitCode=1;}
function serve(){const dir=path.resolve(val('--dir','outputs/frost-trial')),port=Number(val('--port','4192'));const mime={'.html':'text/html;charset=utf-8','.js':'text/javascript;charset=utf-8','.json':'application/json;charset=utf-8','.png':'image/png','.svg':'image/svg+xml'};http.createServer((req,res)=>{let rel=decodeURIComponent((req.url??'/').split('?')[0]);if(rel==='/')rel='/playable.html';const file=path.resolve(dir,'.'+rel);if(!file.startsWith(dir)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'content-type':mime[path.extname(file)]??'application/octet-stream'});fs.createReadStream(file).pipe(res);}).listen(port,'127.0.0.1',()=>console.log(`Reality Behavior demo: http://127.0.0.1:${port}`));}
if(cmd==='demo')await demo();else if(cmd==='verify')verify();else if(cmd==='serve')serve();else{console.log('Usage: node src/cli.mjs demo|verify|serve');}
