#!/bin/bash
echo "========================================"
echo "    增強版RAG系統 - 已就緒"
echo "========================================"
echo ""
echo "📋 使用方法："
echo ""
echo "1. 增強版分析："
echo "   python3 main_enhanced.py <項目路徑>"
echo ""
echo "2. 監測系統："
echo "   python3 run_monitoring_system.py"
echo ""
echo "3. 增量處理："
echo "   python3 run_with_incremental_processing.py <項目路徑>"
echo ""
echo "4. 基礎分析："
echo "   python3 main.py <項目路徑>"
echo ""
echo "💡 示例："
echo "   python3 main_enhanced.py test_project/"
echo ""
echo "========================================"
