import {createHash} from 'node:crypto';

export const RSR_CHARACTER_BODY_PROFILE_FORMAT='rsr.character-body-profile.v0.1';
export const RSR_CHARACTER_BODY_PROFILE_VERSION='0.1.0-alpha.1';

const normalize=value=>{if(value===null||typeof value==='string'||typeof value==='boolean')return value;if(typeof value==='number')return Number.isFinite(value)?(Object.is(value,-0)?0:value):null;if(Array.isArray(value))return value.map(normalize);if(value&&typeof value==='object'){const out={};for(const key of Object.keys(value).sort())if(value[key]!==undefined)out[key]=normalize(value[key]);return out}return String(value)};
const rootHash=value=>createHash('sha256').update(JSON.stringify(normalize(value))).digest('hex');
const seal=(value,field='profile_root')=>{const source=structuredClone(value);delete source[field];return{...structuredClone(value),[field]:rootHash(source)}};
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));

export function createCharacterBodyProfile({genome,collisionProfile,physicsProfile,retargetProfile,rig}={}){
  if(!genome?.character_id||!collisionProfile?.profile_root||!physicsProfile?.profile_root||!retargetProfile?.profile_root)throw Object.assign(new Error('RSR_CHARACTER_BODY_INPUT_REQUIRED'),{code:'RSR_CHARACTER_BODY_INPUT_REQUIRED'});
  return seal({format:RSR_CHARACTER_BODY_PROFILE_FORMAT,version:RSR_CHARACTER_BODY_PROFILE_VERSION,profile_id:`character-body:${genome.character_id}`,character_id:genome.character_id,genome_root:genome.genome_root,identity_root:genome.identity_root,topology_family:genome.topology_family,body:{type:genome.physical_profile.body_type,height_m:genome.physical_profile.height_m,mass_kg:genome.physical_profile.mass_kg,units:'SI'},bindings:{collision_profile_root:collisionProfile.profile_root,physics_profile_root:physicsProfile.profile_root,retarget_profile_root:retargetProfile.profile_root,rig_root:rig.rig_root,bones:rig.bones.length,sockets:structuredClone(rig.sockets)},secondary_motion:{hair:{...structuredClone(physicsProfile.secondary_motion.hair),max_displacement_m:physicsProfile.constraints.max_hair_displacement_m},costume:{...structuredClone(physicsProfile.secondary_motion.costume),max_displacement_m:physicsProfile.constraints.max_coat_displacement_m}},director_override:{authority:'director',bounded:true,identity_mutation:'forbidden',allowed_layers:['hair','costume'],required:['frame_range','reason']},determinism:{seed:genome.lineage.seed,fixed_step:true},authority:{identity:'RNCS Character Genome',body_simulation:'RSR',asset_mutation:'forbidden'},quality_boundary:'Reference bounded secondary motion; production cloth, hair and collision tuning remain external gates',profile_root:''});
}

export function resolveCharacterBodyMotion(profile,{frame=0,overrides=[]}={}){
  const values={};for(const layer of ['hair','costume']){const settings=profile?.secondary_motion?.[layer]??{},override=[...overrides].filter(item=>item.layer===layer&&frame>=item.start_frame&&frame<=item.end_frame).at(-1);if(override&&!override.reason)throw Object.assign(new Error('RSR_CHARACTER_OVERRIDE_REASON_REQUIRED'),{code:'RSR_CHARACTER_OVERRIDE_REASON_REQUIRED'});const amplitude=clamp(Number(override?.amplitude??settings.max_displacement_m??0),0,Number(settings.max_displacement_m??0)),frequency=Number(override?.frequency??.21),phase=Number(override?.phase??(layer==='hair'?.13:.71));values[layer]=Math.sin(frame*frequency+phase)*amplitude;values[`${layer}_override`]=override?.override_id??null}const state={format:'rsr.character-body-motion-state.v0.1',character_id:profile.character_id,identity_root:profile.identity_root,frame,values,profile_root:profile.profile_root,authority:'RSR bounded; director overridable'};return{...state,state_root:rootHash(state)};
}

export function validateCharacterBodyProfile(profile){const errors=[];if(profile?.format!==RSR_CHARACTER_BODY_PROFILE_FORMAT)errors.push('RSR_CHARACTER_BODY_FORMAT_INVALID');if(profile?.version!==RSR_CHARACTER_BODY_PROFILE_VERSION)errors.push('RSR_CHARACTER_BODY_VERSION_INVALID');if((profile?.bindings?.bones??0)<20)errors.push('RSR_CHARACTER_RIG_INSUFFICIENT');if(!profile?.bindings?.collision_profile_root)errors.push('RSR_CHARACTER_COLLISION_REQUIRED');if(profile?.authority?.asset_mutation!=='forbidden')errors.push('RSR_CHARACTER_ASSET_AUTHORITY_INVALID');const copy=structuredClone(profile??{}),actual=copy.profile_root;delete copy.profile_root;if(actual!==rootHash(copy))errors.push('RSR_CHARACTER_BODY_ROOT_INVALID');return{valid:errors.length===0,errors,profile_root:profile?.profile_root??null};}
