import test from 'node:test';import assert from 'node:assert/strict';
import {lowerStudioSequenceFrame,evaluateAnimationFrame} from '../src/index.mjs';
function frame(presentation_state){return {format:'reality-studio.sequence-frame.v1.6',sequence_id:'s',time:.5,active:[],fired:[],authority_events:[{track_type:'behavior',clip_id:'b'}],presentation_state,authority_root:'auth',presentation_root:'present',frame_root:'frame'};}

test('Sequence adapter refuses implicit animation domain',()=>{const r=lowerStudioSequenceFrame(frame([{track_id:'a',track_type:'animation',clip_id:'clip',local_time:.5,progress:.5,payload:{animation:{clipId:'walk'}}}]));assert.equal(r.channels.length,0);assert.equal(r.unlowered[0].reason,'EXPLICIT_ANIMATION_FABRIC_DOMAIN_REQUIRED');});
test('Sequence adapter rejects authority escalation in presentation payload',()=>assert.throws(()=>lowerStudioSequenceFrame(frame([{track_id:'a',track_type:'animation',clip_id:'clip',payload:{animation_fabric:{domain:'3d',clipId:'walk',authoritative:true}}}])),/AUTHORITY_ESCALATION/));
test('3D channel lowers to VSR animation layers',()=>{const r=evaluateAnimationFrame(frame([{track_id:'a',track_type:'animation',clip_id:'clip',local_time:.25,progress:.25,payload:{animation_fabric:{domain:'3d',clipId:'walk',nodeIds:['hero'],weight:.8}}}]));assert.equal(r.three_d.animationLayers[0].clipId,'walk');assert.equal(r.three_d.animationLayers[0].weight,.8);assert.equal(r.source_authority_root,'auth');assert.equal(r.canonical_state_mutated,false);});
test('2D channel evaluates curves and path morph',()=>{const r=evaluateAnimationFrame(frame([{track_id:'a',track_type:'animation',clip_id:'clip2d',local_time:.5,progress:.5,payload:{animation_fabric:{domain:'2d',curves:{opacity:{keys:[{time:0,value:0},{time:1,value:1}]}},pathMorph:{from:[[0,0],[1,0]],to:[[0,1],[2,0]]}}}}]));assert.equal(r.two_d.states[0].sampled.opacity,.5);assert.deepEqual(r.two_d.states[0].pathResult,[[0,.5],[1.5,0]]);});
test('mixed 2D and 3D frame keeps one source frame authority root',()=>{const f=frame([{track_id:'a',track_type:'animation',clip_id:'a2',local_time:.2,payload:{animation_fabric:{domain:'2d',curves:{}}}},{track_id:'b',track_type:'animation',clip_id:'a3',local_time:.2,payload:{animation_fabric:{domain:'3d',clipId:'idle'}}}]);const r=evaluateAnimationFrame(f);assert.equal(r.two_d.states.length,1);assert.equal(r.three_d.animationLayers.length,1);assert.equal(r.source_authority_root,'auth');assert.match(r.frameRoot,/^[0-9a-f]{64}$/);});
test('non-animation presentation tracks remain delegated',()=>{const r=lowerStudioSequenceFrame(frame([{track_id:'camera',track_type:'camera',clip_id:'cam',payload:{camera_id:'camera:main'}}]));assert.equal(r.channels.length,0);assert.equal(r.unlowered[0].reason,'OWNED_BY_OTHER_PRESENTATION_RUNTIME');});
