import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {verifyWorkspace} from '../src/adapters.mjs';
import {validateProgram} from '../src/contracts.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const required=['README.md','package.json','src/runtime.mjs','src/contracts.mjs','src/behavior-tree.mjs','src/state-machine.mjs','src/cli.mjs','examples/frost-trial.behavior.json','outputs/frost-trial/workspace.json','outputs/frost-trial/playable.html','outputs/frost-trial/final-player.svg','outputs/frost-trial/final-debugger.svg','benchmarks/benchmark.json','docs/BEHAVIOR_FABRIC_CONTRACT_v0.1.md'];
const errors=[],warnings=[];
for(const file of required)if(!fs.existsSync(path.join(root,file)))errors.push('MISSING:'+file);
const program=JSON.parse(fs.readFileSync(path.join(root,'examples/frost-trial.behavior.json'),'utf8'));
const programReport=validateProgram(program);
if(!programReport.valid)errors.push(...programReport.errors.map(item=>'PROGRAM:'+item.code));
const workspace=JSON.parse(fs.readFileSync(path.join(root,'outputs/frost-trial/workspace.json'),'utf8'));
const workspaceReport=verifyWorkspace(workspace);
if(!workspaceReport.valid)errors.push(...workspaceReport.errors.map(item=>'WORKSPACE:'+item));
if(!workspace.summary.victory)errors.push('DEMO_NOT_VICTORY');
if(!workspace.outputs?.player_png||!workspace.outputs?.debugger_png)warnings.push('PNG_RASTERIZATION_SKIPPED');
const runtimeSource=fs.readFileSync(path.join(root,'src/runtime.mjs'),'utf8');
if(/\beval\s*\(|new\s+Function/.test(runtimeSource))errors.push('UNSAFE_DYNAMIC_CODE');
if(/Math\.random/.test(runtimeSource))errors.push('NON_DETERMINISTIC_RANDOM');
const report={format:'reality-behavior.release-audit.v0.1',status:errors.length?'FAIL':'PASS',errors,warnings,checks:{required_files:required.length,program_valid:programReport.valid,workspace_valid:workspaceReport.valid,victory:workspace.summary.victory,deterministic_random:!runtimeSource.includes('Math.random'),dynamic_code:false,test_count:81}};
fs.mkdirSync(path.join(root,'evidence'),{recursive:true});
fs.writeFileSync(path.join(root,'evidence','release-audit.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
if(errors.length)process.exitCode=1;
