import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import crypto from 'node:crypto';

function toolPath(name,explicit){const value=explicit??process.env[name.toUpperCase()+'_PATH']??name;if(explicit&&path.isAbsolute(explicit)&&!fs.existsSync(explicit))throw Object.assign(new Error(`MEDIA_TOOL_NOT_FOUND:${name}:${explicit}`),{code:'MEDIA_TOOL_NOT_FOUND'});return value}
export function sha256File(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')}

export function createDeterministicWav(file,{duration=5,sampleRate=48000}={}){const samples=Math.round(duration*sampleRate),data=Buffer.alloc(samples*2),frequency=196;for(let index=0;index<samples;index+=1){const time=index/sampleRate,voice=Math.sin(time*Math.PI*2*frequency)*.075,air=Math.sin(time*Math.PI*2*0.7)*.025,fade=Math.min(1,index/Math.max(1,sampleRate*.08),(samples-index)/Math.max(1,sampleRate*.08));data.writeInt16LE(Math.round((voice+air)*fade*32767),index*2)}const header=Buffer.alloc(44);header.write('RIFF',0);header.writeUInt32LE(36+data.length,4);header.write('WAVE',8);header.write('fmt ',12);header.writeUInt32LE(16,16);header.writeUInt16LE(1,20);header.writeUInt16LE(1,22);header.writeUInt32LE(sampleRate,24);header.writeUInt32LE(sampleRate*2,28);header.writeUInt16LE(2,32);header.writeUInt16LE(16,34);header.write('data',36);header.writeUInt32LE(data.length,40);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,Buffer.concat([header,data]));return{file,duration,sample_rate:sampleRate,sha256:sha256File(file)}}

export function muxMp4({framesDir,wavFile,outFile,fps=24,width=1280,height=720,ffmpegPath=null,ffprobePath=null}){const ffmpeg=toolPath('ffmpeg',ffmpegPath),probe=toolPath('ffprobe',ffprobePath);const args=['-y','-hide_banner','-loglevel','error','-framerate',String(fps),'-i',path.join(framesDir,'frame-%06d.png'),'-i',wavFile,'-c:v','libx264','-preset','veryfast','-pix_fmt','yuv420p','-s',`${width}x${height}`,'-r',String(fps),'-c:a','aac','-ar','48000','-ac','1','-shortest','-movflags','+faststart',outFile];const result=spawnSync(ffmpeg,args,{encoding:'utf8'});if(result.error?.code==='ENOENT')throw Object.assign(new Error(`MEDIA_TOOL_NOT_FOUND:ffmpeg:${ffmpeg}`),{code:'MEDIA_TOOL_NOT_FOUND'});if(result.status!==0)throw Object.assign(new Error(`FFMPEG_FAILED:${result.stderr??result.stdout??''}`),{code:'FFMPEG_FAILED'});const probeResult=spawnSync(probe,['-v','error','-print_format','json','-show_streams','-show_format',outFile],{encoding:'utf8'});if(probeResult.error?.code==='ENOENT')throw Object.assign(new Error(`MEDIA_TOOL_NOT_FOUND:ffprobe:${probe}`),{code:'MEDIA_TOOL_NOT_FOUND'});if(probeResult.status!==0)throw Object.assign(new Error(`FFPROBE_FAILED:${probeResult.stderr??''}`),{code:'FFPROBE_FAILED'});let report;try{report=JSON.parse(probeResult.stdout)}catch(error){throw Object.assign(new Error(`FFPROBE_JSON_INVALID:${error.message}`),{code:'FFPROBE_JSON_INVALID'})}const video=report.streams?.find(stream=>stream.codec_type==='video'),audio=report.streams?.find(stream=>stream.codec_type==='audio'),valid=Boolean(video&&audio&&Number(video.width)===width&&Number(video.height)===height&&String(video.r_frame_rate)===`${fps}/1`&&Number(audio.sample_rate)===48000);if(!valid)throw Object.assign(new Error('FFPROBE_MEDIA_CONTRACT_FAILED'),{code:'FFPROBE_MEDIA_CONTRACT_FAILED',report});return{outFile,mp4_sha256:sha256File(outFile),ffprobe:report,ffprobe_root:crypto.createHash('sha256').update(JSON.stringify(report)).digest('hex'),video:{width:video.width,height:video.height,fps:video.r_frame_rate,frames:Number(video.nb_frames??0),duration:Number(video.duration??0)},audio:{sample_rate:Number(audio.sample_rate),channels:Number(audio.channels),duration:Number(audio.duration??0)}}}
