export const OPEN_WORLD_RPG_VERSION='0.2.0-alpha.1';
export const OPEN_WORLD_RPG_PROTOCOL='rncs.open-world-rpg.v0.2';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const norm=(x,z)=>{const d=Math.hypot(x,z)||1;return{x:x/d,z:z/d}};
const clone=x=>JSON.parse(JSON.stringify(x));
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const rngFrom=s=>{let x=hash(s)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}};
export const SPELLS={
'fire-lance':{name:'火焰长枪',incantation:'火焰 长枪 穿刺',mana:18,damage:44,cooldown:1.3,range:24,kind:'projectile'},
'frost-aegis':{name:'寒霜护壁',incantation:'寒霜 护盾 环绕',mana:22,shield:58,cooldown:6,kind:'shield'},
'thunder-chain':{name:'雷霆锁链',incantation:'雷霆 锁链 追踪',mana:27,damage:34,cooldown:3.8,range:18,kind:'chain'},
'wind-step':{name:'风行步',incantation:'疾风 步伐 前行',mana:14,cooldown:2.5,distance:8,kind:'dash'},
'healing-light':{name:'治愈之光',incantation:'辉光 生命 复苏',mana:25,heal:48,cooldown:7,kind:'heal'},
'ember-nova':{name:'余烬新星',incantation:'余烬 星环 爆裂',mana:38,damage:65,cooldown:9,range:7,kind:'nova'}};
const ARCH={imp:['灰烬小鬼',70,9,3.2,18,1.8,18],wolf:['苔原猎狼',105,13,4.4,22,2.1,28],sentinel:['遗迹哨兵',165,18,2.6,20,2.4,48],warden:['熔心守卫',980,28,2.8,40,3.5,500,true]};
const mkEnemy=(type,id,x,z)=>{const a=ARCH[type];return{id,type,name:a[0],x,z,hp:a[1],maxHp:a[1],damage:a[2],speed:a[3],aggro:a[4],attackRange:a[5],xp:a[6],boss:!!a[7],alive:true,phase:1,attackCooldown:0,burn:0}};
export const normalizeIncantation=(t='')=>String(t).toLowerCase().replace(/[，。！？、·,.!?\s:_-]/g,'');
export function compileIncantation(text=''){const n=normalizeIncantation(text),rules=[['fire-lance',[['火焰','烈火','fire'],['长枪','枪','lance','穿刺']]],['frost-aegis',[['寒霜','冰霜','frost','ice'],['护盾','护壁','盾','shield']]],['thunder-chain',[['雷霆','闪电','thunder'],['锁链','链','chain','追踪']]],['wind-step',[['疾风','风','wind'],['步伐','前行','step','dash']]],['healing-light',[['辉光','治愈','生命','light'],['复苏','恢复','heal']]],['ember-nova',[['余烬','ember'],['星环','新星','nova'],['爆裂','burst']]]];for(const[id,groups]of rules)if(groups.every(g=>g.some(t=>n.includes(normalizeIncantation(t)))))return{ok:true,spellId:id,spell:SPELLS[id],confidence:.96,engine:'deterministic-token-grammar',llmCalls:0};return{ok:false,confidence:0,reason:'INCANTATION_NOT_RECOGNIZED',engine:'deterministic-token-grammar',llmCalls:0}}
const announce=(s,message)=>{s.announcements.unshift({time:s.time,message});s.announcements=s.announcements.slice(0,8);s.history.push({time:s.time,code:'ANNOUNCEMENT',message})};
export function createOpenWorld(o={}){const seed=String(o.seed||'ashen-frontier-3d-season0'),r=rngFrom(seed),enemies=[];let n=1;for(const p of[[32,24],[38,20],[43,29],[48,18],[51,34],[57,27]])enemies.push(mkEnemy('imp',`imp:${n++}`,...p));n=1;for(const p of[[58,49],[65,44],[69,56],[75,46]])enemies.push(mkEnemy('wolf',`wolf:${n++}`,...p));n=1;for(const p of[[82,67],[87,74],[91,63]])enemies.push(mkEnemy('sentinel',`sentinel:${n++}`,...p));enemies.push(mkEnemy('warden','warden:001',96,88));const names=['夜雨','白鸦','铸星者','风铃旅者','霜枝','赤砂','星轨','无声剑','青穹','旧梦','炉心','月湾','影鹿','渡火','银槲','静雷'];const npcPlayers=names.map((name,i)=>({id:`npc-player:${i+1}`,name,guild:['灰烬远征团','星纹学院','白鸦商会','无名旅团'][i%4],level:2+Math.floor(r()*12),role:['剑士','法师','游侠','神官'][i%4],x:8+r()*86,z:8+r()*86,targetX:8+r()*86,targetZ:8+r()*86,speed:1.4+r()*1.3}));const s={format:'rncs.open-world-rpg-state.v0.2',version:OPEN_WORLD_RPG_VERSION,protocol:OPEN_WORLD_RPG_PROTOCOL,seed,time:0,player:{name:o.name||'无名咏唱者',x:20,z:19,yaw:0,level:1,xp:0,xpNext:100,hp:140,maxHp:140,mana:100,maxMana:100,stamina:100,maxStamina:100,shield:0,gold:40,attackCooldown:0,comboWindow:0,comboStep:0,dodgeCooldown:0,invulnerable:0,knownSpells:['fire-lance','frost-aegis','wind-step','healing-light'],cooldowns:{},inventory:{potion:3,ashwood:0,iron:0,runeDust:0},focusCrafted:false},enemies,npcPlayers,projectiles:[],effects:[],announcements:[],history:[],quest:{stage:'meet-lyra',impKills:0,bossDefeated:false},world:{ruinsOpen:false,season:'Season 0',region:'灰烬边境',nextRegion:'浮空学院',nextRegionOpen:false,timeOfDay:.18},metrics:{swordSwings:0,spellCasts:0,voiceCasts:0,kills:0,llmCalls:0}};announce(s,'【世界公告】灰烬边境 Season 0 已开启。');return s}
export function movePlayer(s,i,dt){const p=s.player,v=norm(i.x||0,i.z||0),m=Math.min(1,Math.hypot(i.x||0,i.z||0)),speed=i.sprint&&p.stamina>0?8.5:5.5;p.x=clamp(p.x+v.x*speed*m*dt,2,108);p.z=clamp(p.z+v.z*speed*m*dt,2,108);if(m>.1)p.yaw=Math.atan2(v.x,v.z);p.stamina=clamp(p.stamina+(i.sprint&&m>.1?-14:19)*dt,0,p.maxStamina);return s}
function hurt(s,e,dmg,source='unknown'){if(!e||!e.alive)return false;e.hp-=dmg;if(e.hp>0)return false;e.hp=0;e.alive=false;s.metrics.kills++;s.player.xp+=e.xp;s.player.gold+=e.boss?140:5;if(e.type==='imp'){s.quest.impKills++;s.player.inventory.runeDust++}if(e.type==='wolf')s.player.inventory.ashwood++;if(e.type==='sentinel')s.player.inventory.iron++;if(e.boss){s.quest.bossDefeated=true;s.world.nextRegionOpen=true;announce(s,`【首杀公告】${s.player.name}击败了区域首领“熔心守卫”。`)}s.history.push({time:s.time,code:'ENEMY_DEFEATED',enemy:e.name,source});return true}
export function swordAttack(s,f={x:0,z:1}){const p=s.player;if(p.attackCooldown>0||p.stamina<10)return{ok:false,reason:'NOT_READY'};p.comboStep=p.comboWindow>0?p.comboStep%3+1:1;p.comboWindow=.74;p.attackCooldown=[0,.34,.38,.54][p.comboStep];p.stamina-=[0,10,12,18][p.comboStep];s.metrics.swordSwings++;const d=norm(f.x,f.z),range=3.1+p.comboStep*.15,hits=s.enemies.filter(e=>e.alive&&dist(p,e)<=range&&norm(e.x-p.x,e.z-p.z).x*d.x+norm(e.x-p.x,e.z-p.z).z*d.z>.2),damage=(30+p.level*4)*[0,1,1.18,1.62][p.comboStep];for(const e of hits)hurt(s,e,damage,`sword-combo-${p.comboStep}`);return{ok:true,comboStep:p.comboStep,damage,hits:hits.map(e=>e.id)}}
export function dodge(s,f={x:0,z:1}){const p=s.player;if(p.dodgeCooldown>0||p.stamina<24)return{ok:false,reason:'NOT_READY'};const d=norm(f.x,f.z);p.x=clamp(p.x+d.x*5.5,2,108);p.z=clamp(p.z+d.z*5.5,2,108);p.stamina-=24;p.dodgeCooldown=.85;p.invulnerable=.45;return{ok:true}}
export function castSpell(s,id,d={x:0,z:1},voice=false){const p=s.player,sp=SPELLS[id];if(!sp)return{ok:false,reason:'UNKNOWN_SPELL'};if(!p.knownSpells.includes(id))return{ok:false,reason:'SPELL_NOT_KNOWN'};if((p.cooldowns[id]||0)>0||p.mana<sp.mana)return{ok:false,reason:'NOT_READY'};p.mana-=sp.mana;p.cooldowns[id]=sp.cooldown;s.metrics.spellCasts++;if(voice)s.metrics.voiceCasts++;const v=norm(d.x,d.z);if(sp.kind==='projectile')s.projectiles.push({spellId:id,x:p.x,z:p.z,vx:v.x*18,vz:v.z*18,ttl:1.7,damage:sp.damage});if(sp.kind==='shield')p.shield=Math.max(p.shield,sp.shield);if(sp.kind==='heal')p.hp=clamp(p.hp+sp.heal,0,p.maxHp);if(sp.kind==='dash'){p.x=clamp(p.x+v.x*sp.distance,2,108);p.z=clamp(p.z+v.z*sp.distance,2,108)}if(sp.kind==='chain'||sp.kind==='nova')for(const e of s.enemies.filter(e=>e.alive&&dist(p,e)<=sp.range).slice(0,sp.kind==='chain'?3:99))hurt(s,e,sp.damage,id);return{ok:true,spellId:id}}
export function castIncantation(s,t,d={x:0,z:1}){const c=compileIncantation(t);return c.ok?{...c,result:castSpell(s,c.spellId,d,true)}:c}
export function craftRunicFocus(s){const i=s.player.inventory;if(i.ashwood<2||i.iron<2||i.runeDust<3)return{ok:false,reason:'MATERIALS_REQUIRED'};i.ashwood-=2;i.iron-=2;i.runeDust-=3;s.player.focusCrafted=true;s.world.ruinsOpen=true;return{ok:true}}
export function tick(s,dt){dt=clamp(Number(dt)||0,0,.1);s.time+=dt;const p=s.player;p.attackCooldown=Math.max(0,p.attackCooldown-dt);p.comboWindow=Math.max(0,p.comboWindow-dt);if(p.comboWindow<=0)p.comboStep=0;p.dodgeCooldown=Math.max(0,p.dodgeCooldown-dt);p.invulnerable=Math.max(0,p.invulnerable-dt);p.mana=clamp(p.mana+5*dt,0,p.maxMana);p.stamina=clamp(p.stamina+11*dt,0,p.maxStamina);for(const id of Object.keys(p.cooldowns))p.cooldowns[id]=Math.max(0,p.cooldowns[id]-dt);for(const e of s.enemies){if(!e.alive)continue;e.attackCooldown=Math.max(0,e.attackCooldown-dt);const d=dist(e,p);if(d<=e.attackRange&&e.attackCooldown<=0){e.attackCooldown=1.6;if(p.invulnerable<=0){let damage=e.damage,blocked=Math.min(p.shield,damage);p.shield-=blocked;p.hp=clamp(p.hp-damage+blocked,0,p.maxHp)}}}for(const q of s.projectiles){q.x+=q.vx*dt;q.z+=q.vz*dt;q.ttl-=dt;const e=s.enemies.find(e=>e.alive&&dist(q,e)<(e.boss?2.4:1.4));if(e){hurt(s,e,q.damage,q.spellId);q.ttl=0}}s.projectiles=s.projectiles.filter(q=>q.ttl>0);s.world.timeOfDay=(s.world.timeOfDay+dt/600)%1;return s}
export const snapshot=s=>clone(s);
