import assert from 'node:assert/strict';
import test from 'node:test';
import {seal} from '../../reality-asset-genesis-fabric/src/canonical.mjs';
import {applyAppearanceLoadout,applyStateOverlay,compareCharacterIdentitySignatures,createCharacterGenome,createCharacterIdentitySignature,validateCharacterGenome} from '../src/index.mjs';

const fails=(input,code)=>assert.throws(()=>createCharacterGenome(input),error=>error.code==='CHARACTER_CONSTRAINTS_INVALID'&&error.details.errors.some(item=>item.code===code));

test('unsafe jaw, eye, mouth, lip and chin combinations fail closed',()=>{fails({identity_parameters:{'face.jaw_definition':.99}},'PARAMETER_OUT_OF_SAFE_RANGE');fails({identity_parameters:{'face.eye_spacing':.1}},'PARAMETER_OUT_OF_SAFE_RANGE');fails({identity_parameters:{'face.jaw_width':.25,'face.mouth_width':.7}},'MOUTH_WIDTH_EXCEEDS_JAW');fails({identity_parameters:{'face.upper_lip':.7,'face.lower_lip':.72}},'LIP_VOLUME_COLLISION');fails({identity_parameters:{'face.jaw_definition':.2,'face.chin_projection':.6}},'CHIN_DETACHED_FROM_JAW')});
test('incompatible topology, hair and costume combinations fail closed',()=>{fails({topology_family:'youth-standard',appearance:{hair_family:'high-ponytail',costume_family:'urban-field-v1'}},'HAIR_TOPOLOGY_INCOMPATIBLE');fails({topology_family:'young-female-standard',appearance:{costume_family:'lan-default-v1'}},'COSTUME_TOPOLOGY_INCOMPATIBLE');fails({topology_family:'unknown-topology'},'TOPOLOGY_FAMILY_UNKNOWN')});
test('hair, palette and costume changes cannot rewrite identity or Character ID',()=>{const before=createCharacterGenome({name:'Actor',seed:'appearance-authority'}),after=applyAppearanceLoadout(before,{hair_family:'short-layered',palette_family:'graphite-red-white',costume_family:'urban-field-v1'});assert.equal(after.character_id,before.character_id);assert.equal(after.identity_root,before.identity_root);assert.equal(createCharacterIdentitySignature(after).signature_root,createCharacterIdentitySignature(before).signature_root)});
test('same seed is deterministic and state/expression cannot drift identity',()=>{const a=createCharacterGenome({name:'Actor',seed:'deterministic'}),b=createCharacterGenome({name:'Actor',seed:'deterministic'}),state=applyStateOverlay(a,{expression:'angry',injury:.4});assert.equal(a.genome_root,b.genome_root);assert.equal(a.identity_root,state.identity_root);assert.equal(createCharacterIdentitySignature(a).signature_root,createCharacterIdentitySignature(state).signature_root)});
test('multiple identity writers and unlocked continuity are rejected',()=>{const multiple=createCharacterGenome({provider_policy:{identity_writers:['RNCS Character Genome','provider:auto']}}),unlocked=createCharacterGenome({continuity_contract:{lock_identity:false}});assert.ok(validateCharacterGenome(multiple).errors.includes('MULTIPLE_IDENTITY_WRITERS_DENIED'));assert.ok(validateCharacterGenome(unlocked).errors.includes('IDENTITY_CONTINUITY_LOCK_REQUIRED'))});
test('viseme timelines must return to closed after final audio',()=>{const genome=createCharacterGenome(),tampered=seal({...genome,voice_binding:{...genome.voice_binding,close_mouth_on_end:false},genome_root:''},'genome_root');assert.ok(validateCharacterGenome(tampered).errors.includes('VISEME_CLOSE_MOUTH_REQUIRED'))});
test('user assets cannot be written into the core package',()=>{const genome=createCharacterGenome({lineage:{user_asset_paths:['packages/world/character-genome-runtime/private-face.glb']}});assert.ok(validateCharacterGenome(genome).errors.includes('USER_ASSET_CORE_PACKAGE_CONTAMINATION'))});
test('cross-character and topology drift fail continuity',()=>{const a=createCharacterIdentitySignature(createCharacterGenome({name:'A',seed:'a'})),b=createCharacterIdentitySignature(createCharacterGenome({name:'B',seed:'b',topology_family:'young-male-standard'})),report=compareCharacterIdentitySignatures(a,b);assert.equal(report.status,'fail');assert.equal(report.identity_mismatch,true)});
