import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import os from 'node:os';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import {RealityNetworkRuntime,issuePlayerDelegation,FORMATS,SnapshotInterpolator,createTwoPlayerWorldConfig} from '../src/index.mjs';
import {RealityOneGateway} from '../../../control/reality-one-gateway/src/index.mjs';

const CLOCK=()=> '2026-07-03T12:00:00.000Z';
async function setup({id='session:test',network={seed:1},joinB=true}={}){
  const runtime=new RealityNetworkRuntime();
  await runtime.createSession({sessionId:id,worldConfig:createTwoPlayerWorldConfig({worldId:`world:${id}`}),network,clock:CLOCK});
  await runtime.joinSession({sessionId:id,subjectId:'subject:a',playerId:'a',characterId:'character:blue',bodyId:'player-blue'});
  if(joinB)await runtime.joinSession({sessionId:id,subjectId:'subject:b',playerId:'b',characterId:'character:red',bodyId:'player-red'});
  return {runtime,ctx:runtime.require(id),id};
}
function drain(runtime,id,ticks=12){for(let i=0;i<ticks;i++)runtime.advanceServerTick({sessionId:id});}

test('two players keep one authoritative State Root after 60 ticks',async()=>{const {runtime,id}=await setup({id:'session:t1'});for(let i=0;i<60;i++){runtime.submitInput({sessionId:id,playerId:'a',command:{type:'move',x:i%2?1000000:0,z:i%2?0:1000000}});runtime.submitInput({sessionId:id,playerId:'b',command:{type:'move',x:i%3?-1000000:0,z:i%3?0:-1000000}});runtime.advanceServerTick({sessionId:id});}drain(runtime,id,8);const h=runtime.getSessionHealth({sessionId:id});assert.equal(h.server.tick,68);assert.equal(h.clients.a.clientStateRoot,h.server.stateRoot);assert.equal(h.clients.b.clientStateRoot,h.server.stateRoot);});
test('client prediction converges after server acknowledgement',async()=>{const {runtime,ctx,id}=await setup({id:'session:t2',joinB:false});runtime.submitInput({sessionId:id,playerId:'a',command:{type:'move',x:1000000,z:0}});assert.equal(ctx.clients.get('a').unacknowledged.length,1);drain(runtime,id,3);const h=runtime.getSessionHealth({sessionId:id});assert.equal(h.clients.a.unacknowledgedInputs,0);assert.equal(h.clients.a.clientStateRoot,h.server.stateRoot);});
test('20% packet loss eventually converges',async()=>{const {runtime,id}=await setup({id:'session:t3',network:{seed:77,lossRate:.2,fixedLatencyTicks:1,jitterTicks:1}});for(let i=0;i<35;i++){runtime.submitInput({sessionId:id,playerId:i%2?'a':'b',command:{type:'move',x:i%2?1000000:-1000000,z:0}});runtime.advanceServerTick({sessionId:id});}drain(runtime,id,120);const h=runtime.getSessionHealth({sessionId:id});assert.equal(h.clients.a.unacknowledgedInputs,0);assert.equal(h.clients.b.unacknowledgedInputs,0);assert.equal(h.clients.a.clientStateRoot,h.server.stateRoot);assert.equal(h.clients.b.clientStateRoot,h.server.stateRoot);});
test('out-of-order packets never roll back authoritative tick',async()=>{const {ctx}=await setup({id:'session:t4',joinB:false});const client=ctx.clients.get('a'),late=client.createInput({type:'move',x:1000000,z:0},{targetServerTick:5}),early=client.createInput({type:'move',x:0,z:1000000},{targetServerTick:2});assert.equal(ctx.server.submitInput(late).accepted,true);assert.equal(ctx.server.submitInput(early).accepted,true);let prev=ctx.server.rsrWorld.tick;for(let i=0;i<6;i++){ctx.server.advanceTick();assert.ok(ctx.server.rsrWorld.tick>prev);prev=ctx.server.rsrWorld.tick;}assert.equal(prev,6);});
test('duplicate input sequence executes once',async()=>{const {ctx}=await setup({id:'session:t5',joinB:false});const input=ctx.clients.get('a').createInput({type:'move',x:1000000,z:0});assert.equal(ctx.server.submitInput(input).accepted,true);assert.equal(ctx.server.submitInput(input).duplicate,true);ctx.server.advanceTick();assert.equal(ctx.server.seenSequences.get('a').size,1);assert.equal(ctx.server.accepted.length,1);});
test('player A cannot control player B',async()=>{const {ctx}=await setup({id:'session:t6'});const input=ctx.clients.get('a').createInput({type:'move',x:1,z:0});input.playerId='b';input.targetServerTick=1;const result=ctx.server.submitInput(input);assert.equal(result.accepted,false);assert.match(result.rejection.code,/SUBJECT|PLAYER|CHARACTER|AUTHORIZATION/);});
test('expired authorization is rejected',async()=>{const runtime=new RealityNetworkRuntime(),id='session:t7';await runtime.createSession({sessionId:id,worldConfig:createTwoPlayerWorldConfig(),clock:CLOCK});const delegation=issuePlayerDelegation({sessionId:id,subjectId:'subject:a',playerId:'a',characterId:'character:blue',issuedAt:'2020-01-01T00:00:00Z',expiresAt:'2021-01-01T00:00:00Z'});await runtime.joinSession({sessionId:id,subjectId:'subject:a',playerId:'a',characterId:'character:blue',bodyId:'player-blue',delegation});const input=runtime.require(id).clients.get('a').createInput({type:'move',x:1,z:0});const result=runtime.require(id).server.submitInput(input);assert.equal(result.rejection.code,'AUTHORIZATION_EXPIRED');});
test('late join receives a complete snapshot',async()=>{const {runtime,ctx,id}=await setup({id:'session:t8',joinB:false});drain(runtime,id,10);const joined=await runtime.joinSession({sessionId:id,subjectId:'subject:b',playerId:'b',characterId:'character:red',bodyId:'player-red'});assert.equal(joined.snapshot.tick,10);assert.ok(joined.snapshot.rsrSnapshot.bodies.length>=6);assert.equal(joined.snapshot.stateRoot,ctx.server.lastSnapshot.stateRoot);});
test('disconnect and reconnect preserves unacknowledged inputs',async()=>{const {runtime,ctx,id}=await setup({id:'session:t9',joinB:false});runtime.disconnect({sessionId:id,playerId:'a'});runtime.submitInput({sessionId:id,playerId:'a',command:{type:'move',x:1000000,z:0}});drain(runtime,id,4);assert.equal(ctx.clients.get('a').unacknowledged.length,1);runtime.reconnect({sessionId:id,playerId:'a'});drain(runtime,id,12);assert.equal(ctx.clients.get('a').unacknowledged.length,0);assert.equal(ctx.clients.get('a').world.snapshot().stateRoot,ctx.server.lastSnapshot.stateRoot);});
test('wrong prediction triggers snapshot restore and input replay',async()=>{const {runtime,ctx,id}=await setup({id:'session:t10',joinB:false});runtime.submitInput({sessionId:id,playerId:'a',command:{type:'move',x:1000000,z:0}});const client=ctx.clients.get('a');client.forcePredictionError(5000);const receipt=client.reconcile(ctx.server.pullSnapshot('test-correction'));assert.ok(receipt);assert.equal(receipt.format,FORMATS.correction);assert.ok(client.rollbackCount>=1);});
test('interpolation never modifies authoritative state',async()=>{const {ctx}=await setup({id:'session:t11'});const root=ctx.server.lastSnapshot.stateRoot,interpolator=new SnapshotInterpolator();interpolator.push(ctx.server.pullSnapshot());interpolator.sample('player-blue',ctx.server.rsrWorld.tick+10);assert.equal(ctx.server.lastSnapshot.stateRoot,root);});
test('severe desync creates isolated RBF recovery candidate',async()=>{const {runtime,ctx,id}=await setup({id:'session:t12'});drain(runtime,id,3);const candidate=runtime.createRecovery({sessionId:id,playerId:'a',reportedRoot:'fnv1a64:badbadbadbadbadb'});assert.equal(candidate.status,'candidate');assert.equal(candidate.workspace.branches[0].tags.includes('network-recovery'),true);assert.equal(ctx.server.lastSnapshot.stateRoot,candidate.trustedStateRoot);});
async function deterministicRun(id,seed){const {runtime,ctx}=await setup({id,network:{seed,lossRate:.1,duplicateRate:.15,reorderRate:.2,jitterTicks:2}});for(let i=0;i<25;i++){runtime.submitInput({sessionId:id,playerId:i%2?'a':'b',command:{type:'move',x:(i%3-1)*1000000,z:(i%2)*1000000}});runtime.advanceServerTick({sessionId:id});}drain(runtime,id,80);return {root:ctx.server.lastSnapshot.stateRoot,receipts:ctx.server.receipts.map(x=>x.networkReceiptRoot),seen:[...ctx.server.seenSequences.values()].reduce((n,s)=>n+s.size,0)};}
test('network receipts replay deterministically',async()=>{const a=await deterministicRun('session:t13',123),b=await deterministicRun('session:t13',123);assert.equal(a.receipts.length,b.receipts.length);assert.equal(a.receipts.at(-1),b.receipts.at(-1));});
test('same inputs and network seed produce same final root',async()=>{const a=await deterministicRun('session:t14',456),b=await deterministicRun('session:t14',456);assert.equal(a.root,b.root);assert.equal(a.seen,b.seen);});
test('Gateway discovers and invokes network runtime',async()=>{const here=path.dirname(fileURLToPath(import.meta.url)),manifestDir=path.resolve(here,'../../../control/reality-one-gateway/runtimes'),gateway=new RealityOneGateway({manifestDirs:[manifestDir],dataDir:fs.mkdtempSync(path.join(os.tmpdir(),'rncs-network-gateway-'))});const registry=await gateway.discover();assert.ok(registry.runtime_order.includes('rncs.network'));const health=await gateway.invoke('rncs.network','health',{});assert.equal(health.runtime_id,'rncs.network');});
test('server rejects direct client position submission',async()=>{const {ctx}=await setup({id:'session:t16',joinB:false});const input=ctx.clients.get('a').createInput({type:'move',x:1,z:0});input.position={x:999,y:999,z:999};const result=ctx.server.submitInput(input);assert.equal(result.rejection.code,'CLIENT_STATE_WRITE_FORBIDDEN');});
test('input beyond tick window is rejected',async()=>{const {ctx}=await setup({id:'session:t17',joinB:false});const input=ctx.clients.get('a').createInput({type:'move',x:1,z:0},{targetServerTick:999});const result=ctx.server.submitInput(input);assert.equal(result.rejection.code,'INPUT_TOO_FAR_FUTURE');});
test('burst loss recovery does not double execute inputs',async()=>{const {runtime,ctx,id}=await setup({id:'session:t18',network:{seed:18,burstLossEvery:7,burstLossLength:3,duplicateRate:.5}});for(let i=0;i<20;i++){runtime.submitInput({sessionId:id,playerId:'a',command:{type:'move',x:1000000,z:0}});runtime.advanceServerTick({sessionId:id});}drain(runtime,id,100);assert.equal(ctx.server.accepted.length,ctx.server.seenSequences.get('a').size);assert.equal(ctx.clients.get('a').unacknowledged.length,0);});
test('closed session invalidates old authorization',async()=>{const {runtime,ctx,id}=await setup({id:'session:t19',joinB:false});const input=ctx.clients.get('a').createInput({type:'move',x:1,z:0});runtime.closeSession({sessionId:id});const result=ctx.server.submitInput(input);assert.equal(result.rejection.code,'SESSION_NOT_OPEN');});
test('network module never creates a second authoritative RSR state',async()=>{const {runtime,ctx,id}=await setup({id:'session:t20'});drain(runtime,id,2);const h=runtime.getSessionHealth({sessionId:id});assert.equal(h.server.authoritativeWorldInstances,1);assert.equal(ctx.server.rsrWorld===ctx.clients.get('a').world,false);assert.equal(ctx.server.rsrWorld===ctx.clients.get('b').world,false);assert.equal(h.clients.a.clientStateRoot,h.server.stateRoot);});
