import { renderPng } from '../../backend-canvas/src/index.js';
import { evaluateAt, prepareDocument } from '../../core/src/index.js';
import { projectDisplayForObserver, verifyObserverProjectionSet, type VSRObserverProfile, type VSRObserverProjection } from '../../observer-projection/src/index.js';
import { documentHash, semanticHash, type VSRDocument, type VSRNode } from '../../spec/src/index.js';
import { Q, type ExperienceFabricConfig, type ExperienceSnapshot, type ParticleState, type ScreenSignal } from '../../experience-fabric/src/index.js';

export interface ExperienceVisualOptions { width?: number; height?: number; title?: string; background?: string; maxParticles?: number }
export interface ExperienceRenderView { observer: VSRObserverProfile; projection: VSRObserverProjection; png: Uint8Array; pngHash: string }
export interface ExperienceRenderSet { sourceDocumentHash: string; sourceDisplayHash: string; experienceRoot: string; invariantHash: string; verification: ReturnType<typeof verifyObserverProjectionSet>; views: ExperienceRenderView[] }

const debugPolicy = { format: 'vsr.observer-policy.v0.1', anyRole: ['debugger', 'auditor'], deny: 'hide', reason: 'experience-debug-only' };
const audioPolicy = { format: 'vsr.observer-policy.v0.1', anyRole: ['debugger', 'auditor', 'accessibility'], deny: 'hide', reason: 'experience-audio-captions' };
export function createExperienceObserverProfile(kind: 'player' | 'debugger' | 'auditor' | 'accessibility'): VSRObserverProfile {
  const debug = kind === 'debugger' || kind === 'auditor';
  return { format: 'vsr.observer-profile.v0.1', observerId: `experience:${kind}`, roles: [kind], scopes: debug ? ['experience.view', 'experience.debug', 'experience.evidence', 'diagnostics.read'] : kind === 'accessibility' ? ['experience.view', 'experience.audio-captions'] : ['experience.view'], clearance: debug ? 4 : kind === 'accessibility' ? 1 : 0 };
}
function rgba(p: ParticleState): string { return `rgba(${p.color.r},${p.color.g},${p.color.b},${Math.max(0, Math.min(1, p.color.a / 255))})`; }
function signal(snapshot: ExperienceSnapshot, type: ScreenSignal['type']): ScreenSignal | undefined { return snapshot.screenSignals.filter(s => s.type === type).sort((a, b) => b.intensityQ - a.intensityQ)[0]; }
function shakeOffset(snapshot: ExperienceSnapshot): { x: number; y: number } { const shake = signal(snapshot, 'shake'); if (!shake) return { x: 0, y: 0 }; const amount = shake.intensityQ / Q * 18; return { x: Math.sin(snapshot.tick * 2.399) * amount, y: Math.cos(snapshot.tick * 1.731) * amount }; }
function heroPosition(snapshot: ExperienceSnapshot, width: number, height: number): { x: number; y: number } { const sx = width / 960; const sy = height / 540; return { x: (snapshot.properties['hero.position.x'] ?? 326) * sx, y: (snapshot.properties['hero.position.y'] ?? 378) * sy }; }

export function experienceSnapshotToDocument(config: ExperienceFabricConfig, snapshot: ExperienceSnapshot, options: ExperienceVisualOptions = {}): VSRDocument {
  const width = options.width ?? 960; const height = options.height ?? 540; const sx = width / 960; const sy = height / 540; const scale = Math.min(sx, sy); const rawShake = shakeOffset(snapshot); const shake = { x: rawShake.x * sx, y: rawShake.y * sy }; const hero = heroPosition(snapshot, width, height); const nodes: VSRNode[] = [];
  nodes.push({ id: 'ground', type: 'rect', zIndex: 1, layout: { x: 0, y: height * 0.76, width, height: height * 0.24 }, appearance: { fill: { type: 'solid', color: '#0d1b2a' } } });
  nodes.push({ id: 'horizon', type: 'line', zIndex: 2, layout: { x: 0, y: 0, width, height }, content: { x1: 0, y1: height * 0.76, x2: width, y2: height * 0.76 }, appearance: { stroke: { type: 'solid', color: '#38bdf8' }, strokeWidth: 2, opacity: 0.35 } });
  for (let i = 0; i < 16; i++) nodes.push({ id: `ambient-star:${i}`, type: 'ellipse', zIndex: 0, layout: { x: (i * 137 + 43) % width, y: 30 + ((i * 83) % Math.floor(height * 0.55)), width: 2 + (i % 3), height: 2 + (i % 3) }, appearance: { fill: { type: 'solid', color: i % 2 ? '#7dd3fc' : '#c4b5fd' }, opacity: 0.55 } });
  nodes.push({ id: 'hero:body', type: 'ellipse', zIndex: 25, layout: { x: hero.x - 24 + shake.x, y: hero.y - 46 + shake.y, width: 48, height: 72 }, appearance: { fill: { type: 'solid', color: '#2563eb' }, stroke: { type: 'solid', color: '#dbeafe' }, strokeWidth: 2 } });
  nodes.push({ id: 'hero:head', type: 'ellipse', zIndex: 26, layout: { x: hero.x - 15 + shake.x, y: hero.y - 76 + shake.y, width: 30, height: 30 }, appearance: { fill: { type: 'solid', color: '#dbeafe' }, stroke: { type: 'solid', color: '#60a5fa' }, strokeWidth: 2 } });
  const pose = snapshot.skeletonPoses[0]; if (pose) for (const bone of pose.bones) nodes.push({ id: `bone:${bone.id}`, type: 'line', zIndex: 30, layout: { x: 0, y: 0, width, height }, content: { x1: hero.x + bone.worldPosition.x * sx + shake.x, y1: hero.y + bone.worldPosition.y * sy + shake.y, x2: hero.x + bone.endpoint.x * sx + shake.x, y2: hero.y + bone.endpoint.y * sy + shake.y }, appearance: { stroke: { type: 'solid', color: '#f8fafc' }, strokeWidth: bone.id.includes('sword') ? 5 : 4, lineCap: 'round' } });
  for (const particle of snapshot.particles.slice(0, options.maxParticles ?? 100)) { const size = Math.max(1, particle.sizeQ / Q * 14 * scale); nodes.push({ id: particle.id, type: 'ellipse', zIndex: particle.blend === 'additive' ? 60 : 50, layout: { x: particle.position.x * sx - size / 2 + shake.x, y: particle.position.y * sy - size / 2 + shake.y, width: size, height: size }, transform: { rotation: particle.rotation / Q * 360 }, appearance: { fill: { type: 'solid', color: rgba(particle) }, opacity: Math.max(0, Math.min(1, particle.opacityQ / Q)) }, tags: particle.tags }); }
  const flash = signal(snapshot, 'flash'); if (flash) { const color = flash.color ?? { r: 255, g: 255, b: 255, a: 255 }; nodes.push({ id: 'screen:flash', type: 'rect', zIndex: 100, layout: { x: 0, y: 0, width, height }, appearance: { fill: { type: 'solid', color: `rgba(${color.r},${color.g},${color.b},${color.a / 255})` }, opacity: Math.min(0.85, flash.intensityQ / Q) } }); }
  const chroma = signal(snapshot, 'chromatic-aberration'); if (chroma) { const alpha = Math.min(0.5, chroma.intensityQ / Q); nodes.push({ id: 'screen:chroma-left', type: 'line', zIndex: 90, layout: { x: 0, y: 0, width, height }, content: { x1: 4, y1: 0, x2: 4, y2: height }, appearance: { stroke: { type: 'solid', color: '#ef4444' }, strokeWidth: 8, opacity: alpha } }); nodes.push({ id: 'screen:chroma-right', type: 'line', zIndex: 90, layout: { x: 0, y: 0, width, height }, content: { x1: width - 4, y1: 0, x2: width - 4, y2: height }, appearance: { stroke: { type: 'solid', color: '#22d3ee' }, strokeWidth: 8, opacity: alpha } }); }
  const recentAudio = snapshot.audioEvents.filter(e => snapshot.tick - e.tick <= config.tickHz).slice(-3); nodes.push({ id: 'audio:caption', type: 'text', zIndex: 110, layout: { x: 20, y: height - 56, width: width - 40, height: 30 }, appearance: { fill: { type: 'solid', color: '#f8fafc' } }, content: { text: recentAudio.length ? `AUDIO: ${recentAudio.map(e => e.cueId).join(' / ')}` : 'AUDIO: SILENT', fontSize: 15 }, extensions: { 'vsr:observer-policy': audioPolicy } });
  nodes.push({ id: 'title', type: 'text', zIndex: 120, layout: { x: 18, y: 14, width: width - 36, height: 30 }, appearance: { fill: { type: 'solid', color: '#e0f2fe' } }, content: { text: options.title ?? 'RNCS TEMPORAL EXPERIENCE FABRIC', fontSize: 20 } });
  nodes.push({ id: 'debug:state', type: 'text', zIndex: 121, layout: { x: 18, y: 46, width: width - 36, height: 88 }, appearance: { fill: { type: 'solid', color: '#fbbf24' } }, content: { text: `tick=${snapshot.tick}  state=${snapshot.layerStates.map(s => `${s.layerId}:${s.currentState}`).join(' | ')}\nparticles=${snapshot.particles.length}  audio=${snapshot.audioEvents.length}  effects=${snapshot.effectInstances.length}\nroot=${snapshot.stateRoot}`, fontSize: 12 }, extensions: { 'vsr:observer-policy': debugPolicy } });
  for (const [index, event] of snapshot.events.slice(-6).entries()) nodes.push({ id: `debug:event:${event.id}:${index}`, type: 'text', zIndex: 122, layout: { x: width - 330, y: 48 + index * 18, width: 310, height: 18 }, appearance: { fill: { type: 'solid', color: '#c4b5fd' } }, content: { text: `${event.tick} · ${event.type} · ${event.source}`, fontSize: 11 }, extensions: { 'vsr:observer-policy': debugPolicy } });
  return { specVersion: '0.1', runtimeTarget: 'rsr-experience-fabric-v0.4', metadata: { id: `experience:${config.experienceId}:${snapshot.tick}`, title: options.title ?? config.experienceId, duration: 1, defaultFps: config.tickHz, seed: config.seed, description: 'Animation, audio and effects as multimodal projections of one causal reality.' }, canvas: { width, height, background: { type: 'solid', color: options.background ?? '#07111f' } }, variables: { tick: snapshot.tick, stateRoot: snapshot.stateRoot }, nodes, extensions: { 'rsr:experience-fabric': { format: config.format, experienceId: config.experienceId, configHash: snapshot.configHash, animationRoot: snapshot.animationRoot, audioPlanRoot: snapshot.audioPlanRoot, effectRoot: snapshot.effectRoot } } };
}

export class ExperienceFabricVSRBridge {
  constructor(readonly config: ExperienceFabricConfig, readonly options: ExperienceVisualOptions = {}) {}
  render(snapshot: ExperienceSnapshot, observers: VSRObserverProfile[]): ExperienceRenderSet {
    const document = experienceSnapshotToDocument(this.config, snapshot, this.options); const prepared = prepareDocument(document); const evaluated = evaluateAt({ document: prepared, time: 0, context: {} }); const invariant = { experienceId: snapshot.experienceId, tick: snapshot.tick, stateRoot: snapshot.stateRoot, animationRoot: snapshot.animationRoot, audioPlanRoot: snapshot.audioPlanRoot, effectRoot: snapshot.effectRoot }; const invariantHash = semanticHash(invariant); const projections = observers.map(observer => projectDisplayForObserver(document, evaluated.displayState, observer, { invariant })); const views = projections.map(projection => { const png = renderPng(projection.displayState); return { observer: projection.observer, projection, png, pngHash: semanticHash([...png]) }; }); return { sourceDocumentHash: documentHash(document), sourceDisplayHash: evaluated.displayState.semanticHash, experienceRoot: snapshot.stateRoot, invariantHash, verification: verifyObserverProjectionSet(projections), views };
  }
}
