import test from 'node:test';
import assert from 'node:assert/strict';
import os from 'node:os';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {compileAnimeSource,tryCompileAnimeSource,buildAnimeControlPlaneCandidate,bindVoicePerformance} from '../src/index.mjs';
import {renderCutFrame} from '../../../world/anime-production-runtime/src/index.mjs';

const example=fs.readFileSync(path.join(import.meta.dirname,'../examples/shenlinzhe-yanlv.rcl'),'utf8');
const editorialExample=fs.readFileSync(path.join(import.meta.dirname,'../examples/shenlinzhe-yanlv-editorial.rcl'),'utf8');
const microEpisode=fs.readFileSync(path.join(import.meta.dirname,'../examples/shenlinzhe-yanlv-micro-episode.rcl'),'utf8');

test('RCL Anime source compiles to IR, source map and core RCL bytecode',()=>{const result=compileAnimeSource(example);assert.equal(result.format,'rcl.anime-compiled-program.v0.1');assert.equal(result.production.cut.cut_id,'S01');assert.equal(result.production.cut.dialogue_track.length,1);assert.equal(result.production.cut.dialogue_track[0].text,'何罪之有？');assert.ok(result.source_map['cut.S01.dialogue.'+result.production.cut.dialogue_track[0].dialogue_event_id].line>0);assert.ok(result.bytecode_length>0);assert.match(result.shadow_rcl,/^reality AnimeForge_/)});
test('same Anime source produces the same compiled root across runs',()=>{const a=compileAnimeSource(example),b=compileAnimeSource(example);assert.equal(a.compiled_root,b.compiled_root);assert.equal(a.production.production_root,b.production.production_root)});
test('RCL Anime syntax errors retain source location',()=>{const result=tryCompileAnimeSource(example.replace('keypose 15f begin_raise_head','keypose 15f'));assert.equal(result.ok,false);assert.match(result.diagnostics[0].code,/^ANIME_/);assert.ok(result.diagnostics[0].location.line>0);assert.ok(result.diagnostics[0].location.column>0)});
test('finite animation is not silently converted to game-style interpolation',()=>{const result=compileAnimeSource(example);assert.equal(result.production.cut.animation.exposure,'on_twos');assert.equal(result.production.cut.key_pose_track.find(item=>item.pose_id==='gaze_locked').frame,28)});
test('VSR Anime Profile and RSR director override are executed and evidenced',()=>{const result=compileAnimeSource(example),profile=result.production.rendering_profile,motion=result.production.motion_profile;assert.equal(profile.format,'vsr.anime-rendering-profile.v0.1');assert.equal(motion.format,'rsr.anime-secondary-motion-profile.v0.1');assert.equal(motion.director_overrides.length,1);const frame=renderCutFrame(result.production,35,{width:320,height:180});assert.equal(frame.evidence.provider_receipts.some(item=>item.provider_id==='vsr.anime-reference-renderer'),true);assert.equal(frame.evidence.provider_receipts.some(item=>item.provider_id==='rsr.anime-secondary-motion-reference'),true);assert.equal(frame.state.director_overrides.hair,motion.director_overrides[0].override_id)});
test('Anime production enters RNCS control plane as a non-committing candidate',async()=>{const compiled=compileAnimeSource(example),candidate=await buildAnimeControlPlaneCandidate(compiled);assert.equal(candidate.format,'rncs.anime-control-plane-candidate.v0.1');assert.equal(candidate.status,'candidate');assert.equal(candidate.commit_permitted,false);assert.ok(candidate.candidate_branch.branch_id);assert.ok(candidate.state_root);assert.ok(candidate.authority_requirements.some(item=>item.action==='merge_candidate_branch'));assert.ok(candidate.evidence_requirements.length>0)});
test('RCL Anime compiler lowers every Scene Cut with per-Cut RAGF, VSR, and RSR bindings',()=>{const result=compileAnimeSource(editorialExample),production=result.production;assert.equal(production.cuts.length,2);assert.equal(production.editorial_timeline.total_frame_count,168);assert.deepEqual(production.editorial_timeline.cut_order,['EP01/无名城审判/S01','EP01/无名城审判/S02']);assert.equal(Object.keys(production.rendering_profiles).length,2);assert.equal(Object.keys(production.motion_profiles).length,2);assert.equal(result.asset_families.characters['character:蓝天临'].family.family_root,result.asset_families.character.family.family_root);assert.equal(production.cuts[0].character_layers[0].family_root,production.cuts[1].character_layers[0].family_root);assert.equal(production.cuts[1].dialogue_track[0].text,'无需多言。');assert.match(result.shadow_rcl,/anime\.cut_count : Number = 2/)});
test('Voice binding fails closed for an unknown dialogue event',()=>{const production=compileAnimeSource(example).production;assert.throws(()=>bindVoicePerformance(production,{dialogue_event_id:'dialogue:unknown'}),/DIALOGUE_EVENT_NOT_FOUND/)});
test('Phase 4 Micro-Episode compiles one authoritative Episode into three continuous derived Cuts',()=>{const result=compileAnimeSource(microEpisode),production=result.production,cuts=production.cuts,actorLayers=cuts.map(cut=>cut.character_layers[0]);assert.equal(cuts.length,3);assert.equal(production.editorial_timeline.total_duration_seconds,20);assert.equal(production.editorial_timeline.total_frame_count,480);assert.equal(production.authority_contract.episode_authoritative,true);assert.equal(production.authority_contract.cut_derived,true);assert.equal(cuts.every(cut=>cut.authority.derived_from_episode&&!cut.authority.creative_authority),true);assert.equal(new Set(actorLayers.map(layer=>layer.identity_root)).size,1);assert.equal(new Set(actorLayers.map(layer=>layer.genome_root)).size,1);assert.equal(new Set(actorLayers.map(layer=>layer.palette_root)).size,1);assert.equal(new Set(actorLayers.map(layer=>layer.proportion_root)).size,1);assert.equal(new Set(cuts.map(cut=>cut.layout)).size,3);assert.equal(cuts.flatMap(cut=>cut.secondary_motion_track).some(item=>item.layer==='breathing'),true);assert.equal(production.composition_contract.cut_contracts.length,3);for(const contract of production.composition_contract.cut_contracts){const profile=production.rendering_profiles[contract.cut_ref];assert.equal(contract.colour_anchor,profile.compositing.colour_anchor);assert.equal(contract.exposure_anchor,profile.exposure.anchor)}assert.equal(production.provider_bindings.asset,'ragf.anime-builtin-generator')});

test('CLI materializes nested RAGF motion PNGs as real binary media',()=>{const out=fs.mkdtempSync(path.join(os.tmpdir(),'rncs-anime-cli-assets-')),sourceFile=path.resolve(import.meta.dirname,'../examples/shenlinzhe-yanlv.rcl'),cli=path.resolve(import.meta.dirname,'../src/cli.mjs');try{execFileSync(process.execPath,[cli,'compile',sourceFile,'--out',out],{encoding:'utf8'});const matches=[];const visit=directory=>{for(const entry of fs.readdirSync(directory,{withFileTypes:true})){const file=path.join(directory,entry.name);if(entry.isDirectory())visit(file);else if(entry.name==='frame-0001.png')matches.push(file)}};visit(path.join(out,'assets'));assert.equal(matches.length>=1,true);const bytes=fs.readFileSync(matches[0]);assert.equal(bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),true);assert.ok(bytes.length>1000)}finally{fs.rmSync(out,{recursive:true,force:true})}});
