import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {compileAnimeSource,tryCompileAnimeSource,buildAnimeControlPlaneCandidate} from '../src/index.mjs';
import {renderCutFrame} from '../../../world/anime-production-runtime/src/index.mjs';

const example=fs.readFileSync(path.join(import.meta.dirname,'../examples/shenlinzhe-yanlv.rcl'),'utf8');

test('RCL Anime source compiles to IR, source map and core RCL bytecode',()=>{const result=compileAnimeSource(example);assert.equal(result.format,'rcl.anime-compiled-program.v0.1');assert.equal(result.production.cut.cut_id,'S01');assert.equal(result.production.cut.dialogue_track.length,1);assert.equal(result.production.cut.dialogue_track[0].text,'何罪之有？');assert.ok(result.source_map['cut.S01.dialogue.'+result.production.cut.dialogue_track[0].dialogue_event_id].line>0);assert.ok(result.bytecode_length>0);assert.match(result.shadow_rcl,/^reality AnimeForge_/)});
test('same Anime source produces the same compiled root across runs',()=>{const a=compileAnimeSource(example),b=compileAnimeSource(example);assert.equal(a.compiled_root,b.compiled_root);assert.equal(a.production.production_root,b.production.production_root)});
test('RCL Anime syntax errors retain source location',()=>{const result=tryCompileAnimeSource(example.replace('keypose 15f begin_raise_head','keypose 15f'));assert.equal(result.ok,false);assert.match(result.diagnostics[0].code,/^ANIME_/);assert.ok(result.diagnostics[0].location.line>0);assert.ok(result.diagnostics[0].location.column>0)});
test('finite animation is not silently converted to game-style interpolation',()=>{const result=compileAnimeSource(example);assert.equal(result.production.cut.animation.exposure,'on_twos');assert.equal(result.production.cut.key_pose_track.find(item=>item.pose_id==='gaze_locked').frame,28)});
test('VSR Anime Profile and RSR director override are executed and evidenced',()=>{const result=compileAnimeSource(example),profile=result.production.rendering_profile,motion=result.production.motion_profile;assert.equal(profile.format,'vsr.anime-rendering-profile.v0.1');assert.equal(motion.format,'rsr.anime-secondary-motion-profile.v0.1');assert.equal(motion.director_overrides.length,1);const frame=renderCutFrame(result.production,35,{width:320,height:180});assert.equal(frame.evidence.provider_receipts.some(item=>item.provider_id==='vsr.anime-reference-renderer'),true);assert.equal(frame.evidence.provider_receipts.some(item=>item.provider_id==='rsr.anime-secondary-motion-reference'),true);assert.equal(frame.state.director_overrides.hair,motion.director_overrides[0].override_id)});
test('Anime production enters RNCS control plane as a non-committing candidate',async()=>{const compiled=compileAnimeSource(example),candidate=await buildAnimeControlPlaneCandidate(compiled);assert.equal(candidate.format,'rncs.anime-control-plane-candidate.v0.1');assert.equal(candidate.status,'candidate');assert.equal(candidate.commit_permitted,false);assert.ok(candidate.candidate_branch.branch_id);assert.ok(candidate.state_root);assert.ok(candidate.authority_requirements.some(item=>item.action==='merge_candidate_branch'));assert.ok(candidate.evidence_requirements.length>0)});
