import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createLocalDiffusionProviderManifest,runLocalVisualProvider,resolveLocalVisualCommand} from '../src/index.mjs';
import {createCharacterReferencePack,createVisualConditionPack,createVisualModelManifest,CONDITION_TYPES,REFERENCE_VIEWS} from '../../../world/anime-production-runtime/src/index.mjs';

const completeReference=createCharacterReferencePack({character_id:'c',identity_root:'i',genome_root:'g',appearance_root:'a',lineage_root:'l',references:REFERENCE_VIEWS.map(view=>({view_id:view,path:`${view}.png`,media_type:'image/png',sha256:'a'.repeat(64)})),human_character_acceptance:'accepted',status:'ready'});
const completeConditions=createVisualConditionPack({episode_intent_root:'e',shot_intent_root:'s',character_identity_root:'i',reference_pack_root:completeReference.reference_pack_root,status:'complete',conditions:CONDITION_TYPES.map(type=>({type,status:'ready',root:`${type}-root`,path:`${type}.png`}))});
const completeModel=createVisualModelManifest({model_id:'m',model_revision:'r',weight_sha256:'b'.repeat(64),weight_bytes:10,license:{status:'declared',spdx:'Apache-2.0',source:'test'},status:'available'});

test('missing visual provider fails closed without falling back to procedural frames',()=>{const result=runLocalVisualProvider({episodeIntentRoot:'e',shotIntentRoot:'s',characterIdentityRoot:'i',referencePack:completeReference,conditionPack:completeConditions,modelManifest:completeModel,outDir:path.join(process.cwd(),'tmp','visual-provider-missing'),frameCount:2,executable:null});assert.equal(result.ok,false);assert.equal(result.code,'VISUAL_PROVIDER_MISSING');assert.equal(result.media,null);assert.equal(result.execution_receipt.authority.commit_write,false)});
test('model and license missing are rejected before external execution',()=>{const missing=createVisualModelManifest({status:'missing'}),result=runLocalVisualProvider({episodeIntentRoot:'e',shotIntentRoot:'s',characterIdentityRoot:'i',referencePack:completeReference,conditionPack:completeConditions,modelManifest:missing,outDir:path.join(process.cwd(),'tmp','visual-model-missing'),frameCount:2,executable:'definitely-not-a-provider'});assert.equal(result.ok,false);assert.equal(result.code,'MODEL_MISSING');assert.ok(result.model_validation.errors.includes('VISUAL_MODEL_LICENSE_MISSING'))});
test('timeout and OOM failure classifications remain blocked',()=>{for(const code of ['VISUAL_PROVIDER_TIMEOUT','VISUAL_PROVIDER_OOM']){const result=runLocalVisualProvider({episodeIntentRoot:'e',shotIntentRoot:'s',characterIdentityRoot:'i',referencePack:completeReference,conditionPack:completeConditions,modelManifest:completeModel,outDir:path.join(process.cwd(),'tmp',code),frameCount:2,executable:'worker',forceFailure:code});assert.equal(result.ok,false);assert.equal(result.code,code);assert.equal(result.status,'blocked')}});
test('malformed Provider arguments fail closed without executing a command',()=>{const previous=process.env.VISUAL_PROVIDER_ARGS_JSON;process.env.VISUAL_PROVIDER_ARGS_JSON='{bad-json';try{const command=resolveLocalVisualCommand({executable:'worker'});assert.equal(command.error,'VISUAL_PROVIDER_ARGS_INVALID');const result=runLocalVisualProvider({episodeIntentRoot:'e',shotIntentRoot:'s',characterIdentityRoot:'i',referencePack:completeReference,conditionPack:completeConditions,modelManifest:completeModel,outDir:path.join(process.cwd(),'tmp','visual-provider-args-invalid'),frameCount:2,executable:'worker'});assert.equal(result.ok,false);assert.equal(result.code,'VISUAL_PROVIDER_ARGS_INVALID')}finally{if(previous==null)delete process.env.VISUAL_PROVIDER_ARGS_JSON;else process.env.VISUAL_PROVIDER_ARGS_JSON=previous}});
