import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createLocalDiffusionProviderManifest,runLocalVisualProvider,resolveLocalVisualCommand} from '../src/index.mjs';
import {createCharacterReferencePack,createVisualConditionPack,createVisualModelManifest,CONDITION_TYPES,REFERENCE_VIEWS,encodePng} from '../../../world/anime-production-runtime/src/index.mjs';

const fixtureRoot=fs.mkdtempSync(path.join(os.tmpdir(),'anime-visual-provider-fixture-'));
const sha256=value=>crypto.createHash('sha256').update(value).digest('hex');
const png=(color)=>{const alternate=color.map(value=>Math.min(255,value+32));return encodePng(2,2,Buffer.from([...color,255,...alternate,255,...alternate,255,...color,255]))};
const referenceBytes=png([48,88,128]);
const blankBytes=encodePng(2,2,Buffer.from([64,64,64,255,64,64,64,255,64,64,64,255,64,64,64,255]));
const referenceRoot=path.join(fixtureRoot,'references'),conditionRoot=path.join(fixtureRoot,'conditions');fs.mkdirSync(referenceRoot,{recursive:true});fs.mkdirSync(conditionRoot,{recursive:true});
const completeReference=createCharacterReferencePack({character_id:'c',identity_root:'i',genome_root:'g',appearance_root:'a',lineage_root:'l',references:REFERENCE_VIEWS.map(view=>{const file=path.join(referenceRoot,`${view}.png`);fs.writeFileSync(file,referenceBytes);return{view_id:view,path:`references/${view}.png`,media_type:'image/png',sha256:sha256(referenceBytes),bytes:referenceBytes.length,placeholder:false}}),human_character_acceptance:'accepted',status:'ready'});
const completeConditions=createVisualConditionPack({episode_intent_root:'e',shot_intent_root:'s',character_identity_root:'i',reference_pack_root:completeReference.reference_pack_root,status:'complete',conditions:CONDITION_TYPES.map(type=>{const body=Buffer.from(`${type}\n`),file=path.join(conditionRoot,`${type}.json`);fs.writeFileSync(file,body);return{type,status:'ready',root:`${type}-root`,path:`conditions/${type}.json`,sha256:sha256(body)}})});
const modelBytes=Buffer.from('licensed-test-model-weight');
const modelPath=path.join(fixtureRoot,'model.bin');fs.writeFileSync(modelPath,modelBytes);
const completeModel=createVisualModelManifest({model_id:'m',model_revision:'r',weight_path:modelPath,weight_sha256:sha256(modelBytes),weight_bytes:modelBytes.length,license:{status:'declared',spdx:'Apache-2.0',source:'test'},status:'available'});
const baseInput={episodeIntentRoot:'e',shotIntentRoot:'s',characterIdentityRoot:'i',referencePack:completeReference,conditionPack:completeConditions,modelManifest:completeModel,referenceRoot:fixtureRoot,conditionRoot:fixtureRoot};

test('missing visual provider fails closed without falling back to procedural frames',()=>{const result=runLocalVisualProvider({...baseInput,outDir:path.join(fixtureRoot,'missing-provider'),frameCount:2,executable:null});assert.equal(result.ok,false);assert.equal(result.code,'VISUAL_PROVIDER_MISSING');assert.equal(result.media,null);assert.equal(result.execution_receipt.authority.commit_write,false)});
test('model and license missing are rejected before external execution',()=>{const missing=createVisualModelManifest({status:'missing'}),result=runLocalVisualProvider({...baseInput,modelManifest:missing,outDir:path.join(fixtureRoot,'visual-model-missing'),frameCount:2,executable:'definitely-not-a-provider'});assert.equal(result.ok,false);assert.equal(result.code,'MODEL_MISSING');assert.ok(result.model_validation.errors.includes('VISUAL_MODEL_LICENSE_MISSING'))});
test('timeout and OOM failure classifications remain blocked',()=>{for(const code of ['VISUAL_PROVIDER_TIMEOUT','VISUAL_PROVIDER_OOM']){const result=runLocalVisualProvider({...baseInput,outDir:path.join(fixtureRoot,code),frameCount:2,executable:'worker',forceFailure:code});assert.equal(result.ok,false);assert.equal(result.code,code);assert.equal(result.status,'blocked')}});
test('malformed Provider arguments fail closed without executing a command',()=>{const previous=process.env.VISUAL_PROVIDER_ARGS_JSON;process.env.VISUAL_PROVIDER_ARGS_JSON='{bad-json';try{const command=resolveLocalVisualCommand({executable:'worker'});assert.equal(command.error,'VISUAL_PROVIDER_ARGS_INVALID');const result=runLocalVisualProvider({...baseInput,outDir:path.join(fixtureRoot,'visual-provider-args-invalid'),frameCount:2,executable:'worker'});assert.equal(result.ok,false);assert.equal(result.code,'VISUAL_PROVIDER_ARGS_INVALID')}finally{if(previous==null)delete process.env.VISUAL_PROVIDER_ARGS_JSON;else process.env.VISUAL_PROVIDER_ARGS_JSON=previous}});

function worker(mode,count){const file=path.join(fixtureRoot,`${mode}-worker.mjs`);const body=`import fs from 'node:fs';\nimport path from 'node:path';\nconst output=process.argv[process.argv.indexOf('--output')+1];\nconst png=Buffer.from('${png([48,88,128]).toString('base64')}','base64');\nconst png2=Buffer.from('${png([160,190,220]).toString('base64')}','base64');\nconst blank=Buffer.from('${blankBytes.toString('base64')}','base64');\nfs.mkdirSync(output,{recursive:true});\n${Array.from({length:count},(_,index)=>`fs.writeFileSync(path.join(output,'frame-${String(index+1).padStart(6,'0')}.png'),${mode==='repeat'?'png':mode==='blank'?'blank':index%2?'png2':'png'});`).join('\n')}`;fs.writeFileSync(file,body);return file}

test('real external worker output is accepted only with complete nonblank temporal frames',()=>{const result=runLocalVisualProvider({...baseInput,outDir:path.join(fixtureRoot,'valid-worker-output'),frameCount:2,executable:process.execPath,args:[worker('valid',2)]});assert.equal(result.ok,true,result.code);assert.equal(result.media.frame_count,2);assert.equal(result.temporal.status,'pass');assert.ok(fs.existsSync(result.media.frame_manifest))});
test('blank and repeated external frames fail temporal validation',()=>{for(const mode of ['blank','repeat']){const result=runLocalVisualProvider({...baseInput,outDir:path.join(fixtureRoot,`${mode}-output`),frameCount:2,executable:process.execPath,args:[worker(mode,2)]});assert.equal(result.ok,false,mode);assert.equal(result.code,'TEMPORAL_VALIDATION_FAILED');assert.equal(result.media,null)}});
test('external worker with the wrong frame count fails before media closure',()=>{const result=runLocalVisualProvider({...baseInput,outDir:path.join(fixtureRoot,'wrong-count-output'),frameCount:2,executable:process.execPath,args:[worker('wrong-count',1)]});assert.equal(result.ok,false);assert.equal(result.code,'FRAME_SEQUENCE_FILES_MISSING');assert.equal(result.media,null)});
