import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {readJson,verifyBuild,writeJson,verifySeal} from '../src/index.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),checks=[];const check=(name,ok,detail='')=>checks.push({name,ok:Boolean(ok),detail});
const required=['README.md','LICENSE','CHANGELOG.md','STATUS.md','开发验收报告.md','RELEASE_NOTES_v0.2.0-alpha.1.md','docs/NAMING_BOUNDARY_INVERSION_BUILD_FABRIC_v0.1.md','docs/BUILD_FABRIC_CONTRACT_v0.2.md','docs/TARGET_MATRIX_v0.2.md','docs/NATIVE_PACKAGING_ARCHITECTURE_v0.2.md','docs/IAL_现实构建织构_自执行提示词.md','schemas/reality-build-request.v0.2.schema.json','examples/冰境试炼.unified-project.json','examples/资产对账记录.json'];for(const f of required)check(`required:${f}`,fs.existsSync(path.join(root,f)));
const out=path.join(root,'output','冰境试炼-release'),verification=verifyBuild(out);check('sample-build-verifies',verification.valid,verification.errors);
if(verification.valid){check('five-targets',verification.receipt.targets.length===5,verification.receipt.targets.map(x=>x.target));check('deterministic-outputs',verification.receipt.deterministic_outputs===true);check('core-files',verification.receipt.core_files.length===5);check('preflight-root',typeof verification.receipt.preflight_root==='string');}
const preflightFile=path.join(out,'build-preflight.json');check('preflight-evidence',fs.existsSync(preflightFile));if(fs.existsSync(preflightFile)){const p=readJson(preflightFile);check('preflight-ready',p.status==='ready',p.blocked);check('preflight-seal',verifySeal(p,'preflight_root'));}
const browserFile=path.join(root,'evidence','BROWSER_ACCEPTANCE_v0.2.json');check('browser-evidence',fs.existsSync(browserFile));if(fs.existsSync(browserFile)){const b=readJson(browserFile);check('browser-pass',b.pass===true);check('three-browser-hosts',b.results?.length===3);check('browser-roots-equal',new Set(b.results.map(x=>x.outcome.state_root)).size===1);}
const android=path.join(out,'android-project','android-build-manifest.json');check('android-manifest',fs.existsSync(android));if(fs.existsSync(android)){const a=readJson(android);check('android-honest-boundary',a.apk_built===false&&a.artifact_status==='source-project');check('android-build-script',a.automatic_build_script===true&&fs.existsSync(path.join(out,'android-project','构建调试APK.bat')));}
const winPortable=path.join(out,'windows-portable','app-manifest.json');check('windows-portable-manifest',fs.existsSync(winPortable));if(fs.existsSync(winPortable))check('windows-portable-boundary',readJson(winPortable).native_executable===false);
const winDir=path.join(out,'windows-native'),winManifest=path.join(winDir,'app-manifest.json'),winExe=path.join(winDir,'冰境试炼.exe');check('windows-native-manifest',fs.existsSync(winManifest));check('windows-native-exe',fs.existsSync(winExe));if(fs.existsSync(winManifest)){const w=readJson(winManifest);check('windows-native-declared',w.native_executable===true&&w.external_node_required===false&&w.render_backend==='system-browser-app-mode');}if(fs.existsSync(winExe)){const b=fs.readFileSync(winExe);check('windows-pe-header',b.subarray(0,2).toString()==='MZ');check('windows-exe-size',b.length>500000,b.length);}
const bench=path.join(root,'evidence','BENCHMARK_v0.2.json');check('benchmark-evidence',fs.existsSync(bench));
const pkg=readJson(path.join(root,'package.json'));check('package-version',pkg.version==='0.2.0-alpha.1');
const result={format:'reality-build.release-audit.v0.2',version:'0.2.0-alpha.1',ok:checks.every(x=>x.ok),checks,failures:checks.filter(x=>!x.ok)};writeJson(path.join(root,'evidence','RELEASE_AUDIT_v0.2.json'),result);fs.writeFileSync(path.join(root,'evidence','RELEASE_AUDIT_OUTPUT_v0.2.txt'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));if(!result.ok)process.exitCode=1;
