import fs from 'node:fs';
import path from 'node:path';
import {performance} from 'node:perf_hooks';
import {clone,rootHash,seal,stableId} from '../../reality-asset-genesis-fabric/src/canonical.mjs';
import {assertValidCharacterGenome,createCharacterIdentitySignature,createCrossMediaContinuityReport,analyzeCharacterGenomeImpact,createIncrementalRebuildReceipt} from '../../character-genome-runtime/src/index.mjs';
import {generateCharacterGeometrySet} from './geometry.mjs';
import {generateCharacterProjectionAssets,generateCharacterTextureAssets} from './projections.mjs';
import {createCharacterQualityReport,validateCharacterAssetFamily} from './quality.mjs';
import {createCharacterVisualProfile} from '../../visual-state-runtime/src/character-profile.mjs';
import {createCharacterBodyProfile} from '../../reality-simulation-runtime/src/character-body.mjs';

const MIME={'.json':'application/json','.glb':'model/gltf-binary','.png':'image/png','.svg':'image/svg+xml'};
const hashBuffer=buffer=>rootHash(buffer.toString('base64'));
const fileRecord=(file,role,buffer)=>({path:file,role,mime:MIME[path.extname(file)]??'application/octet-stream',size:buffer.length,root:hashBuffer(buffer)});
const jsonBuffer=value=>Buffer.from(JSON.stringify(value,null,2));
const safe=value=>String(value).replace(/[^a-zA-Z0-9_.-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'character';
const write=(base,file,buffer)=>{const target=path.resolve(base,file);if(!target.startsWith(path.resolve(base)))throw new Error(`OUTPUT_PATH_INVALID:${file}`);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,buffer)};

export function createCharacterReferenceProviderReceipt(genome){return seal({format:'ragf.character-provider-receipt.v0.1',provider_id:'ragf.character-genome-reference-provider',version:'0.1.0-alpha.1',mode:'reference-offline',capabilities:['character-genome.solve','character-phenotype.compile','character.glb','character.lod','character.morphs','character.modular-hair','character.modular-costume','character.native-2d','character.2.5d','character.3d-assisted-2d'],input_root:genome.genome_root,authority:'candidate-only',identity_authority:'RNCS Character Genome',license:'Apache-2.0',quality_tier:'reference-digital-actor-v0.1',cloud_calls:false,receipt_root:''},'receipt_root')}

function collisionProfile(genome,geometrySet){const d=geometrySet.main.metadata.dimensions,height=d.height,shoulder=d.shoulder_width;return seal({format:'rsr.character-collision-profile.v0.1',character_id:genome.character_id,units:'meters',fixtures:[{id:'body',role:'solid',type:'capsule',center:[0,height*.49,0],radius:shoulder*.42,height:height*.9},{id:'head',role:'hit-region',type:'sphere',center:[0,height*.91,0],radius:d.head_height*.48},{id:'hair',role:'secondary-motion-collision',type:'sphere',center:[0,height*.91,.01],radius:d.head_height*.55},{id:'garment',role:'cloth-collision',type:'capsule',center:[0,height*.52,0],radius:shoulder*.55,height:height*.68},{id:'weapon',role:'attachment-clearance',type:'capsule',from:[shoulder*.4,height*.52,.08],to:[shoulder*.65,height*.84,.08],radius:.045}],quality:{eye_inside_head:true,mouth_inside_face:true,hair_clearance_m:.006,garment_clearance_m:.008,severe_intersection:false},profile_root:''},'profile_root')}
function physicsProfile(genome){return seal({format:'rsr.character-physics-profile.v0.1',character_id:genome.character_id,body:{kind:'dynamic-character',mass_kg:genome.physical_profile.mass_kg,height_m:genome.physical_profile.height_m},secondary_motion:{hair:{profile:genome.appearance_loadout.hair_family,damping:.72,stiffness:.48,director_override:true},costume:{profile:genome.appearance_loadout.costume_family,damping:.78,stiffness:.56,director_override:true}},constraints:{max_hair_displacement_m:.12,max_coat_displacement_m:.16,deterministic:true},profile_root:''},'profile_root')}
function retargetProfile(genome,rig){return seal({format:'ragf.character-retarget-profile.v0.1',character_id:genome.character_id,source_profile:rig.profile,target_profiles:['rncs.anime-humanoid-v0.1','rsr.humanoid-character-v0.1'],bone_map:Object.fromEntries(rig.bones.map(item=>[item.name,item.name])),required_bones:['root','hips','spine','chest','neck','head','jaw','arm_l','arm_r','leg_l','leg_r'],facial_channels:{jaw:'jaw',visemes:genome.voice_binding.visemes,expressions:genome.expression_profile.morphs},director_override:true,profile_root:''},'profile_root')}

function buildRecords(genome){
  const timings={},mark=(name,start)=>{timings[name]=Math.round((performance.now()-start)*1000)/1000};let started=performance.now(),geometrySet=generateCharacterGeometrySet(genome);mark('mesh_morph_and_lod_ms',started);
  started=performance.now();const projections=generateCharacterProjectionAssets(genome);mark('projection_ms',started);started=performance.now();const textures=generateCharacterTextureAssets(genome);mark('material_generation_ms',started);
  const signature=createCharacterIdentitySignature(genome),providerReceipt=createCharacterReferenceProviderReceipt(genome);for(const mode of projections.modes)mode.identity_signature_root=signature.signature_root;const continuity=createCrossMediaContinuityReport(signature,projections.modes),collision=collisionProfile(genome,geometrySet),physics=physicsProfile(genome),retarget=retargetProfile(genome,geometrySet.rig),visualProfile=createCharacterVisualProfile({genome,identitySignature:signature,projectionModes:projections.modes}),bodyProfile=createCharacterBodyProfile({genome,collisionProfile:collision,physicsProfile:physics,retargetProfile:retarget,rig:geometrySet.rig});
  const records={},buffers={};const add=(file,role,buffer)=>{buffers[file]=buffer;records[file]=fileRecord(file,role,buffer)};const addJson=(file,role,value)=>add(file,role,jsonBuffer(value));
  add('character.glb','character-glb',geometrySet.main.buffer);for(const item of geometrySet.lods)add(`character-lod${item.lod}.glb`,`character-lod${item.lod}`,item.buffer);for(const [part,item] of Object.entries(geometrySet.modules))add(`${part}.glb`,`${part}-module`,item.buffer);
  for(const item of Object.values(textures))add(item.path,item.role,item.buffer);for(const item of Object.values(projections.files))add(item.path,item.role,item.buffer);
  const morphs=geometrySet.main.metadata.morph_stats;addJson('identity_signature.json','identity-signature',signature);addJson('genome.json','character-genome',genome);addJson('phenotype.json','character-phenotype',{format:'ragf.character-phenotype.v0.1',character_id:genome.character_id,genome_root:genome.genome_root,identity_root:genome.identity_root,topology_family:genome.topology_family,resolved_dimensions:geometrySet.main.metadata.dimensions,appearance:genome.appearance_loadout,modules:{body:geometrySet.modules.body.metadata.glb_root,face:geometrySet.modules.face.metadata.glb_root,hair:geometrySet.modules.hair.metadata.glb_root,costume:geometrySet.modules.costume.metadata.glb_root}});addJson('rig.json','rig',geometrySet.rig);addJson('morph-map.json','morph-map',{format:'ragf.character-morph-map.v0.1',identity:morphs.filter(item=>item.category==='identity'),semantic_parameter_graph_root:genome.semantic_morph_graph.graph_root});addJson('expression-map.json','expression-map',{format:'ragf.character-expression-map.v0.1',expressions:morphs.filter(item=>item.category==='expression'),composition:{identity_preserved:true,additive:true,neutral_restore:true}});addJson('viseme-map.json','viseme-map',{format:'ragf.character-viseme-map.v0.1',visemes:morphs.filter(item=>item.category==='viseme'),jaw_channel:'jaw',authority:'final-dialogue-audio',close_mouth_on_end:true});addJson('collision-profile.json','collision-profile',collision);addJson('physics-profile.json','physics-profile',physics);addJson('retarget-profile.json','retarget-profile',retarget);addJson('voice-binding.json','voice-binding',genome.voice_binding);addJson('provider-receipt.json','provider-receipt',providerReceipt);addJson('continuity-report.json','continuity-report',continuity);addJson('vsr-character-profile.json','vsr-character-profile',visualProfile);addJson('rsr-character-body-profile.json','rsr-character-body-profile',bodyProfile);
  return{records,buffers,geometrySet,projections,signature,providerReceipt,continuity,collision,physics,retarget,visualProfile,bodyProfile,timings};
}

export function compileCharacterPhenotype(genome,{outDir,provider='reference'}={}){
  if(!outDir)throw Object.assign(new Error('CHARACTER_OUTPUT_DIRECTORY_REQUIRED'),{code:'CHARACTER_OUTPUT_DIRECTORY_REQUIRED'});assertValidCharacterGenome(genome);if(provider!=='reference')throw Object.assign(new Error(`CHARACTER_PROVIDER_NOT_CONFIGURED:${provider}`),{code:'CHARACTER_PROVIDER_NOT_CONFIGURED'});
  const totalStart=performance.now(),built=buildRecords(genome),quality=createCharacterQualityReport({genome,geometrySet:built.geometrySet,records:built.records,continuity:built.continuity,providerReceipt:built.providerReceipt});built.buffers['quality-report.json']=jsonBuffer(quality);built.records['quality-report.json']=fileRecord('quality-report.json','quality-report',built.buffers['quality-report.json']);
  const files=Object.values(built.records).sort((a,b)=>a.path.localeCompare(b.path)),assetRoot=rootHash({genome_root:genome.genome_root,identity_signature_root:built.signature.signature_root,provider_receipt_root:built.providerReceipt.receipt_root,files:files.map(({path,role,mime,size,root})=>({path,role,mime,size,root}))}),manifest=seal({format:'ragf.character-asset-manifest.v0.1',version:'0.1.0-alpha.1',asset_id:genome.character_id,asset_root:assetRoot,genome_root:genome.genome_root,identity_signature_root:built.signature.signature_root,files,manifest_root:''},'manifest_root'),lineage=seal({format:'ragf.character-lineage.v0.1',character_id:genome.character_id,genome_root:genome.genome_root,asset_root:assetRoot,parents:clone(genome.lineage.parents),seed:genome.lineage.seed,provider_receipt_root:built.providerReceipt.receipt_root,source_assets:clone(genome.lineage.source_assets),user_assets_external:true,lineage_root:''},'lineage_root');
  const lods=built.geometrySet.lods.map(item=>({lod:item.lod,file:`character-lod${item.lod}.glb`,root:item.metadata.glb_root,triangles:item.metadata.triangle_count,vertices:item.metadata.vertex_count})),family=seal({format:'ragf.character-asset-family.v0.1',version:'0.1.0-alpha.1',asset_family_id:stableId('character-asset-family',{character:genome.character_id,assetRoot}),character_id:genome.character_id,genome_id:genome.genome_id,genome_root:genome.genome_root,identity_root:genome.identity_root,identity_signature:built.signature,asset_root:assetRoot,topology_family:genome.topology_family,quality_tier:'reference-digital-actor-v0.1',appearance:clone(genome.appearance_loadout),palette:clone(genome.style_genome.palette),proportions:clone(built.geometrySet.main.metadata.dimensions),identity_descriptors:clone(genome.identity_genome.descriptors),modules:{body:built.geometrySet.modules.body.metadata.glb_root,face:built.geometrySet.modules.face.metadata.glb_root,hair:built.geometrySet.modules.hair.metadata.glb_root,costume:built.geometrySet.modules.costume.metadata.glb_root},lods,counts:{identity_parameters:genome.identity_genome.identity_parameters?Object.keys(genome.identity_genome.identity_parameters).length:0,identity_morphs:built.geometrySet.main.metadata.identity_morph_count,expressions:built.geometrySet.main.metadata.expression_morph_count,visemes:built.geometrySet.main.metadata.viseme_morph_count,bones:built.geometrySet.rig.bones.length,hair_families:6,costume_families:3,topology_families:4},cross_media:{modes:built.projections.modes,continuity_report_root:built.continuity.report_root},runtime_profiles:{vsr:{file:'vsr-character-profile.json',profile_root:built.visualProfile.profile_root},rsr:{file:'rsr-character-body-profile.json',profile_root:built.bodyProfile.profile_root}},continuity:{status:built.continuity.status,report_root:built.continuity.report_root,identity_signature_root:built.signature.signature_root},provider_receipt:built.providerReceipt,license:'Apache-2.0',manifest:{manifest_root:manifest.manifest_root,files:manifest.files},lineage:{lineage_root:lineage.lineage_root},quality:{valid:quality.valid,report_root:quality.report_root},family_root:''},'family_root');
  const deterministicReceipt={format:'ragf.character-build-receipt.v0.1',character_id:genome.character_id,genome_root:genome.genome_root,asset_root:assetRoot,family_root:family.family_root,manifest_root:manifest.manifest_root,provider_receipt_root:built.providerReceipt.receipt_root,quality_report_root:quality.report_root,status:quality.valid?'candidate-built':'candidate-rejected',authority:'RAGF candidate; RNCS commit required',receipt_root:''},receipt=seal(deterministicReceipt,'receipt_root'),performanceReport={format:'ragf.character-build-performance.v0.1',...built.timings,total_ms:Math.round((performance.now()-totalStart)*1000)/1000,peak_rss_bytes:process.memoryUsage().rss,cache_hit_rate:0,measurement_boundary:'single local Node.js reference-provider run'},evidence=seal({format:'rncs.character-evidence-ledger.v0.1',character_id:genome.character_id,genome_root:genome.genome_root,identity_root:genome.identity_root,identity_signature_root:built.signature.signature_root,asset_root:assetRoot,family_root:family.family_root,manifest_root:manifest.manifest_root,lineage_root:lineage.lineage_root,provider_receipt_root:built.providerReceipt.receipt_root,build_receipt_root:receipt.receipt_root,quality_report_root:quality.report_root,continuity_report_root:built.continuity.report_root,gates:{genome:true,constraints:genome.constraint_report.valid,geometry:quality.gates.geometry.pass,identity:quality.gates.identity.pass,expression:quality.gates.expression.pass,animation:quality.gates.animation.pass,render:quality.gates.render.pass,asset:quality.gates.asset.pass},status:quality.valid?'candidate-evidence-complete':'candidate-rejected',commit_authority:'RNCS Character Genome Authority',commit_permitted:false,boundary:'Reference Provider evidence only; commercial art, actor and target-device acceptance remain external gates',ledger_root:''},'ledger_root');
  for(const [file,buffer] of Object.entries(built.buffers))write(outDir,file,buffer);for(const [file,value] of [['manifest.json',manifest],['lineage.json',lineage],['family.json',family],['build-receipt.json',receipt],['performance.json',performanceReport],['evidence.json',evidence]])write(outDir,file,jsonBuffer(value));
  const validation=validateCharacterAssetFamily(family,{baseDir:outDir,verifyFiles:true});return{family,manifest,lineage,quality,evidence,receipt,performance:performanceReport,validation,out_dir:path.resolve(outDir),records:built.records,geometry_set:built.geometrySet};
}

export function verifyCharacterAssetDirectory(outDir){
  const family=JSON.parse(fs.readFileSync(path.join(outDir,'family.json'),'utf8')),manifest=JSON.parse(fs.readFileSync(path.join(outDir,'manifest.json'),'utf8')),errors=[];for(const file of manifest.files){const target=path.resolve(outDir,file.path);if(!target.startsWith(path.resolve(outDir))||!fs.existsSync(target)){errors.push(`FILE_MISSING:${file.path}`);continue}if(hashBuffer(fs.readFileSync(target))!==file.root)errors.push(`FILE_ROOT_MISMATCH:${file.path}`)}const familyValidation=validateCharacterAssetFamily(family,{baseDir:outDir,verifyFiles:true});errors.push(...familyValidation.errors);return seal({format:'rncs.character-verification-report.v0.1',ok:errors.length===0,errors,warnings:familyValidation.warnings,asset_root:family.asset_root,family_root:family.family_root,identity_signature_root:family.identity_signature.signature_root,verified_files:manifest.files.length,report_root:''},'report_root');
}

export function replayCharacterAsset(genome,{outDir,replayDir=path.join(outDir,'.replay')}={}){const before=JSON.parse(fs.readFileSync(path.join(outDir,'family.json'),'utf8')),replayed=compileCharacterPhenotype(genome,{outDir:replayDir}),valid=before.asset_root===replayed.family.asset_root&&before.identity_signature.signature_root===replayed.family.identity_signature.signature_root;return seal({format:'rncs.character-replay-report.v0.1',valid,before_asset_root:before.asset_root,replayed_asset_root:replayed.family.asset_root,before_identity_signature_root:before.identity_signature.signature_root,replayed_identity_signature_root:replayed.family.identity_signature.signature_root,replay_dir:path.resolve(replayDir),report_root:''},'report_root')}

export function snapshotCharacterAsset(outDir,id='snapshot'){
  const snapshotId=safe(id),snapshotDir=path.join(outDir,'snapshots',snapshotId),manifest=JSON.parse(fs.readFileSync(path.join(outDir,'manifest.json'),'utf8')),files=[...manifest.files.map(item=>item.path),'manifest.json','family.json','lineage.json','build-receipt.json','quality-report.json','evidence.json','performance.json'];fs.mkdirSync(snapshotDir,{recursive:true});for(const file of files){const source=path.join(outDir,file);if(fs.existsSync(source)){const target=path.join(snapshotDir,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(source,target)}}const receipt=seal({format:'rncs.character-snapshot-receipt.v0.1',snapshot_id:snapshotId,asset_root:manifest.asset_root,file_count:files.length,snapshot_dir:path.resolve(snapshotDir),receipt_root:''},'receipt_root');write(snapshotDir,'snapshot-receipt.json',jsonBuffer(receipt));return receipt;
}

export function rollbackCharacterAsset(outDir,id){
  const snapshotId=safe(id),snapshotDir=path.join(outDir,'snapshots',snapshotId);if(!fs.existsSync(snapshotDir))throw Object.assign(new Error(`CHARACTER_SNAPSHOT_NOT_FOUND:${snapshotId}`),{code:'CHARACTER_SNAPSHOT_NOT_FOUND'});const manifest=JSON.parse(fs.readFileSync(path.join(snapshotDir,'manifest.json'),'utf8')),files=[...manifest.files.map(item=>item.path),'manifest.json','family.json','lineage.json','build-receipt.json','quality-report.json','evidence.json','performance.json'];for(const file of files){const source=path.join(snapshotDir,file);if(fs.existsSync(source))write(outDir,file,fs.readFileSync(source))}const family=JSON.parse(fs.readFileSync(path.join(outDir,'family.json'),'utf8')),receipt=seal({format:'rncs.character-rollback-receipt.v0.1',snapshot_id:snapshotId,status:'restored-character-asset-family',asset_root:family.asset_root,identity_signature_root:family.identity_signature.signature_root,restored_files:files.length,receipt_root:''},'receipt_root');write(outDir,'rollback-receipt.json',jsonBuffer(receipt));return receipt;
}

function rebuildMaterialAndProjections(afterGenome,{outDir,scope}){
  assertValidCharacterGenome(afterGenome);
  const totalStart=performance.now(),beforeFamily=JSON.parse(fs.readFileSync(path.join(outDir,'family.json'),'utf8')),beforeManifest=JSON.parse(fs.readFileSync(path.join(outDir,'manifest.json'),'utf8')),quality=JSON.parse(fs.readFileSync(path.join(outDir,'quality-report.json'),'utf8')),beforePhenotype=JSON.parse(fs.readFileSync(path.join(outDir,'phenotype.json'),'utf8')),records=Object.fromEntries(beforeManifest.files.map(item=>[item.path,clone(item)])),buffers={};
  const add=(file,role,buffer)=>{buffers[file]=buffer;records[file]=fileRecord(file,role,buffer)};
  const addJson=(file,role,value)=>add(file,role,jsonBuffer(value));
  const existingRoots=Object.fromEntries(beforeManifest.files.map(item=>[item.path,item.root]));
  let started=performance.now(),projections=generateCharacterProjectionAssets(afterGenome,{colorOnly:true,existingRoots}),projectionMs=Math.round((performance.now()-started)*1000)/1000;
  started=performance.now();const textures=generateCharacterTextureAssets(afterGenome),materialMs=Math.round((performance.now()-started)*1000)/1000;
  const signature=createCharacterIdentitySignature(afterGenome);
  if(signature.signature_root!==beforeFamily.identity_signature.signature_root)throw Object.assign(new Error('INCREMENTAL_IDENTITY_DRIFT'),{code:'INCREMENTAL_IDENTITY_DRIFT'});
  for(const mode of projections.modes)mode.identity_signature_root=signature.signature_root;
  const continuity=createCrossMediaContinuityReport(signature,projections.modes),providerReceipt=createCharacterReferenceProviderReceipt(afterGenome),collision=JSON.parse(fs.readFileSync(path.join(outDir,'collision-profile.json'),'utf8')),physics=JSON.parse(fs.readFileSync(path.join(outDir,'physics-profile.json'),'utf8')),retarget=JSON.parse(fs.readFileSync(path.join(outDir,'retarget-profile.json'),'utf8')),rig=JSON.parse(fs.readFileSync(path.join(outDir,'rig.json'),'utf8')),visualProfile=createCharacterVisualProfile({genome:afterGenome,identitySignature:signature,projectionModes:projections.modes}),bodyProfile=createCharacterBodyProfile({genome:afterGenome,collisionProfile:collision,physicsProfile:physics,retargetProfile:retarget,rig});
  for(const item of Object.values(textures))add(item.path,item.role,item.buffer);
  for(const item of Object.values(projections.files))add(item.path,item.role,item.buffer);
  addJson('genome.json','character-genome',afterGenome);
  addJson('phenotype.json','character-phenotype',{...beforePhenotype,genome_root:afterGenome.genome_root,appearance:clone(afterGenome.appearance_loadout)});
  addJson('provider-receipt.json','provider-receipt',providerReceipt);
  addJson('continuity-report.json','continuity-report',continuity);
  addJson('vsr-character-profile.json','vsr-character-profile',visualProfile);
  addJson('rsr-character-body-profile.json','rsr-character-body-profile',bodyProfile);
  const files=Object.values(records).sort((a,b)=>a.path.localeCompare(b.path)),assetRoot=rootHash({genome_root:afterGenome.genome_root,identity_signature_root:signature.signature_root,provider_receipt_root:providerReceipt.receipt_root,files:files.map(({path,role,mime,size,root})=>({path,role,mime,size,root}))}),manifest=seal({format:'ragf.character-asset-manifest.v0.1',version:'0.1.0-alpha.1',asset_id:afterGenome.character_id,asset_root:assetRoot,genome_root:afterGenome.genome_root,identity_signature_root:signature.signature_root,files,manifest_root:''},'manifest_root'),lineage=seal({format:'ragf.character-lineage.v0.1',character_id:afterGenome.character_id,genome_root:afterGenome.genome_root,asset_root:assetRoot,parents:clone(afterGenome.lineage.parents),seed:afterGenome.lineage.seed,provider_receipt_root:providerReceipt.receipt_root,source_assets:clone(afterGenome.lineage.source_assets),user_assets_external:true,lineage_root:''},'lineage_root');
  const family=seal({...clone(beforeFamily),asset_family_id:stableId('character-asset-family',{character:afterGenome.character_id,assetRoot}),genome_id:afterGenome.genome_id,genome_root:afterGenome.genome_root,asset_root:assetRoot,appearance:clone(afterGenome.appearance_loadout),palette:clone(afterGenome.style_genome.palette),cross_media:{modes:projections.modes,continuity_report_root:continuity.report_root},runtime_profiles:{vsr:{file:'vsr-character-profile.json',profile_root:visualProfile.profile_root},rsr:{file:'rsr-character-body-profile.json',profile_root:bodyProfile.profile_root}},continuity:{status:continuity.status,report_root:continuity.report_root,identity_signature_root:signature.signature_root},provider_receipt:providerReceipt,manifest:{manifest_root:manifest.manifest_root,files:manifest.files},lineage:{lineage_root:lineage.lineage_root},family_root:''},'family_root'),receipt=seal({format:'ragf.character-build-receipt.v0.1',character_id:afterGenome.character_id,genome_root:afterGenome.genome_root,asset_root:assetRoot,family_root:family.family_root,manifest_root:manifest.manifest_root,provider_receipt_root:providerReceipt.receipt_root,quality_report_root:quality.report_root,status:quality.valid?'candidate-built':'candidate-rejected',authority:'RAGF candidate; RNCS commit required',incremental_scope:scope,receipt_root:''},'receipt_root');
  const changed=files.filter(item=>beforeManifest.files.find(old=>old.path===item.path)?.root!==item.root).length,cacheHits=files.length-changed,performanceReport={format:'ragf.character-build-performance.v0.1',mesh_morph_and_lod_ms:0,rig_build_ms:0,material_generation_ms:materialMs,projection_ms:projectionMs,total_ms:Math.round((performance.now()-totalStart)*1000)/1000,peak_rss_bytes:process.memoryUsage().rss,cache_hit_rate:files.length?cacheHits/files.length:0,cache_hits:cacheHits,cache_misses:changed,measurement_boundary:`incremental ${scope} rebuild; geometry and rig read from content cache`},evidence=seal({format:'rncs.character-evidence-ledger.v0.1',character_id:afterGenome.character_id,genome_root:afterGenome.genome_root,identity_root:afterGenome.identity_root,identity_signature_root:signature.signature_root,asset_root:assetRoot,family_root:family.family_root,manifest_root:manifest.manifest_root,lineage_root:lineage.lineage_root,provider_receipt_root:providerReceipt.receipt_root,build_receipt_root:receipt.receipt_root,quality_report_root:quality.report_root,continuity_report_root:continuity.report_root,gates:{genome:true,constraints:afterGenome.constraint_report.valid,geometry:quality.gates.geometry.pass,identity:quality.gates.identity.pass,expression:quality.gates.expression.pass,animation:quality.gates.animation.pass,render:quality.gates.render.pass,asset:quality.gates.asset.pass},status:quality.valid?'candidate-evidence-complete':'candidate-rejected',commit_authority:'RNCS Character Genome Authority',commit_permitted:false,boundary:'Reference Provider evidence only; geometry reused by hash, commercial art and target-device acceptance remain external gates',ledger_root:''},'ledger_root');
  for(const [file,buffer] of Object.entries(buffers))write(outDir,file,buffer);
  for(const [file,value] of [['manifest.json',manifest],['lineage.json',lineage],['family.json',family],['build-receipt.json',receipt],['performance.json',performanceReport],['evidence.json',evidence]])write(outDir,file,jsonBuffer(value));
  const validation=validateCharacterAssetFamily(family,{baseDir:outDir,verifyFiles:true});
  return{family,manifest,lineage,quality,evidence,receipt,performance:performanceReport,validation,out_dir:path.resolve(outDir),records,geometry_set:null};
}

export function rebuildCharacterPhenotype(beforeGenome,afterGenome,{outDir,changePath}={}){
  const beforeFamily=JSON.parse(fs.readFileSync(path.join(outDir,'family.json'),'utf8')),beforeRoots=Object.fromEntries(beforeFamily.manifest.files.map(item=>[item.path,item.root])),impact=analyzeCharacterGenomeImpact(beforeGenome,{change_path:changePath}),start=performance.now(),next=['hair-material','palette','state-overlay'].includes(impact.scope)?rebuildMaterialAndProjections(afterGenome,{outDir,scope:impact.scope}):compileCharacterPhenotype(afterGenome,{outDir}),afterRoots=Object.fromEntries(next.family.manifest.files.map(item=>[item.path,item.root])),receipt=createIncrementalRebuildReceipt({beforeGenome,afterGenome,impact,beforeRoots,afterRoots,durationMs:Math.round((performance.now()-start)*1000)/1000,cacheHits:Object.keys(beforeRoots).filter(key=>beforeRoots[key]===afterRoots[key]).length,cacheMisses:Object.keys(afterRoots).filter(key=>beforeRoots[key]!==afterRoots[key]).length});write(outDir,'incremental-rebuild-receipt.json',jsonBuffer(receipt));return{...next,impact,rebuild_receipt:receipt};
}
