import fs from 'node:fs';
import path from 'node:path';
import {rootHash,seal,verifySeal} from '../../reality-asset-genesis-fabric/src/canonical.mjs';
import {validateCharacterGenome} from '../../character-genome-runtime/src/index.mjs';

const finiteArray=values=>Array.isArray(values)&&values.every(Number.isFinite);
const triangleArea=(p,a,b,c)=>{const ax=p[b*3]-p[a*3],ay=p[b*3+1]-p[a*3+1],az=p[b*3+2]-p[a*3+2],bx=p[c*3]-p[a*3],by=p[c*3+1]-p[a*3+1],bz=p[c*3+2]-p[a*3+2];return Math.hypot(ay*bz-az*by,az*bx-ax*bz,ax*by-ay*bx)/2};
const weldedIndex=positions=>{const ids=new Map(),result=[];for(let index=0;index<positions.length;index+=3){const key=`${Math.round(positions[index]*1e5)},${Math.round(positions[index+1]*1e5)},${Math.round(positions[index+2]*1e5)}`;if(!ids.has(key))ids.set(key,ids.size);result.push(ids.get(key))}return result};

export function inspectCharacterGeometry(encoded){
  const g=encoded.geometry,errors=[],warnings=[];
  if(!finiteArray(g.positions)||!finiteArray(g.normals)||!finiteArray(g.uvs)||!finiteArray(g.weights))errors.push('GEOMETRY_NON_FINITE');
  if(g.indices.some(index=>index<0||index>=g.positions.length/3))errors.push('GEOMETRY_INDEX_OUT_OF_RANGE');
  let thin=0;const faces=new Set(),duplicates=[];for(let index=0;index<g.indices.length;index+=3){const face=[g.indices[index],g.indices[index+1],g.indices[index+2]],key=[...face].sort((a,b)=>a-b).join(':');if(faces.has(key))duplicates.push(key);faces.add(key);if(triangleArea(g.positions,...face)<1e-9)thin++}
  if(duplicates.length)errors.push('GEOMETRY_DUPLICATE_FACES');if(thin)errors.push('GEOMETRY_THIN_TRIANGLES');
  let badNormals=0;for(let index=0;index<g.normals.length;index+=3){const length=Math.hypot(g.normals[index],g.normals[index+1],g.normals[index+2]);if(Math.abs(length-1)>.01)badNormals++}if(badNormals)errors.push('GEOMETRY_NORMAL_INVALID');
  let badWeights=0;for(let index=0;index<g.weights.length;index+=4){const sum=g.weights[index]+g.weights[index+1]+g.weights[index+2]+g.weights[index+3],influences=g.weights.slice(index,index+4).filter(value=>value>0).length;if(Math.abs(sum-1)>1e-6||influences>4)badWeights++}if(badWeights)errors.push('SKIN_WEIGHT_INVALID');
  const weld=weldedIndex(g.positions),edges=new Map();for(let index=0;index<g.indices.length;index+=3){const face=[weld[g.indices[index]],weld[g.indices[index+1]],weld[g.indices[index+2]]];for(const [a,b] of [[face[0],face[1]],[face[1],face[2]],[face[2],face[0]]]){const key=a<b?`${a}:${b}`:`${b}:${a}`;edges.set(key,(edges.get(key)??0)+1)}}const boundary=[...edges.values()].filter(count=>count!==2).length;if(boundary)errors.push('GEOMETRY_NON_MANIFOLD');
  const morphs=encoded.metadata.morph_stats??[],inactive=morphs.filter(item=>item.nonzero_vertex_count===0||item.max_delta<=0);if(inactive.length)errors.push('MORPH_TARGET_INACTIVE');
  return{valid:errors.length===0,errors,warnings,metrics:{vertices:g.positions.length/3,triangles:g.indices.length/3,thin_triangles:thin,duplicate_faces:duplicates.length,non_manifold_edges:boundary,bad_normals:badNormals,bad_weights:badWeights,morph_targets:morphs.length,active_morph_targets:morphs.length-inactive.length}};
}

export function createCharacterQualityReport({genome,geometrySet,records,continuity,providerReceipt}){
  const genomeValidation=validateCharacterGenome(genome),lodChecks=geometrySet.lods.map(item=>inspectCharacterGeometry(item)),triangles=geometrySet.lods.map(item=>item.metadata.triangle_count),roots=geometrySet.lods.map(item=>item.metadata.glb_root),main=inspectCharacterGeometry(geometrySet.main),errors=[...genomeValidation.errors,...main.errors,...lodChecks.flatMap(item=>item.errors)];
  if(!(triangles[0]>triangles[1]&&triangles[1]>triangles[2]))errors.push('LOD_TRIANGLE_ORDER_INVALID');if(new Set(roots).size!==3)errors.push('LOD_ROOTS_NOT_UNIQUE');
  if(geometrySet.main.metadata.identity_morph_count<24)errors.push('IDENTITY_MORPH_COUNT_INSUFFICIENT');if(geometrySet.main.metadata.expression_morph_count<8)errors.push('EXPRESSION_MORPH_COUNT_INSUFFICIENT');if(geometrySet.main.metadata.viseme_morph_count<12)errors.push('VISEME_MORPH_COUNT_INSUFFICIENT');
  if(continuity.status!=='pass')errors.push('CROSS_MEDIA_IDENTITY_DIVERGENCE');if(providerReceipt.license!=='Apache-2.0')errors.push('PROVIDER_LICENSE_MISSING');
  const required=['character.glb','character-lod0.glb','character-lod1.glb','character-lod2.glb','body.glb','face.glb','hair.glb','costume.glb','identity_signature.json','rig.json','morph-map.json','expression-map.json','viseme-map.json','collision-profile.json','physics-profile.json','retarget-profile.json','vsr-character-profile.json','rsr-character-body-profile.json','model-sheet.svg','front-view.svg','side-view.svg','back-view.svg','expression-sheet.svg','mouth-chart.svg','eye-state-sheet.svg','portrait-preview.png','anime-projection.png','native-2d/manifest.json','2.5d/manifest.json','3d-assisted-2d/color.png'];for(const name of required)if(!records[name])errors.push(`ASSET_ROLE_MISSING:${name}`);
  const gates={geometry:{pass:main.valid&&lodChecks.every(item=>item.valid),details:{main:main.metrics,lods:lodChecks.map(item=>item.metrics),lod_triangles:triangles,lod_roots:roots}},identity:{pass:continuity.status==='pass',identity_root:genome.identity_root,continuity_root:continuity.report_root},expression:{pass:geometrySet.main.metadata.expression_morph_count>=8&&geometrySet.main.metadata.viseme_morph_count>=12,expression_count:geometrySet.main.metadata.expression_morph_count,viseme_count:geometrySet.main.metadata.viseme_morph_count,close_mouth_on_end:genome.voice_binding.close_mouth_on_end},animation:{pass:geometrySet.rig.bones.length>=20&&genome.motion_profile.director_override,rig_bones:geometrySet.rig.bones.length,director_override:genome.motion_profile.director_override},render:{pass:Boolean(records['3d-assisted-2d/line.png']&&records['3d-assisted-2d/shadow.png']&&records['3d-assisted-2d/color.png']),passes:['line','shadow','color','depth','normal','motion'],quality_boundary:'deterministic supersampled reference raster'},asset:{pass:errors.filter(code=>String(code).startsWith('ASSET_ROLE_MISSING')||code==='PROVIDER_LICENSE_MISSING').length===0,stable_ids:true,hashes:true,manifest:true,lineage:true,provider_receipt:true,license:providerReceipt.license}};
  return seal({format:'rncs.character-quality-report.v0.1',version:'0.1.0-alpha.1',valid:errors.length===0,quality_tier:'reference-digital-actor-v0.1',errors,warnings:[...genomeValidation.warnings],gates,record_count:Object.keys(records).length,report_root:''},'report_root');
}

export function validateCharacterAssetFamily(family,{baseDir=null,verifyFiles=false}={}){
  const errors=[],warnings=[];if(family?.format!=='ragf.character-asset-family.v0.1')errors.push('CHARACTER_ASSET_FAMILY_FORMAT_INVALID');if(!family?.character_id||!family?.asset_family_id)errors.push('CHARACTER_ASSET_FAMILY_ID_REQUIRED');if(!verifySeal(family,'family_root'))errors.push('CHARACTER_ASSET_FAMILY_ROOT_INVALID');if((family?.counts?.identity_morphs??0)<24)errors.push('CHARACTER_IDENTITY_MORPHS_INSUFFICIENT');if((family?.counts?.expressions??0)<8)errors.push('CHARACTER_EXPRESSIONS_INSUFFICIENT');if((family?.counts?.visemes??0)<12)errors.push('CHARACTER_VISEMES_INSUFFICIENT');if((family?.lods??[]).length<3)errors.push('CHARACTER_LOD_INSUFFICIENT');const lodRoots=(family?.lods??[]).map(item=>item.root),lodTriangles=(family?.lods??[]).map(item=>item.triangles);if(new Set(lodRoots).size!==lodRoots.length)errors.push('CHARACTER_LOD_ROOT_DUPLICATE');if(lodTriangles.length>=3&&!(lodTriangles[0]>lodTriangles[1]&&lodTriangles[1]>lodTriangles[2]))errors.push('CHARACTER_LOD_ORDER_INVALID');if(family?.continuity?.status!=='pass')errors.push('CHARACTER_CONTINUITY_FAILED');if(!family?.provider_receipt?.license)errors.push('CHARACTER_PROVIDER_LICENSE_MISSING');if(family?.provider_receipt?.identity_authority!=='RNCS Character Genome')errors.push('CHARACTER_PROVIDER_IDENTITY_AUTHORITY_INVALID');if(family?.quality?.valid!==true)errors.push('CHARACTER_QUALITY_GATE_FAILED');for(const module of ['body','face','hair','costume'])if(!family?.modules?.[module])errors.push(`CHARACTER_MODULE_REQUIRED:${module}`);if(!family?.runtime_profiles?.vsr?.profile_root)errors.push('CHARACTER_VSR_PROFILE_REQUIRED');if(!family?.runtime_profiles?.rsr?.profile_root)errors.push('CHARACTER_RSR_PROFILE_REQUIRED');for(const mode of family?.cross_media?.modes??[])if(mode.identity_signature_root!==family?.identity_signature?.signature_root)errors.push(`CHARACTER_MODE_IDENTITY_DIVERGENCE:${mode.mode}`);
  if(verifyFiles&&baseDir){for(const file of family?.manifest?.files??[]){const target=path.resolve(baseDir,file.path);if(!target.startsWith(path.resolve(baseDir))||!fs.existsSync(target)){errors.push(`CHARACTER_FILE_MISSING:${file.path}`);continue}const actual=rootHash(fs.readFileSync(target).toString('base64'));if(actual!==file.root)errors.push(`CHARACTER_FILE_ROOT_MISMATCH:${file.path}`)}}
  return{valid:errors.length===0,errors,warnings,family_root:family?.family_root??null,asset_root:family?.asset_root??null};
}
