// 角色 → 权限矩阵。第一版用代码常量实现，避免过度复杂。
// 后续如需细粒度授权，可走 user_permissions 表覆盖。

import type { AetherRole, PermissionKey } from "./authTypes";

const ALL_PERMISSIONS_FOUNDER: PermissionKey[] = [
  "VIEW_SYSTEM", "VIEW_ADMIN", "VIEW_AUDIT", "VIEW_DATABASE", "VIEW_LOGS",
  "MANAGE_USERS", "MANAGE_ROLES", "MANAGE_SETTINGS",
  "VIEW_TRAINING", "CREATE_DATASET", "EXPORT_DATASET", "CREATE_TRAINING_PLAN",
  "RUN_AUTO_TRAINING", "VIEW_EXPERIMENT_LEDGER", "MANAGE_LOCAL_GATEWAY",
  "VIEW_STORE", "CREATE_CAPABILITY_ASSET", "UPLOAD_USER_ASSET",
  "SUBMIT_FOR_REVIEW", "REVIEW_ASSET", "PUBLISH_PRIVATE", "PUBLISH_PUBLIC",
  "CREATE_OBJECT", "CREATE_WORLD", "CREATE_APP", "CREATE_AGENT", "USE_ADVANCED_CHAT",
  "FOUNDER_ONLY", "MANAGE_CORE_SYSTEM", "VIEW_HIDDEN_SYSTEMS",
  "USE_LOVABLE_AI", "USE_LOCAL_MODEL", "USE_WEBLLM", "USE_EXTERNAL_OWN_KEY",
  "MANAGE_AI_PROVIDERS", "VIEW_AI_USAGE", "VIEW_AI_COST_RISK", "TEST_AI_PROVIDER",
];

const ADMIN_DEFAULT: PermissionKey[] = [
  "VIEW_SYSTEM", "VIEW_ADMIN", "VIEW_AUDIT", "VIEW_LOGS",
  "MANAGE_USERS",
  "VIEW_TRAINING", "VIEW_EXPERIMENT_LEDGER",
  "VIEW_STORE", "REVIEW_ASSET", "PUBLISH_PRIVATE",
  "CREATE_OBJECT", "CREATE_WORLD", "CREATE_APP", "CREATE_AGENT", "USE_ADVANCED_CHAT",
  "CREATE_CAPABILITY_ASSET", "UPLOAD_USER_ASSET", "SUBMIT_FOR_REVIEW",
  "CREATE_DATASET", "CREATE_TRAINING_PLAN",
  // AI：默认禁用 Lovable AI，仅允许本地/WebLLM 与查看用量
  "USE_LOCAL_MODEL", "USE_WEBLLM", "VIEW_AI_USAGE", "TEST_AI_PROVIDER",
];

const PRO_USER_DEFAULT: PermissionKey[] = [
  "VIEW_TRAINING", "CREATE_DATASET", "EXPORT_DATASET", "CREATE_TRAINING_PLAN",
  "VIEW_EXPERIMENT_LEDGER",
  "VIEW_STORE", "CREATE_CAPABILITY_ASSET", "UPLOAD_USER_ASSET",
  "SUBMIT_FOR_REVIEW", "PUBLISH_PRIVATE",
  "CREATE_OBJECT", "CREATE_WORLD", "CREATE_APP", "CREATE_AGENT", "USE_ADVANCED_CHAT",
  // AI：不能用创始人额度
  "USE_LOCAL_MODEL", "USE_WEBLLM", "USE_EXTERNAL_OWN_KEY",
];

const USER_DEFAULT: PermissionKey[] = [
  "VIEW_STORE", "CREATE_OBJECT",
  // AI：仅低成本来源
  "USE_WEBLLM", "USE_LOCAL_MODEL",
];

const GUEST_DEFAULT: PermissionKey[] = [];

export const ROLE_PERMISSION_MATRIX: Record<AetherRole, PermissionKey[]> = {
  FOUNDER: ALL_PERMISSIONS_FOUNDER,
  ADMIN: ADMIN_DEFAULT,
  PRO_USER: PRO_USER_DEFAULT,
  USER: USER_DEFAULT,
  GUEST: GUEST_DEFAULT,
};

export function roleHasPermission(role: AetherRole, key: PermissionKey): boolean {
  return ROLE_PERMISSION_MATRIX[role].includes(key);
}
