import test from 'node:test';
import assert from 'node:assert/strict';
import {compileTextGraphIntent,createFiveDimensionalAttributeModel,createComplexityStateMachine,evaluateComplexityState,createDistributedGenerativeDiffusionPlan,runDistributedGenerativeDiffusion,createDownstreamProjectionPlan,compileGenerativeMorphogenesisCandidate,verifyGenerativeMorphogenesisCandidate} from '../src/index.mjs';

const fiveD=()=>createFiveDimensionalAttributeModel({object_id:'tower.central',domain:'visual-asset',dimensions:[{id:'geometry',quantities:[{id:'height',value:0.9},{id:'taper',value:0.6}]},{id:'semantic',quantities:[{id:'importance',value:0.95}]},{id:'material',quantities:[{id:'reflectivity',value:0.4}]},{id:'visual',quantities:[{id:'salience',value:0.92}]},{id:'dynamic',quantities:[{id:'motion',value:0.1}]}]});
const machine=()=>createComplexityStateMachine({representation_kind:'mesh',states:[{id:'proxy',rank:0,complexity:{faces:128}},{id:'standard',rank:1,complexity:{faces:4096}},{id:'cinematic',rank:2,complexity:{faces:65536}}],thresholds:[0.30,0.68],hysteresis:0.02});
const diffusionPlan=()=>createDistributedGenerativeDiffusionPlan({channels:[{id:'geometry',role:'geometry',initial:0,damping:1},{id:'material',role:'material',depends_on:['geometry'],initial:0,damping:1},{id:'lighting',role:'lighting',depends_on:['geometry','material'],initial:0,damping:1}],max_iterations:6,convergence_epsilon:0});

test('Chinese/English text compiles into an auditable relation graph',()=>{const graph=compileTextGraphIntent({text:'未来城市悬浮在云海上，轨道围绕主塔，人物仰望主塔。 CentralTower supports WorldTree.',entities:['未来城市','云海','轨道','主塔','人物','WorldTree','CentralTower']});assert.equal(graph.authority.candidate_only,true);assert.ok(graph.nodes.length>=7);assert.ok(graph.edges.some(e=>e.relation==='above'));assert.ok(graph.edges.some(e=>e.relation==='surrounds'));assert.ok(graph.edges.some(e=>e.relation==='gaze_target'));assert.ok(graph.edges.some(e=>e.relation==='supports'));assert.match(graph.graph_root,/^[0-9a-f]{64}$/);});
test('five-dimensional model requires exactly five domain-defined dimensions and multiple quantities',()=>{const model=fiveD();assert.equal(model.dimensions.length,5);assert.equal(model.dimensions[0].quantities.length,2);assert.equal(model.authority.authoritative,false);assert.throws(()=>createFiveDimensionalAttributeModel({object_id:'x',dimensions:model.dimensions.slice(0,4)}),/FIVE_DIMENSIONS/);});
test('complexity state machine expands for high visual/semantic demand',()=>{const result=evaluateComplexityState(machine(),{semantic_importance:1,screen_coverage:1,edit_focus:1,representation_error:1,motion_importance:0.8,proximity:1,visibility:1,compute_pressure:0,occlusion:0},'proxy');assert.equal(result.transition,'EXPAND');assert.equal(result.to_state,'cinematic');assert.equal(result.target_complexity.faces,65536);});
test('complexity state machine contracts under pressure and occlusion',()=>{const result=evaluateComplexityState(machine(),{semantic_importance:0.1,screen_coverage:0.1,edit_focus:0,representation_error:0.05,motion_importance:0,proximity:0.1,visibility:0.2,compute_pressure:1,occlusion:1},'cinematic');assert.equal(result.transition,'CONTRACT');assert.equal(result.to_state,'proxy');});
test('distributed diffusion rejects dependency cycles',()=>{assert.throws(()=>createDistributedGenerativeDiffusionPlan({channels:[{id:'a',depends_on:['b']},{id:'b',depends_on:['a']}]}),/GRAPH_CYCLE/);});
test('distributed diffusion executes dependency waves deterministically',()=>{const plan=diffusionPlan();const run=runDistributedGenerativeDiffusion(plan,{geometry:()=>1,material:({dependencies})=>dependencies.geometry*2,lighting:({dependencies})=>dependencies.geometry+dependencies.material});assert.equal(run.state.geometry,1);assert.equal(run.state.material,2);assert.equal(run.state.lighting,3);assert.ok(['CONVERGED','BOUNDED_STOP'].includes(run.status));assert.equal(run.authority.canonical_state_mutated,false);});
test('URRF-2D bridge projects DVG + PPD without authority escalation',()=>{const projection=createDownstreamProjectionPlan({object_id:'scene.city',target:'urrf-2d'});assert.deepEqual(projection.representations.map(x=>x.kind),['dvg','ppd']);assert.equal(projection.authority.provider_can_write_authoritative_world_state,false);});
test('universal projection can target 3D asset morphology',()=>{const projection=createDownstreamProjectionPlan({object_id:'actor.1',target:'ragf-3d'});assert.deepEqual(projection.representations.map(x=>x.kind),['mesh','material','rig','lod']);});
test('candidate composes all four concepts with RNCS authority isolation',()=>{const candidate=compileGenerativeMorphogenesisCandidate({graph:{text:'CentralTower supports WorldTree.',entities:['CentralTower','WorldTree']},attributes:fiveD(),complexity:machine(),diffusion:diffusionPlan(),target:'urrf-2d'});const verification=verifyGenerativeMorphogenesisCandidate(candidate);assert.equal(verification.valid,true,verification.errors.join(','));assert.equal(candidate.authority.generated_geometry_authoritative,false);assert.equal(candidate.authority.canonical_state_mutated,false);assert.equal(candidate.acceptance.five_dimensions_exact,true);});
test('candidate root detects tampering',()=>{const candidate=compileGenerativeMorphogenesisCandidate({graph:{text:'A contains B.',entities:['A','B'],relations:[{source:'A',target:'B',relation:'contains'}]},attributes:fiveD(),complexity:machine(),diffusion:diffusionPlan()});const tampered=structuredClone(candidate);tampered.authority.authoritative=true;const verification=verifyGenerativeMorphogenesisCandidate(tampered);assert.equal(verification.valid,false);assert.ok(verification.errors.includes('AUTHORITATIVE_FALSE'));assert.ok(verification.errors.includes('ROOT'));});
