import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {writeWavPcm16} from '../../voice-performance-runtime/src/index.mjs';
import {canonicalCutRef,listProductionCuts} from '../../anime-production-runtime/src/index.mjs';

export const AUDIO_SCENE_FORMAT='rncs.audio-scene-ir.v0.1';
const hash=value=>createHash('sha256').update(typeof value==='string'||Buffer.isBuffer(value)?value:JSON.stringify(value)).digest('hex');
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
function metrics(samples){let peak=0,sumSquares=0;for(const value of samples){const absolute=Math.abs(value);if(absolute>peak)peak=absolute;sumSquares+=value*value}const rms=Math.sqrt(sumSquares/Math.max(1,samples.length));return{peak,rms,lufs_estimate:20*Math.log10(Math.max(1e-8,rms))}}

export function createSoundScene({productionId,cut,voiceBundle=null,voiceBundles=null,seed='audio-reference-v0.1'}={}){
  const activeTakes=(cut?.voice_track??[]).filter(item=>item.active!==false),authorityCounts=new Map();for(const take of activeTakes)authorityCounts.set(take.dialogue_event_id,(authorityCounts.get(take.dialogue_event_id)??0)+1);const duplicate=[...authorityCounts].find(([,count])=>count>1);if(duplicate)throw Object.assign(new Error(`MULTIPLE_DIALOGUE_AUTHORITY:${duplicate[0]}`),{code:'MULTIPLE_DIALOGUE_AUTHORITY',details:{dialogue_event_id:duplicate[0]}});
  const bundles=Array.isArray(voiceBundles)?voiceBundles:(voiceBundle?[voiceBundle]:[]),cutRef=canonicalCutRef(cut),duration=Number(cut?.duration??5),fps=Number(cut?.fps??24);
  return{format:AUDIO_SCENE_FORMAT,version:'0.1.0-alpha.1',scene_id:`sound:${productionId}:${cutRef}`,production_id:productionId,cut_ref:cutRef,duration_seconds:duration,sample_rate:22050,dialogue_stems:bundles.map(bundle=>({stem_id:`dialogue:${bundle.dialogue_event_id}`,dialogue_event_id:bundle.dialogue_event_id,voice_root:bundle.bundle_root,start_seconds:Number(bundle.start_seconds??0),duration_seconds:Number(bundle.duration_seconds??0),active:true})),ambience_stems:(cut?.ambience_track??[]).map(item=>({stem_id:item.cue_id??`ambience:${item.sound}`,cue:item.sound,start_seconds:Number(item.start_frame??0)/fps,end_seconds:Number(item.end_frame??duration*fps)/fps})),foley_stems:(cut?.foley_track??[]).map(item=>({stem_id:item.cue_id??`foley:${item.sound}`,cue:item.sound,start_seconds:Number(item.start_frame??0)/fps,end_seconds:Number(item.end_frame??duration*fps)/fps})),sfx_stems:(cut?.sfx_track??[]).map(item=>({stem_id:item.cue_id??`sfx:${item.sound}`,cue:item.sound,start_seconds:Number(item.start_frame??0)/fps,end_seconds:Number(item.end_frame??duration*fps)/fps})),music_stems:(cut?.music_track??[]).map(item=>({stem_id:item.cue_id??`music:${item.sound}`,cue:item.sound,start_seconds:Number(item.start_frame??0)/fps,end_seconds:Number(item.end_frame??duration*fps)/fps})),bus_graph:{dialogue:{gain_db:0},ambience:{gain_db:-16,ducking_db:-7},foley:{gain_db:-10},sfx:{gain_db:-8},music:{gain_db:-18},master:{gain_db:0}},spatial_layout:{dialogue:[.5,.5],ambience:[.5,.52],foley:[.62,.5],sfx:[.55,.48],music:[.5,.5]},reverb_zones:[{id:`reverb:${cutRef}`,start:0,end:duration,preset:'cold-stone-short'}],automation:[{kind:'dialogue-ducking',source:'dialogue',targets:['ambience','music'],amount_db:-7}],loudness_target:{integrated_lufs:-16,true_peak_db:-1},export_policy:{stems:['dialogue','ambience','foley','sfx','music'],master:true,format:'wav'},seed};
}

export function createProductionSoundScene({production,voiceBundles=[],seed='audio-reference-v0.1'}={}){
  const bundlesByEvent=new Map(voiceBundles.map(bundle=>[bundle.dialogue_event_id,bundle])),timelineByRef=new Map((production?.editorial_timeline?.entries??[]).map(entry=>[entry.cut_ref,entry])),parts=[];
  for(const cut of listProductionCuts(production)){
    const cutRef=canonicalCutRef(cut),entry=timelineByRef.get(cutRef),offset=Number(entry?.global_start_frame??0)/Number(entry?.fps??cut.fps),activeEvents=new Set((cut.voice_track??[]).filter(item=>item.active!==false).map(item=>item.dialogue_event_id)),cutBundles=[...activeEvents].map(id=>bundlesByEvent.get(id)).filter(Boolean),part=createSoundScene({productionId:production.production_id,cut,voiceBundles:cutBundles,seed});
    const shift=item=>({...item,cut_ref:cutRef,start_seconds:Number(item.start_seconds??0)+offset,end_seconds:item.end_seconds===undefined?undefined:Number(item.end_seconds)+offset});
    parts.push({...part,global_start_seconds:offset,dialogue_stems:part.dialogue_stems.map(shift),ambience_stems:part.ambience_stems.map(shift),foley_stems:part.foley_stems.map(shift),sfx_stems:part.sfx_stems.map(shift),music_stems:part.music_stems.map(shift),reverb_zones:part.reverb_zones.map(zone=>({...zone,start:zone.start+offset,end:zone.end+offset}))});
  }
  const first=parts[0]??createSoundScene({productionId:production?.production_id,cut:{cut_id:'empty',duration:0,fps:24},seed}),flatten=name=>parts.flatMap(part=>part[name]);
  return{...first,format:AUDIO_SCENE_FORMAT,version:'0.1.0-alpha.1',scene_id:`sound:${production.production_id}:editorial`,cut_ref:null,production_root:production.production_root,timeline_root:production.editorial_timeline?.timeline_root??null,duration_seconds:Number(production.editorial_timeline?.total_duration_seconds??0),dialogue_stems:flatten('dialogue_stems'),ambience_stems:flatten('ambience_stems'),foley_stems:flatten('foley_stems'),sfx_stems:flatten('sfx_stems'),music_stems:flatten('music_stems'),reverb_zones:flatten('reverb_zones'),cut_parts:parts.map(part=>({cut_ref:part.cut_ref,start_seconds:part.global_start_seconds,duration_seconds:part.duration_seconds}))};
}

function tone(samples,rate,start,duration,frequency,amplitude,kind='sine'){const from=Math.max(0,Math.floor(start*rate)),to=Math.min(samples.length,Math.ceil((start+duration)*rate));for(let index=from;index<to;index++){const t=index/rate-start,envelope=Math.min(1,t/.02,(duration-t)/.05);const base=kind==='noise'?Math.sin(index*12.9898)*.5+.5:Math.sin(t*frequency*Math.PI*2);samples[index]+=base*envelope*amplitude}}

export function renderAudioScene(scene,{voiceWav=null,voiceWavs=null,outDir=null,seed=scene.seed??'audio-reference-v0.1'}={}){
  const rate=scene.sample_rate,samples=Math.ceil(scene.duration_seconds*rate),stems={dialogue:new Float32Array(samples),ambience:new Float32Array(samples),foley:new Float32Array(samples),sfx:new Float32Array(samples),music:new Float32Array(samples)};
  const wavFor=stem=>voiceWavs instanceof Map?(voiceWavs.get(stem.dialogue_event_id)??voiceWavs.get(stem.voice_root)):(voiceWavs?.[stem.dialogue_event_id]??voiceWavs?.[stem.voice_root]??(scene.dialogue_stems.length===1?voiceWav:null));
  const renderedDialogueCounts=new Map();for(const stem of scene.dialogue_stems??[]){const source=wavFor(stem);if(!source)continue;const data=Buffer.isBuffer(source)?source:Buffer.from(source),pcmStart=44,targetStart=Math.max(0,Math.floor(Number(stem.start_seconds??0)*rate)),sourceSamples=Math.max(0,Math.floor((data.length-pcmStart)/2));for(let index=0;index<Math.min(sourceSamples,samples-targetStart);index++)stems.dialogue[targetStart+index]+=data.readInt16LE(pcmStart+index*2)/32767;renderedDialogueCounts.set(stem.dialogue_event_id,(renderedDialogueCounts.get(stem.dialogue_event_id)??0)+1)}
  for(const item of scene.ambience_stems??[]){const start=Number(item.start_seconds??0),duration=Math.max(0,Number(item.end_seconds??scene.duration_seconds)-start);tone(stems.ambience,rate,start,duration,46,.045,'noise');tone(stems.ambience,rate,start,duration,82,.035)}for(const item of scene.foley_stems??[]){const start=Number(item.start_seconds??0)+.2,duration=Math.max(0,Number(item.end_seconds??scene.duration_seconds)-start);tone(stems.foley,rate,start,duration,180,.045)}for(const item of scene.sfx_stems??[]){const start=Number(item.start_seconds??0);tone(stems.sfx,rate,start+.05,.11,240,.18);tone(stems.sfx,rate,start+.18,.08,360,.12)}for(const item of scene.music_stems??[]){const start=Number(item.start_seconds??0),duration=Math.max(0,Number(item.end_seconds??scene.duration_seconds)-start);tone(stems.music,rate,start,duration,110,.035)}
  const master=new Float32Array(samples);for(let index=0;index<samples;index++){const active=stems.dialogue[index];const duck=active?Math.pow(10,-7/20):1;master[index]=stems.dialogue[index]+stems.ambience[index]*duck+stems.foley[index]*.82+stems.sfx[index]*.72+stems.music[index]*duck*.75}const peak=metrics(master).peak;const gain=peak>.92?.92/peak:1;for(let index=0;index<samples;index++)master[index]=clamp(master[index]*gain,-.98,.98);
  const buffers={dialogue:writeWavPcm16({sampleRate:rate,samples:stems.dialogue}),ambience:writeWavPcm16({sampleRate:rate,samples:stems.ambience}),foley:writeWavPcm16({sampleRate:rate,samples:stems.foley}),sfx:writeWavPcm16({sampleRate:rate,samples:stems.sfx}),music:writeWavPcm16({sampleRate:rate,samples:stems.music}),master:writeWavPcm16({sampleRate:rate,samples:master})};
  let repeatDialogueCount=0;for(const count of renderedDialogueCounts.values())if(count>repeatDialogueCount)repeatDialogueCount=count;const report={format:'rncs.audio-scene-render-report.v0.1',scene_id:scene.scene_id,duration_seconds:scene.duration_seconds,sample_rate:rate,stems:Object.fromEntries(Object.entries(buffers).map(([name,buffer])=>[name,{bytes:buffer.length,root:hash(buffer.toString('base64')),metrics:metrics(name==='master'?master:stems[name])}])),dialogue_placements:(scene.dialogue_stems??[]).map(stem=>({dialogue_event_id:stem.dialogue_event_id,cut_ref:stem.cut_ref??scene.cut_ref??null,start_seconds:stem.start_seconds??0,rendered:renderedDialogueCounts.has(stem.dialogue_event_id)})),ducking:{enabled:true,amount_db:-7},repeat_dialogue_count:repeatDialogueCount,seed,master_root:hash(buffers.master.toString('base64'))};report.audio_root=hash(report);
  if(outDir){fs.mkdirSync(outDir,{recursive:true});for(const [name,buffer] of Object.entries(buffers))fs.writeFileSync(path.join(outDir,`${name}.wav`),buffer);fs.writeFileSync(path.join(outDir,'audio-scene.json'),JSON.stringify(scene,null,2));fs.writeFileSync(path.join(outDir,'audio-report.json'),JSON.stringify(report,null,2));}
  return{buffers,report};
}

export function validateAudioScene(scene,report){const errors=[],events=new Set();if(scene?.format!==AUDIO_SCENE_FORMAT)errors.push('AUDIO_SCENE_FORMAT_INVALID');for(const stem of scene?.dialogue_stems??[]){if(events.has(stem.dialogue_event_id))errors.push(`DIALOGUE_STEM_AUTHORITY_DUPLICATE:${stem.dialogue_event_id}`);events.add(stem.dialogue_event_id)}if(report?.repeat_dialogue_count>1)errors.push('DIALOGUE_REPEATED');for(const [name,item] of Object.entries(report?.stems??{})){if(item.metrics.peak>1)errors.push(`AUDIO_CLIP:${name}`);if(!item.root)errors.push(`AUDIO_ROOT_MISSING:${name}`)}return{valid:errors.length===0,errors,audio_root:report?.audio_root??null};}
