import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {writeWavPcm16} from '../../voice-performance-runtime/src/index.mjs';

export const AUDIO_SCENE_FORMAT='rncs.audio-scene-ir.v0.1';
const hash=value=>createHash('sha256').update(typeof value==='string'||Buffer.isBuffer(value)?value:JSON.stringify(value)).digest('hex');
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
function metrics(samples){const peak=Math.max(...samples.map(value=>Math.abs(value))),rms=Math.sqrt(samples.reduce((sum,value)=>sum+value*value,0)/Math.max(1,samples.length));return{peak,rms,lufs_estimate:20*Math.log10(Math.max(1e-8,rms))}}

export function createSoundScene({productionId,cut,voiceBundle,seed='audio-reference-v0.1'}={}){
  const activeTakes=(cut?.voice_track??[]).filter(item=>item.active!==false);if(activeTakes.length>1)throw Object.assign(new Error('MULTIPLE_DIALOGUE_AUTHORITY'),{code:'MULTIPLE_DIALOGUE_AUTHORITY'});
  return{format:AUDIO_SCENE_FORMAT,version:'0.1.0-alpha.1',scene_id:`sound:${productionId}:${cut?.cut_id}`,duration_seconds:Number(cut?.duration??5),sample_rate:22050,dialogue_stems:voiceBundle?[{stem_id:`dialogue:${voiceBundle.dialogue_event_id}`,dialogue_event_id:voiceBundle.dialogue_event_id,voice_root:voiceBundle.bundle_root,active:true}]:[],ambience_stems:(cut?.ambience_track??[]).map(item=>({stem_id:item.cue_id??`ambience:${item.sound}`,cue:item.sound})),foley_stems:(cut?.foley_track??[]).map(item=>({stem_id:item.cue_id??`foley:${item.sound}`,cue:item.sound})),sfx_stems:(cut?.sfx_track??[]).map(item=>({stem_id:item.cue_id??`sfx:${item.sound}`,cue:item.sound})),music_stems:(cut?.music_track??[]).map(item=>({stem_id:item.cue_id??`music:${item.sound}`,cue:item.sound})),bus_graph:{dialogue:{gain_db:0},ambience:{gain_db:-16,ducking_db:-7},foley:{gain_db:-10},sfx:{gain_db:-8},music:{gain_db:-18},master:{gain_db:0}},spatial_layout:{dialogue:[.5,.5],ambience:[.5,.52],foley:[.62,.5],sfx:[.55,.48],music:[.5,.5]},reverb_zones:[{id:'judgment-square',start:0,end:Number(cut?.duration??5),preset:'cold-stone-short'}],automation:[{kind:'dialogue-ducking',source:'dialogue',targets:['ambience','music'],amount_db:-7}],loudness_target:{integrated_lufs:-16,true_peak_db:-1},export_policy:{stems:['dialogue','ambience','foley','sfx','music'],master:true,format:'wav'},seed};
}

function tone(samples,rate,start,duration,frequency,amplitude,kind='sine'){const from=Math.max(0,Math.floor(start*rate)),to=Math.min(samples.length,Math.ceil((start+duration)*rate));for(let index=from;index<to;index++){const t=index/rate-start,envelope=Math.min(1,t/.02,(duration-t)/.05);const base=kind==='noise'?Math.sin(index*12.9898)*.5+.5:Math.sin(t*frequency*Math.PI*2);samples[index]+=base*envelope*amplitude}}

export function renderAudioScene(scene,{voiceWav=null,outDir=null,seed=scene.seed??'audio-reference-v0.1'}={}){
  const rate=scene.sample_rate,samples=Math.ceil(scene.duration_seconds*rate),stems={dialogue:new Float32Array(samples),ambience:new Float32Array(samples),foley:new Float32Array(samples),sfx:new Float32Array(samples),music:new Float32Array(samples)};
  if(voiceWav){const data=Buffer.isBuffer(voiceWav)?voiceWav:Buffer.from(voiceWav);const pcmStart=44;for(let index=0;index<Math.min(samples,Math.floor((data.length-pcmStart)/2));index++)stems.dialogue[index]=data.readInt16LE(pcmStart+index*2)/32767}
  tone(stems.ambience,rate,0,scene.duration_seconds,46,.045,'noise');tone(stems.ambience,rate,0,scene.duration_seconds,82,.035);for(const item of scene.foley_stems)tone(stems.foley,rate,.2,scene.duration_seconds-.2,180,.045);for(const item of scene.sfx_stems){tone(stems.sfx,rate,1.05,.11,240,.18);tone(stems.sfx,rate,1.18,.08,360,.12)}for(const item of scene.music_stems)tone(stems.music,rate,0,scene.duration_seconds,110,.035);
  const master=new Float32Array(samples);for(let index=0;index<samples;index++){const active=stems.dialogue[index];const duck=active?Math.pow(10,-7/20):1;master[index]=stems.dialogue[index]+stems.ambience[index]*duck+stems.foley[index]*.82+stems.sfx[index]*.72+stems.music[index]*duck*.75}const peak=metrics(master).peak;const gain=peak>.92?.92/peak:1;for(let index=0;index<samples;index++)master[index]=clamp(master[index]*gain,-.98,.98);
  const buffers={dialogue:writeWavPcm16({sampleRate:rate,samples:stems.dialogue}),ambience:writeWavPcm16({sampleRate:rate,samples:stems.ambience}),foley:writeWavPcm16({sampleRate:rate,samples:stems.foley}),sfx:writeWavPcm16({sampleRate:rate,samples:stems.sfx}),music:writeWavPcm16({sampleRate:rate,samples:stems.music}),master:writeWavPcm16({sampleRate:rate,samples:master})};
  const report={format:'rncs.audio-scene-render-report.v0.1',scene_id:scene.scene_id,duration_seconds:scene.duration_seconds,sample_rate:rate,stems:Object.fromEntries(Object.entries(buffers).map(([name,buffer])=>[name,{bytes:buffer.length,root:hash(buffer.toString('base64')),metrics:metrics(name==='master'?master:stems[name])}])),ducking:{enabled:true,amount_db:-7},repeat_dialogue_count:scene.dialogue_stems.length?1:0,seed,master_root:hash(buffers.master.toString('base64'))};report.audio_root=hash(report);
  if(outDir){fs.mkdirSync(outDir,{recursive:true});for(const [name,buffer] of Object.entries(buffers))fs.writeFileSync(path.join(outDir,`${name}.wav`),buffer);fs.writeFileSync(path.join(outDir,'audio-scene.json'),JSON.stringify(scene,null,2));fs.writeFileSync(path.join(outDir,'audio-report.json'),JSON.stringify(report,null,2));}
  return{buffers,report};
}

export function validateAudioScene(scene,report){const errors=[];if(scene?.format!==AUDIO_SCENE_FORMAT)errors.push('AUDIO_SCENE_FORMAT_INVALID');if((scene?.dialogue_stems??[]).length>1)errors.push('DIALOGUE_STEM_AUTHORITY_DUPLICATE');if(report?.repeat_dialogue_count>1)errors.push('DIALOGUE_REPEATED');for(const [name,item] of Object.entries(report?.stems??{})){if(item.metrics.peak>1)errors.push(`AUDIO_CLIP:${name}`);if(!item.root)errors.push(`AUDIO_ROOT_MISSING:${name}`)}return{valid:errors.length===0,errors,audio_root:report?.audio_root??null};}
