import assert from 'node:assert/strict';
import { compileSpatialFrame, renderSpatialReference, sampleSpatialAnimation } from '../packages/spatial-reality-3d/src/index.js';
import { decodeGltfImageToSpatialTexture, decodeKtx2ToSpatialTexture, importGlbToSpatialScene, importGlbToSpatialSceneAsync, importGltfToSpatialScene, importGltfToSpatialSceneAsync, parseGlb, resolveGltfTextureSource, verifyGltfImportReceipt } from '../packages/gltf-asset/src/index.js';

const tests:Array<{name:string;fn:()=>void|Promise<void>}>=[];
const test=(name:string,fn:()=>void|Promise<void>):void=>{tests.push({name,fn})};

function ktx2Fixture():Uint8Array{const output=new Uint8Array(148),view=new DataView(output.buffer),identifier=[0xab,0x4b,0x54,0x58,0x20,0x32,0x30,0xbb,0x0d,0x0a,0x1a,0x0a];output.set(identifier,0);view.setUint32(12,43,true);view.setUint32(16,1,true);view.setUint32(20,2,true);view.setUint32(24,2,true);view.setUint32(36,1,true);view.setUint32(40,2,true);view.setBigUint64(80,128n,true);view.setBigUint64(88,16n,true);view.setBigUint64(96,16n,true);view.setBigUint64(104,144n,true);view.setBigUint64(112,4n,true);view.setBigUint64(120,4n,true);output.set([255,0,0,255,0,255,0,255,0,0,255,255,255,255,255,255],128);output.set([128,128,128,255],144);return output}

function fixture():Record<string,unknown>{
  const positions=new Float32Array([-1,-1,0,1,-1,0,0,1,0]);
  const normals=new Float32Array([0,0,1,0,0,1,0,0,1]);
  const uvs=new Float32Array([0,0,1,0,.5,1]);
  const indices=new Uint16Array([0,1,2]);
  const times=new Float32Array([0,1]);
  const translations=new Float32Array([0,0,0,1,0,0]);
  const chunks=[positions,normals,uvs,indices,times,translations];
  const offsets:number[]=[];let length=0;
  for(const chunk of chunks){while(length%4)length++;offsets.push(length);length+=chunk.byteLength}
  const binary=Buffer.alloc(length);
  chunks.forEach((chunk,index)=>Buffer.from(chunk.buffer,chunk.byteOffset,chunk.byteLength).copy(binary,offsets[index]));
  const views=chunks.map((chunk,index)=>({buffer:0,byteOffset:offsets[index],byteLength:chunk.byteLength}));
  return {
    asset:{version:'2.0',generator:'RNCS VSR test'},
    buffers:[{byteLength:length,uri:`data:application/octet-stream;base64,${binary.toString('base64')}`}],
    bufferViews:views,
    accessors:[
      {bufferView:0,componentType:5126,count:3,type:'VEC3'},
      {bufferView:1,componentType:5126,count:3,type:'VEC3'},
      {bufferView:2,componentType:5126,count:3,type:'VEC2'},
      {bufferView:3,componentType:5123,count:3,type:'SCALAR'},
      {bufferView:4,componentType:5126,count:2,type:'SCALAR'},
      {bufferView:5,componentType:5126,count:2,type:'VEC3'},
    ],
    images:[{extras:{vsrRGBA:{width:2,height:2,pixels:[255,0,0,255,0,255,0,255,0,0,255,255,255,255,255,255]}}}],
    textures:[{source:0}],
    materials:[{pbrMetallicRoughness:{baseColorFactor:[1,1,1,1],baseColorTexture:{index:0},metallicFactor:.1,roughnessFactor:.7}}],
    meshes:[{primitives:[{attributes:{POSITION:0,NORMAL:1,TEXCOORD_0:2},indices:3,material:0}]}],
    nodes:[{mesh:0,translation:[0,0,0]}],
    scenes:[{nodes:[0]}],scene:0,
    animations:[{samplers:[{input:4,output:5,interpolation:'LINEAR'}],channels:[{sampler:0,target:{node:0,path:'translation'}}]}]
  };
}


function pbrFixture():Record<string,unknown>{
  const value=fixture() as any;
  value.samplers=[{magFilter:9729,minFilter:9729,wrapS:33071,wrapT:10497}];
  value.images=[
    {extras:{vsrRGBA:{width:1,height:1,pixels:[70,150,255,255]}}},
    {extras:{vsrRGBA:{width:1,height:1,pixels:[0,80,240,255],colorSpace:'linear'}}},
    {extras:{vsrRGBA:{width:1,height:1,pixels:[255,128,255,255],colorSpace:'linear'}}},
    {extras:{vsrRGBA:{width:1,height:1,pixels:[64,64,64,255],colorSpace:'linear'}}},
    {extras:{vsrRGBA:{width:1,height:1,pixels:[0,255,220,255]}}}
  ];
  value.textures=value.images.map((_:unknown,index:number)=>({source:index,sampler:0}));
  value.materials=[{pbrMetallicRoughness:{baseColorFactor:[1,1,1,1],baseColorTexture:{index:0},metallicFactor:.8,roughnessFactor:.7,metallicRoughnessTexture:{index:1}},normalTexture:{index:2,scale:.75},occlusionTexture:{index:3,strength:.6},emissiveFactor:[.3,.8,1],emissiveTexture:{index:4},alphaMode:'MASK',alphaCutoff:.4}];
  return value;
}
function deformationFixture():Record<string,unknown>{
  const value=fixture() as any,binary=Buffer.from(value.buffers[0].uri.split(',')[1],'base64');
  const append=(data:ArrayBufferView,type:string,componentType:number,count:number)=>{let offset=binary.length;while(offset%4)offset++;const next=Buffer.alloc(offset+data.byteLength);binary.copy(next);Buffer.from(data.buffer,data.byteOffset,data.byteLength).copy(next,offset);value.buffers[0].byteLength=next.length;value.buffers[0].uri=`data:application/octet-stream;base64,${next.toString('base64')}`;value.bufferViews.push({buffer:0,byteOffset:offset,byteLength:data.byteLength});value.accessors.push({bufferView:value.bufferViews.length-1,componentType,count,type});return value.accessors.length-1};
  const joints=append(new Uint8Array([0,0,0,0,0,0,0,0,0,0,0,0]),'VEC4',5121,3),weights=append(new Float32Array([1,0,0,0,1,0,0,0,1,0,0,0]),'VEC4',5126,3),morph=append(new Float32Array([.4,0,0,.4,0,0,.4,0,0]),'VEC3',5126,3),inverseBind=append(new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),'MAT4',5126,1);
  value.meshes[0].weights=[1];value.meshes[0].primitives[0].attributes.JOINTS_0=joints;value.meshes[0].primitives[0].attributes.WEIGHTS_0=weights;value.meshes[0].primitives[0].targets=[{POSITION:morph}];value.nodes=[{mesh:0,skin:0,weights:[1]},{translation:[.6,0,0]}];value.scenes=[{nodes:[0,1]}];value.skins=[{joints:[1],inverseBindMatrices:inverseBind}];return value;
}
function cubicRotationFixture():Record<string,unknown>{
  const value=fixture() as any,binary=Buffer.from(value.buffers[0].uri.split(',')[1],'base64');
  const append=(data:ArrayBufferView,type:string,componentType:number,count:number)=>{let offset=binary.length;while(offset%4)offset++;const next=Buffer.alloc(offset+data.byteLength);binary.copy(next);Buffer.from(data.buffer,data.byteOffset,data.byteLength).copy(next,offset);value.buffers[0].byteLength=next.length;value.buffers[0].uri=`data:application/octet-stream;base64,${next.toString('base64')}`;value.bufferViews.push({buffer:0,byteOffset:offset,byteLength:data.byteLength});value.accessors.push({bufferView:value.bufferViews.length-1,componentType,count,type});return value.accessors.length-1};
  const cubicOutput=append(new Float32Array([0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0]),'VEC4',5126,6);value.nodes=[{mesh:0,rotation:[0,0,0,1]}];value.animations=[{samplers:[{input:4,output:cubicOutput,interpolation:'CUBICSPLINE'}],channels:[{sampler:0,target:{node:0,path:'rotation'}}]}];return value;
}
function glbFixture():Uint8Array{const value=fixture() as any,binary=Buffer.from(value.buffers[0].uri.split(',')[1],'base64'),json={...value,buffers:[{byteLength:binary.length}]},jsonBytes=Buffer.from(JSON.stringify(json),'utf8'),jsonLength=(jsonBytes.length+3)&~3,binLength=(binary.length+3)&~3,total=12+8+jsonLength+8+binLength,out=Buffer.alloc(total);jsonBytes.copy(out,20);out.fill(0x20,20+jsonBytes.length,20+jsonLength);binary.copy(out,28+jsonLength);out.writeUInt32LE(0x46546c67,0);out.writeUInt32LE(2,4);out.writeUInt32LE(total,8);out.writeUInt32LE(jsonLength,12);out.writeUInt32LE(0x4e4f534a,16);out.writeUInt32LE(binLength,20+jsonLength);out.writeUInt32LE(0x004e4942,24+jsonLength);return new Uint8Array(out)}
test('glTF 2.0 importer materializes geometry material texture hierarchy and animation',()=>{const result=importGltfToSpatialScene(fixture(),{sceneId:'gltf-test'});assert.equal(result.scene.meshes.length,1);assert.equal(result.scene.materials.length,1);assert.equal(result.scene.textures?.length,1);assert.equal(result.scene.animations?.length,1);assert.equal(result.scene.nodes[0]?.meshId,'mesh:gltf:0:0');assert.equal(verifyGltfImportReceipt(result.receipt),true)});
test('glTF importer preserves TEXCOORD_1 as the lightmap UV set',()=>{const value=fixture() as any;value.meshes[0].primitives[0].attributes.TEXCOORD_1=2;const result=importGltfToSpatialScene(value,{sceneId:'gltf-lightmap-uv'}),mesh=result.scene.meshes[0]!;assert.deepEqual(mesh.uvs1,mesh.uvs);assert.equal(verifyGltfImportReceipt(result.receipt),true)});
test('imported glTF compiles into a verified frame with texture resources',()=>{const {scene}=importGltfToSpatialScene(fixture(),{sceneId:'gltf-frame'});const frame=compileSpatialFrame(scene,{width:128,height:128,animation:{clipId:'animation:gltf:0',timeSeconds:.5}});assert.equal(frame.stats.textureCount,1);assert.equal(frame.stats.animationClipCount,1);assert.ok(frame.resources.some(resource=>resource.kind==='texture-2d'));assert.notEqual(frame.animationRoot,'0'.repeat(64))});
test('imported glTF texture and animation affect pixels while reality root remains authoritative',()=>{const {scene}=importGltfToSpatialScene(fixture(),{sceneId:'gltf-render'});const a=renderSpatialReference(scene,{width:128,height:128,enableShadows:false,animation:{clipId:'animation:gltf:0',timeSeconds:0}}),b=renderSpatialReference(scene,{width:128,height:128,enableShadows:false,animation:{clipId:'animation:gltf:0',timeSeconds:.8}});assert.equal(a.framePlan.sourceRealityRoot,b.framePlan.sourceRealityRoot);assert.notEqual(a.framePlan.animationRoot,b.framePlan.animationRoot);assert.notEqual(a.pixelRoot,b.pixelRoot)});

test('glTF PBR importer maps metallic roughness normal occlusion emissive and alpha contracts',()=>{const result=importGltfToSpatialScene(pbrFixture(),{sceneId:'gltf-pbr'}),material=result.scene.materials[0]!;assert.equal(result.receipt.materialTextureBindingCount,5);assert.equal(material.metallicRoughnessTextureId,'texture:gltf:1');assert.equal(material.normalTextureId,'texture:gltf:2');assert.equal(material.occlusionTextureId,'texture:gltf:3');assert.equal(material.emissiveTextureId,'texture:gltf:4');assert.equal(material.alphaMode,'MASK');assert.equal(material.alphaCutoff,.4);assert.equal(result.scene.textures?.[0]?.filter,'linear');assert.equal(result.scene.textures?.[0]?.wrapU,'clamp')});
test('glTF material extensions map clearcoat, IOR and emissive strength into VSR PBR',()=>{const value=pbrFixture() as any;value.materials[0].extensions={KHR_materials_clearcoat:{clearcoatFactor:.82,clearcoatRoughnessFactor:.06},KHR_materials_ior:{ior:1.82},KHR_materials_emissive_strength:{emissiveStrength:2.4}};const result=importGltfToSpatialScene(value,{sceneId:'gltf-material-extensions'}),material=result.scene.materials[0]!;assert.equal(material.clearcoat,.82);assert.equal(material.clearcoatRoughness,.06);assert.equal(material.ior,1.82);assert.equal(material.emissiveStrength,2.4);const base=importGltfToSpatialScene(pbrFixture(),{sceneId:'gltf-material-extensions-base'});assert.notEqual(renderSpatialReference(result.scene,{width:96,height:64,enableShadows:false}).pixelRoot,renderSpatialReference(base.scene,{width:96,height:64,enableShadows:false}).pixelRoot)});
test('glTF complete PBR textures change pixels without rewriting authority root',()=>{const {scene}=importGltfToSpatialScene(pbrFixture(),{sceneId:'gltf-pbr-render'}),full=renderSpatialReference(scene,{width:128,height:128,enableShadows:false});const material=scene.materials[0]!;delete material.metallicRoughnessTextureId;delete material.normalTextureId;delete material.occlusionTextureId;delete material.emissiveTextureId;const reduced=renderSpatialReference(scene,{width:128,height:128,enableShadows:false});assert.equal(full.framePlan.sourceRealityRoot,reduced.framePlan.sourceRealityRoot);assert.equal(full.framePlan.stats.materialTextureBindings,5);assert.equal(reduced.framePlan.stats.materialTextureBindings,1);assert.notEqual(full.pixelRoot,reduced.pixelRoot)});
test('glTF PBR import receipt seals material texture binding evidence',()=>{const result=importGltfToSpatialScene(pbrFixture());assert.equal(verifyGltfImportReceipt(result.receipt),true);result.receipt.materialTextureBindingCount--;assert.equal(verifyGltfImportReceipt(result.receipt),false)});
test('glTF compressed texture extensions select their alternative image source',()=>{const value=fixture() as any;value.images=[{extras:{vsrRGBA:{width:1,height:1,pixels:[255,20,20,255]}}},{extras:{vsrRGBA:{width:1,height:1,pixels:[20,220,255,255]}}}];value.textures=[{source:0,extensions:{KHR_texture_basisu:{source:1}}}];assert.deepEqual(resolveGltfTextureSource(value.textures[0]),{imageIndex:1,kind:'KHR_texture_basisu'});const result=importGltfToSpatialScene(value,{sceneId:'gltf-basis-source'});assert.deepEqual(result.scene.textures?.[0]?.pixels,[20,220,255,255]);assert.equal(result.receipt.warnings.length,0)});
test('KTX2 decoder materializes native RGBA8 and SRGB mip levels',()=>{const texture=decodeKtx2ToSpatialTexture(ktx2Fixture(),'texture:ktx2');assert.equal(texture.width,2);assert.equal(texture.height,2);assert.equal(texture.colorSpace,'srgb');assert.deepEqual(texture.pixels.slice(0,8),[255,0,0,255,0,255,0,255]);assert.equal(texture.mipmaps?.[0]?.width,1);assert.deepEqual(texture.mipmaps?.[0]?.pixels,[128,128,128,255])});
test('glTF image decoder routes KTX2 without browser bitmap APIs',async()=>{const texture=await decodeGltfImageToSpatialTexture({imageIndex:0,image:{mimeType:'image/ktx2'},id:'texture:ktx2-decoded',sampler:{},bytes:ktx2Fixture(),mimeType:'image/ktx2'});assert.equal(texture.id,'texture:ktx2-decoded');assert.equal(texture.mipmaps?.length,1)});
test('glTF importer materializes skin joints weights and morph targets',()=>{const result=importGltfToSpatialScene(deformationFixture(),{sceneId:'gltf-deformation'}),mesh=result.scene.meshes[0]!,node=result.scene.nodes[0]!,frame=compileSpatialFrame(result.scene,{width:128,height:128,enableShadows:false});assert.equal(result.receipt.skinCount,1);assert.equal(result.receipt.morphTargetCount,1);assert.equal(result.scene.skins?.[0]?.joints[0],'node:gltf:1');assert.equal(mesh.jointIndices?.length,12);assert.equal(mesh.jointWeights?.length,12);assert.equal(mesh.morphTargets?.length,1);assert.equal(node.skinId,'skin:gltf:0');assert.deepEqual(node.morphWeights,[1]);assert.equal(frame.stats.skinnedDraws,1);assert.equal(frame.stats.morphedDraws,1);assert.ok(frame.resources.some(resource=>resource.kind==='joint-buffer'));assert.ok(frame.resources.some(resource=>resource.kind==='morph-buffer'));assert.equal(verifyGltfImportReceipt(result.receipt),true)});
test('glTF importer preserves quaternion CUBICSPLINE animation data',()=>{const result=importGltfToSpatialScene(cubicRotationFixture(),{sceneId:'gltf-cubic-rotation'}),channel=result.scene.animations?.[0]?.channels[0]!,sample=sampleSpatialAnimation(result.scene,'animation:gltf:0',.5,false).get('node:gltf:0')?.rotationQuaternion!;assert.equal(channel.path,'rotationQuaternion');assert.equal(channel.interpolation,'CUBICSPLINE');assert.equal(channel.values.length,2);assert.equal(channel.inTangents?.length,2);assert.equal(channel.outTangents?.length,2);assert.ok(Math.abs(sample[2]-Math.sqrt(.5))<1e-6);assert.ok(Math.abs(sample[3]-Math.sqrt(.5))<1e-6);const rest=compileSpatialFrame(result.scene,{width:128,height:128,enableShadows:false,animation:{clipId:'animation:gltf:0',timeSeconds:0}}),animated=compileSpatialFrame(result.scene,{width:128,height:128,enableShadows:false,animation:{clipId:'animation:gltf:0',timeSeconds:.5}});assert.equal(rest.sourceRealityRoot,animated.sourceRealityRoot);assert.notEqual(rest.animationRoot,animated.animationRoot);assert.notEqual(rest.frameRoot,animated.frameRoot);assert.equal(verifyGltfImportReceipt(result.receipt),true)});
test('glTF external image resolver and node matrix preserve presentation inputs',()=>{const value=fixture() as any;value.images=[{uri:'albedo.png'}];value.nodes=[{mesh:0,matrix:[1,0,0,0,0,1,0,0,0,0,1,0,1.5,.25,0,1]}];const result=importGltfToSpatialScene(value,{sceneId:'gltf-external-image-matrix',imageResolver:({id})=>({id,width:1,height:1,pixels:[40,180,255,255],filter:'linear'})}),node=result.scene.nodes[0]!,frame=compileSpatialFrame(result.scene,{width:128,height:128,enableShadows:false});assert.equal(result.scene.textures?.length,1);assert.equal(result.receipt.warnings.length,0);assert.deepEqual(node.transform?.matrix,[1,0,0,1.5,0,1,0,.25,0,0,1,0,0,0,0,1]);assert.equal(frame.drawPackets[0]?.worldMatrix[3],1.5);assert.equal(frame.drawPackets[0]?.worldMatrix[7],.25);assert.equal(verifyGltfImportReceipt(result.receipt),true)});
test('glTF sparse normalized accessors materialize deterministic UV values',()=>{const value=fixture() as any;let binary=Buffer.from(value.buffers[0].uri.split(',')[1],'base64');const append=(data:ArrayBufferView)=>{let offset=binary.length;while(offset%4)offset++;const next=Buffer.alloc(offset+data.byteLength);binary.copy(next);Buffer.from(data.buffer,data.byteOffset,data.byteLength).copy(next,offset);binary=next;value.buffers[0].byteLength=next.length;value.buffers[0].uri=`data:application/octet-stream;base64,${next.toString('base64')}`;value.bufferViews.push({buffer:0,byteOffset:offset,byteLength:data.byteLength});return value.bufferViews.length-1},indicesView=append(new Uint8Array([1])),valuesView=append(new Uint8Array([255,0])),accessorIndex=value.accessors.length;value.accessors.push({componentType:5121,count:3,type:'VEC2',normalized:true,sparse:{count:1,indices:{bufferView:indicesView,componentType:5121},values:{bufferView:valuesView}}});value.meshes[0].primitives[0].attributes.TEXCOORD_0=accessorIndex;const result=importGltfToSpatialScene(value,{sceneId:'gltf-sparse-normalized'});assert.deepEqual(result.scene.meshes[0]?.uvs,[0,0,1,0,0,0]);assert.equal(verifyGltfImportReceipt(result.receipt),true)});
test('GLB v2 parser materializes JSON and BIN chunks into a sealed spatial asset',()=>{const bytes=glbFixture(),parsed=parseGlb(bytes),result=importGlbToSpatialScene(bytes,{sceneId:'glb-test'});assert.equal(parsed.gltf.asset.version,'2.0');assert.ok(parsed.binaryChunk?.byteLength);assert.equal(result.scene.meshes.length,1);assert.equal(result.scene.textures?.length,1);assert.equal(result.receipt.warnings.length,0);assert.equal(result.receipt.sourceRoot.length,64);assert.equal(verifyGltfImportReceipt(result.receipt),true);const altered=bytes.slice(),binaryOffset=parsed.binaryChunk?bytes.length-parsed.binaryChunk.length:bytes.length-1;altered[binaryOffset]=(altered[binaryOffset]??0)^1;assert.notEqual(importGlbToSpatialScene(altered,{sceneId:'glb-test'}).receipt.sourceRoot,result.receipt.sourceRoot)});
test('async glTF image decoding receives embedded image bytes and binds a texture',async()=>{const value=fixture() as any;value.images=[{uri:'data:image/png;base64,AAECAw==',mimeType:'image/png'}];let seen=0;const result=await importGltfToSpatialSceneAsync(value,{sceneId:'gltf-async-image',imageDecoder:async input=>{seen=input.bytes.length;return{id:input.id,width:1,height:1,pixels:[10,20,30,255],filter:'linear'}}});assert.equal(seen,4);assert.equal(result.scene.textures?.length,1);assert.equal(result.receipt.warnings.length,0);assert.equal(verifyGltfImportReceipt(result.receipt),true)});
test('async glTF decoding reads the selected WebP extension image',async()=>{const value=fixture() as any;value.images=[{uri:'fallback.png',mimeType:'image/png'},{uri:'albedo.webp',mimeType:'image/webp'}];value.textures=[{source:0,extensions:{EXT_texture_webp:{source:1}}}];let seen:{imageIndex:number;mimeType?:string;bytes:number}|undefined;const result=await importGltfToSpatialSceneAsync(value,{imageBytes:{'albedo.webp':new Uint8Array([8,7,6])},imageDecoder:async input=>{seen={imageIndex:input.imageIndex,mimeType:input.mimeType,bytes:input.bytes.length};return{id:input.id,width:1,height:1,pixels:[8,7,6,255]}}});assert.deepEqual(seen,{imageIndex:1,mimeType:'image/webp',bytes:3});assert.equal(result.scene.textures?.[0]?.pixels?.[0],8);assert.equal(result.receipt.warnings.length,0)});
test('browser glTF image decoder converts a decoded bitmap into RGBA pixels',async()=>{const globals=globalThis as any,previousBitmap=globals.createImageBitmap,previousCanvas=globals.OffscreenCanvas;let closed=false;globals.createImageBitmap=async()=>({width:2,height:1,close:()=>{closed=true}});globals.OffscreenCanvas=class{width:number;height:number;constructor(width:number,height:number){this.width=width;this.height=height}getContext(){return{drawImage:()=>undefined,getImageData:()=>({data:new Uint8ClampedArray([1,2,3,255,5,6,7,255])})}}};try{const texture=await decodeGltfImageToSpatialTexture({imageIndex:0,image:{mimeType:'image/png'},id:'texture:decoded',sampler:{},bytes:new Uint8Array([137,80,78,71]),mimeType:'image/png'});assert.equal(texture.width,2);assert.deepEqual(texture.pixels,[1,2,3,255,5,6,7,255]);assert.equal(closed,true)}finally{if(previousBitmap===undefined)delete globals.createImageBitmap;else globals.createImageBitmap=previousBitmap;if(previousCanvas===undefined)delete globals.OffscreenCanvas;else globals.OffscreenCanvas=previousCanvas}});
test('async GLB import decodes image bytes from a BIN bufferView',async()=>{const bytes=glbFixture(),parsed=parseGlb(bytes),gltf=parsed.gltf as any;const binary=parsed.binaryChunk!;const imageOffset=binary.length;const imageBytes=new Uint8Array([9,8,7,6]);const next=new Uint8Array(binary.length+imageBytes.length);next.set(binary);next.set(imageBytes,binary.length);gltf.bufferViews=[...(gltf.bufferViews??[]),{buffer:0,byteOffset:imageOffset,byteLength:imageBytes.length}];gltf.images=[{bufferView:gltf.bufferViews.length-1,mimeType:'image/png'}];gltf.textures=[{source:0}];gltf.materials[0].pbrMetallicRoughness.baseColorTexture={index:0};const jsonBytes=Buffer.from(JSON.stringify(gltf),'utf8'),jsonLength=(jsonBytes.length+3)&~3,binLength=(next.length+3)&~3,total=12+8+jsonLength+8+binLength,out=Buffer.alloc(total);jsonBytes.copy(out,20);out.fill(0x20,20+jsonBytes.length,20+jsonLength);Buffer.from(next).copy(out,28+jsonLength);out.writeUInt32LE(0x46546c67,0);out.writeUInt32LE(2,4);out.writeUInt32LE(total,8);out.writeUInt32LE(jsonLength,12);out.writeUInt32LE(0x4e4f534a,16);out.writeUInt32LE(binLength,20+jsonLength);out.writeUInt32LE(0x004e4942,24+jsonLength);let seen=0;const result=await importGlbToSpatialSceneAsync(new Uint8Array(out),{imageDecoder:async input=>{seen=input.bytes.length;return{id:input.id,width:1,height:1,pixels:[9,8,7,255]}}});assert.equal(seen,4);assert.equal(result.scene.textures?.length,1);assert.equal(result.receipt.warnings.length,0)});
test('glTF receipt detects tampering',()=>{const result=importGltfToSpatialScene(fixture());assert.equal(verifyGltfImportReceipt(result.receipt),true);result.receipt.meshCount++;assert.equal(verifyGltfImportReceipt(result.receipt),false)});

let passed=0;for(const entry of tests){try{await entry.fn();passed++;console.log(`PASS ${entry.name}`)}catch(error){console.error(`FAIL ${entry.name}`);throw error}}console.log(`VSR glTF asset tests: ${passed}/${tests.length} PASS`);
