import { readFileSync, rmSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { cryptographicHash, type VSRDocument } from '../../spec/src/index.js';
import type { VSRBitmapFont } from '../../backend-canvas/src/index.js';

export const VSR_FONT_FREEZE_VERSION='0.1.0-alpha.12';
export interface VSRFrozenFont extends VSRBitmapFont {
  metadata?: { sourceFontHash?:string; glyphSetHash:string; glyphCount:number; generatedBy:string; pixelSize?:number };
}
export interface VSRFontFreezeResult { format:'vsr.font-freeze-result.v0.1'; output:string; family:string; glyphCount:number; glyphSetHash:string; fontHash:string; sourceFontHash?:string }

export function collectGlyphs(text:string):string[]{return[...new Set([...text].filter(character=>character!=='\r'&&character!=='\n'))].sort((a,b)=>a.codePointAt(0)!-b.codePointAt(0)!);}
export function collectDocumentText(document:VSRDocument):string {const chunks:string[]=[];for(const node of document.nodes){if(node.type!=='text')continue;const value=(node.content as Record<string,unknown>|undefined)?.text;if(typeof value==='string')chunks.push(value);}return chunks.join('\n');}
export function verifyFrozenFont(font:VSRFrozenFont,requiredText=''):{ok:boolean;diagnostics:string[];fontHash:string;glyphSetHash:string}{const diagnostics:string[]=[];if(font.format!=='vsr-bitmap-font-1')diagnostics.push('format 必须为 vsr-bitmap-font-1');if(!font.family)diagnostics.push('family 不能为空');if(!Number.isInteger(font.glyphWidth)||font.glyphWidth<=0)diagnostics.push('glyphWidth 无效');if(!Number.isInteger(font.glyphHeight)||font.glyphHeight<=0)diagnostics.push('glyphHeight 无效');for(const [character,rows] of Object.entries(font.glyphs??{})){if(rows.length!==font.glyphHeight)diagnostics.push(`${character} 行数不等于 glyphHeight`);if(rows.some(row=>row.length!==font.glyphWidth||/[^01]/.test(row)))diagnostics.push(`${character} 字形不是固定宽度二值位图`);}for(const character of collectGlyphs(requiredText))if(!font.glyphs[character])diagnostics.push(`缺少字形：U+${character.codePointAt(0)!.toString(16).toUpperCase().padStart(4,'0')} ${character}`);const glyphSetHash=cryptographicHash(Object.keys(font.glyphs).sort());return{ok:diagnostics.length===0,diagnostics,fontHash:cryptographicHash(font),glyphSetHash};}
export function freezeFontWithPython(options:{fontPath:string;family:string;text:string;pixelSize:number;outPath:string;python?:string;scriptPath?:string}):VSRFontFreezeResult {const textPath=resolve(`${options.outPath}.glyphs.txt`);writeFileSync(textPath,options.text);const script=resolve(options.scriptPath??'scripts/freeze-font.py');const result=spawnSync(options.python??'python3',[script,'--font',resolve(options.fontPath),'--family',options.family,'--text-file',textPath,'--size',String(options.pixelSize),'--out',resolve(options.outPath)],{encoding:'utf8'});try{if(result.status!==0)throw new Error(String(result.stderr||result.stdout||'字体冻结失败'));const font=JSON.parse(readFileSync(resolve(options.outPath),'utf8')) as VSRFrozenFont;const verification=verifyFrozenFont(font,options.text);if(!verification.ok)throw new Error(`字体冻结验证失败：${verification.diagnostics.join('；')}`);return{format:'vsr.font-freeze-result.v0.1',output:resolve(options.outPath),family:font.family,glyphCount:Object.keys(font.glyphs).length,glyphSetHash:verification.glyphSetHash,fontHash:verification.fontHash,sourceFontHash:font.metadata?.sourceFontHash};}finally{try{rmSync(textPath,{force:true});}catch{void 0;}}}
