import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import fs from 'node:fs';import os from 'node:os';import {fileURLToPath} from 'node:url';
import {normalizeBuildRequest,buildProject,readJson} from '../src/index.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),projectFile=path.join(root,'examples','冰境试炼.unified-project.json');
function makeFakeGradle(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rbf-gradle-')),file=path.join(dir,'gradle');fs.writeFileSync(file,`#!/usr/bin/env sh\nif [ "$1" = "--version" ]; then echo "Gradle 8.7"; exit 0; fi\nmkdir -p app/build/outputs/apk/debug\npython3 - <<'PY'\nimport zipfile\nwith zipfile.ZipFile('app/build/outputs/apk/debug/app-debug.apk','w') as z:\n z.writestr('AndroidManifest.xml',b'mock')\n z.writestr('classes.dex',b'dex')\nPY\n`,{mode:0o755});return file;}
test('自动 APK 目标执行 Gradle 并产出签名调试包',()=>{
 const sdk=fs.mkdtempSync(path.join(os.tmpdir(),'rbf-sdk-')),gradle=makeFakeGradle(),out=fs.mkdtempSync(path.join(os.tmpdir(),'rbf-apk-'));
 const before={sdk:process.env.ANDROID_SDK_ROOT,gradle:process.env.RBF_GRADLE_COMMAND};process.env.ANDROID_SDK_ROOT=sdk;process.env.RBF_GRADLE_COMMAND=gradle;
 try{const b=buildProject(normalizeBuildRequest({project_file:projectFile,output_dir:out,targets:['android-apk'],app:{app_id:'com.taowind.apk',title:'安卓验收',version_name:'0.2.0',version_code:2}}));const dir=path.join(out,'android-apk'),apk=fs.readdirSync(dir).find(x=>x.endsWith('.apk'));assert.ok(apk);assert.equal(fs.readFileSync(path.join(dir,apk)).subarray(0,2).toString(),'PK');const m=readJson(path.join(dir,'android-build-manifest.json'));assert.equal(m.apk_built,true);assert.equal(m.signed,true);assert.equal(m.signing_identity,'android-debug-keystore');assert.equal(b.verification.valid,true);}finally{if(before.sdk===undefined)delete process.env.ANDROID_SDK_ROOT;else process.env.ANDROID_SDK_ROOT=before.sdk;if(before.gradle===undefined)delete process.env.RBF_GRADLE_COMMAND;else process.env.RBF_GRADLE_COMMAND=before.gradle;}
});
