import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import fs from 'node:fs';import {fileURLToPath} from 'node:url';
import {normalizeBuildRequest,validateBuildRequest,validateUnifiedProject,createBuildIdentity,verifySeal,SUPPORTED_TARGETS,TARGET_PROFILES,readJson} from '../src/index.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),projectFile=path.join(root,'examples','冰境试炼.unified-project.json'),project=readJson(projectFile);
const base=()=>normalizeBuildRequest({project_file:projectFile,output_dir:path.join(root,'output','test-contract'),targets:['web-release'],app:{app_id:'com.taowind.test',title:'测试'}});
test('支持八种构建目标',()=>assert.deepEqual(SUPPORTED_TARGETS,['web-release','web-single','windows-portable','windows-native','android-project','android-apk','headless-server','replay-bundle']));
test('原生 Windows 目标存在',()=>assert.equal(TARGET_PROFILES['windows-native'].kind,'native-windows-executable'));
test('自动 APK 目标存在',()=>assert.equal(TARGET_PROFILES['android-apk'].kind,'compiled-signed-debug-apk'));
test('每种目标都有配置',()=>SUPPORTED_TARGETS.forEach(t=>assert.ok(TARGET_PROFILES[t])));
test('请求被规范化',()=>assert.equal(base().format,'reality-build.request.v0.1'));
test('请求版本正确',()=>assert.equal(base().version,'0.2.0-alpha.1'));
test('默认发布模式',()=>assert.equal(base().mode,'release'));
test('默认平衡质量',()=>assert.equal(base().quality_profile,'balanced'));
test('请求根可验证',()=>assert.ok(verifySeal(base(),'request_root')));
test('目标会去重',()=>assert.deepEqual(normalizeBuildRequest({...base(),targets:['web-release','web-release']}).targets,['web-release']));
test('开发模式保留',()=>assert.equal(normalizeBuildRequest({...base(),mode:'development'}).mode,'development'));
test('无效模式回落发布',()=>assert.equal(normalizeBuildRequest({...base(),mode:'x'}).mode,'release'));
test('无效目标被拒绝',()=>{const r=normalizeBuildRequest({...base(),targets:['ps6']});assert.equal(validateBuildRequest(r).valid,false)});
test('无效 app id 被拒绝',()=>{const r=normalizeBuildRequest({...base(),app:{app_id:'bad id',title:'x'}});assert.equal(validateBuildRequest(r).valid,false)});
test('Android 电影级给出警告',()=>{const r=normalizeBuildRequest({...base(),targets:['android-project'],quality_profile:'cinematic'});assert.ok(validateBuildRequest(r).warnings.some(x=>x.code==='ANDROID_CINEMATIC_DOWNGRADED'))});
test('项目格式有效',()=>assert.equal(validateUnifiedProject(project).valid,true));
test('项目统计四资产',()=>assert.equal(validateUnifiedProject(project).counts.assets,4));
test('项目统计四节点',()=>assert.equal(validateUnifiedProject(project).counts.nodes,4));
test('缺失活动场景会失败',()=>{const p=structuredClone(project);p.active_scene_id='missing';assert.equal(validateUnifiedProject(p).valid,false)});
test('节点引用缺失资产产生警告',()=>{const p=structuredClone(project);p.scenes[0].nodes[0].asset_id='missing';assert.ok(validateUnifiedProject(p).warnings.some(x=>x.code==='NODE_ASSET_UNRESOLVED'))});
test('构建身份确定性',()=>{const r=base();assert.equal(createBuildIdentity(r,project).build_key,createBuildIdentity(r,project).build_key)});
test('输出目录不影响语义构建键',()=>{const a=base(),b=normalizeBuildRequest({...a,output_dir:path.join(root,'output','elsewhere')});assert.equal(createBuildIdentity(a,project).build_key,createBuildIdentity(b,project).build_key)});
test('质量影响构建键',()=>{const a=base(),b=normalizeBuildRequest({...a,quality_profile:'quality'});assert.notEqual(createBuildIdentity(a,project).build_key,createBuildIdentity(b,project).build_key)});
test('目标影响构建键',()=>{const a=base(),b=normalizeBuildRequest({...a,targets:['web-single']});assert.notEqual(createBuildIdentity(a,project).build_key,createBuildIdentity(b,project).build_key)});
test('空间轨迹被规范化并纳入构建键',()=>{const r=normalizeBuildRequest({...base(),spatial_trace:[[{type:'apply-impulse',bodyId:'orb',impulse:{x:1000,y:0,z:0}}]]}),v=validateBuildRequest(r);assert.equal(v.valid,true);assert.equal(r.spatial_trace[0][0].id,'build-spatial-command:1:1');const empty=base();assert.notEqual(createBuildIdentity(r,project).build_key,createBuildIdentity(empty,project).build_key)});
