import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import fs from 'node:fs';import os from 'node:os';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {normalizeBuildRequest,readJson,runBuildPreflight,doctorReport,verifySeal} from '../src/index.mjs';
import {commandInvocation} from '../src/preflight.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),projectFile=path.join(root,'examples','冰境试炼.unified-project.json'),project=readJson(projectFile);
function request(targets){return normalizeBuildRequest({project_file:projectFile,output_dir:path.join(os.tmpdir(),'rbf-preflight'),targets,app:{app_id:'com.taowind.preflight',title:'预检'}})}
test('Web 构建无需外部工具链',()=>{const p=runBuildPreflight({request:request(['web-single']),project,env:{PATH:''}});assert.equal(p.status,'ready');assert.equal(p.blocked.length,0)});
test('预检结果可验证',()=>assert.ok(verifySeal(runBuildPreflight({request:request(['web-single']),project}),'preflight_root')));
test('Windows 原生要求 Go',()=>{const p=runBuildPreflight({request:request(['windows-native']),project,env:{PATH:''}});assert.equal(p.status,'blocked');assert.ok(p.blocked.some(x=>x.capability==='toolchain.go'))});
const nativePreflight=runBuildPreflight({request:request(['windows-native']),project});
test('当前环境可构建 Windows 原生目标',{skip:nativePreflight.status!=='ready'},()=>{assert.equal(nativePreflight.status,'ready')});
test('Android APK 缺工具链时阻止构建',()=>{const empty=fs.mkdtempSync(path.join(os.tmpdir(),'rbf-empty-'));const p=runBuildPreflight({request:request(['android-apk']),project,env:{PATH:'',ANDROID_SDK_ROOT:empty}});assert.equal(p.status,'blocked');assert.ok(p.blocked.length>=2)});
test('Android 工程仅给工具链警告',()=>{const p=runBuildPreflight({request:request(['android-project']),project,env:{PATH:''}});assert.equal(p.status,'ready');assert.ok(p.warnings.some(x=>x.code==='ANDROID_PROJECT_TOOLCHAIN_NOT_READY'))});
test('Doctor 识别 Windows build-tools 中的 apksigner.bat',()=>{const sdk=fs.mkdtempSync(path.join(os.tmpdir(),'rbf-sdk-tools-'));const buildTools=path.join(sdk,'build-tools','36.1.0');fs.mkdirSync(buildTools,{recursive:true});const signer=path.join(buildTools,'apksigner.bat');fs.writeFileSync(signer,'@echo off\r\n');const d=doctorReport({env:{PATH:'',ANDROID_SDK_ROOT:sdk},includePaths:true});assert.equal(d.toolchains.android_sdk.apksigner,signer)});
test('Windows BAT command adapter preserves paths with spaces',{skip:process.platform!=='win32'},()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rbf-bat space-')),script=path.join(dir,'tool with spaces.bat'),argument=path.join(dir,'argument with spaces.txt');fs.writeFileSync(script,'@echo off\r\necho [%~1]\r\n');const invocation=commandInvocation(script,[argument]),result=spawnSync(invocation.command,invocation.args,{encoding:'utf8',windowsHide:true,windowsVerbatimArguments:true});assert.equal(result.status,0);assert.match(result.stdout,/argument with spaces\.txt/)});
test('Doctor 暴露平台和工具链',()=>{const d=doctorReport();assert.equal(d.format,'reality-build.doctor.v0.2');assert.ok(d.toolchains.platform.os);assert.equal(typeof d.toolchains.go.available,'boolean')});
