import test from 'node:test';import assert from 'node:assert/strict';import {buildBrowserBehaviorRuntime,buildBrowserRSRRuntime,buildBrowserVSRRuntime,buildGameSource,renderIndexHtml} from '../src/index.mjs';
const runtime=buildBrowserBehaviorRuntime(),game=buildGameSource();
test('浏览器行为运行时可解析',()=>assert.doesNotThrow(()=>new Function(runtime)));
test('浏览器游戏宿主可解析',()=>assert.doesNotThrow(()=>new Function(game)));
test('运行时暴露 BehaviorRuntime',()=>assert.match(runtime,/RNCSBehavior=\{BehaviorRuntime/));
test('运行时不包含 node crypto 导入',()=>assert.doesNotMatch(runtime,/node:crypto/));
test('游戏宿主使用统一行为与空间 Tick',()=>{assert.match(game,/function advance\(input=\{\}\)/);assert.match(game,/runtime\.tick\(input\)/);assert.match(game,/syncSpatialRuntime\(\)/);assert.match(game,/function tick\(\)\{advance\(inputState\(\)\)/)});
test('游戏宿主包含触摸控制',()=>assert.match(game,/data-action/));
test('游戏宿主包含音频 Provider',()=>assert.match(game,/experience\.audio\.emit/));
test('游戏宿主包含特效 Provider',()=>assert.match(game,/experience\.effect\.emit/));
test('游戏宿主包含 VSR WebGPU 入口与回退',()=>{assert.match(game,/VSRRealtimeWebGPUExecutor/);assert.match(game,/Canvas 2D/);assert.match(game,/gpu_frame_plan/)});
test('浏览器 VSR 入口无 Node 依赖',()=>{const source=buildBrowserVSRRuntime();assert.doesNotMatch(source,/node:/);assert.match(source,/VSRRealtimeWebGPUExecutor/);assert.match(source,/createRealtimeWebGPUFrame/);assert.match(source,/verifyRealtimeWebGPUFrame/);assert.match(source,/__RNCSVSR__/)});
test('浏览器 RSR 入口包含真实空间运行时',()=>{const source=buildBrowserRSRRuntime();assert.doesNotMatch(source,/node:/);assert.match(source,/SpatialEmbodimentWorld/);assert.match(source,/verifySpatialEmbodimentSnapshot/);assert.match(source,/__RNCSRSR__/)});
test('游戏宿主按行为 Tick 生成动态 GPU 帧快照',()=>{assert.match(game,/dynamicGPUFrame/);assert.match(game,/gpuFrameSnapshot/);assert.match(game,/runtime\.stateRoot\(\)/)});
test('单文件 HTML 嵌入运行时',()=>{const h=renderIndexHtml({title:'T',inline:true,runtimeSource:runtime,rsrRuntimeSource:'window.__RNCSRSR__={};',gpuRuntimeSource:'window.__RNCSVSR__={};',gameSource:game,payload:{project:{},assets:{},build:{}}});assert.match(h,/RNCSBehavior/);assert.match(h,/__RNCSRSR__/);assert.match(h,/__RNCSVSR__/);assert.doesNotMatch(h,/src="runtime\.js"/)});
test('文件夹 HTML 引用外部脚本',()=>{const h=renderIndexHtml({title:'T'});assert.match(h,/src="runtime\.js"/);assert.match(h,/src="rsr-runtime\.js"/);assert.match(h,/src="vsr-runtime\.js"/);assert.match(h,/src="game\.js"/)});
test('HTML 有移动端视口',()=>assert.match(renderIndexHtml({title:'T'}),/viewport-fit=cover/));
test('HTML 有 Canvas 渲染与 GPU 画布',()=>{const h=renderIndexHtml({title:'T'});assert.match(h,/id="game"/);assert.match(h,/id="gpu-game"/)});
