export type AppExportTarget =
  | "SINGLE_HTML_FILE" | "REACT_DRAFT_FILES" | "VITE_PROJECT_DRAFT"
  | "MARKDOWN_SPEC" | "CODEX_HANDOFF_PACK" | "CURSOR_HANDOFF_PACK"
  | "LOVABLE_HANDOFF_PACK" | "QA_REPORT" | "ZIP_DRAFT";

export const APP_EXPORT_TARGETS: AppExportTarget[] = [
  "SINGLE_HTML_FILE","REACT_DRAFT_FILES","VITE_PROJECT_DRAFT",
  "MARKDOWN_SPEC","CODEX_HANDOFF_PACK","CURSOR_HANDOFF_PACK",
  "LOVABLE_HANDOFF_PACK","QA_REPORT","ZIP_DRAFT",
];

export const APP_EXPORT_LABELS: Record<AppExportTarget, string> = {
  SINGLE_HTML_FILE: "单文件 HTML",
  REACT_DRAFT_FILES: "React 草案文件",
  VITE_PROJECT_DRAFT: "Vite 项目草案",
  MARKDOWN_SPEC: "Markdown 说明",
  CODEX_HANDOFF_PACK: "Codex 任务包",
  CURSOR_HANDOFF_PACK: "Cursor 任务包",
  LOVABLE_HANDOFF_PACK: "Lovable 提示词包",
  QA_REPORT: "QA 报告",
  ZIP_DRAFT: "ZIP 草案（清单）",
};
