import { cryptographicHash } from '../../spec/src/index.js';
import {
  VSR_SPATIAL_SCENE_FORMAT,
  type Mat4,
  type Vec3,
  type Vec4,
  type VSRSpatialAnimationChannel,
  type VSRSpatialAnimationClip,
  type VSRSpatialAnimationPath,
  type VSRSpatialCamera,
  type VSRSpatialLight,
  type VSRSpatialMaterial,
  type VSRSpatialMesh,
  type VSRSpatialNode,
  type VSRSpatialScene3D,
  type VSRSpatialSkin,
  type VSRSpatialTexture,
  type VSRSpatialTextureLevel,
  identityMat4,
} from '../../spatial-reality-3d/src/index.js';

export const VSR_GLTF_ASSET_VERSION='0.2.0-alpha.1';
export const VSR_GLTF_IMPORT_FORMAT='vsr.gltf-import-receipt.v0.2' as const;

type Json=Record<string,any>;
export interface VSRGltfImageResolverInput {imageIndex:number;image:Json;id:string;sampler:Json}
export type VSRGltfImageResolver=(input:VSRGltfImageResolverInput)=>VSRSpatialTexture|undefined;
export interface VSRGltfImageDecoderInput extends VSRGltfImageResolverInput {bytes:Uint8Array;mimeType?:string}
export type VSRGltfImageDecoder=(input:VSRGltfImageDecoderInput)=>Promise<VSRSpatialTexture|undefined>;
export interface VSRGltfImportOptions {sceneId?:string;title?:string;buffers?:Record<string,Uint8Array>;imageBytes?:Record<string,Uint8Array>;defaultCamera?:boolean;imageResolver?:VSRGltfImageResolver;imageDecoder?:VSRGltfImageDecoder;sourceRoot?:string}
export interface VSRGltfImportReceipt {format:typeof VSR_GLTF_IMPORT_FORMAT;assetVersion:string;sceneId:string;meshCount:number;nodeCount:number;materialCount:number;textureCount:number;materialTextureBindingCount:number;animationCount:number;skinCount:number;morphTargetCount:number;sourceRoot:string;sceneRoot:string;warnings:string[];receiptRoot:string}
export interface VSRGltfImportResult {scene:VSRSpatialScene3D;receipt:VSRGltfImportReceipt}
export interface VSRGlbParseResult {gltf:Json;binaryChunk?:Uint8Array}
export type VSRGltfTextureSourceKind='KHR_texture_basisu'|'EXT_texture_webp'|'source';
export interface VSRGltfTextureSource {imageIndex:number;kind:VSRGltfTextureSourceKind}

const GLB_MAGIC=0x46546c67;
const GLB_VERSION=2;
const GLB_JSON_CHUNK=0x4e4f534a;
const GLB_BIN_CHUNK=0x004e4942;

const componentSize:Record<number,number>={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4};
const componentCount:Record<string,number>={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16};
const readComponent=(view:DataView,offset:number,type:number):number=>{
  if(type===5120)return view.getInt8(offset);if(type===5121)return view.getUint8(offset);if(type===5122)return view.getInt16(offset,true);if(type===5123)return view.getUint16(offset,true);if(type===5125)return view.getUint32(offset,true);if(type===5126)return view.getFloat32(offset,true);throw new Error(`Unsupported glTF componentType ${type}.`);
};
function decodeDataUri(uri:string):Uint8Array{const match=/^data:([^;,]+)?(;base64)?,(.*)$/s.exec(uri);if(!match)throw new Error('Invalid data URI.');if(!match[2])return new TextEncoder().encode(decodeURIComponent(match[3]??''));const text=match[3]??'',decode=(globalThis as typeof globalThis&{atob?:(value:string)=>string}).atob;if(decode){const binary=decode(text),bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);return bytes}return Uint8Array.from(Buffer.from(text,'base64'));}
function loadBuffers(gltf:Json,options:VSRGltfImportOptions):Uint8Array[]{return (gltf.buffers??[]).map((buffer:Json,index:number)=>{if(typeof buffer.uri==='string'){if(buffer.uri.startsWith('data:'))return decodeDataUri(buffer.uri);const value=options.buffers?.[buffer.uri];if(value)return value;throw new Error(`Missing external glTF buffer ${buffer.uri}.`)}const value=options.buffers?.[`buffer:${index}`];if(value)return value;throw new Error(`Missing binary glTF buffer ${index}.`)})}
function imageBytes(gltf:Json,imageIndex:number,buffers:Uint8Array[],options:VSRGltfImportOptions):Uint8Array|undefined{const image=gltf.images?.[imageIndex];if(typeof image?.uri==='string'){if(image.uri.startsWith('data:'))return decodeDataUri(image.uri);const external=options.imageBytes?.[image.uri];if(external)return external}if(image?.bufferView!==undefined){const view=gltf.bufferViews?.[image.bufferView],buffer=buffers[view?.buffer];if(!view||!buffer)throw new Error(`Missing glTF image bufferView ${String(image.bufferView)}.`);const start=view.byteOffset??0,end=start+(view.byteLength??0);if(start<0||end>buffer.byteLength)throw new Error(`glTF image bufferView ${String(image.bufferView)} exceeds its buffer.`);return buffer.slice(start,end)}return undefined}
export function parseGlb(input:ArrayBuffer|Uint8Array):VSRGlbParseResult{const bytes=input instanceof Uint8Array?input:new Uint8Array(input),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(bytes.byteLength<12)throw new Error('Invalid GLB: header is truncated.');if(view.getUint32(0,true)!==GLB_MAGIC)throw new Error('Invalid GLB: magic does not match glTF.');if(view.getUint32(4,true)!==GLB_VERSION)throw new Error(`Unsupported GLB version ${view.getUint32(4,true)}.`);const declaredLength=view.getUint32(8,true);if(declaredLength!==bytes.byteLength)throw new Error(`Invalid GLB: declared length ${declaredLength} does not match ${bytes.byteLength}.`);let offset=12,jsonText='',binaryChunk:Uint8Array|undefined;while(offset<declaredLength){if(offset+8>declaredLength)throw new Error('Invalid GLB: chunk header is truncated.');const chunkLength=view.getUint32(offset,true),chunkType=view.getUint32(offset+4,true),chunkStart=offset+8,chunkEnd=chunkStart+chunkLength;if(chunkEnd>declaredLength)throw new Error('Invalid GLB: chunk exceeds declared length.');if(chunkType===GLB_JSON_CHUNK){if(jsonText)throw new Error('Invalid GLB: multiple JSON chunks are not supported.');if(offset!==12)throw new Error('Invalid GLB: JSON chunk must be first.');jsonText=new TextDecoder().decode(bytes.subarray(chunkStart,chunkEnd)).replace(/\u0000+$/,'').trim()}else if(chunkType===GLB_BIN_CHUNK){if(binaryChunk)throw new Error('Invalid GLB: multiple BIN chunks are not supported.');binaryChunk=bytes.slice(chunkStart,chunkEnd)}offset=chunkEnd}if(!jsonText)throw new Error('Invalid GLB: JSON chunk is missing.');let gltf:Json;try{gltf=JSON.parse(jsonText)}catch(error){throw new Error(`Invalid GLB JSON: ${error instanceof Error?error.message:String(error)}`)}return{gltf,binaryChunk}}
function normalizedComponent(value:number,componentType:number):number{if(componentType===5121)return value/255;if(componentType===5123)return value/65535;if(componentType===5125)return value/4294967295;if(componentType===5120)return Math.max(value/127,-1);if(componentType===5122)return Math.max(value/32767,-1);return value}
function readAccessorData(gltf:Json,buffers:Uint8Array[],bufferView:Json|undefined,count:number,type:string,componentType:number,byteOffset=0,normalized=false):number[]{const components=componentCount[type],size=componentSize[componentType];if(!components||!size)throw new Error(`Unsupported accessor layout ${type}/${componentType}.`);if(!bufferView)return new Array<number>(count*components).fill(0);const buffer=buffers[bufferView.buffer];if(!buffer)throw new Error(`Missing glTF buffer ${bufferView.buffer}.`);const stride=bufferView.byteStride??components*size,base=(bufferView.byteOffset??0)+byteOffset,view=new DataView(buffer.buffer,buffer.byteOffset,buffer.byteLength),values:number[]=[];for(let item=0;item<count;item++)for(let component=0;component<components;component++){const value=readComponent(view,base+item*stride+component*size,componentType);values.push(normalized?normalizedComponent(value,componentType):value)}return values}
function accessorValues(gltf:Json,buffers:Uint8Array[],index:number):number[]{const accessor=gltf.accessors?.[index];if(!accessor)throw new Error(`Missing glTF accessor ${index}.`);const components=componentCount[accessor.type];if(!components)throw new Error(`Unsupported glTF accessor type ${accessor.type}.`);const values=readAccessorData(gltf,buffers,gltf.bufferViews?.[accessor.bufferView],accessor.count,accessor.type,accessor.componentType,accessor.byteOffset??0,Boolean(accessor.normalized)),sparse=accessor.sparse;if(!sparse)return values;const sparseIndicesView=gltf.bufferViews?.[sparse.indices?.bufferView],sparseValuesView=gltf.bufferViews?.[sparse.values?.bufferView],sparseCount=Number(sparse.count??0),indexType=Number(sparse.indices?.componentType);if(!sparseIndicesView||!sparseValuesView||!sparseCount)throw new Error(`Accessor ${index} sparse declaration is incomplete.`);const sparseIndices=readAccessorData(gltf,buffers,sparseIndicesView,sparseCount,'SCALAR',indexType,sparse.indices.byteOffset??0),sparseValues=readAccessorData(gltf,buffers,sparseValuesView,sparseCount,accessor.type,accessor.componentType,sparse.values.byteOffset??0,Boolean(accessor.normalized));for(let item=0;item<sparseCount;item++){const target=Math.trunc(sparseIndices[item]!);if(target<0||target>=accessor.count)throw new Error(`Accessor ${index} sparse index ${target} is out of range.`);for(let component=0;component<components;component++)values[target*components+component]=sparseValues[item*components+component]!}return values}
const colorHex=(value:number[]|undefined,fallback='#ffffff'):string=>{if(!value)return fallback;const c=value.map((entry,index)=>Math.max(0,Math.min(255,Math.round((index===3?entry:Math.pow(entry,1/2.2))*255))));return`#${c.slice(0,4).map(v=>v.toString(16).padStart(2,'0')).join('')}`};
function quaternionValue(q:number[]|undefined):Vec4|undefined{if(!q)return undefined;return[q[0]??0,q[1]??0,q[2]??0,q[3]??1]}
function matrixValue(matrix:number[]|undefined):Mat4|undefined{if(!matrix||matrix.length!==16)return undefined;return[matrix[0]!,matrix[4]!,matrix[8]!,matrix[12]!,matrix[1]!,matrix[5]!,matrix[9]!,matrix[13]!,matrix[2]!,matrix[6]!,matrix[10]!,matrix[14]!,matrix[3]!,matrix[7]!,matrix[11]!,matrix[15]!]}
function textureSampling(sampler:Json):Pick<VSRSpatialTexture,'wrapU'|'wrapV'|'filter'>{return{wrapU:sampler.wrapS===33071?'clamp':'repeat',wrapV:sampler.wrapT===33071?'clamp':'repeat',filter:sampler.magFilter===9728||sampler.minFilter===9728?'nearest':'linear'}}
export function resolveGltfTextureSource(texture:Json):VSRGltfTextureSource|undefined{const candidates:[[VSRGltfTextureSourceKind,unknown],[VSRGltfTextureSourceKind,unknown],[VSRGltfTextureSourceKind,unknown]]=[['KHR_texture_basisu',texture.extensions?.KHR_texture_basisu?.source],['EXT_texture_webp',texture.extensions?.EXT_texture_webp?.source],['source',texture.source]];for(const [kind,value] of candidates)if(Number.isInteger(value)&&Number(value)>=0)return{imageIndex:Number(value),kind};return undefined}
function textureFromImage(gltf:Json,imageIndex:number,id:string,warnings:string[],sampler:Json={},resolver?:VSRGltfImageResolver):VSRSpatialTexture|undefined{
  const image=gltf.images?.[imageIndex];const resolved=resolver?.({imageIndex,image,id,sampler});if(resolved)return{...resolved,id};
  const raw=image?.extras?.vsrRGBA;
  if(raw&&Number.isInteger(raw.width)&&Number.isInteger(raw.height)&&Array.isArray(raw.pixels))return{id,width:raw.width,height:raw.height,pixels:raw.pixels,colorSpace:raw.colorSpace??'srgb',...textureSampling(sampler)};
  warnings.push(`image:${imageIndex}:encoded-image-preserved-without-decoder`);return undefined
}
const KTX2_IDENTIFIER=[0xab,0x4b,0x54,0x58,0x20,0x32,0x30,0xbb,0x0d,0x0a,0x1a,0x0a];
export function decodeKtx2ToSpatialTexture(input:ArrayBuffer|Uint8Array,id='texture:ktx2'):VSRSpatialTexture{const bytes=input instanceof Uint8Array?input:new Uint8Array(input),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(bytes.byteLength<104||!KTX2_IDENTIFIER.every((value,index)=>bytes[index]===value))throw new Error('Invalid KTX2 identifier.');const vkFormat=view.getUint32(12,true),typeSize=view.getUint32(16,true),width=view.getUint32(20,true),height=view.getUint32(24,true),depth=view.getUint32(28,true),layers=view.getUint32(32,true),faces=view.getUint32(36,true),levelCount=Math.max(1,view.getUint32(40,true)),supercompression=view.getUint32(44,true);if(!width||!height||depth>1||layers>1||faces!==1||typeSize!==1)throw new Error('Unsupported KTX2 dimensions or texel type.');if(vkFormat!==37&&vkFormat!==43)throw new Error(`KTX2 format ${vkFormat} requires a BasisU or host transcoder.`);if(supercompression!==0)throw new Error(`KTX2 supercompression ${supercompression} requires a BasisU or host transcoder.`);const levels:VSRSpatialTextureLevel[]=[];for(let level=0;level<levelCount;level++){const entry=80+level*24;if(entry+24>bytes.byteLength)throw new Error('KTX2 level index is truncated.');const offset=Number(view.getBigUint64(entry,true)),length=Number(view.getBigUint64(entry+8,true)),expectedWidth=Math.max(1,width>>level),expectedHeight=Math.max(1,height>>level),expectedLength=expectedWidth*expectedHeight*4;if(!Number.isSafeInteger(offset)||!Number.isSafeInteger(length)||offset<0||length<expectedLength||offset+expectedLength>bytes.byteLength)throw new Error(`KTX2 level ${level} payload is truncated.`);levels.push({width:expectedWidth,height:expectedHeight,pixels:Array.from(bytes.subarray(offset,offset+expectedLength)),colorSpace:vkFormat===43?'srgb':'linear',filter:'linear'})}const [base,...mipmaps]=levels;return{id,width:base!.width,height:base!.height,pixels:base!.pixels,colorSpace:base!.colorSpace,mipmaps:mipmaps.length?mipmaps:undefined,filter:'linear',wrapU:'repeat',wrapV:'repeat'} }
export async function decodeGltfImageToSpatialTexture(input:VSRGltfImageDecoderInput):Promise<VSRSpatialTexture>{
  if(input.mimeType==='image/ktx2'||input.image?.mimeType==='image/ktx2')return decodeKtx2ToSpatialTexture(input.bytes,input.id);
  if(typeof Blob!=='function'||typeof createImageBitmap!=='function')throw new Error('glTF image decoding requires Blob and createImageBitmap.');
  const bytes=input.bytes.slice().buffer as ArrayBuffer,blob=new Blob([bytes],{type:input.mimeType??input.image?.mimeType??'application/octet-stream'}),bitmap=await createImageBitmap(blob);
  try{
    const canvas=typeof OffscreenCanvas==='function'?new OffscreenCanvas(bitmap.width,bitmap.height):(()=>{if(typeof document==='undefined')throw new Error('glTF image decoding requires OffscreenCanvas or document.');const element=document.createElement('canvas');element.width=bitmap.width;element.height=bitmap.height;return element})();
    const context=canvas.getContext('2d',{willReadFrequently:true}) as CanvasRenderingContext2D|OffscreenCanvasRenderingContext2D|null;if(!context)throw new Error('glTF image decoder could not create a 2D context.');context.drawImage(bitmap,0,0);const pixels=Array.from(context.getImageData(0,0,bitmap.width,bitmap.height).data);return{id:input.id,width:bitmap.width,height:bitmap.height,pixels,...textureSampling(input.sampler)};
  }finally{bitmap.close()}
}
export function importGltfToSpatialScene(gltf:Json,options:VSRGltfImportOptions={}):VSRGltfImportResult{
  if(gltf.asset?.version!=='2.0')throw new Error(`Unsupported glTF version ${String(gltf.asset?.version)}.`);const buffers=loadBuffers(gltf,options),warnings:string[]=[],textures:VSRSpatialTexture[]=[],textureIds=new Map<number,string>();
  for(let index=0;index<(gltf.textures??[]).length;index++){const texture=gltf.textures[index],source=resolveGltfTextureSource(texture),id=`texture:gltf:${index}`;if(!source){warnings.push(`texture:${index}:missing-image-source`);continue}const loaded=textureFromImage(gltf,source.imageIndex,id,warnings,gltf.samplers?.[texture.sampler]??{},options.imageResolver);if(loaded){textures.push(loaded);textureIds.set(index,id)}}
  const materials:VSRSpatialMaterial[]=(gltf.materials??[]).map((material:Json,index:number)=>{
    const pbr=material.pbrMetallicRoughness??{};
    return{
      id:`material:gltf:${index}`,
      baseColor:colorHex(pbr.baseColorFactor,'#ffffff'),
      metallic:pbr.metallicFactor??1,
      roughness:pbr.roughnessFactor??1,
      emissive:colorHex([...(material.emissiveFactor??[0,0,0]),1],'#000000'),
      emissiveStrength:material.extensions?.KHR_materials_emissive_strength?.emissiveStrength??1,
      clearcoat:material.extensions?.KHR_materials_clearcoat?.clearcoatFactor??0,
      clearcoatRoughness:material.extensions?.KHR_materials_clearcoat?.clearcoatRoughnessFactor??.12,
      ior:material.extensions?.KHR_materials_ior?.ior??1.5,
      doubleSided:material.doubleSided??false,
      opacity:pbr.baseColorFactor?.[3]??1,
      baseColorTextureId:textureIds.get(pbr.baseColorTexture?.index),
      metallicRoughnessTextureId:textureIds.get(pbr.metallicRoughnessTexture?.index),
      normalTextureId:textureIds.get(material.normalTexture?.index),
      normalScale:material.normalTexture?.scale??1,
      occlusionTextureId:textureIds.get(material.occlusionTexture?.index),
      occlusionStrength:material.occlusionTexture?.strength??1,
      emissiveTextureId:textureIds.get(material.emissiveTexture?.index),
      alphaMode:material.alphaMode??'OPAQUE',
      alphaCutoff:material.alphaCutoff??.5
    }
  });if(!materials.length)materials.push({id:'material:gltf:default'});
  const skins:VSRSpatialSkin[]=(gltf.skins??[]).map((skin:Json,index:number)=>{const joints=(skin.joints??[]).map((joint:number)=>`node:gltf:${joint}`),flat=skin.inverseBindMatrices===undefined?[]:accessorValues(gltf,buffers,skin.inverseBindMatrices),inverseBindMatrices=joints.map((_:string,jointIndex:number)=>flat.length?matrixValue(flat.slice(jointIndex*16,jointIndex*16+16))??identityMat4():identityMat4());return{id:`skin:gltf:${index}`,joints,inverseBindMatrices}});
  const meshes:VSRSpatialMesh[]=[],primitiveMaterial=new Map<string,string>();for(let meshIndex=0;meshIndex<(gltf.meshes??[]).length;meshIndex++)for(let primitiveIndex=0;primitiveIndex<(gltf.meshes[meshIndex].primitives??[]).length;primitiveIndex++){const primitive=gltf.meshes[meshIndex].primitives[primitiveIndex];if((primitive.mode??4)!==4)throw new Error('Only glTF TRIANGLES primitives are supported.');const id=`mesh:gltf:${meshIndex}:${primitiveIndex}`,positions=accessorValues(gltf,buffers,primitive.attributes.POSITION),normals=primitive.attributes.NORMAL===undefined?undefined:accessorValues(gltf,buffers,primitive.attributes.NORMAL),uvs=primitive.attributes.TEXCOORD_0===undefined?undefined:accessorValues(gltf,buffers,primitive.attributes.TEXCOORD_0),uvs1=primitive.attributes.TEXCOORD_1===undefined?undefined:accessorValues(gltf,buffers,primitive.attributes.TEXCOORD_1),indices=primitive.indices===undefined?Array.from({length:positions.length/3},(_,i)=>i):accessorValues(gltf,buffers,primitive.indices).map(Math.trunc),jointIndices=primitive.attributes.JOINTS_0===undefined?undefined:accessorValues(gltf,buffers,primitive.attributes.JOINTS_0).map(Math.trunc),jointWeights=primitive.attributes.WEIGHTS_0===undefined?undefined:accessorValues(gltf,buffers,primitive.attributes.WEIGHTS_0),morphTargets=(primitive.targets??[]).map((target:Json,targetIndex:number)=>({id:`morph:gltf:${meshIndex}:${primitiveIndex}:${targetIndex}`,positions:target.POSITION===undefined?new Array<number>(positions.length).fill(0):accessorValues(gltf,buffers,target.POSITION),normals:target.NORMAL===undefined?undefined:accessorValues(gltf,buffers,target.NORMAL),defaultWeight:gltf.meshes[meshIndex].weights?.[targetIndex]??0}));meshes.push({id,positions,normals,uvs,uvs1,indices,jointIndices,jointWeights,morphTargets:morphTargets.length?morphTargets:undefined});primitiveMaterial.set(id,`material:gltf:${primitive.material??0}`)}
  const nodes:VSRSpatialNode[]=[];for(let nodeIndex=0;nodeIndex<(gltf.nodes??[]).length;nodeIndex++){const node=gltf.nodes[nodeIndex],base={id:`node:gltf:${nodeIndex}`,transform:{...(matrixValue(node.matrix) ? {matrix:matrixValue(node.matrix)} : {}),translation:node.translation as Vec3|undefined,rotationQuaternion:quaternionValue(node.rotation),scale:node.scale as Vec3|undefined}},skinId=node.skin===undefined?undefined:`skin:gltf:${node.skin}`,morphWeights=node.weights as number[]|undefined;const primitives=node.mesh===undefined?[]:(gltf.meshes[node.mesh]?.primitives??[]);if(primitives.length<=1){const meshId=node.mesh===undefined?undefined:`mesh:gltf:${node.mesh}:0`;nodes.push({...base,meshId,materialId:meshId?primitiveMaterial.get(meshId):undefined,skinId,morphWeights})}else{nodes.push({...base,skinId,morphWeights});for(let p=0;p<primitives.length;p++){const meshId=`mesh:gltf:${node.mesh}:${p}`;nodes.push({id:`node:gltf:${nodeIndex}:primitive:${p}`,parentId:base.id,meshId,materialId:primitiveMaterial.get(meshId),skinId,morphWeights})}}}
  for(let parent=0;parent<(gltf.nodes??[]).length;parent++)for(const child of gltf.nodes[parent].children??[]){const target=nodes.find(node=>node.id===`node:gltf:${child}`);if(target)target.parentId=`node:gltf:${parent}`}
  const cameras:VSRSpatialCamera[]=(gltf.cameras??[]).map((camera:Json,index:number)=>{const nodeIndex=(gltf.nodes??[]).findIndex((node:Json)=>node.camera===index),node=gltf.nodes?.[nodeIndex]??{};return{id:`camera:gltf:${index}`,projection:camera.type==='orthographic'?'orthographic':'perspective',fovYDeg:camera.perspective?.yfov===undefined?undefined:camera.perspective.yfov*180/Math.PI,orthoHeight:camera.orthographic?.ymag===undefined?undefined:camera.orthographic.ymag*2,near:camera.perspective?.znear??camera.orthographic?.znear??.1,far:camera.perspective?.zfar??camera.orthographic?.zfar??1000,transform:{translation:node.translation as Vec3|undefined,rotationQuaternion:quaternionValue(node.rotation),scale:node.scale as Vec3|undefined}}});if(!cameras.length&&options.defaultCamera!==false)cameras.push({id:'camera:gltf:default',projection:'perspective',fovYDeg:55,near:.1,far:1000,transform:{translation:[0,1.5,5]}});
  const punctual=gltf.extensions?.KHR_lights_punctual?.lights??[],lights:VSRSpatialLight[]=[{id:'light:gltf:ambient',kind:'ambient',color:'#ffffff',intensity:.12}];for(let nodeIndex=0;nodeIndex<(gltf.nodes??[]).length;nodeIndex++){const node=gltf.nodes[nodeIndex],lightIndex=node.extensions?.KHR_lights_punctual?.light;if(lightIndex===undefined)continue;const light=punctual[lightIndex]??{},kind=light.type==='directional'?'directional':'point';lights.push({id:`light:gltf:${lightIndex}`,kind,color:colorHex([...(light.color??[1,1,1]),1]),intensity:light.intensity??1,range:light.range,position:node.translation as Vec3|undefined,direction:kind==='directional'?[0,-1,0]:undefined,castShadow:true})}
  const animations:VSRSpatialAnimationClip[]=(gltf.animations??[]).map((animation:Json,animationIndex:number)=>{const channels:VSRSpatialAnimationChannel[]=[];let duration=0;for(const channel of animation.channels??[]){const sampler=animation.samplers[channel.sampler],times=accessorValues(gltf,buffers,sampler.input),flat=accessorValues(gltf,buffers,sampler.output),path=(channel.target.path==='rotation'?'rotationQuaternion':channel.target.path) as VSRSpatialAnimationPath;if(!['translation','rotationQuaternion','scale'].includes(path)){warnings.push(`animation:${animationIndex}:unsupported-path:${path}`);continue}const dimension=path==='rotationQuaternion'?4:3,interpolation=sampler.interpolation==='STEP'?'STEP':sampler.interpolation==='CUBICSPLINE'?'CUBICSPLINE':'LINEAR',values:(Vec3|Vec4)[]=[],inTangents:(Vec3|Vec4)[]=[],outTangents:(Vec3|Vec4)[]=[],valueOf=(raw:number[]):Vec3|Vec4=>dimension===4?raw as Vec4:raw as Vec3;if(interpolation==='CUBICSPLINE'){const stride=dimension*3;if(flat.length!==times.length*stride){warnings.push(`animation:${animationIndex}:invalid-cubic-output:${channel.target.path}`);continue}for(let index=0;index<times.length;index++){const base=index*stride;inTangents.push(valueOf(flat.slice(base,base+dimension)));values.push(valueOf(flat.slice(base+dimension,base+dimension*2)));outTangents.push(valueOf(flat.slice(base+dimension*2,base+stride)))}}else{if(flat.length!==times.length*dimension){warnings.push(`animation:${animationIndex}:invalid-output:${channel.target.path}`);continue}for(let index=0;index<times.length;index++)values.push(valueOf(flat.slice(index*dimension,index*dimension+dimension)))}duration=Math.max(duration,...times);channels.push({nodeId:`node:gltf:${channel.target.node}`,path,times,values,interpolation,...(interpolation==='CUBICSPLINE'?{inTangents,outTangents}:{})})}return{id:`animation:gltf:${animationIndex}`,duration,channels}});
  const sourceRoot=options.sourceRoot??cryptographicHash(gltf),sceneId=options.sceneId??`gltf:${sourceRoot.slice(0,16)}`,scene:VSRSpatialScene3D={format:VSR_SPATIAL_SCENE_FORMAT,sceneId,title:options.title??gltf.scene?.name??'glTF 2.0 Asset',activeCameraId:cameras[0]!.id,meshes,materials,textures,animations,skins,nodes,cameras,lights,reality:{worldId:`world:${sceneId}`,realityRoot:cryptographicHash({asset:gltf.asset,scene:gltf.scene,nodes:gltf.nodes,sourceRoot})}};
  const materialTextureBindingCount=materials.reduce((sum,material)=>sum+[material.baseColorTextureId,material.metallicRoughnessTextureId,material.normalTextureId,material.occlusionTextureId,material.emissiveTextureId].filter(Boolean).length,0),morphTargetCount=meshes.reduce((sum,mesh)=>sum+(mesh.morphTargets?.length??0),0),base={format:VSR_GLTF_IMPORT_FORMAT,assetVersion:VSR_GLTF_ASSET_VERSION,sceneId,meshCount:meshes.length,nodeCount:nodes.length,materialCount:materials.length,textureCount:textures.length,materialTextureBindingCount,animationCount:animations.length,skinCount:skins.length,morphTargetCount,sourceRoot,sceneRoot:cryptographicHash(scene),warnings};return{scene,receipt:{...base,receiptRoot:cryptographicHash(base)}};
}
export function importGlbToSpatialScene(input:ArrayBuffer|Uint8Array,options:VSRGltfImportOptions={}):VSRGltfImportResult{const parsed=parseGlb(input),buffers={...(options.buffers??{})};if(parsed.binaryChunk&&!buffers['buffer:0'])buffers['buffer:0']=parsed.binaryChunk;const binaryRoot=parsed.binaryChunk?cryptographicHash([...parsed.binaryChunk]):cryptographicHash([]),sourceRoot=options.sourceRoot??cryptographicHash({gltf:parsed.gltf,binaryRoot});return importGltfToSpatialScene(parsed.gltf,{...options,buffers,sourceRoot})}
export async function importGltfToSpatialSceneAsync(gltf:Json,options:VSRGltfImportOptions={}):Promise<VSRGltfImportResult>{const buffers=loadBuffers(gltf,options),decoded=new Map<number,VSRSpatialTexture>(),imageRoots:[number,string][]=[];if(options.imageDecoder)for(const texture of gltf.textures??[]){const source=resolveGltfTextureSource(texture);if(!source||!Number.isInteger(source.imageIndex)||decoded.has(source.imageIndex))continue;const imageIndex=source.imageIndex,image=gltf.images?.[imageIndex],bytes=imageBytes(gltf,imageIndex,buffers,options);if(!image||!bytes)continue;const id=`texture:gltf:${imageIndex}`,sampler=gltf.samplers?.[texture.sampler]??{},resolved=await options.imageDecoder({imageIndex,image,id,sampler,bytes,mimeType:image.mimeType});if(resolved){decoded.set(imageIndex,resolved);imageRoots.push([imageIndex,cryptographicHash([...bytes])])}}const sourceRoot=options.sourceRoot??(imageRoots.length?cryptographicHash({gltf,imageRoots}):cryptographicHash(gltf));return importGltfToSpatialScene(gltf,{...options,sourceRoot,imageResolver:input=>decoded.get(input.imageIndex)??options.imageResolver?.(input)})}
export async function importGlbToSpatialSceneAsync(input:ArrayBuffer|Uint8Array,options:VSRGltfImportOptions={}):Promise<VSRGltfImportResult>{const parsed=parseGlb(input),buffers={...(options.buffers??{})};if(parsed.binaryChunk&&!buffers['buffer:0'])buffers['buffer:0']=parsed.binaryChunk;const binaryRoot=parsed.binaryChunk?cryptographicHash([...parsed.binaryChunk]):cryptographicHash([]),sourceRoot=options.sourceRoot??cryptographicHash({gltf:parsed.gltf,binaryRoot});return importGltfToSpatialSceneAsync(parsed.gltf,{...options,buffers,sourceRoot})}
export function verifyGltfImportReceipt(receipt:VSRGltfImportReceipt):boolean{const {receiptRoot,...base}=receipt;return cryptographicHash(base)===receiptRoot}
