#!/usr/bin/env node
import { createServer } from 'node:http';
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, normalize, resolve } from 'node:path';
import { applyTransaction, type VSRTransaction } from '../../agent-protocol/src/index.js';
import { evaluateAt, prepareDocument, VSR_RUNTIME_VERSION } from '../../core/src/index.js';
import { VSRNullBackend } from '../../backend-null/src/index.js';
import { encodeVideo, renderFrame, renderRange } from '../../renderer/src/index.js';
import { documentHash, validateDocument, type VSRDocument } from '../../spec/src/index.js';
import { projectDisplayForObserver, type VSRObserverProfile } from '../../observer-projection/src/index.js';
import { RealityOneVSRSession, realityOneResultToLifecycleEvents, realityOneResultToVSR, type RealityOneLifecycleEvent } from '../../adapter-reality-one/src/index.js';

interface ParsedArgs { command?:string;positionals:string[];flags:Record<string,string|boolean> }
function parseArgs(argv:string[]):ParsedArgs{const [command,...rest]=argv;const positionals:string[]=[];const flags:Record<string,string|boolean>={};for(let i=0;i<rest.length;i++){const value=rest[i]!;if(value.startsWith('--')){const key=value.slice(2);const next=rest[i+1];if(next!==undefined&&!next.startsWith('--')){flags[key]=next;i++}else flags[key]=true}else positionals.push(value)}return{command,positionals,flags}}
function loadDocument(path:string):VSRDocument{return JSON.parse(readFileSync(resolve(path),'utf8')) as VSRDocument}
function print(value:unknown,json=false):void{process.stdout.write(json?`${JSON.stringify(value,null,2)}\n`:`${typeof value==='string'?value:JSON.stringify(value,null,2)}\n`)}
function fail(message:string,code=1,json=false):never{process.stderr.write(json?`${JSON.stringify({ok:false,error:message})}\n`:`错误：${message}\n`);process.exitCode=code;throw new Error('__CLI_EXIT__')}
function numberFlag(flags:ParsedArgs['flags'],key:string,fallback?:number):number{const raw=flags[key];if(raw===undefined){if(fallback!==undefined)return fallback;throw new Error(`Missing --${key}`)}const n=Number(raw);if(!Number.isFinite(n))throw new Error(`Invalid --${key}: ${String(raw)}`);return n}
function usage():string{return`VSR CLI ${VSR_RUNTIME_VERSION}

命令：
  vsr validate <document> [--json]
  vsr inspect <document> [--json]
  vsr deps <document> [--json]
  vsr schema [--kind visual-ir|reality-one-lifecycle|observer-profile|observer-policy] [--out schema.json]
  vsr eval <document> --time <seconds> [--width N --height N --json]
  vsr render-frame <document> --time N --out frame.png
  vsr render-range <document> --start N --end N --fps N --out frames/
  vsr encode <frames-manifest.json> --format mp4|webm --out output.mp4
  vsr patch <document> <transaction.json> --out patched.vsr.json
  vsr project-reality-one <application-result.json> --profile desktop|mobile --out result.vsr.json
  vsr project-observer <document> <observer-profile.json> --time N --out display.json [--manifest manifest.json]
  vsr replay-reality-one <events-or-result.json> --profile desktop|mobile --out snapshot.vsr.json [--manifest replay.json --png frame.png]
  vsr verify <document> [--json]
  vsr serve [document] [--port 4173]
  vsr benchmark [--nodes 1000]
`}

function verify(document:VSRDocument):unknown{const prepared=prepareDocument(document);const times=[0,document.metadata.duration*.25,document.metadata.duration*.5,document.metadata.duration];const checks=[];for(const time of times){const a=evaluateAt({document:prepared,time});const b=evaluateAt({document:prepared,time});checks.push({name:`repeat@${time}`,ok:a.semanticHash===b.semanticHash,hash:a.semanticHash});const c=evaluateAt({document:prepared,time:Math.min(document.metadata.duration,time+0.1)});const d=evaluateAt({document:prepared,time});checks.push({name:`A-B-A@${time}`,ok:a.semanticHash===d.semanticHash,intermediate:c.semanticHash})}const nullBackend=new VSRNullBackend();const state=evaluateAt({document:prepared,time:times[2]!}).displayState;const n1=nullBackend.render(state),n2=nullBackend.render(state);checks.push({name:'null-backend-repeat',ok:n1.commandHash===n2.commandHash,hash:n1.commandHash});return{ok:checks.every(c=>c.ok),documentHash:prepared.documentHash,runtimeVersion:VSR_RUNTIME_VERSION,checks}}

function mime(path:string):string{return({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.svg':'image/svg+xml'} as Record<string,string>)[extname(path)]??'application/octet-stream'}
function serve(port:number):void{const root=resolve('.');const server=createServer((req,res)=>{try{const raw=(req.url??'/').split('?')[0]??'/';const requested=raw==='/'?'/dist/apps/studio/index.html':raw;const safe=normalize(requested).replace(/^([.][.][/\\])+/, '').replace(/^[/\\]+/,'');const path=resolve(join(root,safe));if(!path.startsWith(root)||!existsSync(path)||statSync(path).isDirectory()){res.statusCode=404;res.end('Not found');return}res.setHeader('Content-Type',mime(path));res.setHeader('Cache-Control','no-store');res.end(readFileSync(path))}catch(error){res.statusCode=500;res.end(error instanceof Error?error.message:String(error))}});server.listen(port,()=>print(`VSR Studio: http://127.0.0.1:${port}`))}

async function main():Promise<void>{const args=parseArgs(process.argv.slice(2)),json=Boolean(args.flags.json);if(!args.command||args.command==='help'||args.flags.help){print(usage());return}try{
  if(args.command==='validate'){const doc=loadDocument(args.positionals[0]??fail('缺少文档路径',2,json));const report=validateDocument(doc);print({ok:report.ok,documentHash:report.ok?documentHash(doc):undefined,diagnostics:report.diagnostics},json);if(!report.ok)process.exitCode=3;return}
  if(args.command==='inspect'){const doc=loadDocument(args.positionals[0]??fail('缺少文档路径',2,json));const prepared=prepareDocument(doc);print({ok:true,id:doc.metadata.id,title:doc.metadata.title,duration:doc.metadata.duration,fps:doc.metadata.defaultFps,nodes:doc.nodes.length,tracks:doc.nodes.reduce((n,x)=>n+(x.tracks?.length??0),0),events:doc.events?.length??0,outputs:doc.outputs??[],documentHash:prepared.documentHash,dependencies:{variablePaths:prepared.dependencyGraph.variableToNodes.size,contextPaths:prepared.dependencyGraph.contextToNodes.size,inputPaths:prepared.dependencyGraph.inputToNodes.size,timeDependentNodes:prepared.dependencyGraph.timeDependentNodes.size,layoutDependentNodes:prepared.dependencyGraph.layoutDependentNodes.size},diagnostics:prepared.diagnostics},json);return}
  if(args.command==='deps'){const doc=loadDocument(args.positionals[0]??fail('缺少文档路径',2,json));const prepared=prepareDocument(doc);const map=(value:Map<string,Set<string>>)=>Object.fromEntries([...value].map(([key,nodes])=>[key,[...nodes].sort()]));print({ok:true,documentHash:prepared.documentHash,variables:map(prepared.dependencyGraph.variableToNodes),context:map(prepared.dependencyGraph.contextToNodes),input:map(prepared.dependencyGraph.inputToNodes),timeDependent:[...prepared.dependencyGraph.timeDependentNodes].sort(),layoutDependent:[...prepared.dependencyGraph.layoutDependentNodes].sort()},json);return}
  if(args.command==='schema'){const kind=String(args.flags.kind??'visual-ir');const schemaFile=kind==='reality-one-lifecycle'?'reality-one-lifecycle-event.v0.1.schema.json':kind==='observer-profile'?'vsr-observer-profile.v0.1.schema.json':kind==='observer-policy'?'vsr-observer-policy.v0.1.schema.json':kind==='visual-ir'?'vsr-0.1.schema.json':fail(`未知 schema kind：${kind}`,2,json);const schemaPath=resolve('schemas',schemaFile);if(!existsSync(schemaPath))fail(`找不到 schemas/${schemaFile}`,4,json);const output=args.flags.out?resolve(String(args.flags.out)):undefined;if(output){mkdirSync(resolve(output,'..'),{recursive:true});writeFileSync(output,readFileSync(schemaPath));print({ok:true,output,schema:'draft-2020-12',kind},json);}else print(JSON.parse(readFileSync(schemaPath,'utf8')),json);return}
  if(args.command==='eval'){const doc=loadDocument(args.positionals[0]??fail('缺少文档路径',2,json));const result=evaluateAt({document:doc,time:numberFlag(args.flags,'time'),context:{width:args.flags.width?Number(args.flags.width):undefined,height:args.flags.height?Number(args.flags.height):undefined}});print({ok:true,state:result.state,displayState:result.displayState,stats:result.evaluationStats},json);return}
  if(args.command==='render-frame'){const documentPath=args.positionals[0]??fail('缺少文档路径',2,json);const doc=loadDocument(documentPath);const out=String(args.flags.out??'outputs/frame.png');const entry=renderFrame(doc,numberFlag(args.flags,'time'),out,{width:args.flags.width?Number(args.flags.width):undefined,height:args.flags.height?Number(args.flags.height):undefined},{assetBaseDir:dirname(resolve(documentPath)),strictResources:Boolean(args.flags['strict-resources'])});print({ok:true,output:entry},json);return}
  if(args.command==='render-range'){const documentPath=args.positionals[0]??fail('缺少文档路径',2,json);const doc=loadDocument(documentPath);const outDir=String(args.flags.out??'outputs/frames');const manifest=renderRange(doc,{start:numberFlag(args.flags,'start',0),end:numberFlag(args.flags,'end',doc.metadata.duration),fps:numberFlag(args.flags,'fps',doc.metadata.defaultFps),outDir,context:{width:args.flags.width?Number(args.flags.width):undefined,height:args.flags.height?Number(args.flags.height):undefined},assetBaseDir:dirname(resolve(documentPath)),strictResources:Boolean(args.flags['strict-resources'])});print({ok:true,manifestPath:resolve(outDir,'frames-manifest.json'),frameCount:manifest.frames.length,first:manifest.frames[0],last:manifest.frames.at(-1)},json);return}
  if(args.command==='encode'){const manifest=args.positionals[0]??fail('缺少 frames-manifest.json',2,json);const output=String(args.flags.out??`outputs/output.${String(args.flags.format??'mp4')}`);const path=encodeVideo(manifest,output,String(args.flags.format??'mp4')==='webm'?'webm':'mp4');print({ok:true,output:path},json);return}
  if(args.command==='patch'){const doc=loadDocument(args.positionals[0]??fail('缺少文档路径',2,json));const tx=JSON.parse(readFileSync(resolve(args.positionals[1]??fail('缺少事务路径',2,json)),'utf8')) as VSRTransaction;const result=applyTransaction(doc,tx);if(!result.ok)fail(result.error??'事务失败',7,json);const output=resolve(String(args.flags.out??'outputs/patched.vsr.json'));mkdirSync(resolve(output,'..'),{recursive:true});writeFileSync(output,JSON.stringify(result.document,null,2));print({ok:true,output,documentHash:result.documentHashAfter,diff:result.diff},json);return}
  if(args.command==='project-observer'){const documentPath=resolve(args.positionals[0]??fail('缺少 VSR 文档路径',2,json));const observerPath=resolve(args.positionals[1]??fail('缺少观察者档案路径',2,json));const doc=loadDocument(documentPath);const observer=JSON.parse(readFileSync(observerPath,'utf8')) as VSRObserverProfile;const timeValue=numberFlag(args.flags,'time',0);const source=evaluateAt({document:doc,time:timeValue,context:{width:args.flags.width?Number(args.flags.width):undefined,height:args.flags.height?Number(args.flags.height):undefined}}).displayState;const invariantRaw=args.flags.invariant?JSON.parse(readFileSync(resolve(String(args.flags.invariant)),'utf8')) as Record<string,import('../../spec/src/index.js').VSRValue>:undefined;const projection=projectDisplayForObserver(doc,source,observer,{invariant:invariantRaw});const output=resolve(String(args.flags.out??`outputs/${doc.metadata.id}-${observer.observerId}.display.json`));const manifestPath=resolve(String(args.flags.manifest??`outputs/${doc.metadata.id}-${observer.observerId}.observer-manifest.json`));mkdirSync(resolve(output,'..'),{recursive:true});mkdirSync(resolve(manifestPath,'..'),{recursive:true});writeFileSync(output,JSON.stringify(projection.displayState,null,2));writeFileSync(manifestPath,JSON.stringify(projection.manifest,null,2));print({ok:true,observerId:projection.observer.observerId,sourceDisplayHash:projection.manifest.sourceDisplayHash,projectedDisplayHash:projection.manifest.projectedDisplayHash,shown:projection.manifest.shownNodeIds.length,redacted:projection.manifest.redactedNodeIds.length,hidden:projection.manifest.hiddenNodeIds.length,output,manifest:manifestPath},json);return}
  if(args.command==='project-reality-one'){const inputPath=resolve(args.positionals[0]??fail('缺少 Reality One application-result 路径',2,json));const input=JSON.parse(readFileSync(inputPath,'utf8')) as unknown;const profile=String(args.flags.profile??'desktop');if(profile!=='desktop'&&profile!=='mobile')fail('--profile 仅支持 desktop 或 mobile',2,json);const document=realityOneResultToVSR(input,{profile:profile as 'desktop'|'mobile'});const output=resolve(String(args.flags.out??`outputs/reality-one-${profile}.vsr.json`));mkdirSync(resolve(output,'..'),{recursive:true});writeFileSync(output,JSON.stringify(document,null,2));print({ok:true,output,profile,documentHash:documentHash(document),nodes:document.nodes.length},json);return}
  if(args.command==='replay-reality-one'){const inputPath=resolve(args.positionals[0]??fail('缺少 Reality One 事件流或 application-result 路径',2,json));const input=JSON.parse(readFileSync(inputPath,'utf8')) as unknown;const profile=String(args.flags.profile??'desktop');if(profile!=='desktop'&&profile!=='mobile')fail('--profile 仅支持 desktop 或 mobile',2,json);const root=input&&typeof input==='object'&&!Array.isArray(input)?input as Record<string,unknown>:{};const eventInput=Array.isArray(input)?input:Array.isArray(root.events)?root.events:undefined;const events=(eventInput??realityOneResultToLifecycleEvents(input)) as RealityOneLifecycleEvent[];const session=new RealityOneVSRSession({profile:profile as 'desktop'|'mobile'});const manifest=session.replay(events);const document=session.snapshotDocument();const output=resolve(String(args.flags.out??`outputs/reality-one-${profile}-snapshot.vsr.json`));const manifestPath=resolve(String(args.flags.manifest??`outputs/reality-one-${profile}-replay.json`));mkdirSync(resolve(output,'..'),{recursive:true});mkdirSync(resolve(manifestPath,'..'),{recursive:true});writeFileSync(output,JSON.stringify(document,null,2));writeFileSync(manifestPath,JSON.stringify(manifest,null,2));let png:string|undefined;if(args.flags.png){png=resolve(String(args.flags.png));renderFrame(document,0,png,{width:document.canvas.width,height:document.canvas.height});}session.dispose();print({ok:true,profile,eventCount:events.length,eventChainRoot:manifest.eventChainRoot,finalStateHash:manifest.finalStateHash,finalDisplayHash:manifest.finalDisplayHash,output,manifest:manifestPath,png},json);return}
  if(args.command==='verify'){const doc=loadDocument(args.positionals[0]??fail('缺少文档路径',2,json));const report=verify(doc);print(report,json);if(!(report as {ok:boolean}).ok)process.exitCode=8;return}
  if(args.command==='serve'){serve(numberFlag(args.flags,'port',4173));return}
  if(args.command==='benchmark'){const count=numberFlag(args.flags,'nodes',1000);const doc:VSRDocument={specVersion:'0.1',metadata:{id:'benchmark',title:'Benchmark',duration:10,defaultFps:60,seed:7},canvas:{width:1920,height:1080,background:{type:'solid',color:'#000'}},nodes:Array.from({length:count},(_,i)=>({id:`n${i}`,type:'rect' as const,layout:{x:(i%100)*19,y:Math.floor(i/100)*19,width:16,height:16},appearance:{fill:{type:'solid' as const,color:'#44aaff'},opacity:1},tracks:[{id:`t${i}`,property:'transform.rotation',mode:'expression' as const,expression:`time * ${(i%7)+1}`}]}))};const prepared=prepareDocument(doc);const samples=[];for(let i=0;i<20;i++){const start=performance.now();evaluateAt({document:prepared,time:i/3});samples.push(performance.now()-start)}samples.sort((a,b)=>a-b);print({ok:true,nodes:count,runs:samples.length,medianMs:samples[Math.floor(samples.length*.5)],p95Ms:samples[Math.floor(samples.length*.95)],memory:process.memoryUsage(),node:process.version,platform:process.platform},json);return}
  fail(`未知命令：${args.command}`,2,json);
}catch(error){if(error instanceof Error&&error.message==='__CLI_EXIT__')return;fail(error instanceof Error?error.message:String(error),1,json)}}
void main();
