// 本机慢速训练炉 · Local Forge Plan
import type { ForgeExperiment, ForgeExperimentType } from "./personalModelForgeTypes";

const TYPE_LABEL: Record<ForgeExperimentType, string> = {
  TOKENIZER_TRAINING: "Tokenizer 训练",
  TOY_PRETRAIN: "玩具预训练",
  SMALL_SFT: "小规模 SFT",
  LORA_TEST: "LoRA / QLoRA 实验",
  ROUTER_MODEL: "Router 小模型",
  MSL_MODEL: "MSL 小模型",
  FORMAT_MODEL: "格式 / 结构小模型",
  DATA_ABLATION: "数据消融",
  SERVER_PRETRAIN: "服务器预训练",
  SERVER_SFT: "服务器 SFT",
};

function exp(p: Omit<ForgeExperiment, "experimentTypeLabel">): ForgeExperiment {
  return { ...p, experimentTypeLabel: TYPE_LABEL[p.experimentType] };
}

export function buildLocalForgePlan(): ForgeExperiment[] {
  return [
    exp({
      id: "LF-TOK-01",
      name: "AetherSeed Tokenizer v0",
      targetModel: "AetherSeed Tokenizer",
      experimentType: "TOKENIZER_TRAINING",
      location: "LOCAL_PC",
      estimatedDuration: "数小时（适合夜间运行）",
      costMode: "TIME_RICH",
      requiredTools: ["local-pc", "codex", "cursor"],
      datasetRefs: ["Aetherworld 对话压缩语料", "数列语言 / MSL 样例", "Lovable Prompt 模板"],
      outputArtifacts: ["tokenizer.json", "vocab.txt", "训练日志"],
      status: "DRAFT",
      notes: "先验证 Tokenizer 覆盖度，再决定模型规模。",
      goal: "建立 AetherSeed 全族通用 BPE / SentencePiece 词表。",
      evalItems: ["压缩率", "未登录词比例", "数列语言覆盖率"],
      failureRisks: ["数列语言被切碎", "中英混排切分不稳"],
      nextStep: "通过后用于 AetherSeed-10M 训练脚本。",
    }),
    exp({
      id: "LF-10M-01",
      name: "AetherSeed-10M 训练脚本验证",
      targetModel: "AetherSeed-10M",
      experimentType: "TOY_PRETRAIN",
      location: "LOCAL_PC",
      estimatedDuration: "数小时～1 天（夜间长时运行）",
      costMode: "TIME_RICH",
      requiredTools: ["local-pc", "codex", "cursor"],
      datasetRefs: ["压缩对话样本", "数列 / MSL 微样本"],
      outputArtifacts: ["10M checkpoint", "loss 曲线", "训练脚本"],
      status: "DRAFT",
      notes: "目标不是好模型，是验证整条训练管线可跑通。",
      goal: "跑通 data → tokenizer → model → loss → checkpoint 全链路。",
      evalItems: ["loss 收敛", "checkpoint 可加载", "Ollama 导入可推理"],
      failureRisks: ["OOM", "梯度爆炸", "数据格式错位"],
      nextStep: "通过后扩展到 AetherSeed-50M。",
    }),
    exp({
      id: "LF-50M-01",
      name: "AetherSeed-50M Tokenizer / MSL / Lovable Prompt 验证",
      targetModel: "AetherSeed-50M",
      experimentType: "TOY_PRETRAIN",
      location: "LOCAL_PC",
      estimatedDuration: "数天（适合连续夜间运行）",
      costMode: "TIME_RICH",
      requiredTools: ["local-pc", "codex", "cursor", "ollama"],
      datasetRefs: [
        "Aetherworld 对话压缩",
        "数列语言语料",
        "MSL 指令样本",
        "Lovable Prompt 样例（脱敏）",
      ],
      outputArtifacts: ["50M checkpoint", "Tokenizer 报告", "格式对齐评测"],
      status: "DRAFT",
      goal: "验证 Tokenizer + MSL + 数列语言 + Lovable Prompt 四类输入是否被模型学到。",
      evalItems: ["格式还原率", "MSL opcode 命中", "数列语言保留率"],
      failureRisks: ["小模型欠拟合", "训练步数不足"],
      nextStep: "通过后扩展到 AetherSeed-100M。",
    }),
    exp({
      id: "LF-100M-01",
      name: "AetherSeed-100M 小型结构输出验证",
      targetModel: "AetherSeed-100M",
      experimentType: "TOY_PRETRAIN",
      location: "LOCAL_PC",
      estimatedDuration: "1～2 周（长时低占用）",
      costMode: "TIME_RICH",
      requiredTools: ["local-pc", "codex", "cursor", "ollama"],
      datasetRefs: ["50M 语料 + Aetherworld 任务样本"],
      outputArtifacts: ["100M checkpoint", "结构输出评测"],
      status: "DRAFT",
      goal: "验证小型 AetherSeed 是否能稳定输出结构化 JSON / MSL / 数列。",
      evalItems: ["结构化命中率", "JSON 合法率", "MSL 合法率"],
      failureRisks: ["结构幻觉", "训练数据多样性不足"],
      nextStep: "通过后规划 Router / MSL 子模型。",
    }),
    exp({
      id: "LF-ROUTER-01",
      name: "Router 小模型 v0",
      targetModel: "AetherSeed-Router-Tiny",
      experimentType: "ROUTER_MODEL",
      location: "LOCAL_PC",
      estimatedDuration: "数小时",
      costMode: "TIME_RICH",
      requiredTools: ["local-pc", "codex"],
      datasetRefs: ["Chat 意图标签", "Aetherworld 计算法链命中样本"],
      outputArtifacts: ["router checkpoint", "意图分类报告"],
      status: "DRAFT",
      goal: "为 Aetherworld 子任务提供轻量分流。",
      evalItems: ["Top1 准确率", "推理延迟"],
      failureRisks: ["类别不平衡"],
      nextStep: "接入 Sequence AI 调度。",
    }),
    exp({
      id: "LF-MSL-01",
      name: "MSL 小模型 v0",
      targetModel: "AetherSeed-MSL-Tiny",
      experimentType: "MSL_MODEL",
      location: "LOCAL_PC",
      estimatedDuration: "数小时～1 天",
      costMode: "TIME_RICH",
      requiredTools: ["local-pc", "codex"],
      datasetRefs: ["MSL 指令样本", "状态转换样本"],
      outputArtifacts: ["msl checkpoint", "opcode 评测"],
      status: "DRAFT",
      goal: "MSL 状态语言专用小模型，服务子任务。",
      evalItems: ["opcode 合法率", "状态转换正确率"],
      failureRisks: ["样本覆盖不足"],
      nextStep: "接入 MSL Console。",
    }),
    exp({
      id: "LF-LORA-01",
      name: "LoRA / QLoRA 数据集质量验证",
      targetModel: "Llama / Qwen / Mistral（已开源基座）",
      experimentType: "LORA_TEST",
      location: "LOCAL_PC",
      estimatedDuration: "数小时（按基座大小变化）",
      costMode: "TIME_RICH",
      requiredTools: ["local-pc", "codex"],
      datasetRefs: ["Aetherworld SFT 数据样本"],
      outputArtifacts: ["LoRA 权重", "前后对照评测"],
      status: "DRAFT",
      goal: "在不进行全量训练前，先验证数据质量。",
      evalItems: ["指令遵循率", "格式合法率", "风格一致性"],
      failureRisks: ["数据噪声", "Prompt 模板不统一"],
      nextStep: "数据通过后再上服务器做全量 SFT。",
    }),
  ];
}
