// AetherSeed 血统线：10M → 50M → 100M → 300M → 700M → 1.5B → 3B → 7B
import type { ModelBloodlineStage } from "./personalModelForgeTypes";

export function buildBloodline(): ModelBloodlineStage[] {
  return [
    {
      id: "BL-10M",
      modelName: "AetherSeed-10M",
      parameterScale: "10M",
      forgeLocation: "LOCAL_PC",
      purpose: "验证训练管线全链路。",
      prerequisites: ["AetherSeed Tokenizer v0"],
      nextStageId: "BL-50M",
      evalRequirements: ["loss 收敛", "checkpoint 可加载"],
    },
    {
      id: "BL-50M",
      modelName: "AetherSeed-50M",
      parameterScale: "50M",
      forgeLocation: "LOCAL_PC",
      purpose: "验证 Tokenizer / MSL / 数列语言 / Lovable Prompt 格式覆盖。",
      prerequisites: ["AetherSeed-10M"],
      nextStageId: "BL-100M",
      evalRequirements: ["格式还原率", "MSL opcode 命中", "数列保留率"],
    },
    {
      id: "BL-100M",
      modelName: "AetherSeed-100M",
      parameterScale: "100M",
      forgeLocation: "LOCAL_PC",
      purpose: "验证小型结构输出能力。",
      prerequisites: ["AetherSeed-50M"],
      nextStageId: "BL-300M",
      evalRequirements: ["JSON 合法率", "结构化命中率"],
    },
    {
      id: "BL-300M",
      modelName: "AetherSeed-300M",
      parameterScale: "300M",
      forgeLocation: "GPU_SERVER",
      purpose: "首个具备弱通用能力的基座。",
      prerequisites: ["AetherSeed-100M", "服务器训练环境"],
      nextStageId: "BL-700M",
      evalRequirements: ["perplexity", "Aetherworld 任务命中"],
    },
    {
      id: "BL-700M",
      modelName: "AetherSeed-700M",
      parameterScale: "700M",
      forgeLocation: "GPU_SERVER",
      purpose: "中等规模通用能力跃迁。",
      prerequisites: ["AetherSeed-300M"],
      nextStageId: "BL-1B5",
      evalRequirements: ["指令遵循", "结构化输出"],
    },
    {
      id: "BL-1B5",
      modelName: "AetherSeed-1.5B",
      parameterScale: "1.5B",
      forgeLocation: "GPU_SERVER",
      purpose: "AetherSeed 主力工作模型。",
      prerequisites: ["AetherSeed-700M"],
      nextStageId: "BL-3B",
      evalRequirements: ["综合 eval", "Aetherworld 通过率"],
    },
    {
      id: "BL-3B",
      modelName: "AetherSeed-3B",
      parameterScale: "3B",
      forgeLocation: "GPU_SERVER",
      purpose: "中等成本下的强通用能力。",
      prerequisites: ["AetherSeed-1.5B"],
      nextStageId: "BL-7B",
      evalRequirements: ["综合 eval", "推理速度"],
    },
    {
      id: "BL-7B",
      modelName: "AetherSeed-7B",
      parameterScale: "7B",
      forgeLocation: "GPU_SERVER",
      purpose: "AetherSeed 系列旗舰。",
      prerequisites: ["AetherSeed-3B"],
      evalRequirements: ["综合 eval", "Ollama 部署可行性"],
    },
  ];
}
