import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {generateAnimeCharacterFamily,generateAnimeBackgroundFamily,validateAnimeCharacterFamily,validateAnimeBackgroundFamily} from '../src/index.mjs';

test('Anime RAGF character and background families pass provider and continuity gates',()=>{const character=generateAnimeCharacterFamily({assetId:'character:test',name:'Test Character'}),background=generateAnimeBackgroundFamily({assetId:'background:test',name:'Test Background'});assert.equal(validateAnimeCharacterFamily(character.family).valid,true);assert.equal(validateAnimeBackgroundFamily(background.family).valid,true);assert.equal(Object.keys(character.files).length,10);assert.equal(Object.keys(background.files).length,1);assert.equal(character.files['front-view.png'].mime,'image/png');assert.deepEqual([...Buffer.from(character.files['front-view.png'].content,'base64').subarray(0,8)],[137,80,78,71,13,10,26,10]);assert.ok(character.family.media_manifest.primary_raster.byte_length>128);assert.equal(character.family.quality.rendered_media.png,true);assert.equal(character.family.optional_3d_proxy.status,'not-implemented');assert.equal(character.family.optional_3d_proxy.provider,null)});
test('Anime RAGF family tampering is rejected',()=>{const family=generateAnimeCharacterFamily({assetId:'character:test'}).family;const tampered={...family,provider:{...family.provider,mode:'external'}};assert.equal(validateAnimeCharacterFamily(tampered).valid,false)});
test('Anime RAGF state changes visible media but preserves identity and appearance continuity',()=>{const idle=generateAnimeCharacterFamily({assetId:'character:continuity',name:'Continuity Character',seed:'continuity-seed',state:{expression:'neutral',pose:'idle',mouth_shape:'closed'}}).family,resolve=generateAnimeCharacterFamily({assetId:'character:continuity',name:'Continuity Character',seed:'continuity-seed',state:{expression:'resolve',pose:'raise',mouth_shape:'o'}}).family;assert.equal(idle.identity_root,resolve.identity_root);assert.equal(idle.palette_root,resolve.palette_root);assert.equal(idle.proportion_root,resolve.proportion_root);assert.notEqual(idle.state_root,resolve.state_root);assert.notEqual(idle.media_manifest.primary_vector.root,resolve.media_manifest.primary_vector.root);assert.notEqual(idle.asset_root,resolve.asset_root);assert.equal(idle.continuity_bundle.stable_across_cuts,true);assert.equal(resolve.continuity_bundle.stable_across_cuts,true)});
test('Anime RAGF deterministic render repeats byte-identically',()=>{const a=generateAnimeCharacterFamily({assetId:'character:deterministic',name:'Deterministic Character',seed:'same-seed',state:{expression:'restrained_question',pose:'idle',mouth_shape:'a'}}),b=generateAnimeCharacterFamily({assetId:'character:deterministic',name:'Deterministic Character',seed:'same-seed',state:{expression:'restrained_question',pose:'idle',mouth_shape:'a'}});assert.equal(a.family.family_root,b.family.family_root);assert.equal(a.files['front-view.png'].content,b.files['front-view.png'].content);assert.equal(a.family.provider_receipt.output_root,b.family.provider_receipt.output_root)});
test('Anime RAGF rejects a missing raster evidence contract',()=>{const family=generateAnimeCharacterFamily({assetId:'character:raster-negative'}).family;const invalid={...family,media_manifest:{...family.media_manifest,primary_raster:null}};assert.equal(validateAnimeCharacterFamily(invalid).valid,false);assert.ok(validateAnimeCharacterFamily(invalid).errors.includes('RAGF_ANIME_CHARACTER_RASTER_MEDIA_MISSING'))});
test('Anime RAGF schema requires a real raster and state contract',()=>{const schema=JSON.parse(fs.readFileSync(path.join(import.meta.dirname,'../schemas/anime-character-family.v0.1.schema.json'),'utf8'));assert.equal(schema.properties.format.const,'ragf.anime-character-family.v0.1');assert.ok(schema.required.includes('media_manifest'));assert.ok(schema.properties.media_manifest.required.includes('primary_raster'));assert.ok(schema.properties.render_contract.required.includes('state_fields'));});
