import test from 'node:test';import assert from 'node:assert/strict';
import {canonicalJson,rootHash,seal,verifySeal,seededRandom,normalizeIntent,validateIntent,createGenome,validateGenome,createProviderManifest,validateProvider,deriveGenomeFromIntent,requiredCapabilities,ProviderRegistry,negotiateCapabilities,builtinProviders,createGenerationPlan} from '../src/index.mjs';
const base={description:'创建一名冰属性女剑士，名字叫霜璃，属于北境守望者，动作敏捷。',asset_kind:'character-2d',target_platforms:['mobile','desktop'],constraints:{palette:['#1c4fa3','#f2f6ff','#9ddcff','#17305a'],max_texture_size:512,max_sprite_frames:6,max_particles:96,audio_seconds:.8}};
test('canonical JSON ignores object key order',()=>assert.equal(canonicalJson({b:2,a:1}),canonicalJson({a:1,b:2})));
test('root hash is stable',()=>assert.equal(rootHash({a:[1,2]}),rootHash({a:[1,2]})));
test('seal and verify',()=>assert.equal(verifySeal(seal({a:1},'x'),'x'),true));
test('tampered seal fails',()=>{const x=seal({a:1},'x');x.a=2;assert.equal(verifySeal(x,'x'),false)});
test('seeded random repeats',()=>{const a=seededRandom('x'),b=seededRandom('x');assert.deepEqual([a(),a(),a()],[b(),b(),b()])});
test('intent requires description',()=>assert.throws(()=>normalizeIntent({}),/INTENT_DESCRIPTION_REQUIRED/));
test('intent normalizes platform order',()=>assert.deepEqual(normalizeIntent(base).target_platforms,['desktop','mobile']));
test('intent seal validates',()=>assert.equal(validateIntent(normalizeIntent(base)).valid,true));
test('tampered intent rejected',()=>{const x=normalizeIntent(base);x.description='changed';assert.equal(validateIntent(x).valid,false)});
test('genome stable identity is created',()=>assert.match(createGenome(normalizeIntent(base)).identity.asset_id,/^asset:/));
test('genome validation passes',()=>{const i=normalizeIntent(base);assert.equal(validateGenome(createGenome(i)).valid,true)});
test('derived genome detects ice',()=>assert.equal(deriveGenomeFromIntent(normalizeIntent(base)).semantics.element,'ice'));
test('derived genome extracts name',()=>assert.equal(deriveGenomeFromIntent(normalizeIntent(base)).identity.name,'霜璃'));
test('derived genome adds dash for agile intent',()=>assert.ok(deriveGenomeFromIntent(normalizeIntent(base)).behavior.animation_set.includes('dash')));
test('required capabilities map every output',()=>{const g=deriveGenomeFromIntent(normalizeIntent(base));assert.equal(requiredCapabilities(g).length,g.required_outputs.length)});
test('provider manifest seals',()=>{const p=createProviderManifest({provider_id:'p',capabilities:[{capability_id:'x'}]});assert.equal(validateProvider(p).valid,true)});
test('provider registry rejects tampering',()=>{const p=createProviderManifest({provider_id:'p',capabilities:[{capability_id:'x'}]});p.name='bad';assert.throws(()=>new ProviderRegistry([p]),/PROVIDER_INVALID/)});
test('builtin provider covers five reference outputs',()=>assert.ok(builtinProviders()[0].capabilities.length>=5));
test('negotiation resolves required capabilities',()=>{const i=normalizeIntent(base),g=deriveGenomeFromIntent(i),n=negotiateCapabilities(requiredCapabilities(g),new ProviderRegistry(builtinProviders()),{platforms:i.target_platforms});assert.equal(n.eligible,true)});
test('negotiation reports unresolved capability',()=>{const n=negotiateCapabilities([{output:'x',capability_id:'missing'}],new ProviderRegistry(builtinProviders()));assert.equal(n.unresolved.length,1)});
test('generation plan has three variants',()=>{const i=normalizeIntent(base),g=deriveGenomeFromIntent(i),n=negotiateCapabilities(requiredCapabilities(g),new ProviderRegistry(builtinProviders()),{platforms:i.target_platforms});assert.equal(createGenerationPlan(g,n).variants.length,3)});
