import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {generateAssetWorkspace,regenerateAssetWorkspace,verifyWorkspace,validateAssetFamily,planIncrementalRegeneration,validateLineageGraph,rootHash} from '../src/index.mjs';
const intent={description:'创建一名冰属性三维女剑士，名字叫霜璃，属于北境守望者，动作敏捷，攻击前有预警。',subject_id:'subject:test',asset_kind:'character-3d',target_platforms:['desktop','mobile','web','xr'],constraints:{palette:['#1c4fa3','#f2f6ff','#9ddcff','#17305a'],style:'stylized-readable-pbr',max_texture_size:512,max_sprite_frames:6,audio_seconds:.8,max_particles:96,max_triangles:2400,pbr_texture_size:256,max_bones:64,animation_fps:30}};
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ragf-family-')),ws=generateAssetWorkspace(intent,{outDir:dir}),selected=ws.candidates.find(c=>c.candidate_id===ws.recommended_candidate_id);
test('workspace exposes asset family',()=>assert.equal(ws.asset_family.format,'reality-asset.family.v0.3'));
test('asset family validation passes',()=>assert.equal(validateAssetFamily(ws.asset_family).valid,true));
test('asset family contains three platform-quality members',()=>assert.equal(ws.asset_family.members.length,3));
test('asset family has exactly one selected member',()=>assert.equal(ws.asset_family.members.filter(x=>x.selected).length,1));
test('asset family preserves stable asset identity',()=>assert.equal(ws.asset_family.asset_id,ws.genome.identity.asset_id));
test('lineage graph links intent genome family and bundle',()=>assert.deepEqual(ws.lineage_graph.edges.map(x=>x.relation),['compiled-to','instantiated-as-family','selected-and-sealed']));
test('prefab blueprint is produced',()=>assert.equal(selected.artifacts['prefab-blueprint'].data.format,'reality-asset.prefab-blueprint.v0.3'));
test('prefab contains six runtime components',()=>assert.equal(selected.artifacts['prefab-blueprint'].data.components.length,6));
test('prefab binds mesh, rig, collision, audio and effects',()=>{const d=selected.artifacts['prefab-blueprint'].data.dependencies;for(const x of ['mesh-glb','skeleton-rig','collision-shape','sfx-wav','particle-preset'])assert.ok(d.includes(x));});
test('retarget profile maps canonical right arm',()=>assert.equal(selected.artifacts['retarget-profile'].data.bone_map.right_arm,'arm_r'));
test('retarget profile carries semantic animation events',()=>assert.ok(selected.artifacts['retarget-profile'].data.clips.find(x=>x.name==='attack').semantic_events.some(x=>x.type==='telegraph')));
test('projection manifest has five media projections',()=>assert.equal(selected.artifacts['projection-manifest'].data.projections.length,5));
test('projection manifest preserves stable identity',()=>assert.equal(selected.artifacts['projection-manifest'].data.invariants.identity,ws.genome.identity.asset_id));
test('XR projection references VSR RSR and retarget roles',()=>{const roles=selected.artifacts['projection-manifest'].data.projections.find(x=>x.projection_id==='xr-avatar').roles;for(const x of ['vsr-spatial-asset','rsr-embodiment-profile','retarget-profile'])assert.ok(roles.includes(x));});
test('dependency graph records assembly edges',()=>assert.ok(selected.artifacts['dependency-graph'].data.edges.some(x=>x.to==='role:prefab-blueprint')));
test('dependency graph records palette impact',()=>assert.ok(selected.artifacts['dependency-graph'].data.change_impact.palette.includes('pbr-texture-pack')));
test('Studio import registers prefab and projections',()=>{const x=JSON.parse(fs.readFileSync(path.join(dir,'reality-studio-import.json')));assert.ok(x.operations.some(o=>o.op==='register-prefab'));assert.ok(x.operations.some(o=>o.op==='register-cross-media-projections'));});
test('continuity bundle exposes asset-family runtime roles',()=>{assert.equal(ws.continuity_bundle.extensions.studio.prefab_role,'prefab-blueprint');assert.equal(ws.continuity_bundle.extensions.vsr.projection_role,'projection-manifest');});
test('family and lineage roots are deterministic',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'ragf-family-b-')),b=generateAssetWorkspace(intent,{outDir:d});assert.equal(b.asset_family.family_root,ws.asset_family.family_root);assert.equal(b.lineage_graph.lineage_root,ws.lineage_graph.lineage_root);});
test('palette patch plans material and projection rebuild',()=>{const p=planIncrementalRegeneration(ws,{constraints:{palette:['#122244','#ffffff','#00ccff','#000011']}});assert.ok(p.impacted_roles.includes('pbr-texture-pack'));assert.ok(p.impacted_roles.includes('projection-manifest'));});
test('palette patch plans geometry reuse',()=>{const p=planIncrementalRegeneration(ws,{constraints:{palette:['#122244','#ffffff','#00ccff','#000011']}});assert.ok(p.reusable_roles.includes('mesh-glb'));assert.ok(p.reusable_roles.includes('skeleton-rig'));});
test('bone budget patch impacts rig mesh and retargeting',()=>{const p=planIncrementalRegeneration(ws,{constraints:{max_bones:48}});for(const x of ['skeleton-rig','mesh-glb','retarget-profile'])assert.ok(p.impacted_roles.includes(x));});
test('regeneration preserves stable asset id and lineage',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'ragf-regen-')),next=regenerateAssetWorkspace(ws,{constraints:{palette:['#122244','#ffffff','#00ccff','#000011']}},{outDir:d});assert.equal(next.genome.identity.asset_id,ws.genome.identity.asset_id);assert.ok(next.lineage_graph.nodes.some(n=>n.root===ws.workspace_root));assert.equal(verifyWorkspace(next,{baseDir:d,verifyFiles:true}).valid,true);});
test('regeneration receipt proves palette-independent mesh reuse',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'ragf-regen-reuse-')),next=regenerateAssetWorkspace(ws,{constraints:{palette:['#122244','#ffffff','#00ccff','#000011']}},{outDir:d});assert.ok(next.regeneration_receipt.reused_by_content_root.includes('mesh-glb'));assert.ok(next.regeneration_receipt.changed_roles.includes('pbr-texture-pack'));});
test('tampered family root fails workspace verification',()=>{const x=structuredClone(ws);x.asset_family.name='tampered';assert.equal(verifyWorkspace(x).valid,false);});
test('family root is content addressed',()=>{const x=structuredClone(ws.asset_family),r=x.family_root;delete x.family_root;assert.equal(rootHash(x),r);});

test('lineage graph validation passes',()=>assert.equal(validateLineageGraph(ws.lineage_graph).valid,true));
test('tampered lineage root fails workspace verification',()=>{const x=structuredClone(ws);x.lineage_graph.edges[0].relation='tampered';assert.equal(verifyWorkspace(x).valid,false);});
