import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeIntent,deriveGenomeFromIntent,generateMesh3d,generateLodManifest,generatePbrTexturePack,generateSkeletonRig,generateAnimationClips,generateVsrSpatialAsset,generateRsrEmbodimentProfile,inspectGlb,rootHash} from '../src/index.mjs';
const intent=normalizeIntent({description:'创建一名冰属性三维女剑士，名字叫霜璃，动作敏捷。',asset_kind:'character-3d',constraints:{max_triangles:2400,pbr_texture_size:128,max_bones:64}}),genome=deriveGenomeFromIntent(intent),mesh0=generateMesh3d({genome,variant:'balanced',lod:0}),mesh1=generateMesh3d({genome,variant:'balanced',lod:1}),mesh2=generateMesh3d({genome,variant:'balanced',lod:2}),inspection=inspectGlb(mesh0.glb),rig=generateSkeletonRig({genome,variant:'balanced'}),clips=generateAnimationClips({genome,variant:'balanced'}),pbr=generatePbrTexturePack({genome,variant:'balanced'});
test('GLB begins with glTF magic',()=>assert.equal(mesh0.glb.readUInt32LE(0),0x46546c67));
test('GLB version is 2',()=>assert.equal(mesh0.glb.readUInt32LE(4),2));
test('GLB declared length matches bytes',()=>assert.equal(mesh0.glb.readUInt32LE(8),mesh0.glb.length));
test('GLB inspection passes',()=>assert.equal(inspection.valid,true));
test('GLB contains one mesh',()=>assert.equal(inspection.mesh_count,1));
test('GLB contains a skin',()=>assert.equal(inspection.skin_count,1));
test('GLB contains animation',()=>assert.equal(inspection.animation_count,1));
test('GLB contains right arm bone',()=>assert.ok(inspection.json.nodes.some(n=>n.name==='arm_r')));
test('GLB mesh is rigged',()=>assert.equal(mesh0.metadata.rigged,true));
test('GLB material is PBR',()=>assert.equal(mesh0.metadata.pbr,true));
test('3D generation is deterministic',()=>assert.equal(rootHash(mesh0.glb.toString('base64')),rootHash(generateMesh3d({genome,variant:'balanced',lod:0}).glb.toString('base64'))));
test('LOD triangle counts descend',()=>assert.ok(mesh0.metadata.triangle_count>mesh1.metadata.triangle_count&&mesh1.metadata.triangle_count>mesh2.metadata.triangle_count));
test('LOD manifest contains three levels',()=>assert.equal(generateLodManifest({genome,variant:'balanced',meshes:[mesh0,mesh1,mesh2]}).levels.length,3));
test('PBR pack contains four texture maps',()=>assert.equal(pbr.files.length,4));
test('PBR texture files are PNG',()=>assert.ok(pbr.files.every(f=>f.buffer.subarray(1,4).toString()==='PNG')));
test('skeleton uses humanoid-lite profile',()=>assert.equal(rig.profile,'humanoid-lite'));
test('skeleton exposes weapon socket',()=>assert.ok(rig.sockets.some(s=>s.name==='weapon_r')));
test('attack animation has telegraph event',()=>assert.ok(clips.clips.find(c=>c.name==='attack').events.some(e=>e.type==='telegraph')));
test('VSR adapter targets spatial scene v0.4',()=>assert.equal(generateVsrSpatialAsset({genome,variant:'balanced',mesh:mesh0}).compatibility.target_format,'vsr.spatial-scene.v0.4'));
test('VSR adapter preserves mesh positions',()=>assert.equal(generateVsrSpatialAsset({genome,variant:'balanced',mesh:mesh0}).mesh.positions.length,mesh0.geometry.positions.length));
test('RSR adapter targets embodiment v0.5',()=>assert.equal(generateRsrEmbodimentProfile({genome,variant:'balanced',rig}).compatibility.target_format,'rsr.spatial-embodiment-world.v0.5'));
