import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeIntent,deriveGenomeFromIntent,generateMesh3d,generateLodManifest,generatePbrTexturePack,generateSkeletonRig,generateAnimationClips,generateVsrSpatialAsset,generateRsrEmbodimentProfile,encodeKtx2Rgba8,inspectKtx2,inspectGlb,rootHash} from '../src/index.mjs';
const intent=normalizeIntent({description:'创建一名冰属性三维女剑士，名字叫霜璃，动作敏捷。',asset_kind:'character-3d',constraints:{max_triangles:2400,pbr_texture_size:128,max_bones:64}}),genome=deriveGenomeFromIntent(intent),pbr=generatePbrTexturePack({genome,variant:'balanced'}),mesh0=generateMesh3d({genome,variant:'balanced',lod:0}),mesh1=generateMesh3d({genome,variant:'balanced',lod:1}),mesh2=generateMesh3d({genome,variant:'balanced',lod:2}),texturedMesh=generateMesh3d({genome,variant:'balanced',lod:0,pbr}),inspection=inspectGlb(mesh0.glb),texturedInspection=inspectGlb(texturedMesh.glb),rig=generateSkeletonRig({genome,variant:'balanced'}),clips=generateAnimationClips({genome,variant:'balanced'});
test('GLB begins with glTF magic',()=>assert.equal(mesh0.glb.readUInt32LE(0),0x46546c67));
test('GLB version is 2',()=>assert.equal(mesh0.glb.readUInt32LE(4),2));
test('GLB declared length matches bytes',()=>assert.equal(mesh0.glb.readUInt32LE(8),mesh0.glb.length));
test('GLB inspection passes',()=>assert.equal(inspection.valid,true));
test('GLB contains one mesh',()=>assert.equal(inspection.mesh_count,1));
test('GLB contains a skin',()=>assert.equal(inspection.skin_count,1));
test('GLB contains the embedded animation set',()=>assert.equal(inspection.animation_count,4));
test('GLB contains right arm bone',()=>assert.ok(inspection.json.nodes.some(n=>n.name==='arm_r')));
test('GLB mesh is rigged',()=>assert.equal(mesh0.metadata.rigged,true));
test('GLB material is PBR',()=>assert.equal(mesh0.metadata.pbr,true));
test('GLB quality profile supports embedded PBR textures and a morph target',()=>{assert.equal(texturedMesh.metadata.embedded_texture_count,4);assert.equal(texturedMesh.metadata.morph_target_count,1);assert.equal(texturedInspection.json.images.length,4);assert.ok(texturedMesh.metadata.triangle_count>700)});
test('3D generation is deterministic',()=>assert.equal(rootHash(mesh0.glb.toString('base64')),rootHash(generateMesh3d({genome,variant:'balanced',lod:0}).glb.toString('base64'))));
test('LOD triangle counts descend',()=>assert.ok(mesh0.metadata.triangle_count>mesh1.metadata.triangle_count&&mesh1.metadata.triangle_count>mesh2.metadata.triangle_count));
test('LOD manifest contains three levels',()=>assert.equal(generateLodManifest({genome,variant:'balanced',meshes:[mesh0,mesh1,mesh2]}).levels.length,3));
test('PBR pack contains four texture maps',()=>assert.equal(pbr.files.length,4));
test('PBR texture files are PNG',()=>assert.ok(pbr.files.every(f=>f.buffer.subarray(1,4).toString()==='PNG')));
test('skeleton uses the rounded humanoid profile',()=>{assert.equal(rig.profile,'humanoid-rounded-v0.4');assert.equal(rig.bones.length,8);assert.equal(rig.bones[0].name,'root')});
test('skeleton exposes weapon socket',()=>assert.ok(rig.sockets.some(s=>s.name==='weapon_r')));
test('attack animation has telegraph event',()=>assert.ok(clips.clips.find(c=>c.name==='attack').events.some(e=>e.type==='telegraph')));
test('VSR adapter targets spatial scene v0.4',()=>assert.equal(generateVsrSpatialAsset({genome,variant:'balanced',mesh:mesh0}).compatibility.target_format,'vsr.spatial-scene.v0.4'));
test('VSR adapter preserves mesh positions',()=>assert.equal(generateVsrSpatialAsset({genome,variant:'balanced',mesh:mesh0}).mesh.positions.length,mesh0.geometry.positions.length));
test('VSR adapter carries all generated LOD meshes',()=>assert.equal(generateVsrSpatialAsset({genome,variant:'balanced',mesh:mesh0,meshes:[mesh0,mesh1,mesh2]}).lods.length,3));
test('RSR adapter targets current embodiment v0.6',()=>assert.equal(generateRsrEmbodimentProfile({genome,variant:'balanced',rig}).compatibility.target_format,'rsr.spatial-embodiment-world.v0.6'));
test('RSR adapter exposes fixed-point body dimensions',()=>{const profile=generateRsrEmbodimentProfile({genome,variant:'balanced',rig});assert.equal(profile.units.fixed_point_scale,1000);assert.equal(profile.body.runtime_kind,'dynamic');assert.ok(profile.body.shape_spec.halfHeight>0)});
test('KTX2 encoder seals deterministic RGBA8 mip levels for progressive residency',()=>{const levels=[{width:4,height:4,pixels:Buffer.alloc(4*4*4,24)},{width:2,height:2,pixels:Buffer.alloc(2*2*4,80)},{width:1,height:1,pixels:Buffer.from([128,128,128,255])}],bytes=encodeKtx2Rgba8(levels,{colorSpace:'srgb'}),repeat=encodeKtx2Rgba8(levels,{colorSpace:'srgb'}),inspection=inspectKtx2(bytes);assert.equal(bytes.equals(repeat),true);assert.equal(inspection.valid,true);assert.equal(inspection.color_space,'srgb');assert.equal(inspection.level_count,3);assert.deepEqual(inspection.levels.map(level=>[level.width,level.height,level.byteLength]),[[4,4,64],[2,2,16],[1,1,4]]);assert.match(inspection.root,/^[a-f0-9]{64}$/)});
