import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {AssetProductionSession,evaluateProductionCandidate,materializeCandidateSelection,ASSET_PRODUCTION_VERSION} from '../src/index.mjs';

const intent={description:'创建一名冰属性三维女剑士，名字叫霜璃，属于北境守望者，动作敏捷，攻击前有预警。',subject_id:'subject:production-test',asset_kind:'character-3d',target_platforms:['desktop','mobile','web','xr'],constraints:{palette:['#1c4fa3','#f2f6ff','#9ddcff','#17305a'],style:'stylized-readable-pbr',max_texture_size:512,max_sprite_frames:6,audio_seconds:.8,max_particles:96,max_triangles:2400,pbr_texture_size:256,max_bones:64,animation_fps:30}};
const make=()=>new AssetProductionSession(intent,{rootDir:fs.mkdtempSync(path.join(os.tmpdir(),'ragf-production-'))});

test('production session generates three reviewable candidates',()=>{const s=make();const i=s.generate();assert.equal(i.version,ASSET_PRODUCTION_VERSION);assert.equal(i.candidates.length,3);assert.equal(i.status,'review')});
test('every generated candidate passes production readiness',()=>{const s=make();const i=s.generate();assert.ok(i.candidates.every(c=>c.pass));assert.ok(i.candidates.every(c=>Object.values(c.gates).every(Boolean)))});
test('candidate readiness exposes real 3D statistics',()=>{const s=make();s.generate();const w=s.current().workspace,c=w.candidates[0],r=evaluateProductionCandidate(w,c.candidate_id);assert.ok(r.statistics.triangle_count>0);assert.equal(r.statistics.bone_count,8);assert.ok(r.statistics.animation_count>0);assert.ok(r.statistics.file_count>=20)});
test('manual candidate selection creates sealed receipt',()=>{const s=make();const i=s.generate(),mobile=i.candidates.find(c=>c.variant==='mobile');const next=s.select(mobile.candidate_id,{reason:'mobile-budget'});assert.equal(next.selected_candidate_id,mobile.candidate_id);assert.equal(next.selection_receipt.reason,'mobile-budget');assert.equal(next.selection_receipt.receipt_root.length,64)});
test('materialized selection rewrites continuity to selected candidate',()=>{const s=make();const i=s.generate(),cinematic=i.candidates.find(c=>c.variant==='cinematic'),x=materializeCandidateSelection(s.current().workspace,cinematic.candidate_id);assert.equal(x.continuity_bundle.variants.selected,'cinematic');assert.equal(x.asset_family.selected_candidate_id,cinematic.candidate_id);assert.equal(x.asset_family.members.filter(m=>m.selected).length,1);assert.equal(x.asset_family.members.find(m=>m.selected).variant,'cinematic')});
test('materialized candidate files use selected variant paths',()=>{const s=make();const i=s.generate(),mobile=i.candidates.find(c=>c.variant==='mobile'),x=materializeCandidateSelection(s.current().workspace,mobile.candidate_id);assert.ok(x.continuity_bundle.files.every(f=>f.path.startsWith('candidates/mobile/')));assert.ok(x.continuity_bundle.files.every(f=>f.sha256.length===64))});
test('targeted regeneration preserves asset identity',()=>{const s=make();const a=s.generate(),asset=a.asset.asset_id,b=s.regenerate({constraints:{palette:['#2f59c4','#ffffff','#80e8ff','#101a34']}});assert.equal(b.asset.asset_id,asset);assert.equal(b.generation,2);assert.ok(b.generations[1].regeneration_plan_root)});
test('targeted palette regeneration records reuse and change receipt',()=>{const s=make();s.generate();s.regenerate({constraints:{palette:['#2f59c4','#ffffff','#80e8ff','#101a34']}});const w=s.current().workspace;assert.ok(w.regeneration_receipt.changed_roles.includes('pbr-texture-pack'));assert.ok(w.regeneration_receipt.reused_by_content_root.includes('mesh-glb'))});
test('accept creates Studio import authority request and production manifest',()=>{const s=make();s.generate();const x=s.accept();assert.equal(x.acceptance_receipt.status,'accepted');assert.equal(x.studio_import.asset_id,x.continuity_bundle.asset_identity.asset_id);assert.equal(x.authority_request.status,'proposed');assert.ok(x.production_manifest.roles.includes('prefab-blueprint'))});
test('accept can choose a non-recommended eligible candidate',()=>{const s=make();const i=s.generate(),cinematic=i.candidates.find(c=>c.variant==='cinematic');s.select(cinematic.candidate_id);const x=s.accept();assert.equal(x.production_manifest.variant,'cinematic');assert.equal(x.continuity_bundle.variants.selected,'cinematic')});
test('generation files are physically present and verifiable',()=>{const s=make();s.generate();const x=s.exportArtifacts();const base=s.current().out_dir;for(const f of x.production_manifest.files)assert.ok(fs.existsSync(path.join(base,f.path)));assert.equal(s.current().verification.valid,true)});
test('session export is deterministic for unchanged generation',()=>{const s=make();s.generate();const a=s.exportArtifacts().production_manifest.manifest_root,b=s.exportArtifacts().production_manifest.manifest_root;assert.equal(a,b)});
