import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {generateAssetWorkspace,verifyWorkspace,inspectWorkspace,inspectGlb,validateRealityBranchWorkspace} from '../src/index.mjs';
const intent={description:'创建一名冰属性三维女剑士，名字叫霜璃，属于北境守望者，动作敏捷，攻击前有预警。',subject_id:'subject:test',asset_kind:'character-3d',target_platforms:['desktop','mobile','web','xr'],constraints:{palette:['#1c4fa3','#f2f6ff','#9ddcff','#17305a'],style:'stylized-readable-pbr',max_texture_size:512,max_sprite_frames:6,audio_seconds:.8,max_particles:96,max_triangles:2400,pbr_texture_size:256,max_bones:64,animation_fps:30}};
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ragf3d-')),ws=generateAssetWorkspace(intent,{outDir:dir}),selected=ws.candidates.find(c=>c.candidate_id===ws.recommended_candidate_id),summary=inspectWorkspace(ws);
test('3D workspace uses v0.3 format',()=>assert.equal(ws.format,'reality-asset.genesis-workspace.v0.3'));
test('3D genome kind is preserved',()=>assert.equal(ws.genome.identity.kind,'character-3d'));
test('three production candidates exist',()=>assert.equal(ws.candidates.length,3));
test('every candidate has 18 output families',()=>assert.ok(ws.candidates.every(c=>Object.keys(c.artifacts).length===18)));
test('every candidate has primary GLB',()=>assert.ok(ws.candidates.every(c=>c.artifacts['mesh-glb'])));
test('every candidate has PBR pack',()=>assert.ok(ws.candidates.every(c=>c.artifacts['pbr-texture-pack'])));
test('every candidate has rig and clips',()=>assert.ok(ws.candidates.every(c=>c.artifacts['skeleton-rig']&&c.artifacts['animation-clips'])));
test('every candidate meets rounded geometry and material quality gates',()=>assert.ok(ws.candidates.every(c=>c.artifacts['mesh-glb'].metadata.triangle_count>700&&c.artifacts['mesh-glb'].metadata.morph_target_count===1&&c.artifacts['mesh-glb'].metadata.animation_count===4&&c.artifacts['pbr-texture-pack'].metadata.material_model==='stylized-pbr-v0.4')));
test('every candidate has VSR and RSR adapters',()=>assert.ok(ws.candidates.every(c=>c.artifacts['vsr-spatial-asset']&&c.artifacts['rsr-embodiment-profile'])));
test('runtime adapter validation is part of production readiness',()=>assert.ok(ws.reports.every(report=>report.runtime_validation?.valid===true)));
test('all candidate production scores pass',()=>assert.ok(ws.reports.every(r=>r.scores.production>=6500&&r.eligible)));
test('selected continuity bundle has 27 files',()=>assert.equal(ws.continuity_bundle.files.length,27));
test('workspace and selected files verify',()=>assert.equal(verifyWorkspace(ws,{baseDir:dir,verifyFiles:true}).valid,true));
test('file verifier checks all selected files',()=>assert.equal(verifyWorkspace(ws,{baseDir:dir,verifyFiles:true}).file_integrity_checked,27));
test('primary GLB file exists',()=>assert.ok(fs.existsSync(path.join(dir,'candidates',selected.variant,'mesh','lod0.glb'))));
test('all three GLB LOD files parse',()=>{for(let i=0;i<3;i++)assert.equal(inspectGlb(fs.readFileSync(path.join(dir,'candidates',selected.variant,'mesh',`lod${i}.glb`))).valid,true)});
test('selected LOD triangle counts descend',()=>{const a=selected.artifacts['mesh-glb'].metadata.triangle_count,b=selected.artifacts['mesh-lod1-glb'].metadata.triangle_count,c=selected.artifacts['mesh-lod2-glb'].metadata.triangle_count;assert.ok(a>b&&b>c)});
test('PBR maps are written',()=>{for(const n of ['base-color.png','normal.png','orm.png','emissive.png'])assert.ok(fs.existsSync(path.join(dir,'candidates',selected.variant,'pbr',n)))});
test('Studio import contains v1.4 asset record',()=>{const x=JSON.parse(fs.readFileSync(path.join(dir,'reality-studio-import.json')));assert.equal(x.asset_record.format,'reality-studio.asset-record.v1.4')});
test('Studio record preserves stable asset id',()=>{const x=JSON.parse(fs.readFileSync(path.join(dir,'reality-studio-import.json')));assert.equal(x.asset_record.asset_id,ws.genome.identity.asset_id)});
test('VSR adapter file targets v0.4',()=>{const x=JSON.parse(fs.readFileSync(path.join(dir,'candidates',selected.variant,'adapters','vsr-spatial-asset.json')));assert.equal(x.compatibility.target_format,'vsr.spatial-scene.v0.4')});
test('RSR adapter file targets current v0.6',()=>{const x=JSON.parse(fs.readFileSync(path.join(dir,'candidates',selected.variant,'adapters','rsr-embodiment-profile.json')));assert.equal(x.compatibility.target_format,'rsr.spatial-embodiment-world.v0.6');assert.equal(x.body.runtime_kind,'dynamic')});
test('VSR adapter file contains generated LOD bindings',()=>{const x=JSON.parse(fs.readFileSync(path.join(dir,'candidates',selected.variant,'adapters','vsr-spatial-asset.json')));assert.equal(x.version,'0.4.0');assert.equal(x.lods.length,3);assert.equal(x.node.lods.length,2)});
test('continuity provenance records providers',()=>assert.ok(ws.continuity_bundle.provenance.providers.length>=2));
test('continuity provider licenses are explicit',()=>assert.ok(ws.continuity_bundle.provenance.providers.every(p=>p.license&&p.license!=='unspecified')));
test('Reality Branch workspace remains valid',()=>assert.equal(validateRealityBranchWorkspace(ws.reality_branch_workspace).valid,true));
test('preview contains rotating canvas',()=>assert.ok(fs.readFileSync(path.join(dir,'preview.html'),'utf8').includes('requestAnimationFrame')));
test('inspect summary exposes mesh statistics',()=>assert.ok(summary.selected.triangle_count>0&&summary.selected.bone_count===8));
test('same intent has deterministic workspace root',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'ragf3d-b-'));assert.equal(generateAssetWorkspace(intent,{outDir:d}).workspace_root,ws.workspace_root)});
test('different seed changes 3D workspace root',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'ragf3d-c-'));assert.notEqual(generateAssetWorkspace({...intent,seed:'other'},{outDir:d}).workspace_root,ws.workspace_root)});
test('tampered selected file is detected',()=>{const p=path.join(dir,'candidates',selected.variant,'mesh','lod0.glb'),original=fs.readFileSync(p);fs.appendFileSync(p,'x');assert.equal(verifyWorkspace(ws,{baseDir:dir,verifyFiles:true}).valid,false);fs.writeFileSync(p,original)});
