export const SEQUENCE_OBJECT_RISK_TYPES = [
  "MEANING_DRIFT","REAL_FACT_CLAIM","SCIENCE_VERIFIED_CLAIM","PRODUCTION_DEPLOYED_CLAIM","REAL_BACKEND_CLAIM",
  "REAL_LAW_CLAIM","REAL_PHYSICS_CLAIM","FINANCIAL_ASSET_CLAIM","REALITY_FORECAST_CLAIM",
  "DEMO_LEAK_TO_REAL","REAL_WRITE_TO_DEMO","FOUNDER_LEAK_TO_PUBLIC",
  "RUNTIME_WITHOUT_CONTRACT","ENGINE_WITHOUT_QA","MODEL_WITHOUT_VALIDATION","CIVIL_WITHOUT_GOVERNANCE",
  "PERMISSION_ESCALATION","OVERGROWTH","CHARACTER_PERSONA_SHIFT","WORLD_CANON_CONTAMINATION",
] as const;
export type SequenceObjectRiskType = (typeof SEQUENCE_OBJECT_RISK_TYPES)[number];

export const RISK_SEVERITY: Record<SequenceObjectRiskType, "LOW"|"MEDIUM"|"HIGH"|"CRITICAL"> = {
  MEANING_DRIFT: "MEDIUM",
  REAL_FACT_CLAIM: "CRITICAL", SCIENCE_VERIFIED_CLAIM: "CRITICAL", PRODUCTION_DEPLOYED_CLAIM: "CRITICAL", REAL_BACKEND_CLAIM: "CRITICAL",
  REAL_LAW_CLAIM: "CRITICAL", REAL_PHYSICS_CLAIM: "CRITICAL", FINANCIAL_ASSET_CLAIM: "CRITICAL", REALITY_FORECAST_CLAIM: "CRITICAL",
  DEMO_LEAK_TO_REAL: "CRITICAL", REAL_WRITE_TO_DEMO: "CRITICAL", FOUNDER_LEAK_TO_PUBLIC: "CRITICAL",
  RUNTIME_WITHOUT_CONTRACT: "HIGH", ENGINE_WITHOUT_QA: "HIGH", MODEL_WITHOUT_VALIDATION: "HIGH", CIVIL_WITHOUT_GOVERNANCE: "HIGH",
  PERMISSION_ESCALATION: "CRITICAL", OVERGROWTH: "MEDIUM",
  CHARACTER_PERSONA_SHIFT: "HIGH", WORLD_CANON_CONTAMINATION: "HIGH",
};
