// Sequence Object Types — 36 类
export const SEQUENCE_OBJECT_TYPES = [
  // A. 内容
  "TEXT_OBJECT","LYRIC_OBJECT","STORY_OBJECT","NARRATIVE_SCENE_OBJECT","PROMPT_OBJECT","TRANSLATION_OBJECT",
  // B. 资产
  "CHARACTER_OBJECT","WORLD_OBJECT","SONG_OBJECT","VISUAL_CONCEPT_OBJECT","PRODUCT_OBJECT","KNOWLEDGE_ENTRY_OBJECT","VOCABULARY_TERM_OBJECT","CALCULUS_ENTRY_OBJECT",
  // C. 结构
  "MODEL_OBJECT","FRAMEWORK_OBJECT","VARIABLE_MAP_OBJECT","DECISION_TREE_OBJECT","SCORE_MODEL_OBJECT","KNOWLEDGE_GRAPH_OBJECT","PROTOCOL_OBJECT",
  // D. 运行
  "ENGINE_OBJECT","WORKFLOW_OBJECT","RUNTIME_OBJECT","STATE_MACHINE_OBJECT","ROUTER_OBJECT","QA_RULE_OBJECT","VALIDATION_OBJECT","EXPORT_PACKAGE_OBJECT",
  // E. 文明
  "LANGUAGE_OBJECT","CONSTITUTION_OBJECT","CONSTANT_UNIVERSE_OBJECT","CIVILIZATION_PROTOCOL_OBJECT","MULTIWORLD_OBJECT","GOVERNANCE_OBJECT","CLM_ENTITY_OBJECT",
] as const;
export type SequenceObjectType = (typeof SEQUENCE_OBJECT_TYPES)[number];

export const SEQUENCE_OBJECT_TYPE_LABELS: Record<SequenceObjectType, string> = {
  TEXT_OBJECT: "文本对象", LYRIC_OBJECT: "歌词对象", STORY_OBJECT: "故事对象", NARRATIVE_SCENE_OBJECT: "剧情场景对象", PROMPT_OBJECT: "提示词对象", TRANSLATION_OBJECT: "翻译对象",
  CHARACTER_OBJECT: "角色对象", WORLD_OBJECT: "世界对象", SONG_OBJECT: "歌曲对象", VISUAL_CONCEPT_OBJECT: "视觉概念对象", PRODUCT_OBJECT: "产品对象", KNOWLEDGE_ENTRY_OBJECT: "知识条目对象", VOCABULARY_TERM_OBJECT: "词条对象", CALCULUS_ENTRY_OBJECT: "计算法条目对象",
  MODEL_OBJECT: "模型对象", FRAMEWORK_OBJECT: "框架对象", VARIABLE_MAP_OBJECT: "变量图对象", DECISION_TREE_OBJECT: "决策树对象", SCORE_MODEL_OBJECT: "评分模型对象", KNOWLEDGE_GRAPH_OBJECT: "知识图谱对象", PROTOCOL_OBJECT: "协议对象",
  ENGINE_OBJECT: "引擎对象", WORKFLOW_OBJECT: "工作流对象", RUNTIME_OBJECT: "运行时对象", STATE_MACHINE_OBJECT: "状态机对象", ROUTER_OBJECT: "路由对象", QA_RULE_OBJECT: "QA 规则对象", VALIDATION_OBJECT: "回验对象", EXPORT_PACKAGE_OBJECT: "导出包对象",
  LANGUAGE_OBJECT: "语言对象", CONSTITUTION_OBJECT: "宪法对象", CONSTANT_UNIVERSE_OBJECT: "常数宇宙对象", CIVILIZATION_PROTOCOL_OBJECT: "文明协议对象", MULTIWORLD_OBJECT: "多世界对象", GOVERNANCE_OBJECT: "治理对象", CLM_ENTITY_OBJECT: "创造物生命周期对象",
};
