import type { SequenceObjectType } from "./sequenceObjectTypes";

export const SEQUENCE_OBJECT_LAYERS = ["CONTENT_LAYER","ASSET_LAYER","STRUCTURE_LAYER","RUNTIME_LAYER","CIVILIZATION_LAYER"] as const;
export type SequenceObjectLayer = (typeof SEQUENCE_OBJECT_LAYERS)[number];

export const SEQUENCE_OBJECT_LAYER_LABELS: Record<SequenceObjectLayer, string> = {
  CONTENT_LAYER: "内容层",
  ASSET_LAYER: "资产层",
  STRUCTURE_LAYER: "结构层",
  RUNTIME_LAYER: "运行层",
  CIVILIZATION_LAYER: "文明层",
};

export const SEQUENCE_OBJECT_LAYER_DESCRIPTIONS: Record<SequenceObjectLayer, string> = {
  CONTENT_LAYER: "生成文字、歌词、剧情、Prompt 等内容，可直接输出。",
  ASSET_LAYER: "生成可保存、可复用的角色、世界、歌曲、产品、词条等资产，必须可保存到 Workspace。",
  STRUCTURE_LAYER: "生成模型、框架、变量图、知识图谱、协议等结构，必须有变量和关系。",
  RUNTIME_LAYER: "生成引擎、工作流、状态机、路由、QA 规则、回验对象等运行对象，必须有 Runtime Contract。",
  CIVILIZATION_LAYER: "生成语言、宪法、常数宇宙、治理协议、多世界网络等文明级对象，必须经过 Constitution Guard 与 CLM。",
};

export const OBJECT_TYPE_TO_LAYER: Record<SequenceObjectType, SequenceObjectLayer> = {
  TEXT_OBJECT: "CONTENT_LAYER", LYRIC_OBJECT: "CONTENT_LAYER", STORY_OBJECT: "CONTENT_LAYER", NARRATIVE_SCENE_OBJECT: "CONTENT_LAYER", PROMPT_OBJECT: "CONTENT_LAYER", TRANSLATION_OBJECT: "CONTENT_LAYER",
  CHARACTER_OBJECT: "ASSET_LAYER", WORLD_OBJECT: "ASSET_LAYER", SONG_OBJECT: "ASSET_LAYER", VISUAL_CONCEPT_OBJECT: "ASSET_LAYER", PRODUCT_OBJECT: "ASSET_LAYER", KNOWLEDGE_ENTRY_OBJECT: "ASSET_LAYER", VOCABULARY_TERM_OBJECT: "ASSET_LAYER", CALCULUS_ENTRY_OBJECT: "ASSET_LAYER",
  MODEL_OBJECT: "STRUCTURE_LAYER", FRAMEWORK_OBJECT: "STRUCTURE_LAYER", VARIABLE_MAP_OBJECT: "STRUCTURE_LAYER", DECISION_TREE_OBJECT: "STRUCTURE_LAYER", SCORE_MODEL_OBJECT: "STRUCTURE_LAYER", KNOWLEDGE_GRAPH_OBJECT: "STRUCTURE_LAYER", PROTOCOL_OBJECT: "STRUCTURE_LAYER",
  ENGINE_OBJECT: "RUNTIME_LAYER", WORKFLOW_OBJECT: "RUNTIME_LAYER", RUNTIME_OBJECT: "RUNTIME_LAYER", STATE_MACHINE_OBJECT: "RUNTIME_LAYER", ROUTER_OBJECT: "RUNTIME_LAYER", QA_RULE_OBJECT: "RUNTIME_LAYER", VALIDATION_OBJECT: "RUNTIME_LAYER", EXPORT_PACKAGE_OBJECT: "RUNTIME_LAYER",
  LANGUAGE_OBJECT: "CIVILIZATION_LAYER", CONSTITUTION_OBJECT: "CIVILIZATION_LAYER", CONSTANT_UNIVERSE_OBJECT: "CIVILIZATION_LAYER", CIVILIZATION_PROTOCOL_OBJECT: "CIVILIZATION_LAYER", MULTIWORLD_OBJECT: "CIVILIZATION_LAYER", GOVERNANCE_OBJECT: "CIVILIZATION_LAYER", CLM_ENTITY_OBJECT: "CIVILIZATION_LAYER",
};
