export const SEQUENCE_OBJECT_INTERFACE_TYPES = [
  "NARRATIVE","VOCAL","MODEL_GEN","TRANSLATION","PROMPT_FORGE","CODE_GEN",
  "WORLD_ENGINE","MULTI_WORLD","WORLD_KNOWLEDGE",
  "RUNTIME_SPINE","QA","VERSION_LEAP","LEARNING_DOCS","PRODUCT_ENCYCLOPEDIA",
  "MSL","VOCABULARY","CALCULUS_UNIVERSE","SYSTEM_CONSTITUTION","CLM","GOVERNANCE","ARCHIVE",
  "WORKSPACE","CROSS_FUNCTIONAL","DECISION_ENGINE","VISUAL_PROMPT",
] as const;
export type SequenceObjectInterfaceType = (typeof SEQUENCE_OBJECT_INTERFACE_TYPES)[number];

export const INTERFACE_TYPE_LABELS: Record<SequenceObjectInterfaceType, string> = {
  NARRATIVE: "剧情文本引擎", VOCAL: "声乐引擎", MODEL_GEN: "模型生成", TRANSLATION: "翻译引擎",
  PROMPT_FORGE: "Prompt Forge", CODE_GEN: "代码生成",
  WORLD_ENGINE: "数列世界引擎", MULTI_WORLD: "多世界网络", WORLD_KNOWLEDGE: "世界知识引擎",
  RUNTIME_SPINE: "运行时主干", QA: "Software QA", VERSION_LEAP: "版本跃迁", LEARNING_DOCS: "学习文档", PRODUCT_ENCYCLOPEDIA: "产品百科",
  MSL: "母体数列语言", VOCABULARY: "词汇百科", CALCULUS_UNIVERSE: "计算法宇宙", SYSTEM_CONSTITUTION: "系统宪法",
  CLM: "创造物生命周期", GOVERNANCE: "治理", ARCHIVE: "归档",
  WORKSPACE: "工作区", CROSS_FUNCTIONAL: "跨功能计算法", DECISION_ENGINE: "决策引擎", VISUAL_PROMPT: "视觉提示词",
};
