import assert from 'node:assert/strict';
import test from 'node:test';
import {createAnatomySystem} from '../src/anatomy.mjs';
import {compileFullBodyArtDirectedMorphology} from '../src/lower-body-morphology.mjs';
import {buildNativeSurfaceFrame} from '../src/native-surface-runtime.mjs';
import {buildWeightedNativeSurfaceFrame} from '../src/weighted-native-surface-runtime.mjs';
import {buildCelShadingDrawingGuide,validateCelShadingDrawingGuide} from '../src/cel-shading-drawing.mjs';
import {createSemanticAnimeVisualGrammar} from '../src/semantic-anime-visual-grammar.mjs';
import {compileFullBodyAnimeDrawingIR,validateFullBodyAnimeDrawingIR} from '../src/full-body-drawing-ir.mjs';
import {compileDrawingMeshIR,createPerformanceDrawingControls,applyDrawingCageDeformation} from '../src/drawing-mesh-deformation.mjs';

function fixture({view='front',pose='neutral',frame=0,weighted=true}={}){const system=createAnatomySystem({seed:'phase6-6-cel-shading'}),asset=compileFullBodyArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),options={view,pose,frame,totalFrames:120,width:320,height:180,scale:.52},surface=weighted?buildWeightedNativeSurfaceFrame({canonical_morphology_asset:asset},options):buildNativeSurfaceFrame({canonical_morphology_asset:asset},options);return{system,asset,surface};}

test('NormalBuffer produces measured three-band cel shading across front, three-quarter and side views',()=>{for(const view of ['front','three-quarter-right','side']){const{surface}=fixture({view}),guide=buildCelShadingDrawingGuide(surface),validation=validateCelShadingDrawingGuide(guide);assert.equal(validation.valid,true,`${view}:${validation.errors.join(',')}`);assert.equal(guide.visibility_root,surface.visibility.visibility_root);assert.equal(guide.normal_buffer_root,surface.visibility.buffer_roots.NormalBuffer);assert.ok(guide.measurements.visible_group_count>=3,view);assert.ok(guide.measurements.shadow_pixels>0,view);assert.ok(guide.measurements.highlight_pixels>0,view);assert.ok(guide.measurements.shadow_parts>0,view);assert.ok(guide.measurements.highlight_parts>0,view);assert.ok(guide.groups.head||guide.groups.torso,view);assert.ok(guide.lighting.shadow_threshold<guide.lighting.highlight_threshold,view);}});

test('Weighted FullBody DrawingIR carries evidence-bound cel shadow and highlight vector paths',()=>{const{surface}=fixture({view:'three-quarter-right',pose:'action',frame:60}),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir,{requireMeshSilhouette:true,requireHeadSurface:true,requireFaceSurface:true,requireHairSurface:true,requireGarmentSurface:true,requireCelShading:true});assert.equal(validation.valid,true,validation.errors.join(','));assert.ok(ir.cel_shading_drawing_guide_root);assert.equal(ir.cel_shading_policy,'normal-buffer-three-band-vector-cel-shading');const shadows=ir.operations.filter(op=>op.role==='cel-shadow'),highlights=ir.operations.filter(op=>op.role==='cel-highlight');assert.ok(shadows.length>0);assert.ok(highlights.length>0);for(const op of [...shadows,...highlights]){assert.ok(op.cel_shading_guide_root);assert.ok(op.cel_shading_group);assert.ok(op.cel_shading_part_root);assert.ok(op.d.includes('C '));}});

test('Legacy non-weighted FullBody DrawingIR keeps flat-color compatibility and does not silently activate cel shading',()=>{const{surface}=fixture({weighted:false}),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir);assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(ir.cel_shading_drawing_guide_root,undefined);assert.equal(ir.cel_shading_policy,'disabled-compatible');assert.equal(ir.operations.some(op=>op.role==='cel-shadow'||op.role==='cel-highlight'),false);});

test('Cel garment shadows follow explicit DrawingMesh deformation roles while skin shading remains surface-authoritative',()=>{const{surface}=fixture({view:'three-quarter-right',pose:'action',frame:60}),ir=compileFullBodyAnimeDrawingIR(surface),mesh=compileDrawingMeshIR(ir,{samplesPerCubic:3}),garmentShade=mesh.meshes.filter(item=>(item.role==='cel-shadow'||item.role==='cel-highlight')&&['garment-body-silhouette','continuous-sleeve','continuous-leg-garment'].includes(item.deformation_role)),skinShade=mesh.meshes.find(item=>(item.role==='cel-shadow'||item.role==='cel-highlight')&&item.deformation_role===item.role);assert.ok(garmentShade.length>0);assert.ok(skinShade);const controls=createPerformanceDrawingControls(mesh,{secondary:{hair_lag:.02,costume_lag:.018,breath:.012,overshoot:.01}}),deformed=applyDrawingCageDeformation(mesh,controls),byId=new Map(deformed.meshes.map(item=>[item.mesh_id,item]));assert.ok(garmentShade.some(item=>byId.get(item.mesh_id).deformation_summary.max_offset>0));assert.equal(byId.get(skinShade.mesh_id).deformation_summary.max_offset,0);});

test('Changing light direction changes cel shading root without changing canonical morphology or pose roots',()=>{const{surface}=fixture({view:'three-quarter-right',pose:'neutral',frame:0}),a=buildCelShadingDrawingGuide(surface),grammar=createSemanticAnimeVisualGrammar({lighting:{key_direction:[.48,.42,.76]}}),b=buildCelShadingDrawingGuide(surface,{grammar});assert.equal(a.native_surface_root,b.native_surface_root);assert.equal(a.posed_mesh_root,b.posed_mesh_root);assert.equal(a.visibility_root,b.visibility_root);assert.notEqual(a.semantic_grammar_root,b.semantic_grammar_root);assert.notEqual(a.guide_root,b.guide_root);});
