import assert from 'node:assert/strict';
import test from 'node:test';
import {createAnatomySystem} from '../src/anatomy.mjs';
import {compileFullBodyArtDirectedMorphology} from '../src/lower-body-morphology.mjs';
import {buildNativeSurfaceFrame} from '../src/native-surface-runtime.mjs';
import {buildWeightedNativeSurfaceFrame} from '../src/weighted-native-surface-runtime.mjs';
import {buildFaceSurfaceDrawingGuide,validateFaceSurfaceDrawingGuide} from '../src/face-surface-drawing.mjs';
import {compileFullBodyAnimeDrawingIR,validateFullBodyAnimeDrawingIR} from '../src/full-body-drawing-ir.mjs';

function fixture({view='front',pose='neutral',frame=0,weighted=true}={}){const system=createAnatomySystem({seed:'phase6-6-face-surface'}),asset=compileFullBodyArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),options={view,pose,frame,totalFrames:120,width:320,height:180,scale:.52},surface=weighted?buildWeightedNativeSurfaceFrame({canonical_morphology_asset:asset},options):buildNativeSurfaceFrame({canonical_morphology_asset:asset},options);return{system,asset,surface};}
const approx=(a,b,eps=.01)=>Math.abs(Number(a)-Number(b))<=eps;

test('Front, three-quarter and profile face guides resolve real skull surface feature samples',()=>{for(const view of ['front','three-quarter-right','side']){const{surface}=fixture({view}),guide=buildFaceSurfaceDrawingGuide(surface),validation=validateFaceSurfaceDrawingGuide(guide);assert.equal(validation.valid,true,`${view}:${validation.errors.join(',')}`);assert.equal(guide.visibility_root,surface.visibility.visibility_root);assert.equal(guide.pose_root,surface.posed_skeleton.pose_root);assert.equal(guide.missing_features.length,0);assert.equal(guide.unresolved_features.length,0);assert.ok(guide.visible_eyes.length>=(view==='side'?1:2),view);}});

test('Three-quarter eye DrawingIR centers are sourced from Visibility feature_samples, not guessed view ratios',()=>{const{surface}=fixture({view:'three-quarter-right',pose:'alert',frame:60}),guide=buildFaceSurfaceDrawingGuide(surface),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir,{requireMeshSilhouette:true,requireFaceSurface:true});assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(ir.face_surface_drawing_guide_root,guide.guide_root);for(const side of ['left','right']){const entry=guide.features[`${side}_eye`],eye=ir.operations.find(op=>op.id===`eye-white-${side}`);if(entry.visible){assert.ok(eye,side);assert.ok(approx(eye.cx,entry.screen_position[0]),`${side}:x:${eye.cx}:${entry.screen_position[0]}`);assert.ok(approx(eye.cy,entry.screen_position[1]),`${side}:y:${eye.cy}:${entry.screen_position[1]}`);assert.equal(eye.face_surface_entry_root,entry.entry_root);}else assert.equal(eye,undefined,side);}});

test('Profile DrawingIR follows the visibility-selected near eye side',()=>{const{surface}=fixture({view:'side'}),guide=buildFaceSurfaceDrawingGuide(surface),ir=compileFullBodyAnimeDrawingIR(surface),visibleSide=guide.visible_eyes[0].replace('_eye',''),visibleEye=ir.operations.find(op=>op.id===`eye-white-${visibleSide}`),hiddenSide=visibleSide==='left'?'right':'left';assert.equal(guide.visible_eyes.length,1);assert.ok(visibleEye,visibleSide);assert.equal(visibleEye.face_surface_entry_root,guide.features[`${visibleSide}_eye`].entry_root);assert.equal(ir.operations.find(op=>op.id===`eye-white-${hiddenSide}`),undefined);});

test('Nose and mouth drawing are bound to actual face surface attachment roots',()=>{const{surface}=fixture({view:'front'}),guide=buildFaceSurfaceDrawingGuide(surface),ir=compileFullBodyAnimeDrawingIR(surface),nose=ir.operations.find(op=>op.id==='nose-bridge'),mouth=ir.operations.find(op=>op.id==='mouth-line'||op.id==='mouth-open');assert.ok(nose?.face_surface_entry_root);assert.ok(mouth?.face_surface_entry_root);assert.deepEqual(nose.a,guide.features.nose_bridge.screen_position);assert.deepEqual(nose.b,guide.features.nose_tip.screen_position);});

test('Legacy non-weighted full-body DrawingIR keeps previous face path without silently gaining surface-face authority',()=>{const{surface}=fixture({weighted:false}),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir);assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(ir.face_surface_drawing_guide_root,undefined);assert.equal(ir.face_surface_policy,'disabled-compatible');});
