import assert from 'node:assert/strict';
import test from 'node:test';
import {createAnatomySystem} from '../src/anatomy.mjs';
import {compileArtDirectedMorphology} from '../src/semantic-anatomy.mjs';
import {compileFullBodyArtDirectedMorphology} from '../src/lower-body-morphology.mjs';
import {buildNativeSurfaceFrame} from '../src/native-surface-runtime.mjs';
import {compileFullBodyCharacterDrawing,validateFullBodyCharacterDrawing} from '../src/full-body-drawing.mjs';
import {compileFullBodyAnimeDrawingIR,validateFullBodyAnimeDrawingIR} from '../src/full-body-drawing-ir.mjs';
import {compileDrawingMeshIR,validateDrawingMeshIR,applyDrawingCageDeformation,drawingMeshToDrawingIR,createPerformanceDrawingControls} from '../src/drawing-mesh-deformation.mjs';

const make=(view='front',pose='neutral',frame=0)=>{const system=createAnatomySystem({seed:`phase6-6-full-body-${view}-${pose}`}),asset=compileFullBodyArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),surface=buildNativeSurfaceFrame({canonical_morphology_asset:asset},{view,pose,frame,totalFrames:120,width:640,height:360,scale:.52});return{system,asset,surface};};

test('Upper-body-only canonical asset cannot enter full-body drawing path',()=>{const system=createAnatomySystem({seed:'phase6-6-upper-only-negative'}),asset=compileArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),surface=buildNativeSurfaceFrame({canonical_morphology_asset:asset},{view:'front',pose:'neutral',frame:0,totalFrames:1,width:640,height:360,scale:.52});assert.throws(()=>compileFullBodyCharacterDrawing(surface),error=>error?.code==='FULL_BODY_CANONICAL_LOWER_BODY_REQUIRED');});

test('Front, three-quarter and profile full-body drawings are derived from canonical lower-body bones',()=>{for(const view of ['front','three-quarter-right','side']){const{surface}=make(view,view==='front'?'neutral':'alert'),drawing=compileFullBodyCharacterDrawing(surface),validation=validateFullBodyCharacterDrawing(drawing);assert.equal(validation.valid,true,`${view}:${validation.errors.join(',')}`);assert.equal(drawing.lower_body.legs.length,2);assert.equal(drawing.lower_body_status,'represented-in-canonical-morphology-v0.2-candidate');assert.ok(drawing.full_body_drawing_certificate_root);for(const leg of drawing.lower_body.legs){assert.equal(leg.full_contour.length,10);assert.equal(leg.foot.contour.length,6);assert.ok(leg.canonical_lengths.thigh>0);assert.ok(leg.canonical_lengths.shin>0);assert.ok(leg.canonical_lengths.foot>0);}}});

test('Full-body DrawingIR carries two canonical legs and feet without granting renderer anatomy authority',()=>{const{surface}=make('three-quarter-right','action',60),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir);assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(ir.lower_body_status,'represented-in-canonical-morphology-v0.2-candidate');assert.equal(ir.operations.filter(op=>op.role==='continuous-leg-garment').length,2);assert.equal(ir.operations.filter(op=>op.role==='foot-silhouette').length,2);assert.equal(ir.backend_contract.identity_authority,false);assert.equal(ir.backend_contract.geometry_authority,false);assert.equal(ir.backend_contract.rasterizer_authority,false);});

test('Full-body DrawingIR survives bounded mesh/cage deformation without triangle inversion',()=>{const{surface}=make('three-quarter-right','action',60),ir=compileFullBodyAnimeDrawingIR(surface),mesh=compileDrawingMeshIR(ir,{samplesPerCubic:3}),meshValidation=validateDrawingMeshIR(mesh);assert.equal(meshValidation.valid,true,meshValidation.errors.join(','));assert.ok(mesh.meshes.some(item=>item.role==='continuous-leg-garment'));assert.ok(mesh.meshes.some(item=>item.role==='foot-silhouette'));const controls=createPerformanceDrawingControls(mesh,surface.performance),deformed=applyDrawingCageDeformation(mesh,controls),rebuilt=drawingMeshToDrawingIR(ir,deformed),rebuiltValidation=validateFullBodyAnimeDrawingIR(rebuilt);assert.equal(rebuiltValidation.valid,true,rebuiltValidation.errors.join(','));assert.ok(deformed.meshes.every(item=>item.deformation_summary.triangle_inversions===0));assert.equal(rebuilt.lower_body_status,'represented-in-canonical-morphology-v0.2-candidate');});
