import assert from 'node:assert/strict';
import test from 'node:test';
import {createAnatomySystem} from '../src/anatomy.mjs';
import {compileFullBodyArtDirectedMorphology} from '../src/lower-body-morphology.mjs';
import {buildNativeSurfaceFrame} from '../src/native-surface-runtime.mjs';
import {buildWeightedNativeSurfaceFrame} from '../src/weighted-native-surface-runtime.mjs';
import {buildMeshSilhouetteDrawingGuide} from '../src/mesh-silhouette-drawing.mjs';
import {buildGarmentSurfaceDrawingGuide,validateGarmentSurfaceDrawingGuide} from '../src/garment-surface-drawing.mjs';
import {compileFullBodyAnimeDrawingIR,validateFullBodyAnimeDrawingIR} from '../src/full-body-drawing-ir.mjs';
import {compileDrawingMeshIR,createPerformanceDrawingControls,applyDrawingCageDeformation} from '../src/drawing-mesh-deformation.mjs';

function fixture({view='front',pose='neutral',frame=0,weighted=true}={}){const system=createAnatomySystem({seed:'phase6-6-garment-surface'}),asset=compileFullBodyArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),options={view,pose,frame,totalFrames:120,width:320,height:180,scale:.52},surface=weighted?buildWeightedNativeSurfaceFrame({canonical_morphology_asset:asset},options):buildNativeSurfaceFrame({canonical_morphology_asset:asset},options);return{system,asset,surface};}

function assertSleeveState(guide,side){const state=guide.visibility[`sleeve-${side}`],section=guide.sleeves[side];assert.ok(['visible','occluded'].includes(state),`${side}:${state}`);if(state==='visible'){assert.ok(section?.parts?.length,side);assert.ok(section.parts.every(part=>part.clearance_area_ratio>1),side);}else assert.equal(section,null,side);}

test('Garment guide adds measured ease over real torso and preserves visible/occluded sleeve semantics',()=>{for(const view of ['front','three-quarter-right','side']){const{surface}=fixture({view}),mesh=buildMeshSilhouetteDrawingGuide(surface),guide=buildGarmentSurfaceDrawingGuide(surface,mesh),validation=validateGarmentSurfaceDrawingGuide(guide);assert.equal(validation.valid,true,`${view}:${validation.errors.join(',')}`);assert.equal(guide.mesh_silhouette_guide_root,mesh.guide_set_root);assert.equal(guide.large_form_authority,'GarmentSurfaceDrawingGuide');assert.equal(guide.secondary_motion_authority,'DrawingMeshCage');assert.ok(guide.measurements.minimum_clearance_area_ratio>1,view);assert.ok(guide.torso.parts.every(part=>part.clearance_area_ratio>1));assertSleeveState(guide,'left');assertSleeveState(guide,'right');assert.equal(guide.measurements.visible_sleeve_count+guide.measurements.occluded_sleeve_count,2);assert.ok(guide.collar.left.length>=4&&guide.collar.right.length>=4);}});

test('Weighted FullBody DrawingIR binds coat, visible sleeves, collar and seam to GarmentSurface guide',()=>{const{surface}=fixture({view:'three-quarter-right',pose:'action',frame:60}),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir,{requireMeshSilhouette:true,requireHeadSurface:true,requireFaceSurface:true,requireHairSurface:true,requireGarmentSurface:true});assert.equal(validation.valid,true,validation.errors.join(','));assert.ok(ir.garment_surface_drawing_guide_root);assert.equal(ir.garment_large_form_authority,'GarmentSurfaceDrawingGuide');assert.equal(ir.garment_secondary_motion_authority,'DrawingMeshCage');for(const op of ir.operations.filter(op=>op.role==='garment-body-silhouette'||op.role==='continuous-sleeve')){assert.ok(op.garment_surface_guide_root,op.id);assert.ok(op.garment_surface_part_root,op.id);assert.equal(op.garment_secondary_motion_authority,'DrawingMeshCage');}for(const side of ['left','right']){const state=ir.garment_visibility[`sleeve-${side}`],ops=ir.operations.filter(op=>op.mesh_silhouette_group===`arm-${side}`&&op.role==='continuous-sleeve');if(state==='visible')assert.ok(ops.length>=1,side);else assert.equal(ops.length,0,side);}for(const id of ['collar-left','collar-right','center-seam'])assert.ok(ir.operations.find(op=>op.id===id)?.garment_surface_guide_root,id);});

test('DrawingMesh owns garment secondary motion after GarmentSurface establishes large form',()=>{const{surface}=fixture({view:'three-quarter-right',pose:'action',frame:60}),ir=compileFullBodyAnimeDrawingIR(surface),mesh=compileDrawingMeshIR(ir),controls=createPerformanceDrawingControls(mesh,{secondary:{hair_lag:.02,costume_lag:.018,breath:.012,overshoot:.01}}),deformed=applyDrawingCageDeformation(mesh,controls),garment=deformed.meshes.filter(item=>item.role==='garment-body-silhouette'||item.role==='continuous-sleeve');assert.ok(garment.length>=1);assert.ok(garment.some(item=>item.deformation_summary.max_offset>0));assert.ok(garment.every(item=>item.deformation_summary.triangle_inversions===0));});

test('Legacy non-weighted DrawingIR does not silently activate GarmentSurface authority',()=>{const{surface}=fixture({weighted:false}),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir);assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(ir.garment_surface_drawing_guide_root,undefined);assert.equal(ir.garment_surface_policy,'disabled-compatible');assert.equal(ir.operations.find(op=>op.id==='garment-body')?.garment_surface_guide_root,undefined);assert.equal(ir.operations.find(op=>op.id==='collar-left')?.garment_surface_guide_root,undefined);});

test('Weighted A/B may disable MeshSilhouette without accidentally activating dependent GarmentSurface',()=>{const{surface}=fixture({weighted:true}),ir=compileFullBodyAnimeDrawingIR(surface,{useMeshSilhouette:false}),validation=validateFullBodyAnimeDrawingIR(ir);assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(ir.mesh_silhouette_policy,'disabled-compatible');assert.equal(ir.mesh_silhouette_guide_root,null);assert.equal(ir.garment_surface_policy,'disabled-compatible');assert.equal(ir.garment_surface_drawing_guide_root,undefined);});

test('Explicit GarmentSurface request fails closed when MeshSilhouette is explicitly disabled',()=>{const{surface}=fixture({weighted:true});assert.throws(()=>compileFullBodyAnimeDrawingIR(surface,{useMeshSilhouette:false,useGarmentSurface:true}),error=>error?.code==='GARMENT_SURFACE_REQUIRES_MESH_SILHOUETTE');});
