import assert from 'node:assert/strict';
import test from 'node:test';
import {createAnatomySystem} from '../src/anatomy.mjs';
import {compileFullBodyArtDirectedMorphology} from '../src/lower-body-morphology.mjs';
import {buildNativeSurfaceFrame} from '../src/native-surface-runtime.mjs';
import {buildWeightedNativeSurfaceFrame} from '../src/weighted-native-surface-runtime.mjs';
import {buildHairSurfaceDrawingGuide,validateHairSurfaceDrawingGuide} from '../src/hair-surface-drawing.mjs';
import {compileFullBodyAnimeDrawingIR,validateFullBodyAnimeDrawingIR} from '../src/full-body-drawing-ir.mjs';

function fixture({view='front',pose='neutral',frame=0,weighted=true}={}){const system=createAnatomySystem({seed:'phase6-6-hair-surface'}),asset=compileFullBodyArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),options={view,pose,frame,totalFrames:120,width:320,height:180,scale:.52},surface=weighted?buildWeightedNativeSurfaceFrame({canonical_morphology_asset:asset},options):buildNativeSurfaceFrame({canonical_morphology_asset:asset},options);return{system,asset,surface};}

test('Front, three-quarter and profile hair guides remain scalp-rooted through the posed skull',()=>{for(const view of ['front','three-quarter-right','side']){const{surface}=fixture({view}),guide=buildHairSurfaceDrawingGuide(surface),validation=validateHairSurfaceDrawingGuide(guide);assert.equal(validation.valid,true,`${view}:${validation.errors.join(',')}`);assert.equal(guide.pose_root,surface.posed_skeleton.pose_root);assert.equal(guide.visibility_root,surface.visibility.visibility_root);assert.equal(guide.scalp_attachment_root,surface.asset.surface_attachments.attachment_root);assert.equal(guide.roots_preserved,true);assert.ok(guide.crown.contour.length>=3);assert.ok(guide.fringe.contour.length>=3);assert.ok(guide.side_near.contour.length>=3);assert.ok(guide.side_far.contour.length>=3);}});

test('Secondary hair lag changes guide tips and contour while preserving scalp roots exactly',()=>{const{surface}=fixture({view:'three-quarter-right',pose:'neutral',frame:0}),zero={...surface,performance:{...surface.performance,secondary:{...surface.performance.secondary,hair_lag:0}}},lagged={...surface,performance:{...surface.performance,secondary:{...surface.performance.secondary,hair_lag:.024}}},a=buildHairSurfaceDrawingGuide(zero),b=buildHairSurfaceDrawingGuide(lagged);assert.equal(a.roots_preserved,true);assert.equal(b.roots_preserved,true);assert.deepEqual(a.scalp_roots.map(item=>item.screen_position),b.scalp_roots.map(item=>item.screen_position));assert.notEqual(a.crown.contour_root,b.crown.contour_root);const curveA=a.masses[0].curves[0],curveB=b.masses[0].curves[0];assert.deepEqual(curveA.local_points[0],curveB.local_points[0]);assert.notDeepEqual(curveA.local_points.at(-1),curveB.local_points.at(-1));});

test('Weighted FullBody DrawingIR binds crown/fringe/side hair paths to scalp-derived contour roots',()=>{const{surface}=fixture({view:'three-quarter-right',pose:'action',frame:60}),guide=buildHairSurfaceDrawingGuide(surface),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir,{requireMeshSilhouette:true,requireFaceSurface:true,requireHairSurface:true});assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(ir.hair_surface_drawing_guide_root,guide.guide_root);for(const id of ['hair-crown','hair-fringe','hair-side-near']){const op=ir.operations.find(item=>item.id===id);assert.ok(op,id);assert.ok(op.hair_surface_contour_root,id);assert.ok(op.hair_surface_root_attachment_ids?.length,id);}const far=ir.operations.find(item=>item.id==='hair-side-far');if(far)assert.ok(far.hair_surface_contour_root);const highlight=ir.operations.find(item=>item.id==='hair-highlight');assert.ok(highlight?.hair_surface_contour_root);});

test('Legacy non-weighted FullBody DrawingIR keeps old hair construction without scalp surface authority',()=>{const{surface}=fixture({weighted:false}),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir);assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(ir.hair_surface_drawing_guide_root,undefined);assert.equal(ir.hair_surface_policy,'disabled-compatible');assert.ok(ir.operations.filter(op=>op.id.startsWith('hair-')).every(op=>!op.hair_surface_contour_root));});
