import assert from 'node:assert/strict';
import test from 'node:test';
import {createAnatomySystem} from '../src/anatomy.mjs';
import {compileArtDirectedMorphology} from '../src/semantic-anatomy.mjs';
import {extendArtDirectedMorphologyWithLowerBody} from '../src/lower-body-morphology.mjs';
import {performanceStateForFrame,solveKinematics} from '../src/kinematics.mjs';

function bonesById(posed){return new Map((posed?.bones??[]).map(bone=>[bone.id,bone]));}
function vecDelta(a,b){return Math.hypot(...a.map((value,index)=>Number(value)-Number(b[index])));}

test('Upper-body assets keep legacy performance behavior while full-body assets activate bounded lower-body joints',()=>{const system=createAnatomySystem({seed:'phase6-6-lower-body-performance'}),upper=compileArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),full=extendArtDirectedMorphologyWithLowerBody(upper,system.genome,{surface_resolution:'property',certificate_mode:'property'}),upperState=performanceStateForFrame(upper,{view:'front',pose:'action',frame:60,totalFrames:120}),fullState=performanceStateForFrame(full,{view:'front',pose:'action',frame:60,totalFrames:120});assert.equal(upperState.lower_body_active,false);assert.equal(fullState.lower_body_active,true);for(const id of ['hip-left','thigh-left','knee-left','ankle-left','hip-right','thigh-right','knee-right','ankle-right'])assert.ok(fullState.joint_rotations[id],id);assert.equal(upperState.joint_rotations['hip-left'],undefined);});

test('Lower-body performance changes pose without changing canonical bone lengths',()=>{const system=createAnatomySystem({seed:'phase6-6-lower-body-fk'}),upper=compileArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),full=extendArtDirectedMorphologyWithLowerBody(upper,system.genome,{surface_resolution:'property',certificate_mode:'property'}),neutral=solveKinematics(full,performanceStateForFrame(full,{view:'three-quarter-right',pose:'neutral',frame:0,totalFrames:120})),action=solveKinematics(full,performanceStateForFrame(full,{view:'three-quarter-right',pose:'action',frame:60,totalFrames:120})),neutralBones=bonesById(neutral),actionBones=bonesById(action);assert.equal(neutral.bone_lengths_pose_invariant,true);assert.equal(action.bone_lengths_pose_invariant,true);for(const id of ['thigh-left','shin-left','foot-left','thigh-right','shin-right','foot-right']){assert.equal(neutralBones.get(id).length,actionBones.get(id).length,id);assert.ok(Math.abs(actionBones.get(id).length-neutralBones.get(id).length)<1e-12,id);}const moved=['thigh-left','knee-left','ankle-left','thigh-right','knee-right','ankle-right'].some(id=>{const a=neutralBones.get(id)?.world_end,b=actionBones.get(id)?.world_end;return a&&b&&vecDelta(a,b)>1e-5;});assert.equal(moved,true);});
