import assert from 'node:assert/strict';
import test from 'node:test';
import {createAnatomySystem} from '../src/anatomy.mjs';
import {compileArtDirectedMorphology} from '../src/semantic-anatomy.mjs';
import {compileFullBodyArtDirectedMorphology,extendArtDirectedMorphologyWithLowerBody,validateLowerBodyCertificate} from '../src/lower-body-morphology.mjs';

function source(seed='phase6-6-lower-body'){const system=createAnatomySystem({seed}),base=compileArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'});return{system,base};}

test('Lower-body extension preserves identity/genome authority while adding canonical bilateral leg chains',()=>{const{system,base}=source(),full=extendArtDirectedMorphologyWithLowerBody(base,system.genome,{surface_resolution:'property',certificate_mode:'property'}),validation=validateLowerBodyCertificate(full.lower_body_certificate),bones=new Map(full.skeleton.bones.map(item=>[item.id,item]));assert.equal(validation.valid,true,validation.failures.join(','));assert.equal(full.identity_root,base.identity_root);assert.equal(full.genome_root,base.genome_root);assert.equal(full.lower_body_status,'represented-in-canonical-morphology-v0.2-candidate');for(const id of ['hip-left','thigh-left','knee-left','shin-left','ankle-left','foot-left','hip-right','thigh-right','knee-right','shin-right','ankle-right','foot-right'])assert.ok(bones.has(id),id);assert.equal(bones.get('thigh-left').length,bones.get('thigh-right').length);assert.equal(bones.get('shin-left').length,bones.get('shin-right').length);assert.equal(bones.get('foot-left').length,bones.get('foot-right').length);assert.ok(full.proportions.full_height>full.proportions.height);});

test('Full-body canonical field and mesh contain measured leg/foot geometry rather than renderer-only placeholders',()=>{const{system}=source('phase6-6-lower-body-fields'),full=compileFullBodyArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),fieldIds=new Set(full.continuous_morphology_field.fields.map(item=>item.field_id)),regions=new Set(full.canonical_surface_mesh.region_ids),weights=full.canonical_surface_mesh.bone_weights;for(const id of ['HipField:left','ThighField:left','KneeField:left','ShinField:left','FootField:left','HipField:right','ThighField:right','KneeField:right','ShinField:right','FootField:right'])assert.ok(fieldIds.has(id),id);for(const region of ['hip','thigh','knee','shin','foot'])assert.ok(regions.has(region),region);assert.ok(weights.some(item=>item['thigh-left']));assert.ok(weights.some(item=>item['shin-right']));assert.ok(weights.some(item=>item['foot-left']));assert.equal(full.canonical_surface_mesh.connected_components.length,1);assert.equal(full.canonical_surface_mesh.topology_report.surface_self_intersection_count,0);});

test('Lower-body certificate is evidence-bearing and does not reduce to boolean declarations',()=>{const{system}=source('phase6-6-lower-body-certificate'),full=compileFullBodyArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),certificate=full.lower_body_certificate;for(const [name,gate] of Object.entries(certificate.gates)){assert.notEqual(typeof gate,'boolean',name);assert.ok(gate.measurement!==undefined,name);assert.ok(gate.allowed!==undefined,name);assert.ok(gate.method,name);assert.ok(gate.evidence_root,name);assert.equal(gate.pass,true,name);}});
