import assert from 'node:assert/strict';
import test from 'node:test';
import {createAnatomySystem} from '../src/anatomy.mjs';
import {compileFullBodyArtDirectedMorphology} from '../src/lower-body-morphology.mjs';
import {buildNativeSurfaceFrame} from '../src/native-surface-runtime.mjs';
import {buildWeightedNativeSurfaceFrame} from '../src/weighted-native-surface-runtime.mjs';
import {buildMeshSilhouetteDrawingGuide,validateMeshSilhouetteDrawingGuide} from '../src/mesh-silhouette-drawing.mjs';
import {compileFullBodyAnimeDrawingIR,validateFullBodyAnimeDrawingIR} from '../src/full-body-drawing-ir.mjs';

function fixture({view='front',pose='neutral',frame=0,weighted=true}={}){const system=createAnatomySystem({seed:'phase6-6-mesh-silhouette'}),asset=compileFullBodyArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),options={view,pose,frame,totalFrames:120,width:320,height:180,scale:.52},surface=weighted?buildWeightedNativeSurfaceFrame({canonical_morphology_asset:asset},options):buildNativeSurfaceFrame({canonical_morphology_asset:asset},options);return{system,asset,surface};}

test('Weighted posed mesh yields evidence-bound multipart visible contours for torso, bilateral arms, legs and feet',()=>{const{surface}=fixture(),guide=buildMeshSilhouetteDrawingGuide(surface,{epsilon:1.1}),validation=validateMeshSilhouetteDrawingGuide(guide,{requireFullBody:true});assert.equal(validation.valid,true,validation.errors.join(','));assert.deepEqual(guide.missing_groups,[]);assert.equal(guide.surface_weighting_root,surface.surface_weighting_root);for(const group of ['torso','arm-left','arm-right','leg-left','leg-right','foot-left','foot-right']){const item=guide.guides[group];assert.ok(item,group);assert.ok(item.guide_root,group);assert.ok(item.source_pixel_count>0,group);assert.ok(item.contour.length>=6,group);assert.ok(item.area>0,group);assert.equal(item.part_count,item.parts.length,group);assert.ok(item.parts.length>=1,group);for(const part of item.parts){assert.ok(part.part_root,`${group}:${part.part_id}`);assert.ok(part.contour.length>=6,`${group}:${part.part_id}`);}}});

test('Weighted full-body DrawingIR automatically binds torso and final limb visible parts to MeshSilhouetteGuide roots',()=>{const{surface}=fixture({view:'three-quarter-right',pose:'action',frame:60}),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir,{requireMeshSilhouette:true});assert.equal(validation.valid,true,validation.errors.join(','));assert.ok(ir.mesh_silhouette_guide_root);assert.equal(ir.mesh_silhouette_policy,'weighted-posed-mesh-visible-surface-multipart');const requiredGroups=new Set(['torso','arm-left','arm-right','leg-left','leg-right','foot-left','foot-right']),seen=new Set();for(const role of ['garment-body-silhouette','continuous-sleeve','continuous-leg-garment','foot-silhouette'])for(const op of ir.operations.filter(item=>item.role===role)){assert.ok(op.mesh_silhouette_guide_root,`${role}:${op.id}`);assert.ok(op.mesh_silhouette_group,`${role}:${op.id}`);assert.ok(op.mesh_silhouette_part_root,`${role}:${op.id}`);seen.add(op.mesh_silhouette_group);}assert.deepEqual(seen,requiredGroups);});

test('Legacy non-weighted full-body surface keeps compatibility path and does not silently activate mesh silhouette authority',()=>{const{surface}=fixture({weighted:false}),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir);assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(ir.mesh_silhouette_guide_root,null);assert.equal(ir.mesh_silhouette_policy,'disabled-compatible');assert.ok(ir.operations.filter(op=>['garment-body-silhouette','continuous-sleeve','continuous-leg-garment','foot-silhouette'].includes(op.role)).every(op=>!op.mesh_silhouette_guide_root&&!op.mesh_silhouette_group&&!op.mesh_silhouette_part_root));});

test('Mesh silhouette evidence changes with a real lower-body/upper-body performance state while canonical morphology remains the same',()=>{const neutral=fixture({view:'three-quarter-right',pose:'neutral',frame:0}).surface,action=fixture({view:'three-quarter-right',pose:'action',frame:60}).surface,a=buildMeshSilhouetteDrawingGuide(neutral),b=buildMeshSilhouetteDrawingGuide(action);assert.equal(a.canonical_mesh_root,b.canonical_mesh_root);assert.equal(a.surface_weighting_root,b.surface_weighting_root);assert.notEqual(a.posed_mesh_root,b.posed_mesh_root);assert.notEqual(a.guide_set_root,b.guide_set_root);});
