import assert from 'node:assert/strict';
import test from 'node:test';
import {createAnatomySystem} from '../src/anatomy.mjs';
import {compileFullBodyArtDirectedMorphology} from '../src/lower-body-morphology.mjs';
import {buildNativeSurfaceFrame} from '../src/native-surface-runtime.mjs';
import {buildWeightedNativeSurfaceFrame} from '../src/weighted-native-surface-runtime.mjs';
import {classifyBodySurfaceTriangle} from '../src/body-surface-semantic-groups.mjs';
import {buildMeshSilhouetteDrawingGuide,validateMeshSilhouetteDrawingGuide} from '../src/mesh-silhouette-drawing.mjs';
import {compileFullBodyAnimeDrawingIR,validateFullBodyAnimeDrawingIR} from '../src/full-body-drawing-ir.mjs';

const groups=['torso','neck','arm-left','arm-right','hand-left','hand-right','leg-left','leg-right','foot-left','foot-right'];
function fixture({view='front',pose='neutral',frame=0,weighted=true}={}){const system=createAnatomySystem({seed:'phase6-6-mesh-silhouette'}),asset=compileFullBodyArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'}),options={view,pose,frame,totalFrames:120,width:320,height:180,scale:.52},surface=weighted?buildWeightedNativeSurfaceFrame({canonical_morphology_asset:asset},options):buildNativeSurfaceFrame({canonical_morphology_asset:asset},options);return{system,asset,surface};}
function hideVisibleGroup(surface,target){const visible=new Uint8Array(surface.visibility.VisibilityBuffer),surfaceId=new Int32Array(surface.visibility.SurfaceIdBuffer);for(let pixel=0;pixel<visible.length;pixel++){if(!visible[pixel])continue;const triangleIndex=Number(surfaceId[pixel]);if(triangleIndex<0)continue;const group=classifyBodySurfaceTriangle(surface.posed_mesh,surface.posed_mesh.triangles[triangleIndex]);if(group===target){visible[pixel]=0;surfaceId[pixel]=-1;}}return{...surface,visibility:{...surface.visibility,VisibilityBuffer:visible,SurfaceIdBuffer:surfaceId,visibility_root:`${surface.visibility.visibility_root}:occlusion-test:${target}`}};}

test('Weighted posed mesh distinguishes canonical presence from current visibility',()=>{for(const view of ['front','three-quarter-right','side']){const{surface}=fixture({view}),guide=buildMeshSilhouetteDrawingGuide(surface,{epsilon:1.1}),validation=validateMeshSilhouetteDrawingGuide(guide,{requireFullBody:true});assert.equal(validation.valid,true,`${view}:${validation.errors.join(',')}`);assert.deepEqual(guide.missing_canonical_groups,[]);assert.equal(guide.surface_weighting_root,surface.surface_weighting_root);for(const group of groups){assert.ok(guide.canonical_group_triangle_counts[group]>0,`${view}:${group}:canonical`);assert.ok(guide.visible_groups.includes(group)||guide.occluded_groups.includes(group),`${view}:${group}:resolved`);const item=guide.guides[group];if(item){assert.ok(item.guide_root,group);assert.ok(item.source_pixel_count>0,group);assert.ok(item.contour.length>=6,group);assert.equal(item.part_count,item.parts.length,group);for(const part of item.parts){assert.ok(part.part_root,`${group}:${part.part_id}`);assert.ok(part.contour.length>=6,`${group}:${part.part_id}`);}}}}});

test('Weighted FullBody DrawingIR binds every visible group and omits canonically occluded groups',()=>{const{surface}=fixture({view:'three-quarter-right',pose:'action',frame:60}),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir,{requireMeshSilhouette:true,requireHeadSurface:true,requireFaceSurface:true,requireHairSurface:true,requireGarmentSurface:true,requireCelShading:true});assert.equal(validation.valid,true,validation.errors.join(','));assert.ok(ir.mesh_silhouette_guide_root);const seen=new Set();for(const role of ['garment-body-silhouette','neck','continuous-sleeve','hand-silhouette','continuous-leg-garment','foot-silhouette'])for(const op of ir.operations.filter(item=>item.role===role)){assert.ok(op.mesh_silhouette_guide_root,`${role}:${op.id}`);assert.ok(op.mesh_silhouette_group,`${role}:${op.id}`);assert.ok(op.mesh_silhouette_part_root,`${role}:${op.id}`);seen.add(op.mesh_silhouette_group);}for(const group of ir.mesh_silhouette_visible_groups)assert.ok(seen.has(group),`visible:${group}`);for(const group of ir.mesh_silhouette_occluded_groups)assert.equal(seen.has(group),false,`occluded:${group}`);assert.equal(new Set([...ir.mesh_silhouette_visible_groups,...ir.mesh_silhouette_occluded_groups]).size,groups.length);});

test('Legacy non-weighted full-body surface keeps compatibility paths without mesh silhouette authority',()=>{const{surface}=fixture({weighted:false}),ir=compileFullBodyAnimeDrawingIR(surface),validation=validateFullBodyAnimeDrawingIR(ir);assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(ir.mesh_silhouette_guide_root,null);assert.equal(ir.mesh_silhouette_policy,'disabled-compatible');assert.ok(ir.operations.filter(op=>['garment-body-silhouette','neck','continuous-sleeve','hand-silhouette','continuous-leg-garment','foot-silhouette'].includes(op.role)).every(op=>!op.mesh_silhouette_guide_root&&!op.mesh_silhouette_group&&!op.mesh_silhouette_part_root));});

test('Canonical-present but fully occluded arm is omitted instead of falling back to a legacy sleeve',()=>{const{surface}=fixture({view:'three-quarter-right',pose:'neutral'}),hidden=hideVisibleGroup(surface,'arm-right'),guide=buildMeshSilhouetteDrawingGuide(hidden),guideValidation=validateMeshSilhouetteDrawingGuide(guide,{requireFullBody:true});assert.equal(guideValidation.valid,true,guideValidation.errors.join(','));assert.ok(guide.canonical_group_triangle_counts['arm-right']>0);assert.ok(guide.occluded_groups.includes('arm-right'));assert.equal(guide.guides['arm-right'],undefined);const ir=compileFullBodyAnimeDrawingIR(hidden),validation=validateFullBodyAnimeDrawingIR(ir,{requireMeshSilhouette:true,requireHeadSurface:true,requireFaceSurface:true,requireHairSurface:true,requireGarmentSurface:true,requireCelShading:true});assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(ir.operations.some(op=>op.id==='sleeve-right'||op.id.startsWith('sleeve-right-visible-')),false);assert.equal(ir.garment_visibility['sleeve-right'],'occluded');});

test('Mesh silhouette changes with performance while canonical morphology and weighting authority stay fixed',()=>{const neutral=fixture({view:'three-quarter-right',pose:'neutral',frame:0}).surface,action=fixture({view:'three-quarter-right',pose:'action',frame:60}).surface,a=buildMeshSilhouetteDrawingGuide(neutral),b=buildMeshSilhouetteDrawingGuide(action);assert.equal(a.canonical_mesh_root,b.canonical_mesh_root);assert.equal(a.surface_weighting_root,b.surface_weighting_root);assert.notEqual(a.posed_mesh_root,b.posed_mesh_root);assert.notEqual(a.guide_set_root,b.guide_set_root);});
