import assert from 'node:assert/strict';
import test from 'node:test';
import {createAnatomySystem} from '../src/anatomy.mjs';
import {compileFullBodyArtDirectedMorphology} from '../src/lower-body-morphology.mjs';
import {applyFieldGuidedSurfaceWeights,validateFieldGuidedSurfaceWeights} from '../src/surface-weighting.mjs';
import {buildWeightedNativeSurfaceFrame,validateWeightedNativeSurfaceFrame} from '../src/weighted-native-surface-runtime.mjs';

function full(seed='phase6-6-surface-weighting'){const system=createAnatomySystem({seed}),asset=compileFullBodyArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'});return{system,asset};}

test('Field-guided weighting preserves canonical geometry while creating normalized multi-bone surface weights',()=>{const{asset}=full(),weighted=applyFieldGuidedSurfaceWeights(asset.canonical_surface_mesh,asset.continuous_morphology_field),validation=validateFieldGuidedSurfaceWeights(weighted,{requireMultiInfluence:true});assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(weighted.source_mesh_root,asset.canonical_surface_mesh.mesh_root);assert.notEqual(weighted.mesh_root,asset.canonical_surface_mesh.mesh_root);assert.equal(weighted.vertices.length,asset.canonical_surface_mesh.vertices.length);assert.deepEqual(weighted.triangles,asset.canonical_surface_mesh.triangles);assert.ok(validation.multi_influence_vertices>0);assert.ok(validation.multi_influence_ratio>0);assert.ok(validation.max_observed_influences<=4);for(const weights of weighted.bone_weights){const values=Object.values(weights);assert.ok(values.length>=1&&values.length<=4);assert.ok(Math.abs(values.reduce((sum,value)=>sum+value,0)-1)<1e-6);}});

test('Weighted native surface frame binds canonical mesh, weighting, skinning and visibility into one root chain',()=>{const{asset}=full('phase6-6-weighted-frame'),frame=buildWeightedNativeSurfaceFrame({canonical_morphology_asset:asset},{view:'three-quarter-right',pose:'action',frame:60,totalFrames:120,width:640,height:360,scale:.52}),validation=validateWeightedNativeSurfaceFrame(frame);assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(frame.canonical_mesh_root,asset.canonical_surface_mesh.mesh_root);assert.notEqual(frame.mesh_root,frame.canonical_mesh_root);assert.ok(frame.surface_weighting_root);assert.ok(validation.multi_influence_ratio>0);assert.equal(frame.posed_skeleton.bone_lengths_pose_invariant,true);assert.equal(frame.posed_mesh.triangles.length,asset.canonical_surface_mesh.triangles.length);assert.ok(frame.posed_mesh.bone_weights.some(weights=>Object.keys(weights).length>1));});
