import assert from 'node:assert/strict';
import test from 'node:test';
import {createAnatomySystem} from '../src/anatomy.mjs';
import {compileFullBodyArtDirectedMorphology} from '../src/lower-body-morphology.mjs';
import {applyFieldGuidedSurfaceWeights,validateFieldGuidedSurfaceWeights,anatomicalWeightCompatibility} from '../src/surface-weighting.mjs';
import {buildWeightedNativeSurfaceFrame,validateWeightedNativeSurfaceFrame} from '../src/weighted-native-surface-runtime.mjs';

function full(seed='phase6-6-surface-weighting'){const system=createAnatomySystem({seed}),asset=compileFullBodyArtDirectedMorphology(system.genome,{surface_resolution:'property',certificate_mode:'property'});return{system,asset};}

test('Field-guided weighting preserves canonical geometry while creating normalized anatomically compatible multi-bone weights',()=>{const{asset}=full(),weighted=applyFieldGuidedSurfaceWeights(asset.canonical_surface_mesh,asset.continuous_morphology_field),validation=validateFieldGuidedSurfaceWeights(weighted,{requireMultiInfluence:true,requireCompatibilityEvidence:true});assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(weighted.source_mesh_root,asset.canonical_surface_mesh.mesh_root);assert.notEqual(weighted.mesh_root,asset.canonical_surface_mesh.mesh_root);assert.equal(weighted.vertices.length,asset.canonical_surface_mesh.vertices.length);assert.deepEqual(weighted.triangles,asset.canonical_surface_mesh.triangles);assert.ok(validation.multi_influence_vertices>0);assert.ok(validation.multi_influence_ratio>0);assert.ok(validation.max_observed_influences<=4);assert.equal(weighted.surface_weighting.policy.compatibility,'hierarchical-anatomical-chain-v0.1');assert.equal(weighted.surface_weighting.policy.cross_side_limb_influence,'forbidden');assert.equal(weighted.source_primary_bones.length,weighted.vertices.length);for(let index=0;index<weighted.bone_weights.length;index++){const weights=weighted.bone_weights[index],values=Object.values(weights),primary=weighted.source_primary_bones[index];assert.ok(values.length>=1&&values.length<=4);assert.ok(Math.abs(values.reduce((sum,value)=>sum+value,0)-1)<1e-6);for(const bone of Object.keys(weights))assert.equal(anatomicalWeightCompatibility(primary,bone),true,`${index}:${primary}->${bone}`);}});

test('Anatomical compatibility rejects cross-side limb candidates even when they occupy the same space',()=>{const mesh={mesh_root:'synthetic-mesh',vertices:[[0,0,0]],bone_weights:[{'upper-arm-left':1}],triangles:[],normals:[[0,1,0]],region_ids:['upper_arm'],material_ids:['skin'],connected_components:[{component_id:'one'}]},field={field_root:'synthetic-field',fields:[{attached_bone:'upper-arm-left',rest_center:[0,0,0],extent:1},{attached_bone:'elbow-left',rest_center:[0,0,0],extent:1},{attached_bone:'upper-arm-right',rest_center:[0,0,0],extent:1},{attached_bone:'elbow-right',rest_center:[0,0,0],extent:1}]},weighted=applyFieldGuidedSurfaceWeights(mesh,field,{padding:.1,minWeight:0,primaryBias:1});assert.ok(Number(weighted.surface_weighting.rejected_incompatible_influences)>0);assert.equal(weighted.bone_weights[0]['upper-arm-right'],undefined);assert.equal(weighted.bone_weights[0]['elbow-right'],undefined);assert.ok(weighted.bone_weights[0]['upper-arm-left']>0);assert.ok(weighted.bone_weights[0]['elbow-left']>0);const validation=validateFieldGuidedSurfaceWeights(weighted,{requireMultiInfluence:true,requireCompatibilityEvidence:true});assert.equal(validation.valid,true,validation.errors.join(','));});

test('Validator independently rejects malicious cross-side weights even if a caller bypasses the compiler',()=>{const{asset}=full('phase6-6-malicious-weight'),weighted=applyFieldGuidedSurfaceWeights(asset.canonical_surface_mesh,asset.continuous_morphology_field),index=weighted.source_primary_bones.findIndex(bone=>bone==='upper-arm-left');assert.ok(index>=0);const tampered=structuredClone(weighted);tampered.bone_weights[index]={'upper-arm-left':.5,'upper-arm-right':.5};const validation=validateFieldGuidedSurfaceWeights(tampered,{requireCompatibilityEvidence:true});assert.equal(validation.valid,false);assert.ok(validation.errors.some(error=>error.startsWith(`SURFACE_WEIGHTING_CROSS_CHAIN_INVALID:${index}:upper-arm-left`)),validation.errors.join(','));});

test('Weighted native surface frame binds canonical mesh, chain-constrained weighting, skinning and visibility into one root chain',()=>{const{asset}=full('phase6-6-weighted-frame'),frame=buildWeightedNativeSurfaceFrame({canonical_morphology_asset:asset},{view:'three-quarter-right',pose:'action',frame:60,totalFrames:120,width:640,height:360,scale:.52}),validation=validateWeightedNativeSurfaceFrame(frame);assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(frame.canonical_mesh_root,asset.canonical_surface_mesh.mesh_root);assert.notEqual(frame.mesh_root,frame.canonical_mesh_root);assert.ok(frame.surface_weighting_root);assert.ok(validation.multi_influence_ratio>0);assert.equal(frame.surface_weighting.policy.compatibility,'hierarchical-anatomical-chain-v0.1');assert.equal(frame.posed_skeleton.bone_lengths_pose_invariant,true);assert.equal(frame.posed_mesh.triangles.length,asset.canonical_surface_mesh.triangles.length);assert.ok(frame.posed_mesh.bone_weights.some(weights=>Object.keys(weights).length>1));});
