import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import test from 'node:test';
import {normalizeSvgRasterBackend,inspectSvgRasterBackend,rasterizeSvgFile,validateSvgRasterReceipt,SVG_RASTER_BACKENDS,RESVG_JS_PINNED_VERSION} from '../src/svg-raster-provider.mjs';

const sampleReceipt=overrides=>({format:'rncs.svg-raster-provider-receipt.v0.1',version:'0.1.0-alpha.1',backend:'resvg-js',provider_id:'rncs.svg-raster.resvg-js',provider_version:RESVG_JS_PINNED_VERSION,pinned_provider_version:RESVG_JS_PINNED_VERSION,pin_match:true,system_library_dependency:false,node_module:'@resvg/resvg-js',svg_file:'input.svg',png_file:'output.png',width:1280,height:720,output:{path:'output.png',sha256:'a'.repeat(64),bytes:128},authority:{identity:false,canonical_geometry:false,drawing_ir:false,art_direction:false},receipt_root:'receipt-root',...overrides});

test('SVG raster backend normalization is explicit and rejects silent unknown providers',()=>{assert.deepEqual(new Set(SVG_RASTER_BACKENDS),new Set(['librsvg','resvg-js']));assert.equal(RESVG_JS_PINNED_VERSION,'2.6.2');assert.equal(normalizeSvgRasterBackend('LIBRSVG'),'librsvg');assert.equal(normalizeSvgRasterBackend('resvg-js'),'resvg-js');assert.throws(()=>normalizeSvgRasterBackend('browser-magic'),/SVG_RASTER_BACKEND_UNSUPPORTED/);});

test('SVG raster receipt requires pinned resvg version, hashed output and zero creative authority',()=>{const valid=validateSvgRasterReceipt(sampleReceipt());assert.equal(valid.valid,true,valid.errors.join(','));assert.equal(valid.output_sha256,'a'.repeat(64));assert.equal(valid.provider_version,RESVG_JS_PINNED_VERSION);const wrongVersion=validateSvgRasterReceipt(sampleReceipt({provider_version:'2.7.0-alpha.0',pin_match:false}));assert.equal(wrongVersion.valid,false);assert.ok(wrongVersion.errors.some(error=>error.startsWith('SVG_RASTER_RESVG_JS_VERSION_INVALID:')));const authority=validateSvgRasterReceipt(sampleReceipt({authority:{identity:false,canonical_geometry:false,drawing_ir:true,art_direction:false}}));assert.equal(authority.valid,false);assert.ok(authority.errors.includes('SVG_RASTER_RECEIPT_AUTHORITY_INVALID'));const noHash=validateSvgRasterReceipt(sampleReceipt({output:{path:'output.png',bytes:128}}));assert.equal(noHash.valid,false);assert.ok(noHash.errors.includes('SVG_RASTER_RECEIPT_OUTPUT_INVALID'));});

test('resvg-js provider rasterizes a deterministic 16:9 SVG when optional pinned provider is installed',t=>{let provider;try{provider=inspectSvgRasterBackend({backend:'resvg-js'});}catch(error){if(error?.code==='SVG_RASTER_RESVG_JS_MISSING'){t.skip('optional @resvg/resvg-js provider is not installed in this execution body');return;}throw error;}assert.equal(provider.version,RESVG_JS_PINNED_VERSION);assert.equal(provider.pin_match,true);const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rncs-resvg-')),svg=path.join(dir,'input.svg'),png=path.join(dir,'output.png');try{fs.writeFileSync(svg,'<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360" viewBox="0 0 640 360"><rect width="640" height="360" fill="#123456"/><circle cx="320" cy="180" r="80" fill="#abcdef"/></svg>');const receipt=rasterizeSvgFile(svg,png,{backend:'resvg-js',width:1280,height:720}),validation=validateSvgRasterReceipt(receipt);assert.equal(validation.valid,true,validation.errors.join(','));assert.equal(receipt.backend,'resvg-js');assert.equal(receipt.provider_version,RESVG_JS_PINNED_VERSION);assert.equal(receipt.width,1280);assert.equal(receipt.height,720);assert.ok(fs.statSync(png).size>100);assert.match(receipt.output.sha256,/^[a-f0-9]{64}$/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
