// 旧模块总登记表
// 以扫描结果为基础，对 Aetherworld 中已存在的历史 / 老系统资产做统一登记。
// 不重复造孤立系统：本登记表只对已有路由 / lib 做接入规划，不新建业务页面。
import type { LegacyModule, LegacyConnectableTo } from "./legacyModuleTypes";

function conn(p: Partial<LegacyConnectableTo>): LegacyConnectableTo {
  return {
    chat: false,
    fusion: false,
    memory: false,
    currency: false,
    msl: false,
    prediction: false,
    scheduler: false,
    calendar: false,
    workspace: false,
    store: false,
    social: false,
    qa: false,
    ...p,
  };
}

export const LEGACY_MODULE_REGISTRY: LegacyModule[] = [
  // ===== 虚拟生活 OS =====
  {
    id: "LM-VIRTUAL-LIFE",
    name: "Virtual Life OS",
    cnName: "虚拟生活 OS",
    category: "VIRTUAL_LIFE",
    layer: "LIFE",
    currentStatus: "PARTIAL",
    routes: ["/virtual-life", "/virtual-day", "/personal-world"],
    files: ["src/routes/virtual-life.tsx", "src/routes/virtual-day.tsx", "src/routes/personal-world.tsx"],
    capabilities: ["虚拟日常", "生活事件模拟", "主体状态", "日历联动"],
    connectableTo: conn({ chat: true, calendar: true, scheduler: true, memory: true, msl: true, prediction: true, workspace: true }),
    activationPriority: "P1",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["可能与 Calendar / Workspace 数据模型重叠", "需要明确「虚拟身份」隐私边界"],
    notes: "已有页面，下一步把日常状态写入 Sequence Memory 并接入 Calendar Trigger。",
    bridgePlan: {
      goal: "把虚拟生活 OS 接入 Chat / Calendar / Memory / Prediction",
      targets: ["Chat", "Calendar Trigger", "Scheduler", "Sequence Memory", "MSL", "Prediction"],
      reusableFiles: ["src/routes/virtual-life.tsx", "src/routes/virtual-day.tsx"],
      newBridges: ["virtualLifeMemoryBridge.ts", "virtualLifeCalendarBridge.ts"],
      risks: ["与 Workspace 对象重叠", "需要隐私 / 脱敏策略"],
      promptDraft: "请把 /virtual-life 与 /virtual-day 的生活事件接入 Sequence Memory，并允许 Calendar Trigger 写回。",
    },
  },
  // ===== 虚拟世界 OS =====
  {
    id: "LM-VIRTUAL-WORLD",
    name: "Virtual World OS",
    cnName: "虚拟世界 OS",
    category: "VIRTUAL_WORLD",
    layer: "WORLD",
    currentStatus: "ACTIVE",
    routes: [
      "/virtual-world", "/worlds", "/world-engine", "/world-runtime",
      "/world-society", "/world-factions", "/world-npcs", "/world-timelines",
      "/world-causality", "/multi-world-network",
    ],
    files: [
      "src/routes/virtual-world.tsx", "src/routes/world-engine.tsx",
      "src/routes/world-runtime.tsx", "src/routes/worlds.tsx",
    ],
    capabilities: ["多世界", "NPC", "阵营", "因果链", "世界事件"],
    connectableTo: conn({ chat: true, calendar: true, scheduler: true, msl: true, prediction: true, workspace: true, social: true }),
    activationPriority: "P1",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["世界对象数据量大，需控制 Memory 写入率", "禁止把世界叙事自动发布到公开社交"],
    notes: "已有大量子页面，下一步通过 WORLD_ENGINE_CALCULUS 与 Scheduler 串联世界事件。",
    bridgePlan: {
      goal: "把世界引擎与多世界网络接入 Scheduler / Memory / Prediction",
      targets: ["World Engine", "Narrative", "Calendar Trigger", "Workspace", "Prediction", "MSL"],
      reusableFiles: ["src/routes/world-engine.tsx", "src/routes/world-runtime.tsx"],
      newBridges: ["virtualWorldEventBridge.ts"],
      risks: ["世界事件可能过载 Memory 通道"],
      promptDraft: "请把 /world-engine 的世界事件写入 Calendar Trigger 与 Sequence Memory，并允许 Prediction 引用。",
    },
  },
  // ===== 产品自进化 =====
  {
    id: "LM-PRODUCT-EVOLUTION",
    name: "Product Self Evolution",
    cnName: "产品自进化",
    category: "PRODUCT_EVOLUTION",
    layer: "GOVERNANCE",
    currentStatus: "PARTIAL",
    routes: ["/bio-evolution", "/civilization-evolution", "/version-iteration", "/version-leap", "/version-timeline", "/system-evolution-map"],
    files: [
      "src/lib/bioProductEvolutionEngine.ts",
      "src/lib/evolutionRecommendationEngine.ts",
      "src/lib/evolutionMutationPlanner.ts",
      "src/lib/evolutionSafetyGuard.ts",
    ],
    capabilities: ["自进化建议", "版本跃迁", "演化时间线", "演化信号采集"],
    connectableTo: conn({ chat: true, prediction: true, scheduler: true, workspace: true, currency: true, qa: true }),
    activationPriority: "P0",
    recommendedAction: "ACTIVATE_NOW",
    risks: ["自进化建议不得自动应用代码", "需经 Lovable Handoff 审批"],
    notes: "P0：与 Bug Audit + Value Ledger + Prediction 串联，输出 ProductEvolutionSuggestion。",
    bridgePlan: {
      goal: "读取 Bug Audit / Value Ledger / Usage Record / Prediction 自动产出升级建议",
      targets: ["Bug Audit", "Sequence Currency", "Prediction", "Scheduler", "Workspace", "Code Sandbox", "Lovable Handoff"],
      reusableFiles: ["src/lib/evolutionRecommendationEngine.ts", "src/lib/bioProductEvolutionEngine.ts"],
      newBridges: ["productEvolutionAuditBridge.ts", "productEvolutionLovableHandoffBridge.ts"],
      risks: ["不得自动执行代码改动", "高风险建议必须人工确认"],
      promptDraft: "请把 Bug Audit / Value Ledger / Prediction 结果输入 evolutionRecommendationEngine，输出 ProductEvolutionSuggestion 并写入 Workspace。",
    },
  },
  // ===== 记录中心 =====
  {
    id: "LM-RECORD-CENTER",
    name: "Record Center",
    cnName: "记录中心",
    category: "RECORD_CENTER",
    layer: "MEMORY",
    currentStatus: "PARTIAL",
    routes: ["/usage-examples", "/integration-audit", "/system-audit"],
    files: ["src/lib/system/bugAuditReport.ts"],
    capabilities: ["记录模型回答", "记录任务执行", "记录预测", "记录工作区对象"],
    connectableTo: conn({ chat: true, scheduler: true, msl: true, memory: true, workspace: true, qa: true }),
    activationPriority: "P0",
    recommendedAction: "ACTIVATE_NOW",
    risks: ["原文必须脱敏", "Full60 / Founder-only 不得写入"],
    notes: "P0：作为回验中心 / 权重中心的数据源；输出 RecordEvent。",
    bridgePlan: {
      goal: "建立统一 RecordEvent 流，供回验 / 权重 / 自进化读取",
      targets: ["Chat", "Scheduler", "MSL", "Sequence Memory", "Workspace", "Audit"],
      reusableFiles: ["src/lib/msl-state/mslStateStore.ts"],
      newBridges: ["recordCenterEventBridge.ts", "recordCenterQueryBridge.ts"],
      risks: ["写入率需限流", "PII / Secret 必须脱敏"],
      promptDraft: "请把 Chat / Scheduler / MSL / Memory 输出统一映射为 RecordEvent，并提供 query API 给回验中心。",
    },
  },
  // ===== 回验中心 =====
  {
    id: "LM-VERIFICATION-CENTER",
    name: "Verification Center",
    cnName: "回验中心",
    category: "VERIFICATION_CENTER",
    layer: "PREDICTION",
    currentStatus: "PLACEHOLDER",
    routes: ["/reality-calibration", "/accuracy", "/prediction-dimensions"],
    files: ["src/routes/reality-calibration.tsx", "src/routes/accuracy.tsx"],
    capabilities: ["事后验证预测", "事后验证任务", "事后验证判断"],
    connectableTo: conn({ prediction: true, calendar: true, scheduler: true, workspace: true, msl: true, currency: true }),
    activationPriority: "P0",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["回验结论不得对外宣称为确定性结论"],
    notes: "P0.5：先桥接 RecordEvent + Prediction，输出回验结论与权重修正。",
    bridgePlan: {
      goal: "读取 RecordEvent + Prediction 结果做事后回验",
      targets: ["Prediction", "Calendar", "Scheduler", "Workspace", "MSL", "Sequence Currency"],
      reusableFiles: ["src/routes/reality-calibration.tsx", "src/routes/accuracy.tsx"],
      newBridges: ["verificationCenterPredictionBridge.ts"],
      risks: ["回验结论需声明为结构化判断"],
      promptDraft: "请基于 RecordEvent 与 SequencePredictionResult 做事后回验，输出 VerificationOutcome。",
    },
  },
  // ===== 记录权重 =====
  {
    id: "LM-RECORD-WEIGHT",
    name: "Record Weight",
    cnName: "记录权重",
    category: "WEIGHT_ENGINE",
    layer: "MEMORY",
    currentStatus: "PARTIAL",
    routes: ["/feedback-weights"],
    files: ["src/routes/feedback-weights.tsx", "src/constants/feedbackWeightFactors.ts"],
    capabilities: ["记忆权重", "预测权重", "任务权重", "对象权重"],
    connectableTo: conn({ memory: true, prediction: true, scheduler: true, workspace: true, chat: true, currency: true }),
    activationPriority: "P0",
    recommendedAction: "ACTIVATE_NOW",
    risks: ["权重调整需要审计轨迹"],
    notes: "已有反馈权重因子常数；P0：注入 Sequence Memory / Prediction / Currency。",
    bridgePlan: {
      goal: "把权重因子注入 Memory / Prediction / Currency 评分",
      targets: ["Sequence Memory", "Prediction", "Scheduler", "Workspace", "Chat Context", "Value Ledger"],
      reusableFiles: ["src/constants/feedbackWeightFactors.ts"],
      newBridges: ["recordWeightMemoryBridge.ts", "recordWeightPredictionBridge.ts"],
      risks: ["权重必须可解释，不得隐式生效"],
      promptDraft: "请把 feedbackWeightFactors 接入 Sequence Memory scoring 与 Prediction trajectory 概率估计。",
    },
  },
  // ===== 反馈权重 =====
  {
    id: "LM-FEEDBACK-WEIGHT",
    name: "Feedback Weight",
    cnName: "反馈权重",
    category: "WEIGHT_ENGINE",
    layer: "VALUE",
    currentStatus: "PARTIAL",
    routes: ["/feedback-weights"],
    files: [
      "src/routes/feedback-weights.tsx",
      "src/constants/feedbackEntryRules.ts",
      "src/constants/feedbackBiasTypes.ts",
      "src/constants/feedbackConstants.ts",
    ],
    capabilities: ["反馈条目规则", "偏差识别", "反馈常数"],
    connectableTo: conn({ memory: true, prediction: true, qa: true, currency: true, chat: true }),
    activationPriority: "P1",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["偏差识别须人工复检"],
    notes: "与「记录权重」可能可合并；先做 Bridge，长期评估合并。",
  },
  // ===== 事件算法 =====
  {
    id: "LM-EVENT-ALGORITHM",
    name: "Event Algorithm",
    cnName: "事件算法",
    category: "EVENT_ENGINE",
    layer: "RUNTIME",
    currentStatus: "ACTIVE",
    routes: ["/event-algorithms", "/event-library-audit"],
    files: [
      "src/lib/eventAlgorithmEngine.ts",
      "src/lib/eventCompletionEngine.ts",
      "src/lib/eventStageEngine.ts",
      "src/lib/eventManifestationEngine.ts",
      "src/lib/eventValidationEngine.ts",
      "src/constants/eventAlgorithmTypes.ts",
    ],
    capabilities: ["事件识别", "状态变化", "触发条件", "后续动作"],
    connectableTo: conn({ calendar: true, scheduler: true, prediction: true, workspace: true, msl: true }),
    activationPriority: "P1",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["事件可能与 Scheduler 任务重叠", "禁止自动执行高风险动作"],
    notes: "已有较完整事件库；下一步把 EventStage 输出接入 Scheduler 与 Calendar Trigger。",
  },
  // ===== 预测校准 =====
  {
    id: "LM-PREDICTION-CALIBRATION",
    name: "Prediction Calibration",
    cnName: "预测校准",
    category: "PREDICTION_CALIBRATION",
    layer: "PREDICTION",
    currentStatus: "PARTIAL",
    routes: ["/prediction-dimensions", "/accuracy"],
    files: ["src/routes/prediction-dimensions.tsx", "src/routes/accuracy.tsx"],
    capabilities: ["预测维度", "准确率追踪", "校准回路"],
    connectableTo: conn({ prediction: true, memory: true, workspace: true, scheduler: true }),
    activationPriority: "P1",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["校准结果不得用于金融 / 医疗承诺"],
    notes: "可作为 Sequence Prediction Engine 的真实回路。",
  },
  // ===== 现实校准 =====
  {
    id: "LM-REALITY-CALIBRATION",
    name: "Reality Calibration",
    cnName: "现实校准",
    category: "REALITY_CALIBRATION",
    layer: "GOVERNANCE",
    currentStatus: "PARTIAL",
    routes: ["/reality-calibration", "/reality-data-audit"],
    files: ["src/routes/reality-calibration.tsx", "src/routes/reality-data-audit.tsx"],
    capabilities: ["对照现实数据", "现实数据审计"],
    connectableTo: conn({ prediction: true, workspace: true, qa: true }),
    activationPriority: "P2",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["现实数据可能受版权 / 隐私限制"],
    notes: "与 Verification Center 强相关，长期可合并到「回验 / 校准」层。",
  },
  // ===== 虚拟日记 =====
  {
    id: "LM-VIRTUAL-JOURNAL",
    name: "Virtual Journal",
    cnName: "虚拟日记",
    category: "JOURNAL",
    layer: "LIFE",
    currentStatus: "PARTIAL",
    routes: ["/virtual-journal", "/virtual-day"],
    files: ["src/routes/virtual-journal.tsx", "src/routes/virtual-day.tsx"],
    capabilities: ["日常记录", "情绪", "事件回顾"],
    connectableTo: conn({ memory: true, workspace: true, social: false, msl: true }),
    activationPriority: "P2",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["不得自动发布到公开社交"],
    notes: "可作为虚拟生活 OS 的子模块；建议合并视图。",
  },
  // ===== 虚拟创造 =====
  {
    id: "LM-VIRTUAL-CREATION",
    name: "Virtual Creation",
    cnName: "虚拟创造",
    category: "JOURNAL",
    layer: "LIFE",
    currentStatus: "PARTIAL",
    routes: ["/virtual-creation", "/creation-simulator"],
    files: ["src/routes/virtual-creation.tsx", "src/routes/creation-simulator.tsx", "src/lib/creationSeedCompiler.ts"],
    capabilities: ["创作片段", "角色生活日志", "创造模拟"],
    connectableTo: conn({ workspace: true, memory: true, msl: true }),
    activationPriority: "P2",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["创作内容版权归属需明确"],
    notes: "可作为 Virtual Life / World 的创作通道。",
  },
  // ===== 系统进化图谱 =====
  {
    id: "LM-SYSTEM-EVOLUTION-MAP",
    name: "System Evolution Map",
    cnName: "系统进化图谱",
    category: "SYSTEM_AUDIT",
    layer: "GOVERNANCE",
    currentStatus: "ACTIVE",
    routes: ["/system-evolution-map"],
    files: ["src/routes/system-evolution-map.tsx"],
    capabilities: ["系统级演化可视化"],
    connectableTo: conn({ prediction: true, qa: true, workspace: true }),
    activationPriority: "P1",
    recommendedAction: "BRIDGE_ONLY",
    risks: [],
    notes: "可被 Legacy Module Registry 反向引用，形成「旧模块 + 进化轨迹」联合视图。",
  },
  // ===== 共鸣 / 信号 =====
  {
    id: "LM-RESONANCE",
    name: "Resonance",
    cnName: "共鸣",
    category: "OTHER",
    layer: "STATE",
    currentStatus: "DEMO",
    routes: ["/resonance"],
    files: ["src/routes/resonance.tsx"],
    capabilities: ["共鸣概念演示"],
    connectableTo: conn({ memory: true, msl: true }),
    activationPriority: "P3",
    recommendedAction: "KEEP_READ_ONLY",
    risks: ["概念性强，需避免对外承诺"],
    notes: "暂保留为只读，等待与「权重 / 反馈」整合契机。",
  },
  {
    id: "LM-SIGNAL",
    name: "Signal",
    cnName: "信号净化",
    category: "OTHER",
    layer: "STATE",
    currentStatus: "DEMO",
    routes: ["/signal"],
    files: ["src/routes/signal.tsx"],
    capabilities: ["信号概念演示"],
    connectableTo: conn({ memory: true, msl: true }),
    activationPriority: "P3",
    recommendedAction: "KEEP_READ_ONLY",
    risks: [],
    notes: "与共鸣可能可合并为一个统一「信号 / 共鸣」入口。",
  },
  // ===== 物本身 / 本体 =====
  {
    id: "LM-OBJECT-ONTOLOGY",
    name: "Object Ontology",
    cnName: "物本体",
    category: "OTHER",
    layer: "STATE",
    currentStatus: "PARTIAL",
    routes: ["/object-ontology"],
    files: ["src/routes/object-ontology.tsx"],
    capabilities: ["对象本体定义"],
    connectableTo: conn({ workspace: true, msl: true }),
    activationPriority: "P2",
    recommendedAction: "BRIDGE_ONLY",
    risks: [],
    notes: "可被 Workspace 对象系统引用。",
  },
  // ===== 版本跃迁 / 时间线 =====
  {
    id: "LM-VERSION-LEAP",
    name: "Version Leap",
    cnName: "版本跃迁",
    category: "SYSTEM_AUDIT",
    layer: "GOVERNANCE",
    currentStatus: "ACTIVE",
    routes: ["/version-leap", "/version-iteration", "/version-timeline", "/version-audit"],
    files: ["src/routes/version-leap.tsx", "src/routes/version-iteration.tsx", "src/routes/version-timeline.tsx"],
    capabilities: ["版本管理", "跃迁记录"],
    connectableTo: conn({ workspace: true, qa: true, prediction: true }),
    activationPriority: "P1",
    recommendedAction: "BRIDGE_ONLY",
    risks: [],
    notes: "与产品自进化强相关；可合并视图。",
  },
  // ===== 触发 / 日历触发 =====
  {
    id: "LM-TRIGGER-CALENDAR",
    name: "Trigger Calendar",
    cnName: "触发日历",
    category: "EVENT_ENGINE",
    layer: "SCHEDULER",
    currentStatus: "ACTIVE",
    routes: ["/trigger-calendar", "/calendar/triggers"],
    files: ["src/routes/trigger-calendar.tsx", "src/routes/calendar.triggers.tsx"],
    capabilities: ["触发器配置", "日历触发"],
    connectableTo: conn({ calendar: true, scheduler: true, prediction: true }),
    activationPriority: "P1",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["不得自动执行高风险动作"],
    notes: "已与 Aether Scheduler 部分接入；可继续合并事件算法输出。",
  },
  // ===== 过去回放 / 系统回放 =====
  {
    id: "LM-PAST-LIFE-RECALL",
    name: "Past Life Recall",
    cnName: "回放中心",
    category: "RECORD_CENTER",
    layer: "MEMORY",
    currentStatus: "DEMO",
    routes: ["/past-life-recall"],
    files: ["src/routes/past-life-recall.tsx"],
    capabilities: ["系统回放", "历史片段重演"],
    connectableTo: conn({ memory: true, prediction: true }),
    activationPriority: "P2",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["回放原文须脱敏"],
    notes: "可作为「记录中心 → 回验中心」之间的回放通道。",
  },
  // ===== 多世界关系 =====
  {
    id: "LM-CROSS-WORLD",
    name: "Cross World Relations",
    cnName: "跨世界关系",
    category: "VIRTUAL_WORLD",
    layer: "WORLD",
    currentStatus: "PARTIAL",
    routes: ["/cross-world-relations", "/multi-world-network", "/multi-world-export"],
    files: ["src/routes/cross-world-relations.tsx", "src/routes/multi-world-network.tsx"],
    capabilities: ["世界间关系", "联邦", "导出"],
    connectableTo: conn({ workspace: true, msl: true, prediction: true }),
    activationPriority: "P2",
    recommendedAction: "BRIDGE_ONLY",
    risks: [],
    notes: "属于虚拟世界 OS 的扩展层；可在第二轮接入。",
  },
  // ===== 文明 / 神话 =====
  {
    id: "LM-CIVILIZATION",
    name: "Civilization Chronicle",
    cnName: "文明编年",
    category: "VIRTUAL_WORLD",
    layer: "WORLD",
    currentStatus: "ACTIVE",
    routes: ["/civilization-chronicle", "/civilization-evolution", "/civilization-myth", "/civilization-phase"],
    files: ["src/routes/civilization-chronicle.tsx", "src/routes/civilization-evolution.tsx"],
    capabilities: ["文明阶段", "神话", "演化"],
    connectableTo: conn({ workspace: true, msl: true, prediction: true }),
    activationPriority: "P2",
    recommendedAction: "BRIDGE_ONLY",
    risks: [],
    notes: "与虚拟世界 OS / 产品自进化均相关。",
  },
  // ===== 使用记录 / 例子 =====
  {
    id: "LM-USAGE-RECORD",
    name: "Usage Record",
    cnName: "使用记录",
    category: "RECORD_CENTER",
    layer: "MEMORY",
    currentStatus: "PARTIAL",
    routes: ["/usage-examples", "/usage-safety"],
    files: ["src/routes/usage-examples.tsx", "src/routes/usage-safety.tsx"],
    capabilities: ["使用案例", "使用安全"],
    connectableTo: conn({ memory: true, qa: true, workspace: true, currency: true }),
    activationPriority: "P1",
    recommendedAction: "BRIDGE_ONLY",
    risks: ["使用记录中的敏感字段需脱敏"],
    notes: "可作为产品自进化的输入信号源。",
  },
];

export function getAllLegacyModules(): LegacyModule[] {
  return LEGACY_MODULE_REGISTRY;
}

export function getLegacyModuleById(id: string): LegacyModule | undefined {
  return LEGACY_MODULE_REGISTRY.find((m) => m.id === id);
}
