import {clone,hash,seal,uniq,matchPattern,AAFError} from './canonical.mjs';
import {verifyPolicyBundle,verifyDelegation,verifyApproval,verifyRevocationRegistry,makeAuthorityRequest} from './contracts.mjs';
import {verifyEnvelope,applyDecisionToEnvelope,toProposedEnvelope} from './rncs.mjs';
import {verifySignedObject} from './signatures.mjs';
const riskRank={low:1,medium:2,high:3,critical:4};
const parseTime=s=>{const n=Date.parse(s);return Number.isFinite(n)?n:null};
const inWindow=(now,from,to)=>{const n=parseTime(now);if(n===null)return false;const a=from?parseTime(from):null,b=to?parseTime(to):null;return(a===null||n>=a)&&(b===null||n<=b)};
const scopeMatch=(patterns,scope)=>(patterns??[]).some(p=>matchPattern(p,scope));
const capabilityMatch=(patterns,id)=>(patterns??['*']).some(p=>matchPattern(p,id));
function normalizeSteps(envelope,negotiation){if(negotiation?.plan?.steps)return clone(negotiation.plan.steps);return (envelope.capability_plan?.capabilities??[]).map((c,i)=>({step_id:`step:${i+1}`,capability_id:c.capability_id,required_scopes:c.required_scopes??[],risk:{level:c.risk??'low'},reversible:c.reversible!==false,execution_phase:c.execution_phase??'transaction',cost:c.cost??{}}));}
function effectiveRisk(steps){let max='low';for(const s of steps){const r=s.risk?.level??'low';if((riskRank[r]??0)>(riskRank[max]??0))max=r;}return max;}
function validDelegation(d,subjectId,scope,capIds,now,revoked){if(!verifyDelegation(d))return{ok:false,reason:'delegation-root-invalid'};if(revoked.has(d.delegation_id))return{ok:false,reason:'delegation-revoked'};if(d.delegate_id!==subjectId)return{ok:false,reason:'delegate-mismatch'};if(!inWindow(now,d.not_before,d.expires_at))return{ok:false,reason:'delegation-time-invalid'};if(!scopeMatch(d.scopes,scope))return{ok:false,reason:'scope-not-delegated'};if(!capIds.every(id=>capabilityMatch(d.capability_patterns,id)))return{ok:false,reason:'capability-not-delegated'};return{ok:true,reason:'delegated',delegation_id:d.delegation_id,issuer_id:d.issuer_id};}
function policyApplies(p,ctx){const m=p.match??{};if(m.scopes_any&&!ctx.scopes.some(s=>scopeMatch(m.scopes_any,s)))return false;if(m.roles_any&&!ctx.roles.some(r=>(m.roles_any??[]).includes(r)))return false;if(m.subject_kinds&&!m.subject_kinds.includes(ctx.subject_kind))return false;if(m.capabilities_any&&!ctx.capability_ids.some(id=>capabilityMatch(m.capabilities_any,id)))return false;if(m.environments&&!m.environments.includes(ctx.environment))return false;if(m.risk_at_least&&(riskRank[ctx.risk]??0)<(riskRank[m.risk_at_least]??0))return false;if(m.risk_at_most&&(riskRank[ctx.risk]??0)>(riskRank[m.risk_at_most]??0))return false;if(m.irreversible!==undefined&&m.irreversible!==ctx.irreversible)return false;if(m.monetary_above!==undefined&&ctx.monetary<=m.monetary_above)return false;return true;}
function approvalValid(a,proposalRoot,now,revoked,keyring,requireSignatures){if(!verifyApproval(a))return{ok:false,reason:'approval-root-invalid'};if(revoked.has(a.approval_id))return{ok:false,reason:'approval-revoked'};if(a.proposal_root!==proposalRoot)return{ok:false,reason:'approval-proposal-mismatch'};if(!inWindow(now,a.issued_at,a.expires_at))return{ok:false,reason:'approval-time-invalid'};if(requireSignatures){const key=keyring?.[a.signature?.signer_id];if(!key||!verifySignedObject(a,key))return{ok:false,reason:'approval-signature-invalid'};}return{ok:true};}
export function evaluateAuthority({envelope,negotiation=null,policy_bundle,delegations=[],approvals=[],revocations=null,identity_scopes=[],context={},keyring={},require_signatures=false}){
 const ev=toProposedEnvelope(envelope), vv=verifyEnvelope(ev);if(!vv.valid)throw new AAFError('ENVELOPE_INVALID',vv.errors.join(','));if(!verifyPolicyBundle(policy_bundle))throw new AAFError('POLICY_BUNDLE_INVALID');
 const rev=revocations??{format:'aaf.revocation-registry.v0.1',registry_id:'empty',revoked_delegations:[],revoked_approvals:[],updated_at:'',revocation_root:''};
 const revokedD=new Set(rev.revoked_delegations??[]),revokedA=new Set(rev.revoked_approvals??[]);
 if(rev.revocation_root&&!verifyRevocationRegistry(rev))throw new AAFError('REVOCATION_REGISTRY_INVALID');
 const steps=normalizeSteps(ev,negotiation),scopes=uniq([...(ev.capability_plan?.required_scopes??[]),...steps.flatMap(s=>s.required_scopes??[])]),capabilityIds=uniq(steps.map(s=>s.capability_id));
 const roles=uniq(ev.subject.roles),now=String(context.now??''),environment=String(context.environment??'local'),monetary=Number(context.monetary_microunits??steps.reduce((n,s)=>n+Number(s.cost?.monetary_microunits??0),0));
 const risk=effectiveRisk(steps),irreversible=steps.some(s=>s.reversible===false),claims=[];
 const direct=new Set(identity_scopes.map(String));
 for(const scope of scopes){if(direct.has('*')||direct.has(scope)){claims.push({scope,granted:true,source:'identity',reason:'direct-scope'});continue;}let grant=null;for(const d of delegations){const r=validDelegation(d,ev.subject.subject_id,scope,capabilityIds,now,revokedD);if(r.ok){grant=r;break;}}const claim={scope,granted:!!grant,source:grant?'delegation':'none',reason:grant?.reason??'scope-not-held'};if(grant?.delegation_id)claim.delegation_id=grant.delegation_id;claims.push(claim);}
 const baseCtx={scopes,roles,subject_kind:ev.subject.kind,capability_ids:capabilityIds,environment,risk,irreversible,monetary};
 const matched=(policy_bundle.policies??[]).filter(p=>policyApplies(p,baseCtx)).sort((a,b)=>(Number(b.priority??0)-Number(a.priority??0))||String(a.policy_id).localeCompare(String(b.policy_id),'en'));
 const denies=matched.filter(p=>p.effect==='deny');const requires=matched.filter(p=>p.effect==='require_approval');const allows=matched.filter(p=>p.effect==='allow');
 const constraints=matched.flatMap(p=>(p.constraints??[]).map(c=>({policy_id:p.policy_id,...clone(c)})));
 const obligations=matched.flatMap(p=>(p.obligations??[]).map(o=>({policy_id:p.policy_id,...clone(o)})));
 let status='denied',reason='default-deny',requirements=[];
 if(claims.some(c=>!c.granted)){status='denied';reason='required-scope-not-held';}
 else if(denies.length){status='denied';reason=`denied-by:${denies.map(p=>p.policy_id).join(',')}`;}
 else if(requires.length){const roleSet=uniq(requires.flatMap(p=>p.approval?.roles??[]));const quorum=Math.max(...requires.map(p=>Number(p.approval?.quorum??1)),1);requirements=[{kind:'human-approval',roles:roleSet,quorum,proposal_root:ev.proposal_root,policy_ids:requires.map(p=>p.policy_id)}];const valid=[];const invalid=[];for(const a of approvals){const r=approvalValid(a,ev.proposal_root,now,revokedA,keyring,require_signatures);if(!r.ok){invalid.push({approval_id:a.approval_id,reason:r.reason});continue;}if(a.decision==='denied'){status='denied';reason=`denied-by-approver:${a.approver_id}`;break;}if(!roleSet.length||a.approver_roles.some(r=>roleSet.includes(r)))valid.push(a);}if(status!=='denied'||!reason.startsWith('denied-by-approver')){const unique=new Set(valid.map(a=>a.approver_id));if(unique.size>=quorum){status='approved';reason='approval-quorum-satisfied';}else{status='pending_approval';reason=`approval-required:${unique.size}/${quorum}`;}}requirements[0].valid_approvers=[...new Set(valid.map(a=>a.approver_id))].sort();requirements[0].invalid_approvals=invalid;}
 else if(allows.length||policy_bundle.default_effect==='allow'){status='approved';reason=allows.length?`allowed-by:${allows.map(p=>p.policy_id).join(',')}`:'allowed-by-default';}
 const request=makeAuthorityRequest({request_id:context.request_id??`authority:${ev.transition_id}`,envelope:ev,requested_scopes:scopes,capability_steps:steps,context:{...clone(context),risk,irreversible,monetary_microunits:monetary},policy_bundle_root:policy_bundle.policy_bundle_root,delegation_roots:delegations.map(d=>d.delegation_root),approval_roots:approvals.map(a=>a.approval_root)});
 const result={format:'aaf.authority-decision.v0.1',request,proposal_root:ev.proposal_root,status,reason,claims,constraints,obligations,requirements,risk_summary:{level:risk,irreversible,monetary_microunits:monetary,capability_ids:capabilityIds},matched_policies:matched.map(p=>({policy_id:p.policy_id,effect:p.effect,priority:Number(p.priority??0)})),delegation_evidence:claims.filter(c=>c.delegation_id).map(c=>({scope:c.scope,delegation_id:c.delegation_id})),evaluated_at:now};
 result.decision_root=hash(result);const authorized_envelope=applyDecisionToEnvelope(ev,result);return{...result,authorized_envelope};
}
