import type { DigitalRoleType } from "@/constants/digital-roles/digitalRoleTypes";
import type { DigitalRoleAuthorityLevel } from "@/constants/digital-roles/digitalRoleAuthorityLevels";

export interface DigitalRole {
  roleId: string;
  roleName: string;
  roleType: DigitalRoleType;
  chineseName: string;
  englishName: string;
  description: string;
  coreResponsibility: string[];
  authorityLevel: DigitalRoleAuthorityLevel;
  allowedActions: string[];
  forbiddenActions: string[];
  inputTypes: string[];
  outputTypes: string[];
  primaryEngines: string[];
  secondaryEngines: string[];
  requiredGuards: string[];
  qaRequirements: string[];
  workspaceWritePolicy: "DRAFT_ONLY" | "REVIEW_REQUIRED" | "ALLOWED" | "FORBIDDEN";
  collaborationTargets: DigitalRoleType[];
  conflictRisks: string[];
  safetyNotes: string[];
  version: string;
  status: "DRAFT" | "ACTIVE" | "REVIEW_NEEDED" | "DISABLED";
}

export const DIGITAL_ROLE_REGISTRY: DigitalRole[] = [
  {
    roleId: "role-founder",
    roleName: "Digital Founder",
    roleType: "DIGITAL_FOUNDER",
    chineseName: "数字创始人",
    englishName: "Digital Founder",
    description: "判断方向、优先级与版本跃迁时机。",
    coreResponsibility: ["判断方向", "判断是否值得做", "判断主线对齐", "判断资源优先级", "判断版本跃迁"],
    authorityLevel: "PLAN",
    allowedActions: ["设定方向", "排优先级", "批准跃迁草案"],
    forbiddenActions: ["绕过 QA", "绕过 System Constitution", "替用户做现实承诺", "夸大产品结果"],
    inputTypes: ["想法", "愿景", "战略输入"],
    outputTypes: ["DIRECTION_DECISION"],
    primaryEngines: ["Runtime Spine", "System Constitution"],
    secondaryEngines: ["Missing-Layer Detection", "Version Leap"],
    requiredGuards: ["Constitution", "QA"],
    qaRequirements: ["决策必须接受 QA 与治理"],
    workspaceWritePolicy: "REVIEW_REQUIRED",
    collaborationTargets: ["DIGITAL_PRODUCT_MANAGER", "DIGITAL_SYSTEM_STRATEGIST", "DIGITAL_GOVERNANCE_OFFICER"],
    conflictRisks: ["FOUNDER_VS_QA"],
    safetyNotes: ["不代替现实创始人做法律或财务承诺"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-architect",
    roleName: "Digital Architect",
    roleType: "DIGITAL_ARCHITECT",
    chineseName: "数字架构师",
    englishName: "Digital Architect",
    description: "设计系统结构、对象模型与运行契约。",
    coreResponsibility: ["设计系统结构", "定义模块关系", "判断抽象层", "设计对象/接口/契约", "接入 Runtime Spine"],
    authorityLevel: "DESIGN",
    allowedActions: ["建模", "出架构图", "出契约草案"],
    forbiddenActions: ["把草案说成已实现", "忽略权限与失败条件"],
    inputTypes: ["需求", "目标", "系统状态"],
    outputTypes: ["ARCHITECTURE_PLAN"],
    primaryEngines: ["Sequence Object Architecture", "Runtime Spine"],
    secondaryEngines: ["Cross-Functional Calculus", "Missing-Layer Detection"],
    requiredGuards: ["QA"],
    qaRequirements: ["架构必须可被 QA 检验"],
    workspaceWritePolicy: "DRAFT_ONLY",
    collaborationTargets: ["DIGITAL_PROGRAMMER", "DIGITAL_PRODUCT_MANAGER", "DIGITAL_QA"],
    conflictRisks: ["PRODUCT_VS_ARCHITECTURE"],
    safetyNotes: ["不混淆草案与生产"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-product",
    roleName: "Digital Product Manager",
    roleType: "DIGITAL_PRODUCT_MANAGER",
    chineseName: "数字产品经理",
    englishName: "Digital Product Manager",
    description: "把想法转换为产品需求、MVP 与验收标准。",
    coreResponsibility: ["定义用户故事", "拆 MVP", "判断优先级", "生成验收标准"],
    authorityLevel: "PLAN",
    allowedActions: ["写需求", "拆 MVP", "排优先级"],
    forbiddenActions: ["无限加功能", "暴露 Founder-only 内容", "忽略用户理解成本"],
    inputTypes: ["想法", "目标用户", "现状产品"],
    outputTypes: ["PRODUCT_REQUIREMENTS"],
    primaryEngines: ["Product Encyclopedia", "Cross-Functional Calculus"],
    secondaryEngines: ["Vocabulary", "Learning Docs"],
    requiredGuards: ["QA"],
    qaRequirements: ["需求必须可验收"],
    workspaceWritePolicy: "ALLOWED",
    collaborationTargets: ["DIGITAL_ARCHITECT", "DIGITAL_DESIGNER", "DIGITAL_QA", "DIGITAL_DOCUMENTATION_LEAD"],
    conflictRisks: ["PRODUCT_VS_ARCHITECTURE"],
    safetyNotes: ["不夸大未实现功能"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-programmer",
    roleName: "Digital Programmer",
    roleType: "DIGITAL_PROGRAMMER",
    chineseName: "数字程序员",
    englishName: "Digital Programmer",
    description: "把需求与对象转成代码任务、文件计划与测试建议。",
    coreResponsibility: ["生成实现方案", "生成文件结构", "生成测试建议", "处理技术债"],
    authorityLevel: "GENERATE",
    allowedActions: ["写实现计划", "出代码草案", "出测试建议"],
    forbiddenActions: ["声称已部署", "绕过 QA", "执行危险代码", "删除现有功能"],
    inputTypes: ["架构计划", "需求", "对象模型"],
    outputTypes: ["CODE_PLAN"],
    primaryEngines: ["Code Generation", "Sequence Object Architecture"],
    secondaryEngines: ["Software QA", "Recalculation"],
    requiredGuards: ["QA"],
    qaRequirements: ["代码必须 QA 通过"],
    workspaceWritePolicy: "DRAFT_ONLY",
    collaborationTargets: ["DIGITAL_ARCHITECT", "DIGITAL_QA"],
    conflictRisks: ["PROGRAMMER_VS_QA"],
    safetyNotes: ["不绕过 QA"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-planner",
    roleName: "Digital Planner",
    roleType: "DIGITAL_PLANNER",
    chineseName: "数字策划",
    englishName: "Digital Planner",
    description: "拆玩法、内容、活动与阶段性规划。",
    coreResponsibility: ["创作企划", "任务链设计", "体验流程", "阶段规划"],
    authorityLevel: "PLAN",
    allowedActions: ["出企划", "拆任务链", "设阶段"],
    forbiddenActions: ["无限扩张", "脱离开发成本", "与 CLM 冲突"],
    inputTypes: ["创意", "世界对象", "产品需求"],
    outputTypes: ["CONTENT_PLAN"],
    primaryEngines: ["Narrative Engine", "Cross-Functional Calculus"],
    secondaryEngines: ["CLM"],
    requiredGuards: ["CLM"],
    qaRequirements: ["规划必须接受 CLM Review"],
    workspaceWritePolicy: "ALLOWED",
    collaborationTargets: ["DIGITAL_WORLD_BUILDER", "DIGITAL_NARRATIVE_DIRECTOR", "DIGITAL_MUSIC_DIRECTOR"],
    conflictRisks: ["CREATIVE_VS_CLM"],
    safetyNotes: ["与 CLM 不冲突"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-designer",
    roleName: "Digital Designer",
    roleType: "DIGITAL_DESIGNER",
    chineseName: "数字设计师",
    englishName: "Digital Designer",
    description: "设计 UI/UX、视觉与角色/世界视觉 Prompt。",
    coreResponsibility: ["设计 UI/UX", "降低理解成本", "视觉风格", "页面结构"],
    authorityLevel: "DESIGN",
    allowedActions: ["出视觉草案", "出页面结构"],
    forbiddenActions: ["视觉破坏功能", "暴露 Founder-only"],
    inputTypes: ["产品需求", "品牌", "对象"],
    outputTypes: ["DOCS_DRAFT"],
    primaryEngines: ["Product Encyclopedia"],
    secondaryEngines: ["Vocabulary"],
    requiredGuards: ["QA"],
    qaRequirements: ["UI 必须可访问"],
    workspaceWritePolicy: "ALLOWED",
    collaborationTargets: ["DIGITAL_PRODUCT_MANAGER", "DIGITAL_GROWTH_STRATEGIST"],
    conflictRisks: ["PUBLIC_VS_FOUNDER"],
    safetyNotes: ["不暴露 Founder-only"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-researcher",
    roleName: "Digital Researcher",
    roleType: "DIGITAL_RESEARCHER",
    chineseName: "数字研究员",
    englishName: "Digital Researcher",
    description: "查资料、标可信度、区分现实与推演。",
    coreResponsibility: ["查资料", "标来源", "区分现实/推演", "生成证据"],
    authorityLevel: "SUGGEST",
    allowedActions: ["收集来源", "出证据映射"],
    forbiddenActions: ["伪造来源", "把未校准数据写成 VERIFIED", "忽略新鲜度"],
    inputTypes: ["问题", "现实数据", "系统输出"],
    outputTypes: ["RESEARCH_REPORT"],
    primaryEngines: ["Reality Data Calibration"],
    secondaryEngines: ["Vocabulary"],
    requiredGuards: ["QA"],
    qaRequirements: ["证据必须可追溯"],
    workspaceWritePolicy: "DRAFT_ONLY",
    collaborationTargets: ["DIGITAL_PRODUCT_MANAGER", "DIGITAL_GROWTH_STRATEGIST"],
    conflictRisks: ["RESEARCH_VS_MARKETING"],
    safetyNotes: ["不伪造证据"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-qa",
    roleName: "Digital QA",
    roleType: "DIGITAL_QA",
    chineseName: "数字 QA",
    englishName: "Digital QA",
    description: "检查功能、对象、Runtime、权限与隔离。",
    coreResponsibility: ["检查功能", "检查对象", "检查 Runtime", "检查权限", "检查 Demo/Real/Founder 隔离", "检测 Meaning Drift"],
    authorityLevel: "QA_BLOCK",
    allowedActions: ["阻断 CRITICAL", "出 QA 报告"],
    forbiddenActions: ["被其他角色绕过", "降低 CRITICAL 风险"],
    inputTypes: ["任意输出", "任意对象", "任意工作流"],
    outputTypes: ["QA_REPORT"],
    primaryEngines: ["Software QA"],
    secondaryEngines: ["Recalculation"],
    requiredGuards: [],
    qaRequirements: ["自身即 QA"],
    workspaceWritePolicy: "ALLOWED",
    collaborationTargets: ["DIGITAL_GOVERNANCE_OFFICER"],
    conflictRisks: ["FOUNDER_VS_QA", "PROGRAMMER_VS_QA"],
    safetyNotes: ["CRITICAL 必须 BLOCK"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-docs",
    roleName: "Digital Documentation Lead",
    roleType: "DIGITAL_DOCUMENTATION_LEAD",
    chineseName: "数字文档员",
    englishName: "Digital Documentation Lead",
    description: "维护教程、术语、产品百科与使用示例。",
    coreResponsibility: ["写 Learning Docs", "写 Usage Examples", "写 Quick Start", "维护 Vocabulary"],
    authorityLevel: "GENERATE",
    allowedActions: ["写文档", "更新术语"],
    forbiddenActions: ["使用过期术语", "遗漏安全边界"],
    inputTypes: ["产品需求", "对象", "工作流"],
    outputTypes: ["DOCS_DRAFT"],
    primaryEngines: ["Learning Docs", "Vocabulary"],
    secondaryEngines: ["Text Dynamic Update"],
    requiredGuards: ["QA"],
    qaRequirements: ["术语必须最新"],
    workspaceWritePolicy: "ALLOWED",
    collaborationTargets: ["DIGITAL_PRODUCT_MANAGER", "DIGITAL_QA"],
    conflictRisks: ["DUPLICATE_RESPONSIBILITY"],
    safetyNotes: ["术语保持最新"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-operator",
    roleName: "Digital Operator",
    roleType: "DIGITAL_OPERATOR",
    chineseName: "数字运营",
    englishName: "Digital Operator",
    description: "维护发布节奏、更新日志与用户反馈。",
    coreResponsibility: ["维护节奏", "整理日志", "管理反馈", "规划维护"],
    authorityLevel: "PLAN",
    allowedActions: ["排发布节奏"],
    forbiddenActions: ["虚假宣传", "承诺未上线功能"],
    inputTypes: ["版本", "用户反馈"],
    outputTypes: ["GROWTH_PLAN"],
    primaryEngines: ["Version Leap"],
    secondaryEngines: [],
    requiredGuards: ["QA"],
    qaRequirements: ["上线声明必须真实"],
    workspaceWritePolicy: "ALLOWED",
    collaborationTargets: ["DIGITAL_GROWTH_STRATEGIST"],
    conflictRisks: ["GROWTH_VS_GOVERNANCE"],
    safetyNotes: ["不虚假宣传"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-growth",
    roleName: "Digital Growth Strategist",
    roleType: "DIGITAL_GROWTH_STRATEGIST",
    chineseName: "数字增长官",
    englishName: "Digital Growth Strategist",
    description: "设计传播、对外话术与 Demo Showcase。",
    coreResponsibility: ["传播策略", "对外话术", "Demo Showcase", "PoC 包装"],
    authorityLevel: "PLAN",
    allowedActions: ["写传播草案", "包装 Demo"],
    forbiddenActions: ["过度营销", "把虚拟能力写成现实保证", "金融化数列货币"],
    inputTypes: ["产品", "Demo", "用户路径"],
    outputTypes: ["GROWTH_PLAN"],
    primaryEngines: ["Product Encyclopedia", "Cross-Functional Calculus"],
    secondaryEngines: [],
    requiredGuards: ["Governance"],
    qaRequirements: ["话术必须治理通过"],
    workspaceWritePolicy: "DRAFT_ONLY",
    collaborationTargets: ["DIGITAL_DESIGNER", "DIGITAL_DOCUMENTATION_LEAD"],
    conflictRisks: ["GROWTH_VS_GOVERNANCE", "RESEARCH_VS_MARKETING"],
    safetyNotes: ["禁止虚假宣传与金融化"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-governance",
    roleName: "Digital Governance Officer",
    roleType: "DIGITAL_GOVERNANCE_OFFICER",
    chineseName: "数字治理官",
    englishName: "Digital Governance Officer",
    description: "审查宪法、权限、高风险调用与 CLM。",
    coreResponsibility: ["Constitution 检查", "权限检查", "高风险调用检查", "CLM 检查"],
    authorityLevel: "GOVERNANCE_BLOCK",
    allowedActions: ["阻断 CRITICAL", "封存对象"],
    forbiddenActions: ["被普通角色覆盖", "降低 CRITICAL 风险"],
    inputTypes: ["任意工作流", "任意对象"],
    outputTypes: ["GOVERNANCE_REPORT"],
    primaryEngines: ["System Constitution", "CLM"],
    secondaryEngines: ["Software QA"],
    requiredGuards: [],
    qaRequirements: ["自身即治理"],
    workspaceWritePolicy: "ALLOWED",
    collaborationTargets: ["DIGITAL_QA"],
    conflictRisks: ["FOUNDER_VS_QA", "GROWTH_VS_GOVERNANCE"],
    safetyNotes: ["不可被覆盖"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-world",
    roleName: "Digital World Builder",
    roleType: "DIGITAL_WORLD_BUILDER",
    chineseName: "数字世界构筑师",
    englishName: "Digital World Builder",
    description: "生成世界、文明、世界规则。",
    coreResponsibility: ["生成世界", "生成文明", "生成规则", "接入多世界网络"],
    authorityLevel: "GENERATE",
    allowedActions: ["建世界对象"],
    forbiddenActions: ["把虚拟世界现实化", "污染 Real 数据"],
    inputTypes: ["策划", "母体数列"],
    outputTypes: ["WORLD_DRAFT"],
    primaryEngines: ["Sequence World Engine", "Multi-World Network"],
    secondaryEngines: ["Sequence Object Architecture"],
    requiredGuards: ["QA", "Constitution"],
    qaRequirements: ["世界必须 Demo/Real 隔离"],
    workspaceWritePolicy: "ALLOWED",
    collaborationTargets: ["DIGITAL_NARRATIVE_DIRECTOR", "DIGITAL_MUSIC_DIRECTOR"],
    conflictRisks: ["DEMO_VS_REAL"],
    safetyNotes: ["不现实化"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-narrative",
    roleName: "Digital Narrative Director",
    roleType: "DIGITAL_NARRATIVE_DIRECTOR",
    chineseName: "数字叙事导演",
    englishName: "Digital Narrative Director",
    description: "生成剧情、角色弧光、冲突与章节。",
    coreResponsibility: ["剧情", "角色弧光", "冲突", "章节"],
    authorityLevel: "GENERATE",
    allowedActions: ["写剧情草案"],
    forbiddenActions: ["破坏正典", "让角色意义漂移"],
    inputTypes: ["世界", "角色", "策划"],
    outputTypes: ["NARRATIVE_DRAFT"],
    primaryEngines: ["Narrative Engine", "Vocal Engine", "Prompt Forge"],
    secondaryEngines: ["Sequence Object Architecture"],
    requiredGuards: ["QA"],
    qaRequirements: ["不破坏正典"],
    workspaceWritePolicy: "DRAFT_ONLY",
    collaborationTargets: ["DIGITAL_MUSIC_DIRECTOR", "DIGITAL_WORLD_BUILDER"],
    conflictRisks: ["CREATIVE_VS_CLM"],
    safetyNotes: ["不漂移"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-music",
    roleName: "Digital Music Director",
    roleType: "DIGITAL_MUSIC_DIRECTOR",
    chineseName: "数字音乐总监",
    englishName: "Digital Music Director",
    description: "设计歌曲主题、声乐风格与 Suno/Udio Prompt。",
    coreResponsibility: ["歌曲主题", "声乐风格", "Suno/Udio Prompt"],
    authorityLevel: "GENERATE",
    allowedActions: ["生成 Prompt 草案"],
    forbiddenActions: ["承诺现实版权安全", "忽略平台限制"],
    inputTypes: ["角色", "世界", "剧情"],
    outputTypes: ["MUSIC_PROMPT"],
    primaryEngines: ["Vocal Engine", "Translation Engine", "Prompt Forge"],
    secondaryEngines: [],
    requiredGuards: ["QA"],
    qaRequirements: ["不做版权承诺"],
    workspaceWritePolicy: "DRAFT_ONLY",
    collaborationTargets: ["DIGITAL_NARRATIVE_DIRECTOR"],
    conflictRisks: ["DEMO_VS_REAL"],
    safetyNotes: ["不替平台担保"],
    version: "v1.0",
    status: "ACTIVE",
  },
  {
    roleId: "role-system-strategist",
    roleName: "Digital System Strategist",
    roleType: "DIGITAL_SYSTEM_STRATEGIST",
    chineseName: "数字系统战略官",
    englishName: "Digital System Strategist",
    description: "调用 Missing-Layer Detection，判断下一步补层或整合。",
    coreResponsibility: ["调用 Missing-Layer", "判断补层", "判断暂停扩张", "生成路线图"],
    authorityLevel: "PLAN",
    allowedActions: ["出系统路线图", "建议整合"],
    forbiddenActions: ["无限建议新增", "在过度生长时仍建议扩张"],
    inputTypes: ["系统状态", "缺层报告"],
    outputTypes: ["SYSTEM_ROADMAP"],
    primaryEngines: ["Missing-Layer Detection", "Version Leap"],
    secondaryEngines: ["Sequence Object Architecture", "Cross-Functional Calculus"],
    requiredGuards: ["Governance"],
    qaRequirements: ["路线图必须 QA"],
    workspaceWritePolicy: "ALLOWED",
    collaborationTargets: ["DIGITAL_ARCHITECT", "DIGITAL_GOVERNANCE_OFFICER"],
    conflictRisks: ["DUPLICATE_RESPONSIBILITY"],
    safetyNotes: ["过度生长时必须建议整合"],
    version: "v1.0",
    status: "ACTIVE",
  },
];

export function listDigitalRoles(): DigitalRole[] {
  return DIGITAL_ROLE_REGISTRY;
}

export function getDigitalRoleByType(type: DigitalRoleType): DigitalRole | undefined {
  return DIGITAL_ROLE_REGISTRY.find((r) => r.roleType === type);
}

export function getDigitalRoleById(id: string): DigitalRole | undefined {
  return DIGITAL_ROLE_REGISTRY.find((r) => r.roleId === id);
}
