// L0-L10 层级定义 + 现有模块清单
// 数据来源：Aetherworld 当前已合并的模块（依据 src/lib 目录与历史 Bridge Plan 静态汇总）。
// 这里采用静态映射，避免在前端做文件系统扫描；后续可由 Product Self-Evolution 自动回填。

import type { LayerAspect, LayerAspectStatus, LayerDefinition } from "./layerAuditTypes";

export const LAYER_DEFINITIONS: LayerDefinition[] = [
  {
    layerId: "L0",
    layerName: "基础安全层",
    cnDescription: "Secret / Permission / Safety / Founder / QA 等系统级守门。",
    expectedSystems: [
      "Secret Guard",
      "Permission Guard",
      "Safety Policy",
      "Founder-only",
      "Full60 防泄漏",
      "Social Publish Guard",
      "Model Context Sanitizer",
      "QA / Bug Audit",
    ],
  },
  {
    layerId: "L1",
    layerName: "模型与推理层",
    cnDescription: "LLM Provider / Ollama / WebLLM / Local Gateway / Fallback。",
    expectedSystems: [
      "LLM Provider",
      "Ollama",
      "WebLLM",
      "Local Gateway",
      "Model Test",
      "Provider Resolver",
      "Streaming",
      "Fallback",
    ],
  },
  {
    layerId: "L2",
    layerName: "对话与输入层",
    cnDescription: "Chat 主链路 / 结果卡 / 工具调用 / 提示词模式 / 意图。",
    expectedSystems: [
      "Chat",
      "ChatDisplayResult",
      "Chat Result Cards",
      "Tool Calling",
      "Prompt Mode",
      "User Intent",
      "Message State",
    ],
  },
  {
    layerId: "L3",
    layerName: "跨域融合层",
    cnDescription: "Fusion Runtime / 五域 / 计算法链 / 常数宇宙 / WebLCM。",
    expectedSystems: [
      "Fusion Runtime",
      "ENGINE_WEIGHT_CONSTANTS",
      "Five Domain",
      "Calculus Chain",
      "Constants Universe",
      "WebLCM Concept Graph",
      "Fusion Info Panel",
    ],
  },
  {
    layerId: "L4",
    layerName: "数列底座层",
    cnDescription: "Sequence Memory / Currency / MSL / Prediction / Agent / AI / Mother。",
    expectedSystems: [
      "Sequence Memory",
      "Sequence Currency",
      "MSL State Language",
      "Sequence Prediction",
      "Sequence Agent",
      "Sequence AI",
      "Sequence Objects",
      "MSL Terminal",
      "Mother Sequence",
    ],
  },
  {
    layerId: "L5",
    layerName: "对象与工作区层",
    cnDescription: "Workspace / Projects / Objects / Save / Load / Version / Tags / Relations。",
    expectedSystems: [
      "Workspace",
      "Projects",
      "Objects",
      "Object Types",
      "Save / Load",
      "Version",
      "Tags",
      "Relations",
    ],
  },
  {
    layerId: "L6",
    layerName: "工具与执行层",
    cnDescription: "Store / WebXXM / App Runtime / Sandbox / 吸收 / 项目融合 / 工具调用。",
    expectedSystems: [
      "Store / WebXXM",
      "App Runtime",
      "Code Sandbox",
      "Open Architecture Absorption",
      "Project Fusion",
      "Local Tool Calling",
      "Capability Registry",
    ],
  },
  {
    layerId: "L7",
    layerName: "任务与调度层",
    cnDescription: "Scheduler / Calendar / Review / State Machine / ExecutionPlan / Reminder。",
    expectedSystems: [
      "Scheduler",
      "Calendar Trigger",
      "Review Nodes",
      "Task State Machine",
      "ExecutionPlan",
      "Queue",
      "Automation",
      "Reminder",
    ],
  },
  {
    layerId: "L8",
    layerName: "记录、统计、回验层",
    cnDescription: "Record / Analytics / Verification / Weight / Replay / Usage。",
    expectedSystems: [
      "Record Center",
      "Analytics",
      "Verification Center",
      "Record Weight",
      "Bug Audit",
      "QA",
      "Replay Center",
      "Usage Record",
    ],
  },
  {
    layerId: "L9",
    layerName: "生态与外部吸收层",
    cnDescription: "Social / Store Ecosystem / 开源吸收 / 项目融合 / 联网 / 外部源。",
    expectedSystems: [
      "Social",
      "Store Ecosystem",
      "Open Architecture Absorption",
      "Same-Account Project Fusion",
      "Imaginative Fusion",
      "Network Runtime",
      "GitHub / Docs / External Source",
    ],
  },
  {
    layerId: "L10",
    layerName: "自进化与文明层",
    cnDescription: "产品自进化 / Legacy / 虚拟生活 / 虚拟世界 / 文明 / 事件算法 / 进化图谱。",
    expectedSystems: [
      "Product Self-Evolution",
      "Legacy Module Registry",
      "Virtual Life OS",
      "Virtual World OS",
      "Civilizational Layer",
      "World Engine",
      "Event Algorithm",
      "System Evolution Map",
    ],
  },
];

/**
 * 每层四象的静态评估表。
 * existing: 当前真实已落地（基于代码扫描 + Bridge Plan 静态结论）
 * missing : 暂未接入或仅占位
 * duplicated: 存在多套同义实现需要合并
 * score   : 0-100 启发式打分（高=已成型）
 */
export interface LayerAspectSnapshot {
  layerId: string;
  aspect: LayerAspect;
  existing: string[];
  missing: string[];
  duplicated: string[];
  score: number;
  notes: string;
}

export const LAYER_ASPECT_SNAPSHOTS: LayerAspectSnapshot[] = [
  // ───────────────────────────── L0 基础安全层 ─────────────────────────────
  { layerId: "L0", aspect: "SKELETON", score: 80,
    existing: ["safetyPolicy", "permissionGuard", "secretGuard", "founder roles enum"],
    missing: ["统一 L0 Permission Boundary Registry", "全链路 QA Status Enum"],
    duplicated: ["safetyPolicy 在多个 runtime 内被重复实现"],
    notes: "守门类型与常量已具备，缺一份顶层 Permission Registry。" },
  { layerId: "L0", aspect: "MUSCLE", score: 70,
    existing: ["modelContextSanitizer", "socialPublishGuard", "QA runtime"],
    missing: ["统一 Safety Executor", "跨模块 Fallback 链"],
    duplicated: ["多处自实现脱敏逻辑"],
    notes: "执行件已分散落地，缺顶层统一执行器。" },
  { layerId: "L0", aspect: "BLOOD", score: 55,
    existing: ["Bug Audit 已落 Record Center"],
    missing: ["Safety 决策回写 Record Center", "Permission 拒绝事件落 Analytics"],
    duplicated: [],
    notes: "安全决策大多未沉淀为可回验的事件。" },
  { layerId: "L0", aspect: "NERVE", score: 60,
    existing: ["QA Notice", "Founder Audit"],
    missing: ["Permission 拒绝统一通知", "Safety Review Node 自动触发"],
    duplicated: [],
    notes: "异常时缺乏统一的回路通知。" },

  // ───────────────────────────── L1 模型与推理层 ─────────────────────────────
  { layerId: "L1", aspect: "SKELETON", score: 85,
    existing: ["LLM Provider Registry", "Provider Resolver", "Streaming State"],
    missing: ["统一 Provider Capability Enum"],
    duplicated: ["Ollama / OpenAI-Compat 配置结构略有重复"],
    notes: "Provider 抽象完整，缺能力位枚举。" },
  { layerId: "L1", aspect: "MUSCLE", score: 80,
    existing: ["llmProviderRuntime", "realWebLlmRuntime", "rule fallback"],
    missing: ["Stop Generation 统一 AbortController", "Local Gateway 真实通道"],
    duplicated: [],
    notes: "三层 fallback 已存在，缺中止与本地网关。" },
  { layerId: "L1", aspect: "BLOOD", score: 60,
    existing: ["modelCall 已落 Record Center", "Currency 计费已接入"],
    missing: ["Provider 失败原因落 Analytics 分布"],
    duplicated: [],
    notes: "成功路径已沉淀，失败原因尚未结构化。" },
  { layerId: "L1", aspect: "NERVE", score: 55,
    existing: ["chatProviderResolver 通知"],
    missing: ["Provider 健康检查 Scheduler 任务", "Provider 切换 Event Bus"],
    duplicated: [],
    notes: "缺乏主动健康检查与切换通知。" },

  // ───────────────────────────── L2 对话与输入层 ─────────────────────────────
  { layerId: "L2", aspect: "SKELETON", score: 90,
    existing: ["chatMessageEngine", "ChatDisplayResult 类型", "Prompt Mode Router"],
    missing: [],
    duplicated: ["info 字段在 ChatMessage 上逐个挂载，已开始拥挤"],
    notes: "类型层非常完整，但 ChatMessage 字段需重整。" },
  { layerId: "L2", aspect: "MUSCLE", score: 85,
    existing: ["chatAnswerStreamingRuntime", "tool calling runtime", "intent resolver"],
    missing: ["Chat 失败统一恢复器"],
    duplicated: [],
    notes: "执行链路已稳定，缺失败恢复抽象。" },
  { layerId: "L2", aspect: "BLOOD", score: 80,
    existing: ["Chat Turn → Record / Memory / Currency / MSL"],
    missing: ["Chat 工具调用结果统一回写"],
    duplicated: [],
    notes: "主链路血液已通，工具旁路尚未串。" },
  { layerId: "L2", aspect: "NERVE", score: 70,
    existing: ["QA Notice", "Tool Confirmation"],
    missing: ["Chat 错误 → Scheduler 重试任务"],
    duplicated: [],
    notes: "缺把错误转为可调度修复任务的回路。" },

  // ───────────────────────────── L3 跨域融合层 ─────────────────────────────
  { layerId: "L3", aspect: "SKELETON", score: 80,
    existing: ["Fusion types", "Five Domain", "Constants Universe", "WebLCM Concept Graph"],
    missing: ["Fusion Capability Registry"],
    duplicated: [],
    notes: "结构齐备，缺一份「融合能力可被外部查询」的注册表。" },
  { layerId: "L3", aspect: "MUSCLE", score: 75,
    existing: ["fusionRuntime", "calculusChain", "fallback builder"],
    missing: ["跨域 Adapter（Memory↔Currency↔MSL 三角）"],
    duplicated: [],
    notes: "主 runtime 完整，跨数列对象的适配器还在分散。" },
  { layerId: "L3", aspect: "BLOOD", score: 70,
    existing: ["fusionPlan → Record Center"],
    missing: ["Fusion drift 落 Analytics 时序"],
    duplicated: [],
    notes: "结果已记录，过程指标未沉淀。" },
  { layerId: "L3", aspect: "NERVE", score: 60,
    existing: ["drift notice"],
    missing: ["Fusion 失败自动触发回验"],
    duplicated: [],
    notes: "缺 Verification 触发器。" },

  // ───────────────────────────── L4 数列底座层 ─────────────────────────────
  { layerId: "L4", aspect: "SKELETON", score: 85,
    existing: ["Sequence Memory / Currency / MSL / Prediction / Agent / AI 类型"],
    missing: ["Sequence Objects 统一注册表", "Mother Sequence Boundary"],
    duplicated: [],
    notes: "九大底座类型已存在，缺顶层对象注册表。" },
  { layerId: "L4", aspect: "MUSCLE", score: 75,
    existing: ["compressor / predictor / agent runtime / sequence-ai runtime"],
    missing: ["Mother Sequence Runtime", "MSL Terminal Executor"],
    duplicated: [],
    notes: "运行件主要齐全，母数列尚未运行时化。" },
  { layerId: "L4", aspect: "BLOOD", score: 80,
    existing: ["Memory / Currency / MSL / Prediction 互相桥接 + 落 Record"],
    missing: [],
    duplicated: ["Memory 与 Record 内容存在概念重叠"],
    notes: "血液通畅，需明确 Memory 与 Record 的边界。" },
  { layerId: "L4", aspect: "NERVE", score: 65,
    existing: ["Scheduler ↔ Prediction 部分接入"],
    missing: ["Currency 异常 → Scheduler 告警", "MSL 异常态 → 通知"],
    duplicated: [],
    notes: "底座异常态尚未形成主动神经反射。" },

  // ───────────────────────────── L5 对象与工作区层 ─────────────────────────────
  { layerId: "L5", aspect: "SKELETON", score: 75,
    existing: ["Workspace 类型", "Object Types", "Tags"],
    missing: ["Object Relations 统一模型", "Version Schema"],
    duplicated: [],
    notes: "对象骨架基本齐，关系与版本仍缺。" },
  { layerId: "L5", aspect: "MUSCLE", score: 65,
    existing: ["save / load runtime"],
    missing: ["跨对象 Relations Resolver", "对象搜索/筛选"],
    duplicated: [],
    notes: "保存/加载完备，复杂查询能力不足。" },
  { layerId: "L5", aspect: "BLOOD", score: 60,
    existing: ["对象保存 → Record"],
    missing: ["对象变更 → Memory / Analytics"],
    duplicated: [],
    notes: "对象改动未充分喂给数列底座。" },
  { layerId: "L5", aspect: "NERVE", score: 50,
    existing: ["保存提示"],
    missing: ["对象冲突 Review Node", "Version diff 通知"],
    duplicated: [],
    notes: "对象冲突缺乏回路。" },

  // ───────────────────────────── L6 工具与执行层 ─────────────────────────────
  { layerId: "L6", aspect: "SKELETON", score: 80,
    existing: ["Store / WebXXM", "App Runtime", "Code Sandbox", "Capability Registry"],
    missing: ["Tool 调用统一权限层"],
    duplicated: ["Project Fusion / Open Architecture Absorption 注册结构相似"],
    notes: "工具层骨架完整，权限边界需统一。" },
  { layerId: "L6", aspect: "MUSCLE", score: 70,
    existing: ["openArchitectureAnalyzer", "projectFusionAnalyzer", "Code Sandbox runtime"],
    missing: ["Tool Executor Fallback", "Patch Application Runtime"],
    duplicated: [],
    notes: "分析器丰富，缺统一回退与补丁落地。" },
  { layerId: "L6", aspect: "BLOOD", score: 60,
    existing: ["工具结果 → Record / Workspace"],
    missing: ["工具消耗 → Currency", "工具结果 → Memory"],
    duplicated: [],
    notes: "工具血液只通了「保存」一端。" },
  { layerId: "L6", aspect: "NERVE", score: 65,
    existing: ["Tool Confirmation", "Safety Policy"],
    missing: ["工具失败 Scheduler 复查任务", "Tool Permission Guard 细粒度"],
    duplicated: [],
    notes: "失败回路尚未自动化。" },

  // ───────────────────────────── L7 任务与调度层 ─────────────────────────────
  { layerId: "L7", aspect: "SKELETON", score: 80,
    existing: ["Scheduler 类型", "Task State Machine", "ExecutionPlan"],
    missing: ["Review Nodes 统一注册"],
    duplicated: [],
    notes: "调度骨架完整，Review 节点需注册化。" },
  { layerId: "L7", aspect: "MUSCLE", score: 75,
    existing: ["Scheduler runtime", "Calendar trigger", "Automation"],
    missing: ["并发执行器", "失败自动修复策略"],
    duplicated: [],
    notes: "顺序推进可用，并发与自愈缺位。" },
  { layerId: "L7", aspect: "BLOOD", score: 70,
    existing: ["Scheduler 任务 → Record / Currency"],
    missing: ["Scheduler 任务 → MSL 状态"],
    duplicated: [],
    notes: "调度未充分写入 MSL。" },
  { layerId: "L7", aspect: "NERVE", score: 65,
    existing: ["Reminder", "Calendar notice"],
    missing: ["Scheduler 失败 → 自动新建修复任务"],
    duplicated: [],
    notes: "失败 → 修复任务的自反射缺失。" },

  // ───────────────────────────── L8 记录、统计、回验层 ─────────────────────────────
  { layerId: "L8", aspect: "SKELETON", score: 75,
    existing: ["Record Center 类型", "Bug Audit", "Analytics 类型"],
    missing: ["Verification Center 类型注册", "Replay Center 类型"],
    duplicated: [],
    notes: "记录与统计骨架齐，回验与回放尚为占位。" },
  { layerId: "L8", aspect: "MUSCLE", score: 60,
    existing: ["Record Runtime", "Analytics Runtime"],
    missing: ["Verification Runner", "Replay Runner", "Record Weight Updater"],
    duplicated: [],
    notes: "回验与回放无真实运行件。" },
  { layerId: "L8", aspect: "BLOOD", score: 55,
    existing: ["Record 自循环"],
    missing: ["Verification 结果 → Memory / Currency"],
    duplicated: [],
    notes: "回验数据无法回流到底座。" },
  { layerId: "L8", aspect: "NERVE", score: 55,
    existing: ["QA Bug Audit"],
    missing: ["Verification 触发 Scheduler", "Replay 触发 Notice"],
    duplicated: [],
    notes: "回验/回放尚未形成神经回路。" },

  // ───────────────────────────── L9 生态与外部吸收层 ─────────────────────────────
  { layerId: "L9", aspect: "SKELETON", score: 80,
    existing: ["Open Arch / Project Fusion / Imaginative Fusion / Network 类型"],
    missing: ["External Source 统一注册表"],
    duplicated: ["Project Fusion 与 Imaginative Fusion 概念存在重叠"],
    notes: "外部吸收骨架完整，需要顶层 Source Registry。" },
  { layerId: "L9", aspect: "MUSCLE", score: 70,
    existing: ["Network Runtime", "Open Arch Analyzer", "Project Fusion Analyzer"],
    missing: ["GitHub API 真实拉取", "搜索引擎接入"],
    duplicated: [],
    notes: "执行件齐，外部信息源受限。" },
  { layerId: "L9", aspect: "BLOOD", score: 55,
    existing: ["Network → Record"],
    missing: ["外部源 → Memory / Currency", "Social 发布 → Record"],
    duplicated: [],
    notes: "外部血液未流回底座。" },
  { layerId: "L9", aspect: "NERVE", score: 50,
    existing: ["Social Publish Guard"],
    missing: ["外部源变化 Scheduler 周期复查", "License 风险通知"],
    duplicated: [],
    notes: "缺周期复查与合规通知。" },

  // ───────────────────────────── L10 自进化与文明层 ─────────────────────────────
  { layerId: "L10", aspect: "SKELETON", score: 65,
    existing: ["Legacy Module Registry", "Product Self-Evolution 类型", "Virtual World OS 骨架"],
    missing: ["Civilizational Layer 类型", "World Engine 统一接口"],
    duplicated: ["Virtual Life OS / Virtual World OS 概念重叠"],
    notes: "文明层骨架最弱，多模块在概念上待合并。" },
  { layerId: "L10", aspect: "MUSCLE", score: 45,
    existing: ["evolutionRecommendationEngine"],
    missing: ["World Engine Runtime", "Civilization Simulator"],
    duplicated: [],
    notes: "自进化建议器已有，文明级执行件几乎空缺。" },
  { layerId: "L10", aspect: "BLOOD", score: 40,
    existing: ["Bug Audit → Evolution 输入"],
    missing: ["Memory / Currency / MSL / Record 全量喂给自进化"],
    duplicated: [],
    notes: "自进化只读到部分血液，文明层尚无血液。" },
  { layerId: "L10", aspect: "NERVE", score: 40,
    existing: ["Legacy Registry 引导"],
    missing: ["Self-Evolution 自动生成 Lovable Prompt", "文明事件 Event Bus"],
    duplicated: [],
    notes: "顶层缺乏神经反射弧。" },
];

export function snapshotsForLayer(layerId: string): LayerAspectSnapshot[] {
  return LAYER_ASPECT_SNAPSHOTS.filter((s) => s.layerId === layerId);
}

export function snapshotToStatus(s: LayerAspectSnapshot): LayerAspectStatus {
  return {
    score: s.score,
    existing: s.existing,
    missing: s.missing,
    duplicated: s.duplicated,
    notes: s.notes,
  };
}
