// 计算法宇宙注册表 / Calculus Universe Registry
// Aetherworld 所有计算法的统一登记。条目用于 Encyclopedia / Usage Examples / Learning Docs 接入。

export type CalculusMaturity =
  | "CONCEPT"
  | "DRAFT"
  | "ACTIVE"
  | "EXPERIMENTAL"
  | "FOUNDER_ONLY";

export interface CalculusEntry {
  id: string;
  chineseName: string;
  englishName: string;
  category: CalculusCategoryId;
  userExplanation: string;
  technicalExplanation: string;
  inputTypes: string[];
  outputTypes: string[];
  relatedEngines: string[];
  relatedModules: string[];
  exampleInput: string;
  expectedOutput: string;
  safetyBoundary: string;
  maturity: CalculusMaturity;
}

export type CalculusCategoryId =
  | "A_SEQUENCE_BASE"
  | "B_SUBJECT_FOUNDER"
  | "C_OBJECT_THINGS"
  | "D_GENERATION"
  | "E_WORLD_LIFE"
  | "F_SYSTEM_GOV"
  | "G_QA_FEEDBACK"
  | "H_VALUE_RESOURCE"
  | "I_DIGITAL_SCIENCE"
  | "J_MYTH_SYMBOL";

export const CALCULUS_CATEGORIES: { id: CalculusCategoryId; title: string; en: string; desc: string }[] = [
  { id: "A_SEQUENCE_BASE",   title: "数列基础计算法",           en: "Sequence Base Calculi",        desc: "母体数列、MSL、五域、操作码、常数映射等基础结构层。" },
  { id: "B_SUBJECT_FOUNDER", title: "主体与创始人计算法",       en: "Subject & Founder Calculi",    desc: "主体模式、Light20 / Full60、Founder Subject、创始人权限。" },
  { id: "C_OBJECT_THINGS",   title: "对象与万物计算法",         en: "Object & Thing-Itself Calculi",desc: "对象本体、价值、风险、演化与万物破解。" },
  { id: "D_GENERATION",      title: "生成类计算法",             en: "Generation Calculi",           desc: "模型、代码、文案、剧情、声乐、翻译、Prompt、示例生成。" },
  { id: "E_WORLD_LIFE",      title: "世界与虚拟生活计算法",     en: "World & Virtual Life Calculi", desc: "世界生成、模拟、社会、文明演化与虚拟生活。" },
  { id: "F_SYSTEM_GOV",      title: "系统治理计算法",           en: "System Governance Calculi",    desc: "常数宇宙、宪法、权限、安全边界、UI/文本更新、版本跃迁。" },
  { id: "G_QA_FEEDBACK",     title: "质量与回验计算法",         en: "QA & Feedback Calculi",        desc: "软件 QA、回验、重新计算、过期检测、审计、发布就绪。" },
  { id: "H_VALUE_RESOURCE",  title: "价值与资源计算法",         en: "Value & Resource Calculi",     desc: "数列货币、内部价值、世界资源、贡献评分、资产估值（虚拟）。" },
  { id: "I_DIGITAL_SCIENCE", title: "扩展现实科学计算法",       en: "Digital Science Calculi",      desc: "数字物理 / 化学 / 地理 / 天文 / 生物及自进化阶梯。" },
  { id: "J_MYTH_SYMBOL",     title: "神话 / 潜意识 / 高阶象征计算法", en: "Myth & Symbol Calculi",   desc: "潜意识调用、神明生成、象征映射、九核执行人格。" },
];

const c = (
  id: string, zh: string, en: string, category: CalculusCategoryId,
  userExp: string, techExp: string,
  inputTypes: string[], outputTypes: string[],
  relatedEngines: string[], relatedModules: string[],
  exampleInput: string, expectedOutput: string,
  maturity: CalculusMaturity = "ACTIVE",
  safetyBoundary = "结构化推演与产品内部生成，不构成现实预测或医疗 / 法律 / 金融 / 心理 / 工程专业判断。",
): CalculusEntry => ({
  id, chineseName: zh, englishName: en, category,
  userExplanation: userExp, technicalExplanation: techExp,
  inputTypes, outputTypes, relatedEngines, relatedModules,
  exampleInput, expectedOutput, safetyBoundary, maturity,
});

export const CALCULUS_REGISTRY: CalculusEntry[] = [
  // A 数列基础
  c("mother-sequence-calculus", "母体数列计算法", "Mother Sequence Calculus", "A_SEQUENCE_BASE",
    "把任何对象映射成可推演的母体数列。", "对输入对象抽取定数 / 变数 / 关系链，生成母体数列骨架并交由 MSL 解析。",
    ["对象", "问题", "事件", "产品"], ["母体数列", "结构骨架", "可解析符号串"],
    ["Sequence AI", "MSL", "Free Input"], ["/free-input", "/sequence"],
    "把这段产品描述转成母体数列。", "{定数:..., 变数:..., 关系链:...}",
    "ACTIVE"),
  c("msl-parser-calculus", "MSL 解析计算法", "MSL Parser Calculus", "A_SEQUENCE_BASE",
    "把母体数列语言翻译成结构化指令。", "Mother Sequence Language 词法 / 句法解析，输出 AST 与执行计划。",
    ["MSL 文本"], ["AST", "执行计划", "权限标记"],
    ["MSL Engine", "Sequence Terminal"], ["/msl", "/sequence-terminal"],
    "msl: predict( subject=demo, window=7d )", "{op:predict, args:{...}}"),
  c("five-domain-calculus", "五域计算法", "Five-Domain Calculus", "A_SEQUENCE_BASE",
    "把对象分到五个相互制衡的域里看。", "在身 / 心 / 事 / 物 / 时五域上做加权评分与相互作用解算。",
    ["对象状态", "主体上下文"], ["五域分布", "失衡警示"],
    ["Subject Mode Resolver"], ["/subject"],
    "评估当前主体五域分布。", "{身:0.6,心:0.4,事:0.7,物:0.5,时:0.55}"),
  c("digit-opcode-calculus", "数字操作码计算法", "Digit Opcode Calculus", "A_SEQUENCE_BASE",
    "数字本身就是命令。", "0-9 与扩展位的语义化操作码映射，驱动数列层操作执行。",
    ["数字串"], ["操作序列"], ["Sequence AI"], ["/sequence"],
    "解码 3141592653", "{ops:[π-cycle, expand, ...]}"),
  c("constant-mapping-calculus", "常数映射计算法", "Constant Mapping Calculus", "A_SEQUENCE_BASE",
    "把对象贴到系统常数上。", "对象 → 常数宇宙坐标的映射，提供稳定锚点。",
    ["对象"], ["常数坐标"], ["Constant Universe"], ["/constants"],
    "把这次发布映射到常数。", "{constant:'release-cycle', coord:...}"),
  c("calculus-universe-meta-calculus", "计算法宇宙总计算法", "Calculus Universe Meta-Calculus", "A_SEQUENCE_BASE",
    "管理“管理计算法的计算法”。", "元层注册、依赖、版本与成熟度治理，是其他计算法的注册总线。",
    ["计算法定义", "依赖图"], ["注册表快照", "依赖警告"], ["Calculus Universe"], ["/encyclopedia-entry?id=calculus-universe-encyclopedia"],
    "列出所有 EXPERIMENTAL 计算法。", "{count:N, entries:[...]}"),

  // B 主体 / 创始人
  c("subject-mode-calculus", "主体模式计算法", "Subject Mode Calculus", "B_SUBJECT_FOUNDER",
    "判断当前是 Demo / 真实 / Founder 哪种主体。", "Subject Mode Resolver 的判定与切换逻辑。",
    ["会话上下文", "用户角色"], ["subjectMode"], ["Subject Mode Resolver"], ["/subject"],
    "当前是哪个主体模式？", "FULL60 / LIGHT20 / DEMO / FOUNDER"),
  c("light20-calculus", "Light20 计算法", "Light20 Calculus", "B_SUBJECT_FOUNDER",
    "用 20 个轻量信号给你画像。", "20 维轻量主体特征收集与初步聚合。",
    ["20 项问答"], ["轻量主体画像"], ["Subject Engine"], ["/subject/light20"],
    "完成 Light20。", "{traits:{...}}"),
  c("full60-calculus", "Full60 计算法", "Full60 Calculus", "B_SUBJECT_FOUNDER",
    "用 60 个信号建立深度主体。", "60 维深度主体建模与稳定性回验。",
    ["60 项问答", "历史回验"], ["深度主体模型"], ["Subject Engine"], ["/subject/full60"],
    "构建 Full60 主体。", "{model:{...}, privacyNote:true}",
    "ACTIVE",
    "Full60 涉及更深的个人信号，请确认已阅读隐私提示。"),
  c("founder-subject-calculus", "Founder Subject 计算法", "Founder Subject Calculus", "B_SUBJECT_FOUNDER",
    "创始人专属主体建模。", "Founder 私有主体特征与权限标记。",
    ["Founder 会话"], ["Founder 主体"], ["Founder Engine"], ["/founder"],
    "进入创始人主体。", "{role:'founder', perms:[...]}",
    "FOUNDER_ONLY"),
  c("founder-calculus", "创始人计算法", "Founder Calculus", "B_SUBJECT_FOUNDER",
    "创始人能动什么、不能动什么。", "Founder 行为边界与升级路径。",
    ["Founder 操作"], ["许可 / 拒绝"], ["Founder Engine"], ["/founder"],
    "Founder 修改宪法。", "{allowed:true, audit:true}",
    "FOUNDER_ONLY"),
  c("founder-password-calculus", "创始人密码计算法", "Founder Password Calculus", "B_SUBJECT_FOUNDER",
    "本地创始人密码哈希。", "PBKDF2-SHA256 本地哈希，不上传。",
    ["明文密码"], ["哈希"], ["Founder Engine"], ["/founder"],
    "设定创始人密码。", "{ok:true}",
    "FOUNDER_ONLY"),
  c("founder-permission-calculus", "创始人权限计算法", "Founder Permission Calculus", "B_SUBJECT_FOUNDER",
    "按等级×风险给出权限。", "5 级 role × 模块 riskLevel 矩阵。",
    ["role", "module"], ["allow/deny"], ["Founder Engine"], ["/founder"],
    "L3 能否动 sequence-currency？", "deny"),

  // C 对象 / 万物
  c("thing-itself-calculus", "万物本身计算法", "Thing-Itself Calculus", "C_OBJECT_THINGS",
    "先看清这个东西本身是什么，再说预测。", "提取对象定义 / 不变量 / 动态变量 / 关系链 / 风险 / 可验证输出，作为多数任务的前置层。",
    ["对象", "问题", "产品", "关系", "世界设定", "数列"], ["对象定义", "不变量", "动态变量", "关系链", "风险", "下一步动作", "回验点"],
    ["Free Input", "Sequence AI", "Model Generation", "World Knowledge", "Hybrid Compression"], ["/free-input"],
    "这个产品到底是什么？", "{definition:..., invariants:[...], risks:[...]}"),
  c("thing-crack-calculus", "万物破解计算法", "Thing-Crack Calculus", "C_OBJECT_THINGS",
    "找到一个对象最关键的那一层。", "在 Thing-Itself 之上做关键路径与杠杆点提取。",
    ["对象本体"], ["关键变量", "杠杆点"], ["Free Input"], ["/free-input"],
    "破解这场谈判。", "{leverage:[...], risk:[...]}",
    "EXPERIMENTAL"),
  c("object-entity-calculus", "对象本体计算法", "Object Entity Calculus", "C_OBJECT_THINGS",
    "建立对象的稳定身份。", "对象 ID / 类型 / 不变量持久化。",
    ["对象"], ["entity 记录"], ["Object Registry"], ["/objects"],
    "登记一个新对象。", "{id:..., type:...}"),
  c("object-value-calculus", "对象价值计算法", "Object Value Calculus", "C_OBJECT_THINGS",
    "估出对象的内部价值。", "结合稀缺性、关系密度、回验权重。",
    ["对象"], ["内部价值分"], ["Value Engine"], ["/value"],
    "估值这个虚拟物品。", "{value:0.72}"),
  c("object-risk-calculus", "对象风险计算法", "Object Risk Calculus", "C_OBJECT_THINGS",
    "评估对象潜在风险。", "失稳概率 × 影响半径。",
    ["对象"], ["风险等级"], ["Risk Engine"], ["/risk"],
    "评估这次发布风险。", "{risk:'MEDIUM'}"),
  c("object-evolution-calculus", "对象演化计算法", "Object Evolution Calculus", "C_OBJECT_THINGS",
    "看对象未来如何演化。", "依据历史轨迹与系统常数推演下一阶段。",
    ["对象历史"], ["演化路径"], ["Evolution Engine"], ["/evolution"],
    "演化这个角色。", "{nextStages:[...]}"),

  // D 生成
  c("model-generation-calculus", "模型生成计算法", "Model Generation Calculus", "D_GENERATION",
    "为对象自动生成可运行模型。", "从对象本体到可执行模型骨架的转换。",
    ["对象本体"], ["可执行模型"], ["Model Generation"], ["/model-generation"],
    "生成产品评估模型。", "{model:..., entries:[...]}"),
  c("code-generation-calculus", "代码生成计算法", "Code Generation Calculus", "D_GENERATION",
    "把意图变成可运行代码草稿。", "意图 → 代码骨架，再交由用户/Founder 审核。",
    ["意图描述"], ["代码草稿"], ["Code Engine"], ["/code"],
    "生成一个 React 组件骨架。", "<Component .../> 草稿"),
  c("copy-generation-calculus", "文案生成计算法", "Copy Generation Calculus", "D_GENERATION",
    "为系统生成符合宪法的文案。", "依据语调画像、受众、安全规则生成文案候选。",
    ["scope", "tone", "audience"], ["文案候选", "diff"], ["Text Dynamic Update Engine"], ["/text-dynamic-update"],
    "为 /onboarding hero 生成新文案。", "{candidates:[...]}"),
  c("story-text-calculus", "剧情文本计算法", "Story Text Calculus", "D_GENERATION",
    "为虚拟世界生成剧情。", "世界设定 + 角色 → 情节单元。",
    ["世界", "角色"], ["剧情段落"], ["World Engine"], ["/world"],
    "生成一段开场剧情。", "段落文本"),
  c("vocal-calculus", "声乐计算法", "Vocal Calculus", "D_GENERATION",
    "为对象生成声乐方案。", "音高 / 节奏 / 风格映射。",
    ["对象", "情绪"], ["声乐方案"], ["Vocal Engine"], ["/vocal"],
    "为角色生成主题旋律。", "{melody:..., timbre:...}",
    "EXPERIMENTAL"),
  c("translation-calculus", "翻译计算法", "Translation Calculus", "D_GENERATION",
    "保持系统语义的跨语言翻译。", "保留术语、安全边界、宪法约束。",
    ["源文本", "locale"], ["译文"], ["Text Localization"], ["/text-localization"],
    "把这段安全提示翻成英文。", "EN safety note"),
  c("prompt-generation-calculus", "Prompt 生成计算法", "Prompt Generation Calculus", "D_GENERATION",
    "为模型与用户生成 Prompt。", "Prompt Forge 的核心生成逻辑。",
    ["意图", "受众"], ["Prompt 候选"], ["Prompt Forge"], ["/prompt-forge"],
    "为 onboarding 生成 prompt。", "{prompts:[...]}"),
  c("usage-example-calculus", "使用示例计算法", "Usage Example Calculus", "D_GENERATION",
    "为模块生成可复制的使用示例。", "模块语义 + 模板 → 示例。",
    ["module"], ["examples[]"], ["Usage Examples"], ["/usage-examples"],
    "为 vitality 生成 3 个示例。", "[{input,output}, ...]"),

  // E 世界 / 虚拟生活
  c("world-generation-calculus", "世界生成计算法", "World Generation Calculus", "E_WORLD_LIFE",
    "从数列生成一个虚拟世界。", "World Engine 的入口生成器。",
    ["种子数列"], ["世界骨架"], ["World Engine"], ["/world"],
    "生成一个海洋文明。", "{world:'oceanic-...', layers:[...]}"),
  c("sequence-world-calculus", "数列世界计算法", "Sequence World Calculus", "E_WORLD_LIFE",
    "由数列直接派生的世界规则。", "数列 ↔ 世界律的稳定映射。",
    ["数列"], ["世界规则集"], ["World Engine"], ["/world"],
    "由 7-3-1 数列生成世界律。", "{laws:[...]}"),
  c("world-simulation-calculus", "世界模拟计算法", "World Simulation Calculus", "E_WORLD_LIFE",
    "推演世界走向。", "多步骤事件演化与社会反馈。",
    ["世界", "步数"], ["时间线"], ["World Engine"], ["/world"],
    "模拟 100 步。", "{steps:[...]}"),
  c("world-growth-calculus", "世界生长计算法", "World Growth Calculus", "E_WORLD_LIFE",
    "让世界自我生长。", "资源 / 人口 / 文明阶梯演化。",
    ["世界"], ["生长曲线"], ["World Engine"], ["/world"],
    "推动 1000 年。", "{eras:[...]}"),
  c("world-society-calculus", "世界社会计算法", "World Society Calculus", "E_WORLD_LIFE",
    "推演社会结构。", "群体、阶层、制度演化。",
    ["世界", "人群"], ["社会结构"], ["World Engine"], ["/world"],
    "推演社会分层。", "{classes:[...]}"),
  c("civilization-evolution-calculus", "文明演化计算法", "Civilization Evolution Calculus", "E_WORLD_LIFE",
    "看文明阶梯如何升级。", "技术 / 文化 / 神话三轴的协同演化。",
    ["世界"], ["文明阶段"], ["World Engine"], ["/world"],
    "演化这个文明。", "{tier:..., milestones:[...]}"),
  c("world-presentation-calculus", "世界表现计算法", "World Presentation Calculus", "E_WORLD_LIFE",
    "把世界讲清楚。", "把模拟结果转成可读叙事 / 可视化。",
    ["世界状态"], ["叙事", "图表"], ["World Engine"], ["/world"],
    "展示这一回合。", "叙事 + 图"),
  c("virtual-life-calculus", "虚拟生活计算法", "Virtual Life Calculus", "E_WORLD_LIFE",
    "构造虚拟生活的细节。", "日常 / 关系 / 情绪三层模拟。",
    ["角色"], ["生活轨迹"], ["World Engine"], ["/world"],
    "模拟一周虚拟生活。", "{days:[...]}"),
  c("virtual-creation-calculus", "虚拟创造物计算法", "Virtual Creation Calculus", "E_WORLD_LIFE",
    "为虚拟世界生成创造物。", "物品 / 建筑 / 制度的生成器。",
    ["世界", "需求"], ["创造物"], ["World Engine"], ["/world"],
    "造一个图书馆。", "{building:...}"),

  // F 系统治理
  c("constant-universe-calculus", "常数宇宙计算法", "Constant Universe Calculus", "F_SYSTEM_GOV",
    "维护系统稳定常数。", "常数注册 / 版本 / 影响图。",
    ["常数变更"], ["影响范围"], ["Constant Universe"], ["/constants"],
    "更新常数 X。", "{impactedModules:[...]}"),
  c("system-constitution-calculus", "系统宪法计算法", "System Constitution Calculus", "F_SYSTEM_GOV",
    "确保所有模块遵守宪法。", "宪法条款解析 + 合规检查。",
    ["模块行为"], ["合规判定"], ["Constitution"], ["/constitution"],
    "检查 prompt-forge 是否合规。", "{ok:true}"),
  c("permission-calculus", "权限计算法", "Permission Calculus", "F_SYSTEM_GOV",
    "决定谁能做什么。", "角色 × 模块 × 操作 三维授权。",
    ["actor", "module", "op"], ["allow/deny"], ["Auth"], ["/auth"],
    "普通用户能进 /founder?", "deny"),
  c("safety-boundary-calculus", "安全边界计算法", "Safety Boundary Calculus", "F_SYSTEM_GOV",
    "守住非医疗 / 非金融 / 非法律边界。", "对生成内容做安全规则匹配。",
    ["生成文本 / 行为"], ["安全判定", "整改建议"], ["Safety"], ["/safety"],
    "检查一段建议是否越界。", "{violations:[...]}"),
  c("hybrid-compression-calculus", "黑白箱混合压缩计算法", "Hybrid Black-White-Box Compression Calculus", "F_SYSTEM_GOV",
    "把不确定信号压缩成可用结构。", "白箱可解释规则 + 黑箱信号融合。",
    ["混合信号"], ["压缩态"], ["Hybrid Compression"], ["/hybrid"],
    "压缩本周信号。", "{state:...}",
    "EXPERIMENTAL"),
  c("text-dynamic-update-calculus", "文本动态更新计算法", "Text Dynamic Update Calculus", "F_SYSTEM_GOV",
    "系统变了，文案跟着变。", "依据模块 / 路由 / 常数 / 宪法 / 主体 / 教程 / UI 的变化，检测 stale 文本并生成候选 / diff / 审计 / 版本。",
    ["系统变更", "模块注册表", "UI 注册表", "文档状态", "常数版本", "宪法版本"], ["stale 文本", "新文案候选", "文本 diff", "审计结果", "本地化同步"],
    ["Text Dynamic Update Engine", "UI Update Engine", "Learning Docs Engine", "Software QA", "Recalculation"], ["/text-dynamic-update", "/text-audit"],
    "宪法更新后扫描 stale。", "{stale:[...], candidates:[...]}",
    "EXPERIMENTAL",
    "文本更新不能违反宪法、安全边界、隐私边界与非金融化边界。"),
  c("ui-update-calculus", "UI 更新计算法", "UI Update Calculus", "F_SYSTEM_GOV",
    "保持入口、空状态、Quick Start 完整。", "UI Interface Update Engine 的核心逻辑。",
    ["模块注册表"], ["stale UI 列表"], ["UI Update Engine"], ["/ui-update-engine"],
    "扫描入口完整性。", "{stale:N}"),
  c("sub-router-collapse-calculus", "子路由折叠计算法", "Sub-Router Collapse Calculus", "F_SYSTEM_GOV",
    "侧栏分组的展开 / 收起。", "Collapsible Sub-Router System 状态机。",
    ["路由树"], ["折叠状态"], ["Sidebar"], ["/"],
    "记住用户折叠偏好。", "{group:'world',open:false}"),
  c("learning-docs-calculus", "教程文档计算法", "Learning Docs Calculus", "F_SYSTEM_GOV",
    "为每个模块生成教程文档。", "Learning & Documentation Engine 的生成逻辑。",
    ["模块"], ["教程 / FAQ / 术语表"], ["Learning Docs Engine"], ["/learn"],
    "为 vitality 生成教程。", "{lessons:[...]}"),
  c("version-leap-calculus", "版本跃迁计算法", "Version Leap Calculus", "F_SYSTEM_GOV",
    "判断这次变更是 PATCH 还是 LEAP。", "五级打分 + 强制规则。",
    ["变更集"], ["leap 等级", "版本建议"], ["Version Leap Engine"], ["/version-leap"],
    "评估本次发布。", "MAJOR"),

  // G 质量 / 回验
  c("software-qa-calculus", "软件 QA 计算法", "Software QA Calculus", "G_QA_FEEDBACK",
    "扫出模块未接入 / 入口缺失。", "QA 注册表 × 实际路由 × Feedback 入口。",
    ["代码现状"], ["issues[]"], ["Software QA"], ["/software-qa"],
    "全量 QA。", "{issues:[...], critical:0}"),
  c("feedback-calculus", "回验计算法", "Feedback Calculus", "G_QA_FEEDBACK",
    "用户回验调整权重。", "把命中 / 偏差转成下一次权重调整。",
    ["回验记录"], ["权重 delta"], ["Feedback Engine"], ["/feedback"],
    "回验本周预测。", "{delta:{...}}"),
  c("recalculation-calculus", "重新计算计算法", "Recalculation Calculus", "G_QA_FEEDBACK",
    "标记并重算 stale 项。", "stale → 重算队列 → 新结果。",
    ["stale 项"], ["新结果"], ["Recalculation"], ["/recalculation"],
    "重算所有 stale。", "{recomputed:N}"),
  c("stale-detection-calculus", "过期检测计算法", "Stale Detection Calculus", "G_QA_FEEDBACK",
    "找出已经过期的输出 / 文案 / 模型。", "依据上游版本 hash 判定。",
    ["产物 + 依赖 hash"], ["stale 标记"], ["Recalculation", "Text Dynamic Update"], ["/recalculation"],
    "扫一次过期。", "{stale:[...]}"),
  c("audit-calculus", "审计计算法", "Audit Calculus", "G_QA_FEEDBACK",
    "把决策与生成留痕。", "事件日志 + 安全规则匹配。",
    ["事件流"], ["audit 报告"], ["Audit Engine"], ["/audit"],
    "审计本周生成。", "{violations:[]}"),
  c("release-readiness-calculus", "发布就绪计算法", "Release Readiness Calculus", "G_QA_FEEDBACK",
    "判断这次能不能发。", "16+ 条 readiness 检查。",
    ["当前状态"], ["READY/WARN/BLOCKED"], ["Version Leap Engine"], ["/release-readiness"],
    "检查发布就绪。", "READY"),

  // H 价值 / 资源
  c("sequence-currency-calculus", "数列货币计算法", "Sequence Currency Calculus", "H_VALUE_RESOURCE",
    "系统内部的虚拟数列货币。", "仅用于产品内部价值流转，不与现实货币挂钩。",
    ["内部贡献"], ["货币余额（虚拟）"], ["Value Engine"], ["/value"],
    "查看数列货币。", "{balance:123}",
    "ACTIVE",
    "数列货币是产品内部虚拟单位，不构成现实金融工具或投资建议。"),
  c("internal-value-calculus", "内部价值计算法", "Internal Value Calculus", "H_VALUE_RESOURCE",
    "评估系统内部价值。", "贡献 + 稀缺性 + 回验权重。",
    ["对象 / 行为"], ["内部价值"], ["Value Engine"], ["/value"],
    "评估一次贡献。", "{value:0.4}"),
  c("world-resource-calculus", "世界资源计算法", "World Resource Calculus", "H_VALUE_RESOURCE",
    "虚拟世界中的资源分布。", "资源点 / 流量 / 衰减。",
    ["世界"], ["资源地图"], ["World Engine"], ["/world"],
    "看资源分布。", "{nodes:[...]}"),
  c("contribution-score-calculus", "贡献评分计算法", "Contribution Score Calculus", "H_VALUE_RESOURCE",
    "给参与者打贡献分。", "行为流 → 评分。",
    ["行为流"], ["score"], ["Value Engine"], ["/value"],
    "给本周打分。", "{score:78}"),
  c("asset-valuation-calculus", "资产估值计算法（虚拟）", "Virtual Asset Valuation Calculus", "H_VALUE_RESOURCE",
    "为虚拟资产估值。", "仅限虚拟世界资产；不等于现实金融估值。",
    ["虚拟资产"], ["虚拟估值"], ["Value Engine"], ["/value"],
    "估值这件虚拟物品。", "{value:0.62}",
    "ACTIVE",
    "虚拟资产估值仅在产品内部生效，不构成现实金融估值或投资建议。"),

  // I 数字科学
  c("digital-physics-calculus", "数字物理学计算法", "Digital Physics Calculus", "I_DIGITAL_SCIENCE",
    "虚拟世界的物理律。", "面向数列世界的物理规则系统。",
    ["世界律"], ["物理参数"], ["World Engine"], ["/world"],
    "设定重力。", "{g:9.8}",
    "EXPERIMENTAL"),
  c("digital-chemistry-calculus", "数字化学计算法", "Digital Chemistry Calculus", "I_DIGITAL_SCIENCE",
    "虚拟元素与反应。", "符号化反应方程。",
    ["元素"], ["反应链"], ["World Engine"], ["/world"],
    "合成虚拟物质。", "{product:...}",
    "EXPERIMENTAL"),
  c("digital-geography-calculus", "数字地理学计算法", "Digital Geography Calculus", "I_DIGITAL_SCIENCE",
    "虚拟世界地形。", "高程 / 气候 / 资源叠加。",
    ["世界种子"], ["地形图"], ["World Engine"], ["/geo"],
    "生成大陆。", "{map:...}",
    "EXPERIMENTAL"),
  c("digital-astronomy-calculus", "数字天文学计算法", "Digital Astronomy Calculus", "I_DIGITAL_SCIENCE",
    "虚拟星空与天象。", "周期 + 触发。",
    ["世界时间"], ["天象事件"], ["World Engine"], ["/world"],
    "下个月食何时？", "{date:...}",
    "EXPERIMENTAL"),
  c("digital-biology-calculus", "数字生物计算法", "Digital Biology Calculus", "I_DIGITAL_SCIENCE",
    "虚拟生命与生态。", "种群 / 食物链 / 演化。",
    ["生态"], ["种群曲线"], ["World Engine"], ["/world"],
    "演化森林生态。", "{species:[...]}",
    "EXPERIMENTAL"),
  c("bio-self-evolution-calculus", "生物产品自进化计算法", "Bio-Product Self-Evolution Calculus", "I_DIGITAL_SCIENCE",
    "虚拟生物产品自我演化。", "代际 + 突变 + 选择。",
    ["种子"], ["演化路径"], ["World Engine"], ["/world"],
    "让产品演化 10 代。", "{generations:[...]}",
    "EXPERIMENTAL"),
  c("digital-life-ladder-calculus", "数字生命阶梯计算法", "Digital Life Ladder Calculus", "I_DIGITAL_SCIENCE",
    "判断虚拟生命阶段。", "从单元 → 群体 → 文明 → 文化阶梯。",
    ["虚拟实体"], ["阶梯位置"], ["World Engine"], ["/world"],
    "评估这个虚拟物种。", "tier 3",
    "EXPERIMENTAL"),

  // J 神话 / 象征
  c("subconscious-recall-calculus", "前世记忆潜意识调用计算法", "Subconscious Recall Calculus", "J_MYTH_SYMBOL",
    "调用潜意识象征意象。", "象征库 + 主体特征的混合检索（仅作为创作辅助）。",
    ["主体", "提问"], ["象征素材"], ["Myth Engine"], ["/myth"],
    "给我一个象征意象。", "{symbol:...}",
    "EXPERIMENTAL",
    "潜意识调用仅作为创作与自我反思辅助，不构成心理诊断或灵性承诺。"),
  c("god-algorithm-calculus", "神明算法生成计算法", "Deity Algorithm Calculus", "J_MYTH_SYMBOL",
    "为虚拟文明生成神明结构。", "神格 / 神职 / 神话叙事三元组。",
    ["文明"], ["神明结构"], ["World Engine"], ["/world"],
    "为这个文明生神。", "{deity:...}",
    "EXPERIMENTAL"),
  c("symbol-mapping-calculus", "象征映射计算法", "Symbol Mapping Calculus", "J_MYTH_SYMBOL",
    "把对象映到象征体系。", "对象 ↔ 象征坐标。",
    ["对象"], ["象征坐标"], ["Myth Engine"], ["/myth"],
    "把愤怒映到象征。", "{symbol:'fire'}",
    "EXPERIMENTAL"),
  c("civilization-myth-calculus", "文明神话计算法", "Civilization Myth Calculus", "J_MYTH_SYMBOL",
    "为文明生成神话。", "起源 / 英雄 / 末日三段式。",
    ["文明"], ["神话集"], ["World Engine"], ["/world"],
    "生成创世神话。", "{myth:...}",
    "EXPERIMENTAL"),
  c("nine-core-persona-calculus", "九核执行人格计算法", "Nine-Core Persona Calculus", "J_MYTH_SYMBOL",
    "把执行任务分给九个内部人格。", "九核分工 + 协同 + 仲裁。",
    ["任务"], ["人格分配", "执行计划"], ["Persona Engine"], ["/persona"],
    "把一个产品任务派给九核。", "{assigned:[...]}",
    "EXPERIMENTAL"),
  c("app-version-leap-calculus", "应用版本跃迁计算法", "Application Version Leap Calculus", "F_SYSTEM_GOV",
    "判断应用层版本跃迁。", "App 层指标 + Engine 跃迁联合打分。",
    ["release 候选"], ["leap 等级"], ["Version Leap Engine"], ["/version-leap"],
    "评估这次 App 发布。", "LEAP"),
];

export const CALCULUS_COUNT = CALCULUS_REGISTRY.length;

export function calculusByCategory(cat: CalculusCategoryId): CalculusEntry[] {
  return CALCULUS_REGISTRY.filter(e => e.category === cat);
}
