export type DigitalRoleConflictType =
  | "AUTHORITY_OVERREACH"
  | "DUPLICATE_RESPONSIBILITY"
  | "PRODUCT_VS_ARCHITECTURE"
  | "GROWTH_VS_GOVERNANCE"
  | "FOUNDER_VS_QA"
  | "PROGRAMMER_VS_QA"
  | "CREATIVE_VS_CLM"
  | "RESEARCH_VS_MARKETING"
  | "PUBLIC_VS_FOUNDER"
  | "DEMO_VS_REAL";

export const DIGITAL_ROLE_CONFLICT_TYPES: DigitalRoleConflictType[] = [
  "AUTHORITY_OVERREACH", "DUPLICATE_RESPONSIBILITY", "PRODUCT_VS_ARCHITECTURE",
  "GROWTH_VS_GOVERNANCE", "FOUNDER_VS_QA", "PROGRAMMER_VS_QA", "CREATIVE_VS_CLM",
  "RESEARCH_VS_MARKETING", "PUBLIC_VS_FOUNDER", "DEMO_VS_REAL",
];

export const CRITICAL_CONFLICTS: DigitalRoleConflictType[] = [
  "GROWTH_VS_GOVERNANCE",
  "FOUNDER_VS_QA",
  "PUBLIC_VS_FOUNDER",
  "DEMO_VS_REAL",
];
