export type DigitalRoleType =
  | "DIGITAL_FOUNDER"
  | "DIGITAL_ARCHITECT"
  | "DIGITAL_PRODUCT_MANAGER"
  | "DIGITAL_PROGRAMMER"
  | "DIGITAL_PLANNER"
  | "DIGITAL_DESIGNER"
  | "DIGITAL_RESEARCHER"
  | "DIGITAL_QA"
  | "DIGITAL_DOCUMENTATION_LEAD"
  | "DIGITAL_OPERATOR"
  | "DIGITAL_GROWTH_STRATEGIST"
  | "DIGITAL_GOVERNANCE_OFFICER"
  | "DIGITAL_WORLD_BUILDER"
  | "DIGITAL_NARRATIVE_DIRECTOR"
  | "DIGITAL_MUSIC_DIRECTOR"
  | "DIGITAL_SYSTEM_STRATEGIST";

export const DIGITAL_ROLE_TYPES: DigitalRoleType[] = [
  "DIGITAL_FOUNDER",
  "DIGITAL_ARCHITECT",
  "DIGITAL_PRODUCT_MANAGER",
  "DIGITAL_PROGRAMMER",
  "DIGITAL_PLANNER",
  "DIGITAL_DESIGNER",
  "DIGITAL_RESEARCHER",
  "DIGITAL_QA",
  "DIGITAL_DOCUMENTATION_LEAD",
  "DIGITAL_OPERATOR",
  "DIGITAL_GROWTH_STRATEGIST",
  "DIGITAL_GOVERNANCE_OFFICER",
  "DIGITAL_WORLD_BUILDER",
  "DIGITAL_NARRATIVE_DIRECTOR",
  "DIGITAL_MUSIC_DIRECTOR",
  "DIGITAL_SYSTEM_STRATEGIST",
];
