export type DigitalRoleOutputType =
  | "DIRECTION_DECISION"
  | "ARCHITECTURE_PLAN"
  | "PRODUCT_REQUIREMENTS"
  | "CODE_PLAN"
  | "CONTENT_PLAN"
  | "QA_REPORT"
  | "GOVERNANCE_REPORT"
  | "RESEARCH_REPORT"
  | "DOCS_DRAFT"
  | "GROWTH_PLAN"
  | "WORLD_DRAFT"
  | "NARRATIVE_DRAFT"
  | "MUSIC_PROMPT"
  | "SYSTEM_ROADMAP";

export const DIGITAL_ROLE_OUTPUT_TYPES: DigitalRoleOutputType[] = [
  "DIRECTION_DECISION", "ARCHITECTURE_PLAN", "PRODUCT_REQUIREMENTS", "CODE_PLAN",
  "CONTENT_PLAN", "QA_REPORT", "GOVERNANCE_REPORT", "RESEARCH_REPORT", "DOCS_DRAFT",
  "GROWTH_PLAN", "WORLD_DRAFT", "NARRATIVE_DRAFT", "MUSIC_PROMPT", "SYSTEM_ROADMAP",
];
