export type DigitalRoleTaskType =
  | "IDEA_TO_PRODUCT"
  | "IDEA_TO_SYSTEM"
  | "SYSTEM_ARCHITECTURE"
  | "PRODUCT_REQUIREMENTS"
  | "CODE_IMPLEMENTATION_PLAN"
  | "CREATIVE_PLANNING"
  | "WORLD_BUILDING"
  | "NARRATIVE_DESIGN"
  | "MUSIC_DIRECTION"
  | "RESEARCH_AND_EVIDENCE"
  | "QA_AND_AUDIT"
  | "DOCS_AND_TUTORIALS"
  | "GROWTH_AND_SHOWCASE"
  | "GOVERNANCE_REVIEW"
  | "VERSION_UPGRADE"
  | "CLM_REVIEW"
  | "CROSS_FUNCTIONAL_WORKFLOW"
  | "OBJECT_COMPILATION";

export const DIGITAL_ROLE_TASK_TYPES: DigitalRoleTaskType[] = [
  "IDEA_TO_PRODUCT", "IDEA_TO_SYSTEM", "SYSTEM_ARCHITECTURE", "PRODUCT_REQUIREMENTS",
  "CODE_IMPLEMENTATION_PLAN", "CREATIVE_PLANNING", "WORLD_BUILDING", "NARRATIVE_DESIGN",
  "MUSIC_DIRECTION", "RESEARCH_AND_EVIDENCE", "QA_AND_AUDIT", "DOCS_AND_TUTORIALS",
  "GROWTH_AND_SHOWCASE", "GOVERNANCE_REVIEW", "VERSION_UPGRADE", "CLM_REVIEW",
  "CROSS_FUNCTIONAL_WORKFLOW", "OBJECT_COMPILATION",
];

export const DIGITAL_ROLE_TASK_LABELS: Record<DigitalRoleTaskType, string> = {
  IDEA_TO_PRODUCT: "想法转产品",
  IDEA_TO_SYSTEM: "想法转系统",
  SYSTEM_ARCHITECTURE: "系统架构",
  PRODUCT_REQUIREMENTS: "产品需求",
  CODE_IMPLEMENTATION_PLAN: "代码实现计划",
  CREATIVE_PLANNING: "创意策划",
  WORLD_BUILDING: "世界构建",
  NARRATIVE_DESIGN: "剧情设计",
  MUSIC_DIRECTION: "音乐方向",
  RESEARCH_AND_EVIDENCE: "研究与证据",
  QA_AND_AUDIT: "质量审计",
  DOCS_AND_TUTORIALS: "文档教程",
  GROWTH_AND_SHOWCASE: "增长展示",
  GOVERNANCE_REVIEW: "治理审查",
  VERSION_UPGRADE: "版本升级",
  CLM_REVIEW: "生命周期复审",
  CROSS_FUNCTIONAL_WORKFLOW: "跨功能工作流",
  OBJECT_COMPILATION: "对象编译",
};
