import {timingSafeEqual} from 'node:crypto';

const asBuffer=value=>Buffer.from(String(value),'utf8');
export function constantTimeEqual(left,right){const a=asBuffer(left),b=asBuffer(right);return a.length===b.length&&timingSafeEqual(a,b);}
export function originMiddleware(config){return(req,res,next)=>{const origin=req.headers.origin;if(origin&&!config.allowedOrigins.includes('*')&&!config.allowedOrigins.includes(origin)){res.status(403).json({error:'origin_not_allowed'});return;}if(origin){res.setHeader('access-control-allow-origin',origin);res.setHeader('vary','Origin');}res.setHeader('access-control-allow-methods','GET,POST,DELETE,OPTIONS');res.setHeader('access-control-allow-headers','content-type,accept,authorization,mcp-session-id,mcp-protocol-version,last-event-id');res.setHeader('access-control-expose-headers','mcp-session-id');if(req.method==='OPTIONS'){res.status(204).end();return;}next();};}
export function authMiddleware(config){return(req,res,next)=>{if(config.authMode==='none'){req.auth={token:config.pathToken?'path-token':'none',clientId:'taowind-private-client',scopes:authorityScopes(config)};next();return;}const header=String(req.headers.authorization??'');const [scheme,token]=header.split(/\s+/,2);if(scheme?.toLowerCase()!=='bearer'||!token||!constantTimeEqual(token,config.bearerToken)){res.setHeader('www-authenticate','Bearer realm="taowind-reality-mcp"');res.status(401).json({error:'unauthorized'});return;}req.auth={token:'static-bearer',clientId:'taowind-mcp-client',scopes:authorityScopes(config)};next();};}
export function authorityScopes(config){const scopes=['rncs.read'];if(config.candidateWritesEnabled)scopes.push('rncs.candidate');if(config.authorityWritesEnabled)scopes.push('rncs.authority','rncs.runtime');if(config.executionToolsEnabled)scopes.push('rncs.execution','provider.github','provider.vercel');if(config.executionShellEnabled)scopes.push('rncs.execution.breakglass');return scopes;}
export function rateLimitMiddleware(config){const buckets=new Map();return(req,res,next)=>{const key=req.ip||req.socket.remoteAddress||'unknown';const minute=Math.floor(Date.now()/60_000),bucketKey=`${key}:${minute}`,count=(buckets.get(bucketKey)??0)+1;buckets.set(bucketKey,count);if(buckets.size>10_000)for(const old of buckets.keys())if(!old.endsWith(`:${minute}`))buckets.delete(old);res.setHeader('x-ratelimit-limit',String(config.rateLimitPerMinute));res.setHeader('x-ratelimit-remaining',String(Math.max(0,config.rateLimitPerMinute-count)));if(count>config.rateLimitPerMinute){res.status(429).json({error:'rate_limited'});return;}next();};}
export const redactPath=path=>String(path).replace(/\/mcp\/[A-Za-z0-9_-]{24,}/g,'/mcp/[redacted]');
