import fs from 'node:fs';
import path from 'node:path';
import {performance} from 'node:perf_hooks';
import {readJson,writeJson,emptyDir,ensureDir,fileManifest,seal,verifySeal,sha256File,BuildError,rootHash,clone} from './canonical.mjs';
import {normalizeBuildRequest,assertRequest,assertProject,validateBuildRequest,validateUnifiedProject,createBuildIdentity,TARGET_PROFILES} from './contracts.mjs';
import {bakeAssets,syncAssetDatabase,writeAssetDatabaseEvidence,publicAssetManifest as createPublicAssetManifest} from './assets.mjs';
import {TARGET_BUILDERS} from './targets.mjs';
import {runBuildPreflight} from './preflight.mjs';
import {buildRuntimeEvidence} from './runtime-evidence.mjs';

export function createBuildGraph(request,project,identity){
  const databaseEnabled=request.asset_database?.enabled===true;
  const nodes=[
    {id:'validate',kind:'validation',depends_on:[],outputs:['validation.json']},
    ...(databaseEnabled?[{id:'asset-database',kind:'incremental-asset-database',depends_on:['validate'],outputs:['asset-database.json','asset-change-plan.json','asset-database-sync.json','asset-cache-index.json']}]:[]),
    {id:'preflight',kind:'capability-preflight',depends_on:[databaseEnabled?'asset-database':'validate'],outputs:['build-preflight.json']},
    {id:'runtime-evidence',kind:'deterministic-runtime-evidence',depends_on:['preflight'],outputs:['runtime-evidence.json','runtime-timeline.json','runtime-replay.json','runtime-checkpoint.json','spatial-snapshot.json','spatial-causal-delta.json','spatial-runtime.manifest.json','gpu-frame-plan.json','gpu-frame-summary.json','gpu-viewport.manifest.json']},
    {id:'asset-bake',kind:'asset-bake',depends_on:['preflight',...(databaseEnabled?['asset-database']:[])],outputs:['asset-manifest.json']},
    ...request.targets.map(t=>({id:`target:${t}`,kind:'target-build',target:t,depends_on:['asset-bake','runtime-evidence'],outputs:[t]})),
    {id:'receipt',kind:'evidence',depends_on:request.targets.map(t=>`target:${t}`),outputs:['build-receipt.json','integrity-manifest.json']}
  ];
  return seal({format:'reality-build.graph.v0.2',version:'0.2.0-alpha.1',build_id:identity.build_id,project_root:identity.project_root,request_root:request.request_root,nodes},'graph_root');
}

export function verifyTarget(dir){
  const receiptFile=path.join(dir,'target-receipt.json');if(!fs.existsSync(receiptFile))return{valid:false,errors:[{code:'TARGET_RECEIPT_MISSING',path:receiptFile}]};
  const receipt=readJson(receiptFile),errors=[];if(!verifySeal(receipt,'target_root'))errors.push({code:'TARGET_ROOT_MISMATCH'});
  for(const f of receipt.files??[]){const p=path.join(dir,f.path);if(!fs.existsSync(p)){errors.push({code:'FILE_MISSING',path:f.path});continue;}const actual=sha256File(p);if(actual!==f.sha256)errors.push({code:'FILE_HASH_MISMATCH',path:f.path,expected:f.sha256,actual});if(fs.statSync(p).size!==f.size)errors.push({code:'FILE_SIZE_MISMATCH',path:f.path});}
  return{valid:errors.length===0,errors,target:receipt.target,target_root:receipt.target_root,files:receipt.files?.length??0};
}

export function verifyBuild(outRoot){
  const receiptFile=path.join(outRoot,'build-receipt.json');if(!fs.existsSync(receiptFile))return{valid:false,errors:[{code:'BUILD_RECEIPT_MISSING'}]};
  const receipt=readJson(receiptFile),errors=[];if(!verifySeal(receipt,'receipt_root'))errors.push({code:'BUILD_RECEIPT_ROOT_MISMATCH'});
  const runtimeEvidenceFile=path.join(outRoot,'runtime-evidence.json');let runtimeEvidence=null;if(!fs.existsSync(runtimeEvidenceFile))errors.push({code:'RUNTIME_EVIDENCE_MISSING'});else{runtimeEvidence=readJson(runtimeEvidenceFile);if(!verifySeal(runtimeEvidence,'evidence_root'))errors.push({code:'RUNTIME_EVIDENCE_ROOT_MISMATCH'});if(runtimeEvidence.deterministic!==true)errors.push({code:'RUNTIME_EVIDENCE_NONDETERMINISTIC'});if(runtimeEvidence.spatial_deterministic!==true)errors.push({code:'SPATIAL_EVIDENCE_NONDETERMINISTIC'});}
  const spatialManifestFile=path.join(outRoot,'spatial-runtime.manifest.json');if(!fs.existsSync(spatialManifestFile))errors.push({code:'SPATIAL_RUNTIME_MANIFEST_MISSING'});else{const manifest=readJson(spatialManifestFile);if(!verifySeal(manifest,'manifest_root'))errors.push({code:'SPATIAL_RUNTIME_MANIFEST_ROOT_MISMATCH'});if(receipt.spatial_runtime_manifest_root&&manifest.manifest_root!==receipt.spatial_runtime_manifest_root)errors.push({code:'SPATIAL_RUNTIME_MANIFEST_RECEIPT_MISMATCH'});}
  const gpuPlanFile=path.join(outRoot,'gpu-frame-plan.json'),gpuSummaryFile=path.join(outRoot,'gpu-frame-summary.json'),gpuManifestFile=path.join(outRoot,'gpu-viewport.manifest.json');if(!fs.existsSync(gpuPlanFile))errors.push({code:'GPU_FRAME_PLAN_MISSING'});if(!fs.existsSync(gpuSummaryFile))errors.push({code:'GPU_FRAME_SUMMARY_MISSING'});if(!fs.existsSync(gpuManifestFile))errors.push({code:'GPU_VIEWPORT_MANIFEST_MISSING'});if(fs.existsSync(gpuPlanFile)&&fs.existsSync(gpuSummaryFile)){const plan=readJson(gpuPlanFile),summary=readJson(gpuSummaryFile);if(plan.framePlanRoot!==summary.frame_plan_root)errors.push({code:'GPU_FRAME_PLAN_ROOT_MISMATCH'});if(receipt.gpu_frame_plan_root&&plan.framePlanRoot!==receipt.gpu_frame_plan_root)errors.push({code:'GPU_FRAME_PLAN_RECEIPT_MISMATCH'});if(receipt.gpu_frame_summary_root&&summary.summary_root!==receipt.gpu_frame_summary_root)errors.push({code:'GPU_FRAME_SUMMARY_RECEIPT_MISMATCH'});if(!verifySeal(summary,'summary_root'))errors.push({code:'GPU_FRAME_SUMMARY_ROOT_MISMATCH'});}if(fs.existsSync(gpuManifestFile)){const manifest=readJson(gpuManifestFile);if(!verifySeal(manifest,'manifest_root'))errors.push({code:'GPU_VIEWPORT_MANIFEST_ROOT_MISMATCH'});if(receipt.gpu_viewport_manifest_root&&manifest.manifest_root!==receipt.gpu_viewport_manifest_root)errors.push({code:'GPU_VIEWPORT_MANIFEST_RECEIPT_MISMATCH'});}
  if(receipt.navigation_manifest_root){const navigationFile=path.join(outRoot,'tilemap-navigation.manifest.json');if(!fs.existsSync(navigationFile))errors.push({code:'NAVIGATION_MANIFEST_MISSING'});else{const navigation=readJson(navigationFile);if(!verifySeal(navigation,'manifest_root'))errors.push({code:'NAVIGATION_MANIFEST_ROOT_MISMATCH'});if(navigation.manifest_root!==receipt.navigation_manifest_root)errors.push({code:'NAVIGATION_MANIFEST_RECEIPT_MISMATCH'});}}
  if(receipt.asset_database_root){const databaseFile=path.join(outRoot,'asset-database.json');if(!fs.existsSync(databaseFile))errors.push({code:'ASSET_DATABASE_EVIDENCE_MISSING'});else{const database=readJson(databaseFile);if(!verifySeal(database,'database_root'))errors.push({code:'ASSET_DATABASE_ROOT_MISMATCH'});if(database.database_root!==receipt.asset_database_root)errors.push({code:'ASSET_DATABASE_RECEIPT_MISMATCH'});}}
  for(const f of receipt.core_files??[]){const p=path.join(outRoot,f.path);if(!fs.existsSync(p)){errors.push({code:'CORE_FILE_MISSING',path:f.path});continue;}const actual=sha256File(p);if(actual!==f.sha256)errors.push({code:'CORE_FILE_HASH_MISMATCH',path:f.path,expected:f.sha256,actual});}
  const targetResults={};for(const t of receipt.targets??[]){const r=verifyTarget(path.join(outRoot,t.target));targetResults[t.target]=r;if(!r.valid)errors.push(...r.errors.map(e=>({...e,target:t.target})));if(r.target_root!==t.target_root)errors.push({code:'TARGET_ROOT_REFERENCE_MISMATCH',target:t.target});}
  return{valid:errors.length===0,errors,receipt,target_results:targetResults};
}

export function buildProject(input={}){
  const request=assertRequest(input?.format?input:normalizeBuildRequest(input));
  if(!fs.existsSync(request.project_file))throw new BuildError('PROJECT_FILE_NOT_FOUND',request.project_file);
  const sourceProject=assertProject(readJson(request.project_file)),assetDatabase=syncAssetDatabase({project:sourceProject,request}),project=assertProject(assetDatabase.project),identity=createBuildIdentity(request,project,{asset_database_root:assetDatabase.evidence?.database_root??null}),outRoot=request.output_dir;
  if(fs.existsSync(path.join(outRoot,'build-receipt.json'))){const existing=verifyBuild(outRoot);if(existing.valid&&existing.receipt.build_key===identity.build_key)return{...existing.receipt,cache_hit:true,asset_cache_summary:assetDatabase.observation?.summary??null,output_dir:outRoot,verification:existing};}
  emptyDir(outRoot);const graph=createBuildGraph(request,project,identity);writeJson(path.join(outRoot,'build-graph.json'),graph);
  const started=performance.now(),metrics=[];
  const mark=(phase,t0,extra={})=>metrics.push({phase,duration_ms:Number((performance.now()-t0).toFixed(3)),...extra});
  let t=performance.now();const requestValidation=validateBuildRequest(request),projectValidation=validateUnifiedProject(project);writeJson(path.join(outRoot,'validation.json'),{request:requestValidation,project:projectValidation});mark('validate',t,{warnings:requestValidation.warnings.length+projectValidation.warnings.length});
  if(request.policy.fail_on_warning&&(requestValidation.warnings.length||projectValidation.warnings.length))throw new BuildError('BUILD_WARNING_FORBIDDEN');
  t=performance.now();const preflight=runBuildPreflight({request,project});writeJson(path.join(outRoot,'build-preflight.json'),preflight);mark('preflight',t,{checks:preflight.checks.length,warnings:preflight.warnings.length,blocked:preflight.blocked.length});
  if(preflight.status!=='ready')throw new BuildError('BUILD_PREFLIGHT_BLOCKED','',preflight);
  t=performance.now();const runtimeEvidence=buildRuntimeEvidence({project,request,identity});writeJson(path.join(outRoot,'runtime-evidence.json'),runtimeEvidence.evidence);writeJson(path.join(outRoot,'runtime-timeline.json'),runtimeEvidence.timeline);writeJson(path.join(outRoot,'runtime-replay.json'),runtimeEvidence.replay);writeJson(path.join(outRoot,'runtime-checkpoint.json'),runtimeEvidence.checkpoint);writeJson(path.join(outRoot,'spatial-snapshot.json'),runtimeEvidence.spatial_snapshot);writeJson(path.join(outRoot,'spatial-causal-delta.json'),runtimeEvidence.spatial_causal_delta);writeJson(path.join(outRoot,'spatial-runtime.manifest.json'),runtimeEvidence.spatial_runtime_manifest);writeJson(path.join(outRoot,'gpu-frame-plan.json'),runtimeEvidence.gpu_frame_plan);writeJson(path.join(outRoot,'gpu-frame-summary.json'),runtimeEvidence.gpu_frame_summary);writeJson(path.join(outRoot,'gpu-viewport.manifest.json'),runtimeEvidence.gpu_viewport_manifest);if(runtimeEvidence.navigation_manifest)writeJson(path.join(outRoot,'tilemap-navigation.manifest.json'),runtimeEvidence.navigation_manifest);mark('runtime-evidence',t,{entries:runtimeEvidence.timeline.entries.length,spatial_frames:runtimeEvidence.evidence.spatial_frames.length,deterministic:runtimeEvidence.replay.deterministic,spatial_deterministic:runtimeEvidence.evidence.spatial_deterministic,gpu_frame_plan_root:runtimeEvidence.evidence.gpu_frame_plan_root});
  t=performance.now();const bakeDir=ensureDir(path.join(outRoot,'_bake'));const assetManifest=bakeAssets({project,projectFile:request.project_file,outDir:bakeDir,embed:true,missingPolicy:request.policy.missing_asset,assetDatabase});const sealedPublicAssetManifest=createPublicAssetManifest(assetManifest);if(assetDatabase.enabled)writeAssetDatabaseEvidence(outRoot,{assetDatabase,assetManifest:sealedPublicAssetManifest});else writeJson(path.join(outRoot,'asset-manifest.json'),sealedPublicAssetManifest);mark('asset-bake',t,{assets:Object.keys(assetManifest.records).length,files:assetManifest.store.file_count,cache_hits:assetDatabase.observation?.summary.cache_hits??0,cache_builds:assetDatabase.observation?.summary.cache_builds??0,payload_cache_hits:Object.values(assetManifest.records).flatMap(record=>record.files??[]).filter(file=>file.cache_status==='hit').length});
  const targets=[];for(const target of request.targets){t=performance.now();const builder=TARGET_BUILDERS[target];const result=builder({project,request,identity,bakeDir,outRoot,assetManifest,runtimeEvidence,assetDatabase,publicAssetManifest:sealedPublicAssetManifest});targets.push({target,target_root:result.receipt.target_root,files:result.receipt.files.length,profile:TARGET_PROFILES[target]});mark(`target:${target}`,t,{files:result.receipt.files.length});}
  fs.rmSync(bakeDir,{recursive:true,force:true});
  const integrity=seal({format:'reality-build.integrity-manifest.v0.2',version:'0.2.0-alpha.1',build_id:identity.build_id,build_key:identity.build_key,graph_root:graph.graph_root,asset_database_root:assetDatabase.evidence?.database_root??null,asset_manifest_root:sealedPublicAssetManifest.manifest_root,runtime_evidence_root:runtimeEvidence.evidence.evidence_root,spatial_runtime_manifest_root:runtimeEvidence.spatial_runtime_manifest?.manifest_root??null,gpu_frame_plan_root:runtimeEvidence.evidence.gpu_frame_plan_root,gpu_frame_summary_root:runtimeEvidence.evidence.gpu_frame_summary_root,gpu_viewport_manifest_root:runtimeEvidence.evidence.gpu_viewport_manifest_root,navigation_manifest_root:runtimeEvidence.navigation_manifest?.manifest_root??null,targets:targets.map(t=>({target:t.target,target_root:t.target_root,files:t.files}))},'integrity_root');writeJson(path.join(outRoot,'integrity-manifest.json'),integrity);
  const coreNames=['build-graph.json','validation.json','build-preflight.json','runtime-evidence.json','runtime-timeline.json','runtime-replay.json','runtime-checkpoint.json','spatial-snapshot.json','spatial-causal-delta.json','spatial-runtime.manifest.json','gpu-frame-plan.json','gpu-frame-summary.json','gpu-viewport.manifest.json','asset-manifest.json'];if(runtimeEvidence.navigation_manifest)coreNames.push('tilemap-navigation.manifest.json');if(assetDatabase.enabled)coreNames.push('asset-database.json','asset-change-plan.json','asset-database-sync.json','asset-cache-index.json');coreNames.push('integrity-manifest.json');const coreFiles=coreNames.map(rel=>({path:rel,size:fs.statSync(path.join(outRoot,rel)).size,sha256:sha256File(path.join(outRoot,rel))}));
  const receipt=seal({format:'reality-build.receipt.v0.2',version:'0.2.0-alpha.1',build_id:identity.build_id,build_key:identity.build_key,project_id:project.identity.project_id,project_root:identity.project_root,request_root:request.request_root,semantic_request_root:identity.semantic_request_root,graph_root:graph.graph_root,asset_database_root:assetDatabase.evidence?.database_root??null,asset_plan_root:assetDatabase.plan?.plan_root??null,asset_sync_root:assetDatabase.sync_receipt?.sync_root??null,asset_cache_index_root:assetDatabase.cache_index?.index_root??null,asset_manifest_root:sealedPublicAssetManifest.manifest_root,preflight_root:preflight.preflight_root,runtime_evidence_root:runtimeEvidence.evidence.evidence_root,runtime_timeline_root:runtimeEvidence.timeline.timeline_root,runtime_replay_root:runtimeEvidence.replay.replay_root,runtime_deterministic:runtimeEvidence.replay.deterministic,spatial_snapshot_root:runtimeEvidence.spatial_snapshot?.stateRoot??null,spatial_causal_delta_root:runtimeEvidence.spatial_causal_delta?.deltaRoot??null,spatial_runtime_manifest_root:runtimeEvidence.spatial_runtime_manifest?.manifest_root??null,gpu_frame_plan_root:runtimeEvidence.evidence.gpu_frame_plan_root,gpu_resource_root:runtimeEvidence.evidence.gpu_resource_root,gpu_command_root:runtimeEvidence.evidence.gpu_command_root,gpu_frame_summary_root:runtimeEvidence.evidence.gpu_frame_summary_root,gpu_viewport_manifest_root:runtimeEvidence.evidence.gpu_viewport_manifest_root,navigation_manifest_root:runtimeEvidence.navigation_manifest?.manifest_root??null,navigation_receipt_root:runtimeEvidence.navigation_manifest?.receipt?.receipt_root??null,spatial_deterministic:runtimeEvidence.evidence.spatial_deterministic,mode:request.mode,quality_profile:request.quality_profile,app:clone(request.app),build_time:request.build_time,targets,core_files:coreFiles,integrity_root:integrity.integrity_root,deterministic_outputs:request.policy.deterministic,environment_evidence:true,status:'built'},'receipt_root');writeJson(path.join(outRoot,'build-receipt.json'),receipt);
  const verification=verifyBuild(outRoot);if(!verification.valid)throw new BuildError('BUILD_SELF_VERIFY_FAILED','',verification);
  writeJson(path.join(outRoot,'build-metrics.json'),{format:'reality-build.metrics.v0.2',build_id:identity.build_id,total_ms:Number((performance.now()-started).toFixed(3)),phases:metrics,not_part_of_deterministic_root:true});
  return{...receipt,cache_hit:false,asset_cache_summary:assetDatabase.observation?.summary??null,output_dir:outRoot,verification};
}

export function inspectBuild(outRoot){const v=verifyBuild(outRoot);return{...v,output_dir:path.resolve(outRoot)};}
