import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {ensureDir,BuildError,sha256File} from './canonical.mjs';
import {findCommand} from './preflight.mjs';

function goString(value){return JSON.stringify(String(value));}

export function windowsHostSource({html,title,appId,buildId}){
  const encoded=Buffer.from(html,'utf8').toString('base64');
  return `// Generated by Reality Build Fabric v0.2.0-alpha.1\npackage main\n\nimport (\n  "crypto/sha256"\n  "encoding/base64"\n  "fmt"\n  "net/url"\n  "os"\n  "os/exec"\n  "path/filepath"\n  "strings"\n  "syscall"\n  "unsafe"\n)\n\nconst appHTMLBase64 = ${goString(encoded)}\nconst appTitle = ${goString(title)}\nconst appID = ${goString(appId)}\nconst buildID = ${goString(buildId)}\n\nfunc messageBox(text string) {\n  user32 := syscall.NewLazyDLL("user32.dll")\n  proc := user32.NewProc("MessageBoxW")\n  t, _ := syscall.UTF16PtrFromString(text)\n  c, _ := syscall.UTF16PtrFromString(appTitle)\n  proc.Call(0, uintptr(unsafe.Pointer(t)), uintptr(unsafe.Pointer(c)), 0x10)\n}\n\nfunc fileURL(file string) string {\n  p := filepath.ToSlash(file)\n  if !strings.HasPrefix(p, "/") { p = "/" + p }\n  return (&url.URL{Scheme:"file", Path:p}).String()\n}\n\nfunc writePayload() (string,error) {\n  raw, err := base64.StdEncoding.DecodeString(appHTMLBase64); if err != nil { return "",err }\n  root := os.Getenv("LOCALAPPDATA"); if root=="" { root=os.TempDir() }\n  sum := fmt.Sprintf("%x",sha256.Sum256(raw))[:16]\n  dir := filepath.Join(root,"RealityBuild",appID,buildID+"-"+sum)\n  if err=os.MkdirAll(dir,0755); err!=nil { return "",err }\n  file := filepath.Join(dir,"app.html")\n  if old,readErr:=os.ReadFile(file); readErr!=nil || string(old)!=string(raw) { if err=os.WriteFile(file,raw,0644); err!=nil{return "",err} }\n  return file,nil\n}\n\nfunc start(name string,args ...string) error {\n  cmd:=exec.Command(name,args...); cmd.SysProcAttr=&syscall.SysProcAttr{HideWindow:true}; return cmd.Start()\n}\n\nfunc launch(file string) error {\n  u:=fileURL(file)\n  candidates:=[]string{}\n  for _,envName:=range []string{"PROGRAMFILES(X86)","PROGRAMFILES","LOCALAPPDATA"}{ if root:=os.Getenv(envName); root!="" { candidates=append(candidates,filepath.Join(root,"Microsoft","Edge","Application","msedge.exe"),filepath.Join(root,"Google","Chrome","Application","chrome.exe")) } }\n  candidates=append(candidates,"msedge.exe","chrome.exe")\n  for _,browser:=range candidates {\n    args:=[]string{"--app="+u,"--no-first-run","--disable-features=msEdgeSidebarV2"}\n    if err:=start(browser,args...); err==nil{return nil}\n  }\n  return start("rundll32.exe","url.dll,FileProtocolHandler",u)\n}\n\nfunc main(){ file,err:=writePayload(); if err==nil {err=launch(file)}; if err!=nil {\n  root:=os.Getenv("LOCALAPPDATA"); if root=="" {root=os.TempDir()}; logDir:=filepath.Join(root,"RealityBuild",appID); _=os.MkdirAll(logDir,0755); _=os.WriteFile(filepath.Join(logDir,"launch-error.log"),[]byte(err.Error()),0644); messageBox("启动失败："+err.Error()+"\\n错误日志已写入 "+logDir)\n} }\n`;
}

export function compileWindowsNativeHost({html,title,appId,buildId,outFile,env=process.env}){
  const go=findCommand('go',{env});if(!go)throw new BuildError('WINDOWS_NATIVE_TOOLCHAIN_UNAVAILABLE','Go toolchain not found');
  const buildDir=ensureDir(path.join(path.dirname(outFile),'.rbf-windows-host-build'));
  const sourceFile=path.join(buildDir,'main.go');fs.writeFileSync(sourceFile,windowsHostSource({html,title,appId,buildId}));
  const args=['build','-trimpath','-ldflags=-s -w -buildid= -H=windowsgui','-o',path.resolve(outFile),sourceFile];
  const r=spawnSync(go,args,{cwd:buildDir,encoding:'utf8',windowsHide:true,env:{...env,GOOS:'windows',GOARCH:'amd64',CGO_ENABLED:'0',SOURCE_DATE_EPOCH:'0'}});
  fs.rmSync(buildDir,{recursive:true,force:true});
  if(r.status!==0||!fs.existsSync(outFile))throw new BuildError('WINDOWS_NATIVE_COMPILE_FAILED',String(r.stderr||r.stdout||`exit ${r.status}`));
  return{file:outFile,size:fs.statSync(outFile).size,sha256:sha256File(outFile),toolchain:'go',architecture:'windows/amd64'};
}
