// Constant Universe v0.2 — Civilization Constants
export const CIVILIZATION_CONSTANTS = {
  ERA_STEPS_MAX_DEFAULT: 12,
  HISTORICAL_EVENTS_MAX_DEFAULT: 60,
  TECH_TREE_NODE_MAX_DEFAULT: 50,
  CIVILIZATION_MYTH_MAX_DEFAULT: 20,
  HISTORICAL_FIGURE_MAX_DEFAULT: 30,
} as const;
