// Constant Universe v0.2 — Presentation Constants
export const PRESENTATION_CONSTANTS = {
  PARTICLE_DENSITY_MAX_SAFE: 0.85,
  BLOOM_INTENSITY_MAX_SAFE: 0.75,
  CAMERA_FAST_CUT_MAX_SAFE: 0.7,
  UI_MOTION_REDUCED_MODE_AVAILABLE: true,
  SEMANTIC_PHYSICS_NOT_REAL_PHYSICS: true,
} as const;
