// Constant Universe v0.2 — World Society Constants
export const WORLD_SOCIETY_CONSTANTS = {
  NPC_AGENT_MAX_DEFAULT: 30,
  FACTION_MAX_DEFAULT: 8,
  INSTITUTION_MAX_DEFAULT: 12,
  SOCIAL_EDGE_MAX_DEFAULT: 200,
  SOCIAL_COMPLEXITY_COMPRESSION_THRESHOLD: 0.72,
} as const;
