// Constant Universe v0.2 — World Simulation Constants
export const WORLD_SIMULATION_CONSTANTS = {
  WORLD_TICK_MAX_DEFAULT: 10,
  WORLD_TICK_MAX_FOUNDER: 100,
  EVENTS_PER_TICK_MAX: 2,
  NPC_GENERATION_PER_GROWTH_MAX: 5,
  ZONE_GENERATION_PER_GROWTH_MAX: 3,
  AUTONOMOUS_EVENT_PER_TICK_MAX: 2,
  HISTORY_EVENT_PER_ERA_MAX: 8,
  PRESENTATION_CHANGE_PER_TICK_MAX: 6,
  WORLD_COMPRESSION_AUTO_THRESHOLD: 0.7,
} as const;

export type WorldSimulationConstantKey = keyof typeof WORLD_SIMULATION_CONSTANTS;
