export const CANVAS_OBJECT_TYPES = [
  "APP_PROJECT_OBJECT",
  "CODE_RUN_RESULT_OBJECT",
  "WEBLWM_WORLD_OBJECT",
  "WEBLCM_CONCEPT_GRAPH_OBJECT",
  "WEB_KNOWLEDGE_TRINITY_RUN_OBJECT",
  "WEB_CAPABILITY_RUN_OBJECT",
  "SONG_OBJECT",
  "STORY_OBJECT",
  "GENERIC_OBJECT",
] as const;
export type CanvasObjectType = (typeof CANVAS_OBJECT_TYPES)[number];
