export const COMMAND_INTENT_TYPES = [
  "CREATE_APP", "FIX_CODE", "GENERATE_SONG", "GENERATE_STORY",
  "RUN_WORLD_TICK", "RUN_CAPABILITY", "RUN_KNOWLEDGE_TRINITY",
  "OPEN_OBJECT", "OPEN_DOC", "OPEN_LEGACY_ROUTE",
  "CHECK_QA", "EXPORT", "UNKNOWN",
] as const;
export type CommandIntentType = (typeof COMMAND_INTENT_TYPES)[number];
