// Godot Export Adapter — snake_case JSON + GDScript skeleton
import type { SequenceWorldExport } from "./engineExportAdapter";

function toSnake(key: string): string {
  return key.replace(/[A-Z]/g, m => "_" + m.toLowerCase()).replace(/^_/, "");
}
function deepSnake(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(deepSnake);
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    Object.entries(value as Record<string, unknown>).forEach(([k, v]) => {
      out[toSnake(k)] = deepSnake(v);
    });
    return out;
  }
  return value;
}

export function exportGodotJSON(world: SequenceWorldExport): string {
  return JSON.stringify(deepSnake(world), null, 2);
}

export function exportGodotGDScriptSkeleton(world: SequenceWorldExport): string {
  return [
    `# Auto-generated by Aether Sequence World Engine v${world.metadata.engineVersion}`,
    `# Source mode: ${world.metadata.sourceMode}`,
    `extends Node`,
    ``,
    `var engine_version := "${world.metadata.engineVersion}"`,
    `var world_phase := "${world.worldState.currentPhase}"`,
    `var dominant_force := "${world.worldState.dominantForce}"`,
    `var entropy := ${world.worldState.entropyLevel.toFixed(2)}`,
    `var event_pressure := ${world.worldState.eventPressure.toFixed(2)}`,
    `var stability := ${world.worldState.stability.toFixed(2)}`,
    ``,
    `func get_world_profile() -> Dictionary:`,
    `    var f := FileAccess.open("res://sequence_world_profile.json", FileAccess.READ)`,
    `    if f == null:`,
    `        push_warning("sequence_world_profile.json not found")`,
    `        return {}`,
    `    var data := JSON.parse_string(f.get_as_text())`,
    `    return data`,
    ``,
    `func apply_render_profile(node: Node3D, profile: Dictionary) -> void:`,
    `    # TODO: map palette / lighting / motifs to your shaders & lights`,
    `    pass`,
    ``,
    `func spawn_npcs(profiles: Array) -> void:`,
    `    for p in profiles:`,
    `        # TODO: instantiate NPC scene by archetype = p.get("archetype")`,
    `        pass`,
    ``,
    `# NOTE: This script is a skeleton. Aether SDK does NOT replace Godot's renderer or physics.`,
  ].join("\n");
}
