export const WEB_CAPABILITY_PROCEDURE_STEPS = [
  "RETRIEVE_KNOWLEDGE",
  "SELECT_CALCULUS",
  "INJECT_CONSTANTS",
  "BUILD_CONCEPT_CHAIN",
  "RUN_TOOL_INTERFACE",
  "EXPAND_WITH_WEBLLM",
  "PRODUCE_OUTPUT_OBJECT",
  "RUN_QA",
  "SAVE_WORKSPACE",
] as const;
export type WebCapabilityProcedureStepType = typeof WEB_CAPABILITY_PROCEDURE_STEPS[number];
