export const WEB_CAPABILITY_RISK_TYPES = [
  "SKILL_DRIFT",
  "WRONG_WORKFLOW",
  "UNSAFE_OUTPUT",
  "OVERCLAIM",
  "MISSING_EVALUATION",
  "CONTEXT_POLLUTION",
  "SOURCE_FABRICATION",
  "DOMAIN_OVERREACH",
  "VIRTUAL_AS_REAL",
  "DATA_LEAK",
] as const;
export type WebCapabilityRiskType = typeof WEB_CAPABILITY_RISK_TYPES[number];
