export const WEB_CAPABILITY_OUTPUT_TYPES = [
  "CODE_PLAN_OBJECT", "FILE_TREE_OBJECT", "CODE_DRAFT_OBJECT", "REPAIR_SUGGESTION_OBJECT", "PATCH_DRAFT_OBJECT", "CODEX_HANDOFF_PACK_OBJECT",
  "PRODUCT_REQUIREMENT_OBJECT", "MVP_SCOPE_OBJECT", "USER_STORY_OBJECT", "ACCEPTANCE_CRITERIA_OBJECT", "APP_PROJECT_REQUEST_OBJECT",
  "DESIGN_SPEC_OBJECT", "UI_LAYOUT_OBJECT", "COMPONENT_STYLE_OBJECT", "DESIGN_PROMPT_OBJECT", "APP_UI_GUIDE_OBJECT",
  "SONG_OBJECT", "LYRIC_OBJECT", "VOCAL_PROMPT_OBJECT", "MUSIC_STYLE_OBJECT", "SUNO_HANDOFF_PACK_OBJECT",
  "STORY_OBJECT", "CHAPTER_OUTLINE_OBJECT", "SCENE_OBJECT", "COMIC_SCRIPT_OBJECT", "QUEST_TEXT_OBJECT",
  "RESEARCH_REPORT_OBJECT", "EVIDENCE_MAP_OBJECT", "COMPARISON_OBJECT", "CLAIM_OBJECT", "SOURCE_NOTE_OBJECT",
  "BUSINESS_PLAN_OBJECT", "POC_PLAN_OBJECT", "PRICING_DRAFT_OBJECT", "SALES_SCRIPT_OBJECT", "PARTNERSHIP_PROPOSAL_OBJECT",
  "LESSON_OBJECT", "COURSE_OUTLINE_OBJECT", "EXERCISE_OBJECT", "LEARNING_PATH_OBJECT", "FEEDBACK_OBJECT",
  "RELEASE_NOTE_OBJECT", "CONTENT_PLAN_OBJECT", "SOCIAL_POST_DRAFT_OBJECT", "FEEDBACK_SUMMARY_OBJECT", "OPERATION_PLAN_OBJECT",
  "STRATEGY_REPORT_OBJECT", "PRIORITY_MAP_OBJECT", "ROADMAP_OBJECT", "RISK_MATRIX_OBJECT", "NEXT_ACTION_OBJECT",
  "GAME_DESIGN_OBJECT", "GAME_LOOP_OBJECT", "QUEST_DESIGN_OBJECT", "LEVEL_OBJECT", "GAME_RULES_OBJECT", "GAME_EXPORT_PACK_OBJECT",
  "AGENT_PROFILE_OBJECT", "AGENT_BINDING_PROFILE_OBJECT", "AGENT_WORKFLOW_OBJECT", "AGENT_QA_OBJECT",
] as const;
export type WebCapabilityOutputType = typeof WEB_CAPABILITY_OUTPUT_TYPES[number];
