import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {verifyWorkspace,validateRealityBranchWorkspace,inspectGlb} from '../src/index.mjs';
const checks=[],add=(name,pass,detail='')=>checks.push({name,pass:Boolean(pass),detail});
const test=spawnSync(process.execPath,['--test','--test-concurrency=1','tests/*.test.mjs'],{encoding:'utf8',shell:true,maxBuffer:30_000_000});add('node-tests-133',test.status===0&&/pass 133/.test(test.stdout),`exit=${test.status}`);fs.writeFileSync('evidence/NODE_TESTS_v0.3.txt',test.stdout+test.stderr);
const wsPath='outputs/ice-swordswoman-3d/workspace.json';add('demo-workspace-exists',fs.existsSync(wsPath));if(fs.existsSync(wsPath)){const ws=JSON.parse(fs.readFileSync(wsPath)),v=verifyWorkspace(ws,{baseDir:path.dirname(wsPath),verifyFiles:true});add('workspace-file-verification',v.valid,`${v.file_integrity_checked} files; ${v.errors.join(',')}`);const r=validateRealityBranchWorkspace(ws.reality_branch_workspace);add('rbf-adapter-verification',r.valid,r.errors.join(','));const selected=ws.candidates.find(c=>c.candidate_id===ws.recommended_candidate_id),base=path.join('outputs/ice-swordswoman-3d/candidates',selected.variant);for(let i=0;i<3;i++){const p=path.join(base,'mesh',`lod${i}.glb`),glb=fs.existsSync(p)?inspectGlb(fs.readFileSync(p)):{valid:false,errors:['MISSING']};add(`glb-lod${i}-valid`,glb.valid,glb.errors.join(','));}const tris=[0,1,2].map(i=>selected.artifacts[i===0?'mesh-glb':`mesh-lod${i}-glb`].metadata.triangle_count);add('lod-triangles-descend',tris[0]>tris[1]&&tris[1]>tris[2],tris.join(' > '));add('production-score',ws.reports.every(x=>x.scores.production>=6500));add('provider-license-evidence',ws.continuity_bundle.provenance.providers.every(p=>p.license&&p.license!=='unspecified'));add('asset-family-valid',ws.asset_family?.members?.length===3&&ws.asset_family.members.filter(x=>x.selected).length===1);add('prefab-present',Boolean(selected.artifacts['prefab-blueprint']));add('projection-present',Boolean(selected.artifacts['projection-manifest']));add('retarget-present',Boolean(selected.artifacts['retarget-profile']));add('lineage-present',ws.lineage_graph?.asset_id===ws.genome.identity.asset_id);}

const regenPath='outputs/ice-swordswoman-3d-palette/workspace.json';add('regenerated-workspace-exists',fs.existsSync(regenPath));if(fs.existsSync(regenPath)&&fs.existsSync(wsPath)){const baseWs=JSON.parse(fs.readFileSync(wsPath)),regenWs=JSON.parse(fs.readFileSync(regenPath)),rv=verifyWorkspace(regenWs,{baseDir:path.dirname(regenPath),verifyFiles:true});add('regenerated-workspace-verification',rv.valid,rv.errors.join(','));add('regeneration-preserves-asset-id',regenWs.genome.identity.asset_id===baseWs.genome.identity.asset_id);add('regeneration-has-receipt',Boolean(regenWs.regeneration_receipt?.receipt_root));add('palette-patch-reuses-mesh-root',regenWs.regeneration_receipt?.reused_by_content_root?.includes('mesh-glb'));add('palette-patch-changes-pbr',regenWs.regeneration_receipt?.changed_roles?.includes('pbr-texture-pack'));add('lineage-links-previous-workspace',regenWs.lineage_graph?.nodes?.some(n=>n.root===baseWs.workspace_root));}
for(const [name,p,signature] of [['sprite-png','outputs/ice-swordswoman-3d/candidates/mobile/sprite-sheet.png',Buffer.from([137,80,78,71,13,10,26,10])],['audio-wav','outputs/ice-swordswoman-3d/candidates/mobile/audio/attack-sfx.wav',Buffer.from('RIFF')],['pbr-normal','outputs/ice-swordswoman-3d/candidates/mobile/pbr/normal.png',Buffer.from([137,80,78,71,13,10,26,10])]]){const b=fs.existsSync(p)?fs.readFileSync(p):Buffer.alloc(0);add(name,b.subarray(0,signature.length).equals(signature),p);}
for(const p of ['schemas/asset-intent.v0.3.schema.json','schemas/asset-genome.v0.3.schema.json','schemas/provider-manifest.v0.3.schema.json','schemas/genesis-workspace.v0.3.schema.json','schemas/asset-family.v0.3.schema.json','schemas/prefab-blueprint.v0.3.schema.json','schemas/projection-manifest.v0.3.schema.json','schemas/incremental-regeneration-plan.v0.3.schema.json','docs/ASSET_FAMILY_COMPILER_CONTRACT_v0.3.md','docs/INCREMENTAL_REGENERATION_PROTOCOL_v0.3.md'])add(`required:${p}`,fs.existsSync(p));
const sourceFiles=fs.readdirSync('src',{recursive:true}).filter(x=>String(x).endsWith('.mjs'));let evalHit=false;for(const f of sourceFiles){const s=fs.readFileSync(path.join('src',f),'utf8');if(/\beval\s*\(|new Function\s*\(/.test(s))evalHit=true;}add('no-dynamic-eval',!evalHit);const failures=checks.filter(x=>!x.pass),report={format:'reality-asset.release-audit.v0.3',version:'0.3.0-alpha.1',status:failures.length?'FAIL':'PASS',checks,failures};fs.writeFileSync('evidence/RELEASE_AUDIT_v0.3.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;
