export const QUEST_TYPES = [
  "WORLD_EXPLORATION","NPC_INTERACTION","SYSTEM_REPAIR","REALITY_ANCHOR",
  "CREATION_TASK","ARCHIVE_TASK","RELATION_TASK","RECOVERY_TASK",
  "FOUNDER_TASK","END_STATE_TASK",
] as const;
export type QuestType = typeof QUEST_TYPES[number];

export const QUEST_TYPE_LABEL: Record<QuestType, string> = {
  WORLD_EXPLORATION:"世界探索", NPC_INTERACTION:"NPC互动", SYSTEM_REPAIR:"系统修复",
  REALITY_ANCHOR:"现实锚点", CREATION_TASK:"创造任务", ARCHIVE_TASK:"归档任务",
  RELATION_TASK:"关系任务", RECOVERY_TASK:"恢复任务", FOUNDER_TASK:"创始人任务",
  END_STATE_TASK:"终局任务",
};

export const DIGIT_QUEST_AFFINITY: Record<string, QuestType[]> = {
  "0": ["ARCHIVE_TASK","SYSTEM_REPAIR"],
  "1": ["FOUNDER_TASK","WORLD_EXPLORATION"],
  "2": ["RELATION_TASK","NPC_INTERACTION"],
  "3": ["CREATION_TASK","NPC_INTERACTION"],
  "4": ["SYSTEM_REPAIR","REALITY_ANCHOR"],
  "5": ["WORLD_EXPLORATION","REALITY_ANCHOR"],
  "6": ["RECOVERY_TASK","RELATION_TASK"],
  "7": ["WORLD_EXPLORATION","ARCHIVE_TASK"],
  "8": ["CREATION_TASK","RELATION_TASK"],
  "9": ["END_STATE_TASK","FOUNDER_TASK"],
};
