import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {UnifiedManufacturingSession,AssetForgeSession,AssetForgeRegistry,ASSET_FORGE_VERSION,createAssetRecord} from '../src/index.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const sample=()=>JSON.parse(fs.readFileSync(path.join(root,'examples','冰境试炼.unified-project.json'),'utf8'));
const intent={description:'创建一名冰属性三维女剑士，名字叫霜璃，属于北境守望者，动作敏捷，攻击前有预警。',subject_id:'subject:studio-forge-test',asset_kind:'character-3d',target_platforms:['desktop','mobile','web','xr'],constraints:{palette:['#1c4fa3','#f2f6ff','#9ddcff','#17305a'],style:'stylized-readable-pbr',max_texture_size:512,max_sprite_frames:6,audio_seconds:.8,max_particles:96,max_triangles:2400,pbr_texture_size:256,max_bones:64,animation_fps:30}};
function make(){const manufacturing=new UnifiedManufacturingSession(sample()),forge=new AssetForgeSession(manufacturing,intent,{outDir:fs.mkdtempSync(path.join(os.tmpdir(),'studio-forge-'))});return{manufacturing,forge}}

test('Studio v1.5 creates an asset forge session',()=>{const {forge}=make();const i=forge.inspect();assert.equal(i.version,ASSET_FORGE_VERSION);assert.equal(i.status,'new')});
test('asset forge generates three RAGF candidates',()=>{const {forge}=make();const i=forge.generate();assert.equal(i.status,'review');assert.equal(i.production.candidates.length,3);assert.ok(i.production.candidates.every(c=>c.pass))});
test('asset forge preview exposes real mesh material and embodiment',()=>{const {forge}=make();forge.generate();const p=forge.preview();assert.ok(p.runtime_payload.mesh.positions.length>0);assert.ok(p.runtime_payload.mesh.indices.length>0);assert.ok(p.runtime_payload.material.baseColor);assert.equal(p.runtime_payload.physical.body.shape,'capsule-3d');assert.equal(p.runtime_payload.prefab.components.length,6)});
test('candidate switching changes selected preview variant',()=>{const {forge}=make();const i=forge.generate(),cinematic=i.production.candidates.find(c=>c.variant==='cinematic');forge.select(cinematic.candidate_id);assert.equal(forge.preview().variant,'cinematic')});
test('targeted palette regeneration advances generation and preserves identity',()=>{const {forge}=make();const a=forge.generate(),asset=a.production.asset.asset_id,b=forge.regenerate({constraints:{palette:['#2f59c4','#ffffff','#80e8ff','#101a34']}});assert.equal(b.production.generation,2);assert.equal(b.production.asset.asset_id,asset);assert.ok(b.production.generations[1].regeneration_receipt_root)});
test('Studio accepts RAGF v0.3 continuity bundles',()=>{const {forge}=make();forge.generate();const x=forge.production.exportArtifacts(),record=createAssetRecord(x.continuity_bundle,{sourceRoot:forge.production.current().out_dir,strictFiles:true});assert.equal(record.format,'reality-studio.asset-record.v1.5');assert.equal(record.bundle_root,x.continuity_bundle.bundle_root)});
test('accept imports asset and instantiates scene node',()=>{const {manufacturing,forge}=make();const beforeAssets=manufacturing.project.assets.order.length,beforeNodes=manufacturing.project.scenes[0].nodes.length;const i=forge.generate();forge.acceptIntoProject({x:224,y:144});assert.equal(manufacturing.project.assets.order.length,beforeAssets+1);assert.equal(manufacturing.project.scenes[0].nodes.length,beforeNodes+1);assert.equal(forge.inspect().accepted.asset_id,i.production.asset.asset_id)});
test('3D acceptance creates RSR body and character',()=>{const {manufacturing,forge}=make();const beforeBodies=manufacturing.spatial.config.bodies.length,beforeCharacters=manufacturing.spatial.config.characters.length;forge.generate();const i=forge.acceptIntoProject({x:120,y:100,z:20});assert.equal(manufacturing.spatial.config.bodies.length,beforeBodies+1);assert.equal(manufacturing.spatial.config.characters.length,beforeCharacters+1);assert.ok(i.accepted.spatial_body_id);assert.ok(i.accepted.spatial_character_id)});
test('accepted scene node keeps asset forge and spatial bindings',()=>{const {manufacturing,forge}=make();forge.generate();const i=forge.acceptIntoProject(),node=manufacturing.project.scenes[0].nodes.find(n=>n.node_id===i.accepted.node_id);assert.equal(node.asset_id,i.accepted.asset_id);assert.equal(node.components.asset_forge_id,forge.forge_id);assert.equal(node.components.spatial_body_id,i.accepted.spatial_body_id)});
test('asset forge export binds production preview and project roots',()=>{const {forge}=make();forge.generate();forge.acceptIntoProject();const x=forge.exportArtifacts();assert.equal(x.manifest.production_manifest_root,x.production.production_manifest.manifest_root);assert.equal(x.manifest.preview_root,x.preview.preview_root);assert.equal(x.manifest.acceptance_root,x.acceptance.acceptance_root);assert.equal(x.manifest.manifest_root.length,64)});
test('accepted generated files pass strict Studio asset verification',()=>{const {manufacturing,forge}=make();forge.generate();const i=forge.acceptIntoProject(),record=manufacturing.project.assets.registry[i.accepted.asset_id];assert.ok(record.files.length>=20);assert.ok(record.files.every(f=>fs.existsSync(f.absolute_path)))});
test('registry creates and retrieves forge sessions',()=>{const manufacturing=new UnifiedManufacturingSession(sample()),registry=new AssetForgeRegistry(),forge=registry.create(manufacturing,intent,{outDir:fs.mkdtempSync(path.join(os.tmpdir(),'studio-forge-registry-'))});assert.equal(registry.get(forge.forge_id),forge);assert.throws(()=>registry.get('missing'),/ASSET_FORGE_SESSION_NOT_FOUND/)});
test('forge root changes after generation selection and acceptance',()=>{const {forge}=make();const a=forge.inspect().forge_root,b=forge.generate().forge_root,cinematic=forge.inspect().production.candidates.find(c=>c.variant==='cinematic');const c=forge.select(cinematic.candidate_id).forge_root,d=forge.acceptIntoProject().forge_root;assert.notEqual(a,b);assert.notEqual(b,c);assert.notEqual(c,d)});
