import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import test from 'node:test';
import {Canvas,color} from '../../../packages/world/native-character-morphogenesis-runtime/src/raster.mjs';
import {NativeCharacterSurgeryWorkspace} from '../src/native-character-surgery-studio.mjs';
import {startStudioServer} from '../src/server.mjs';

const writeJson=(file,value)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,`${JSON.stringify(value,null,2)}\n`)};
const fixture=()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rncs-native-surgery-')),png=new Canvas(8,8);png.gradient(color('#dbe7eb'),color('#8e9da8'));for(const file of ['anatomy-contact-sheet.png','phase6-1-frame-action.png','repair-experiment/repair-before.png','repair-experiment/repair-after.png']){const target=path.join(dir,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,png.png())}writeJson(path.join(dir,'phase-status.json'),{media_status:'blocked',media_failure:'MEDIA_TOOL_NOT_FOUND',human_visual_acceptance:'pending',body_surface_status:'complete',face_rig_status:'complete',hair_topology_status:'complete',shoulder_torso_pelvis_status:'complete',joint_deformation_status:'complete',hand_abstraction_status:'complete',anatomy_validation_pack_status:'complete',rebuilt_native_shot_status:'blocked',boundary:'experimental'});writeJson(path.join(dir,'provider-manifest.json'),{provider_id:'rncs.native-character-morphogenesis.cpu',deterministic:true,seed_support:true,cpu_required:true,output_types:['RGBA PNG','MP4 via FFmpeg'],provider_root:'provider-root'});writeJson(path.join(dir,'anatomy-pack.json'),{pack_root:'pack-root'});writeJson(path.join(dir,'morphogenesis-surgery-report.json'),{baseline:{file:'phase6-baseline-frame.png'},after:{frames:[]},visual_surgery_uplift_vs_phase6:'pending-human-review',human_visual_acceptance:'pending',criteria:{shoulder_torso_pelvis:'complete'}});writeJson(path.join(dir,'repair-receipt.json'),{status:'candidate',region:'elbow-left',frame_range:{start:55,end:86},root_preservation:{identity_and_unaffected_roots_preserved:true},rollback:{allowed:true},repair_root:'repair-root'});writeJson(path.join(dir,'media-result.json'),{status:'blocked',reason:'MEDIA_TOOL_NOT_FOUND',wav:{sha256:'wav'}});writeJson(path.join(dir,'morphogenesis-surgery-ledger.json'),{status:'blocked',ledger_internal_root:'ledger-root',ledger_file_sha256:'ledger-file',evidence_bundle_root:'bundle-root',roots:{character_identity_root:'identity',character_genome_root:'genome',anatomy_pack_root:'pack-root'}});return dir};

test('workspace exposes progressive status and blocks path traversal',()=>{const dir=fixture(),workspace=new NativeCharacterSurgeryWorkspace({evidenceDir:dir}),value=workspace.inspect();assert.equal(value.first_screen.can_play,false);assert.equal(value.first_screen.failed_part,'MEDIA_TOOL_NOT_FOUND');assert.equal(value.structural_status.body_surface,'complete');assert.equal(value.provider.provider_id,'rncs.native-character-morphogenesis.cpu');assert.equal(workspace.compare().automatic_selection,false);assert.equal(workspace.repairPreview().write_performed,false);assert.equal(workspace.rollbackPreview().write_performed,false);assert.throws(()=>workspace.frame({name:'../episode.mp4'}),error=>error.code==='EVIDENCE_PATH_FORBIDDEN');assert.throws(()=>workspace.frame({name:'not-allowlisted.png'}),error=>error.code==='FRAME_NOT_IN_EVIDENCE_ALLOWLIST');assert.equal(workspace.frame({name:'anatomy-contact-sheet.png'}).bytes>0,true)});

test('Reality Studio server exposes desktop/mobile-stable surgery endpoints',async()=>{const dir=fixture(),dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'rncs-studio-server-')),started=await startStudioServer({port:0,dataDir,nativeCharacterSurgeryEvidenceDir:dir});try{const summary=await fetch(`${started.url}/api/anime-forge/native-character-surgery`).then(response=>response.json());assert.equal(summary.format,'reality-studio.native-character-surgery-workspace.v0.1');const compare=await fetch(`${started.url}/api/anime-forge/native-character-surgery`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command:'compare'})}).then(response=>response.json());assert.equal(compare.automatic_selection,false);const image=await fetch(`${started.url}/api/anime-forge/native-character-surgery/asset/anatomy-contact-sheet.png`);assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');const forbidden=await fetch(`${started.url}/api/anime-forge/native-character-surgery/asset/..%2Fphase-status.json`);assert.equal(forbidden.status,500);}finally{await new Promise(resolve=>started.server.close(resolve))}});

test('Anime Forge page contains the surgery workspace hook for both viewport modes',()=>{const html=fs.readFileSync(fileURLToPath(new URL('../web/anime-forge.html',import.meta.url)),'utf8');assert.match(html,/nativeSurgeryPanel/u);assert.match(html,/nativeSurgeryImage/u);assert.match(html,/native-character-surgery/u);assert.match(html,/visual-candidate-status/u)});
