import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {
  SPATIAL_STUDIO_VERSION,SPATIAL_WORKSPACE_FORMAT,createDefaultSpatialWorkspace,
  sealSpatialWorkspace,ensureSpatialWorkspace,validateSpatialWorkspace,SpatialStudioSession,
  createSpatialRuntimeManifest
} from '../src/spatial-studio.mjs';
import {UnifiedManufacturingSession,ensureUIInputProject,validateUnifiedProject} from '../src/scene-studio.mjs';
import {verifySpatialReplayBundle} from '@taowind/reality-engine-session/spatial-replay';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const project=()=>ensureUIInputProject(JSON.parse(fs.readFileSync(path.join(root,'examples','冰境试炼.unified-project.json'),'utf8')));

test('spatial studio version constants',()=>{assert.equal(SPATIAL_STUDIO_VERSION,'1.4.0-alpha.1');assert.equal(SPATIAL_WORKSPACE_FORMAT,'reality-studio.spatial-workspace.v1.4')});
test('default spatial workspace validates',()=>{const w=createDefaultSpatialWorkspace();const v=validateSpatialWorkspace(w);assert.equal(v.valid,true);assert.equal(v.body_count,4);assert.equal(v.character_count,1)});
test('spatial workspace seal is deterministic',()=>{const w=createDefaultSpatialWorkspace(),a=sealSpatialWorkspace(w),b=sealSpatialWorkspace(w);assert.equal(a.workspace_root,b.workspace_root)});
test('ensure spatial workspace upgrades project',()=>{const p={identity:{project_id:'p'},editor:{}};const x=ensureSpatialWorkspace(p);assert.equal(x.spatial3d.format,SPATIAL_WORKSPACE_FORMAT);assert.equal(x.editor.selected_spatial_body_id,'avatar')});
test('invalid active world is rejected',()=>{const w=createDefaultSpatialWorkspace();w.active_world_id='world:missing';const v=validateSpatialWorkspace(w);assert.equal(v.valid,false);assert.ok(v.errors.some(e=>e.code==='SPATIAL_ACTIVE_WORLD_MISSING'))});
test('invalid joint reference is rejected',()=>{const w=createDefaultSpatialWorkspace(),world=w.worlds[w.active_world_id];world.joints.push({id:'bad',type:'distance',bodyA:'avatar',bodyB:'missing',restLength:1000});const v=validateSpatialWorkspace(w);assert.equal(v.valid,false);assert.ok(v.errors.some(e=>e.code==='SPATIAL_JOINT_BODY_MISSING'))});
test('spatial session exposes body snapshot and VSR frame',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace()),i=s.inspect();assert.equal(i.snapshot.bodies.length,4);assert.equal(i.frame.verified,true);assert.ok(i.frame.frame_root);assert.equal(i.frame.stats.visibleDraws,5)});
test('body selection changes editor state',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());s.selectBody('crate-a');assert.equal(s.workspace.editor.selected_body_id,'crate-a');assert.equal(s.inspect().selected_body.id,'crate-a')});
test('add box body updates runtime',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace()),before=s.inspect().snapshot.bodies.length;s.addBody({id:'body:test',shape:'box',position:{x:0,y:1200,z:0}});const i=s.inspect();assert.equal(i.snapshot.bodies.length,before+1);assert.ok(i.snapshot.bodies.some(b=>b.id==='body:test'))});
test('add sphere body uses radius',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());s.addBody({id:'sphere:test',shape:'sphere',radius:333});const b=s.config.bodies.find(x=>x.id==='sphere:test');assert.equal(b.fixtures[0].shape.type,'sphere');assert.equal(b.fixtures[0].shape.radius,333)});
test('patch body updates transform and resets runtime',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());s.patchBody('crate-a',{position:{x:2222,y:777,z:-333}});const b=s.inspect().snapshot.bodies.find(x=>x.id==='crate-a');assert.deepEqual(b.position,{x:2222,y:777,z:-333});assert.equal(s.inspect().snapshot.tick,0)});
test('patch fixture changes collider type',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());s.patchFixture('crate-a','crate-a:shape',{shape:{type:'sphere',radius:420}});const f=s.config.bodies.find(x=>x.id==='crate-a').fixtures[0];assert.equal(f.shape.type,'sphere');assert.equal(f.shape.radius,420)});
test('remove body removes dependent character and joint',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());s.addJoint({id:'joint:test',bodyA:'avatar',bodyB:'crate-a'});s.removeBody('avatar');assert.equal(s.config.characters.length,0);assert.equal(s.config.joints.length,0)});
test('add distance joint compiles',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());s.addJoint({id:'joint:test',bodyA:'avatar',bodyB:'crate-a',type:'distance',restLength:2500});const j=s.inspect().snapshot.joints.find(x=>x.id==='joint:test');assert.equal(j.type,'distance');assert.equal(j.restLength,2500)});
test('add ball and hinge joints compile',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());s.addJoint({id:'joint:ball',bodyA:'avatar',bodyB:'crate-a',type:'ball'});s.addJoint({id:'joint:hinge',bodyA:'crate-a',bodyB:'orb',type:'hinge'});assert.deepEqual(s.inspect().snapshot.joints.map(j=>j.type).sort(),['ball','hinge'])});
test('patch and remove joint',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());s.addJoint({id:'joint:test',bodyA:'avatar',bodyB:'crate-a'});s.patchJoint('joint:test',{breakForce:12345});assert.equal(s.config.joints[0].breakForce,12345);s.removeJoint('joint:test');assert.equal(s.config.joints.length,0)});
test('upsert character binds body',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());s.upsertCharacter({id:'subject:npc',bodyId:'crate-a',walkSpeed:2000,acceleration:9000,jumpSpeed:3000});assert.ok(s.config.characters.some(c=>c.id==='subject:npc'&&c.bodyId==='crate-a'))});
test('character move command changes avatar position',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());const before=s.inspect().snapshot.bodies.find(b=>b.id==='avatar').position.x;for(let i=0;i<30;i++)s.step({commands:[{type:'move-character',characterId:'subject:player',direction:{x:1000000,y:0,z:0},speedQ:1000000}]});const after=s.inspect().snapshot.bodies.find(b=>b.id==='avatar').position.x;assert.ok(after>before)});
test('jump command raises character',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());let body=s.inspect().snapshot.bodies.find(b=>b.id==='avatar');for(let i=0;i<20&&!body.grounded;i++){s.step();body=s.inspect().snapshot.bodies.find(b=>b.id==='avatar')}const before=body.position.y;s.command({type:'jump-character',characterId:'subject:player'});const peak=[];for(let i=0;i<12;i++){s.step();peak.push(s.inspect().snapshot.bodies.find(b=>b.id==='avatar').position.y)}assert.ok(Math.max(...peak)>before+100)});
test('impulse command changes orb velocity',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());const before=s.inspect().snapshot.bodies.find(b=>b.id==='orb').velocity.x;s.command({type:'apply-impulse',bodyId:'orb',impulse:{x:1000,y:0,z:0}});const after=s.inspect().snapshot.bodies.find(b=>b.id==='orb').velocity.x;assert.notEqual(after,before)});
test('same commands produce deterministic state root',()=>{const make=()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());for(let i=0;i<20;i++)s.step({commands:[{type:'move-character',characterId:'subject:player',direction:{x:1000000,y:0,z:0}}]});return s.inspect().snapshot.stateRoot};assert.equal(make(),make())});
test('snapshot restore converges',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());for(let i=0;i<10;i++)s.step();const saved=s.createSnapshot('ten');for(let i=0;i<12;i++)s.step();s.restoreSnapshot(saved.snapshot_id);assert.equal(s.inspect().snapshot.stateRoot,saved.state_root);assert.equal(s.inspect().snapshot.tick,10)});
test('camera update changes frame root but not body root',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace()),a=s.inspect();s.setCamera({positionMilli:{x:9000}});const b=s.inspect();assert.equal(a.snapshot.bodyRoot,b.snapshot.bodyRoot);assert.notEqual(a.frame.frame_root,b.frame.frame_root)});
test('reference render produces PNG and pixel root',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace()),r=s.renderReference({width:160,height:90,qualityTier:'economy'});assert.equal(Buffer.from(r.png).subarray(1,4).toString(),'PNG');assert.ok(r.pixelRoot);assert.equal(r.frameVerified,true)});
test('causal delta carries state evidence',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace()),d=s.causalDelta('rfe:base');assert.equal(d.baseRealityRoot,'rfe:base');assert.equal(d.evidence.stateRoot,s.inspect().snapshot.stateRoot);assert.ok(d.deltaRoot)});
test('studio spatial session exports and compares verified replay branches',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace());for(let i=0;i<2;i++)s.step();const bundle=s.createReplayBundle({ticks:2,commands:[{id:'studio-replay-x',tick:3,type:'move-character',characterId:'subject:player',direction:{x:1000000,y:0,z:0},speedQ:1000000}]});assert.equal(verifySpatialReplayBundle(bundle).valid,true);const branch=s.createReplayBranch(bundle,{fromCheckpoint:0,branchId:'branch:studio-replay-z',ticks:1,commands:[{id:'studio-replay-z',tick:4,type:'move-character',characterId:'subject:player',direction:{x:0,y:0,z:1000000},speedQ:1000000}]});const comparison=s.compareReplayBranches(bundle,branch);assert.equal(comparison.same_state,false);assert.ok(comparison.changed_body_ids.includes('avatar')||comparison.changed_snapshot_sections.length>0);assert.ok(s.events.some(event=>event.type==='spatial.replay-branch-created'))});
test('runtime manifest binds workspace state frame and delta',()=>{const s=new SpatialStudioSession(createDefaultSpatialWorkspace()),e=s.exportArtifacts(),m=e.spatial_runtime_manifest;assert.equal(m.workspace_root,s.workspace.workspace_root);assert.equal(m.state_root,e.spatial_snapshot.stateRoot);assert.equal(m.frame_root,e.spatial_frame_plan.frameRoot);assert.equal(m.causal_delta_root,e.spatial_causal_delta.deltaRoot);assert.ok(m.manifest_root)});
test('unified project includes valid spatial workspace',()=>{const p=project(),v=validateUnifiedProject(p);assert.equal(v.valid,true);assert.equal(v.spatial.body_count,4)});
test('unified session exposes spatial inspection',()=>{const s=new UnifiedManufacturingSession(project()),i=s.inspect();assert.equal(i.spatial.validation.valid,true);assert.equal(i.spatial.snapshot.bodies.length,4);assert.equal(i.spatial.frame.verified,true)});
test('unified session spatial body edit enters project history',()=>{const s=new UnifiedManufacturingSession(project()),root=s.project.project_root;s.spatialAddBody({id:'body:history',shape:'box'});assert.notEqual(s.project.project_root,root);assert.ok(s.inspect().project_full.spatial3d.worlds[s.project.spatial3d.active_world_id].bodies.some(b=>b.id==='body:history'));s.undo();assert.equal(s.inspect().project_full.spatial3d.worlds[s.project.spatial3d.active_world_id].bodies.some(b=>b.id==='body:history'),false)});
test('unified export contains spatial artifacts',()=>{const s=new UnifiedManufacturingSession(project()),e=s.exportArtifacts();for(const k of ['spatial_workspace','spatial_world','spatial_snapshot','spatial_scene','spatial_frame_plan','spatial_causal_delta','spatial_runtime_manifest'])assert.ok(e[k]);assert.ok(e.build_plan.files.includes('spatial-runtime.manifest.json'))});
