import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {
  TILEMAP_FORMAT,TILEMAP_VERSION,NAVIGATION_FORMAT,createDefaultTileset,createTileMap,generateFrostTrialTileMap,validateTileMap,
  setTile,paintTiles,paintRect,floodFill,compileTileMapProjection,compileCollisionShapes,compileNavigationGrid,worldToCell,cellToWorld,
  findPath,smoothPath,pathWorldPoints,collectDynamicObstacles,compileSceneNavigation,navigationReceipt
} from '../src/tilemap-navigation.mjs';
import {UnifiedManufacturingSession,validateUnifiedProject} from '../src/scene-studio.mjs';
import {sceneProjectionToVSRDisplayState} from '../src/gpu-studio.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const project=()=>JSON.parse(fs.readFileSync(path.join(root,'examples','冰境试炼.unified-project.json'),'utf8'));

test('TileMap and navigation constants',()=>{assert.equal(TILEMAP_FORMAT,'reality-studio.tilemap.v1.1');assert.equal(TILEMAP_VERSION,'1.1.0-alpha.1');assert.equal(NAVIGATION_FORMAT,'reality-studio.navigation-grid.v1.1')});
test('default tileset has solid wall and costly hazard',()=>{const t=createDefaultTileset();assert.equal(t.tiles['2'].solid,true);assert.ok(t.tiles['5'].cost>t.tiles['1'].cost);assert.match(t.tileset_root,/^[a-f0-9]{64}$/)});
test('new tilemap validates',()=>{assert.equal(validateTileMap(createTileMap()).valid,true)});
test('invalid tilemap cell count is rejected',()=>{const t=createTileMap();t.layers[0].cells.pop();assert.equal(validateTileMap(t).valid,false)});
test('single tile paint changes root and keeps source immutable',()=>{const a=createTileMap(),b=setTile(a,{layerId:'layer:terrain',x:2,y:3,tileId:2});assert.notEqual(a.tilemap_root,b.tilemap_root);assert.equal(a.layers[1].cells[3*a.width+2],0);assert.equal(b.layers[1].cells[3*b.width+2],2)});
test('paint tiles ignores cells outside bounds',()=>{const t=paintTiles(createTileMap({width:4,height:4}),{layerId:'layer:terrain',cells:[{x:1,y:1},{x:99,y:99}],tileId:3});assert.equal(t.layers[1].cells.filter(x=>x===3).length,1)});
test('paint rect fills deterministic area',()=>{const t=paintRect(createTileMap({width:6,height:6}),{layerId:'layer:terrain',x0:1,y0:2,x1:3,y1:4,tileId:2});assert.equal(t.layers[1].cells.filter(x=>x===2).length,9)});
test('flood fill replaces connected region',()=>{let t=createTileMap({width:5,height:5});t=paintRect(t,{layerId:'layer:terrain',x0:0,y0:0,x1:4,y1:4,tileId:1});t=setTile(t,{layerId:'layer:terrain',x:2,y:2,tileId:2});const f=floodFill(t,{layerId:'layer:terrain',x:0,y:0,tileId:3});assert.equal(f.layers[1].cells.filter(x=>x===3).length,24);assert.equal(f.layers[1].cells[12],2)});
test('out of bounds paint throws',()=>{assert.throws(()=>setTile(createTileMap(),{layerId:'layer:terrain',x:-1,y:0,tileId:2}),/TILEMAP_CELL_OUT_OF_BOUNDS/)});
test('frost trial map validates with four layers',()=>{const t=generateFrostTrialTileMap();assert.equal(validateTileMap(t).valid,true);assert.equal(t.layers.length,4);assert.equal(t.width,40);assert.equal(t.height,22)});
test('projection merges adjacent tiles into fewer rectangles',()=>{const t=generateFrostTrialTileMap(),p=compileTileMapProjection(t);const nonzero=t.layers.filter(l=>l.kind==='visual').flatMap(l=>l.cells).filter(Boolean).length;assert.ok(p.rects.length<nonzero/3);assert.match(p.projection_root,/^[a-f0-9]{64}$/)});
test('collision compiler merges walls',()=>{const c=compileCollisionShapes(generateFrostTrialTileMap());assert.ok(c.shapes.length>0);assert.ok(c.shapes.length<100);assert.equal(c.shapes.every(s=>s.kind==='box'),true)});
test('navigation grid marks border wall blocked',()=>{const t=generateFrostTrialTileMap(),g=compileNavigationGrid(t);assert.equal(g.walkable[0],0);assert.equal(g.walkable[1+t.width],1);assert.match(g.navigation_root,/^[a-f0-9]{64}$/)});
test('world cell conversion is stable',()=>{const t=generateFrostTrialTileMap(),c=worldToCell(t,72,272),w=cellToWorld(t,c.x,c.y);assert.deepEqual(w,{x:72,y:272})});
test('A star finds route around ruins',()=>{const t=generateFrostTrialTileMap(),g=compileNavigationGrid(t),p=findPath(g,worldToCell(t,72,272),worldToCell(t,568,224));assert.equal(p.status,'ok');assert.ok(p.cells.length>25);assert.ok(p.visited>0)});
test('path finding is deterministic',()=>{const t=generateFrostTrialTileMap(),g=compileNavigationGrid(t),s=worldToCell(t,72,272),e=worldToCell(t,568,224),a=findPath(g,s,e),b=findPath(g,s,e);assert.equal(a.path_root,b.path_root);assert.deepEqual(a.cells,b.cells)});
test('path smoothing removes unnecessary turns',()=>{const t=generateFrostTrialTileMap(),g=compileNavigationGrid(t),a=findPath(g,worldToCell(t,72,272),worldToCell(t,568,224)),b=smoothPath(g,a);assert.equal(b.status,'ok');assert.ok(b.cells.length<a.cells.length);assert.equal(b.original_cell_count,a.cells.length)});
test('unreachable map returns explicit status',()=>{let t=createTileMap({width:5,height:5});t=paintRect(t,{layerId:'layer:navigation',x0:0,y0:0,x1:4,y1:4,tileId:2});const g=compileNavigationGrid(t),p=findPath(g,{x:1,y:1},{x:3,y:3});assert.equal(p.status,'unreachable');assert.equal(p.cells.length,0)});
test('dynamic obstacle blocks navigation cells',()=>{const t=createTileMap({width:10,height:10}),a=compileNavigationGrid(t),b=compileNavigationGrid(t,{dynamicObstacles:[{obstacle_id:'crate',x:32,y:32,width:32,height:32}]});assert.ok(a.walkable.filter(Boolean).length>b.walkable.filter(Boolean).length);assert.equal(b.dynamic_obstacles[0].obstacle_id,'crate')});
test('scene dynamic obstacles respect explicit opt out',()=>{const scene={nodes:[{node_id:'a',visible:true,transform:{x:30,y:30},components:{collider:{kind:'box',width:16,height:16}}},{node_id:'b',visible:true,transform:{x:60,y:30},components:{collider:{kind:'box',width:16,height:16},navigation_obstacle:false}}]};const o=collectDynamicObstacles(scene);assert.equal(o.length,1);assert.equal(o[0].node_id,'a')});
test('compile scene navigation binds collision and grid',()=>{const p=project(),scene=p.scenes[0],n=compileSceneNavigation(scene,{excludeNodeIds:['node:player','node:navigation-scout']});assert.ok(n.collision.shapes.length);assert.equal(n.grid.tilemap_id,scene.tilemaps[0].tilemap_id)});
test('world path points bind cell centers',()=>{const t=generateFrostTrialTileMap(),g=compileNavigationGrid(t),p=smoothPath(g,findPath(g,{x:2,y:2},{x:5,y:5})),w=pathWorldPoints(t,p);assert.equal(w.length,p.cells.length);assert.equal(Number.isInteger(w[0].x),true)});
test('navigation receipt binds path roots',()=>{const t=generateFrostTrialTileMap(),g=compileNavigationGrid(t),p=findPath(g,{x:2,y:2},{x:5,y:5}),r=navigationReceipt({sceneId:'s',tilemap:t,grid:g,paths:[p],agents:[]});assert.equal(r.paths[0].path_root,p.path_root);assert.match(r.receipt_root,/^[a-f0-9]{64}$/)});
test('unified project exposes valid tilemap',()=>{const p=project(),v=validateUnifiedProject(p);assert.equal(v.valid,true);assert.equal(p.scenes[0].tilemaps.length,1)});
test('session inspection exposes tilemap and navigation agent',()=>{const s=new UnifiedManufacturingSession(project()),i=s.inspect();assert.equal(i.navigation.tilemap_count,1);assert.ok(i.navigation.positions['node:navigation-scout']);assert.equal(i.scene.tilemaps[0].format,TILEMAP_FORMAT)});
test('session tile edit changes tile and project roots',()=>{const s=new UnifiedManufacturingSession(project()),a=s.project.project_root,t=s.activeTileMap().tilemap_root;s.editTile({operation:'paint',layerId:'layer:terrain',x:8,y:8,tileId:2});assert.notEqual(s.project.project_root,a);assert.notEqual(s.activeTileMap().tilemap_root,t)});
test('session tile edit supports undo redo',()=>{const s=new UnifiedManufacturingSession(project()),a=s.activeTileMap().tilemap_root;s.editTile({operation:'paint',layerId:'layer:terrain',x:8,y:8,tileId:2});const b=s.activeTileMap().tilemap_root;s.undo();assert.equal(s.activeTileMap().tilemap_root,a);s.redo();assert.equal(s.activeTileMap().tilemap_root,b)});
test('session path query creates evidence receipt',()=>{const s=new UnifiedManufacturingSession(project()),q=s.queryPath({start:{x:72,y:272},end:{x:568,y:224},excludeNodeIds:['node:player','node:door']});assert.equal(q.path.status,'ok');assert.ok(q.path.world_points.length);assert.equal(q.receipt.paths[0].path_root,q.path.path_root)});
test('navigation agent advances during runtime step',()=>{const s=new UnifiedManufacturingSession(project()),a={...s.inspect().navigation.positions['node:navigation-scout']};s.step({});const b=s.inspect().navigation.positions['node:navigation-scout'];assert.ok(a.x!==b.x||a.y!==b.y);assert.equal(['moving','arrived'].includes(b.status),true)});
test('navigation target can be replaced and cleared',()=>{const s=new UnifiedManufacturingSession(project());s.setNavigationTarget({nodeId:'node:navigation-scout',x:200,y:200,speedMilli:4000});assert.equal(s.inspect().navigation.targets['node:navigation-scout'].x,200);s.clearNavigationTarget('node:navigation-scout');assert.equal(s.inspect().navigation.targets['node:navigation-scout'],undefined)});
test('reset restores navigation agent start',()=>{const s=new UnifiedManufacturingSession(project()),start={...s.inspect().navigation.positions['node:navigation-scout']};for(let i=0;i<10;i++)s.step({});s.reset();assert.equal(s.inspect().navigation.positions['node:navigation-scout'].x,start.x);assert.equal(s.inspect().navigation.positions['node:navigation-scout'].y,start.y)});
test('export includes tilemap navigation manifest',()=>{const s=new UnifiedManufacturingSession(project()),e=s.exportArtifacts();assert.ok(e.tilemap_navigation_manifest.manifest_root);assert.equal(e.tilemap_navigation_manifest.tilemap.format,TILEMAP_FORMAT);assert.ok(e.build_plan.files.includes('tilemap-navigation.manifest.json'))});
test('GPU display state contains batched tilemap items',()=>{const s=new UnifiedManufacturingSession(project()),d=sceneProjectionToVSRDisplayState(s.project,s.inspect().scene.projection);assert.ok(d.items.some(i=>i.tags?.includes('tilemap')));assert.ok(d.items.length>10)});
test('tile tool updates editor without changing map root',()=>{const s=new UnifiedManufacturingSession(project()),r=s.activeTileMap().tilemap_root;s.setTileTool({layerId:'layer:terrain',tileId:5,overlay:'cost',tool:'tile-paint'});assert.equal(s.inspect().editor.selected_tile_id,5);assert.equal(s.activeTileMap().tilemap_root,r)});
test('navigation agent reuses cached path across ticks',()=>{const s=new UnifiedManufacturingSession(project());for(let i=0;i<100;i++){s.step({});s.behavior.runtime.paused=false;}assert.equal(s.navigation.queries,1);assert.equal(Object.keys(s.navigation.paths).length,1)});
test('tile tool edit reseals a valid project without mutating tilemap',()=>{const s=new UnifiedManufacturingSession(project()),mapRoot=s.activeTileMap().tilemap_root,projectRoot=s.project.project_root;s.setTileTool({tileId:5,overlay:'cost',tool:'tile-paint'});assert.notEqual(s.project.project_root,projectRoot);assert.equal(s.activeTileMap().tilemap_root,mapRoot);assert.equal(validateUnifiedProject(s.project).valid,true)});
