import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
test('unified workbench exposes scene asset behavior and sequence controls',()=>{const h=read('../web/index.html');for(const id of ['sceneCanvas','scenePanel','assetPanel','playBtn','pauseBtn','stepBtn','undoBtn','redoBtn','trace','inspector','machineGraph','sequenceView','sequenceTime','sequenceTracks','buildManifest'])assert.ok(h.includes(`id="${id}"`),id);assert.ok(h.includes('sequencer-workbench.js'));assert.ok(h.includes('sequencer.css'))});
test('web app connects to authoritative unified session API',()=>{const j=read('../web/app.js');for(const route of ['/api/unified/sample','/api/unified/session/new','/api/unified/session/command','/api/unified/session/export'])assert.ok(j.includes(route),route)});
test('web app supports drag drop assets and scene manipulation',()=>{const j=read('../web/app.js');for(const token of ['text/asset-id','add-asset-node','move-node','patch-node','remove-node'])assert.ok(j.includes(token),token)});
test('sequencer workbench exposes deterministic timeline controls',()=>{const j=read('../web/sequencer-workbench.js');for(const token of ['sequence-seek','sequence-step','sequence-snapshot','sequencePlayBtn','sequenceAuthorityRoot','sequencePresentationRoot'])assert.ok(j.includes(token),token)});
test('offline v0.9 workbench is self contained',()=>{const h=read('../Reality_Studio_v0.9_统一制造工作台_离线版.html');assert.ok(h.includes('window.SAMPLE_UNIFIED='));assert.ok(h.includes('Reality Studio v0.9'));assert.ok(!h.includes('src="app.js"'));assert.ok(!h.includes('href="style.css"'))});

test('v1.5 asset forge workbench exposes native production controls',()=>{const h=read('../web/asset-forge.html'),j=read('../web/asset-forge.js');for(const id of ['description','generate','regenerate','accept','cards','canvas','evidence'])assert.ok(h.includes(`id=\"${id}\"`)||h.includes(`id="${id}"`),id);for(const route of ['/api/asset-forge/session/new','/api/asset-forge/session/generate','/api/asset-forge/session/select','/api/asset-forge/session/regenerate','/api/asset-forge/session/preview','/api/asset-forge/session/accept'])assert.ok(j.includes(route),route)});
test('offline v1.5 asset forge workbench is self contained',()=>{const h=read('../Reality_Studio_v1.5_资产创生工作台_离线版.html');assert.ok(h.includes('Reality Studio v1.5'));assert.ok(h.includes('/api/asset-forge/session/generate'));assert.ok(!h.includes('src="asset-forge.js"'));assert.ok(!h.includes('href="asset-forge.css"'))});
