import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
test('unified workbench exposes scene asset behavior and sequence controls',()=>{const h=read('../web/index.html');for(const id of ['sceneCanvas','scenePanel','assetPanel','playBtn','pauseBtn','stepBtn','undoBtn','redoBtn','trace','inspector','machineGraph','sequenceView','sequenceTime','sequenceTracks','buildManifest'])assert.ok(h.includes(`id="${id}"`),id);assert.ok(h.includes('sequencer-workbench.js'));assert.ok(h.includes('sequencer.css'))});
test('web app connects to authoritative unified session API',()=>{const j=read('../web/app.js');for(const route of ['/api/unified/sample','/api/unified/session/new','/api/unified/session/command','/api/unified/session/export'])assert.ok(j.includes(route),route)});
test('web app supports drag drop assets and scene manipulation',()=>{const j=read('../web/app.js');for(const token of ['text/asset-id','add-asset-node','move-node','patch-node','remove-node'])assert.ok(j.includes(token),token)});
test('sequencer workbench exposes deterministic timeline controls',()=>{const j=read('../web/sequencer-workbench.js');for(const token of ['sequence-seek','sequence-step','sequence-snapshot','sequencePlayBtn','sequenceAuthorityRoot','sequencePresentationRoot'])assert.ok(j.includes(token),token)});
test('offline v0.9 workbench is self contained',()=>{const h=read('../Reality_Studio_v0.9_统一制造工作台_离线版.html');assert.ok(h.includes('window.SAMPLE_UNIFIED='));assert.ok(h.includes('Reality Studio v0.9'));assert.ok(!h.includes('src="app.js"'));assert.ok(!h.includes('href="style.css"'))});

test('v1.5 asset forge workbench exposes native production controls',()=>{const h=read('../web/asset-forge.html'),j=read('../web/asset-forge.js');for(const id of ['description','generate','regenerate','accept','cards','canvas','evidence'])assert.ok(h.includes(`id=\"${id}\"`)||h.includes(`id="${id}"`),id);for(const route of ['/api/asset-forge/session/new','/api/asset-forge/session/generate','/api/asset-forge/session/select','/api/asset-forge/session/regenerate','/api/asset-forge/session/preview','/api/asset-forge/session/accept'])assert.ok(j.includes(route),route)});
test('offline v1.5 asset forge workbench is self contained',()=>{const h=read('../Reality_Studio_v1.5_资产创生工作台_离线版.html');assert.ok(h.includes('Reality Studio v1.5'));assert.ok(h.includes('/api/asset-forge/session/generate'));assert.ok(!h.includes('src="asset-forge.js"'));assert.ok(!h.includes('href="asset-forge.css"'))});

test('Reality Graph shell exposes the real-runtime product path',()=>{const h=read('../web/reality-graph.html');for(const id of ['graphCanvas','graphEdges','graphNodes','graphBranchRail','graphPromotionStatus','consoleContent','consoleSearch','inspectorContent','viewportImage','commitCard','footerTick','workspaceStatusStrip','viewportExpandButton'])assert.ok(h.includes(`id="${id}"`),id);for(const token of ['graph-layer-authoritative','graph-layer-candidate','graph-layer-promotion','graph-zone-input','graph-zone-output','brand-slogan','command-search','inspector-kicker','data-action="toggle-viewport"'])assert.ok(h.includes(token),token);assert.ok(h.includes('reality-studio.js'));assert.ok(h.includes('reality-studio.css'))});
test('Reality Graph client has no offline or sample-state fallback',()=>{const j=read('../web/reality-studio.js');for(const route of ['/api/reality-studio/session/new','/api/reality-studio/session/inspect','/api/reality-studio/session/command','/api/reality-studio/session/viewport'])assert.ok(j.includes(route),route);for(const token of ['inspector-summary','Technical details','Roots & receipts','Backend gaps','viewport-expanded','Integration timeline root','Canonical state mutated','state.replay?.scope','graphEdgePath','stateRevision','requestedRevision'])assert.ok(j.includes(token),token);assert.ok(j.includes('Native Runtime unavailable'));assert.ok(!j.includes('SAMPLE_UNIFIED'));assert.ok(!j.includes('offline'))});
test('Reality Graph refuses a raw file entry rather than inventing a Runtime',()=>{const j=read('../web/reality-studio.js');for(const token of ["window.location.protocol === 'file:'",'showFileProtocolEntry','file-entry-required','未创建假 Runtime 会话','http://127.0.0.1:17608/'])assert.ok(j.includes(token),token)});
test('Windows launcher starts the real Studio endpoint instead of an offline page',()=>{const b=read('../启动Reality Studio原生版.bat');for(const token of ['api/health','node.exe','--host','127.0.0.1','--port','17608','http://127.0.0.1:17608/','WindowStyle Hidden'])assert.ok(b.includes(token),token);assert.ok(!b.includes('离线行为工作台'))});
test('Reality Graph uses the reference palette and fits the verified VSR frame on short desktops',()=>{const c=read('../web/reality-studio.css');for(const token of ['--bg: #0d1b24','--cyan: #55caf6','--cyan-strong: #8be8ff','@media (min-width: 901px) and (max-height: 820px)','grid-template-rows: 78px minmax(200px, 1fr) 180px','#viewportImage { width: 100%; height: 100%; min-width: 0; min-height: 0;'])assert.ok(c.includes(token),token)});
test('Reality Graph product projection exposes truthful branch context, visual-only graph controls, and real event search',()=>{const h=read('../web/reality-graph.html'),j=read('../web/reality-studio.js'),c=read('../web/reality-studio.css');for(const token of ['graphBranchRail','graphPromotionStatus','graph-arrow-projection','data-action="zoom-in"','data-action="toggle-grid"','data-action="focus-graph"'])assert.ok(h.includes(token),token);for(const token of ['EDGE_MARKERS','renderGraphBranchRail','renderGraphPromotionStatus','applyGraphView','Product Body 投影视图','eventSummary','consoleQuery','consoleSearch'])assert.ok(j.includes(token),token);for(const token of ['.graph-edge-projection','.graph-edge.is-related','.graph-edge.is-dimmed','.graph-branch-chip','.graph-promotion-status','.console-message span','.filter-search input'])assert.ok(c.includes(token),token)});
test('Reality Graph product shell is positioned as a deterministic multiplayer game world engine',()=>{const h=read('../web/reality-graph.html'),j=read('../web/reality-studio.js'),c=read('../web/reality-studio.css');for(const token of ['确定性多人游戏世界引擎','WORLD PROJECT','GAME WORLD','GAMEPLAY &amp; BRANCHES','EVIDENCE &amp; AUTHORITY','MULTIPLAYER','WORLD PROJECTION','GAME WORLD GRAPH','Authoritative Server → Candidate Branch → Promotion Gate','TICK / PLAYERS','SYNC','VSR / RSR World Viewport'])assert.ok(h.includes(token),token);for(const token of ['Game World Graph','statusTickPlayersValue','statusSyncValue','authoritative server','Game World Runtime','VSR 世界投影'])assert.ok(j.includes(token),token);for(const token of ['Game World Engine product pass','.status-signal-wide','grid-template-columns: repeat(4, minmax(0, 1fr))'])assert.ok(c.includes(token),token)});
