export type CodeErrorType =
  | "MISSING_ENTRY_FILE"
  | "MISSING_PACKAGE_JSON"
  | "IMPORT_NOT_FOUND"
  | "UNDEFINED_VARIABLE"
  | "UNDEFINED_COMPONENT"
  | "INVALID_HTML"
  | "UNSAFE_SCRIPT"
  | "SENSITIVE_INPUT"
  | "BUILD_CONFIG_MISSING"
  | "PREVIEW_UNAVAILABLE"
  | "EXTERNAL_API_UNSAFE"
  | "DEPENDENCY_RISK"
  | "UNKNOWN_ERROR";

export const CODE_ERROR_TYPE_LABELS: Record<CodeErrorType, string> = {
  MISSING_ENTRY_FILE: "缺入口文件",
  MISSING_PACKAGE_JSON: "缺 package.json",
  IMPORT_NOT_FOUND: "import 文件不存在",
  UNDEFINED_VARIABLE: "未定义变量",
  UNDEFINED_COMPONENT: "未定义组件",
  INVALID_HTML: "HTML 结构错误",
  UNSAFE_SCRIPT: "危险脚本",
  SENSITIVE_INPUT: "敏感输入字段",
  BUILD_CONFIG_MISSING: "构建配置缺失",
  PREVIEW_UNAVAILABLE: "预览不可用",
  EXTERNAL_API_UNSAFE: "外部 API 风险",
  DEPENDENCY_RISK: "依赖风险",
  UNKNOWN_ERROR: "未知错误",
};
