export const AGENT_AUTONOMY_LEVELS = [
  "READ_ONLY",
  "SUGGEST",
  "DRAFT",
  "PREPARE_ACTION",
  "EXECUTE_SAFE",
  "EXECUTE_WITH_CONFIRMATION",
  "BLOCKED",
] as const;
export type AgentAutonomyLevel = typeof AGENT_AUTONOMY_LEVELS[number];

export const ACTIONS_REQUIRING_CONFIRMATION = [
  "PUBLISH", "DEPLOY", "DELETE", "SEND_MESSAGE", "PAYMENT",
  "MODIFY_ACCOUNT", "EXTERNAL_API_WRITE", "PRODUCTION_DB_WRITE",
  "PUBLIC_SHARE", "EXPORT_PRIVATE_DATA",
];

export const FORBIDDEN_AUTONOMOUS_ACTIONS = [
  "OBTAIN_PASSWORD", "OBTAIN_PAYMENT_INFO", "BYPASS_LOGIN",
  "DESTROY_SYSTEM", "EXECUTE_DANGEROUS_CODE", "DELETE_USER_FILES",
  "LEAK_FOUNDER_DATA",
];
