import fs from 'node:fs';
import path from 'node:path';
import {deflateSync} from 'node:zlib';
import {rootHash,clone} from './canonical.mjs';
import {assertValidAnimeProduction,ANIME_QUALITY_PROFILES,createFrameEvidence,createProviderReceipt} from './contracts.mjs';
import {canonicalCutRef,listProductionCuts,resolveProductionCut} from './editorial.mjs';
import {buildExposureSheet,buildProductionExposureSheets} from './xsheet.mjs';
import {createAnimeRenderingProfile,resolveAnimeCamera,createAnimeRenderReceipt} from '../../visual-state-runtime/src/anime-profile.mjs';
import {createAnimeSecondaryMotionProfile,resolveAnimeSecondaryMotion} from '../../reality-simulation-runtime/src/anime-motion.mjs';

const W=960,H=540;
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
function prepareFrameDirectory(directory){fs.mkdirSync(directory,{recursive:true});for(const entry of fs.readdirSync(directory,{withFileTypes:true}))if(entry.isFile()&&/^frame-\d{6}\.png$/u.test(entry.name))fs.rmSync(path.join(directory,entry.name))}
const rgba=(hex,alpha=255)=>{const text=String(hex).replace('#','');return[parseInt(text.slice(0,2),16),parseInt(text.slice(2,4),16),parseInt(text.slice(4,6),16),alpha]};
const mix=(a,b,t)=>a.map((value,index)=>Math.round(value+(b[index]-value)*t));
const scaleValue=(value,scale)=>Math.round(value*scale);

const crcTable=(()=>{const table=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0}return table})();
function crc32(buffer){let crc=0xffffffff;for(const value of buffer)crc=crcTable[(crc^value)&255]^(crc>>>8);return(crc^0xffffffff)>>>0}
function pngChunk(type,data){const name=Buffer.from(type),size=Buffer.alloc(4);size.writeUInt32BE(data.length,0);const check=Buffer.alloc(4);check.writeUInt32BE(crc32(Buffer.concat([name,data])),0);return Buffer.concat([size,name,data,check])}
export function encodePng(width,height,pixels){const raw=Buffer.alloc((width*4+1)*height);for(let y=0;y<height;y++){const row=y*(width*4+1);raw[row]=0;pixels.copy(raw,row+1,y*width*4,(y+1)*width*4)}const header=Buffer.alloc(13);header.writeUInt32BE(width,0);header.writeUInt32BE(height,4);header[8]=8;header[9]=6;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),pngChunk('IHDR',header),pngChunk('IDAT',deflateSync(raw,{level:6})),pngChunk('IEND',Buffer.alloc(0))])}

class Canvas{
  constructor(width,height){this.width=width;this.height=height;this.sx=width/W;this.sy=height/H;this.pixels=Buffer.alloc(width*height*4)}
  point(x,y){return[clamp(Math.round(x*this.sx),0,this.width-1),clamp(Math.round(y*this.sy),0,this.height-1)]}
  pixel(x,y,color){if(x<0||y<0||x>=this.width||y>=this.height)return;const index=(y*this.width+x)*4;this.pixels[index]=color[0];this.pixels[index+1]=color[1];this.pixels[index+2]=color[2];this.pixels[index+3]=color[3]??255}
  rect(x,y,w,h,color){const [left,top]=this.point(x,y),[right,bottom]=this.point(x+w,y+h);for(let py=top;py<=bottom;py++)for(let px=left;px<=right;px++)this.pixel(px,py,color)}
  gradient(top,bottom){for(let y=0;y<this.height;y++){const t=y/Math.max(1,this.height-1),color=mix(top,bottom,t);for(let x=0;x<this.width;x++)this.pixel(x,y,color)}}
  ellipse(cx,cy,rx,ry,color){const [x0,y0]=this.point(cx,cy),sx=rx*this.sx,sy=ry*this.sy;const left=Math.floor(x0-sx),right=Math.ceil(x0+sx),top=Math.floor(y0-sy),bottom=Math.ceil(y0+sy);for(let y=top;y<=bottom;y++)for(let x=left;x<=right;x++){const dx=(x-x0)/Math.max(1,sx),dy=(y-y0)/Math.max(1,sy);if(dx*dx+dy*dy<=1)this.pixel(x,y,color)}}
  line(x1,y1,x2,y2,color,width=2){const [ax,ay]=this.point(x1,y1),[bx,by]=this.point(x2,y2),steps=Math.max(Math.abs(bx-ax),Math.abs(by-ay));for(let i=0;i<=steps;i++){const t=steps?i/steps:0,x=Math.round(ax+(bx-ax)*t),y=Math.round(ay+(by-ay)*t);for(let ox=-Math.floor(width*this.sx/2);ox<=Math.ceil(width*this.sx/2);ox++)for(let oy=-Math.floor(width*this.sy/2);oy<=Math.ceil(width*this.sy/2);oy++)this.pixel(x+ox,y+oy,color)}}
  polygon(points,color){if(points.length<3)return;const scaled=points.map(([x,y])=>this.point(x,y)),minY=Math.max(0,Math.floor(Math.min(...scaled.map(p=>p[1])))),maxY=Math.min(this.height-1,Math.ceil(Math.max(...scaled.map(p=>p[1]))));for(let y=minY;y<=maxY;y++){const intersections=[];for(let i=0,j=scaled.length-1;i<scaled.length;j=i++){const [xi,yi]=scaled[i],[xj,yj]=scaled[j];if((yi>y)!==(yj>y))intersections.push(xi+(y-yi)*(xj-xi)/(yj-yi))}intersections.sort((a,b)=>a-b);for(let i=0;i<intersections.length;i+=2){const left=Math.max(0,Math.ceil(intersections[i])),right=Math.min(this.width-1,Math.floor(intersections[i+1]??intersections[i]));for(let x=left;x<=right;x++)this.pixel(x,y,color)}}}
  outlinePolygon(points,fill,stroke='#111923',width=3){this.polygon(points,rgba(fill));for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];this.line(a[0],a[1],b[0],b[1],rgba(stroke),width)}}
  png(){return encodePng(this.width,this.height,this.pixels)}
}

function profilesFor(production,cut){const cutRef=canonicalCutRef(cut);return{renderProfile:production.rendering_profiles?.[cutRef]?.format?production.rendering_profiles[cutRef]:(production.rendering_profile?.format?production.rendering_profile:createAnimeRenderingProfile({fps:cut.fps,resolution:cut.resolution})),motionProfile:production.motion_profiles?.[cutRef]?.format?production.motion_profiles[cutRef]:(production.motion_profile?.format?production.motion_profile:createAnimeSecondaryMotionProfile({hair:cut.animation.hair_secondary,coat:cut.animation.coat_secondary}))}}

function frameState(production,cut,frame,xsheetFrame,renderProfile,motionProfile){
  const total=Math.max(1,Math.round(cut.duration*cut.fps)),keyposes=[...(cut.key_pose_track??[])].sort((a,b)=>(a.frame??0)-(b.frame??0));
  const raiseStart=keyposes.find(item=>String(item.pose_id).includes('begin_raise'))?.frame??15,lockFrame=keyposes.find(item=>String(item.pose_id).includes('gaze_locked'))?.frame??28;
  const raiseProgress=frame<raiseStart?0:clamp((frame-raiseStart)/Math.max(1,lockFrame-raiseStart),0,1),camera=resolveAnimeCamera(renderProfile,cut.camera_track,{frame,totalFrames:total}),secondaryMotion=resolveAnimeSecondaryMotion(motionProfile,{frame});
  const dialogue=xsheetFrame.dialogue_state,rawMouth=xsheetFrame.mouth_shape;const mouth=rawMouth==='automatic_viseme'?(dialogue?'o':'closed'):rawMouth;
  const actorId=cut.character_layers?.[0]?.actor_id,characterBinding=production.asset_bindings?.character?.[actorId]??Object.values(production.asset_bindings?.character??{})[0]??null;
  return{frame,progress:frame/total,pose:keyposes.filter(item=>(item.frame??0)<=frame).at(-1)?.pose_id??'hold',raise_progress:raiseProgress,gaze_locked:frame>=lockFrame,blink:xsheetFrame.eye_state==='closed',mouth,dialogue_active:Boolean(dialogue),camera:{zoom:1+Number(camera.dolly??0),x:Number(camera.x??0),y:Number(camera.y??0)},secondary:{hair:secondaryMotion.hair,coat:secondaryMotion.coat},character:characterBinding?{actor_id:actorId,character_id:characterBinding.character_id,family_root:characterBinding.family_root,identity_root:characterBinding.identity_root,identity_signature_root:characterBinding.identity_signature_root,palette:clone(characterBinding.palette??{}),proportions:clone(characterBinding.proportions??{}),appearance:clone(characterBinding.appearance??{})}:null,render_profile:production.quality_profile?.name??'anime-tv-reference-v0.1',vsr_profile_root:characterBinding?.runtime_profiles?.vsr??renderProfile.profile_root,rsr_body_profile_root:characterBinding?.runtime_profiles?.rsr??null,rsr_motion_root:secondaryMotion.motion_root,director_overrides:{hair:secondaryMotion.hair_override,coat:secondaryMotion.coat_override}}
}

function drawBackground(canvas,state){
  const skyTop=rgba('#dfe4e7'),skyBottom=rgba('#8996a0');canvas.gradient(skyTop,skyBottom);const parallax=state.camera.x;
  canvas.polygon([[0,310],[120,236],[190,290],[278,205],[360,274],[462,222],[566,278],[660,185],[754,268],[862,216],[960,282],[960,420],[0,420]],rgba('#66737e'));
  for(let i=0;i<10;i++){const x=i*110-(parallax*W*.35%110);const height=68+(i%4)*26;canvas.rect(x,350-height,62,height,rgba(i%2?'#515d68':'#586671'));for(let window=0;window<3;window++)canvas.rect(x+12+window*15,370-height,7,10,rgba('#a9b8bd',190))}
  canvas.polygon([[0,414],[160,383],[306,413],[470,363],[610,410],[782,370],[960,405],[960,540],[0,540]],rgba('#4b5661'));
  canvas.rect(0,420,960,120,rgba('#303a45'));for(let i=0;i<9;i++)canvas.line(0,440+i*13,960,430+i*13,rgba('#697681',110),1);
  canvas.polygon([[0,488],[160,455],[300,489],[438,445],[592,490],[734,458],[960,492],[960,540],[0,540]],rgba('#202a34'));
  const postX=72-(parallax*W*.08%80);canvas.rect(postX,260,14,280,rgba('#18212b'));canvas.line(postX+7,270,postX+7,530,rgba('#9caab1',80),2);
}

function drawCharacter(canvas,state){
  const zoom=state.camera.zoom,pan=state.camera.x;const tr=(x,y)=>[(x-480)*zoom+480+pan*W*.02,(y-260)*zoom+260];
  const palette=state.character?.palette??{},shift=state.secondary,raise=state.raise_progress,deep=rgba(palette.base??'#101b2b'),coat=rgba(palette.secondary??'#182b45'),silver=rgba(palette.trim??'#c8d4dc'),skin=rgba(palette.skin??'#e3c8b7'),accent=rgba(palette.eye??'#4f83bd'),ink=rgba('#111821'),hair=rgba(palette.hair??'#111c2e'),faceScale=clamp(Number(state.character?.proportions?.head_height??.24)/.24,.88,1.12);
  const p=(x,y)=>tr(x,y);
  const emblemSlot=state.character?.appearance?.emblem_slot??'blue-axis-v1';
  const coatBody=[p(403,232),p(557,232),p(570,510),p(520,535),p(440,535),p(390,510)];canvas.outlinePolygon(coatBody,palette.secondary??'#182b45','#111821',4);
  canvas.polygon([p(421,250),p(480,275),p(539,250),p(536,478),p(480,505),p(424,478)],coat);
  canvas.polygon([p(435,262),p(480,286),p(525,262),p(507,365),p(480,388),p(453,365)],deep);
  canvas.line(...p(480,287),...p(480,500),silver,2);canvas.line(...p(447,352),...p(513,352),silver,2);
  canvas.line(...p(410,252),...p(369,463+shift.coat),deep,18);canvas.line(...p(410,252),...p(369,463+shift.coat),coat,11);canvas.line(...p(550,252),...p(591,463-shift.coat),deep,18);canvas.line(...p(550,252),...p(591,463-shift.coat),coat,11);canvas.ellipse(...p(368,472+shift.coat),9*zoom,13*zoom,skin);canvas.ellipse(...p(592,472-shift.coat),9*zoom,13*zoom,skin);
  canvas.polygon([p(466,213),p(494,213),p(500,247),p(460,247)],skin);
  canvas.ellipse(...p(480,165),49*zoom*faceScale,59*zoom*faceScale,deep);canvas.ellipse(...p(440,171-raise*4),6*zoom,13*zoom,skin);canvas.ellipse(...p(520,171-raise*4),6*zoom,13*zoom,skin);
  canvas.outlinePolygon([p(448,143-raise*4),p(442,174-raise*4),p(450,202-raise*3),p(463,218-raise*2),p(480,226-raise*2),p(497,218-raise*2),p(510,202-raise*3),p(518,174-raise*4),p(512,143-raise*4)],palette.skin??'#e3c8b7','#2b3036',2);
  const hairTop=[p(437,170-raise*4),p(439,121-raise*3),p(472,99-raise*2),p(522,116-raise*2),p(525,169-raise*4),p(509,145-raise*3),p(486,161-raise*3),p(460,145-raise*3)];canvas.outlinePolygon(hairTop,palette.hair??'#111c2e','#111821',3);
  canvas.polygon([p(440,174),p(417,224+shift.hair),p(437,252+shift.hair),p(455,187)],hair);canvas.polygon([p(520,172),p(543,224-shift.hair),p(523,250-shift.hair),p(505,185)],hair);
  canvas.line(...p(456,132-raise*3),...p(473,113-raise*2),rgba('#8da5bd',120),2);canvas.line(...p(468,138-raise*3),...p(487,111-raise*2),rgba('#8da5bd',90),2);canvas.line(...p(484,137-raise*3),...p(505,119-raise*2),rgba('#8da5bd',70),2);
  const eyeY=164-raise*2,gaze=state.gaze_locked?2:0,eyeSpread=15*faceScale;canvas.line(...p(457,151-raise*2),...p(471,149-raise*2),hair,2);canvas.line(...p(489,149-raise*2),...p(503,151-raise*2),hair,2);canvas.ellipse(...p(480-eyeSpread,eyeY),7*zoom,4*zoom,state.blink?skin:ink);canvas.ellipse(...p(480+eyeSpread,eyeY),7*zoom,4*zoom,state.blink?skin:ink);if(!state.blink){canvas.ellipse(...p(481-eyeSpread+gaze,eyeY),2.5*zoom,3.5*zoom,accent);canvas.ellipse(...p(481+eyeSpread+gaze,eyeY),2.5*zoom,3.5*zoom,accent)}
  canvas.line(...p(480,173-raise*2),...p(477,188-raise*2),rgba('#9f7770'),1);canvas.line(...p(477,188-raise*2),...p(483,189-raise*2),rgba('#9f7770'),1);const mouthY=202-raise*2;if(state.mouth==='closed'||!state.dialogue_active)canvas.line(...p(472,mouthY),...p(488,mouthY),ink,2);else{const openness=state.mouth==='a'?6:state.mouth==='i'?4:state.mouth==='o'?8:5;canvas.ellipse(...p(480,mouthY),9*zoom,openness*zoom,ink);canvas.ellipse(...p(480,mouthY-1),6*zoom,Math.max(1,openness-3)*zoom,rgba('#8d4c57'))}
  if(emblemSlot==='shenlin-original-v1'){canvas.line(...p(466,337),...p(480,349),accent,3);canvas.line(...p(480,349),...p(494,337),accent,3);canvas.line(...p(480,349),...p(480,369),silver,2)}else if(emblemSlot==='taowind-line-v1'){canvas.line(...p(465,350),...p(492,340),accent,3);canvas.line(...p(469,360),...p(496,350),silver,2)}else{canvas.line(...p(480,335),...p(480,369),accent,3);canvas.line(...p(469,347),...p(480,336),silver,2);canvas.line(...p(491,347),...p(480,336),silver,2)}
}

export function renderCutFrame(production,frameNumber,{xsheet=null,width=960,height=540,quality='preview',cutRef=null,cutId=null}={}){
  assertValidAnimeProduction(production);const cut=resolveProductionCut(production,cutRef??cutId??production.active_cut_ref),sheet=xsheet??buildExposureSheet(cut),xsheetFrame=sheet.frames[frameNumber];if(!xsheetFrame)throw new Error(`XSHEET_FRAME_NOT_FOUND:${canonicalCutRef(cut)}:${frameNumber}`);const{renderProfile,motionProfile}=profilesFor(production,cut),state=frameState(production,cut,frameNumber,xsheetFrame,renderProfile,motionProfile),canvas=new Canvas(width,height);drawBackground(canvas,state);drawCharacter(canvas,state);const bytes=canvas.png(),characterBinding=state.character,assetRoots={character:characterBinding?.family_root??rootHash(production.asset_bindings?.character??{}),background:rootHash(production.asset_bindings?.background??{})},renderOutputRoot=rootHash(bytes.toString('base64')),providerReceipts=[createProviderReceipt({provider_id:production.provider_bindings?.asset??'ragf.anime-reference-provider',capability:characterBinding?'character-asset-family':'anime-asset-family',input_root:rootHash(production.asset_bindings??{}),output_root:assetRoots.character}),createProviderReceipt({provider_id:'vsr.anime-reference-renderer',capability:'anime-render-frame',input_root:state.vsr_profile_root??renderProfile.profile_root??production.production_root,output_root:renderOutputRoot}),createProviderReceipt({provider_id:'rsr.anime-secondary-motion-reference',capability:'director-overridable-secondary-motion',input_root:state.rsr_body_profile_root??motionProfile.profile_root??production.production_root,output_root:state.rsr_motion_root})],renderReceipt=createAnimeRenderReceipt({profile:renderProfile,frameNumber,width,height,inputRoot:production.production_root,outputRoot:renderOutputRoot,animationPolicy:xsheetFrame.animation_policy});const evidence=createFrameEvidence({production,cut,frameNumber,state,assetRoots,providerReceipts,renderReceipt});return{bytes,state,xsheet_frame:xsheetFrame,evidence,render_receipt:renderReceipt};
}

export function renderCut(production,{outDir,quality='preview',width,height,maxFrames=null,cutRef=null,cutId=null}={}){
  assertValidAnimeProduction(production);if(!outDir)throw new Error('ANIME_RENDER_OUT_DIR_REQUIRED');const cut=resolveProductionCut(production,cutRef??cutId??production.active_cut_ref),resolvedCutRef=canonicalCutRef(cut),profile=ANIME_QUALITY_PROFILES[quality]??ANIME_QUALITY_PROFILES.preview;width=width??profile.width;height=height??profile.height;prepareFrameDirectory(path.join(outDir,'frames'));const xsheet=buildExposureSheet(cut),count=Math.min(xsheet.frames.length,maxFrames??xsheet.frames.length),frames=[];const started=Date.now();for(let frame=0;frame<count;frame++){const rendered=renderCutFrame(production,frame,{xsheet,width,height,quality,cutRef:resolvedCutRef});const filename=path.join(outDir,'frames',`frame-${String(frame+1).padStart(6,'0')}.png`);fs.writeFileSync(filename,rendered.bytes);frames.push({cut_ref:resolvedCutRef,frame_number:frame,filename:path.relative(outDir,filename).replaceAll('\\','/'),bytes:rendered.bytes.length,frame_id:rendered.evidence.frame_id,state_root:rendered.evidence.state_root,evidence_root:rendered.evidence.evidence_root,provider_receipts:rendered.evidence.provider_receipts,render_receipt:rendered.render_receipt})}
  const elapsedMs=Date.now()-started,manifest={format:'rncs.anime-frame-sequence-manifest.v0.1',version:'0.1.0-alpha.1',production_root:production.production_root,cut_ref:resolvedCutRef,cut_id:cut.cut_id,quality,width,height,fps:cut.fps,duration:cut.duration,expected_frame_count:Math.round(cut.duration*cut.fps),rendered_frame_count:frames.length,frames,deterministic:true,sequence_root:rootHash(frames)};
  const ledger={format:'rncs.anime-evidence-ledger.v0.1',version:'0.1.0-alpha.1',authority:'RNCS',production_root:production.production_root,cut_ref:resolvedCutRef,cut_id:cut.cut_id,deterministic:true,frame_count:frames.length,expected_frame_count:manifest.expected_frame_count,frame_refs:frames.map(frame=>({cut_ref:resolvedCutRef,frame_number:frame.frame_number,frame_id:frame.frame_id,state_root:frame.state_root,evidence_root:frame.evidence_root,provider_receipt_roots:(frame.provider_receipts??[]).map(receipt=>receipt.receipt_root),render_backend:frame.render_receipt.backend})),roots:{sequence_root:manifest.sequence_root},gates:{production_ir:'validated',xsheet:'validated',frame_raster:frames.length===manifest.expected_frame_count?'complete':'partial',provider_receipts:'recorded',mp4:'encoder-dependent'},boundary:'targeted reference evidence; not clean-VM, GPU-provider, human-performance, or commercial-quality proof'};ledger.ledger_root=rootHash(ledger);manifest.evidence_ledger_root=ledger.ledger_root;
  fs.writeFileSync(path.join(outDir,'frames-manifest.json'),JSON.stringify(manifest,null,2));fs.writeFileSync(path.join(outDir,'xsheet.json'),JSON.stringify(xsheet,null,2));fs.writeFileSync(path.join(outDir,'evidence-ledger.json'),JSON.stringify(ledger,null,2));fs.writeFileSync(path.join(outDir,'render-report.json'),JSON.stringify({format:'rncs.anime-render-report.v0.1',manifest_root:rootHash(manifest),frame_sequence_root:manifest.sequence_root,evidence_ledger_root:ledger.ledger_root,backend:'deterministic-native-2d',elapsed_ms:elapsedMs,status:frames.length===manifest.expected_frame_count?'complete':'partial',boundary:'reference procedural anime renderer; not commercial animation quality'},null,2));return{manifest,xsheet,ledger};
}

export function replayCut(production,manifest,{quality=manifest?.quality??'preview'}={}){const cut=resolveProductionCut(production,manifest?.cut_ref??manifest?.cut_id),xsheet=buildExposureSheet(cut),roots=[];for(const frame of manifest?.frames??[])roots.push(renderCutFrame(production,frame.frame_number,{cutRef:canonicalCutRef(cut),xsheet,width:manifest.width,height:manifest.height,quality}).evidence.state_root);return{valid:rootHash(roots)===rootHash((manifest.frames??[]).map(frame=>frame.state_root)),cut_ref:canonicalCutRef(cut),frame_count:roots.length,state_roots:roots,manifest_root:rootHash(manifest)}}

const safeCutPath=value=>String(value).replace(/[^a-zA-Z0-9._-]+/g,'_');

export function renderProduction(production,{outDir,quality='preview',width,height,maxFrames=null}={}){
  assertValidAnimeProduction(production);if(!outDir)throw new Error('ANIME_RENDER_OUT_DIR_REQUIRED');const profile=ANIME_QUALITY_PROFILES[quality]??ANIME_QUALITY_PROFILES.preview;width=width??profile.width;height=height??profile.height;prepareFrameDirectory(path.join(outDir,'frames'));fs.mkdirSync(path.join(outDir,'cuts'),{recursive:true});
  const timeline=production.editorial_timeline,limit=Math.min(timeline.total_frame_count,maxFrames??timeline.total_frame_count),frames=[],cutResults=[];let remaining=limit;
  for(const entry of timeline.entries){if(remaining<=0)break;const cut=resolveProductionCut(production,entry.cut_ref),count=Math.min(entry.local_frame_count,remaining),cutOut=path.join(outDir,'cuts',safeCutPath(entry.cut_ref)),result=renderCut(production,{outDir:cutOut,quality,width,height,maxFrames:count,cutRef:entry.cut_ref});cutResults.push({cut_ref:entry.cut_ref,out_dir:path.relative(outDir,cutOut).replaceAll('\\','/'),manifest:result.manifest,ledger:result.ledger});for(const frame of result.manifest.frames){const globalFrame=entry.global_start_frame+frame.frame_number,filename=path.join(outDir,'frames',`frame-${String(globalFrame+1).padStart(6,'0')}.png`),source=path.join(cutOut,frame.filename);fs.copyFileSync(source,filename);frames.push({...frame,local_frame_number:frame.frame_number,global_frame_number:globalFrame,filename:path.relative(outDir,filename).replaceAll('\\','/')})}remaining-=count}
  const complete=frames.length===timeline.total_frame_count,manifest={format:'rncs.anime-production-sequence-manifest.v0.1',version:'0.1.0-alpha.1',production_id:production.production_id,production_root:production.production_root,timeline_root:timeline.timeline_root,quality,width,height,fps:timeline.master_fps,duration:timeline.total_duration_seconds,cut_count:timeline.cut_count,expected_frame_count:timeline.total_frame_count,rendered_frame_count:frames.length,frames,cut_manifests:cutResults.map(item=>({cut_ref:item.cut_ref,manifest_root:rootHash(item.manifest),sequence_root:item.manifest.sequence_root,evidence_ledger_root:item.ledger.ledger_root,rendered_frame_count:item.manifest.rendered_frame_count})),deterministic:true,status:complete?'complete':'partial',sequence_root:rootHash(frames.map(frame=>({cut_ref:frame.cut_ref,global_frame_number:frame.global_frame_number,state_root:frame.state_root,evidence_root:frame.evidence_root})))};
  const xsheets=buildProductionExposureSheets(production),ledger={format:'rncs.anime-production-evidence-ledger.v0.1',version:'0.1.0-alpha.1',authority:'RNCS',production_id:production.production_id,production_root:production.production_root,timeline_root:timeline.timeline_root,xsheets_root:xsheets.xsheets_root,deterministic:true,cut_count:timeline.cut_count,frame_count:frames.length,expected_frame_count:timeline.total_frame_count,cut_refs:timeline.cut_order,frame_refs:frames.map(frame=>({cut_ref:frame.cut_ref,local_frame_number:frame.local_frame_number,global_frame_number:frame.global_frame_number,frame_id:frame.frame_id,state_root:frame.state_root,evidence_root:frame.evidence_root,provider_receipt_roots:(frame.provider_receipts??[]).map(receipt=>receipt.receipt_root),render_backend:frame.render_receipt.backend})),roots:{sequence_root:manifest.sequence_root,cut_ledger_roots:cutResults.map(item=>item.ledger.ledger_root)},gates:{production_ir:'validated',editorial_timeline:'validated-hard-cut',xsheets:'validated',frame_raster:complete?'complete':'partial',provider_receipts:'recorded',mp4:'encoder-dependent'},boundary:'targeted deterministic reference evidence; not clean-VM, GPU-provider, human-performance, or commercial-quality proof'};ledger.ledger_root=rootHash(ledger);manifest.evidence_ledger_root=ledger.ledger_root;
  const report={format:'rncs.anime-production-render-report.v0.1',production_id:production.production_id,production_root:production.production_root,timeline_root:timeline.timeline_root,manifest_root:rootHash(manifest),frame_sequence_root:manifest.sequence_root,evidence_ledger_root:ledger.ledger_root,backend:'deterministic-native-2d',status:manifest.status,cut_count:timeline.cut_count,rendered_frame_count:frames.length,expected_frame_count:timeline.total_frame_count,boundary:'reference procedural anime renderer; not commercial animation quality'};
  fs.writeFileSync(path.join(outDir,'frames-manifest.json'),JSON.stringify(manifest,null,2));fs.writeFileSync(path.join(outDir,'editorial-timeline.json'),JSON.stringify(timeline,null,2));fs.writeFileSync(path.join(outDir,'xsheets.json'),JSON.stringify(xsheets,null,2));fs.writeFileSync(path.join(outDir,'evidence-ledger.json'),JSON.stringify(ledger,null,2));fs.writeFileSync(path.join(outDir,'render-report.json'),JSON.stringify(report,null,2));return{manifest,xsheets,ledger,report,cut_results:cutResults};
}

export function replayProduction(production,manifest,{quality=manifest?.quality??'preview'}={}){const roots=[];for(const frame of manifest?.frames??[])roots.push(renderCutFrame(production,frame.local_frame_number,{cutRef:frame.cut_ref,width:manifest.width,height:manifest.height,quality}).evidence.state_root);return{valid:rootHash(roots)===rootHash((manifest.frames??[]).map(frame=>frame.state_root)),frame_count:roots.length,cut_count:new Set((manifest?.frames??[]).map(frame=>frame.cut_ref)).size,state_roots:roots,manifest_root:rootHash(manifest),timeline_root:production.editorial_timeline?.timeline_root??null}}
