import crypto from 'node:crypto';
import fs from 'node:fs';
import {clone,rootHash,seal,verifySeal} from './canonical.mjs';

export const VISUAL_PROVIDER_MANIFEST_FORMAT='rncs.anime-visual-provider-manifest.v0.1';
export const VISUAL_MODEL_MANIFEST_FORMAT='rncs.anime-visual-model-manifest.v0.1';
export const CHARACTER_REFERENCE_PACK_FORMAT='rncs.anime-character-reference-pack.v0.1';
export const VISUAL_CONDITION_PACK_FORMAT='rncs.anime-visual-condition-pack.v0.1';
export const VISUAL_CANDIDATE_BRANCH_FORMAT='rncs.anime-visual-candidate-branch.v0.1';
export const VISUAL_QUALITY_REPORT_FORMAT='rncs.anime-visual-quality-report.v0.1';
export const TEMPORAL_CONSISTENCY_REPORT_FORMAT='rncs.anime-temporal-consistency-report.v0.1';
export const SPATIAL_CONSISTENCY_REPORT_FORMAT='rncs.anime-spatial-consistency-report.v0.1';
export const VISUAL_PATCH_RECEIPT_FORMAT='rncs.anime-visual-patch-receipt.v0.1';
export const VISUAL_LEDGER_FORMAT='rncs.anime-visual-evidence-ledger.v0.1';
export const VISUAL_PROVIDER_ROLES=Object.freeze(['condition','keyframe','motion-video','temporal-repair']);
export const VISUAL_CANDIDATE_STATES=Object.freeze(['requested','conditioning','generating','generated','validation-failed','rejected','shortlisted','revision-requested','selected','committed','superseded','blocked']);
export const VISUAL_HUMAN_STATES=Object.freeze(['pending','accepted','rejected','revision-requested']);
export const REFERENCE_VIEWS=Object.freeze(['front','three-quarter','side','full-body','face-closeup']);
export const CONDITION_TYPES=Object.freeze(['pose-skeleton','depth','normal','edge','semantic-mask','camera','layer-order','temporal-context']);
export const VISUAL_TIME='2026-08-06T00:00:00.000Z';

const array=value=>Array.isArray(value)?clone(value):[];
const str=(value,fallback)=>String(value??fallback);
const hashBytes=value=>crypto.createHash('sha256').update(value).digest('hex');
const fail=(code,details)=>{throw Object.assign(new Error(code),{code,details})};
const event=(state,actor='rncs:visual-runtime',reason='state-transition',at=VISUAL_TIME)=>({state,actor,reason,at:String(at)});
const rootDocument=(format,rootField,input={})=>seal({format,version:'0.1.0-alpha.1',...clone(input),source:clone(input.source??{kind:'rncs-visual-runtime',ref:'phase5'}),history:array(input.history).length?array(input.history):[event('created',input.actor??'rncs:visual-runtime',input.reason??'created',input.created_at??VISUAL_TIME)]},rootField);
const validRoot=(value,field)=>Boolean(value&&value.format&&typeof value[field]==='string'&&verifySeal(value,field));
const immutableStatus=value=>VISUAL_HUMAN_STATES.includes(value)?value:'pending';

export function createVisualProviderManifest(input={}){
  const roles=array(input.roles?.length?input.roles:input.role?[input.role]:[]),manifest={format:VISUAL_PROVIDER_MANIFEST_FORMAT,version:'0.1.0-alpha.1',provider_id:str(input.provider_id,'rncs.visual-provider.unknown'),provider_version:str(input.provider_version,'0.0.0'),display_name:str(input.display_name,input.provider_id??'Unnamed Visual Provider'),roles,execution:{kind:str(input.execution?.kind,'external-process'),binary:input.execution?.binary??null,command:array(input.execution?.command),cpu:Boolean(input.execution?.cpu??true),gpu:Boolean(input.execution?.gpu??false),network:Boolean(input.execution?.network??false),platforms:array(input.execution?.platforms??['win32','linux','darwin'])},inputs:array(input.inputs),outputs:array(input.outputs),capabilities:{condition:array(input.capabilities?.condition),keyframe:array(input.capabilities?.keyframe),motion_video:array(input.capabilities?.motion_video),temporal_repair:array(input.capabilities?.temporal_repair)},media:{produces_media:Boolean(input.media?.produces_media),media_types:array(input.media?.media_types),mock:false,fixture:false,...clone(input.media??{})},resolution:clone(input.resolution??{supported:[{width:1280,height:720}]}),frame_rate:clone(input.frame_rate??{supported:[24]}),determinism:clone(input.determinism??{deterministic:false,seed_support:true,declaration:'records model, revision, parameters, seed and input roots'}),character_continuity:clone(input.character_continuity??{identity_root_required:true,reference_pack_required:true,cross_frame:true,cross_shot:true}),temporal_consistency:clone(input.temporal_consistency??{required:true,repair_capable:false}),resources:clone(input.resources??{cpu:'required',gpu:'required',vram_mb:8192,memory_mb:16384,disk_mb:4096}),limits:clone(input.limits??{timeout_ms:3600000,maximum_cost:0,cost_unit:'local-compute'}),failures:array(input.failures??['UNAVAILABLE','MODEL_MISSING','LICENSE_MISSING','INVALID_INPUT','TIMEOUT','OOM','CRASH','OUTPUT_MISSING','OUTPUT_INVALID','TEMPORAL_VALIDATION_FAILED']),evidence:clone(input.evidence??{outputs:['provider-receipt','model-manifest','condition-pack','candidate-branch','frame-manifest'],tool_version:true,model_root:true,input_root:true,output_root:true}),license:clone(input.license??{status:'pending',spdx:null,source:null}),authority:{media_candidate_only:true,episode_intent_write:false,character_identity_write:false,selection_write:false,commit_write:false,...clone(input.authority??{})},quality_boundary:str(input.quality_boundary,'visual generation evidence; commercial Anime quality is not proven')};return seal(manifest,'manifest_root');
}

export function validateVisualProviderManifest(manifest){
  const errors=[],warnings=[];if(manifest?.format!==VISUAL_PROVIDER_MANIFEST_FORMAT)errors.push('VISUAL_PROVIDER_FORMAT_INVALID');if(!manifest?.manifest_root||!verifySeal(manifest,'manifest_root'))errors.push('VISUAL_PROVIDER_ROOT_INVALID');if(!manifest?.provider_id)errors.push('VISUAL_PROVIDER_ID_REQUIRED');if(!(manifest?.roles??[]).every(role=>VISUAL_PROVIDER_ROLES.includes(role)))errors.push('VISUAL_PROVIDER_ROLE_INVALID');if(!manifest?.inputs?.length)errors.push('VISUAL_PROVIDER_INPUTS_REQUIRED');if(!manifest?.outputs?.length)errors.push('VISUAL_PROVIDER_OUTPUTS_REQUIRED');if(manifest?.media?.mock||manifest?.media?.fixture)errors.push('VISUAL_PROVIDER_MOCK_OR_FIXTURE_FORBIDDEN');if(manifest?.authority?.episode_intent_write!==false||manifest?.authority?.character_identity_write!==false||manifest?.authority?.selection_write!==false||manifest?.authority?.commit_write!==false)errors.push('VISUAL_PROVIDER_AUTHORITY_ESCALATION');if(!manifest?.determinism?.declaration)errors.push('VISUAL_PROVIDER_DETERMINISM_DECLARATION_REQUIRED');if(!manifest?.limits?.timeout_ms)errors.push('VISUAL_PROVIDER_TIMEOUT_REQUIRED');if(!manifest?.license)errors.push('VISUAL_PROVIDER_LICENSE_REQUIRED');if(manifest?.execution?.kind==='external-process'&&!manifest.execution.binary)warnings.push('VISUAL_PROVIDER_BINARY_CONFIGURED_AT_RUNTIME');return{valid:errors.length===0,errors,warnings,manifest_root:manifest?.manifest_root??null};
}

export function createVisualModelManifest(input={}){const license=clone(input.license??{status:'missing',spdx:null,source:null});return rootDocument(VISUAL_MODEL_MANIFEST_FORMAT,'model_manifest_root',{model_id:str(input.model_id,'missing-model'),model_revision:str(input.model_revision,'missing-revision'),model_family:str(input.model_family,'diffusion-video'),weight_path:input.weight_path??null,weight_sha256:input.weight_sha256??null,weight_bytes:Number(input.weight_bytes??0),license,license_root:input.license_root??rootHash(license),source:clone(input.source??{kind:'external-model',ref:'not-configured'}),parameters:clone(input.parameters??{}),status:str(input.status,'missing'),runtime:clone(input.runtime??{framework:'diffusers',version:null,device:null}),created_at:str(input.created_at,VISUAL_TIME)});}

export function validateVisualModelManifest(model){const errors=[],warnings=[];if(model?.format!==VISUAL_MODEL_MANIFEST_FORMAT)errors.push('VISUAL_MODEL_FORMAT_INVALID');if(!validRoot(model,'model_manifest_root'))errors.push('VISUAL_MODEL_ROOT_INVALID');if(!model?.model_id||model.model_id==='missing-model')errors.push('VISUAL_MODEL_ID_MISSING');if(!model?.model_revision||model.model_revision==='missing-revision')errors.push('VISUAL_MODEL_REVISION_MISSING');if(!model?.weight_sha256)errors.push('VISUAL_MODEL_WEIGHT_HASH_MISSING');if(!(Number(model?.weight_bytes)>0))errors.push('VISUAL_MODEL_FILE_MISSING');if(!model?.license?.spdx||model.license.status==='missing')errors.push('VISUAL_MODEL_LICENSE_MISSING');if(model?.status==='missing')warnings.push('VISUAL_MODEL_NOT_AVAILABLE');return{valid:errors.length===0,errors,warnings,model_manifest_root:model?.model_manifest_root??null};}

export function createCharacterReferencePack(input={}){const references=array(input.references),pack=rootDocument(CHARACTER_REFERENCE_PACK_FORMAT,'reference_pack_root',{character_id:str(input.character_id,'unknown-character'),identity_root:input.identity_root??null,genome_root:input.genome_root??null,appearance_root:input.appearance_root??null,lineage_root:input.lineage_root??null,references,reference_views:REFERENCE_VIEWS.map(view=>references.find(item=>item.view_id===view)?.view_id??null),hair_structure:clone(input.hair_structure??{}),costume_structure:clone(input.costume_structure??{}),fixed_palette:clone(input.fixed_palette??{}),facial_features:clone(input.facial_features??{}),materials:clone(input.materials??{}),expressions:clone(input.expressions??{neutral:null,target:null}),forbidden_variation:array(input.forbidden_variation),variable_states:array(input.variable_states),identity_anchors:array(input.identity_anchors),source:clone(input.source??{kind:'character-genome-export',ref:input.genome_root??'missing'}),license:clone(input.license??{status:'pending',spdx:null,source:null}),model_parameters:clone(input.model_parameters??{}),human_character_acceptance:immutableStatus(input.human_character_acceptance),status:str(input.status,'pending'),created_at:str(input.created_at,VISUAL_TIME)});return pack;}

export function validateCharacterReferencePack(pack,{requireComplete=false}={}){const errors=[],warnings=[];if(pack?.format!==CHARACTER_REFERENCE_PACK_FORMAT)errors.push('REFERENCE_PACK_FORMAT_INVALID');if(!validRoot(pack,'reference_pack_root'))errors.push('REFERENCE_PACK_ROOT_INVALID');for(const field of ['character_id','identity_root','genome_root','appearance_root','lineage_root'])if(!pack?.[field])errors.push(`REFERENCE_PACK_${field.toUpperCase()}_REQUIRED`);const views=new Set((pack?.references??[]).map(item=>item.view_id));for(const view of REFERENCE_VIEWS)if(!views.has(view))errors.push(`REFERENCE_VIEW_MISSING:${view}`);for(const ref of pack?.references??[]){if(!ref.path)errors.push(`REFERENCE_PATH_MISSING:${ref.view_id}`);if(ref.media_type==='image/svg+xml')errors.push(`REFERENCE_VECTOR_ONLY_FORBIDDEN:${ref.view_id}`);if(ref.placeholder===true)errors.push(`REFERENCE_PLACEHOLDER_FORBIDDEN:${ref.view_id}`)}if(pack?.human_character_acceptance!=='accepted')warnings.push('HUMAN_CHARACTER_ACCEPTANCE_PENDING');if(requireComplete&&errors.length===0&&pack.human_character_acceptance!=='accepted')errors.push('REFERENCE_PACK_HUMAN_ACCEPTANCE_REQUIRED');return{valid:errors.length===0,errors,warnings,reference_pack_root:pack?.reference_pack_root??null};}

export function createVisualConditionPack(input={}){const conditions=array(input.conditions),pack=rootDocument(VISUAL_CONDITION_PACK_FORMAT,'condition_pack_root',{episode_intent_root:input.episode_intent_root??null,shot_intent_root:input.shot_intent_root??null,character_identity_root:input.character_identity_root??null,reference_pack_root:input.reference_pack_root??null,conditions,condition_types:CONDITION_TYPES.map(type=>conditions.find(item=>item.type===type)?.type??null),camera:clone(input.camera??{}),layers:clone(input.layers??['background','midground','character','foreground','lighting']),temporal_context:clone(input.temporal_context??{}),status:str(input.status,'pending'),created_at:str(input.created_at,VISUAL_TIME)});return pack;}

export function validateVisualConditionPack(pack,{requireComplete=false}={}){const errors=[],warnings=[];if(pack?.format!==VISUAL_CONDITION_PACK_FORMAT)errors.push('CONDITION_PACK_FORMAT_INVALID');if(!validRoot(pack,'condition_pack_root'))errors.push('CONDITION_PACK_ROOT_INVALID');for(const field of ['episode_intent_root','shot_intent_root','character_identity_root','reference_pack_root'])if(!pack?.[field])errors.push(`CONDITION_PACK_${field.toUpperCase()}_REQUIRED`);const conditions=new Map((pack?.conditions??[]).map(item=>[item.type,item]));for(const type of CONDITION_TYPES){const item=conditions.get(type);if(!item)errors.push(`CONDITION_MISSING:${type}`);else{if(!item.root)errors.push(`CONDITION_ROOT_MISSING:${type}`);if(item.status==='missing')warnings.push(`CONDITION_UNAVAILABLE:${type}`)}}if(requireComplete&&pack?.status!=='complete')errors.push('CONDITION_PACK_NOT_COMPLETE');return{valid:errors.length===0,errors,warnings,condition_pack_root:pack?.condition_pack_root??null};}

export function createVisualCandidateBranch(input={}){const manifest=input.provider_manifest;if(!manifest)fail('VISUAL_CANDIDATE_PROVIDER_MANIFEST_REQUIRED');const candidate=rootDocument(VISUAL_CANDIDATE_BRANCH_FORMAT,'candidate_branch_root',{candidate_id:str(input.candidate_id,`visual-candidate:${rootHash({episode_intent_root:input.episode_intent_root,shot_intent_root:input.shot_intent_root,provider_id:input.provider_id??manifest.provider_id,seed:input.seed})}`),candidate_status:str(input.candidate_status,'requested'),episode_intent_root:input.episode_intent_root??null,shot_intent_root:input.shot_intent_root??null,character_identity_root:input.character_identity_root??null,character_reference_pack_root:input.character_reference_pack_root??null,condition_pack_root:input.condition_pack_root??null,provider_id:input.provider_id??manifest.provider_id,provider_version:input.provider_version??manifest.provider_version,provider_manifest_root:manifest.manifest_root,model_id:input.model_id??null,model_revision:input.model_revision??null,model_license:clone(input.model_license??{status:'missing'}),model_license_root:input.model_license_root??null,model_manifest_root:input.model_manifest_root??null,seed:input.seed??null,sampler:input.sampler??null,scheduler:input.scheduler??null,reconstruction_parameters:clone(input.reconstruction_parameters??{}),input_reference_roots:clone(input.input_reference_roots??{}),output_frame_root:input.output_frame_root??null,output_video_root:input.output_video_root??null,output_media:clone(input.output_media??{produces_media:false,mock:false,fixture:false}),environment:clone(input.environment??{}),gpu:clone(input.gpu??{status:'unknown',name:null,vram_mb:null}),timing:clone(input.timing??{started_at:null,ended_at:null,elapsed_ms:null}),errors:array(input.errors),identity_continuity_root:input.identity_continuity_root??null,temporal_stability_root:input.temporal_stability_root??null,spatial_consistency_root:input.spatial_consistency_root??null,continuity_report:clone(input.continuity_report??null),quality_report:clone(input.quality_report??null),human_visual_acceptance:immutableStatus(input.human_visual_acceptance),selection_receipt_root:null,commit_receipt_root:null,authority:{media_candidate_only:true,episode_intent_write:false,character_identity_write:false,automatic_commit:false,commit_requires_authorized_selection:true},state_history:array(input.state_history).length?array(input.state_history):[event('requested','rncs:visual-runtime','candidate-requested',input.created_at??VISUAL_TIME)],created_at:str(input.created_at,VISUAL_TIME)});if(!VISUAL_CANDIDATE_STATES.includes(candidate.candidate_status))fail(`VISUAL_CANDIDATE_STATE_INVALID:${candidate.candidate_status}`);return candidate;}

const transitions={requested:['conditioning','blocked','rejected'],conditioning:['generating','blocked','revision-requested'],generating:['generated','blocked','rejected'],generated:['shortlisted','validation-failed','rejected','blocked'],['validation-failed']:['revision-requested','rejected','blocked'],shortlisted:['selected','revision-requested','rejected','blocked'],['revision-requested']:['conditioning','generating','blocked'],selected:['committed','superseded','blocked'],committed:['superseded'],rejected:[],blocked:[],superseded:[]};
export function transitionVisualCandidate(candidate,next,{actor='rncs:visual-runtime',reason='state-transition',at=VISUAL_TIME,updates={}}={}){if(!VISUAL_CANDIDATE_STATES.includes(next))fail(`VISUAL_CANDIDATE_STATE_INVALID:${next}`);if(!transitions[candidate?.candidate_status]?.includes(next))fail(`VISUAL_CANDIDATE_TRANSITION_FORBIDDEN:${candidate?.candidate_status}->${next}`);const nextCandidate={...clone(candidate),...clone(updates),candidate_status:next,state_history:[...(candidate.state_history??[]),event(next,actor,reason,at)],updated_at:String(at)};return seal(nextCandidate,'candidate_branch_root');}

export function validateVisualCandidateBranch(candidate,{requireGeneratedMedia=false}={}){const errors=[],warnings=[];if(candidate?.format!==VISUAL_CANDIDATE_BRANCH_FORMAT)errors.push('VISUAL_CANDIDATE_FORMAT_INVALID');if(!validRoot(candidate,'candidate_branch_root'))errors.push('VISUAL_CANDIDATE_ROOT_INVALID');if(!VISUAL_CANDIDATE_STATES.includes(candidate?.candidate_status))errors.push('VISUAL_CANDIDATE_STATE_INVALID');for(const field of ['episode_intent_root','shot_intent_root','character_identity_root','character_reference_pack_root','condition_pack_root','provider_manifest_root','model_license_root'])if(!candidate?.[field])errors.push(`VISUAL_CANDIDATE_${field.toUpperCase()}_REQUIRED`);if(candidate?.authority?.episode_intent_write!==false||candidate?.authority?.character_identity_write!==false||candidate?.authority?.automatic_commit!==false)errors.push('VISUAL_CANDIDATE_AUTHORITY_ESCALATION');if(candidate?.human_visual_acceptance!=='accepted')warnings.push('HUMAN_VISUAL_ACCEPTANCE_PENDING');if(candidate?.model_license?.status==='missing')errors.push('VISUAL_CANDIDATE_MODEL_LICENSE_MISSING');if(requireGeneratedMedia&&(!candidate?.output_frame_root||candidate.output_media?.produces_media!==true||candidate.output_media?.mock||candidate.output_media?.fixture))errors.push('VISUAL_CANDIDATE_REAL_MEDIA_REQUIRED');if(requireGeneratedMedia&&!candidate?.model_manifest_root)errors.push('VISUAL_CANDIDATE_MODEL_MANIFEST_REQUIRED');return{valid:errors.length===0,errors,warnings,candidate_branch_root:candidate?.candidate_branch_root??null};}

export function createVisualQualityReport(input={}){const rules=array(input.rules).map(rule=>({...rule,pass:Boolean(rule.pass)})),report={format:VISUAL_QUALITY_REPORT_FORMAT,version:'0.1.0-alpha.1',candidate_branch_root:input.candidate_branch_root??null,metrics:clone(input.metrics??{}),rules,representative_frames:array(input.representative_frames),failed_intervals:array(input.failed_intervals),identity_checks:clone(input.identity_checks??{}),temporal_checks:clone(input.temporal_checks??{}),spatial_checks:clone(input.spatial_checks??{}),motion_checks:clone(input.motion_checks??{}),human_review_items:array(input.human_review_items),automatic_score:{value:input.automatic_score??null,meaning:'triage-only',cannot_authorize_selection:true,cannot_authorize_commit:true},status:rules.length&&rules.every(rule=>rule.pass)?'pass':'fail',boundary:'image metrics are supporting evidence, not a single truth and not human aesthetic acceptance',created_at:String(input.created_at??VISUAL_TIME),quality_report_root:''};return seal(report,'quality_report_root');}

export function analyzeVisualFrameSequence({frames=[],expectedFrameCount=null,rootDir=null,createdAt=VISUAL_TIME}={}){const rows=array(frames),errors=[],duplicates=[],blankFrames=[];for(let index=0;index<rows.length;index++){const item=rows[index],absolute=item.absolute_path??(rootDir&&item.filename?`${rootDir}/${item.filename}`:null);if(absolute&&!fs.existsSync(absolute)){errors.push(`FRAME_MISSING:${item.filename??index}`);continue}const bytes=absolute?fs.readFileSync(absolute):null,sha=item.sha256??(bytes?hashBytes(bytes):null);if(!sha)errors.push(`FRAME_HASH_MISSING:${index}`);if(bytes&&bytes.length<64)blankFrames.push(index);if(index>0&&sha&&sha===rows[index-1].sha256)duplicates.push(index)}const complete=expectedFrameCount==null||rows.length===Number(expectedFrameCount),duplicateRatio=rows.length?duplicates.length/rows.length:1,report={format:TEMPORAL_CONSISTENCY_REPORT_FORMAT,version:'0.1.0-alpha.1',expected_frame_count:expectedFrameCount,actual_frame_count:rows.length,complete,errors,blank_frames:blankFrames,consecutive_duplicate_frames:duplicates,duplicate_ratio:duplicateRatio,high_frequency_flicker_intervals:array([]),motion_anomaly_intervals:array([]),status:errors.length||!complete||blankFrames.length||duplicateRatio>.85?'fail':'pass',created_at:String(createdAt),temporal_stability_root:''};return seal(report,'temporal_stability_root');}

export function createSpatialConsistencyReport(input={}){return seal({format:SPATIAL_CONSISTENCY_REPORT_FORMAT,version:'0.1.0-alpha.1',candidate_branch_root:input.candidate_branch_root??null,checks:clone(input.checks??{}),occlusion_intervals:array(input.occlusion_intervals),camera_consistency:clone(input.camera_consistency??{}),layer_consistency:clone(input.layer_consistency??{}),contact_consistency:clone(input.contact_consistency??{}),status:input.status??'blocked',human_review_items:array(input.human_review_items),spatial_consistency_root:''},'spatial_consistency_root');}

export function createVisualSelectionReceipt({candidate,actorId='test:visual-director',mode='test-selection',authorized=false,reason='visual candidate selection',humanVisualAcceptance='pending',at=VISUAL_TIME}={}){if(!authorized)fail('VISUAL_SELECTION_AUTHORIZATION_REQUIRED');return seal({format:'rncs.anime-visual-selection-receipt.v0.1',version:'0.1.0-alpha.1',candidate_branch_root:candidate?.candidate_branch_root??null,episode_intent_root:candidate?.episode_intent_root??null,character_identity_root:candidate?.character_identity_root??null,actor_id:actorId,mode,authorized:true,reason,human_visual_acceptance:immutableStatus(humanVisualAcceptance),authority:'selection receipt only; Episode authority remains external RNCS commit boundary',created_at:String(at),selection_receipt_root:''},'selection_receipt_root');}

export function selectVisualCandidate(candidate,receipt){if(candidate?.candidate_status!=='shortlisted')fail('VISUAL_CANDIDATE_SHORTLIST_REQUIRED');if(!validRoot(receipt,'selection_receipt_root')||receipt.candidate_branch_root!==candidate.candidate_branch_root)fail('VISUAL_SELECTION_RECEIPT_INVALID');return transitionVisualCandidate(candidate,'selected',{actor:receipt.actor_id,reason:receipt.reason,updates:{selection_receipt_root:receipt.selection_receipt_root,human_visual_acceptance:receipt.human_visual_acceptance}});}

export function createVisualCommitPreview({candidate,receipt,currentMediaRoot=null}={}){if(!receipt?.selection_receipt_root)fail('VISUAL_COMMIT_SELECTION_REQUIRED');return seal({format:'rncs.anime-visual-commit-preview.v0.1',candidate_branch_root:candidate.candidate_branch_root,episode_intent_root:candidate.episode_intent_root,character_identity_root:candidate.character_identity_root,previous_media_root:currentMediaRoot,impact:{episode_intent_changed:false,character_identity_changed:false,affected_candidate_branch:candidate.candidate_id},human_visual_acceptance:receipt.human_visual_acceptance,commit_requires_explicit_authorized_selection:true,preview_root:''},'preview_root');}

export function commitVisualCandidate({candidate,receipt,currentMediaRoot=null}={}){if(candidate?.candidate_status!=='selected')fail('VISUAL_CANDIDATE_SELECTED_REQUIRED');if(!validRoot(receipt,'selection_receipt_root')||receipt.selection_receipt_root!==candidate.selection_receipt_root)fail('VISUAL_COMMIT_RECEIPT_INVALID');const commitReceipt=seal({format:'rncs.anime-visual-commit-receipt.v0.1',version:'0.1.0-alpha.1',candidate_branch_root:candidate.candidate_branch_root,selection_receipt_root:receipt.selection_receipt_root,episode_intent_root:candidate.episode_intent_root,character_identity_root:candidate.character_identity_root,previous_media_root:currentMediaRoot,human_visual_acceptance:receipt.human_visual_acceptance,authority:'explicit visual selection receipt',commit_receipt_root:''},'commit_receipt_root');return{candidate:transitionVisualCandidate(candidate,'committed',{actor:receipt.actor_id,reason:'authorized-visual-commit',updates:{commit_receipt_root:commitReceipt.commit_receipt_root}}),commit_receipt:commitReceipt,preview:createVisualCommitPreview({candidate,receipt,currentMediaRoot})};}

export function createVisualPatchReceipt({beforeCandidate,afterCandidate,interval,region,reason,episodeIntentRoot,characterIdentityRoot,unaffectedFrameRoots=[],expandedInterval=null,createdAt=VISUAL_TIME}={}){if(!beforeCandidate?.candidate_branch_root||!afterCandidate?.candidate_branch_root)fail('VISUAL_PATCH_CANDIDATE_REQUIRED');if(beforeCandidate.episode_intent_root!==episodeIntentRoot||afterCandidate.episode_intent_root!==episodeIntentRoot)fail('VISUAL_PATCH_EPISODE_ROOT_MISMATCH');if(beforeCandidate.character_identity_root!==characterIdentityRoot||afterCandidate.character_identity_root!==characterIdentityRoot)fail('VISUAL_PATCH_IDENTITY_ROOT_MISMATCH');return seal({format:VISUAL_PATCH_RECEIPT_FORMAT,version:'0.1.0-alpha.1',patch_id:`visual-patch:${rootHash({before:beforeCandidate.candidate_branch_root,after:afterCandidate.candidate_branch_root,interval,region})}`,before_candidate_branch_root:beforeCandidate.candidate_branch_root,after_candidate_branch_root:afterCandidate.candidate_branch_root,episode_intent_root:episodeIntentRoot,character_identity_root:characterIdentityRoot,interval:clone(interval),expanded_interval:clone(expandedInterval),region:clone(region),reason,unaffected_frame_roots:array(unaffectedFrameRoots),seam_checks:{start_match:Boolean(interval?.start_frame!=null),end_match:Boolean(interval?.end_frame!=null)},status:'pending-human-review',rollback_allowed:true,created_at:String(createdAt),patch_root:''},'patch_root');}

export function validateVisualPatchImpact({beforeCandidate,afterCandidate,patch,unaffectedFrameRoots=[]}={}){const errors=[];if(patch?.episode_intent_root!==beforeCandidate?.episode_intent_root||patch?.episode_intent_root!==afterCandidate?.episode_intent_root)errors.push('VISUAL_PATCH_EPISODE_ROOT_CHANGED');if(patch?.character_identity_root!==beforeCandidate?.character_identity_root||patch?.character_identity_root!==afterCandidate?.character_identity_root)errors.push('VISUAL_PATCH_IDENTITY_ROOT_CHANGED');if(rootHash(unaffectedFrameRoots)!==rootHash(patch?.unaffected_frame_roots??[]))errors.push('VISUAL_PATCH_UNAFFECTED_ROOTS_CHANGED');return{valid:errors.length===0,errors,patch_root:patch?.patch_root??null};}

export function createVisualEvidenceLedger(input={}){const roots={episode_intent_root:input.episode_intent_root??null,shot_intent_root:input.shot_intent_root??null,character_genome_root:input.character_genome_root??null,character_reference_pack_root:input.character_reference_pack_root??null,condition_pack_root:input.condition_pack_root??null,provider_manifest_root:input.provider_manifest_root??null,model_manifest_root:input.model_manifest_root??null,model_license_root:input.model_license_root??null,input_reference_roots:clone(input.input_reference_roots??{}),candidate_branch_root:input.candidate_branch_root??null,generated_frame_root:input.generated_frame_root??null,generated_clip_root:input.generated_clip_root??null,identity_continuity_root:input.identity_continuity_root??null,temporal_stability_root:input.temporal_stability_root??null,spatial_consistency_root:input.spatial_consistency_root??null,patch_root:input.patch_root??null,final_sequence_root:input.final_sequence_root??null,audio_root:input.audio_root??null,mp4_sha256:input.mp4_sha256??null,ffprobe_root:input.ffprobe_root??null,ab_comparison_root:input.ab_comparison_root??null,human_visual_acceptance:immutableStatus(input.human_visual_acceptance),environment_root:input.environment_root??null,source_package_root:input.source_package_root??null};const ledger={format:VISUAL_LEDGER_FORMAT,version:'0.1.0-alpha.1',status:str(input.status,'blocked'),roots,ledger_internal_root:'',ledger_file_sha256:input.ledger_file_sha256??null,evidence_bundle_root:input.evidence_bundle_root??null,artifact_sha256:input.artifact_sha256??null,source_package_sha256:input.source_package_sha256??null,media_sha256:input.media_sha256??null,gates:clone(input.gates??{}),boundary:'visual generation, temporal consistency, rights and human acceptance remain separate gates'};const internal=seal(ledger,'ledger_internal_root');return internal;}

export function setHumanVisualAcceptance(candidate,{status,reviewerId,reviewerMode='human',reason,at=VISUAL_TIME}={}){const next=immutableStatus(status);if(next!=='pending'&&(!reviewerId||reviewerMode!=='human'))fail('HUMAN_VISUAL_ACCEPTANCE_REQUIRES_HUMAN_RECEIPT');return seal({...clone(candidate),human_visual_acceptance:next,human_visual_receipt:next==='pending'?null:{reviewer_id:reviewerId,mode:reviewerMode,reason,at},candidate_branch_root:''},'candidate_branch_root');}
