// World Runtime Export Engine
import type { WorldSimulationResult } from "./worldSimulationCore";
import type { WorldRuntimeExportTargetId } from "@/constants/sequence-world/simulation/worldRuntimeExportTargets";

export interface WorldRuntimePackage {
  metadata: {
    version: string;
    exportedAt: string;
    source: "Aether Sequence World Engine v0.2";
    subjectMode: string;
    privacyNotes: string[];
  };
  worldState: WorldSimulationResult["worldState"];
  zones: WorldSimulationResult["activeZones"];
  npcs: WorldSimulationResult["activeNpcs"];
  events: WorldSimulationResult["activeEvents"];
  causalChain: WorldSimulationResult["causalChain"];
  resources: WorldSimulationResult["resourceFlow"];
  snapshots: WorldSimulationResult["snapshots"];
  safetyNotes: string[];
}

function buildPackage(sim: WorldSimulationResult, subjectMode: string, privacyNotes: string[]): WorldRuntimePackage {
  return {
    metadata: {
      version: "0.2.0",
      exportedAt: new Date().toISOString(),
      source: "Aether Sequence World Engine v0.2",
      subjectMode,
      privacyNotes,
    },
    worldState: sim.worldState,
    zones: sim.activeZones,
    npcs: sim.activeNpcs,
    events: sim.activeEvents,
    causalChain: sim.causalChain,
    resources: sim.resourceFlow,
    snapshots: sim.snapshots,
    safetyNotes: sim.safetyNotes,
  };
}

function toSnake(k: string) { return k.replace(/[A-Z]/g, m => "_" + m.toLowerCase()).replace(/^_/, ""); }
function deep<T>(value: T, fn: (k: string) => string): T {
  if (Array.isArray(value)) return value.map(v => deep(v, fn)) as any;
  if (value && typeof value === "object") {
    const o: any = {};
    for (const [k, v] of Object.entries(value)) o[fn(k)] = deep(v as any, fn);
    return o;
  }
  return value;
}

export function exportRuntime(sim: WorldSimulationResult, target: WorldRuntimeExportTargetId, opts?: { subjectMode?: string; isFull60?: boolean }): { ext: string; mime: string; content: string } {
  const subjectMode = opts?.subjectMode ?? "DEMO";
  const privacy = opts?.isFull60 ? ["Full60 数据：导出前请确认隐私边界，避免上传至公共服务。"] : ["仅本地保存的模拟数据。"];
  const pkg = buildPackage(sim, subjectMode, privacy);

  switch (target) {
    case "GENERIC_JSON":
      return { ext: "json", mime: "application/json", content: JSON.stringify(pkg, null, 2) };
    case "GODOT_RUNTIME_JSON":
      return { ext: "json", mime: "application/json", content: JSON.stringify(deep(pkg, toSnake), null, 2) };
    case "UNITY_RUNTIME_JSON":
      return { ext: "json", mime: "application/json", content: JSON.stringify(pkg, null, 2) };
    case "GODOT_GDSCRIPT_SKELETON":
      return { ext: "gd", mime: "text/plain", content: godotSkeleton(pkg) };
    case "UNITY_CSHARP_SKELETON":
      return { ext: "cs", mime: "text/plain", content: unitySkeleton(pkg) };
    case "NARRATIVE_BIBLE":
      return { ext: "md", mime: "text/markdown", content: narrativeBible(pkg) };
    case "WORLD_KNOWLEDGE_PACK":
      return { ext: "json", mime: "application/json", content: JSON.stringify({
        knowledgeType: "FICTIONAL_LORE",
        worldId: pkg.worldState.worldId,
        title: pkg.worldState.worldName,
        entries: [
          { type: "WORLD_STATE", summary: pkg.worldState.summary },
          ...pkg.zones.map(z => ({ type: "ZONE", id: z.zoneId, name: z.name, stability: z.stability })),
          ...pkg.npcs.map(n => ({ type: "NPC", id: n.npcId, name: n.name, archetype: n.archetype })),
          ...pkg.events.map(e => ({ type: "EVENT", id: e.id, title: e.title, eventType: e.eventType })),
        ],
        metadata: pkg.metadata,
        safetyNotes: pkg.safetyNotes,
      }, null, 2) };
    case "PROMPT_FORGE_PACK":
      return { ext: "md", mime: "text/markdown", content: promptForgePack(pkg) };
  }
}

function godotSkeleton(pkg: WorldRuntimePackage): string {
  return [
    `# Auto-generated by Aether Sequence World Engine v${pkg.metadata.version}`,
    `# Source mode: ${pkg.metadata.subjectMode}`,
    `extends Node`,
    ``,
    `var world_phase := "${pkg.worldState.phase}"`,
    `var tick := ${pkg.worldState.tick}`,
    `var stability := ${pkg.worldState.stability.toFixed(2)}`,
    `var event_pressure := ${pkg.worldState.eventPressure.toFixed(2)}`,
    ``,
    `func load_runtime() -> Dictionary:`,
    `    var f := FileAccess.open("res://world_runtime.json", FileAccess.READ)`,
    `    if f == null: return {}`,
    `    return JSON.parse_string(f.get_as_text())`,
    ``,
    `# NOTE: Aether SDK does NOT replace Godot rendering or physics.`,
  ].join("\n");
}

function unitySkeleton(pkg: WorldRuntimePackage): string {
  return [
    `// Auto-generated by Aether Sequence World Engine v${pkg.metadata.version}`,
    `// Source mode: ${pkg.metadata.subjectMode}`,
    `using System.Collections.Generic;`,
    `using UnityEngine;`,
    ``,
    `[System.Serializable]`,
    `public class AetherWorldRuntime : MonoBehaviour {`,
    `    public string WorldPhase = "${pkg.worldState.phase}";`,
    `    public int Tick = ${pkg.worldState.tick};`,
    `    public float Stability = ${pkg.worldState.stability.toFixed(2)}f;`,
    `    public float EventPressure = ${pkg.worldState.eventPressure.toFixed(2)}f;`,
    ``,
    `    // TODO: load world_runtime.json via Resources.Load<TextAsset>`,
    `}`,
  ].join("\n");
}

function narrativeBible(pkg: WorldRuntimePackage): string {
  const lines = [
    `# ${pkg.worldState.worldName} · 世界剧情圣经`,
    ``, `> 由 Aether Sequence World Engine v${pkg.metadata.version} 生成 · ${pkg.metadata.exportedAt}`,
    ``, `## 当前世界状态`, `- 相位：${pkg.worldState.phase}`,
    `- Tick：${pkg.worldState.tick}`, `- 摘要：${pkg.worldState.summary}`,
    ``, `## 区域`,
    ...pkg.zones.map(z => `- **${z.name}** (${z.zoneType})：稳定 ${z.stability.toFixed(2)}，事件压力 ${z.eventPressure.toFixed(2)}`),
    ``, `## NPC`,
    ...pkg.npcs.map(n => `- **${n.name}** · ${n.archetype}：目标「${n.currentGoal}」，信任 ${n.trust.toFixed(2)}`),
    ``, `## 事件`,
    ...pkg.events.slice(-10).map(e => `- ${e.title} (${e.eventType})`),
    ``, `## 安全说明`,
    ...pkg.safetyNotes.map(s => `> ${s}`),
  ];
  return lines.join("\n");
}

function promptForgePack(pkg: WorldRuntimePackage): string {
  return [
    `# Prompt Forge Pack · ${pkg.worldState.worldName}`,
    ``, `## System`, `你是一位世界生成助手。请基于以下世界状态推进剧情：`,
    ``, `## World State`, "```json", JSON.stringify(pkg.worldState, null, 2), "```",
    ``, `## Next-step prompts`,
    `- 推进 1 个 tick 并描述 NPC 的反应。`,
    `- 选择一个 NPC 写一段对话。`,
    `- 给出 3 个可能的下一步事件。`,
    ``, `## Safety`, ...pkg.safetyNotes.map(s => `> ${s}`),
  ].join("\n");
}
