export const AUTONOMOUS_EVENT_TYPES = [
  "TRADE_DISPUTE","FACTION_NEGOTIATION","SECRET_MEETING","RESOURCE_SHORTAGE",
  "INSTITUTION_REFORM","BELIEF_CONFLICT","NPC_MIGRATION","MEMORY_DISCOVERY",
  "RULE_CHALLENGE","CIVILIZATION_RITUAL",
] as const;
export type AutonomousEventType = typeof AUTONOMOUS_EVENT_TYPES[number];

export const AUTONOMOUS_EVENT_LABELS: Record<AutonomousEventType, string> = {
  TRADE_DISPUTE: "贸易纠纷",
  FACTION_NEGOTIATION: "阵营谈判",
  SECRET_MEETING: "秘密会议",
  RESOURCE_SHORTAGE: "资源短缺",
  INSTITUTION_REFORM: "制度改革",
  BELIEF_CONFLICT: "信仰冲突",
  NPC_MIGRATION: "NPC迁移",
  MEMORY_DISCOVERY: "记忆发现",
  RULE_CHALLENGE: "规则挑战",
  CIVILIZATION_RITUAL: "文明仪式",
};

export const MAX_AUTONOMOUS_EVENTS_PER_TICK = 2;
