export const CIVILIZATION_PHASES = [
  "PRIMAL_SEED","TRIBAL_NETWORK","CITY_STATE","GUILD_SOCIETY","RULED_CIVILIZATION",
  "FRACTURED_ERA","STAR_ARCHIVE_CIVILIZATION","TERMINAL_CIVILIZATION","RESEED_CIVILIZATION",
] as const;
export type CivilizationPhase = typeof CIVILIZATION_PHASES[number];

export const CIVILIZATION_PHASE_LABELS: Record<CivilizationPhase, string> = {
  PRIMAL_SEED: "原初种子",
  TRIBAL_NETWORK: "部落网络",
  CITY_STATE: "城邦",
  GUILD_SOCIETY: "公会社会",
  RULED_CIVILIZATION: "规则文明",
  FRACTURED_ERA: "裂变时代",
  STAR_ARCHIVE_CIVILIZATION: "星海档案文明",
  TERMINAL_CIVILIZATION: "终局文明",
  RESEED_CIVILIZATION: "再种子文明",
};
