import {clone,seal} from '../../reality-asset-genesis-fabric/src/canonical.mjs';

const RULES=[
  {match:/^(appearance_loadout\.)?hair_color$|^hair\.color$/,rebuild:['textures/','native-2d/','2.5d/','3d-assisted-2d/','turntable/','expressions/','model-sheet.svg','front-view.svg','side-view.svg','back-view.svg','expression-sheet.svg','mouth-chart.svg','eye-state-sheet.svg','portrait-preview.png','anime-projection.png'],preserve:['body.glb','face.glb','hair.glb','costume.glb','rig.json','collision-profile.json','character.glb','character-lod0.glb','character-lod1.glb','character-lod2.glb'],scope:'hair-material'},
  {match:/^(appearance_loadout\.)?hair_family$|^hair\.family$/,rebuild:['hair.glb','hair-physics.json','hair-collision.json','native-2d/hair.svg','character.glb','character-lod0.glb','character-lod1.glb','character-lod2.glb','portrait-preview.png','anime-projection.png'],preserve:['body.glb','face.glb','identity_signature.json','rig.json','voice-binding.json'],scope:'hair-geometry'},
  {match:/^(appearance_loadout\.)?costume_family$|^costume\./,rebuild:['costume.glb','costume-materials.json','cloth-profile.json','garment-collision.json','native-2d/costume.svg','character.glb','character-lod0.glb','character-lod1.glb','character-lod2.glb','portrait-preview.png','anime-projection.png'],preserve:['body.glb','face.glb','identity_signature.json','rig.json','voice-binding.json'],scope:'costume'},
  {match:/^(appearance_loadout\.)?palette_family$|^palette\./,rebuild:['textures/','native-2d/','2.5d/','3d-assisted-2d/','turntable/','expressions/','model-sheet.svg','front-view.svg','side-view.svg','back-view.svg','expression-sheet.svg','mouth-chart.svg','eye-state-sheet.svg','portrait-preview.png','anime-projection.png'],preserve:['body.glb','face.glb','hair.glb','costume.glb','rig.json','collision-profile.json','character.glb','character-lod0.glb','character-lod1.glb','character-lod2.glb'],scope:'palette'},
  {match:/^face\.|^face_genome\./,rebuild:['face.glb','character.glb','character-lod0.glb','character-lod1.glb','character-lod2.glb','face-normals.json','portrait-preview.png','expression-sheet.svg','mouth-chart.svg','native-2d/face.svg','anime-projection.png'],preserve:['character_id','voice-binding.json','body.glb','rig.json','unrelated-costume-assets'],scope:'face-identity'},
  {match:/^body\.|^body_genome\./,rebuild:['body.glb','character.glb','character-lod0.glb','character-lod1.glb','character-lod2.glb','rig.json','collision-profile.json','physics-profile.json','retarget-profile.json','native-2d/body.svg','portrait-preview.png','anime-projection.png'],preserve:['character_id','voice-binding.json','face-identity-fields'],scope:'body-morphology'},
  {match:/^state_overlays\.|^expression$/,rebuild:['expression-state.json','portrait-preview.png','anime-projection.png'],preserve:['identity_signature.json','body.glb','face.glb','rig.json','character-lod0.glb'],scope:'state-overlay'},
];

export function analyzeCharacterGenomeImpact(genome,{change_path,from=null,to=null}={}){
  const rule=RULES.find(item=>item.match.test(String(change_path??'')));
  const result=rule??{rebuild:['character.glb','character-lod0.glb','character-lod1.glb','character-lod2.glb','cross-media-projections'],preserve:['character_id','voice-binding.json'],scope:'full-character'};
  return seal({format:'rncs.character-rebuild-impact.v0.1',character_id:genome.character_id,genome_root:genome.genome_root,change:{path:String(change_path??''),from:clone(from),to:clone(to)},scope:result.scope,rebuild:[...result.rebuild],preserve:[...result.preserve],identity_may_change:result.scope==='face-identity'||result.scope==='body-morphology',full_rebuild:result.scope==='full-character',impact_root:''},'impact_root');
}

export function createIncrementalRebuildReceipt({beforeGenome,afterGenome,impact,beforeRoots={},afterRoots={},durationMs=0,cacheHits=0,cacheMisses=0}){
  const metadata=['genome.json','phenotype.json','provider-receipt.json','continuity-report.json','vsr-character-profile.json','rsr-character-body-profile.json'],expected=[...impact.rebuild,...metadata],changed=Object.keys(afterRoots).filter(key=>beforeRoots[key]!==afterRoots[key]),unexpected=changed.filter(key=>!expected.some(pattern=>key===pattern||key.startsWith(String(pattern).replace(/\/$/,'')))),preserved=impact.preserve.filter(key=>beforeRoots[key]&&beforeRoots[key]===afterRoots[key]);
  return seal({format:'rncs.character-incremental-rebuild-receipt.v0.1',character_id:afterGenome.character_id,before_genome_root:beforeGenome.genome_root,after_genome_root:afterGenome.genome_root,before_identity_root:beforeGenome.identity_root,after_identity_root:afterGenome.identity_root,impact_root:impact.impact_root,scope:impact.scope,changed_artifacts:changed,preserved_artifacts:preserved,unexpected_changes:unexpected,duration_ms:durationMs,cache:{hits:cacheHits,misses:cacheMisses,hit_rate:(cacheHits+cacheMisses)?cacheHits/(cacheHits+cacheMisses):0},valid:unexpected.length===0&&(!impact.identity_may_change?beforeGenome.identity_root===afterGenome.identity_root:true),receipt_root:''},'receipt_root');
}
