import type { TermCategoryId }     from "@/constants/vocabulary/termCategories";
import type { TermSystemLayerId }  from "@/constants/vocabulary/termSystemLayers";
import type { TermMaturityId }     from "@/constants/vocabulary/termMaturityLevels";
import type { TermAudienceMode }   from "@/constants/vocabulary/termAudienceModes";
import type { TermLocaleId }       from "@/constants/vocabulary/termLocalizationLocales";

export interface LocalizedTerm {
  locale: TermLocaleId;
  displayTerm: string;
  definition?: string;
  translationNote?: string;
  stale?: boolean;
}

export interface TermUsageExample {
  exampleId: string;
  inputContext: string;
  correctUsage: string;
  incorrectUsage?: string;
  explanation: string;
}

export interface VocabularyTerm {
  termId: string;
  chineseTerm: string;
  englishTerm: string;
  aliases: string[];
  category: TermCategoryId;
  systemLayer: TermSystemLayerId;
  maturity: TermMaturityId;
  audienceMode: TermAudienceMode;
  shortDefinition: string;
  plainDefinition: string;
  technicalDefinition: string;
  sourceType:
    | "PRODUCT" | "SYSTEM" | "WORLD_LORE" | "CALCULUS"
    | "ENGINE"  | "GOVERNANCE" | "USER_CONCEPT" | "FOUNDER";
  relatedModules: string[];
  relatedEngines: string[];
  relatedCalculus: string[];
  relatedTerms: string[];
  correctUsage?: string;
  commonMisuse: string[];
  safetyBoundary: string;
  exampleUsages?: TermUsageExample[];
  localization: LocalizedTerm[];
  version: string;
  founderLocked: boolean;
  createdAt: string;
  updatedAt: string;
}

const NOW = "2026-05-24";
const V = "1.0.0";

/** 快速构造工具，减少冗余。 */
function t(
  termId: string,
  chineseTerm: string,
  englishTerm: string,
  category: TermCategoryId,
  systemLayer: TermSystemLayerId,
  shortDefinition: string,
  plainDefinition: string,
  technicalDefinition: string,
  opts: Partial<VocabularyTerm> = {},
): VocabularyTerm {
  return {
    termId,
    chineseTerm,
    englishTerm,
    aliases: opts.aliases ?? [],
    category,
    systemLayer,
    maturity: opts.maturity ?? "ACTIVE",
    audienceMode: opts.audienceMode ?? "PUBLIC",
    shortDefinition,
    plainDefinition,
    technicalDefinition,
    sourceType: opts.sourceType ?? "SYSTEM",
    relatedModules:  opts.relatedModules  ?? [],
    relatedEngines:  opts.relatedEngines  ?? [],
    relatedCalculus: opts.relatedCalculus ?? [],
    relatedTerms:    opts.relatedTerms    ?? [],
    correctUsage:    opts.correctUsage,
    commonMisuse:    opts.commonMisuse    ?? [],
    safetyBoundary:  opts.safetyBoundary  ?? "属于 Aetherworld 产品内部概念，不代表现实事实、现实金融资产或绝对预测。",
    exampleUsages:   opts.exampleUsages,
    localization:    opts.localization    ?? [{ locale: "en", displayTerm: englishTerm }],
    version:         opts.version         ?? V,
    founderLocked:   opts.founderLocked   ?? false,
    createdAt:       NOW,
    updatedAt:       NOW,
  };
}

export const VOCABULARY_REGISTRY: VocabularyTerm[] = [
  // ===== A. 核心系统词 =====
  t("aetherworld", "Aetherworld", "Aetherworld", "CORE_SYSTEM_TERM", "USER_LAYER",
    "数列元智能操作系统的整体品牌名。",
    "Aetherworld 是整个产品的代号，统称所有引擎、世界和模块。",
    "Aetherworld 指代数列元智能操作系统（Aether Fate Engine）的对外品牌名，是产品级整体名称，包含全部引擎注册表、模块、世界与治理层。",
    { aliases: ["Aether Fate Engine", "数列元智能操作系统"], relatedTerms: ["aether-fate-engine","sequence-ai"] }),
  t("aether-fate-engine", "Aether Fate Engine", "Aether Fate Engine", "CORE_SYSTEM_TERM", "USER_LAYER",
    "Aetherworld 的核心引擎品牌名。",
    "Aether Fate Engine 是 Aetherworld 的内部引擎集合代号，用于强调“数列驱动 + 命数演化”的核心特征。",
    "Aether Fate Engine 指代核心引擎层 (Subject / MSL / World / Governance / QA) 的总称，与品牌 Aetherworld 同义但更偏工程视角。",
    { aliases: ["AFE"], relatedTerms: ["aetherworld"] }),
  t("sequence-meta-ai-os", "数列元智能操作系统", "Sequence Meta-Intelligence OS", "CORE_SYSTEM_TERM", "USER_LAYER",
    "把数列作为最底层抽象的元 OS。",
    "数列元智能操作系统 = 用一串数字（母体数列）来驱动所有引擎、世界、文档和文案的操作系统。",
    "Sequence Meta-Intelligence OS 把母体数列（Mother Sequence）作为统一底层符号，调度 MSL、计算法、引擎、世界与治理层。",
    { aliases: ["Meta-OS"], relatedTerms: ["mother-sequence","msl","sequence-ai"] }),
  t("sequence-ai", "数列 AI", "Sequence AI", "CORE_SYSTEM_TERM", "ENGINE_LAYER",
    "把数列、计算法和引擎统一起来的 AI 入口。",
    "Sequence AI 是 Aetherworld 的内部 AI，它读取你的母体数列并调度对应的引擎来回答你。",
    "Sequence AI 是 Free Input → Engine Router → Calculus Layer → Engine Registry 的总调度模块，承担自然语言到结构化执行的转译。",
    { aliases: ["数列人工智能","Aether AI"], relatedTerms: ["free-input","msl","calculus-universe"] }),
  t("free-input", "Free Input", "Free Input", "CORE_SYSTEM_TERM", "USER_LAYER",
    "一句话就能调度系统的自然语言入口。",
    "Free Input 是“随便问”入口，你写一句话，系统帮你分发到合适的引擎。",
    "Free Input 模块负责自然语言解析、意图识别、计算法匹配与引擎路由，是 Sequence AI 的前端入口。",
    { aliases: ["随便问","Free Answer"], relatedTerms: ["sequence-ai"] }),
  t("omni-dispatch", "Omni 全域调度", "Omni Dispatcher", "CORE_SYSTEM_TERM", "ENGINE_LAYER",
    "把请求分发到合适引擎的调度层。",
    "Omni 全域调度负责把一个请求送到正确的引擎处理，避免你自己挑模块。",
    "Omni Dispatcher 维护 engine route table，根据计算法标签、主体模式和权限把请求分发到对应引擎。",
    { aliases: ["Omni"], audienceMode: "ADVANCED" }),
  t("engine-registry", "引擎注册表", "Engine Registry", "CORE_SYSTEM_TERM", "ENGINE_LAYER",
    "记录所有引擎及其元数据的表。",
    "引擎注册表是系统里所有引擎的清单，写明每个引擎是做什么的、归谁管。",
    "Engine Registry 记录 engineId / capability / inputs / outputs / weights / safety / version 等元数据，供调度与审计使用。",
    { audienceMode: "ADVANCED", relatedTerms: ["sequence-ai","omni-dispatch"] }),
  t("product-encyclopedia", "产品百科", "Product Encyclopedia", "CORE_SYSTEM_TERM", "KNOWLEDGE_LAYER",
    "产品概念与功能的长百科。",
    "产品百科是 Aetherworld 所有功能、概念和世界观的长文档库。",
    "Product Encyclopedia 由 encyclopediaSeedEntries 提供条目，按概念聚合 UI、Docs、Vocabulary、Calculus、World 的相关链接。",
    { relatedTerms: ["vocabulary","calculus-universe-encyclopedia","learning-docs"] }),
  t("usage-examples", "Usage Examples", "Usage Examples", "CORE_SYSTEM_TERM", "UI_LAYER",
    "每个模块的使用示例集。",
    "Usage Examples 是每个功能模块的“怎么用”示例，让你一眼看懂能输入什么。",
    "Usage Examples 由 examplePromptBinder 注入到 UI 模块卡片中，与 quickStart、emptyState 共同构成入口完整性。",
    { relatedTerms: ["ui-update-engine","quick-start"] }),
  t("learning-center", "学习中心", "Learning Center", "DOCS_TERM", "DOCS_LAYER",
    "教学与教程入口。",
    "学习中心汇总所有 Aetherworld 教程、模块手册、FAQ 和术语表。",
    "Learning Center 由 Learning & Documentation Engine 驱动，按 audienceMode 输出不同深度的教程清单。",
    { aliases: ["Learning Docs"], relatedTerms: ["learning-docs","faq","glossary"] }),

  // ===== B. 数列与主体词 =====
  t("mother-sequence", "母体数列", "Mother Sequence", "SEQUENCE_TERM", "SUBJECT_LAYER",
    "代表一个主体的核心数字序列。",
    "母体数列是用数字描述“你是谁、当前状态、倾向方向”的一串数字。",
    "Mother Sequence 是主体的核心数字向量（默认 Full60 = 60 位），所有引擎以它为输入；属于 USER_PRIVATE。",
    { aliases: ["主体数列","Mother Seq"],
      relatedTerms: ["full60","light20","msl","subject-mode","subject-sequence-firewall"],
      commonMisuse: ["把母体数列等同于现实身份证件","把母体数列当成可买卖的资产"],
      safetyBoundary: "母体数列属于用户私有的内部状态向量，不是现实身份、不可金融化、不可被外部数据直接覆盖。" }),
  t("full60", "Full60 主体数列", "Full60 Subject Sequence", "SEQUENCE_TERM", "SUBJECT_LAYER",
    "完整的 60 位主体数列。",
    "Full60 是完整版的母体数列，60 位数字一起描述你最真实的样子。",
    "Full60 是 60 位高维主体数列，默认 USER_PRIVATE，不参与 PUBLIC_DEMO，输出受 Subject Sequence Firewall 保护。",
    { aliases: ["Full60"],
      relatedTerms: ["mother-sequence","light20","demo-mode","subject-sequence-firewall"],
      commonMisuse: ["把 Full60 公开展示","把 Full60 直接传给外部系统"],
      safetyBoundary: "Full60 默认 USER_PRIVATE，禁止以公开数据形式展示或对外传输，必须经过隐私提示。" }),
  t("light20", "Light20 主体数列", "Light20 Subject Sequence", "SEQUENCE_TERM", "SUBJECT_LAYER",
    "可在公共场景使用的 20 位简化数列。",
    "Light20 是 Full60 的简化版，只有 20 位，可以在 Demo 或公开场景中使用。",
    "Light20 是 Full60 的降维投影（默认 20 位），用于 PUBLIC_DEMO 与外部接口，不暴露 Full60 高位信息。",
    { relatedTerms: ["full60","demo-mode","public-demo"] }),
  t("demo-mode", "Demo Mode", "Demo Mode", "SUBJECT_MODE_TERM", "SUBJECT_LAYER",
    "用于展示与试用的主体模式。",
    "Demo Mode 让你不输入真实信息就能体验整个系统。",
    "Demo Mode 使用 Light20 与合成主体画像，所有输出标记 demo=true，不可被当作 Real Subject 输出。",
    { relatedTerms: ["real-subject","light20","subject-mode-resolver"],
      commonMisuse: ["把 Demo Mode 输出当成真实预测"],
      safetyBoundary: "Demo Mode 仅用于演示，不构成对真实主体的判断或建议。" }),
  t("real-subject", "Real Subject", "Real Subject", "SUBJECT_MODE_TERM", "SUBJECT_LAYER",
    "真实用户主体。",
    "Real Subject 表示这一次系统在为真实的你做判断。",
    "Real Subject 调用真实 Full60 / Light20 主体数列，输出标记 real=true，受 Subject Sovereignty 保护。",
    { audienceMode: "ADVANCED", relatedTerms: ["demo-mode","subject-sovereignty"] }),
  t("founder-subject", "Founder Subject", "Founder Subject", "SUBJECT_MODE_TERM", "FOUNDER_LAYER",
    "Founder 自身主体。",
    "Founder Subject 是创始人本人的主体身份，对应最高权限。",
    "Founder Subject 在主体解析中拥有最高权限，可访问 Founder-only 引擎、终端与 Audit。",
    { audienceMode: "FOUNDER", founderLocked: true, maturity: "FOUNDER_LOCKED" }),
  t("subject-mode", "主体模式", "Subject Mode", "SUBJECT_MODE_TERM", "SUBJECT_LAYER",
    "当前系统服务的主体类型。",
    "主体模式说明现在系统在为谁服务：Demo、真实你，还是 Founder。",
    "Subject Mode ∈ { DEMO, REAL, FOUNDER }，控制数据隔离、权限、输出标签与隐私边界。",
    { relatedTerms: ["demo-mode","real-subject","founder-subject","subject-mode-resolver"] }),
  t("subject-mode-resolver", "主体模式解析器", "Subject Mode Resolver", "SUBJECT_MODE_TERM", "SUBJECT_LAYER",
    "决定当前请求属于哪种主体模式。",
    "主体模式解析器在你提出请求时，判断要用 Demo、真实你还是 Founder 来回答。",
    "Subject Mode Resolver 根据登录态、路由、上下文与配置解析当前 SubjectMode，并把结果注入所有引擎调用。",
    { audienceMode: "ADVANCED" }),
  t("subject-sequence-firewall", "主体数列防火墙", "Subject Sequence Firewall", "GOVERNANCE_TERM", "SAFETY_LAYER",
    "防止外部数据污染主体数列。",
    "主体数列防火墙保护你的 Full60 / Light20 不被外部数据直接改写。",
    "Subject Sequence Firewall 拦截外部数据写入路径，外部数据仅能影响 calibratedOutput / validationHistory，不可直接修改主体数列。",
    { audienceMode: "ADVANCED",
      relatedTerms: ["reality-data-calibration","mother-sequence"],
      safetyBoundary: "防火墙是隔离层，外部数据不能跨过它直接覆盖主体数列。" }),
  t("subject-sequence-bias", "主体数列偏置", "Subject Sequence Bias", "SEQUENCE_TERM", "SUBJECT_LAYER",
    "对主体数列做受控偏置以体现倾向。",
    "主体数列偏置允许在一定范围内让数列偏向某种状态，例如更冒险、更稳健。",
    "Subject Sequence Bias 是受常数宇宙约束的有界偏置算子，作用于工作副本，不修改原始 Full60。",
    { audienceMode: "ADVANCED" }),
  t("subject-portrait", "主体画像", "Subject Portrait", "SUBJECT_MODE_TERM", "SUBJECT_LAYER",
    "由数列衍生出的主体描述。",
    "主体画像把数列翻译成可读的描述，比如倾向、节奏、状态。",
    "Subject Portrait 由 Subject Profile Generator 从 Full60/Light20 衍生，是 UI 展示用结构。"),
  t("subject-mode-switch", "主体模式切换", "Subject Mode Switch", "SUBJECT_MODE_TERM", "SUBJECT_LAYER",
    "在 Demo / Real / Founder 之间切换。",
    "主体模式切换让你在演示模式和真实模式之间切换。",
    "Subject Mode Switch 是 UI 与 API 层的模式切换控件，切换会触发 Recalculation 标记 stale。"),
  t("subject-privacy", "主体隐私", "Subject Privacy", "GOVERNANCE_TERM", "SAFETY_LAYER",
    "保护主体数据的边界。",
    "主体隐私规定哪些数据是你私有的、哪些可以公开。",
    "Subject Privacy 受 USER_PRIVATE 策略约束，Full60 默认 USER_PRIVATE，未授权不可外发。",
    { safetyBoundary: "默认 USER_PRIVATE，必须显式授权才能切换为可分享形态。" }),
  t("user-private", "USER_PRIVATE", "USER_PRIVATE", "GOVERNANCE_TERM", "SAFETY_LAYER",
    "用户私有数据等级。",
    "USER_PRIVATE 表示这条数据只属于你自己，不能被公开。",
    "USER_PRIVATE 是 privacy scope 标签，默认应用于 Full60、个人画像、私人世界。"),
  t("public-demo", "PUBLIC_DEMO", "PUBLIC_DEMO", "GOVERNANCE_TERM", "SAFETY_LAYER",
    "演示用公开数据等级。",
    "PUBLIC_DEMO 表示这条数据是演示用的，不代表真实情况。",
    "PUBLIC_DEMO 是 privacy scope 标签，标记 Light20 / Demo 主体生成的可对外展示内容。"),

  // ===== C. MSL 与语言词 =====
  t("msl", "MSL", "MSL", "SEQUENCE_TERM", "LANGUAGE_LAYER",
    "母体数列语言。",
    "MSL 是用来读写数列的语言，让数字像代码一样可被运行。",
    "MSL = Mother Sequence Language，定义 BLOCK / PROGRAM / 数字操作码与五域语义，是数列层的可执行 DSL。",
    { aliases: ["母体数列语言","Mother Sequence Language"], relatedTerms: ["mother-sequence","sequence-terminal","msl-runtime"] }),
  t("mother-sequence-language", "母体数列语言", "Mother Sequence Language", "SEQUENCE_TERM", "LANGUAGE_LAYER",
    "MSL 的中文全称。",
    "母体数列语言 = MSL。",
    "见 MSL 词条。", { aliases: ["MSL"], relatedTerms: ["msl"] }),
  t("sequence-terminal", "数列终端", "Sequence Terminal", "UI_TERM", "UI_LAYER",
    "运行数列命令的终端。",
    "数列终端是一个命令行界面，可以直接对系统下指令。",
    "Sequence Terminal 是 MSL Runtime 的命令行入口，支持 parse / explain / run / compile / engine 命令。",
    { aliases: ["Aether Terminal"], relatedTerms: ["msl","msl-runtime","founder-terminal"] }),
  t("msl-runtime", "MSL 运行时", "MSL Runtime", "SEQUENCE_TERM", "LANGUAGE_LAYER",
    "执行 MSL 程序的运行时。",
    "MSL 运行时是真正“跑数列”的部分。",
    "MSL Runtime 解释 BLOCK / PROGRAM、执行数字操作码并把输出送回 Sequence AI / 引擎。",
    { audienceMode: "ADVANCED" }),
  t("digit-opcode", "数字操作码", "Digit Opcode", "SEQUENCE_TERM", "LANGUAGE_LAYER",
    "0–9 各自代表的语义。",
    "数字操作码就是 0–9 这十个数字各自的含义。",
    "Digit Opcode 是常数宇宙中定义的 0–9 语义表，作为 MSL 最小指令。",
    { relatedTerms: ["constant-universe","five-domains"] }),
  t("five-domains", "五域", "Five Domains", "SEQUENCE_TERM", "LANGUAGE_LAYER",
    "数列的五个语义域。",
    "五域是把数列分成五类语义：天、地、人、神、风。",
    "Five Domains 将数列分为 Heaven / Earth / Human / Divine / Wind 域，每个域承担不同语义维度。",
    { relatedTerms: ["heaven-domain","earth-domain","human-domain","divine-domain","wind-domain"] }),
  t("heaven-domain", "天域", "Heaven Domain", "SEQUENCE_TERM", "LANGUAGE_LAYER",
    "宏观节律域。",
    "天域代表大方向、大周期。",
    "Heaven Domain 承担宏观节律 / 命运曲线维度。"),
  t("earth-domain", "地域", "Earth Domain", "SEQUENCE_TERM", "LANGUAGE_LAYER",
    "资源与基础域。",
    "地域代表资源、基础、土壤。",
    "Earth Domain 承担资源 / 基础结构 / 物质维度。"),
  t("human-domain", "人域", "Human Domain", "SEQUENCE_TERM", "LANGUAGE_LAYER",
    "关系与行为域。",
    "人域代表人际、行为、社会。",
    "Human Domain 承担关系 / 行动 / 社会结构维度。"),
  t("divine-domain", "神域", "Divine Domain", "SEQUENCE_TERM", "LANGUAGE_LAYER",
    "信念与超越域。",
    "神域代表信念、意义、超越。",
    "Divine Domain 承担意义 / 信念 / 超越性维度。"),
  t("wind-domain", "风域", "Wind Domain", "SEQUENCE_TERM", "LANGUAGE_LAYER",
    "变数与扰动域。",
    "风域代表变数、扰动、机会。",
    "Wind Domain 承担扰动 / 机会 / 不确定性维度。"),
  t("sequence-command", "数列命令", "Sequence Command", "UI_TERM", "UI_LAYER",
    "在终端中输入的一条命令。",
    "数列命令就是你在终端里敲的一行字。",
    "Sequence Command 是 Terminal Command 的别名，由 terminalCommands.ts 注册。"),
  t("terminal-command", "终端命令", "Terminal Command", "UI_TERM", "UI_LAYER",
    "终端中可执行的命令。",
    "终端命令是终端里可以使用的指令列表。",
    "Terminal Command 由 CommandDefinition 描述，含 permission / safety / examples。"),
  t("founder-terminal", "Founder 终端", "Founder Terminal", "UI_TERM", "FOUNDER_LAYER",
    "Founder 专属终端。",
    "Founder 终端只有创始人能用。",
    "Founder Terminal 暴露 founder.* / system.audit / engine.audit 等高权限命令。",
    { audienceMode: "FOUNDER", founderLocked: true, maturity: "FOUNDER_LOCKED" }),

  // ===== D. 计算法词 =====
  t("calculus-universe", "计算法宇宙", "Calculus Universe", "CALCULUS_TERM", "CALCULUS_LAYER",
    "Aetherworld 所有计算法的总集。",
    "计算法宇宙是系统里所有“计算方法”的总仓库。",
    "Calculus Universe 是 calculusRegistry 维护的方法总集，按 category / maturity / engine 索引。",
    { relatedTerms: ["calculus-universe-encyclopedia","thing-itself-calculus","universal-breakthrough-calculus"] }),
  t("calculus-universe-encyclopedia", "计算法宇宙百科", "Calculus Universe Encyclopedia", "CALCULUS_TERM", "KNOWLEDGE_LAYER",
    "计算法宇宙的百科入口。",
    "计算法宇宙百科是查看每个计算法详情的页面。",
    "Calculus Universe Encyclopedia 提供 calculusRegistry 的可浏览界面，含分类 / 搜索 / 安全边界。"),
  t("thing-itself-calculus", "万物本身计算法", "Thing-Itself Calculus", "CALCULUS_TERM", "CALCULUS_LAYER",
    "用于回到对象本身的计算法。",
    "万物本身计算法用来抛开干扰，直接看一个事物本身是什么。",
    "Thing-Itself Calculus 在 calculusRegistry 中标记为 CONCEPT_ABSTRACTION 类，输出对象本体结构。"),
  t("universal-breakthrough-calculus", "万物破解计算法", "Universal Breakthrough Calculus", "CALCULUS_TERM", "CALCULUS_LAYER",
    "用于拆解复杂问题的计算法。",
    "万物破解计算法用来把复杂问题层层拆开。",
    "Universal Breakthrough Calculus 提供层级拆解 + 关键路径定位。"),
  t("mother-sequence-calculus", "母体数列计算法", "Mother Sequence Calculus", "CALCULUS_TERM", "CALCULUS_LAYER",
    "围绕母体数列展开的计算法。",
    "母体数列计算法是直接用数列来算结果的方法。",
    "Mother Sequence Calculus 以 Full60 / Light20 为输入运行结构化推断。"),
  t("model-generation-calculus", "模型生成计算法", "Model Generation Calculus", "CALCULUS_TERM", "CALCULUS_LAYER",
    "生成结构化模型的计算法。",
    "模型生成计算法用来给一个想法生成结构化模型。",
    "Model Generation Calculus 输出结构化对象 schema，供下游引擎使用。"),
  t("copy-generation-calculus", "文案生成计算法", "Copy Generation Calculus", "CALCULUS_TERM", "TEXT_LAYER",
    "生成应用文案的计算法。",
    "文案生成计算法用于生成按钮、标题、说明等文案。",
    "Copy Generation Calculus 与 Text Dynamic Update Engine 协作生成 / 修订应用文本。"),
  t("code-generation-calculus", "代码生成计算法", "Code Generation Calculus", "CALCULUS_TERM", "CALCULUS_LAYER",
    "生成代码的计算法。",
    "代码生成计算法用于把需求转成代码。",
    "Code Generation Calculus 接 Prompt Forge 输出工程化提示。"),
  t("world-generation-calculus", "世界生成计算法", "World Generation Calculus", "CALCULUS_TERM", "WORLD_LAYER",
    "生成虚构世界的计算法。",
    "世界生成计算法用来从数列生成一个完整世界。",
    "World Generation Calculus 是 Sequence World Engine 的入口算子。"),
  t("virtual-life-calculus", "虚拟生活计算法", "Virtual Life Calculus", "CALCULUS_TERM", "WORLD_LAYER",
    "生成虚拟日常的计算法。",
    "虚拟生活计算法用来生成你的“另一种生活的一天”。",
    "Virtual Life Calculus 输出 virtual day / journal / event 序列。"),
  t("text-dynamic-update-calculus", "文本动态更新计算法", "Text Dynamic Update Calculus", "CALCULUS_TERM", "TEXT_LAYER",
    "检测并更新应用文案的计算法。",
    "文本动态更新计算法负责检查文案是否过期并生成新文案。",
    "Text Dynamic Update Calculus 驱动 Text Dynamic Update Engine 的 detect / generate / review 流程。"),
  t("version-leap-calculus", "版本跃迁计算法", "Version Leap Calculus", "CALCULUS_TERM", "VERSION_LAYER",
    "判断版本跃迁等级的计算法。",
    "版本跃迁计算法用来评估这次更新是补丁还是大跃迁。",
    "Version Leap Calculus 输出 patch/minor/major/leap/generation 等级。"),
  t("reality-data-calibration-calculus", "外部现实数据校准计算法", "Reality Data Calibration Calculus", "CALCULUS_TERM", "QUALITY_LAYER",
    "用外部数据校准内部判断的计算法。",
    "外部现实数据校准计算法用来用外部资料修正系统结论。",
    "Reality Data Calibration Calculus 在不污染主体数列的前提下融合外部数据。",
    { relatedTerms: ["reality-data-calibration","subject-sequence-firewall"] }),
  t("validation-calculus", "回验计算法", "Validation Calculus", "CALCULUS_TERM", "QUALITY_LAYER",
    "用历史结果回测系统结论的计算法。",
    "回验计算法把过去的结果拿来检查现在的方法是否还有效。",
    "Validation Calculus 与 Software QA 协作执行回测。"),
  t("qa-calculus", "QA 计算法", "QA Calculus", "CALCULUS_TERM", "QUALITY_LAYER",
    "运行软件质量审计的计算法。",
    "QA 计算法是系统自己给自己做体检的方法。",
    "QA Calculus 驱动 Software QA Engine 输出 issues 与 severity。"),

  // ===== E. 世界引擎词 =====
  t("sequence-world-engine", "数列世界引擎", "Sequence World Engine", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "从数列出发生成与运行虚构世界。",
    "数列世界引擎用数列生成世界，并让它持续“活下去”。",
    "Sequence World Engine v0.1–v0.7 覆盖参数生成、模拟内核、生长、社会、文明、表现层、多世界网络。",
    { relatedTerms: ["world-generation","world-simulation","world-growth","world-society","civilization-evolution","world-presentation","multi-world-network"] }),
  t("world-generation", "世界生成", "World Generation", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "从数列生成世界初始参数。",
    "世界生成把数列翻译成一个世界的初始设定。",
    "World Generation v0.1 输出 world seed / domain / faction / map 初始结构。"),
  t("world-simulation", "世界模拟", "World Simulation", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "让世界按规则演化。",
    "世界模拟让世界自己运行，事件随时间推进。",
    "World Simulation 是 World Tick 驱动的内核，按规则演化人口、资源、事件。",
    { commonMisuse: ["把世界模拟当成对现实的预测"],
      safetyBoundary: "世界模拟是虚构世界内部演化，不构成现实预测。" }),
  t("world-tick", "World Tick", "World Tick", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界模拟的时间步进单位。",
    "World Tick 是世界时间往前走一步。",
    "World Tick 是 simulation loop 的最小时间单位，决定演化速度。"),
  t("world-growth", "世界生长", "World Growth", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界自我生长能力。",
    "世界生长让世界自己长出新的元素，不全靠你手动加。",
    "World Growth (v0.3) 是 Self-Growing World OS，按 growth policy 自动注入要素。"),
  t("world-canon", "世界正典", "World Canon", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界已被认定的事实集合。",
    "世界正典是一个世界里被认定为“真”的设定。",
    "World Canon 是 canon registry，不一致的内容会触发 Cross-World Canon 校验。"),
  t("world-society", "世界社会", "World Society", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界中的智能体与关系网络。",
    "世界社会是世界里 NPC 与他们关系组成的网。",
    "World Society (v0.4) 由 NPC Agent / Faction / Institution / Social Graph 构成。"),
  t("npc-agent", "NPC Agent", "NPC Agent", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界中的智能体。",
    "NPC Agent 是世界里有自主行为的角色。",
    "NPC Agent 拥有 memory / goals / relations，被 social graph 连接。"),
  t("social-graph", "社会图谱", "Social Graph", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "NPC 间关系网络。",
    "社会图谱是 NPC 之间关系的网络结构。",
    "Social Graph 是有向加权图，节点为 NPC，边为关系类型。"),
  t("faction", "派系", "Faction", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界中的组织派系。",
    "派系是一群有共同目标的 NPC 组织。",
    "Faction 是 social graph 的中观聚合单位。"),
  t("institution", "制度", "Institution", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界中的制度规则。",
    "制度是这个世界里大家默认遵守的规则。",
    "Institution 在世界社会中扮演规则约束角色。"),
  t("civilization-evolution", "文明演化", "Civilization Evolution", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界中的文明长期演化。",
    "文明演化让世界从远古一路发展到未来。",
    "Civilization Evolution (v0.5) 输出历史时间线、科技树、文明神话。"),
  t("historical-timeline", "历史时间线", "Historical Timeline", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界的历史时间线。",
    "历史时间线是这个世界从开端到现在的时间顺序。",
    "Historical Timeline 由 civilization evolution engine 输出。"),
  t("technology-tree", "科技树", "Technology Tree", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界中科技演进图。",
    "科技树是世界里科技发展的顺序图。",
    "Technology Tree 是 DAG 结构，节点为 tech，边为 prerequisite。"),
  t("civilization-myth", "文明神话", "Civilization Myth", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界的核心神话叙事。",
    "文明神话是这个世界自己流传的传说和信仰。",
    "Civilization Myth 由 myth generator 基于数列与历史输出。"),
  t("world-presentation", "世界表现层", "World Presentation", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界的视觉/动画/物理表现。",
    "世界表现层负责把世界“演”出来：动画、画面、声音。",
    "World Presentation (v0.6) 包含 semantic physics / animation runtime / camera language / world audio。",
    { commonMisuse: ["把世界表现层当成真实渲染引擎"] }),
  t("semantic-physics", "语义物理", "Semantic Physics", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "为叙事服务的近似物理。",
    "语义物理不是真物理，是为了让画面合理的近似规则。",
    "Semantic Physics 是叙事级近似物理，不追求科学严谨。",
    { safetyBoundary: "语义物理不是真实物理仿真，不可作为科学结论使用。" }),
  t("animation-runtime", "动画运行时", "Animation Runtime", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "驱动世界动画播放。",
    "动画运行时是负责让画面动起来的部分。",
    "Animation Runtime 管理 keyframe / blending / tween。"),
  t("camera-language", "镜头语言", "Camera Language", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界镜头叙事规范。",
    "镜头语言决定怎么用镜头讲故事。",
    "Camera Language 提供镜头模板与切换规则。"),
  t("world-audio", "世界音频", "World Audio", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界声音层。",
    "世界音频是这个世界的声音设计。",
    "World Audio 提供 ambient / SFX / music 层。"),
  t("multi-world-network", "多世界网络", "Multi-World Network", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "多个世界互通的网络层。",
    "多世界网络让你的多个世界可以互访、迁移、联邦。",
    "Multi-World Network (v0.7) 提供 portal / travel / federation / cross-world canon。"),
  t("world-portal", "世界门户", "World Portal", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "世界之间的连接点。",
    "世界门户是从一个世界进入另一个世界的入口。",
    "World Portal 以 0–9 数字映射定义连接规则。",
    { commonMisuse: ["把世界门户当成现实空间穿越"],
      safetyBoundary: "世界门户仅在虚构世界之间生效，不是现实穿越。" }),
  t("world-travel", "世界互访", "World Travel", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "穿越世界门户的行为。",
    "世界互访就是带着角色或资源去另一个世界。",
    "World Travel 通过 portal engine 执行 NPC / asset 迁移。"),
  t("cross-world-canon", "跨世界正典", "Cross-World Canon", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "防止多个世界的设定互相污染。",
    "跨世界正典确保不同世界的设定不会乱串。",
    "Cross-World Canon 校验 canon 一致性并隔离冲突。"),
  t("world-federation", "世界联邦", "World Federation", "WORLD_ENGINE_TERM", "WORLD_LAYER",
    "多个世界组成的联邦。",
    "世界联邦是几个世界结成一组，共享规则。",
    "World Federation 维护共享 canon 与规则集合。"),
  t("multi-world-export", "多世界导出", "Multi-World Export", "EXPORT_TERM", "WORLD_LAYER",
    "导出多世界到外部引擎。",
    "多世界导出把世界包导到 Godot / Unity / Three.js 中。",
    "Multi-World Export 支持 godot (snake_case) / unity / three.js 三类目标格式。"),

  // ===== F. 治理词 =====
  t("constant-universe", "常数宇宙", "Constant Universe", "GOVERNANCE_TERM", "GOVERNANCE_LAYER",
    "全部引擎共用的系统常数注册与治理层。",
    "常数宇宙是系统里所有规则数值的统一表，比如 0–9 含义、各引擎权重。",
    "Constant Universe 注册 digit / domain / engine weight / threshold / risk / mode 等常数，并提供版本与冲突检测。",
    { relatedTerms: ["system-constitution","digit-opcode","five-domains","engine-weights"],
      commonMisuse: ["把常数宇宙当成现实物理常数表"],
      safetyBoundary: "常数宇宙是产品内部常数治理层，不代表现实自然科学定律。" }),
  t("digit-constants", "数字常数", "Digit Constants", "GOVERNANCE_TERM", "GOVERNANCE_LAYER",
    "0–9 的常量定义。",
    "数字常数定义 0–9 各自的含义。",
    "Digit Constants 是常数宇宙中关于 0–9 语义的子集。"),
  t("domain-constants", "五域常数", "Domain Constants", "GOVERNANCE_TERM", "GOVERNANCE_LAYER",
    "五域的常量定义。",
    "五域常数定义天、地、人、神、风各自的含义。",
    "Domain Constants 是常数宇宙中五域语义子集。"),
  t("engine-weights", "引擎权重", "Engine Weights", "GOVERNANCE_TERM", "GOVERNANCE_LAYER",
    "各引擎在调度中的权重。",
    "引擎权重决定哪个引擎在某些场景下更被优先使用。",
    "Engine Weights 用于调度评分与冲突仲裁。"),
  t("threshold-constants", "阈值常数", "Threshold Constants", "GOVERNANCE_TERM", "GOVERNANCE_LAYER",
    "触发某些操作的临界值。",
    "阈值常数是系统在哪些数值上会触发警告或行为。",
    "Threshold Constants 用于风险触发、stale 检测、跃迁判定。"),
  t("risk-constants", "风险常数", "Risk Constants", "GOVERNANCE_TERM", "GOVERNANCE_LAYER",
    "风险评估常量。",
    "风险常数定义不同行为对应的风险等级。",
    "Risk Constants 用于 risk classifier 与 safety guard。"),
  t("system-constitution", "系统宪法", "System Constitution", "GOVERNANCE_TERM", "GOVERNANCE_LAYER",
    "Aetherworld 的最高治理文档。",
    "系统宪法是 Aetherworld 内部最重要的规则文件。",
    "System Constitution 由 Founder Locked 条款组成，所有引擎输出都受其约束。",
    { relatedTerms: ["founder-locked","authority-hierarchy","subject-sovereignty"],
      commonMisuse: ["把系统宪法当成现实法律"],
      safetyBoundary: "系统宪法是产品内部治理文件，不具有现实法律效力。" }),
  t("founder-locked", "Founder Locked", "Founder Locked", "GOVERNANCE_TERM", "FOUNDER_LAYER",
    "由 Founder 锁定不可修改。",
    "Founder Locked 表示这部分只能由创始人改。",
    "Founder Locked 是宪法 / 常数 / 词条的锁定标签，需 founder approval 才能修改。",
    { audienceMode: "FOUNDER" }),
  t("authority-hierarchy", "权威层级", "Authority Hierarchy", "GOVERNANCE_TERM", "GOVERNANCE_LAYER",
    "宪法、常数、引擎、用户的优先级。",
    "权威层级说明谁说了算：宪法最高，然后是常数，再到引擎，最后到普通输出。",
    "Authority Hierarchy: Constitution > Constant Universe > Engine Registry > Output。",
    { audienceMode: "ADVANCED" }),
  t("subject-sovereignty", "主体主权", "Subject Sovereignty", "GOVERNANCE_TERM", "GOVERNANCE_LAYER",
    "用户对自己主体数据拥有最终主权。",
    "主体主权意味着你自己的数据由你说了算。",
    "Subject Sovereignty 是宪法核心条款，保证用户对 Full60 / 私人世界拥有控制权。",
    { audienceMode: "ADVANCED" }),
  t("constitutional-compliance", "宪法合规", "Constitutional Compliance", "GOVERNANCE_TERM", "SAFETY_LAYER",
    "输出符合宪法的状态。",
    "宪法合规表示某个输出没有违反系统宪法。",
    "Constitutional Compliance 是输出标签，由 constitution.check 给出。"),
  t("constitutional-violation", "宪法违规", "Constitutional Violation", "GOVERNANCE_TERM", "SAFETY_LAYER",
    "违反宪法的输出。",
    "宪法违规表示这个输出踩了系统宪法的红线。",
    "Constitutional Violation 由 constitution violation registry 维护类别。"),
  t("safety-boundary", "安全边界", "Safety Boundary", "SAFETY_TERM", "SAFETY_LAYER",
    "防止误用的边界说明。",
    "安全边界告诉你某个东西不可以被用来做什么。",
    "Safety Boundary 是结构化字段，附着在引擎、词条、文案上，参与 audit 与 UI 展示。"),
  t("permission-guard", "权限守卫", "Permission Guard", "SAFETY_TERM", "SAFETY_LAYER",
    "请求级权限校验。",
    "权限守卫在你点某个功能时检查你能不能用。",
    "Permission Guard 在路由 / API 调用上执行 SubjectMode + Role 检查。"),
  t("reality-fiction-boundary", "现实 / 虚构边界", "Reality / Fiction Boundary", "SAFETY_TERM", "SAFETY_LAYER",
    "虚构内容与现实内容的分界线。",
    "现实/虚构边界提醒你某些内容只是产品内部设定，不代表现实。",
    "Reality / Fiction Boundary 强制虚构 lore、虚拟世界、内部货币不被表述为现实。",
    { safetyBoundary: "禁止把虚构世界设定、内部货币、内部常数表述为现实事实。" }),

  // ===== G. UI / 文档 / 文本 / 知识词 =====
  t("ui-update-engine", "UI 界面更新引擎", "UI Update Engine", "UI_TERM", "UI_LAYER",
    "维持入口完整性的 UI 引擎。",
    "UI 界面更新引擎自动检查页面是否缺少 Quick Start、空状态、示例等。",
    "UI Update Engine 由 uiModuleRegistry、UIAuditPanel、quickStart/emptyState/safety 模板与 stale 检测组成。",
    { relatedTerms: ["interface-audit","quick-start","empty-state","collapsible-sub-router"] }),
  t("interface-audit", "界面审计", "Interface Audit", "UI_TERM", "UI_LAYER",
    "UI 模块的审计报告。",
    "界面审计告诉你哪些模块的入口、提示、示例缺失。",
    "Interface Audit 输出 totalModules / modulesWithRoutes / quickStart / examples / emptyStates / safety / stale / CRITICAL。"),
  t("quick-start", "Quick Start", "Quick Start", "UI_TERM", "UI_LAYER",
    "模块的快速入门入口。",
    "Quick Start 是每个功能的“怎么开始”按钮。",
    "Quick Start 模板由 quickStartTemplates 维护，按 audienceMode 输出三套版本。"),
  t("empty-state", "空状态", "Empty State", "UI_TERM", "UI_LAYER",
    "数据为空时的提示。",
    "空状态是当还没有数据时页面应该怎么显示。",
    "Empty State 模板由 emptyStateTemplates 维护，与 UI Audit 联动。"),
  t("collapsible-sub-router", "子路由展开收起", "Collapsible Sub-Router", "UI_TERM", "UI_LAYER",
    "可折叠的多级路由系统。",
    "子路由展开收起让侧边栏可以折叠和展开。",
    "Collapsible Sub-Router 由 CollapsibleSidebarGroup / SubRouteAuditPanel 等组件实现。"),
  t("learning-docs", "教程与教学文档引擎", "Learning & Documentation Engine", "DOCS_TERM", "DOCS_LAYER",
    "教程、文档、FAQ 总引擎。",
    "学习文档引擎统一管理教程、模块手册、FAQ、术语表。",
    "Learning Docs 输出 beginner / creator / developer / founder 四套包。",
    { relatedTerms: ["learning-center","faq","glossary"] }),
  t("module-docs", "模块文档", "Module Docs", "DOCS_TERM", "DOCS_LAYER",
    "单模块的技术 / 用户文档。",
    "模块文档是每个模块独立的说明书。",
    "Module Docs 按 moduleId 注册，包含 audience 分层内容。"),
  t("faq", "FAQ", "FAQ", "DOCS_TERM", "DOCS_LAYER",
    "常见问题集合。",
    "FAQ 是常见问题的答案合集。",
    "FAQ 由 learning docs engine 维护。"),
  t("glossary", "术语表", "Glossary", "DOCS_TERM", "DOCS_LAYER",
    "术语简表。",
    "术语表是关键词的简短解释表。",
    "Glossary 是 Vocabulary Encyclopedia 的轻量化派生视图。",
    { relatedTerms: ["vocabulary"] }),
  t("text-dynamic-update-engine", "文本动态更新检测生成引擎", "Text Dynamic Update Engine", "TEXT_TERM", "TEXT_LAYER",
    "应用文本自更新引擎。",
    "文本动态更新引擎在系统变化时自动检测和生成需要更新的文案。",
    "Text Dynamic Update Engine 提供 registry / stale detection / diff / review / version / localization。",
    { relatedTerms: ["text-registry","text-stale","text-diff","text-localization"] }),
  t("text-registry", "文本注册表", "Text Registry", "TEXT_TERM", "TEXT_LAYER",
    "应用文本统一登记表。",
    "文本注册表记录系统里所有受治理的应用文本。",
    "Text Registry 是 TextEntry 的集合，按 scope / audience / type 索引。"),
  t("text-stale", "Text Stale", "Text Stale", "TEXT_TERM", "TEXT_LAYER",
    "需要更新的文本状态。",
    "Text Stale 表示这段文案已经过期。",
    "Text Stale 由 textStaleDetector 在 trigger 发生时标记。"),
  t("text-diff", "Text Diff", "Text Diff", "TEXT_TERM", "TEXT_LAYER",
    "新旧文本差异。",
    "Text Diff 显示文案前后的不同。",
    "Text Diff 由 textDiffEngine 输出 inline diff。"),
  t("text-localization", "文本本地化", "Text Localization", "TEXT_TERM", "TEXT_LAYER",
    "文本的多语言版本。",
    "文本本地化是把文案翻译成不同语言。",
    "Text Localization 维护 zh-CN / zh-HK / zh-TW / en / ja / ko / fr 的同步状态。"),
  t("vocabulary", "词汇百科", "Vocabulary Encyclopedia", "DOCS_TERM", "KNOWLEDGE_LAYER",
    "Aetherworld 词汇百科。",
    "词汇百科解释 Aetherworld 所有术语，包括普通解释和专业解释。",
    "Vocabulary Encyclopedia Engine 管理 termRegistry / relations / aliases / localization / audit / version。",
    { relatedTerms: ["glossary","product-encyclopedia","calculus-universe-encyclopedia"] }),

  // ===== H. 版本 / 数据 / 质量词 =====
  t("version-leap-engine", "应用版本跃迁检测引擎", "Application Version Leap Engine", "VERSION_TERM", "VERSION_LAYER",
    "判断版本跃迁等级的引擎。",
    "版本跃迁引擎判断这次更新是补丁、小版本、大版本还是跃迁。",
    "Version Leap Engine 输出 type / level / readiness / release notes / migration / rollback。"),
  t("version-leap", "版本跃迁", "Version Leap", "VERSION_TERM", "VERSION_LAYER",
    "重大版本跨越。",
    "版本跃迁表示这次更新非常大，是“跃迁式”更新。",
    "Version Leap level ∈ { PATCH, MINOR, MAJOR, LEAP, GENERATION }。"),
  t("release-readiness", "发布就绪", "Release Readiness", "VERSION_TERM", "VERSION_LAYER",
    "本次发布是否可以放出。",
    "发布就绪检查告诉你这次更新是不是可以放出来。",
    "Release Readiness ∈ { READY, WARN, BLOCKED }，CRITICAL 未修复时 BLOCKED。"),
  t("release-notes", "更新日志", "Release Notes", "VERSION_TERM", "DOCS_LAYER",
    "本次发布的说明。",
    "更新日志说明这一版做了什么。",
    "Release Notes 由 releaseNoteGenerator 按 audience 输出 public / founder 版本。"),
  t("migration-plan", "迁移计划", "Migration Plan", "VERSION_TERM", "VERSION_LAYER",
    "数据 / 配置迁移方案。",
    "迁移计划告诉你这次升级要做哪些数据搬迁。",
    "Migration Plan 由 versionMigrationPlanner 输出步骤化方案。"),
  t("rollback-plan", "回滚计划", "Rollback Plan", "VERSION_TERM", "VERSION_LAYER",
    "出现问题时的回滚方案。",
    "回滚计划是这次更新出错时怎么回到上一个版本。",
    "Rollback Plan 由 versionRollbackPlanner 输出可执行步骤。"),
  t("reality-data-calibration", "外部现实数据校准", "Reality Data Calibration", "REALITY_DATA_TERM", "QUALITY_LAYER",
    "用外部数据校准内部结论。",
    "外部现实数据校准在不污染你的主体数列前提下，用外部数据让结果更贴近现实。",
    "Reality Data Calibration Engine 管理 source / freshness / credibility / evidence / calibration。",
    { relatedTerms: ["subject-sequence-firewall","external-data-source","source-credibility","data-freshness","evidence-mapping"] }),
  t("external-data-source", "外部数据源", "External Data Source", "REALITY_DATA_TERM", "QUALITY_LAYER",
    "登记在册的外部数据来源。",
    "外部数据源是系统会去参考的外部资料。",
    "External Data Source 在 registry 中带 credibility / freshness / scope。"),
  t("source-credibility", "来源可信度", "Source Credibility", "REALITY_DATA_TERM", "QUALITY_LAYER",
    "外部来源的可信评分。",
    "来源可信度告诉你这个外部资料有多可靠。",
    "Source Credibility 由 sourceCredibilityScorer 加权计算。"),
  t("data-freshness", "数据新鲜度", "Data Freshness", "REALITY_DATA_TERM", "QUALITY_LAYER",
    "外部数据是否过期。",
    "数据新鲜度表示这条外部数据还新不新。",
    "Data Freshness 由 dataFreshnessDetector 按时间窗判断。"),
  t("evidence-mapping", "证据映射", "Evidence Mapping", "REALITY_DATA_TERM", "QUALITY_LAYER",
    "把外部证据映射到内部判断。",
    "证据映射告诉你内部结论的证据来自哪条外部资料。",
    "Evidence Mapping 由 evidenceMappingEngine 维护证据链。"),
  t("validation", "回验", "Validation", "QA_TERM", "QUALITY_LAYER",
    "用历史结果回测系统结论。",
    "回验是用过去的事实检查现在的方法是否还有效。",
    "Validation 在 validationEngine 中执行。"),
  t("recalculation", "重算", "Recalculation", "QA_TERM", "QUALITY_LAYER",
    "系统重新计算所有受影响内容。",
    "重算让系统在某些事变了之后，重新算一遍所有相关结果。",
    "Recalculation 维护 stale list，触发对应引擎重新计算。"),
  t("software-qa", "软件质量审计", "Software QA", "QA_TERM", "QUALITY_LAYER",
    "系统自检引擎。",
    "软件质量审计是系统自己给自己做体检。",
    "Software QA Engine 输出 issues / severity / blocking。"),
  t("stale-state", "Stale 状态", "Stale State", "QA_TERM", "QUALITY_LAYER",
    "需要重新计算或更新的状态。",
    "Stale 状态表示这块内容已经不对了，要重新算。",
    "Stale State 由各引擎 stale detector 输出，参与 recalculation。"),
  t("audit", "审计", "Audit", "QA_TERM", "QUALITY_LAYER",
    "对系统某个层级的检查。",
    "审计是系统检查自己有没有做错的过程。",
    "Audit 出现在 UI / Docs / Text / Version / Vocabulary / Knowledge 等多个层级。"),
  t("founder-trace", "Founder 追踪", "Founder Trace", "QA_TERM", "FOUNDER_LAYER",
    "Founder 视角的请求追踪。",
    "Founder 追踪让创始人看到一条请求经过了哪些引擎。",
    "Founder Trace 仅在 FOUNDER 模式可见。",
    { audienceMode: "FOUNDER", founderLocked: true }),
  t("hybrid-compression", "黑白箱混合压缩", "Hybrid Compression", "COMPRESSION_TERM", "QUALITY_LAYER",
    "把可解释与不可解释信号组合输出。",
    "黑白箱混合压缩把可以解释的结果和无法完全解释的信号一起给你。",
    "Hybrid Compression 输出 explainable + black-box hint，并强制标注信号边界。",
    { commonMisuse: ["把黑箱信号说成确定事实"],
      safetyBoundary: "黑箱信号是不可解释输出，不能被表述为确定事实。" }),

  // ===== I. 货币 / 价值 / 安全词 =====
  t("sequence-currency", "数列货币", "Sequence Currency", "CURRENCY_TERM", "GOVERNANCE_LAYER",
    "Aetherworld 内部价值单位。",
    "数列货币是 Aetherworld 内部用来记录贡献的积分，不是现实货币。",
    "Sequence Currency 是 INTERNAL_ONLY 价值单位，CASH_REDEEMABLE=false、INVESTMENT_ASSET=false。",
    { aliases: ["Aether Credit"],
      relatedTerms: ["internal-value","contribution-score","non-financial-boundary"],
      commonMisuse: ["把数列货币写成可提现的现实货币","把数列货币描述为投资资产"],
      safetyBoundary: "数列货币是产品内部价值单位，不可提现、不是投资资产、不构成法定货币。" }),
  t("internal-value", "内部价值", "Internal Value", "CURRENCY_TERM", "GOVERNANCE_LAYER",
    "系统内部的价值度量。",
    "内部价值是只在 Aetherworld 内部生效的价值。",
    "Internal Value 是数列货币、贡献分等的统一抽象。"),
  t("contribution-score", "贡献分", "Contribution Score", "CURRENCY_TERM", "GOVERNANCE_LAYER",
    "用户在系统中的贡献度。",
    "贡献分记录你对 Aetherworld 的贡献。",
    "Contribution Score 由 value ledger 维护。"),
  t("asset-registry", "资产注册表", "Asset Registry", "CURRENCY_TERM", "GOVERNANCE_LAYER",
    "登记内部资产的表。",
    "资产注册表登记系统内部所有资产。",
    "Asset Registry 维护 virtual asset id / scope / boundary。"),
  t("virtual-asset", "虚拟资产", "Virtual Asset", "CURRENCY_TERM", "GOVERNANCE_LAYER",
    "仅在系统内有效的资产。",
    "虚拟资产是系统内的资产，不能在现实中提现。",
    "Virtual Asset 标记 INTERNAL_ONLY，禁止外部金融化处理。",
    { safetyBoundary: "虚拟资产仅在产品内部有效，不可作为现实金融资产。" }),
  t("non-financial-boundary", "非金融边界", "Non-Financial Boundary", "SAFETY_TERM", "SAFETY_LAYER",
    "明确不属于金融工具的边界。",
    "非金融边界表示这部分内容不属于金融产品。",
    "Non-Financial Boundary 是 currency / asset / world resource 的强制安全标签。"),
  t("internal-only-flag", "INTERNAL_ONLY", "INTERNAL_ONLY", "GOVERNANCE_TERM", "SAFETY_LAYER",
    "仅内部使用的标签。",
    "INTERNAL_ONLY 表示这条内容只在系统里有意义。",
    "INTERNAL_ONLY 是 scope flag，常用于货币、资产、世界资源。"),
  t("cash-redeemable-false", "CASH_REDEEMABLE=false", "CASH_REDEEMABLE=false", "GOVERNANCE_TERM", "SAFETY_LAYER",
    "不可提现标志。",
    "CASH_REDEEMABLE=false 表示这东西不能换成现金。",
    "CASH_REDEEMABLE=false 是数列货币与虚拟资产的硬性标签。"),
  t("investment-asset-false", "INVESTMENT_ASSET=false", "INVESTMENT_ASSET=false", "GOVERNANCE_TERM", "SAFETY_LAYER",
    "不是投资资产标志。",
    "INVESTMENT_ASSET=false 表示这东西不是投资品。",
    "INVESTMENT_ASSET=false 标签禁止把内部价值表述为投资资产。"),

  // ===== J. 九核执行人格词 =====
  t("nine-core-personas", "九核执行人格", "Nine Core Execution Personas", "PERSONA_TERM", "ENGINE_LAYER",
    "系统的九种核心执行人格。",
    "九核执行人格是系统里九个不同性格的执行者，每个负责一类任务。",
    "Nine Core Execution Personas 是 Aetherworld 引擎层的人格抽象层，分担计算法 / 治理 / 表现 / 回验等职责。",
    { relatedTerms: [
        "du-heng-jie","lan-tian-ji","feng-yun-ce","wan-bian",
        "chang-heng-zhe","zhong-duan-zhe","zhi-jie-zhe","ya-xiang-zhe","hui-yan-zhe",
      ] }),
  t("du-heng-jie", "杜衡界", "Du Hengjie", "PERSONA_TERM", "ENGINE_LAYER",
    "边界守护人格。",
    "杜衡界负责守住系统的安全边界。",
    "Du Hengjie 主管 safety boundary / permission guard。"),
  t("lan-tian-ji", "蓝天机", "Lan Tianji", "PERSONA_TERM", "ENGINE_LAYER",
    "结构与设计人格。",
    "蓝天机负责系统的结构与设计。",
    "Lan Tianji 主管 architecture / blueprint / model generation。"),
  t("feng-yun-ce", "风云策", "Feng Yunce", "PERSONA_TERM", "ENGINE_LAYER",
    "策略与风险人格。",
    "风云策负责策略与风险评估。",
    "Feng Yunce 主管 strategy / risk classifier。"),
  t("wan-bian", "万变", "Wan Bian", "PERSONA_TERM", "ENGINE_LAYER",
    "变化与扰动人格。",
    "万变负责处理变化与意外。",
    "Wan Bian 主管 change detection / dynamic update。"),
  t("chang-heng-zhe", "常衡者", "Chang Hengzhe", "PERSONA_TERM", "ENGINE_LAYER",
    "常数与权衡人格。",
    "常衡者负责常数与平衡判断。",
    "Chang Hengzhe 主管 constant universe / weight balance。"),
  t("zhong-duan-zhe", "终端者", "Zhong Duanzhe", "PERSONA_TERM", "ENGINE_LAYER",
    "终端与指令人格。",
    "终端者负责终端、命令、入口。",
    "Zhong Duanzhe 主管 terminal / command parsing。"),
  t("zhi-jie-zhe", "织界者", "Zhi Jiezhe", "PERSONA_TERM", "ENGINE_LAYER",
    "世界编织人格。",
    "织界者负责编织世界。",
    "Zhi Jiezhe 主管 sequence world engine / world generation。"),
  t("ya-xiang-zhe", "压象者", "Ya Xiangzhe", "PERSONA_TERM", "ENGINE_LAYER",
    "压缩与表达人格。",
    "压象者负责把复杂结果压缩成可表达的样子。",
    "Ya Xiangzhe 主管 hybrid compression / output presentation。"),
  t("hui-yan-zhe", "回验者", "Hui Yanzhe", "PERSONA_TERM", "ENGINE_LAYER",
    "回验与质量人格。",
    "回验者负责回验和质量检查。",
    "Hui Yanzhe 主管 validation / software QA。"),

  // ===== K. Founder 元词 =====
  t("founder-mode", "Founder Mode", "Founder Mode", "SUBJECT_MODE_TERM", "FOUNDER_LAYER",
    "Founder 工作模式。",
    "Founder Mode 是创始人在工作时使用的最高权限模式。",
    "Founder Mode 启用 founder.* 命令、founder-only 模块与 Audit 视图。",
    { audienceMode: "FOUNDER", founderLocked: true, maturity: "FOUNDER_LOCKED" }),
  t("demo-real-isolation", "Demo / Real 隔离", "Demo / Real Isolation", "GOVERNANCE_TERM", "SAFETY_LAYER",
    "演示主体与真实主体的隔离。",
    "Demo / Real 隔离保证演示数据不会和真实数据混在一起。",
    "Demo / Real Isolation 由 Subject Mode Resolver + Subject Sequence Firewall 联合执行。",
    { safetyBoundary: "Demo 主体输出不可被当作 Real 主体输出。" }),
];

/* ============ 索引与查询工具 ============ */

export function getAllTerms(): VocabularyTerm[] {
  return VOCABULARY_REGISTRY;
}
export function getTermById(id: string): VocabularyTerm | undefined {
  return VOCABULARY_REGISTRY.find((t) => t.termId === id);
}
export function getTermsByCategory(cat: TermCategoryId): VocabularyTerm[] {
  return VOCABULARY_REGISTRY.filter((t) => t.category === cat);
}
export function getTermsBySystemLayer(layer: TermSystemLayerId): VocabularyTerm[] {
  return VOCABULARY_REGISTRY.filter((t) => t.systemLayer === layer);
}
export function getTermsByAudience(mode: TermAudienceMode): VocabularyTerm[] {
  return VOCABULARY_REGISTRY.filter((t) =>
    mode === "FOUNDER" ? true : (mode === "ADVANCED" ? t.audienceMode !== "FOUNDER" : t.audienceMode === "PUBLIC"),
  );
}
export function searchTerms(keyword: string, audience: TermAudienceMode = "PUBLIC"): VocabularyTerm[] {
  const k = keyword.trim().toLowerCase();
  if (!k) return [];
  const pool = getTermsByAudience(audience);
  return pool.filter((t) => {
    const hay = [
      t.termId, t.chineseTerm, t.englishTerm,
      ...(t.aliases ?? []),
      t.shortDefinition, t.plainDefinition, t.technicalDefinition,
    ].join(" ").toLowerCase();
    return hay.includes(k);
  });
}
export function getCoreCounts() {
  return {
    totalTerms: VOCABULARY_REGISTRY.length,
    activeTerms: VOCABULARY_REGISTRY.filter((t) => t.maturity === "ACTIVE").length,
    founderLockedTerms: VOCABULARY_REGISTRY.filter((t) => t.founderLocked).length,
    deprecatedTerms: VOCABULARY_REGISTRY.filter((t) => t.maturity === "DEPRECATED").length,
  };
}
