import test from 'node:test';
import assert from 'node:assert/strict';
import {createTownGame,dispatchTownAction,verifyTownGame,inspectTownGame,projectTown2_5D,exportTownSave,importTownSave} from '../src/index.mjs';

function placeAt(state,x,y){state.player.x=x;state.player.y=y;return state;}

test('same seed creates deterministic town and zero LLM calls',()=>{const a=createTownGame({seed:'same'}),b=createTownGame({seed:'same'});assert.equal(a.state_root,b.state_root);assert.equal(a.metrics.llmCalls,0);assert.equal(verifyTownGame(a).valid,true);});
test('creates detailed town, households, professions and persistent NPCs',()=>{const s=createTownGame();assert.ok(s.town.buildings.length>=9);assert.ok(s.npcs.length>=18);assert.ok(s.households.some(h=>h.relations.length));assert.equal(s.player.job,'apprentice');});
test('movement changes player position and advances clock',()=>{const s=createTownGame(),r=dispatchTownAction(s,{type:'move',dx:1,dy:0});assert.equal(r.ok,true);assert.notEqual(r.state.player.x,s.player.x);assert.equal(r.state.minute,s.minute+5);});
test('food purchase and eating operate through world location',()=>{let s=placeAt(createTownGame(),3,9);let r=dispatchTownAction(s,{type:'buy',item:'bread'});assert.equal(r.ok,true);const before=r.state.player.hunger;r=dispatchTownAction(r.state,{type:'eat',item:'bread'});assert.equal(r.ok,true);assert.ok(r.state.player.hunger<before);});
test('school learning increases knowledge',()=>{let s=placeAt(createTownGame(),11,5);const before=s.player.knowledge.materials;const r=dispatchTownAction(s,{type:'study',domain:'materials'});assert.equal(r.ok,true);assert.ok(r.state.player.knowledge.materials>before);});
test('job work earns wages at correct workplace',()=>{let s=placeAt(createTownGame({player:{identity:'shopClerk'}}),3,9);const before=s.player.money;const r=dispatchTownAction(s,{type:'work'});assert.equal(r.ok,true);assert.ok(r.state.player.money>before);});
test('materials evolve from clay to porous ceramic through research and manufacturing',()=>{let s=createTownGame({player:{identity:'apprentice',background:'工匠家庭'}});s.player.knowledge.materials=2.2;s.player.skills.materials=1.8;s=placeAt(s,11,5);let r=dispatchTownAction(s,{type:'research'});assert.equal(r.ok,true);s=r.state;s.player.money+=200;s=placeAt(s,9,9);r=dispatchTownAction(s,{type:'buy',item:'clay',count:6});assert.equal(r.ok,true);s=r.state;s=placeAt(s,15,8);r=dispatchTownAction(s,{type:'rent-workshop'});assert.equal(r.ok,true);r=dispatchTownAction(r.state,{type:'craft',recipe:'porousCeramic'});assert.equal(r.ok,true);assert.equal(r.state.inventory?.porousCeramic,undefined);assert.equal(r.state.player.inventory.porousCeramic,1);assert.equal(r.state.technologies['porous-ceramic-filtration'].stage,2);});
test('technology prototype can become a market product and changes history',()=>{let s=createTownGame();s.player.knowledge.materials=3;s.player.skills.materials=2;s.player.money=800;s.player.workshopRented=true;s.player.stallRented=true;s.player.inventory={porousCeramic:4,wood:2};s.technologies['porous-ceramic-filtration'].stage=2;s.player.x=15;s.player.y=8;let r=dispatchTownAction(s,{type:'craft',recipe:'ceramicFilter'});assert.equal(r.ok,true);s=r.state;s.player.x=12;s.player.y=9;r=dispatchTownAction(s,{type:'launch-product'});assert.equal(r.ok,true);assert.equal(r.state.technologies['porous-ceramic-filtration'].stage,4);assert.ok(r.state.history.some(e=>e.code==='PRODUCT_LAUNCHED'));});
test('2.5D projection exposes visible buildings, citizens and depth layers',()=>{const p=projectTown2_5D(createTownGame());assert.equal(p.format,'vsr.town-2.5d-projection.v0.1');assert.ok(p.map.buildings.length);assert.ok(p.npcs.every(n=>Number.isFinite(n.screenLayer)));});
test('save and load preserves authoritative state root',()=>{const s=createTownGame({seed:'save'});const loaded=importTownSave(exportTownSave(s));assert.equal(loaded.state_root,s.state_root);assert.equal(verifyTownGame(loaded).valid,true);});
