export interface ModuleDoc {
  moduleId: string;
  title: string;
  chineseTitle: string;
  plainExplanation: string;
  technicalExplanation: string;
  whenToUse: string[];
  whenNotToUse: string[];
  inputs: string[];
  outputs: string[];
  examplePrompts: string[];
  relatedModules: string[];
  safetyNotes: string[];
  commonMistakes: string[];
  route?: string;
}

const M = (d: ModuleDoc) => d;

export const CORE_MODULE_DOCS: ModuleDoc[] = [
  M({
    moduleId: "free-input",
    title: "Free Input",
    chineseTitle: "自由输入 / 随便问",
    plainExplanation: "用一句自然语言提问，系统会自动路由到合适的引擎。",
    technicalExplanation: "Free Input 解析意图并调用 Omni 调度到 Sequence AI / World / Narrative 等引擎。",
    whenToUse: ["不确定该用哪个引擎时", "新手入门"],
    whenNotToUse: ["已确定要直接调用某个引擎"],
    inputs: ["自然语言问题"],
    outputs: ["结构化结论 / 下一步 / 验证点"],
    examplePrompts: ["我该不该推进这个项目？", "帮我生成一个世界"],
    relatedModules: ["sequence-ai", "omni"],
    safetyNotes: ["结构推演，不替代专业判断。"],
    commonMistakes: ["把模拟当现实", "输入过短缺少上下文"],
    route: "/free-answer",
  }),
  M({
    moduleId: "sequence-ai",
    title: "Sequence AI",
    chineseTitle: "数列人工智能",
    plainExplanation: "用主体数列回答问题，并给出结论、下一步、验证点。",
    technicalExplanation: "Sequence AI 基于 MSL + Constant Universe + Subject Mode 推理。",
    whenToUse: ["需要结构化决策", "需要验证点"],
    whenNotToUse: ["需要医疗 / 法律 / 金融最终建议"],
    inputs: ["问题", "subjectMode"],
    outputs: ["conclusion", "nextActions", "validationPoints", "safetyNotes"],
    examplePrompts: ["用 Full60 评估方案 A 与方案 B"],
    relatedModules: ["msl", "constants-universe"],
    safetyNotes: ["Full60 默认本地。"],
    commonMistakes: ["把结论当唯一答案"],
    route: "/sequence-ai",
  }),
  M({
    moduleId: "subject-mode",
    title: "Subject Mode",
    chineseTitle: "主体模式",
    plainExplanation: "区分 Demo / Light20 / Full60 / Founder。",
    technicalExplanation: "Subject Mode Resolver 决定引擎读取数据深度。",
    whenToUse: ["首次进入系统", "切换演示与真实"],
    whenNotToUse: [],
    inputs: ["选择模式"],
    outputs: ["当前 subjectMode"],
    examplePrompts: [],
    relatedModules: ["sequence-ai", "free-input"],
    safetyNotes: ["Full60 私有；Demo ≠ Real。"],
    commonMistakes: ["把 Demo 输出当真实结论"],
    route: "/subject-mode",
  }),
  M({
    moduleId: "msl",
    title: "MSL",
    chineseTitle: "母体数列语言",
    plainExplanation: "用数列描述世界结构、规则与状态。",
    technicalExplanation: "Mother Sequence Language，用于编译到 world / godot / unity / ial。",
    whenToUse: ["高阶建模", "终端编译"],
    whenNotToUse: ["普通问答"],
    inputs: ["数列"],
    outputs: ["IAL / world / prompt"],
    examplePrompts: ["compile 55555 --to world"],
    relatedModules: ["sequence-terminal", "world-engine"],
    safetyNotes: [],
    commonMistakes: ["把 MSL 当占卜"],
    route: "/msl-terminal",
  }),
  M({
    moduleId: "sequence-terminal",
    title: "Sequence Terminal",
    chineseTitle: "数列终端",
    plainExplanation: "命令行式调用全系统引擎。",
    technicalExplanation: "命令包括 parse, compile, ask, run, model.generate, world.*, ui.*, docs.*。",
    whenToUse: ["高阶", "脚本化操作"],
    whenNotToUse: ["新手第一次"],
    inputs: ["命令"],
    outputs: ["STRUCTURED 输出"],
    examplePrompts: ["help", "parse 55555", "ui.audit", "docs.audit"],
    relatedModules: ["msl", "world-engine"],
    safetyNotes: ["权限分级。"],
    commonMistakes: [],
    route: "/sequence-terminal",
  }),
  M({
    moduleId: "model-generation",
    title: "Model Generation",
    chineseTitle: "模型生成引擎",
    plainExplanation: "把想法转成数据模型 / Schema / Prompt。",
    technicalExplanation: "",
    whenToUse: ["构建产品 / API"],
    whenNotToUse: [],
    inputs: ["需求文字"],
    outputs: ["模型 JSON"],
    examplePrompts: [],
    relatedModules: ["prompt-forge", "code-generation"],
    safetyNotes: [],
    commonMistakes: [],
    route: "/model-generation",
  }),
  M({
    moduleId: "world-engine",
    title: "World Engine",
    chineseTitle: "世界引擎",
    plainExplanation: "用数列生成虚拟世界。",
    technicalExplanation: "v0.1-v0.6 含 Generation / Simulation / Growth / Society / Civilization / Presentation。",
    whenToUse: ["创作", "教学模拟"],
    whenNotToUse: ["现实预测"],
    inputs: ["数列 / 设定"],
    outputs: ["world snapshot"],
    examplePrompts: ["world.generate 55555"],
    relatedModules: ["world-simulation", "world-growth"],
    safetyNotes: ["虚拟世界 ≠ 现实。"],
    commonMistakes: ["当成现实预测"],
    route: "/world-engine",
  }),
  M({
    moduleId: "world-simulation",
    title: "World Simulation",
    chineseTitle: "世界模拟",
    plainExplanation: "推进 tick 演化世界状态。",
    technicalExplanation: "",
    whenToUse: ["跑模拟"],
    whenNotToUse: ["现实预测"],
    inputs: ["world snapshot", "ticks"],
    outputs: ["events"],
    examplePrompts: [],
    relatedModules: ["world-engine"],
    safetyNotes: ["虚拟世界 ≠ 现实。"],
    commonMistakes: [],
    route: "/world-simulation",
  }),
  M({
    moduleId: "world-growth",
    title: "World Growth",
    chineseTitle: "世界生长",
    plainExplanation: "让世界要素自发扩展。",
    technicalExplanation: "",
    whenToUse: ["扩展世界"],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: [],
    relatedModules: ["world-engine"],
    safetyNotes: [],
    commonMistakes: [],
    route: "/world-growth",
  }),
  M({
    moduleId: "world-society",
    title: "World Society",
    chineseTitle: "世界社会",
    plainExplanation: "生成派系、信仰、制度。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: [],
    relatedModules: [],
    safetyNotes: [],
    commonMistakes: [],
    route: "/world-society",
  }),
  M({
    moduleId: "civilization-evolution",
    title: "Civilization Evolution",
    chineseTitle: "文明演化",
    plainExplanation: "文明阶段、历史线、关键事件。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: [],
    relatedModules: [],
    safetyNotes: [],
    commonMistakes: [],
    route: "/world-timelines",
  }),
  M({
    moduleId: "world-presentation",
    title: "World Presentation",
    chineseTitle: "世界表现层",
    plainExplanation: "把世界导出为 Godot / Unity / Three.js 可消费数据。",
    technicalExplanation: "",
    whenToUse: ["导出渲染"],
    whenNotToUse: [],
    inputs: [],
    outputs: ["JSON"],
    examplePrompts: ["world.export --target godot"],
    relatedModules: ["world-engine"],
    safetyNotes: [],
    commonMistakes: [],
    route: "/world-presentation",
  }),
  M({
    moduleId: "narrative-engine",
    title: "Narrative Engine",
    chineseTitle: "剧情引擎",
    plainExplanation: "生成剧情线、章节、台本。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: ["narrative.generate"],
    relatedModules: [],
    safetyNotes: [],
    commonMistakes: [],
    route: "/narrative-engine",
  }),
  M({
    moduleId: "vocal-engine",
    title: "Vocal Engine",
    chineseTitle: "声乐引擎",
    plainExplanation: "生成 Suno / 音乐 Prompt。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: ["vocal.prompt"],
    relatedModules: [],
    safetyNotes: [],
    commonMistakes: [],
    route: "/vocal-engine",
  }),
  M({
    moduleId: "translation-engine",
    title: "Translation Engine",
    chineseTitle: "翻译引擎",
    plainExplanation: "概念 / 内容多语言翻译。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: ['translate "万物本身计算法" --to en'],
    relatedModules: [],
    safetyNotes: [],
    commonMistakes: [],
    route: "/translation-engine",
  }),
  M({
    moduleId: "prompt-forge",
    title: "Prompt Forge",
    chineseTitle: "Prompt 工坊",
    plainExplanation: "生成工程化 Prompt。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: ["prompt.generate --target lovable"],
    relatedModules: [],
    safetyNotes: [],
    commonMistakes: [],
    route: "/prompt-forge",
  }),
  M({
    moduleId: "world-knowledge",
    title: "World Knowledge",
    chineseTitle: "世界知识引擎",
    plainExplanation: "管理世界与系统知识。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: [],
    relatedModules: [],
    safetyNotes: [],
    commonMistakes: [],
    route: "/world-knowledge",
  }),
  M({
    moduleId: "constants-universe",
    title: "Constant Universe",
    chineseTitle: "常数宇宙",
    plainExplanation: "系统常数注册、版本、审计。",
    technicalExplanation: "v0.2，与所有引擎对齐。",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: [],
    relatedModules: [],
    safetyNotes: ["不是现实宇宙物理定律。"],
    commonMistakes: ["把系统常数当物理常数"],
    route: "/constants-universe",
  }),
  M({
    moduleId: "system-constitution",
    title: "System Constitution",
    chineseTitle: "系统宪法",
    plainExplanation: "最高治理层。",
    technicalExplanation: "管控主权、权限、调用、边界。",
    whenToUse: ["治理"],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: [],
    relatedModules: [],
    safetyNotes: ["Founder Locked 条款不可关。"],
    commonMistakes: [],
    route: "/system-constitution",
  }),
  M({
    moduleId: "sequence-currency",
    title: "Sequence Currency",
    chineseTitle: "数列货币",
    plainExplanation: "内部积分 / 贡献 / 虚拟资源系统。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: ["金融提现 / 交易 / 投资"],
    inputs: [],
    outputs: [],
    examplePrompts: [],
    relatedModules: [],
    safetyNotes: ["不是现实货币，不可提现。"],
    commonMistakes: ["以为可提现"],
    route: "/sequence-currency",
  }),
  M({
    moduleId: "hybrid-compression",
    title: "Hybrid Compression",
    chineseTitle: "黑白箱混合压缩",
    plainExplanation: "把长输出压缩为可读结构。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: [],
    relatedModules: [],
    safetyNotes: ["黑箱信号 ≠ 事实。"],
    commonMistakes: [],
    route: "/hybrid-compression",
  }),
  M({
    moduleId: "ui-update",
    title: "UI Update Engine",
    chineseTitle: "UI 界面更新引擎",
    plainExplanation: "自动维护 Quick Start / 侧边栏 / 入门流程。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: ["ui.audit"],
    relatedModules: [],
    safetyNotes: [],
    commonMistakes: [],
    route: "/ui-update-engine",
  }),
  M({
    moduleId: "software-qa",
    title: "Software QA",
    chineseTitle: "软件 QA",
    plainExplanation: "检查模块完整性、安全边界、误用风险。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: ["qa.run"],
    relatedModules: [],
    safetyNotes: [],
    commonMistakes: [],
    route: "/software-qa",
  }),
  M({
    moduleId: "recalculation",
    title: "Recalculation",
    chineseTitle: "重新计算",
    plainExplanation: "当上游变化时把下游标记 stale 并重算。",
    technicalExplanation: "",
    whenToUse: [],
    whenNotToUse: [],
    inputs: [],
    outputs: [],
    examplePrompts: ["recalc.all"],
    relatedModules: [],
    safetyNotes: [],
    commonMistakes: [],
    route: "/recalculation",
  }),
];

export function listModuleDocs(): ModuleDoc[] {
  return [...CORE_MODULE_DOCS];
}

export function getModuleDoc(id: string): ModuleDoc | undefined {
  return CORE_MODULE_DOCS.find((m) => m.moduleId === id);
}

export function searchModuleDocs(q: string): ModuleDoc[] {
  const s = q.toLowerCase().trim();
  if (!s) return [];
  return CORE_MODULE_DOCS.filter(
    (m) => m.title.toLowerCase().includes(s) || m.chineseTitle.includes(s) || m.moduleId.includes(s)
  );
}
