export const CONTENT_DENSITY_LEVELS = {
  DESKTOP_DETAIL: "DESKTOP_DETAIL",
  TABLET_BALANCED: "TABLET_BALANCED",
  MOBILE_SIMPLE: "MOBILE_SIMPLE",
  MOBILE_MINIMAL: "MOBILE_MINIMAL",
} as const;

export type ContentDensityLevel = keyof typeof CONTENT_DENSITY_LEVELS;
